import pyrosetta.rosetta.numeric
from typing import overload

def get_orientation(a: pyrosetta.rosetta.numeric.xyzVector_double_t, b: pyrosetta.rosetta.numeric.xyzVector_double_t, aphi: int, theta: int, dist: float) -> None: ...
def get_overlap(ra: float, rb: float, dist: float, olp: int) -> None: ...
@overload
def input_sasa_dats() -> None: ...
@overload
def input_sasa_dats() -> void: ...
