import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.io.silent
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.file
from typing import overload

class ExtendedPoseInputStream(PoseInputStream):
    @overload
    def __init__(self, sequence: str, ntimes: int) -> None: ...
    @overload
    def __init__(self, arg0: ExtendedPoseInputStream) -> None: ...
    @overload
    def __init__(self, arg0: ExtendedPoseInputStream) -> None: ...
    def assign(self) -> ExtendedPoseInputStream: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore, constbool) -> void: ...
    @overload
    def fill_pose(self) -> None: ...
    @overload
    def fill_pose(self, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constbool) -> void: ...
    def get_last_pose_descriptor_string(self) -> str: ...
    @overload
    def has_another_pose(self) -> bool: ...
    @overload
    def has_another_pose(self) -> bool: ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self) -> void: ...

class LazySilentFilePoseInputStream(PoseInputStream):
    @overload
    def __init__(self, fns: pyrosetta.rosetta.utility.vector1_utility_file_FileName) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LazySilentFilePoseInputStream) -> None: ...
    @overload
    def __init__(self, arg0: LazySilentFilePoseInputStream) -> None: ...
    def assign(self) -> LazySilentFilePoseInputStream: ...
    def filenames(self) -> pyrosetta.rosetta.utility.vector1_utility_file_FileName: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore, constbool) -> void: ...
    @overload
    def fill_pose(self) -> None: ...
    @overload
    def fill_pose(self, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constbool) -> void: ...
    def get_last_pose_descriptor_string(self) -> str: ...
    @overload
    def has_another_pose(self) -> bool: ...
    @overload
    def has_another_pose(self) -> bool: ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self) -> void: ...

class MetaPoseInputStream(PoseInputStream):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MetaPoseInputStream) -> None: ...
    @overload
    def __init__(self, arg0: MetaPoseInputStream) -> None: ...
    @overload
    def add_pose_input_stream(self, input: PoseInputStream) -> None: ...
    @overload
    def add_pose_input_stream(self, classstd) -> void: ...
    def assign(self) -> MetaPoseInputStream: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore, constbool) -> void: ...
    @overload
    def fill_pose(self) -> None: ...
    @overload
    def fill_pose(self, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constbool) -> void: ...
    def get_input_streams(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_import_pose_pose_stream_PoseInputStream_t: ...
    def get_last_pose_descriptor_string(self) -> str: ...
    @overload
    def has_another_pose(self) -> bool: ...
    @overload
    def has_another_pose(self) -> bool: ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self) -> void: ...

class PDBPoseInputStream(PoseInputStream):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, fns: pyrosetta.rosetta.utility.vector1_utility_file_FileName) -> None: ...
    @overload
    def __init__(self, fn: pyrosetta.rosetta.utility.file.FileName) -> None: ...
    @overload
    def __init__(self, fns: pyrosetta.rosetta.utility.vector1_utility_file_FileName, list_fns: pyrosetta.rosetta.utility.vector1_utility_file_FileName) -> None: ...
    @overload
    def __init__(self, arg0: PDBPoseInputStream) -> None: ...
    @overload
    def __init__(self, arg0: PDBPoseInputStream) -> None: ...
    @overload
    def add_list_filenames(self, list_fns: pyrosetta.rosetta.utility.vector1_utility_file_FileName) -> None: ...
    @overload
    def add_list_filenames(self, classutility) -> void: ...
    def assign(self) -> PDBPoseInputStream: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore, constbool) -> void: ...
    @overload
    def fill_pose(self) -> None: ...
    @overload
    def fill_pose(self, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constbool) -> void: ...
    def get_all_poses(self, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t: ...
    def get_filenames(self) -> pyrosetta.rosetta.utility.vector1_utility_file_FileName: ...
    def get_last_pose_descriptor_string(self) -> str: ...
    @overload
    def has_another_pose(self) -> bool: ...
    @overload
    def has_another_pose(self) -> bool: ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self) -> void: ...
    @overload
    def set_filenames(self, filenames: pyrosetta.rosetta.utility.vector1_utility_file_FileName) -> None: ...
    @overload
    def set_filenames(self, classutility) -> void: ...

class PoseInputStream:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PoseInputStream) -> None: ...
    def assign(self) -> PoseInputStream: ...
    @overload
    def fill_pose(self) -> None: ...
    @overload
    def fill_pose(self, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore, constbool) -> void: ...
    @overload
    def fill_pose(self) -> None: ...
    @overload
    def fill_pose(self, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constbool) -> void: ...
    def get_all_poses(self, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t: ...
    def get_last_pose_descriptor_string(self) -> str: ...
    @overload
    def has_another_pose(self) -> bool: ...
    @overload
    def has_another_pose(self) -> bool: ...
    @overload
    def preprocess_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def preprocess_pose(self, classcore) -> void: ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self) -> void: ...

class SilentFilePoseInputStream(PoseInputStream):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, fns: pyrosetta.rosetta.utility.vector1_utility_file_FileName) -> None: ...
    @overload
    def __init__(self, fn: str) -> None: ...
    @overload
    def __init__(self, fns: pyrosetta.rosetta.utility.vector1_utility_file_FileName, order_by_energy: bool) -> None: ...
    @overload
    def __init__(self, fns: pyrosetta.rosetta.utility.vector1_utility_file_FileName, energy_cut: float) -> None: ...
    @overload
    def __init__(self, fns: pyrosetta.rosetta.utility.vector1_utility_file_FileName, input_tags: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def __init__(self, fns: pyrosetta.rosetta.utility.vector1_utility_file_FileName, input_tags: pyrosetta.rosetta.utility.vector1_std_string, energy_cut: float) -> None: ...
    @overload
    def __init__(self, arg0: SilentFilePoseInputStream) -> None: ...
    @overload
    def __init__(self, arg0: SilentFilePoseInputStream) -> None: ...
    def assign(self) -> SilentFilePoseInputStream: ...
    @overload
    def energy_cut(self) -> float: ...
    @overload
    def energy_cut(self) -> double: ...
    @overload
    def filenames(self, filenames: pyrosetta.rosetta.utility.vector1_utility_file_FileName) -> None: ...
    @overload
    def filenames(self, constclassutility) -> void: ...
    @overload
    def filenames(self) -> pyrosetta.rosetta.utility.vector1_utility_file_FileName: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore, constbool) -> void: ...
    @overload
    def fill_pose(self) -> None: ...
    @overload
    def fill_pose(self, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constbool) -> void: ...
    def get_last_pose_descriptor_string(self) -> str: ...
    @overload
    def has_another_pose(self) -> bool: ...
    @overload
    def has_another_pose(self) -> bool: ...
    def next_struct(self) -> pyrosetta.rosetta.core.io.silent.SilentStruct: ...
    @overload
    def renumber_decoys(self, setting: bool) -> None: ...
    @overload
    def renumber_decoys(self, constbool) -> void: ...
    @overload
    def renumber_decoys(self) -> bool: ...
    @overload
    def renumber_decoys(self) -> bool: ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self) -> void: ...
    def set_order_by_energy(self, setting: bool) -> None: ...
    def set_record_source(self, setting: bool) -> None: ...
    @overload
    def set_silent_file_data(self, sfd: pyrosetta.rosetta.core.io.silent.SilentFileData) -> None: ...
    @overload
    def set_silent_file_data(self, classstd) -> void: ...
    def silent_file_data(self) -> pyrosetta.rosetta.core.io.silent.SilentFileData: ...
    @overload
    def tags(self, tags: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def tags(self, constclassutility) -> void: ...
    @overload
    def tags(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...

@overload
def streams_from_cmd_line(do_renumber_decoys: bool) -> MetaPoseInputStream: ...
@overload
def streams_from_cmd_line() -> MetaPoseInputStream: ...
