import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import typing
from . import metrics as metrics
from typing import Any, overload

class DEERDataCache(pyrosetta.rosetta.basic.datacache.CacheableData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DEERDataCache) -> None: ...
    @overload
    def __init__(self, arg0: DEERDataCache) -> None: ...
    @overload
    def append(self, data) -> None: ...
    @overload
    def append(self, constclassstd) -> void: ...
    @overload
    def append(self, data, i: int) -> None: ...
    def assign(self) -> DEERDataCache: ...
    def at(self, *args, **kwargs): ...
    def clone(self) -> pyrosetta.rosetta.basic.datacache.CacheableData: ...
    def delete_data(self, i: int) -> None: ...
    def edge(self, rsd1: int, rsd2: int) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    @overload
    def f1_force(self, res: int, vec: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def f1_force(self, res: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def f2_force(self, res: int, vec: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def f2_force(self, res: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def fetch_and_organize_data(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def fetch_and_organize_data(self, constclasscore) -> void: ...
    def has_data(self, i: int) -> bool: ...
    def has_f1_force(self, res: int) -> bool: ...
    def has_f2_force(self, res: int) -> bool: ...
    def indices(self) -> pyrosetta.rosetta.std.set_unsigned_long_t: ...
    def label_types(self) -> pyrosetta.rosetta.std.set_std_string_t: ...
    def labeled_residues(self) -> pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_std_string_t: ...
    def labels(self) -> pyrosetta.rosetta.utility.vector1_core_scoring_epr_deer_EPRSpinLabel: ...
    @overload
    def push_back(self, data) -> None: ...
    @overload
    def push_back(self, constclassstd) -> void: ...
    @overload
    def set_labels(self, labels: pyrosetta.rosetta.utility.vector1_core_scoring_epr_deer_EPRSpinLabel) -> None: ...
    @overload
    def set_labels(self, constclassutility) -> void: ...
    @overload
    def set_sl_weights(self, weights: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_sl_weights(self, constclassutility) -> void: ...
    @overload
    def set_up_residues(self) -> None: ...
    @overload
    def set_up_residues(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def sl_weights(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    def __getitem__(self, index): ...

class DEERIO:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DEERIO) -> None: ...
    def generate_data(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.map_unsigned_long_std_shared_ptr_core_scoring_epr_deer_metrics_DEERData_t_std_allocator_std_pair_const_unsigned_long_std_shared_ptr_core_scoring_epr_deer_metrics_DEERData_t: ...
    @overload
    def parse_bounds_lines(self, bounds_lines: pyrosetta.rosetta.utility.vector1_utility_vector1_std_string_t, bounds_data) -> None: ...
    @overload
    def parse_bounds_lines(self, constclassutility, classstd) -> void: ...
    def parse_data(self, *args, **kwargs): ...
    @overload
    def parse_decay_info_lines(self, info_lines: pyrosetta.rosetta.utility.vector1_utility_vector1_std_string_t, data) -> None: ...
    @overload
    def parse_decay_info_lines(self, constclassutility, classstd) -> void: ...
    @overload
    def parse_decay_lines(self, decay_lines: pyrosetta.rosetta.utility.vector1_utility_vector1_std_string_t, data) -> None: ...
    @overload
    def parse_decay_lines(self, constclassutility, classstd) -> void: ...
    def parse_desc_lines(self, pose: pyrosetta.rosetta.core.pose.Pose, desc_lines: pyrosetta.rosetta.utility.vector1_utility_vector1_std_string_t) -> pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_std_string_t: ...
    def parse_dist_datatype(self, *args, **kwargs): ...
    def parse_dist_info_lines(self, *args, **kwargs): ...
    @overload
    def parse_dist_lines(self, dist_lines: pyrosetta.rosetta.utility.vector1_utility_vector1_std_string_t, data) -> None: ...
    @overload
    def parse_dist_lines(self, constclassutility, classstd) -> void: ...
    def split_line(self, line: str) -> pyrosetta.rosetta.utility.vector1_std_string: ...

class EPRSpinLabel:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: EPRSpinLabel) -> None: ...
    def assign(self) -> EPRSpinLabel: ...
    def at(self, res: tuple[int, str]) -> pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t: ...
    @overload
    def calc_sl_for_res(self, res: int, pose: pyrosetta.rosetta.core.pose.Pose, sl_vec: pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t) -> pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t: ...
    @overload
    def calc_sl_for_res(self, res: int, pose: pyrosetta.rosetta.core.pose.Pose, sl_vec: pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t, skip_clash_eval: bool) -> pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t: ...
    @overload
    def calc_sl_for_res(self, res: int, pose: pyrosetta.rosetta.core.pose.Pose, sl_vec: pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t, skip_clash_eval: bool, min_rad: float) -> pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t: ...
    @overload
    def cutoff(self) -> float: ...
    @overload
    def cutoff(self) -> double: ...
    @overload
    def histogram(self, residues: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_std_string_t, bins_per_a: int) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    @overload
    def histogram(self, residues: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_std_string_t, bins_per_a: int, mod: int) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    @overload
    def histogram(self, residues: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_std_string_t, bins_per_a: int, mod: int, stdev: float) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    @overload
    def histogram(self, residues: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_std_string_t, bins_per_a: int, mod: int, stdev: float, dist_ids: pyrosetta.rosetta.std.map_unsigned_long_double) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    @overload
    def histogram(self, binsperangstrom) -> Any: ...
    @overload
    def histogram(self, res1_coords: pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t, res2_coords: pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t, bins_per_a: int) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    @overload
    def histogram(self, res1_coords: pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t, res2_coords: pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t, bins_per_a: int, mod: int) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    @overload
    def histogram(self, res1_coords: pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t, res2_coords: pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t, bins_per_a: int, mod: int, stdev: float) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    @overload
    def histogram(self, res1_coords: pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t, res2_coords: pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t, bins_per_a: int, mod: int, stdev: float, dist_ids: pyrosetta.rosetta.std.map_unsigned_long_double) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    @overload
    def histogram(self, res1: tuple[int, str], res2: tuple[int, str], bins_per_a: int) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    @overload
    def histogram(self, res1: tuple[int, str], res2: tuple[int, str], bins_per_a: int, mod: int) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    @overload
    def histogram(self, res1: tuple[int, str], res2: tuple[int, str], bins_per_a: int, mod: int, stdev: float) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    @overload
    def histogram(self, res1: tuple[int, str], res2: tuple[int, str], bins_per_a: int, mod: int, stdev: float, dist_ids: pyrosetta.rosetta.std.map_unsigned_long_double) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    @overload
    def histogram(self, binsperangstrom) -> Any: ...
    @overload
    def init_vdw(self) -> None: ...
    @overload
    def init_vdw(self) -> void: ...
    @overload
    def label(self, res_label: tuple[int, str], pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def label(self, res_label: tuple[int, str], pose: pyrosetta.rosetta.core.pose.Pose, skip_clash_eval: bool) -> None: ...
    def label_everything(self, pose: pyrosetta.rosetta.core.pose.Pose, residues: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_std_string_t, skip_clash_eval: bool) -> None: ...
    def load_custom_electrons(self, all_coords: pyrosetta.rosetta.std.map_unsigned_long_utility_vector1_std_pair_numeric_xyzVector_double_double_t_std_allocator_std_pair_const_unsigned_long_utility_vector1_std_pair_numeric_xyzVector_double_double_t) -> None: ...
    def normalize(self, sim_map: pyrosetta.rosetta.std.map_unsigned_long_double) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    def read_db_file(self, name: str) -> pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t: ...
    def weight(self, res1: int, clash_xyz: pyrosetta.rosetta.numeric.xyzVector_double_t, w: float, pose: pyrosetta.rosetta.core.pose.Pose, rad: float) -> float: ...
    def __getitem__(self, res: tuple[int, str]) -> pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t: ...

class Simulated4PDEERTrace:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Simulated4PDEERTrace) -> None: ...
    @overload
    def __init__(self, deer_trace: pyrosetta.rosetta.utility.vector1_double, deer_trace_intra: pyrosetta.rosetta.utility.vector1_double, time_pts: pyrosetta.rosetta.utility.vector1_double, depth: float, slope: float, dim: float) -> None: ...
    def assign(self, rhs: Simulated4PDEERTrace) -> Simulated4PDEERTrace: ...
    @overload
    def deer_trace(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def deer_trace(self, val: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def deer_trace(self, constclassutility) -> void: ...
    @overload
    def deer_trace_intra(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def deer_trace_intra(self, val: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def deer_trace_intra(self, constclassutility) -> void: ...
    @overload
    def depth(self) -> float: ...
    @overload
    def depth(self) -> double: ...
    @overload
    def depth(self, val: float) -> None: ...
    @overload
    def dim(self) -> float: ...
    @overload
    def dim(self) -> double: ...
    @overload
    def dim(self, val: float) -> None: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def slope(self) -> float: ...
    @overload
    def slope(self) -> double: ...
    @overload
    def slope(self, val: float) -> None: ...
    @overload
    def time_pts(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def time_pts(self, val: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def time_pts(self, constclassutility) -> void: ...
    def __getitem__(self, i: int) -> tuple[float, float, float]: ...
    def __iter__(self) -> typing.Iterator[tuple[float, float, float]]: ...

class Simulated4PDEERTraceFactory:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, exp_trace: pyrosetta.rosetta.utility.vector1_double, time_pts: pyrosetta.rosetta.utility.vector1_double, bckg_type: str, bins_per_a: int) -> None: ...
    @overload
    def __init__(self, exp_trace: pyrosetta.rosetta.utility.vector1_double, time_pts: pyrosetta.rosetta.utility.vector1_double, bckg_type: str, bins_per_a: int, max_dist: int) -> None: ...
    @overload
    def __init__(self, exp_trace: pyrosetta.rosetta.utility.vector1_double, time_pts: pyrosetta.rosetta.utility.vector1_double, bckg_type: str, bins_per_a: int, max_dist: int, n_bins: int) -> None: ...
    @overload
    def __init__(self, arg0: Simulated4PDEERTraceFactory) -> None: ...
    def append_data_and_recalculate(self, trace_datum: float, time_point: float) -> None: ...
    def assign(self) -> Simulated4PDEERTraceFactory: ...
    @overload
    def bckg_type(self) -> str: ...
    @overload
    def bckg_type(self, val: str) -> None: ...
    @overload
    def bckg_type(self, conststd) -> void: ...
    @overload
    def bins_per_a(self) -> int: ...
    @overload
    def bins_per_a(self) -> unsignedlong: ...
    @overload
    def bins_per_a(self, val: int) -> None: ...
    @overload
    def depth(self) -> float: ...
    @overload
    def depth(self) -> double: ...
    @overload
    def dim(self) -> float: ...
    @overload
    def dim(self) -> double: ...
    @overload
    def initial_search(self, deer_trace: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def initial_search(self, constclassutility) -> void: ...
    @overload
    def initialize_kernel(self, time_pts: pyrosetta.rosetta.utility.vector1_double, bins_per_a: int) -> pyrosetta.rosetta.numeric.MathMatrix_double_t: ...
    @overload
    def initialize_kernel(self, time_pts: pyrosetta.rosetta.utility.vector1_double, bins_per_a: int, max_dist: int) -> pyrosetta.rosetta.numeric.MathMatrix_double_t: ...
    @overload
    def initialize_kernel(self, time_pts: pyrosetta.rosetta.utility.vector1_double, bins_per_a: int, max_dist: int, n_bins: int) -> pyrosetta.rosetta.numeric.MathMatrix_double_t: ...
    def kernel_mult(self, distr: pyrosetta.rosetta.std.map_unsigned_long_double) -> pyrosetta.rosetta.utility.vector1_double: ...
    def opt_bckg(self, deer_trace: pyrosetta.rosetta.utility.vector1_double) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self) -> void: ...
    @overload
    def slope(self) -> float: ...
    @overload
    def slope(self) -> double: ...
    @overload
    def time_pts(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def time_pts(self, val: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def time_pts(self, constclassutility) -> void: ...
    @overload
    def trace(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def trace(self, val: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def trace(self, constclassutility) -> void: ...
    def trace_from_distr(self, distr: pyrosetta.rosetta.std.map_unsigned_long_double) -> Simulated4PDEERTrace: ...

@overload
def add_bckg(sim_trace: pyrosetta.rosetta.utility.vector1_double, time_pts: pyrosetta.rosetta.utility.vector1_double, depth: float, slope: float, dim: float) -> pyrosetta.rosetta.utility.vector1_double: ...
@overload
def add_bckg(sim_trace: pyrosetta.rosetta.utility.vector1_double, time_pts: pyrosetta.rosetta.utility.vector1_double, depth: float, slope: float, dim: float, thru_sigmoid: bool) -> pyrosetta.rosetta.utility.vector1_double: ...
def gauss(x: float, avg: float, stdev: float) -> float: ...
def ln(q: float) -> float: ...
@overload
def logit(x: float) -> float: ...
@overload
def logit(x: float, lo: float) -> float: ...
@overload
def logit(x: float, lo: float, hi: float) -> float: ...
def min_max(histr1: pyrosetta.rosetta.std.map_unsigned_long_double, histr2: pyrosetta.rosetta.std.map_unsigned_long_double) -> tuple[int, int]: ...
def minimize_sumsq(par: float, m_dat: int, data: capsule, fvec: float) -> None: ...
def minimize_sumsq_nodim(par: float, m_dat: int, data: capsule, fvec: float) -> None: ...
def probit(x: float) -> float: ...
def sigmoid(x: float, min: float, max: float) -> float: ...
def unpack(data: capsule, time_pts: pyrosetta.rosetta.utility.vector1_double, exp_trace: pyrosetta.rosetta.utility.vector1_double, sim_trace: pyrosetta.rosetta.utility.vector1_double) -> None: ...
