import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.numeric.geometry
import pyrosetta.rosetta.numeric.geometry.hashing
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.protocols.rosetta_scripts
import pyrosetta.rosetta.protocols.toolbox.match_enzdes_util
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from . import downstream as downstream, output as output, upstream as upstream
from typing import ClassVar, overload

C_ALA: ProbeRadius
C_CAR: ProbeRadius
H_ALA: ProbeRadius
H_ARO: ProbeRadius
NIT: ProbeRadius
OXY: ProbeRadius
SULPH: ProbeRadius
ZERO: ProbeRadius
n_probe_radii: ProbeRadius

class AddAllPositionsMPM(MatchPositionModifier):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AddAllPositionsMPM) -> None: ...
    @overload
    def __init__(self, arg0: AddAllPositionsMPM) -> None: ...
    def assign(self) -> AddAllPositionsMPM: ...
    def modified_match_positions(self, original_positions: pyrosetta.rosetta.utility.vector1_unsigned_long, match_pose: pyrosetta.rosetta.core.pose.Pose, mtask) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...

class BfactorMPM(MatchPositionModifier):
    @overload
    def __init__(self, input_tokens: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def __init__(self, arg0: BfactorMPM) -> None: ...
    @overload
    def __init__(self, arg0: BfactorMPM) -> None: ...
    def assign(self) -> BfactorMPM: ...
    def get_ca_bfactors(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_double: ...
    def modified_match_positions(self, original_positions: pyrosetta.rosetta.utility.vector1_unsigned_long, match_pose: pyrosetta.rosetta.core.pose.Pose, mtask) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...

class Bool3DGrid:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Bool3DGrid) -> None: ...
    def actual_bb(self) -> pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t: ...
    @overload
    def and_with(self, other: Bool3DGrid) -> None: ...
    @overload
    def and_with(self, constclassprotocols) -> void: ...
    def assign(self) -> Bool3DGrid: ...
    def bin_center(self, bin: pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_3UL_t) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def bin_extrema(self, bin: pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_3UL_t) -> pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t: ...
    @overload
    def bin_width(self) -> float: ...
    @overload
    def bin_width(self) -> double: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    def create_grid_for_bb(self, bb: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t) -> Bool3DGrid: ...
    def create_grid_for_sphere(self, center: pyrosetta.rosetta.numeric.xyzVector_double_t, radius: float) -> Bool3DGrid: ...
    def dimsizes(self) -> pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_3UL_t: ...
    @overload
    def occupied(self) -> bool: ...
    @overload
    def occupied(self, constclassnumeric) -> bool: ...
    @overload
    def occupied(self, bin: pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_3UL_t) -> bool: ...
    @overload
    def or_by_box_liberal(self, bb: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t) -> None: ...
    @overload
    def or_by_box_liberal(self, constclassnumeric) -> void: ...
    @overload
    def or_by_sphere_conservative(self, center: pyrosetta.rosetta.numeric.xyzVector_double_t, radius: float) -> None: ...
    @overload
    def or_by_sphere_conservative(self, constclassnumeric, double) -> void: ...
    @overload
    def or_by_sphere_liberal(self, center: pyrosetta.rosetta.numeric.xyzVector_double_t, radius: float) -> None: ...
    @overload
    def or_by_sphere_liberal(self, constclassnumeric, double) -> void: ...
    def or_by_spheres_conservative(self, spheres: pyrosetta.rosetta.utility.vector1_std_pair_numeric_xyzVector_double_double_t) -> None: ...
    @overload
    def or_with(self, other: Bool3DGrid) -> None: ...
    @overload
    def or_with(self, constclassprotocols) -> void: ...
    @overload
    def set_bin_width(self, width: float) -> None: ...
    @overload
    def set_bin_width(self, double) -> void: ...
    @overload
    def set_bounding_box(self, bb: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t) -> None: ...
    @overload
    def set_bounding_box(self, constclassnumeric) -> void: ...
    def set_value_for_bin(self, bin: pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_3UL_t, setting: bool) -> None: ...
    @overload
    def subtract(self, other: Bool3DGrid) -> None: ...
    @overload
    def subtract(self, constclassprotocols) -> void: ...

class Bool3DGridKinemageWriter:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Bool3DGridKinemageWriter) -> None: ...
    def assign(self) -> Bool3DGridKinemageWriter: ...
    @overload
    def set_empty_voxel_color(self, empty_voxel_color_: str) -> None: ...
    @overload
    def set_empty_voxel_color(self, conststd) -> void: ...
    @overload
    def set_facet_alpha(self, facet_alpha: float) -> None: ...
    @overload
    def set_facet_alpha(self, double) -> void: ...
    @overload
    def set_facet_color(self, facet_color: str) -> None: ...
    @overload
    def set_facet_color(self, conststd) -> void: ...
    @overload
    def set_facet_master(self, facet_master: str) -> None: ...
    @overload
    def set_facet_master(self, conststd) -> void: ...
    @overload
    def set_line_color(self, line_color: str) -> None: ...
    @overload
    def set_line_color(self, conststd) -> void: ...
    @overload
    def set_master(self, master: str) -> None: ...
    @overload
    def set_master(self, conststd) -> void: ...
    @overload
    def set_shrink_factor(self, shrink_factor: float) -> None: ...
    @overload
    def set_shrink_factor(self, double) -> void: ...
    @overload
    def set_skip_completely_buried_positions(self, skip_completely_buried_positions: bool) -> None: ...
    @overload
    def set_skip_completely_buried_positions(self, bool) -> void: ...
    @overload
    def set_transparent_facets(self, transparent_facets: bool) -> None: ...
    @overload
    def set_transparent_facets(self, bool) -> void: ...
    @overload
    def set_unselectable(self, unselectable: bool) -> None: ...
    @overload
    def set_unselectable(self, bool) -> void: ...
    @overload
    def set_write_empty_voxels(self, write_empty_voxels_: bool) -> None: ...
    @overload
    def set_write_empty_voxels(self, bool) -> void: ...
    @overload
    def set_write_facets(self, write_facets: bool) -> None: ...
    @overload
    def set_write_facets(self, bool) -> void: ...
    def write_grid_to_file(self, fname: str, group_name: str, grid: Bool3DGrid) -> None: ...
    @overload
    def write_grid_to_kinemage(self, ostr: pyrosetta.rosetta.std.ostream, group_name: str, grid: Bool3DGrid) -> None: ...
    @overload
    def write_grid_to_kinemage(self, std, conststd, constclassprotocols) -> void: ...

class BumpGrid:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: BumpGrid) -> None: ...
    @overload
    def and_with(self) -> None: ...
    @overload
    def and_with(self, constclassprotocols) -> void: ...
    def assign(self) -> BumpGrid: ...
    def create_bump_grid_for_bb(self, bb: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t) -> BumpGrid: ...
    def create_new_bump_grid_for_bb(self, bb: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t) -> BumpGrid: ...
    def grid(self, radtype: ProbeRadius) -> Bool3DGrid: ...
    @overload
    def occupied(self, radius_type: ProbeRadius, p: pyrosetta.rosetta.numeric.xyzVector_double_t) -> bool: ...
    @overload
    def occupied(self, enumprotocols, constclassnumeric) -> bool: ...
    @overload
    def or_by_sphere(self) -> None: ...
    @overload
    def or_by_sphere(self, center: pyrosetta.rosetta.numeric.xyzVector_double_t, radius_type: ProbeRadius) -> None: ...
    @overload
    def or_by_sphere(self, constclassnumeric, enumprotocols) -> void: ...
    @overload
    def or_with(self) -> None: ...
    @overload
    def or_with(self, constclassprotocols) -> void: ...
    @overload
    def overlaps(self) -> bool: ...
    @overload
    def overlaps(self, constclassprotocols) -> bool: ...
    def pair_overlap_tolerance(self, rad1: ProbeRadius, rad2: ProbeRadius) -> float: ...
    @overload
    @staticmethod
    def probe_radius(radtype: ProbeRadius) -> float: ...
    @overload
    @staticmethod
    def probe_radius(enumprotocols) -> double: ...
    def required_separation_distance(self, rad1: ProbeRadius, rad2: ProbeRadius) -> float: ...
    @overload
    def set_bounding_box(self, bb: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t) -> None: ...
    @overload
    def set_bounding_box(self, constclassnumeric) -> void: ...
    @overload
    def set_general_overlap_tolerance(self, tolerated_overlap: float) -> None: ...
    @overload
    def set_general_overlap_tolerance(self, double) -> void: ...
    def set_pair_overlap_tolerance(self, rad1: ProbeRadius, rad2: ProbeRadius, tolerated_overlap: float) -> None: ...

class Hit:
    def __init__(self) -> None: ...
    @overload
    def downstream_conf_id(self) -> int: ...
    @overload
    def downstream_conf_id(self) -> unsignedlong: ...
    @overload
    def external_geom_id(self) -> int: ...
    @overload
    def external_geom_id(self) -> unsignedlong: ...
    def first(self) -> pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_4UL_t: ...
    @overload
    def scaffold_build_id(self) -> int: ...
    @overload
    def scaffold_build_id(self) -> unsignedlong: ...
    def second(self) -> pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t: ...
    @overload
    def upstream_conf_id(self) -> int: ...
    @overload
    def upstream_conf_id(self) -> unsignedlong: ...

class HitHasher:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: HitHasher) -> None: ...
    def assign(self) -> HitHasher: ...
    def binner(self, which_hash_map: int) -> pyrosetta.rosetta.numeric.geometry.hashing.SixDCoordinateBinner: ...
    @overload
    def clear_hash_map(self, which_hash_map: int) -> None: ...
    @overload
    def clear_hash_map(self, unsignedlong) -> void: ...
    @overload
    def initialize(self) -> None: ...
    @overload
    def initialize(self) -> void: ...
    @overload
    def insert_hit(self, geometric_constraint_id: int, hit: Hit) -> None: ...
    @overload
    def insert_hit(self, unsignedlong, constclassprotocols) -> void: ...
    @overload
    def insert_hit(self, which_hash_map: int, geometric_constraint_id: int, hit: Hit) -> None: ...
    @overload
    def set_bounding_box(self, bb: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t) -> None: ...
    @overload
    def set_bounding_box(self, constclassnumeric) -> void: ...
    @overload
    def set_euler_bin_widths(self, euler_bin_widths: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_euler_bin_widths(self, constclassnumeric) -> void: ...
    @overload
    def set_nhits_per_match(self, num_geometric_constraints: int) -> None: ...
    @overload
    def set_nhits_per_match(self, unsignedlong) -> void: ...
    @overload
    def set_uniform_euler_angle_bin_width(self, bin_width_degrees: float) -> None: ...
    @overload
    def set_uniform_euler_angle_bin_width(self, double) -> void: ...
    @overload
    def set_uniform_xyz_bin_width(self, bin_width: float) -> None: ...
    @overload
    def set_uniform_xyz_bin_width(self, double) -> void: ...
    @overload
    def set_xyz_bin_widths(self, bin_widths: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_xyz_bin_widths(self, constclassnumeric) -> void: ...

class HitNeighborFinder:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: HitNeighborFinder) -> None: ...
    @overload
    def add_hits(self, hitlist: pyrosetta.rosetta.std.list_protocols_match_Hit_t) -> None: ...
    @overload
    def add_hits(self, constclassstd) -> void: ...
    @overload
    def add_hits(self, hitptrlist: pyrosetta.rosetta.std.list_const_protocols_match_Hit__star__t) -> None: ...
    @overload
    def add_hits(self, constclassstd) -> void: ...
    def assign(self) -> HitNeighborFinder: ...
    @overload
    def initialize(self) -> None: ...
    @overload
    def initialize(self) -> void: ...
    def neighbor_hits(self, queryhits: pyrosetta.rosetta.std.list_const_protocols_match_Hit__star__t) -> pyrosetta.rosetta.std.list_const_protocols_match_Hit__star__t: ...
    @overload
    def set_bounding_box(self, bb: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t) -> None: ...
    @overload
    def set_bounding_box(self, constclassnumeric) -> void: ...
    @overload
    def set_euler_bin_widths(self, euler_bin_widths: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_euler_bin_widths(self, constclassnumeric) -> void: ...
    @overload
    def set_uniform_euler_angle_bin_width(self, bin_width_degrees: float) -> None: ...
    @overload
    def set_uniform_euler_angle_bin_width(self, double) -> void: ...
    @overload
    def set_uniform_xyz_bin_width(self, bin_width: float) -> None: ...
    @overload
    def set_uniform_xyz_bin_width(self, double) -> void: ...
    @overload
    def set_xyz_bin_widths(self, bin_widths: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_xyz_bin_widths(self, constclassnumeric) -> void: ...

class MatchCounter:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MatchCounter) -> None: ...
    @overload
    def add_hits(self, geomcst_id: int, hitlist: pyrosetta.rosetta.std.list_protocols_match_Hit_t) -> None: ...
    @overload
    def add_hits(self, unsignedlong, constclassstd) -> void: ...
    @overload
    def add_hits(self, geomcst_id: int, hitptrlist: pyrosetta.rosetta.std.list_const_protocols_match_Hit__star__t) -> None: ...
    @overload
    def add_hits(self, unsignedlong, constclassstd) -> void: ...
    def assign(self) -> MatchCounter: ...
    @overload
    def count_n_matches(self) -> int: ...
    @overload
    def count_n_matches(self) -> unsignedlong: ...
    @overload
    def initialize(self) -> None: ...
    @overload
    def initialize(self) -> void: ...
    @overload
    def set_bounding_box(self, bb: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t) -> None: ...
    @overload
    def set_bounding_box(self, constclassnumeric) -> void: ...
    @overload
    def set_euler_bin_widths(self, euler_bin_widths: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_euler_bin_widths(self, constclassnumeric) -> void: ...
    @overload
    def set_n_geometric_constraints(self, ngeomcsts: int) -> None: ...
    @overload
    def set_n_geometric_constraints(self, unsignedlong) -> void: ...
    @overload
    def set_uniform_euler_angle_bin_width(self, bin_width_degrees: float) -> None: ...
    @overload
    def set_uniform_euler_angle_bin_width(self, double) -> void: ...
    @overload
    def set_uniform_xyz_bin_width(self, bin_width: float) -> None: ...
    @overload
    def set_uniform_xyz_bin_width(self, double) -> void: ...
    @overload
    def set_xyz_bin_widths(self, bin_widths: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_xyz_bin_widths(self, constclassnumeric) -> void: ...

class MatchOutputTracker:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MatchOutputTracker) -> None: ...
    def assign(self) -> MatchOutputTracker: ...
    @overload
    def match_has_been_output(self, m) -> bool: ...
    @overload
    def match_has_been_output(self, constclassutility) -> bool: ...
    @overload
    def note_output_match(self) -> None: ...
    @overload
    def note_output_match(self, constclassutility) -> void: ...

class MatchPositionModifier:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MatchPositionModifier) -> None: ...
    def assign(self) -> MatchPositionModifier: ...
    def modified_match_positions(self, original_positions: pyrosetta.rosetta.utility.vector1_unsigned_long, match_pose: pyrosetta.rosetta.core.pose.Pose, mtask) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...

class Matcher:
    def __init__(self) -> None: ...
    @overload
    def add_external_geometry_samples_for_constraint(self, cst_id: int, restype: pyrosetta.rosetta.core.chemical.ResidueType, upstream_launch_atoms: pyrosetta.rosetta.utility.vector1_std_string, downstream_3atoms: pyrosetta.rosetta.utility.vector1_core_id_AtomID, exgeom_list: pyrosetta.rosetta.utility.vector1_protocols_toolbox_match_enzdes_util_ExternalGeomSampler, exgeom_id: int) -> None: ...
    @overload
    def add_external_geometry_samples_for_constraint(self, cst_id: int, restype: pyrosetta.rosetta.core.chemical.ResidueType, upstream_launch_atoms: pyrosetta.rosetta.utility.vector1_std_string, downstream_3atoms: pyrosetta.rosetta.utility.vector1_core_id_AtomID, exgeom_list: pyrosetta.rosetta.utility.vector1_protocols_toolbox_match_enzdes_util_ExternalGeomSampler, exgeom_id: int, enumerate_ligand_rotamers: bool) -> None: ...
    @overload
    def add_external_geometry_samples_for_constraint(self, cst_id: int, restype: pyrosetta.rosetta.core.chemical.ResidueType, upstream_launch_atoms: pyrosetta.rosetta.utility.vector1_std_string, downstream_3atoms: pyrosetta.rosetta.utility.vector1_core_id_AtomID, exgeom_list: pyrosetta.rosetta.utility.vector1_protocols_toolbox_match_enzdes_util_ExternalGeomSampler, exgeom_id: int, enumerate_ligand_rotamers: bool, catalytic_bond: bool) -> None: ...
    @overload
    def add_external_geometry_samples_for_constraint(self, cst_id: int, restype: pyrosetta.rosetta.core.chemical.ResidueType, upstream_launch_atoms: pyrosetta.rosetta.utility.vector1_std_string, downstream_3atoms: pyrosetta.rosetta.utility.vector1_core_id_AtomID, exgeom_list: pyrosetta.rosetta.utility.vector1_protocols_toolbox_match_enzdes_util_ExternalGeomSampler, exgeom_id: int, enumerate_ligand_rotamers: bool, catalytic_bond: bool, build_round1_hits_twice: bool) -> None: ...
    def add_secondary_downstream_match_geometry_for_constraint(self, geom_cst_id: int, candidate_restype: pyrosetta.rosetta.core.chemical.ResidueType, downstream_restype: pyrosetta.rosetta.core.chemical.ResidueType, candidate_atids: pyrosetta.rosetta.utility.vector1_unsigned_long, target_atids: pyrosetta.rosetta.utility.vector1_unsigned_long, mcfi, SecMatchStr: str, upstream_pose: pyrosetta.rosetta.core.pose.Pose, catalytic_bond: bool) -> None: ...
    def add_secondary_upstream_match_geometry_for_constraint(self, geom_cst_id: int, target_geom_cst_id: int, candidate_restype: pyrosetta.rosetta.core.chemical.ResidueType, target_restype: pyrosetta.rosetta.core.chemical.ResidueType, candidate_atids: pyrosetta.rosetta.utility.vector1_unsigned_long, target_atids: pyrosetta.rosetta.utility.vector1_unsigned_long, mcfi, SecMatchStr: str, upstream_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def add_upstream_restype_for_constraint(self, cst_id: int, restype: pyrosetta.rosetta.core.chemical.ResidueType) -> None: ...
    @overload
    def add_upstream_restype_for_constraint(self, unsignedlong, classstd) -> void: ...
    def build_point(self, *args, **kwargs): ...
    @overload
    def desymmeterize_upstream_restype_for_constraint(self, cst_id: int) -> None: ...
    @overload
    def desymmeterize_upstream_restype_for_constraint(self, unsignedlong) -> void: ...
    def downstream_builder(self, *args, **kwargs): ...
    def downstream_builders(self, cst_id: int) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_match_downstream_DownstreamBuilder_t: ...
    def downstream_pose(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    def find_hits(self) -> bool: ...
    @overload
    def find_hits(self) -> bool: ...
    def get_pose_build_resids(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def has_upstream_only_geomcsts(self) -> bool: ...
    @overload
    def has_upstream_only_geomcsts(self) -> bool: ...
    def hits(self, cst_id: int) -> pyrosetta.rosetta.std.list_protocols_match_Hit_t: ...
    def initialize_from_file(self, enz_data: pyrosetta.rosetta.protocols.toolbox.match_enzdes_util.EnzConstraintIO, task) -> None: ...
    @overload
    def initialize_from_task(self, task) -> None: ...
    @overload
    def initialize_from_task(self, constclassprotocols) -> void: ...
    @overload
    def n_geometric_constraints(self) -> int: ...
    @overload
    def n_geometric_constraints(self) -> unsignedlong: ...
    def nonconst_downstream_algorithms(self, cst_id: int) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_match_downstream_DownstreamAlgorithm_t: ...
    def occ_space_hash(self, *args, **kwargs): ...
    @overload
    def process_matches(self, processor) -> None: ...
    @overload
    def process_matches(self, classprotocols) -> void: ...
    def representative_downstream_algorithm(self, *args, **kwargs): ...
    @overload
    def set_bump_tolerance(self, permitted_overlap: float) -> None: ...
    @overload
    def set_bump_tolerance(self, double) -> void: ...
    @overload
    def set_downstream_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, orientation_atoms: pyrosetta.rosetta.utility.vector1_core_id_AtomID) -> None: ...
    @overload
    def set_downstream_pose(self, constclasscore, classutility) -> void: ...
    @overload
    def set_fa_dun_cutoff_for_constraint(self, cst_id: int, restype: pyrosetta.rosetta.core.chemical.ResidueType, fa_dun_cutoff: float) -> None: ...
    @overload
    def set_fa_dun_cutoff_for_constraint(self, unsignedlong, classstd, double) -> void: ...
    @overload
    def set_hash_euclidean_bin_width(self, width: float) -> None: ...
    @overload
    def set_hash_euclidean_bin_width(self, double) -> void: ...
    @overload
    def set_hash_euclidean_bin_widths(self, widths: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_hash_euclidean_bin_widths(self, classnumeric) -> void: ...
    @overload
    def set_hash_euler_bin_width(self, width: float) -> None: ...
    @overload
    def set_hash_euler_bin_width(self, double) -> void: ...
    @overload
    def set_hash_euler_bin_widths(self, widths: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_hash_euler_bin_widths(self, classnumeric) -> void: ...
    @overload
    def set_n_geometric_constraints(self, n_constraints: int) -> None: ...
    @overload
    def set_n_geometric_constraints(self, unsignedlong) -> void: ...
    @overload
    def set_occupied_space_bounding_box(self, bb: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t) -> None: ...
    @overload
    def set_occupied_space_bounding_box(self, constclassnumeric) -> void: ...
    @overload
    def set_original_scaffold_build_points(self, resids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_original_scaffold_build_points(self, constclassutility) -> void: ...
    @overload
    def set_original_scaffold_build_points_for_constraint(self, cst_id: int, resids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_original_scaffold_build_points_for_constraint(self, unsignedlong, constclassutility) -> void: ...
    def set_sample_startegy_for_constraint(self, cst_id: int, restype: pyrosetta.rosetta.core.chemical.ResidueType, chi: int, strat) -> None: ...
    @overload
    def set_upstream_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_upstream_pose(self, constclasscore) -> void: ...
    def upstream_builder(self, *args, **kwargs): ...
    def upstream_pose(self) -> pyrosetta.rosetta.core.pose.Pose: ...

class MatcherMover(pyrosetta.rosetta.protocols.rosetta_scripts.MultiplePoseMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, incorporate_matches_into_pose: bool) -> None: ...
    @overload
    def __init__(self, arg0: MatcherMover) -> None: ...
    @overload
    def __init__(self, arg0: MatcherMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_ligres(self, ligres: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def set_ligres(self, classstd) -> void: ...
    @overload
    def set_match_positions(self, match_positions: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_match_positions(self, constclassutility) -> void: ...
    @overload
    def set_return_single_random_match(self, single_random: bool) -> None: ...
    @overload
    def set_return_single_random_match(self, constbool) -> void: ...

class MatcherMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MatcherMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: MatcherMoverCreator) -> None: ...
    def assign(self) -> MatcherMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class MatcherOutputStats:
    all_lex_states: int
    num_considered_muliple_origins: int
    num_ds_hit_incompatible: int
    num_empty_uplist: int
    num_non_up_only_incompatible: int
    num_potential_matches: int
    num_sent_to_proc: int
    num_up_only_incompatible: int
    def __init__(self) -> None: ...
    def __iadd__(self, rhs: MatcherOutputStats) -> MatcherOutputStats: ...

class MatcherTask:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MatcherTask) -> None: ...
    @overload
    def add_filter(self, filter_name: str) -> None: ...
    @overload
    def add_filter(self, conststd) -> void: ...
    @overload
    def append_downstream_atom_to_active_site_required_list(self, atid: pyrosetta.rosetta.core.id.AtomID) -> None: ...
    @overload
    def append_downstream_atom_to_active_site_required_list(self, classcore) -> void: ...
    @overload
    def append_upstream_resiue_as_defining_active_site(self, resid: int, radius: float) -> None: ...
    @overload
    def append_upstream_resiue_as_defining_active_site(self, unsignedlong, double) -> void: ...
    def assign(self) -> MatcherTask: ...
    @overload
    def build_round1_hits_twice(self) -> bool: ...
    @overload
    def build_round1_hits_twice(self) -> bool: ...
    @overload
    def clear_downstream_orientation_atoms(self) -> None: ...
    @overload
    def clear_downstream_orientation_atoms(self) -> void: ...
    @overload
    def consolidate_matches(self, setting: bool) -> None: ...
    @overload
    def consolidate_matches(self, bool) -> void: ...
    @overload
    def consolidate_matches(self) -> bool: ...
    @overload
    def consolidate_matches(self) -> bool: ...
    def cstfile_name(self) -> str: ...
    @overload
    def define_active_site_from_gridlig_file(self, file_name: str) -> None: ...
    @overload
    def define_active_site_from_gridlig_file(self, conststd) -> void: ...
    @overload
    def define_active_site_from_residue_radii_list(self) -> None: ...
    @overload
    def define_active_site_from_residue_radii_list(self) -> void: ...
    @overload
    def define_match_by_single_downstream_positioning(self, setting: bool) -> None: ...
    @overload
    def define_match_by_single_downstream_positioning(self, bool) -> void: ...
    @overload
    def define_match_by_single_downstream_positioning(self) -> bool: ...
    @overload
    def define_match_by_single_downstream_positioning(self) -> bool: ...
    def downstream_atoms_required_inside_active_site(self) -> pyrosetta.rosetta.std.list_core_id_AtomID_t: ...
    def downstream_orientation_atoms(self) -> pyrosetta.rosetta.utility.vector1_core_id_AtomID: ...
    def downstream_pose(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    def dynamic_grid_refinement(self) -> bool: ...
    @overload
    def dynamic_grid_refinement(self) -> bool: ...
    @overload
    def enumerate_ligand_rotamers(self) -> bool: ...
    @overload
    def enumerate_ligand_rotamers(self) -> bool: ...
    def enz_input_data(self) -> pyrosetta.rosetta.protocols.toolbox.match_enzdes_util.EnzConstraintIO: ...
    def euclidean_bin_widths(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def euler_bin_widths(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def evaluator_name(self, setting: str) -> None: ...
    @overload
    def evaluator_name(self, conststd) -> void: ...
    @overload
    def evaluator_name(self) -> str: ...
    def filter_names(self) -> pyrosetta.rosetta.std.list_std_string_t: ...
    @overload
    def filter_upstream_collisions_by_score(self, setting: bool) -> None: ...
    @overload
    def filter_upstream_collisions_by_score(self, bool) -> void: ...
    @overload
    def filter_upstream_collisions_by_score(self) -> bool: ...
    @overload
    def filter_upstream_collisions_by_score(self) -> bool: ...
    @overload
    def filter_upstream_downstream_collisions(self, setting: bool) -> None: ...
    @overload
    def filter_upstream_downstream_collisions(self, bool) -> void: ...
    @overload
    def filter_upstream_downstream_collisions(self) -> bool: ...
    @overload
    def filter_upstream_downstream_collisions(self) -> bool: ...
    @overload
    def filter_upstream_downstream_collisions_by_score(self, setting: bool) -> None: ...
    @overload
    def filter_upstream_downstream_collisions_by_score(self, bool) -> void: ...
    @overload
    def filter_upstream_downstream_collisions_by_score(self) -> bool: ...
    @overload
    def filter_upstream_downstream_collisions_by_score(self) -> bool: ...
    @overload
    def filter_upstream_residue_collisions(self, setting: bool) -> None: ...
    @overload
    def filter_upstream_residue_collisions(self, bool) -> void: ...
    @overload
    def filter_upstream_residue_collisions(self) -> bool: ...
    @overload
    def filter_upstream_residue_collisions(self) -> bool: ...
    def geom_csts_downstream_output(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def get_self_ptr(self) -> MatcherTask: ...
    @overload
    def gridlig_active_site_definition(self) -> bool: ...
    @overload
    def gridlig_active_site_definition(self) -> bool: ...
    def gridlig_file_name(self) -> str: ...
    @overload
    def grouper_ds_rmsd(self) -> float: ...
    @overload
    def grouper_ds_rmsd(self) -> double: ...
    @overload
    def grouper_name(self, setting: str) -> None: ...
    @overload
    def grouper_name(self, conststd) -> void: ...
    @overload
    def grouper_name(self) -> str: ...
    @overload
    def initialize_from_command_line(self) -> None: ...
    @overload
    def initialize_from_command_line(self) -> void: ...
    @overload
    def initialize_with_mcfi_list(self, mcfi_list_vec: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_toolbox_match_enzdes_util_MatchConstraintFileInfoList_t) -> None: ...
    @overload
    def initialize_with_mcfi_list(self, classutility) -> void: ...
    @overload
    def modify_pose_build_resids_from_endes_input(self) -> None: ...
    @overload
    def modify_pose_build_resids_from_endes_input(self) -> void: ...
    @overload
    def n_to_output_per_group(self, setting: int) -> None: ...
    @overload
    def n_to_output_per_group(self, unsignedlong) -> void: ...
    @overload
    def n_to_output_per_group(self) -> int: ...
    @overload
    def n_to_output_per_group(self) -> unsignedlong: ...
    def occ_space_bounding_box(self) -> pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t: ...
    @overload
    def only_enumerate_non_match_redundant_ligand_rotamers(self) -> bool: ...
    @overload
    def only_enumerate_non_match_redundant_ligand_rotamers(self) -> bool: ...
    @overload
    def output_file_name(self, setting: str) -> None: ...
    @overload
    def output_file_name(self, conststd) -> void: ...
    @overload
    def output_file_name(self) -> str: ...
    @overload
    def output_matchres_only(self) -> bool: ...
    @overload
    def output_matchres_only(self) -> bool: ...
    @overload
    def output_scores(self) -> bool: ...
    @overload
    def output_scores(self) -> bool: ...
    @overload
    def output_writer_name(self, setting: str) -> None: ...
    @overload
    def output_writer_name(self, conststd) -> void: ...
    @overload
    def output_writer_name(self) -> str: ...
    @overload
    def permitted_overlap(self) -> float: ...
    @overload
    def permitted_overlap(self) -> double: ...
    def relevant_downstream_atoms(self) -> pyrosetta.rosetta.utility.vector1_core_id_AtomID: ...
    @overload
    def score_output_file_name(self, setting: str) -> None: ...
    @overload
    def score_output_file_name(self, conststd) -> void: ...
    @overload
    def score_output_file_name(self) -> str: ...
    @overload
    def set_downstream_orientation_atoms(self, orientation_atoms: pyrosetta.rosetta.utility.vector1_core_id_AtomID) -> None: ...
    @overload
    def set_downstream_orientation_atoms(self, constclassutility) -> void: ...
    @overload
    def set_downstream_pose(self, input_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_downstream_pose(self, constclasscore) -> void: ...
    @overload
    def set_downstream_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, orientation_atoms: pyrosetta.rosetta.utility.vector1_core_id_AtomID) -> None: ...
    @overload
    def set_downstream_pose(self, constclasscore, constclassutility) -> void: ...
    @overload
    def set_enumerate_ligand_rotamers(self, setting: bool) -> None: ...
    @overload
    def set_enumerate_ligand_rotamers(self, bool) -> void: ...
    @overload
    def set_enz_input_data(self, data: pyrosetta.rosetta.protocols.toolbox.match_enzdes_util.EnzConstraintIO) -> None: ...
    @overload
    def set_enz_input_data(self, classstd) -> void: ...
    @overload
    def set_hash_euclidean_bin_width(self, width: float) -> None: ...
    @overload
    def set_hash_euclidean_bin_width(self, double) -> void: ...
    @overload
    def set_hash_euler_bin_width(self, width: float) -> None: ...
    @overload
    def set_hash_euler_bin_width(self, double) -> void: ...
    @overload
    def set_ignore_cmdline_for_build_points(self, setting: bool) -> None: ...
    @overload
    def set_ignore_cmdline_for_build_points(self, bool) -> void: ...
    @overload
    def set_occupied_space_bounding_box(self, bb: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t) -> None: ...
    @overload
    def set_occupied_space_bounding_box(self, constclassnumeric) -> void: ...
    @overload
    def set_only_enumerate_non_match_redundant_ligand_rotamers(self, setting: bool) -> None: ...
    @overload
    def set_only_enumerate_non_match_redundant_ligand_rotamers(self, bool) -> void: ...
    @overload
    def set_original_scaffold_build_points(self, resids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_original_scaffold_build_points(self, constclassutility) -> void: ...
    @overload
    def set_original_scaffold_build_points_for_geometric_constraint(self, geom_cst_id: int, resids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_original_scaffold_build_points_for_geometric_constraint(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def set_permitted_overlap(self, permitted_overlap: float) -> None: ...
    @overload
    def set_permitted_overlap(self, double) -> void: ...
    @overload
    def set_upstream_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_upstream_pose(self, constclasscore) -> void: ...
    @overload
    def upstream_downstream_atom_collision_tolerance(self, setting: float) -> None: ...
    @overload
    def upstream_downstream_atom_collision_tolerance(self, double) -> void: ...
    @overload
    def upstream_downstream_atom_collision_tolerance(self) -> float: ...
    @overload
    def upstream_downstream_atom_collision_tolerance(self) -> double: ...
    @overload
    def upstream_downstream_residue_collision_Wfa_atr(self, setting: float) -> None: ...
    @overload
    def upstream_downstream_residue_collision_Wfa_atr(self, double) -> void: ...
    @overload
    def upstream_downstream_residue_collision_Wfa_atr(self) -> float: ...
    @overload
    def upstream_downstream_residue_collision_Wfa_atr(self) -> double: ...
    @overload
    def upstream_downstream_residue_collision_Wfa_rep(self, setting: float) -> None: ...
    @overload
    def upstream_downstream_residue_collision_Wfa_rep(self, double) -> void: ...
    @overload
    def upstream_downstream_residue_collision_Wfa_rep(self) -> float: ...
    @overload
    def upstream_downstream_residue_collision_Wfa_rep(self) -> double: ...
    @overload
    def upstream_downstream_residue_collision_Wfa_sol(self, setting: float) -> None: ...
    @overload
    def upstream_downstream_residue_collision_Wfa_sol(self, double) -> void: ...
    @overload
    def upstream_downstream_residue_collision_Wfa_sol(self) -> float: ...
    @overload
    def upstream_downstream_residue_collision_Wfa_sol(self) -> double: ...
    @overload
    def upstream_downstream_residue_collision_score_cutoff(self, setting: float) -> None: ...
    @overload
    def upstream_downstream_residue_collision_score_cutoff(self, double) -> void: ...
    @overload
    def upstream_downstream_residue_collision_score_cutoff(self) -> float: ...
    @overload
    def upstream_downstream_residue_collision_score_cutoff(self) -> double: ...
    def upstream_only_geom_cst(self) -> pyrosetta.rosetta.std.map_unsigned_long_unsigned_long: ...
    def upstream_pose(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    def upstream_pose_build_resids_for_geometric_constraint(self, cst_id: int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def upstream_pose_name(self) -> str: ...
    def upstream_resids_and_radii_defining_active_site(self) -> pyrosetta.rosetta.std.list_std_pair_unsigned_long_double_t: ...
    @overload
    def upstream_residue_collision_Wfa_atr(self, setting: float) -> None: ...
    @overload
    def upstream_residue_collision_Wfa_atr(self, double) -> void: ...
    @overload
    def upstream_residue_collision_Wfa_atr(self) -> float: ...
    @overload
    def upstream_residue_collision_Wfa_atr(self) -> double: ...
    @overload
    def upstream_residue_collision_Wfa_rep(self, setting: float) -> None: ...
    @overload
    def upstream_residue_collision_Wfa_rep(self, double) -> void: ...
    @overload
    def upstream_residue_collision_Wfa_rep(self) -> float: ...
    @overload
    def upstream_residue_collision_Wfa_rep(self) -> double: ...
    @overload
    def upstream_residue_collision_Wfa_sol(self, setting: float) -> None: ...
    @overload
    def upstream_residue_collision_Wfa_sol(self, double) -> void: ...
    @overload
    def upstream_residue_collision_Wfa_sol(self) -> float: ...
    @overload
    def upstream_residue_collision_Wfa_sol(self) -> double: ...
    @overload
    def upstream_residue_collision_score_cutoff(self, setting: float) -> None: ...
    @overload
    def upstream_residue_collision_score_cutoff(self, double) -> void: ...
    @overload
    def upstream_residue_collision_score_cutoff(self) -> float: ...
    @overload
    def upstream_residue_collision_score_cutoff(self) -> double: ...
    @overload
    def upstream_residue_collision_tolerance(self, setting: float) -> None: ...
    @overload
    def upstream_residue_collision_tolerance(self, double) -> void: ...
    @overload
    def upstream_residue_collision_tolerance(self) -> float: ...
    @overload
    def upstream_residue_collision_tolerance(self) -> double: ...
    @overload
    def use_different_build_points_for_each_geometric_constraint(self, n_geometric_constraints: int) -> None: ...
    @overload
    def use_different_build_points_for_each_geometric_constraint(self, unsignedlong) -> void: ...
    @overload
    def use_input_sc(self) -> bool: ...
    @overload
    def use_input_sc(self) -> bool: ...

class NumNeighborsMPM(MatchPositionModifier):
    @overload
    def __init__(self, input_tokens: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def __init__(self, arg0: NumNeighborsMPM) -> None: ...
    @overload
    def __init__(self, arg0: NumNeighborsMPM) -> None: ...
    def assign(self) -> NumNeighborsMPM: ...
    def modified_match_positions(self, original_positions: pyrosetta.rosetta.utility.vector1_unsigned_long, match_pose: pyrosetta.rosetta.core.pose.Pose, mtask) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def passes_com_vector_criterion(self, seqpos: int, pose: pyrosetta.rosetta.core.pose.Pose, com: pyrosetta.rosetta.numeric.xyzVector_double_t) -> bool: ...
    @overload
    def passes_com_vector_criterion(self, unsignedlong, constclasscore, constclassnumeric) -> bool: ...

class OccupiedSpaceHash:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: OccupiedSpaceHash) -> None: ...
    def assign(self) -> OccupiedSpaceHash: ...
    @overload
    def drop_unsatisfied_voxels(self) -> None: ...
    @overload
    def drop_unsatisfied_voxels(self) -> void: ...
    @overload
    def initialize(self) -> None: ...
    @overload
    def initialize(self) -> void: ...
    def insert_hit_geometry(self, geom: pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t) -> None: ...
    def match_possible_for_hit_geometry(self) -> bool: ...
    def note_hit_geometry(self) -> None: ...
    @overload
    def prepare_to_note_hits_for_completed_round(self) -> None: ...
    @overload
    def prepare_to_note_hits_for_completed_round(self) -> void: ...
    def previous_round_geometry_still_matchable(self) -> bool: ...
    @overload
    def reset_3d_projection(self) -> None: ...
    @overload
    def reset_3d_projection(self) -> void: ...
    @overload
    def revision_id(self) -> int: ...
    @overload
    def revision_id(self) -> unsignedlong: ...
    @overload
    def set_bounding_box(self, bb: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t) -> None: ...
    @overload
    def set_bounding_box(self, constclassnumeric) -> void: ...
    @overload
    def set_euler_bin_widths(self, euler_bin_widths: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_euler_bin_widths(self, constclassnumeric) -> void: ...
    @overload
    def set_uniform_euler_angle_bin_width(self, bin_width_degrees: float) -> None: ...
    @overload
    def set_uniform_euler_angle_bin_width(self, double) -> void: ...
    @overload
    def set_uniform_xyz_bin_width(self, bin_width: float) -> None: ...
    @overload
    def set_uniform_xyz_bin_width(self, double) -> void: ...
    @overload
    def set_xyz_bin_widths(self, bin_widths: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_xyz_bin_widths(self, constclassnumeric) -> void: ...
    @overload
    def write_3Dprojection_kinemage(self, kin_file_name: str) -> None: ...
    @overload
    def write_3Dprojection_kinemage(self, conststd) -> void: ...

class ProbeRadius:
    __members__: ClassVar[dict] = ...  # read-only
    C_ALA: ClassVar[ProbeRadius] = ...
    C_CAR: ClassVar[ProbeRadius] = ...
    H_ALA: ClassVar[ProbeRadius] = ...
    H_ARO: ClassVar[ProbeRadius] = ...
    NIT: ClassVar[ProbeRadius] = ...
    OXY: ClassVar[ProbeRadius] = ...
    SULPH: ClassVar[ProbeRadius] = ...
    ZERO: ClassVar[ProbeRadius] = ...
    __entries: ClassVar[dict] = ...
    n_probe_radii: ClassVar[ProbeRadius] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class RemoveNorCTermMPM(MatchPositionModifier):
    @overload
    def __init__(self, input_tokens: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def __init__(self, arg0: RemoveNorCTermMPM) -> None: ...
    @overload
    def __init__(self, arg0: RemoveNorCTermMPM) -> None: ...
    def assign(self) -> RemoveNorCTermMPM: ...
    def modified_match_positions(self, original_positions: pyrosetta.rosetta.utility.vector1_unsigned_long, match_pose: pyrosetta.rosetta.core.pose.Pose, mtask) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...

class SecondaryStructureMPM(MatchPositionModifier):
    @overload
    def __init__(self, input_tokens: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def __init__(self, arg0: SecondaryStructureMPM) -> None: ...
    @overload
    def __init__(self, arg0: SecondaryStructureMPM) -> None: ...
    def assign(self) -> SecondaryStructureMPM: ...
    def modified_match_positions(self, original_positions: pyrosetta.rosetta.utility.vector1_unsigned_long, match_pose: pyrosetta.rosetta.core.pose.Pose, mtask) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...

class TaskOperationMPM(MatchPositionModifier):
    @overload
    def __init__(self, geom_cst: int, input_tokens: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def __init__(self, arg0: TaskOperationMPM) -> None: ...
    @overload
    def __init__(self, arg0: TaskOperationMPM) -> None: ...
    def assign(self) -> TaskOperationMPM: ...
    def modified_match_positions(self, original_positions: pyrosetta.rosetta.utility.vector1_unsigned_long, match_pose: pyrosetta.rosetta.core.pose.Pose, mtask) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...

class VoxelSetIterator:
    @overload
    def __init__(self, bb: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t, n_xyz_bins: pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_3UL_t, n_euler_bins: pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_3UL_t, xyz_bin_widths: pyrosetta.rosetta.utility.fixedsizearray1_double_3UL_t, euler_bin_widths: pyrosetta.rosetta.utility.fixedsizearray1_double_3UL_t, xyz_bin_halfwidths: pyrosetta.rosetta.utility.fixedsizearray1_double_3UL_t, euler_bin_halfwidths: pyrosetta.rosetta.utility.fixedsizearray1_double_3UL_t, point: pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t) -> None: ...
    @overload
    def __init__(self, arg0: VoxelSetIterator) -> None: ...
    def assign(self) -> VoxelSetIterator: ...
    @overload
    def at_end(self) -> bool: ...
    @overload
    def at_end(self) -> bool: ...
    def get_bin_and_pos(self, bin: pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_6UL_t, pos: int) -> None: ...
    def pre_increment(self) -> None: ...

class downstream_hit:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, source: Hit) -> None: ...
    @overload
    def copy_hit(self, source: Hit) -> None: ...
    @overload
    def copy_hit(self, constclassprotocols) -> void: ...
    @overload
    def downstream_conf_id(self) -> int: ...
    @overload
    def downstream_conf_id(self) -> unsignedlong: ...
    def second(self) -> pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t: ...
    def __eq__(self, rhs: downstream_hit) -> bool: ...

class match_dspos1:
    downstream_conf_id: int
    dspos: pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t
    originating_geom_cst_for_dspos: int
    upstream_hits: pyrosetta.rosetta.utility.vector1_protocols_match_upstream_hit
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, n_geometric_constraints: int) -> None: ...
    @overload
    def __init__(self, m: pyrosetta.rosetta.utility.vector1_protocols_match_Hit, geomcst_specifying_dspos: int) -> None: ...
    @overload
    def __init__(self, arg0: match_dspos1) -> None: ...
    def assign(self) -> match_dspos1: ...

class match_lite_equals:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: match_lite_equals) -> None: ...
    def assign(self) -> match_lite_equals: ...
    def __call__(self, lhs, rhs) -> bool: ...

class match_lite_hasher:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: match_lite_hasher) -> None: ...
    def assign(self) -> match_lite_hasher: ...
    def __call__(self, m) -> int: ...

class upstream_hit:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, source: Hit) -> None: ...
    @overload
    def copy_hit(self, source: Hit) -> None: ...
    @overload
    def copy_hit(self, constclassprotocols) -> void: ...
    @overload
    def external_geom_id(self) -> int: ...
    @overload
    def external_geom_id(self) -> unsignedlong: ...
    @overload
    def external_geom_id(self, setting: int) -> None: ...
    @overload
    def external_geom_id(self, unsignedlong) -> void: ...
    @overload
    def scaffold_build_id(self) -> int: ...
    @overload
    def scaffold_build_id(self) -> unsignedlong: ...
    @overload
    def scaffold_build_id(self, setting: int) -> None: ...
    @overload
    def scaffold_build_id(self, unsignedlong) -> void: ...
    @overload
    def upstream_conf_id(self) -> int: ...
    @overload
    def upstream_conf_id(self) -> unsignedlong: ...
    @overload
    def upstream_conf_id(self, setting: int) -> None: ...
    @overload
    def upstream_conf_id(self, unsignedlong) -> void: ...
    def __eq__(self, rhs: upstream_hit) -> bool: ...

def advance_euler_angles(orig_angles: pyrosetta.rosetta.utility.fixedsizearray1_double_3UL_t, offsets: pyrosetta.rosetta.utility.fixedsizearray1_double_3UL_t) -> pyrosetta.rosetta.utility.fixedsizearray1_double_3UL_t: ...
def bump_grid_to_enclose_pose(pose: pyrosetta.rosetta.core.pose.Pose) -> BumpGrid: ...
def bump_grid_to_enclose_residue(residue: pyrosetta.rosetta.core.conformation.Residue, original_grid: BumpGrid) -> BumpGrid: ...
def bump_grid_to_enclose_residue_backbone(residue: pyrosetta.rosetta.core.conformation.Residue, original_grid: BumpGrid) -> BumpGrid: ...
def create_match_position_modifier(*args, **kwargs): ...
@overload
def fake_hit() -> Hit: ...
@overload
def fake_hit() -> Hit: ...
@overload
def fill_grid_with_backbone_heavyatom_spheres(residue: pyrosetta.rosetta.core.conformation.Residue, grid: BumpGrid) -> None: ...
@overload
def fill_grid_with_backbone_heavyatom_spheres(constclasscore, classprotocols) -> void: ...
@overload
def fill_grid_with_residue_heavyatom_spheres(residue: pyrosetta.rosetta.core.conformation.Residue, grid: BumpGrid) -> None: ...
@overload
def fill_grid_with_residue_heavyatom_spheres(constclasscore, classprotocols) -> void: ...
@overload
def fill_grid_with_residue_spheres(residue: pyrosetta.rosetta.core.conformation.Residue, grid: BumpGrid) -> None: ...
@overload
def fill_grid_with_residue_spheres(constclasscore, classprotocols) -> void: ...
def full_hit(m: match_dspos1) -> Hit: ...
def probe_radius_for_atom_type(atomtype: int) -> ProbeRadius: ...
@overload
def set_ligpose_rotamer(ligpose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def set_ligpose_rotamer(classcore) -> void: ...
