import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.scoring.etable.count_pair
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.numeric.geometry
import pyrosetta.rosetta.protocols.match
import pyrosetta.rosetta.protocols.match.upstream
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import overload

class ActiveSiteGrid:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ActiveSiteGrid) -> None: ...
    def assign(self, rhs: ActiveSiteGrid) -> ActiveSiteGrid: ...
    def bounding_box(self) -> pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def enlargen_to_capture_volume_within_radius_of_backbone(self, res: pyrosetta.rosetta.core.conformation.Residue, radius: float) -> None: ...
    @overload
    def enlargen_to_capture_volume_within_radius_of_backbone(self, constclasscore, double) -> void: ...
    @overload
    def enlargen_to_capture_volume_within_radius_of_residue(self, res: pyrosetta.rosetta.core.conformation.Residue, radius: float) -> None: ...
    @overload
    def enlargen_to_capture_volume_within_radius_of_residue(self, constclasscore, double) -> void: ...
    @overload
    def enlargen_to_capture_volume_within_radius_of_sidechain(self, res: pyrosetta.rosetta.core.conformation.Residue, radius: float) -> None: ...
    @overload
    def enlargen_to_capture_volume_within_radius_of_sidechain(self, constclasscore, double) -> void: ...
    def grid(self) -> pyrosetta.rosetta.protocols.match.Bool3DGrid: ...
    @overload
    def initialize(self) -> None: ...
    @overload
    def initialize(self) -> void: ...
    @overload
    def initialize_from_gridlig_file(self, fname: str) -> None: ...
    @overload
    def initialize_from_gridlig_file(self, conststd) -> void: ...
    @overload
    def occupied(self, p: pyrosetta.rosetta.numeric.xyzVector_double_t) -> bool: ...
    @overload
    def occupied(self, constclassnumeric) -> bool: ...
    @overload
    def or_within_radius_of_backbone(self, res: pyrosetta.rosetta.core.conformation.Residue, radius: float) -> None: ...
    @overload
    def or_within_radius_of_backbone(self, constclasscore, double) -> void: ...
    @overload
    def or_within_radius_of_residue(self, res: pyrosetta.rosetta.core.conformation.Residue, radius: float) -> None: ...
    @overload
    def or_within_radius_of_residue(self, constclasscore, double) -> void: ...
    @overload
    def or_within_radius_of_sidechain(self, res: pyrosetta.rosetta.core.conformation.Residue, radius: float) -> None: ...
    @overload
    def or_within_radius_of_sidechain(self, constclasscore, double) -> void: ...
    @overload
    def set_bin_width(self, width: float) -> None: ...
    @overload
    def set_bin_width(self, double) -> void: ...
    @overload
    def set_bounding_box(self, bb: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t) -> None: ...
    @overload
    def set_bounding_box(self, constclassnumeric) -> void: ...

class AtomAngleSecMatchRPE(AtomGeometrySecMatchRPE):
    @overload
    def __init__(self, gsi) -> None: ...
    @overload
    def __init__(self, arg0: AtomAngleSecMatchRPE) -> None: ...
    @overload
    def __init__(self, arg0: AtomAngleSecMatchRPE) -> None: ...
    def assign(self) -> AtomAngleSecMatchRPE: ...
    def evaluate_residues(self, candidate_res: pyrosetta.rosetta.core.conformation.Residue, target_res: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    def print(self, candidate_restype: pyrosetta.rosetta.core.chemical.ResidueType, target_restype: pyrosetta.rosetta.core.chemical.ResidueType) -> str: ...

class AtomDihedralSecMatchRPE(AtomGeometrySecMatchRPE):
    @overload
    def __init__(self, gsi) -> None: ...
    @overload
    def __init__(self, arg0: AtomDihedralSecMatchRPE) -> None: ...
    @overload
    def __init__(self, arg0: AtomDihedralSecMatchRPE) -> None: ...
    def assign(self) -> AtomDihedralSecMatchRPE: ...
    def evaluate_residues(self, candidate_res: pyrosetta.rosetta.core.conformation.Residue, target_res: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    def print(self, candidate_restype: pyrosetta.rosetta.core.chemical.ResidueType, target_restype: pyrosetta.rosetta.core.chemical.ResidueType) -> str: ...

class AtomDistanceSecMatchRPE(AtomGeometrySecMatchRPE):
    @overload
    def __init__(self, gsi) -> None: ...
    @overload
    def __init__(self, arg0: AtomDistanceSecMatchRPE) -> None: ...
    @overload
    def __init__(self, arg0: AtomDistanceSecMatchRPE) -> None: ...
    def assign(self) -> AtomDistanceSecMatchRPE: ...
    def candidate_res_atoms_reqd_near_target_atom(self, target_atom_id: int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def evaluate_residues(self, candidate_res: pyrosetta.rosetta.core.conformation.Residue, target_res: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    @overload
    def max_separation_dist_to_target_atom(self, target_atom_id: int) -> float: ...
    @overload
    def max_separation_dist_to_target_atom(self, unsignedlong) -> double: ...
    def print(self, candidate_restype: pyrosetta.rosetta.core.chemical.ResidueType, target_restype: pyrosetta.rosetta.core.chemical.ResidueType) -> str: ...
    @overload
    def require_candidate_residue_atoms_to_lie_near_target_atom(self, target_atom_id: int) -> bool: ...
    @overload
    def require_candidate_residue_atoms_to_lie_near_target_atom(self, unsignedlong) -> bool: ...

class AtomGeometrySecMatchRPE(SecMatchResiduePairEvaluator):
    @overload
    def __init__(self, gsi) -> None: ...
    @overload
    def __init__(self, arg0: AtomGeometrySecMatchRPE) -> None: ...
    def add_at_ind(self, which_cst_res: int, atom_ind_in_res: int) -> None: ...
    def assign(self) -> AtomGeometrySecMatchRPE: ...
    def at_inds(self) -> pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t: ...
    @overload
    def check_value(self, value: float) -> bool: ...
    @overload
    def check_value(self, double) -> bool: ...
    def evaluate_residues(self, candidate_res: pyrosetta.rosetta.core.conformation.Residue, target_res: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    @overload
    def highval(self) -> float: ...
    @overload
    def highval(self) -> double: ...
    @overload
    def lowval(self) -> float: ...
    @overload
    def lowval(self) -> double: ...
    def print(self, candidate_restype: pyrosetta.rosetta.core.chemical.ResidueType, target_restype: pyrosetta.rosetta.core.chemical.ResidueType) -> str: ...
    @overload
    def require_all_target_residue_atom_coordinates(self) -> bool: ...
    @overload
    def require_all_target_residue_atom_coordinates(self) -> bool: ...
    @overload
    def require_target_atom_coordinate(self, target_atom_id: int) -> bool: ...
    @overload
    def require_target_atom_coordinate(self, unsignedlong) -> bool: ...

class ClassicMatchAlgorithm(DownstreamAlgorithm):
    @overload
    def __init__(self, geom_cst_id: int) -> None: ...
    @overload
    def __init__(self, arg0: ClassicMatchAlgorithm) -> None: ...
    @overload
    def __init__(self, arg0: ClassicMatchAlgorithm) -> None: ...
    def add_external_geom_sampler(self, sampler: pyrosetta.rosetta.utility.vector1_protocols_toolbox_match_enzdes_util_ExternalGeomSampler, exgeom_id: int, atom1: str, atom2: str, atom3: str, downstream_builder) -> None: ...
    def assign(self) -> ClassicMatchAlgorithm: ...
    def build(self, scaffold_build_point_id: int, upstream_conf_id: int, upstream_residue: pyrosetta.rosetta.core.conformation.Residue) -> pyrosetta.rosetta.std.list_protocols_match_Hit_t: ...
    def build_and_discard_first_round_hits_at_all_positions(self, matcher: pyrosetta.rosetta.protocols.match.Matcher) -> pyrosetta.rosetta.std.list_protocols_match_Hit_t: ...
    def build_from_three_coords(self, which_external_sampler: int, scaffold_build_point_id: int, upstream_conf_id: int, upstream_residue: pyrosetta.rosetta.core.conformation.Residue) -> pyrosetta.rosetta.std.list_protocols_match_Hit_t: ...
    def build_hits_at_all_positions(self, matcher: pyrosetta.rosetta.protocols.match.Matcher) -> pyrosetta.rosetta.std.list_protocols_match_Hit_t: ...
    @overload
    def clear_external_geom_samplers(self) -> None: ...
    @overload
    def clear_external_geom_samplers(self) -> void: ...
    def clone(self) -> DownstreamAlgorithm: ...
    def external_sampler(self, external_geom_id: int) -> pyrosetta.rosetta.utility.vector1_protocols_toolbox_match_enzdes_util_ExternalGeomSampler: ...
    @overload
    def generates_primary_hits(self) -> bool: ...
    @overload
    def generates_primary_hits(self) -> bool: ...
    def hits_to_include_with_partial_match(self, *args, **kwargs): ...
    def launch_atom(self, external_geom_id: int, which_point: int) -> int: ...
    @overload
    def n_external_samplers(self) -> int: ...
    @overload
    def n_external_samplers(self) -> unsignedlong: ...
    @overload
    def n_possible_hits_per_upstream_conformation(self) -> int: ...
    @overload
    def n_possible_hits_per_upstream_conformation(self) -> unsignedlong: ...
    @overload
    def respond_to_peripheral_hitlist_change(self, matcher: pyrosetta.rosetta.protocols.match.Matcher) -> None: ...
    @overload
    def respond_to_peripheral_hitlist_change(self, classprotocols) -> void: ...
    @overload
    def respond_to_primary_hitlist_change(self, matcher: pyrosetta.rosetta.protocols.match.Matcher, round_just_completed: int) -> None: ...
    @overload
    def respond_to_primary_hitlist_change(self, classprotocols, unsignedlong) -> void: ...
    def restype(self) -> pyrosetta.rosetta.core.chemical.ResidueType: ...
    @overload
    def set_build_round1_hits_twice(self) -> None: ...
    @overload
    def set_build_round1_hits_twice(self) -> void: ...
    @overload
    def set_residue_type(self, restype: pyrosetta.rosetta.core.chemical.ResidueType) -> None: ...
    @overload
    def set_residue_type(self, classstd) -> void: ...
    @overload
    def upstream_only(self) -> bool: ...
    @overload
    def upstream_only(self) -> bool: ...

class DownstreamAlgorithm:
    @overload
    def __init__(self, geom_cst_id: int) -> None: ...
    @overload
    def __init__(self, arg0: DownstreamAlgorithm) -> None: ...
    def are_colliding(self, us_res: pyrosetta.rosetta.core.conformation.Residue, ds_res: pyrosetta.rosetta.core.conformation.Residue, ds_atoms: pyrosetta.rosetta.utility.vector1_core_id_AtomID, catalytic_atoms: pyrosetta.rosetta.utility.vector1_unsigned_long) -> bool: ...
    def assign(self) -> DownstreamAlgorithm: ...
    def build(self, scaffold_build_point_id: int, upstream_conf_id: int, upstream_residue: pyrosetta.rosetta.core.conformation.Residue) -> pyrosetta.rosetta.std.list_protocols_match_Hit_t: ...
    def build_hits_at_all_positions(self, matcher: pyrosetta.rosetta.protocols.match.Matcher) -> pyrosetta.rosetta.std.list_protocols_match_Hit_t: ...
    def clone(self) -> DownstreamAlgorithm: ...
    @overload
    def generates_primary_hits(self) -> bool: ...
    @overload
    def generates_primary_hits(self) -> bool: ...
    @overload
    def geom_cst_id(self) -> int: ...
    @overload
    def geom_cst_id(self) -> unsignedlong: ...
    def get_dsbuilder(self, *args, **kwargs): ...
    def hits_to_include_with_partial_match(self, *args, **kwargs): ...
    @overload
    def n_possible_hits_per_upstream_conformation(self) -> int: ...
    @overload
    def n_possible_hits_per_upstream_conformation(self) -> unsignedlong: ...
    @overload
    def prepare_for_match_enumeration(self) -> None: ...
    @overload
    def prepare_for_match_enumeration(self, constclassprotocols) -> void: ...
    @overload
    def respond_to_peripheral_hitlist_change(self, matcher: pyrosetta.rosetta.protocols.match.Matcher) -> None: ...
    @overload
    def respond_to_peripheral_hitlist_change(self, classprotocols) -> void: ...
    @overload
    def respond_to_primary_hitlist_change(self, matcher: pyrosetta.rosetta.protocols.match.Matcher, round_just_completed: int) -> None: ...
    @overload
    def respond_to_primary_hitlist_change(self, classprotocols, unsignedlong) -> void: ...
    @overload
    def set_active_site_grid(self, active_site_grid: ActiveSiteGrid) -> None: ...
    @overload
    def set_active_site_grid(self, classstd) -> void: ...
    @overload
    def set_bb_grid(self, bbgrid: pyrosetta.rosetta.protocols.match.BumpGrid) -> None: ...
    @overload
    def set_bb_grid(self, classstd) -> void: ...
    @overload
    def set_dsbuilder(self, dsbuilder) -> None: ...
    @overload
    def set_dsbuilder(self, classstd) -> void: ...
    @overload
    def upstream_only(self) -> bool: ...
    @overload
    def upstream_only(self) -> bool: ...

class DownstreamBuilder:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DownstreamBuilder) -> None: ...
    def assign(self) -> DownstreamBuilder: ...
    @overload
    def atom1_atom2_atom3_angle(self) -> float: ...
    @overload
    def atom1_atom2_atom3_angle(self) -> double: ...
    @overload
    def atom1_atom2_distance(self) -> float: ...
    @overload
    def atom1_atom2_distance(self) -> double: ...
    @overload
    def atom1_belongs_in_active_site(self) -> bool: ...
    @overload
    def atom1_belongs_in_active_site(self) -> bool: ...
    def atom1_radius(self) -> pyrosetta.rosetta.protocols.match.ProbeRadius: ...
    @overload
    def atom2_atom3_distance(self) -> float: ...
    @overload
    def atom2_atom3_distance(self) -> double: ...
    @overload
    def atom2_belongs_in_active_site(self) -> bool: ...
    @overload
    def atom2_belongs_in_active_site(self) -> bool: ...
    def atom2_radius(self) -> pyrosetta.rosetta.protocols.match.ProbeRadius: ...
    @overload
    def atom3_belongs_in_active_site(self) -> bool: ...
    @overload
    def atom3_belongs_in_active_site(self) -> bool: ...
    def atom3_radius(self) -> pyrosetta.rosetta.protocols.match.ProbeRadius: ...
    def build(self, atom6_frame: pyrosetta.rosetta.numeric.HomogeneousTransform_double_t, scaffold_build_point_id: int, upstream_conf_id: int, external_geometry_id: int, upstream_residue: pyrosetta.rosetta.core.conformation.Residue) -> pyrosetta.rosetta.std.list_protocols_match_Hit_t: ...
    def clone(self) -> DownstreamBuilder: ...
    @overload
    def compatible(self, my_hit: pyrosetta.rosetta.protocols.match.Hit, other: DownstreamBuilder, other_hit: pyrosetta.rosetta.protocols.match.Hit) -> bool: ...
    @overload
    def compatible(self, my_hit: pyrosetta.rosetta.protocols.match.Hit, other: DownstreamBuilder, other_hit: pyrosetta.rosetta.protocols.match.Hit, first_dispatch: bool) -> bool: ...
    @overload
    def compatible(self, my_hit: pyrosetta.rosetta.protocols.match.Hit, other, other_hit: pyrosetta.rosetta.protocols.match.Hit) -> bool: ...
    @overload
    def compatible(self, my_hit: pyrosetta.rosetta.protocols.match.Hit, other, other_hit: pyrosetta.rosetta.protocols.match.Hit, first_dispatch: bool) -> bool: ...
    @overload
    def compatible(self, my_hit: pyrosetta.rosetta.protocols.match.Hit, other, other_hit: pyrosetta.rosetta.protocols.match.Hit) -> bool: ...
    @overload
    def compatible(self, my_hit: pyrosetta.rosetta.protocols.match.Hit, other, other_hit: pyrosetta.rosetta.protocols.match.Hit, first_dispatch: bool) -> bool: ...
    @overload
    def coordinates_from_hit(self, hit: pyrosetta.rosetta.protocols.match.Hit, atom_indices: pyrosetta.rosetta.utility.vector1_core_id_AtomID, atom_coords: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t) -> None: ...
    @overload
    def coordinates_from_hit(self, constclassprotocols, constclassutility, classutility) -> void: ...
    def downstream_pose_from_hit(self, hit: pyrosetta.rosetta.protocols.match.Hit) -> pyrosetta.rosetta.core.pose.Pose: ...
    def get_lig_conformers(self, *args, **kwargs): ...
    def get_upstream_restype(self) -> pyrosetta.rosetta.core.chemical.ResidueType: ...
    @overload
    def hits_potentially_incompatible(self) -> bool: ...
    @overload
    def hits_potentially_incompatible(self) -> bool: ...
    @overload
    def n_possible_hits_per_at3frame(self) -> int: ...
    @overload
    def n_possible_hits_per_at3frame(self) -> unsignedlong: ...
    @overload
    def require_atom_to_reside_in_active_site(self, id: pyrosetta.rosetta.core.id.AtomID) -> None: ...
    @overload
    def require_atom_to_reside_in_active_site(self, constclasscore) -> void: ...
    @overload
    def set_active_site_grid(self, active_site_grid: ActiveSiteGrid) -> None: ...
    @overload
    def set_active_site_grid(self, classstd) -> void: ...
    @overload
    def set_bb_grid(self, bbgrid: pyrosetta.rosetta.protocols.match.BumpGrid) -> None: ...
    @overload
    def set_bb_grid(self, classstd) -> void: ...
    @overload
    def set_occupied_space_hash(self, occ_space: pyrosetta.rosetta.protocols.match.OccupiedSpaceHash) -> None: ...
    @overload
    def set_occupied_space_hash(self, classstd) -> void: ...

class GeometrySecMatchRPE(SecMatchResiduePairEvaluator):
    @overload
    def __init__(self, mcfi, downstream_inds: pyrosetta.rosetta.utility.vector1_unsigned_long, upstream_inds: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GeometrySecMatchRPE) -> None: ...
    @overload
    def __init__(self, arg0: GeometrySecMatchRPE) -> None: ...
    @overload
    def add_atomgeom_evaluator(self, evaluator: AtomGeometrySecMatchRPE) -> None: ...
    @overload
    def add_atomgeom_evaluator(self, classstd) -> void: ...
    def assign(self) -> GeometrySecMatchRPE: ...
    def atom_geom_rpes(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_protocols_match_downstream_AtomGeometrySecMatchRPE_t: ...
    def candidate_res_atoms_reqd_near_target_atom(self, target_atom_id: int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def evaluate_residues(self, candidate_res: pyrosetta.rosetta.core.conformation.Residue, target_res: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    @overload
    def max_separation_dist_to_target_atom(self, target_atom_id: int) -> float: ...
    @overload
    def max_separation_dist_to_target_atom(self, unsignedlong) -> double: ...
    @overload
    def require_all_target_residue_atom_coordinates(self) -> bool: ...
    @overload
    def require_all_target_residue_atom_coordinates(self) -> bool: ...
    @overload
    def require_candidate_residue_atoms_to_lie_near_target_atom(self, target_atom_id: int) -> bool: ...
    @overload
    def require_candidate_residue_atoms_to_lie_near_target_atom(self, unsignedlong) -> bool: ...
    @overload
    def require_target_atom_coordinate(self, target_atom_id: int) -> bool: ...
    @overload
    def require_target_atom_coordinate(self, unsignedlong) -> bool: ...

class LigandConformerBuilder(DownstreamBuilder):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LigandConformerBuilder) -> None: ...
    @overload
    def __init__(self, arg0: LigandConformerBuilder) -> None: ...
    def assign(self) -> LigandConformerBuilder: ...
    @overload
    def assign_conformer_group_to_residue(self, residue: pyrosetta.rosetta.core.conformation.Residue, relevant_atom_indices: pyrosetta.rosetta.utility.vector1_unsigned_long) -> int: ...
    @overload
    def assign_conformer_group_to_residue(self, constclasscore, constclassutility) -> unsignedlong: ...
    @overload
    def atom1_atom2_atom3_angle(self) -> float: ...
    @overload
    def atom1_atom2_atom3_angle(self) -> double: ...
    @overload
    def atom1_atom2_distance(self) -> float: ...
    @overload
    def atom1_atom2_distance(self) -> double: ...
    @overload
    def atom1_belongs_in_active_site(self) -> bool: ...
    @overload
    def atom1_belongs_in_active_site(self) -> bool: ...
    def atom1_radius(self) -> pyrosetta.rosetta.protocols.match.ProbeRadius: ...
    @overload
    def atom2_atom3_distance(self) -> float: ...
    @overload
    def atom2_atom3_distance(self) -> double: ...
    @overload
    def atom2_belongs_in_active_site(self) -> bool: ...
    @overload
    def atom2_belongs_in_active_site(self) -> bool: ...
    def atom2_radius(self) -> pyrosetta.rosetta.protocols.match.ProbeRadius: ...
    @overload
    def atom3_belongs_in_active_site(self) -> bool: ...
    @overload
    def atom3_belongs_in_active_site(self) -> bool: ...
    def atom3_radius(self) -> pyrosetta.rosetta.protocols.match.ProbeRadius: ...
    def build(self, atom3_frame: pyrosetta.rosetta.numeric.HomogeneousTransform_double_t, scaffold_build_point_id: int, upstream_conf_id: int, external_geometry_id: int, upstream_residue: pyrosetta.rosetta.core.conformation.Residue) -> pyrosetta.rosetta.std.list_protocols_match_Hit_t: ...
    def clone(self) -> DownstreamBuilder: ...
    @overload
    def compatible(self, my_hit: pyrosetta.rosetta.protocols.match.Hit, other: DownstreamBuilder, other_hit: pyrosetta.rosetta.protocols.match.Hit) -> bool: ...
    @overload
    def compatible(self, my_hit: pyrosetta.rosetta.protocols.match.Hit, other: DownstreamBuilder, other_hit: pyrosetta.rosetta.protocols.match.Hit, first_dispatch: bool) -> bool: ...
    @overload
    def compatible(self, my_hit: pyrosetta.rosetta.protocols.match.Hit, other: LigandConformerBuilder, other_hit: pyrosetta.rosetta.protocols.match.Hit) -> bool: ...
    @overload
    def compatible(self, my_hit: pyrosetta.rosetta.protocols.match.Hit, other: LigandConformerBuilder, other_hit: pyrosetta.rosetta.protocols.match.Hit, first_dispatch: bool) -> bool: ...
    @overload
    def coordinates_from_hit(self, hit: pyrosetta.rosetta.protocols.match.Hit, atom_indices: pyrosetta.rosetta.utility.vector1_core_id_AtomID, atom_coords: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t) -> None: ...
    @overload
    def coordinates_from_hit(self, constclassprotocols, constclassutility, classutility) -> void: ...
    @overload
    def determine_redundant_conformer_groups(self, relevant_atom_indices: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def determine_redundant_conformer_groups(self, constclassutility) -> void: ...
    def downstream_pose_from_hit(self, hit: pyrosetta.rosetta.protocols.match.Hit) -> pyrosetta.rosetta.core.pose.Pose: ...
    def get_lig_conformers(self, *args, **kwargs): ...
    def get_upstream_restype(self) -> pyrosetta.rosetta.core.chemical.ResidueType: ...
    @overload
    def hits_potentially_incompatible(self) -> bool: ...
    @overload
    def hits_potentially_incompatible(self) -> bool: ...
    @overload
    def ignore_h_collisions(self, setting: bool) -> None: ...
    @overload
    def ignore_h_collisions(self, bool) -> void: ...
    def initialize_from_residue(self, atom1: int, atom2: int, atom3: int, orientation_atom1: int, orientation_atom2: int, orientation_atom3: int, residue: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def initialize_upstream_residue(self, upstream_res: pyrosetta.rosetta.core.chemical.ResidueType) -> None: ...
    @overload
    def initialize_upstream_residue(self, upstream_res: pyrosetta.rosetta.core.chemical.ResidueType, count_pair: pyrosetta.rosetta.core.scoring.etable.count_pair.CountPairFunction) -> None: ...
    @overload
    def n_possible_hits_per_at3frame(self) -> int: ...
    @overload
    def n_possible_hits_per_at3frame(self) -> unsignedlong: ...
    @overload
    def require_atom_to_reside_in_active_site(self, id: pyrosetta.rosetta.core.id.AtomID) -> None: ...
    @overload
    def require_atom_to_reside_in_active_site(self, constclasscore) -> void: ...
    @overload
    def set_bb_grid(self, bbgrid: pyrosetta.rosetta.protocols.match.BumpGrid) -> None: ...
    @overload
    def set_bb_grid(self, classstd) -> void: ...
    @overload
    def set_idealize_conformers(self, setting: bool) -> None: ...
    @overload
    def set_idealize_conformers(self, bool) -> void: ...
    @overload
    def set_rmsd_unique_cutoff(self, setting: float) -> None: ...
    @overload
    def set_rmsd_unique_cutoff(self, double) -> void: ...

class RigidLigandBuilder(DownstreamBuilder):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RigidLigandBuilder) -> None: ...
    @overload
    def __init__(self, arg0: RigidLigandBuilder) -> None: ...
    def assign(self) -> RigidLigandBuilder: ...
    @overload
    def atom1_atom2_atom3_angle(self) -> float: ...
    @overload
    def atom1_atom2_atom3_angle(self) -> double: ...
    @overload
    def atom1_atom2_distance(self) -> float: ...
    @overload
    def atom1_atom2_distance(self) -> double: ...
    @overload
    def atom1_belongs_in_active_site(self) -> bool: ...
    @overload
    def atom1_belongs_in_active_site(self) -> bool: ...
    def atom1_radius(self) -> pyrosetta.rosetta.protocols.match.ProbeRadius: ...
    @overload
    def atom2_atom3_distance(self) -> float: ...
    @overload
    def atom2_atom3_distance(self) -> double: ...
    @overload
    def atom2_belongs_in_active_site(self) -> bool: ...
    @overload
    def atom2_belongs_in_active_site(self) -> bool: ...
    def atom2_radius(self) -> pyrosetta.rosetta.protocols.match.ProbeRadius: ...
    @overload
    def atom3_belongs_in_active_site(self) -> bool: ...
    @overload
    def atom3_belongs_in_active_site(self) -> bool: ...
    def atom3_radius(self) -> pyrosetta.rosetta.protocols.match.ProbeRadius: ...
    def build(self, atom3_frame: pyrosetta.rosetta.numeric.HomogeneousTransform_double_t, scaffold_build_point_id: int, upstream_conf_id: int, external_geometry_id: int, upstream_residue: pyrosetta.rosetta.core.conformation.Residue) -> pyrosetta.rosetta.std.list_protocols_match_Hit_t: ...
    def clone(self) -> DownstreamBuilder: ...
    @overload
    def compatible(self, my_hit: pyrosetta.rosetta.protocols.match.Hit, other: DownstreamBuilder, other_hit: pyrosetta.rosetta.protocols.match.Hit) -> bool: ...
    @overload
    def compatible(self, my_hit: pyrosetta.rosetta.protocols.match.Hit, other: DownstreamBuilder, other_hit: pyrosetta.rosetta.protocols.match.Hit, first_dispatch: bool) -> bool: ...
    @overload
    def compatible(self, my_hit: pyrosetta.rosetta.protocols.match.Hit, other: RigidLigandBuilder, other_hit: pyrosetta.rosetta.protocols.match.Hit) -> bool: ...
    @overload
    def compatible(self, my_hit: pyrosetta.rosetta.protocols.match.Hit, other: RigidLigandBuilder, other_hit: pyrosetta.rosetta.protocols.match.Hit, first_dispatch: bool) -> bool: ...
    @overload
    def coordinates_from_hit(self, hit: pyrosetta.rosetta.protocols.match.Hit, atom_indices: pyrosetta.rosetta.utility.vector1_core_id_AtomID, atom_coords: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t) -> None: ...
    @overload
    def coordinates_from_hit(self, constclassprotocols, constclassutility, classutility) -> void: ...
    def downstream_pose_from_hit(self, hit: pyrosetta.rosetta.protocols.match.Hit) -> pyrosetta.rosetta.core.pose.Pose: ...
    def get_lig_conformers(self, *args, **kwargs): ...
    def get_upstream_restype(self) -> pyrosetta.rosetta.core.chemical.ResidueType: ...
    @overload
    def hits_potentially_incompatible(self) -> bool: ...
    @overload
    def hits_potentially_incompatible(self) -> bool: ...
    @overload
    def ignore_h_collisions(self, setting: bool) -> None: ...
    @overload
    def ignore_h_collisions(self, bool) -> void: ...
    def initialize_from_residue(self, atom1: int, atom2: int, atom3: int, orientation_atom1: int, orientation_atom2: int, orientation_atom3: int, residue: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def initialize_upstream_residue(self, upstream_res: pyrosetta.rosetta.core.chemical.ResidueType) -> None: ...
    @overload
    def initialize_upstream_residue(self, upstream_res: pyrosetta.rosetta.core.chemical.ResidueType, count_pair: pyrosetta.rosetta.core.scoring.etable.count_pair.CountPairFunction) -> None: ...
    @overload
    def n_possible_hits_per_at3frame(self) -> int: ...
    @overload
    def n_possible_hits_per_at3frame(self) -> unsignedlong: ...
    @overload
    def require_atom_to_reside_in_active_site(self, id: pyrosetta.rosetta.core.id.AtomID) -> None: ...
    @overload
    def require_atom_to_reside_in_active_site(self, constclasscore) -> void: ...
    @overload
    def set_bb_grid(self, bbgrid: pyrosetta.rosetta.protocols.match.BumpGrid) -> None: ...
    @overload
    def set_bb_grid(self, classstd) -> void: ...

class ScoringSecMatchRPE(SecMatchResiduePairEvaluator):
    scoringEval_counter: int
    @overload
    def __init__(self, s_in: str, ref_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: ScoringSecMatchRPE) -> None: ...
    @overload
    def __init__(self, arg0: ScoringSecMatchRPE) -> None: ...
    def assign(self) -> ScoringSecMatchRPE: ...
    @overload
    def check2bsc(self, sType: pyrosetta.rosetta.core.scoring.ScoreType, wts: float) -> bool: ...
    @overload
    def check2bsc(self, enumcore, double) -> bool: ...
    def eval_cd_2b_residues(self, match_res: pyrosetta.rosetta.core.conformation.Residue, target_res: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    def eval_longRange_2b_residue(self, match_res: pyrosetta.rosetta.core.conformation.Residue, target_res: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    def evaluate_residues(self, match_res: pyrosetta.rosetta.core.conformation.Residue, target_res: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    @overload
    def getCutoff(self) -> float: ...
    @overload
    def getCutoff(self) -> double: ...
    def get_score_function(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def require_all_target_residue_atom_coordinates(self) -> bool: ...
    @overload
    def require_all_target_residue_atom_coordinates(self) -> bool: ...
    @overload
    def require_target_atom_coordinate(self, target_atom_id: int) -> bool: ...
    @overload
    def require_target_atom_coordinate(self, unsignedlong) -> bool: ...
    @overload
    def setPose(self, ref_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def setPose(self, constclasscore) -> void: ...

class SecMatchEvaluatorFactory:
    def __init__(self) -> None: ...
    @staticmethod
    def create_SecMatchResiduePairEvaluatorOP(mcfi, downstream_inds: pyrosetta.rosetta.utility.vector1_unsigned_long, upstream_inds: pyrosetta.rosetta.utility.vector1_unsigned_long, SecMatchStr: str, upstream_pose: pyrosetta.rosetta.core.pose.Pose) -> SecMatchResiduePairEvaluator: ...

class SecMatchResiduePairEvaluator:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SecMatchResiduePairEvaluator) -> None: ...
    def assign(self) -> SecMatchResiduePairEvaluator: ...
    def candidate_res_atoms_reqd_near_target_atom(self, target_atom_id: int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def evaluate_residues(self, candidate_res: pyrosetta.rosetta.core.conformation.Residue, target_res: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    @overload
    def max_separation_dist_to_target_atom(self, target_atom_id: int) -> float: ...
    @overload
    def max_separation_dist_to_target_atom(self, unsignedlong) -> double: ...
    @overload
    def require_all_target_residue_atom_coordinates(self) -> bool: ...
    @overload
    def require_all_target_residue_atom_coordinates(self) -> bool: ...
    @overload
    def require_candidate_residue_atoms_to_lie_near_target_atom(self, target_atom_id: int) -> bool: ...
    @overload
    def require_candidate_residue_atoms_to_lie_near_target_atom(self, unsignedlong) -> bool: ...
    @overload
    def require_target_atom_coordinate(self, target_atom_id: int) -> bool: ...
    @overload
    def require_target_atom_coordinate(self, unsignedlong) -> bool: ...

class SecondaryMatchUpstreamResProcessor(pyrosetta.rosetta.protocols.match.upstream.UpstreamResidueProcessor):
    @overload
    def __init__(self, sec_matcher: SecondaryMatcherToUpstreamResidue) -> None: ...
    @overload
    def __init__(self, arg0: SecondaryMatchUpstreamResProcessor) -> None: ...
    @overload
    def __init__(self, arg0: SecondaryMatchUpstreamResProcessor) -> None: ...
    @overload
    def process_hit(self, hit: pyrosetta.rosetta.protocols.match.Hit, upstream_conformation: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def process_hit(self, constclassprotocols, constclasscore) -> void: ...

class SecondaryMatcherToDownstreamResidue(DownstreamAlgorithm):
    @overload
    def __init__(self, upstream_pose: pyrosetta.rosetta.core.pose.Pose, geom_cst_id: int) -> None: ...
    @overload
    def __init__(self, arg0: SecondaryMatcherToDownstreamResidue) -> None: ...
    @overload
    def __init__(self, arg0: SecondaryMatcherToDownstreamResidue) -> None: ...
    @overload
    def add_evaluator(self, evaluator: SecMatchResiduePairEvaluator, mcfi_id: int) -> None: ...
    @overload
    def add_evaluator(self, classstd, unsignedlong) -> void: ...
    def assign(self) -> SecondaryMatcherToDownstreamResidue: ...
    def build(self, scaffold_build_point_id: int, upstream_conf_id: int, upstream_residue: pyrosetta.rosetta.core.conformation.Residue) -> pyrosetta.rosetta.std.list_protocols_match_Hit_t: ...
    def build_hits_at_all_positions(self, *args, **kwargs): ...
    def clone(self) -> DownstreamAlgorithm: ...
    @overload
    def generates_primary_hits(self) -> bool: ...
    @overload
    def generates_primary_hits(self) -> bool: ...
    def hits_to_include_with_partial_match(self, *args, **kwargs): ...
    @overload
    def n_possible_hits_per_upstream_conformation(self) -> int: ...
    @overload
    def n_possible_hits_per_upstream_conformation(self) -> unsignedlong: ...
    @overload
    def respond_to_peripheral_hitlist_change(self, matcher: pyrosetta.rosetta.protocols.match.Matcher) -> None: ...
    @overload
    def respond_to_peripheral_hitlist_change(self, classprotocols) -> void: ...
    @overload
    def respond_to_primary_hitlist_change(self, matcher: pyrosetta.rosetta.protocols.match.Matcher, round_just_completed: int) -> None: ...
    @overload
    def respond_to_primary_hitlist_change(self, classprotocols, unsignedlong) -> void: ...
    @overload
    def set_catalytic_atoms(self, catalytic_atoms: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_catalytic_atoms(self, classutility) -> void: ...
    @overload
    def set_downstream_restype(self, downstream_restype: pyrosetta.rosetta.core.chemical.ResidueType) -> None: ...
    @overload
    def set_downstream_restype(self, classstd) -> void: ...
    @overload
    def set_focused_geomcst_id(self, focused_geomcst_id: int) -> None: ...
    @overload
    def set_focused_geomcst_id(self, unsignedlong) -> void: ...
    @overload
    def upstream_only(self) -> bool: ...
    @overload
    def upstream_only(self) -> bool: ...

class SecondaryMatcherToUpstreamResidue(DownstreamAlgorithm):
    @overload
    def __init__(self, geom_cst_id: int) -> None: ...
    @overload
    def __init__(self, arg0: SecondaryMatcherToUpstreamResidue) -> None: ...
    @overload
    def __init__(self, arg0: SecondaryMatcherToUpstreamResidue) -> None: ...
    def add_evaluator_for_target_restype(self, target_restype: pyrosetta.rosetta.core.chemical.ResidueType, evaluator: SecMatchResiduePairEvaluator, mcfi_id_for_evaluator: int) -> None: ...
    @overload
    def add_target_restype(self, target_restype: pyrosetta.rosetta.core.chemical.ResidueType) -> None: ...
    @overload
    def add_target_restype(self, classstd) -> void: ...
    def assign(self) -> SecondaryMatcherToUpstreamResidue: ...
    def build(self, scaffold_build_point_id: int, upstream_conf_id: int, upstream_residue: pyrosetta.rosetta.core.conformation.Residue) -> pyrosetta.rosetta.std.list_protocols_match_Hit_t: ...
    def build_hits_at_all_positions(self, *args, **kwargs): ...
    def clone(self) -> DownstreamAlgorithm: ...
    @overload
    def generates_primary_hits(self) -> bool: ...
    @overload
    def generates_primary_hits(self) -> bool: ...
    def hits_to_include_with_partial_match(self, *args, **kwargs): ...
    @overload
    def n_possible_hits_per_upstream_conformation(self) -> int: ...
    @overload
    def n_possible_hits_per_upstream_conformation(self) -> unsignedlong: ...
    @overload
    def prepare_for_match_enumeration(self, matcher: pyrosetta.rosetta.protocols.match.Matcher) -> None: ...
    @overload
    def prepare_for_match_enumeration(self, constclassprotocols) -> void: ...
    @overload
    def process_hit(self, hit: pyrosetta.rosetta.protocols.match.Hit, upstream_conformation: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def process_hit(self, constclassprotocols, constclasscore) -> void: ...
    @overload
    def respond_to_peripheral_hitlist_change(self, matcher: pyrosetta.rosetta.protocols.match.Matcher) -> None: ...
    @overload
    def respond_to_peripheral_hitlist_change(self, classprotocols) -> void: ...
    @overload
    def respond_to_primary_hitlist_change(self, matcher: pyrosetta.rosetta.protocols.match.Matcher, round_just_completed: int) -> None: ...
    @overload
    def respond_to_primary_hitlist_change(self, classprotocols, unsignedlong) -> void: ...
    @overload
    def set_target_geomcst_id(self, target_geomcst_id: int) -> None: ...
    @overload
    def set_target_geomcst_id(self, unsignedlong) -> void: ...
    @overload
    def upstream_only(self) -> bool: ...
    @overload
    def upstream_only(self) -> bool: ...

class TargetRotamerCoords:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TargetRotamerCoords) -> None: ...
    def assign(self) -> TargetRotamerCoords: ...
    def coord(self, restype_index: int, rotamer_index: int, which_atom: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def get_clash_checking(self, rotamer_index: int) -> bool: ...
    @overload
    def get_clash_checking(self, unsignedlong) -> bool: ...
    def get_coords_for_clash_check(self, rotamer_index: int) -> pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t: ...
    def get_ds_atom_ids_needed(self) -> pyrosetta.rosetta.utility.vector1_core_id_AtomID: ...
    def hit(self, restype_index: int, rotamer_index: int) -> pyrosetta.rosetta.protocols.match.Hit: ...
    @overload
    def n_atoms_for_restype(self, restype_id: int) -> int: ...
    @overload
    def n_atoms_for_restype(self, unsignedlong) -> unsignedlong: ...
    @overload
    def n_restypes(self) -> int: ...
    @overload
    def n_restypes(self) -> unsignedlong: ...
    @overload
    def n_rotamers_for_restype(self, restype_id: int) -> int: ...
    @overload
    def n_rotamers_for_restype(self, unsignedlong) -> unsignedlong: ...
    @overload
    def n_rots_total(self) -> int: ...
    @overload
    def n_rots_total(self) -> unsignedlong: ...
    def restype(self, restype_index: int) -> pyrosetta.rosetta.core.chemical.ResidueType: ...
    def restype_atomno(self, restype_index: int, which_atom: int) -> int: ...
    @overload
    def set_clash_check_types(self, n_rotamers: int) -> None: ...
    @overload
    def set_clash_check_types(self, unsignedlong) -> void: ...
    @overload
    def set_clash_checking(self, rotamer_index: int) -> None: ...
    @overload
    def set_clash_checking(self, unsignedlong) -> void: ...
    def set_coordinates_for_rotamer(self, restype_index: int, rotamer_index: int, hit: pyrosetta.rosetta.protocols.match.Hit, rescoords: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def set_coords_for_clash_check(self, rotamer_index: int, coords: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t) -> None: ...
    @overload
    def set_coords_for_clash_check(self, unsignedlong, classutility) -> void: ...
    @overload
    def set_ds_atom_ids_needed(self, atom_ids: pyrosetta.rosetta.utility.vector1_core_id_AtomID) -> None: ...
    @overload
    def set_ds_atom_ids_needed(self, classutility) -> void: ...
    @overload
    def set_num_restypes(self, n_restypes: int) -> None: ...
    @overload
    def set_num_restypes(self, unsignedlong) -> void: ...
    @overload
    def set_num_target_rotamers(self, n_rotamers_per_target_restype: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_num_target_rotamers(self, constclassutility) -> void: ...
    @overload
    def set_num_target_rotamers(self, target_restype_id: int, n_rotamers: int) -> None: ...
    @overload
    def set_required_atoms(self, restype_index: int, atom_required: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def set_required_atoms(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def set_restype(self, restype_index: int, restype: pyrosetta.rosetta.core.chemical.ResidueType) -> None: ...
    @overload
    def set_restype(self, unsignedlong, classstd) -> void: ...

class us_secmatch_hit_compare:
    def __init__(self) -> None: ...
    def __call__(self, lhs: pyrosetta.rosetta.protocols.match.Hit, rhs: pyrosetta.rosetta.protocols.match.Hit) -> bool: ...
