from Bio import BiopythonWarning as BiopythonWarning
from Bio.PDB.PDBIO import PDBIO as PDBIO
from _typeshed import Incomplete

class ChainSelector:
    chain_id: Incomplete
    start: Incomplete
    end: Incomplete
    model_id: Incomplete
    def __init__(self, chain_id, start, end, model_id: int = 0) -> None: ...
    def accept_model(self, model): ...
    def accept_chain(self, chain): ...
    def accept_residue(self, residue): ...
    def accept_atom(self, atom): ...

def extract(structure, chain_id, start, end, filename) -> None: ...
