from _typeshed import Incomplete

class PDBList:
    PDB_REF: str
    assemblies: Incomplete
    pdb_server: Incomplete
    local_pdb: Incomplete
    obsolete_pdb: Incomplete
    flat_tree: bool
    def __init__(self, server: str = 'https://files.wwpdb.org', pdb=None, obsolete_pdb=None, verbose: bool = True) -> None: ...
    @staticmethod
    def get_status_list(url): ...
    def get_recent_changes(self): ...
    def get_all_entries(self): ...
    def get_all_obsolete(self): ...
    def retrieve_pdb_file(self, pdb_code, obsolete: bool = False, pdir=None, file_format=None, overwrite: bool = False): ...
    def update_pdb(self, file_format=None, with_assemblies: bool = False) -> None: ...
    def download_pdb_files(self, pdb_codes: list[str], obsolete: bool = False, pdir: str | None = None, file_format: str | None = None, overwrite: bool = False, max_num_threads: int | None = None): ...
    def get_all_assemblies(self, file_format: str = '') -> list[tuple[str, str]]: ...
    def retrieve_assembly_file(self, pdb_code, assembly_num, pdir=None, file_format=None, overwrite: bool = False): ...
    def download_all_assemblies(self, listfile: str | None = None, file_format: str | None = None, max_num_threads: int | None = None): ...
    def download_entire_pdb(self, listfile: str | None = None, file_format: str | None = None, max_num_threads: int | None = None): ...
    def download_obsolete_entries(self, listfile: str | None = None, file_format: str | None = None, max_num_threads: int | None = None): ...
    def get_seqres_file(self, savefile: str = 'pdb_seqres.txt') -> None: ...
