import pyrosetta.rosetta.std
from typing import overload

class BadInput(IOError):
    @overload
    def __init__(self, arg0: BadInput) -> None: ...
    @overload
    def __init__(self, arg0: BadInput) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, file: str, line: int, msg: str) -> None: ...
    def assign(self) -> BadInput: ...

class Exception(pyrosetta.rosetta.std.exception):
    @overload
    def __init__(self, file: str, line: int, msg: str) -> None: ...
    @overload
    def __init__(self, arg0: Exception) -> None: ...
    @overload
    def __init__(self, arg0: Exception) -> None: ...
    @overload
    def add_msg(self, str: str) -> None: ...
    @overload
    def add_msg(self, conststd) -> void: ...
    def assign(self) -> Exception: ...
    @overload
    def crash_log(self) -> None: ...
    @overload
    def crash_log(self) -> void: ...
    @overload
    def display(self) -> None: ...
    @overload
    def display(self) -> void: ...
    def file(self) -> str: ...
    @overload
    def line(self) -> int: ...
    @overload
    def line(self) -> int: ...
    @overload
    def msg(self) -> str: ...
    @overload
    def msg(self, m: str) -> None: ...
    @overload
    def msg(self, conststd) -> void: ...
    @overload
    def prepend_to_msg(self, str: str) -> None: ...
    @overload
    def prepend_to_msg(self, conststd) -> void: ...
    def raw_msg(self) -> str: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def traceback(self) -> str: ...

class FileNotFound(IOError):
    @overload
    def __init__(self, file: str, line: int, not_found_file_name: str) -> None: ...
    @overload
    def __init__(self, arg0: FileNotFound) -> None: ...
    @overload
    def __init__(self, arg0: FileNotFound) -> None: ...
    def assign(self) -> FileNotFound: ...
    @overload
    def crash_log(self) -> None: ...
    @overload
    def crash_log(self) -> void: ...

class IOError(Exception):
    @overload
    def __init__(self, arg0: IOError) -> None: ...
    @overload
    def __init__(self, arg0: IOError) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def assign(self) -> IOError: ...

class KeyError(Exception):
    @overload
    def __init__(self, arg0: KeyError) -> None: ...
    @overload
    def __init__(self, arg0: KeyError) -> None: ...
    @overload
    def __init__(self, file: str, line: int, msg: str) -> None: ...
    def assign(self) -> KeyError: ...

class NullPointerError(RangeError):
    @overload
    def __init__(self, arg0: NullPointerError) -> None: ...
    @overload
    def __init__(self, arg0: NullPointerError) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, file: str, line: int, msg: str) -> None: ...
    def assign(self) -> NullPointerError: ...

class RangeError(Exception):
    @overload
    def __init__(self, arg0: RangeError) -> None: ...
    @overload
    def __init__(self, arg0: RangeError) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, file: str, line: int, msg: str) -> None: ...
    def assign(self) -> RangeError: ...

class RosettaScriptsOptionError(UserCorrectableIssue):
    @overload
    def __init__(self, arg0: RosettaScriptsOptionError) -> None: ...
    @overload
    def __init__(self, arg0: RosettaScriptsOptionError) -> None: ...
    @overload
    def __init__(self, file: str, line: int, msg: str) -> None: ...
    def assign(self) -> RosettaScriptsOptionError: ...

class UserCorrectableIssue(Exception):
    @overload
    def __init__(self, arg0: UserCorrectableIssue) -> None: ...
    @overload
    def __init__(self, arg0: UserCorrectableIssue) -> None: ...
    @overload
    def __init__(self, file: str, line: int, msg: str) -> None: ...
    def assign(self) -> UserCorrectableIssue: ...
    @overload
    def crash_log(self) -> None: ...
    @overload
    def crash_log(self) -> void: ...
    @overload
    def display(self) -> None: ...
    @overload
    def display(self) -> void: ...
