from typing import overload

class WidgetFactory_protocols_genetic_algorithm_EntityElementCreator_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: WidgetFactory_protocols_genetic_algorithm_EntityElementCreator_t) -> None: ...
    def assign(self) -> WidgetFactory_protocols_genetic_algorithm_EntityElementCreator_t: ...
    def factory_name(self) -> str: ...
    @overload
    def factory_register(self, creator) -> None: ...
    @overload
    def factory_register(self, classstd) -> void: ...
