from typing import overload

class AutoKey_utility_options_Option_utility_keys_Key_utility_keys_NoClient_t(Key):
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def assign(self, key: AutoKey_utility_options_Option_utility_keys_Key_utility_keys_NoClient_t) -> AutoKey_utility_options_Option_utility_keys_Key_utility_keys_NoClient_t: ...
    @overload
    def assign(self, key: Key) -> AutoKey_utility_options_Option_utility_keys_Key_utility_keys_NoClient_t: ...
    @overload
    def assign(self, key: Key) -> Key: ...
    @overload
    def clone(self) -> AutoKey_utility_options_Option_utility_keys_Key_utility_keys_NoClient_t: ...
    @overload
    def clone(self) -> Key: ...
    @overload
    def code(self) -> str: ...
    @overload
    def code(self, code_a: str) -> AutoKey_utility_options_Option_utility_keys_Key_utility_keys_NoClient_t: ...
    @overload
    def code(self) -> str: ...
    @overload
    def code(self, code_a: str) -> Key: ...
    @overload
    def id(self) -> str: ...
    @overload
    def id(self, id_a: str) -> AutoKey_utility_options_Option_utility_keys_Key_utility_keys_NoClient_t: ...
    @overload
    def id(self) -> str: ...
    @overload
    def id(self, id_a: str) -> Key: ...
    @overload
    def identifier(self) -> str: ...
    @overload
    def identifier(self, identifier_a: str) -> AutoKey_utility_options_Option_utility_keys_Key_utility_keys_NoClient_t: ...
    @overload
    def identifier(self) -> str: ...
    @overload
    def identifier(self, identifier_a: str) -> Key: ...
    @overload
    def load(self, arc) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    @staticmethod
    def n_key() -> int: ...
    @overload
    @staticmethod
    def n_key() -> unsignedlong: ...
    @overload
    def private_index(self) -> int: ...
    @overload
    def private_index(self) -> unsignedlong: ...
    @overload
    def private_index(self) -> int: ...
    @overload
    def private_index(self) -> unsignedlong: ...
    @overload
    def save(self, arc) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class Key:
    def __init__(self, *args, **kwargs) -> None: ...
    def assign(self, key: Key) -> Key: ...
    def clone(self) -> Key: ...
    @overload
    def code(self) -> str: ...
    @overload
    def code(self, code_a: str) -> Key: ...
    @overload
    def id(self) -> str: ...
    @overload
    def id(self, id_a: str) -> Key: ...
    @overload
    def identifier(self) -> str: ...
    @overload
    def identifier(self, identifier_a: str) -> Key: ...
    @overload
    def load(self, arc) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def private_index(self) -> int: ...
    @overload
    def private_index(self) -> unsignedlong: ...
    @overload
    def save(self, arc) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class Key2Tuple_double_double_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, key1_a: float, key2_a: float) -> None: ...
    @overload
    def __init__(self, arg0: Key2Tuple_double_double_t) -> None: ...
    def key1(self) -> float: ...
    def key2(self) -> float: ...

class Key2Tuple_unsigned_long_unsigned_long_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, key1_a: int, key2_a: int) -> None: ...
    @overload
    def __init__(self, arg0: Key2Tuple_unsigned_long_unsigned_long_t) -> None: ...
    def assign(self) -> Key2Tuple_unsigned_long_unsigned_long_t: ...
    def key1(self) -> int: ...
    def key2(self) -> int: ...

class Key3Tuple_protocols_loops_Loop_std_shared_ptr_core_kinematics_MoveMap_std_shared_ptr_core_kinematics_MoveMap_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, key1_a, key2_a, key3_a) -> None: ...
    @overload
    def __init__(self, arg0: Key3Tuple_protocols_loops_Loop_std_shared_ptr_core_kinematics_MoveMap_std_shared_ptr_core_kinematics_MoveMap_t) -> None: ...
    def assign(self) -> Key3Tuple_protocols_loops_Loop_std_shared_ptr_core_kinematics_MoveMap_std_shared_ptr_core_kinematics_MoveMap_t: ...
    def key1(self, *args, **kwargs): ...
    def key2(self, *args, **kwargs): ...
    def key3(self, *args, **kwargs): ...

class Key3Tuple_unsigned_long_unsigned_long_unsigned_long_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, key1_a: int, key2_a: int, key3_a: int) -> None: ...
    @overload
    def __init__(self, arg0: Key3Tuple_unsigned_long_unsigned_long_unsigned_long_t) -> None: ...
    def assign(self) -> Key3Tuple_unsigned_long_unsigned_long_unsigned_long_t: ...
    def key1(self) -> int: ...
    def key2(self) -> int: ...
    def key3(self) -> int: ...

class Key4Tuple_unsigned_long_unsigned_long_unsigned_long_unsigned_long_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, key1_a: int, key2_a: int, key3_a: int, key4_a: int) -> None: ...
    def key1(self) -> int: ...
    def key2(self) -> int: ...
    def key3(self) -> int: ...
    def key4(self) -> int: ...

class KeyLookup_utility_options_OptionKey_t:
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    @staticmethod
    def add(key) -> None: ...
    @overload
    @staticmethod
    def add(constclassutility) -> void: ...
    @overload
    @staticmethod
    def add(key, identifier: str) -> None: ...
    @overload
    @staticmethod
    def add(constclassutility, conststd) -> void: ...
    @overload
    @staticmethod
    def clear() -> None: ...
    @overload
    @staticmethod
    def clear() -> void: ...
    @overload
    @staticmethod
    def empty() -> bool: ...
    @overload
    @staticmethod
    def empty() -> bool: ...
    @overload
    @staticmethod
    def has(id: str) -> bool: ...
    @overload
    @staticmethod
    def has(conststd) -> bool: ...
    @overload
    @staticmethod
    def has(key) -> bool: ...
    @overload
    @staticmethod
    def has(constclassutility) -> bool: ...
    @staticmethod
    def key(*args, **kwargs): ...
    @overload
    @staticmethod
    def n_key() -> int: ...
    @overload
    @staticmethod
    def n_key() -> unsignedlong: ...
    @overload
    @staticmethod
    def size() -> int: ...
    @overload
    @staticmethod
    def size() -> unsignedlong: ...

class NoClient:
    def __init__(self) -> None: ...

class SmallKeyVector_utility_options_AnyOptionKey_utility_options_VariantOption_utility_options_ScalarOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_AnyOptionKey_utility_options_VariantOption_utility_options_ScalarOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_AnyOptionKey_utility_options_VariantOption_utility_options_ScalarOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_AnyOptionKey_utility_options_VariantOption_utility_options_ScalarOption_t) -> SmallKeyVector_utility_options_AnyOptionKey_utility_options_VariantOption_utility_options_ScalarOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_AnyOptionKey_utility_options_VariantOption_utility_options_ScalarOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_AnyOptionKey_utility_options_VariantOption_utility_options_ScalarOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_AnyOptionKey_utility_options_VariantOption_utility_options_ScalarOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_AnyVectorOptionKey_utility_options_VariantOption_utility_options_VectorOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_AnyVectorOptionKey_utility_options_VariantOption_utility_options_VectorOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_AnyVectorOptionKey_utility_options_VariantOption_utility_options_VectorOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_AnyVectorOptionKey_utility_options_VariantOption_utility_options_VectorOption_t) -> SmallKeyVector_utility_options_AnyVectorOptionKey_utility_options_VariantOption_utility_options_VectorOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_AnyVectorOptionKey_utility_options_VariantOption_utility_options_VectorOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_AnyVectorOptionKey_utility_options_VariantOption_utility_options_VectorOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_AnyVectorOptionKey_utility_options_VariantOption_utility_options_VectorOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_BooleanOptionKey_utility_options_BooleanOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_BooleanOptionKey_utility_options_BooleanOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_BooleanOptionKey_utility_options_BooleanOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_BooleanOptionKey_utility_options_BooleanOption_t) -> SmallKeyVector_utility_options_BooleanOptionKey_utility_options_BooleanOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_BooleanOptionKey_utility_options_BooleanOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_BooleanOptionKey_utility_options_BooleanOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_BooleanOptionKey_utility_options_BooleanOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_BooleanVectorOptionKey_utility_options_BooleanVectorOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_BooleanVectorOptionKey_utility_options_BooleanVectorOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_BooleanVectorOptionKey_utility_options_BooleanVectorOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_BooleanVectorOptionKey_utility_options_BooleanVectorOption_t) -> SmallKeyVector_utility_options_BooleanVectorOptionKey_utility_options_BooleanVectorOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_BooleanVectorOptionKey_utility_options_BooleanVectorOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_BooleanVectorOptionKey_utility_options_BooleanVectorOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_BooleanVectorOptionKey_utility_options_BooleanVectorOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_FileOptionKey_utility_options_FileOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_FileOptionKey_utility_options_FileOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_FileOptionKey_utility_options_FileOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_FileOptionKey_utility_options_FileOption_t) -> SmallKeyVector_utility_options_FileOptionKey_utility_options_FileOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_FileOptionKey_utility_options_FileOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_FileOptionKey_utility_options_FileOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_FileOptionKey_utility_options_FileOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_FileVectorOptionKey_utility_options_FileVectorOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_FileVectorOptionKey_utility_options_FileVectorOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_FileVectorOptionKey_utility_options_FileVectorOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_FileVectorOptionKey_utility_options_FileVectorOption_t) -> SmallKeyVector_utility_options_FileVectorOptionKey_utility_options_FileVectorOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_FileVectorOptionKey_utility_options_FileVectorOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_FileVectorOptionKey_utility_options_FileVectorOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_FileVectorOptionKey_utility_options_FileVectorOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_IntegerOptionKey_utility_options_IntegerOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_IntegerOptionKey_utility_options_IntegerOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_IntegerOptionKey_utility_options_IntegerOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_IntegerOptionKey_utility_options_IntegerOption_t) -> SmallKeyVector_utility_options_IntegerOptionKey_utility_options_IntegerOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_IntegerOptionKey_utility_options_IntegerOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_IntegerOptionKey_utility_options_IntegerOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_IntegerOptionKey_utility_options_IntegerOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_IntegerVectorOptionKey_utility_options_IntegerVectorOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_IntegerVectorOptionKey_utility_options_IntegerVectorOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_IntegerVectorOptionKey_utility_options_IntegerVectorOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_IntegerVectorOptionKey_utility_options_IntegerVectorOption_t) -> SmallKeyVector_utility_options_IntegerVectorOptionKey_utility_options_IntegerVectorOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_IntegerVectorOptionKey_utility_options_IntegerVectorOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_IntegerVectorOptionKey_utility_options_IntegerVectorOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_IntegerVectorOptionKey_utility_options_IntegerVectorOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_OptionKey_utility_options_OptionTypes_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_OptionKey_utility_options_OptionTypes_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_OptionKey_utility_options_OptionTypes_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_OptionKey_utility_options_OptionTypes_t) -> SmallKeyVector_utility_options_OptionKey_utility_options_OptionTypes_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_OptionKey_utility_options_OptionTypes_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_OptionKey_utility_options_OptionTypes_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constenumutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constenumutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constenumutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, a: SmallKeyVector_utility_options_OptionKey_utility_options_OptionTypes_t) -> None: ...
    @overload
    def swap(self, classutility, enumutility) -> void: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_PathOptionKey_utility_options_PathOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_PathOptionKey_utility_options_PathOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_PathOptionKey_utility_options_PathOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_PathOptionKey_utility_options_PathOption_t) -> SmallKeyVector_utility_options_PathOptionKey_utility_options_PathOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_PathOptionKey_utility_options_PathOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_PathOptionKey_utility_options_PathOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_PathOptionKey_utility_options_PathOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_PathVectorOptionKey_utility_options_PathVectorOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_PathVectorOptionKey_utility_options_PathVectorOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_PathVectorOptionKey_utility_options_PathVectorOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_PathVectorOptionKey_utility_options_PathVectorOption_t) -> SmallKeyVector_utility_options_PathVectorOptionKey_utility_options_PathVectorOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_PathVectorOptionKey_utility_options_PathVectorOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_PathVectorOptionKey_utility_options_PathVectorOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_PathVectorOptionKey_utility_options_PathVectorOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_RealOptionKey_utility_options_RealOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_RealOptionKey_utility_options_RealOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_RealOptionKey_utility_options_RealOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_RealOptionKey_utility_options_RealOption_t) -> SmallKeyVector_utility_options_RealOptionKey_utility_options_RealOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_RealOptionKey_utility_options_RealOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_RealOptionKey_utility_options_RealOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_RealOptionKey_utility_options_RealOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_RealVectorOptionKey_utility_options_RealVectorOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_RealVectorOptionKey_utility_options_RealVectorOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_RealVectorOptionKey_utility_options_RealVectorOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_RealVectorOptionKey_utility_options_RealVectorOption_t) -> SmallKeyVector_utility_options_RealVectorOptionKey_utility_options_RealVectorOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_RealVectorOptionKey_utility_options_RealVectorOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_RealVectorOptionKey_utility_options_RealVectorOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_RealVectorOptionKey_utility_options_RealVectorOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_ResidueChainVectorOptionKey_utility_options_ResidueChainVectorOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_ResidueChainVectorOptionKey_utility_options_ResidueChainVectorOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_ResidueChainVectorOptionKey_utility_options_ResidueChainVectorOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_ResidueChainVectorOptionKey_utility_options_ResidueChainVectorOption_t) -> SmallKeyVector_utility_options_ResidueChainVectorOptionKey_utility_options_ResidueChainVectorOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_ResidueChainVectorOptionKey_utility_options_ResidueChainVectorOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_ResidueChainVectorOptionKey_utility_options_ResidueChainVectorOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_ResidueChainVectorOptionKey_utility_options_ResidueChainVectorOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_StringOptionKey_utility_options_StringOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_StringOptionKey_utility_options_StringOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_StringOptionKey_utility_options_StringOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_StringOptionKey_utility_options_StringOption_t) -> SmallKeyVector_utility_options_StringOptionKey_utility_options_StringOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_StringOptionKey_utility_options_StringOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_StringOptionKey_utility_options_StringOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_StringOptionKey_utility_options_StringOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class SmallKeyVector_utility_options_StringVectorOptionKey_utility_options_StringVectorOption_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SmallKeyVector_utility_options_StringVectorOptionKey_utility_options_StringVectorOption_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, value) -> None: ...
    @overload
    def active(self, key) -> bool: ...
    @overload
    def active(self, constclassutility) -> bool: ...
    def add(self, key) -> SmallKeyVector_utility_options_StringVectorOptionKey_utility_options_StringVectorOption_t: ...
    @overload
    def assign(self, a: SmallKeyVector_utility_options_StringVectorOptionKey_utility_options_StringVectorOption_t) -> SmallKeyVector_utility_options_StringVectorOptionKey_utility_options_StringVectorOption_t: ...
    @overload
    def assign(self, value) -> SmallKeyVector_utility_options_StringVectorOptionKey_utility_options_StringVectorOption_t: ...
    @overload
    def assign(self, key, value) -> SmallKeyVector_utility_options_StringVectorOptionKey_utility_options_StringVectorOption_t: ...
    @overload
    def assign(self, num: int, value) -> None: ...
    @overload
    def assign(self, unsignedlong, constclassutility) -> void: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> unsignedlong: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def front(self, *args, **kwargs): ...
    @overload
    def has(self, key) -> bool: ...
    @overload
    def has(self, constclassutility) -> bool: ...
    @overload
    def inactive(self, key) -> bool: ...
    @overload
    def inactive(self, constclassutility) -> bool: ...
    def index(self, key) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> void: ...
    @overload
    def push_back(self, value) -> None: ...
    @overload
    def push_back(self, constclassutility) -> void: ...
    @overload
    def reserve(self, num: int) -> None: ...
    @overload
    def reserve(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def resize(self, num: int, value) -> None: ...
    @overload
    def resize(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def swap(self, a: SmallKeyVector_utility_options_StringVectorOptionKey_utility_options_StringVectorOption_t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...

class VariantKey_utility_options_OptionKey_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: VariantKey_utility_options_OptionKey_t) -> None: ...
    @overload
    def __init__(self, key_a) -> None: ...
    def assign(self, var: VariantKey_utility_options_OptionKey_t) -> VariantKey_utility_options_OptionKey_t: ...
    @overload
    def code(self) -> str: ...
    @overload
    def code(self, code_a: str) -> VariantKey_utility_options_OptionKey_t: ...
    @overload
    def id(self) -> str: ...
    @overload
    def id(self, id_a: str) -> VariantKey_utility_options_OptionKey_t: ...
    @overload
    def identifier(self) -> str: ...
    @overload
    def identifier(self, identifier_a: str) -> VariantKey_utility_options_OptionKey_t: ...
    @overload
    def private_index(self) -> int: ...
    @overload
    def private_index(self) -> unsignedlong: ...
    def __call__(self, *args, **kwargs): ...

def comparable(a: Key, b: Key) -> bool: ...
