import pyrosetta.rosetta.cppdb
import pyrosetta.rosetta.utility
from typing import ClassVar, overload

class DatabaseMode:
    class e:
        __members__: ClassVar[dict] = ...  # read-only
        __entries: ClassVar[dict] = ...
        mysql: ClassVar[DatabaseMode.e] = ...
        postgres: ClassVar[DatabaseMode.e] = ...
        sqlite3: ClassVar[DatabaseMode.e] = ...
        def __init__(self, value: int) -> None: ...
        def __and__(self, other: object) -> object: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> int: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> object: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: object) -> object: ...
        def __rand__(self, other: object) -> object: ...
        def __ror__(self, other: object) -> object: ...
        def __rxor__(self, other: object) -> object: ...
        def __xor__(self, other: object) -> object: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...
    mysql: ClassVar[DatabaseMode.e] = ...
    postgres: ClassVar[DatabaseMode.e] = ...
    sqlite3: ClassVar[DatabaseMode.e] = ...
    def __init__(self) -> None: ...

class DatabaseSessionManager(pyrosetta.rosetta.utility.SingletonBase_utility_sql_database_DatabaseSessionManager_t):
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def get_db_session(self, db_mode: DatabaseMode.e, transaction_mode: TransactionMode.e, chunk_size: int, db_name: str, pq_schema: str, host: str, user: str, password: str, port: int) -> session: ...
    @overload
    def get_db_session(self, db_mode: DatabaseMode.e, transaction_mode: TransactionMode.e, chunk_size: int, db_name: str, pq_schema: str, host: str, user: str, password: str, port: int, readonly: bool) -> session: ...
    @overload
    def get_db_session(self, db_mode: DatabaseMode.e, transaction_mode: TransactionMode.e, chunk_size: int, db_name: str, pq_schema: str, host: str, user: str, password: str, port: int, readonly: bool, db_partition: int) -> session: ...
    def get_session_mysql(self, database: str, transaction_mode: TransactionMode.e, chunk_size: int, host: str, user: str, password: str, port: int) -> session: ...
    def get_session_postgres(self, database: str, transaction_mode: TransactionMode.e, chunk_size: int, pq_schema: str, host: str, user: str, password: str, port: int) -> session: ...
    @overload
    def get_session_sqlite3(self, database: str) -> session: ...
    @overload
    def get_session_sqlite3(self, database: str, transaction_mode: TransactionMode.e) -> session: ...
    @overload
    def get_session_sqlite3(self, database: str, transaction_mode: TransactionMode.e, chunk_size: int) -> session: ...
    @overload
    def get_session_sqlite3(self, database: str, transaction_mode: TransactionMode.e, chunk_size: int, readonly: bool) -> session: ...
    @overload
    def get_session_sqlite3(self, database: str, transaction_mode: TransactionMode.e, chunk_size: int, readonly: bool, db_partition: int) -> session: ...

class TransactionMode:
    class e:
        __members__: ClassVar[dict] = ...  # read-only
        __entries: ClassVar[dict] = ...
        chunk: ClassVar[TransactionMode.e] = ...
        none: ClassVar[TransactionMode.e] = ...
        standard: ClassVar[TransactionMode.e] = ...
        def __init__(self, value: int) -> None: ...
        def __and__(self, other: object) -> object: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> int: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> object: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: object) -> object: ...
        def __rand__(self, other: object) -> object: ...
        def __ror__(self, other: object) -> object: ...
        def __rxor__(self, other: object) -> object: ...
        def __xor__(self, other: object) -> object: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...
    chunk: ClassVar[TransactionMode.e] = ...
    none: ClassVar[TransactionMode.e] = ...
    standard: ClassVar[TransactionMode.e] = ...
    def __init__(self) -> None: ...

class session(pyrosetta.rosetta.cppdb.session):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: session) -> None: ...
    def assign(self) -> session: ...
    @overload
    def begin_transaction(self) -> None: ...
    @overload
    def begin_transaction(self) -> void: ...
    @overload
    def commit_transaction(self) -> None: ...
    @overload
    def commit_transaction(self) -> void: ...
    @overload
    def force_commit_transaction(self) -> None: ...
    @overload
    def force_commit_transaction(self) -> void: ...
    @overload
    def get_chunk_size(self) -> int: ...
    @overload
    def get_chunk_size(self) -> unsignedlong: ...
    def get_db_mode(self) -> DatabaseMode.e: ...
    def get_db_name(self) -> str: ...
    @overload
    def get_db_partition(self) -> int: ...
    @overload
    def get_db_partition(self) -> long: ...
    def get_pq_schema(self) -> str: ...
    def get_transaction_mode(self) -> TransactionMode.e: ...
    @overload
    def is_db_partitioned(self) -> bool: ...
    @overload
    def is_db_partitioned(self) -> bool: ...
    def open_mysql_session(self, host: str, user: str, password: str, port: int) -> None: ...
    def open_postgres_session(self, host: str, user: str, password: str, port: int) -> None: ...
    @overload
    def open_sqlite3_session(self) -> None: ...
    @overload
    def open_sqlite3_session(self, read_only: bool) -> None: ...
    @overload
    def open_sqlite3_session(self, bool) -> void: ...
    @overload
    def set_chunk_size(self, chunk_size: int) -> None: ...
    @overload
    def set_chunk_size(self, constunsignedlong) -> void: ...
    @overload
    def set_db_mode(self, db_mode: DatabaseMode.e) -> None: ...
    @overload
    def set_db_mode(self, constenumutility) -> void: ...
    @overload
    def set_db_name(self, db_name: str) -> None: ...
    @overload
    def set_db_name(self, conststd) -> void: ...
    @overload
    def set_db_partition(self, db_partition: int) -> None: ...
    @overload
    def set_db_partition(self, long) -> void: ...
    @overload
    def set_pq_schema(self, pq_schema: str) -> None: ...
    @overload
    def set_pq_schema(self, conststd) -> void: ...
    @overload
    def set_transaction_mode(self, transaction_mode: TransactionMode.e) -> None: ...
    @overload
    def set_transaction_mode(self, constenumutility) -> void: ...

class transaction(pyrosetta.rosetta.cppdb.transaction):
    def __init__(self, session: session) -> None: ...

def database_mode_from_name(database_mode: str) -> DatabaseMode.e: ...
def name_from_database_mode(database_mode: DatabaseMode.e) -> str: ...
def name_from_transaction_mode(transaction_mode: TransactionMode.e) -> str: ...
def transaction_mode_from_name(transaction_mode: str) -> TransactionMode.e: ...
