import pyrosetta.rosetta
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import ClassVar, overload

se_choice_opt: CTGenSubelementBehavior
se_choice_req: CTGenSubelementBehavior
se_none: CTGenSubelementBehavior
se_ordered_sets: CTGenSubelementBehavior
se_repeatable: CTGenSubelementBehavior
se_single_opt: CTGenSubelementBehavior
se_single_req: CTGenSubelementBehavior
se_single_req_ordered: CTGenSubelementBehavior
xs_boolean: XMLSchemaDataType
xs_common: XMLSchemaDataType
xs_custom: XMLSchemaDataType
xs_date: XMLSchemaDataType
xs_decimal: XMLSchemaDataType
xs_element_is_abstract: XMLSchemaElementCategory
xs_element_is_complex_type_w_definition: XMLSchemaElementCategory
xs_element_is_element_reference: XMLSchemaElementCategory
xs_element_is_type_reference: XMLSchemaElementCategory
xs_integer: XMLSchemaDataType
xs_string: XMLSchemaDataType
xs_time: XMLSchemaDataType
xsct_bool_cslist: XMLSchemaCommonType
xsct_bool_wsslist: XMLSchemaCommonType
xsct_canonical_res_char: XMLSchemaCommonType
xsct_chain_cslist: XMLSchemaCommonType
xsct_char: XMLSchemaCommonType
xsct_dssp_string: XMLSchemaCommonType
xsct_int_cslist: XMLSchemaCommonType
xsct_int_wsslist: XMLSchemaCommonType
xsct_minimizer_type: XMLSchemaCommonType
xsct_nnegative_int_cslist: XMLSchemaCommonType
xsct_nnegative_int_wsslist: XMLSchemaCommonType
xsct_non_negative_integer: XMLSchemaCommonType
xsct_none: XMLSchemaCommonType
xsct_packer_palette: XMLSchemaCommonType
xsct_pose_cached_task_operation: XMLSchemaCommonType
xsct_positive_integer: XMLSchemaCommonType
xsct_positive_integer_cslist: XMLSchemaCommonType
xsct_positive_integer_wsslist: XMLSchemaCommonType
xsct_real: XMLSchemaCommonType
xsct_real_cslist: XMLSchemaCommonType
xsct_real_cslist_w_ws: XMLSchemaCommonType
xsct_real_wsslist: XMLSchemaCommonType
xsct_refpose_enabled_residue_number: XMLSchemaCommonType
xsct_refpose_enabled_residue_number_cslist: XMLSchemaCommonType
xsct_residue_number: XMLSchemaCommonType
xsct_residue_number_cslist: XMLSchemaCommonType
xsct_rosetta_autobool: XMLSchemaCommonType
xsct_rosetta_bool: XMLSchemaCommonType
xsct_size_cs_pair: XMLSchemaCommonType
xsct_string_cslist: XMLSchemaCommonType
xsct_task_operation: XMLSchemaCommonType
xsct_task_operation_comma_separated_list: XMLSchemaCommonType
xsmgt_all: XMLSchemaModelGroupType
xsmgt_choice: XMLSchemaModelGroupType
xsmgt_group: XMLSchemaModelGroupType
xsmgt_sequence: XMLSchemaModelGroupType
xsminmax_unbounded: XMLSchemaMinOccursMaxOccurs
xsminmax_unspecified: XMLSchemaMinOccursMaxOccurs
xsr_enumeration: XMLSchemaRestrictionType
xsr_fractionDigits: XMLSchemaRestrictionType
xsr_length: XMLSchemaRestrictionType
xsr_maxExclusive: XMLSchemaRestrictionType
xsr_maxInclusive: XMLSchemaRestrictionType
xsr_maxLength: XMLSchemaRestrictionType
xsr_minExclusive: XMLSchemaRestrictionType
xsr_minInclusive: XMLSchemaRestrictionType
xsr_minLength: XMLSchemaRestrictionType
xsr_pattern: XMLSchemaRestrictionType
xsr_totalDigits: XMLSchemaRestrictionType
xsr_whitespace: XMLSchemaRestrictionType

class AutoBool:
    __members__: ClassVar[dict] = ...  # read-only
    Auto: ClassVar[AutoBool] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class CTGenSubelementBehavior:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    se_choice_opt: ClassVar[CTGenSubelementBehavior] = ...
    se_choice_req: ClassVar[CTGenSubelementBehavior] = ...
    se_none: ClassVar[CTGenSubelementBehavior] = ...
    se_ordered_sets: ClassVar[CTGenSubelementBehavior] = ...
    se_repeatable: ClassVar[CTGenSubelementBehavior] = ...
    se_single_opt: ClassVar[CTGenSubelementBehavior] = ...
    se_single_req: ClassVar[CTGenSubelementBehavior] = ...
    se_single_req_ordered: ClassVar[CTGenSubelementBehavior] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class Tag:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Tag) -> None: ...
    @overload
    def addTag(self, tag: Tag) -> None: ...
    @overload
    def addTag(self, classstd) -> void: ...
    def assign(self, other: Tag) -> Tag: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    def clone(self) -> Tag: ...
    @overload
    @staticmethod
    def create(_in: pyrosetta.rosetta.std.istream) -> Tag: ...
    @overload
    @staticmethod
    def create(instring: str) -> Tag: ...
    @overload
    def die_for_unaccessed_options(self) -> None: ...
    @overload
    def die_for_unaccessed_options(self) -> void: ...
    @overload
    def die_for_unaccessed_options_recursively(self) -> None: ...
    @overload
    def die_for_unaccessed_options_recursively(self) -> void: ...
    def getName(self) -> str: ...
    @overload
    def getOption(self, key: str, t_default: bool) -> bool: ...
    @overload
    def getOption(self, key: str, t_default: AutoBool) -> AutoBool: ...
    @overload
    def getOption(self, key: str, default_int: int) -> int: ...
    @overload
    def getOption(self, conststd, constint) -> unsignedlong: ...
    @overload
    def getOption(self, key: str, default_int: int) -> int: ...
    @overload
    def getOption(self, conststd, constint) -> int: ...
    @overload
    def getOption(self, key: str, default_int: int) -> int: ...
    @overload
    def getOption(self, conststd, constint) -> longlong: ...
    @overload
    def getOption(self, key: str, default_as_string_literal: str) -> bool: ...
    @overload
    def getOption(self, key: str, default_as_string_literal: str) -> AutoBool: ...
    @overload
    def getOption(self, key: str, default_as_string_literal: str) -> str: ...
    @overload
    def getOption(self, key: str) -> bool: ...
    @overload
    def getOption(self, conststd) -> bool: ...
    @overload
    def getOption(self, key: str) -> AutoBool: ...
    def getOptions(self) -> pyrosetta.rosetta.std.map_std_string_std_string: ...
    def getParent(self) -> pyrosetta.rosetta.std.weak_ptr_const_utility_tag_Tag_t: ...
    def getTag(self, name: str) -> Tag: ...
    @overload
    def getTags(self) -> pyrosetta.rosetta.utility.vector0_std_shared_ptr_const_utility_tag_Tag_t: ...
    @overload
    def getTags(self, name: str) -> pyrosetta.rosetta.utility.vector0_std_shared_ptr_const_utility_tag_Tag_t: ...
    @overload
    def get_option_bool(self, key: str) -> bool: ...
    @overload
    def get_option_bool(self, conststd) -> bool: ...
    @overload
    def get_option_bool(self, key: str, default_as_string_literal: str) -> bool: ...
    @overload
    def get_option_bool(self, key: str, t_default: bool) -> bool: ...
    @overload
    def get_option_int(self, key: str) -> int: ...
    @overload
    def get_option_int(self, conststd) -> int: ...
    @overload
    def get_option_int(self, key: str, t_default: int) -> int: ...
    @overload
    def get_option_real(self, key: str) -> float: ...
    @overload
    def get_option_real(self, conststd) -> double: ...
    @overload
    def get_option_real(self, key: str, t_default: float) -> float: ...
    @overload
    def get_option_size(self, key: str) -> int: ...
    @overload
    def get_option_size(self, conststd) -> unsignedlong: ...
    @overload
    def get_option_size(self, key: str, t_default: int) -> int: ...
    @overload
    def get_option_string(self, key: str) -> str: ...
    @overload
    def get_option_string(self, key: str, t_default: str) -> str: ...
    def get_self_ptr(self) -> Tag: ...
    def get_self_weak_ptr(self) -> pyrosetta.rosetta.std.weak_ptr_utility_tag_Tag_t: ...
    @overload
    def hasOption(self, key: str) -> bool: ...
    @overload
    def hasOption(self, conststd) -> bool: ...
    @overload
    def hasTag(self, name: str) -> bool: ...
    @overload
    def hasTag(self, conststd) -> bool: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read(self, std) -> void: ...
    @overload
    def read(self, tag_string: str) -> None: ...
    @overload
    def read(self, conststd) -> void: ...
    @overload
    def reset_accessed_options(self) -> None: ...
    @overload
    def reset_accessed_options(self) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def setAccessed(self, key: str) -> None: ...
    @overload
    def setAccessed(self, conststd) -> void: ...
    @overload
    def setName(self, name: str) -> None: ...
    @overload
    def setName(self, conststd) -> void: ...
    @overload
    def setOptions(self, options: pyrosetta.rosetta.std.map_std_string_std_string) -> None: ...
    @overload
    def setOptions(self, constclassstd, std) -> void: ...
    def set_quote_options(self, *args, **kwargs): ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def to_string(self) -> str: ...
    @overload
    def to_string(self, num_tabs: int) -> str: ...
    @overload
    def write(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def write(self, out: pyrosetta.rosetta.std.ostream, num_tabs: int) -> None: ...
    @overload
    def write(self, std, int) -> void: ...
    def __getitem__(self, key: str) -> Tag: ...

class XMLErrorHandler:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: XMLErrorHandler) -> None: ...
    def assign(self) -> XMLErrorHandler: ...
    def errors(self) -> pyrosetta.rosetta.std.list_std_string_t: ...
    @overload
    def handle_xml_error(self, message: str, line: int) -> None: ...
    @overload
    def handle_xml_error(self, conststd, int) -> void: ...
    @overload
    def handle_xml_warning(self, message: str, line: int) -> None: ...
    @overload
    def handle_xml_warning(self, conststd, int) -> void: ...
    @overload
    def pop_node(self) -> None: ...
    @overload
    def pop_node(self) -> void: ...
    def push_node(self, node: pyrosetta.rosetta._xmlNode) -> None: ...
    @overload
    def set_file_contents(self, file_contents: str) -> None: ...
    @overload
    def set_file_contents(self, conststd) -> void: ...
    def warnings(self) -> pyrosetta.rosetta.std.list_std_string_t: ...

class XMLSchemaAttribute(XMLSchemaTopLevelElement):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaAttribute) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaAttribute) -> None: ...
    def assign(self) -> XMLSchemaAttribute: ...
    @staticmethod
    def attribute_w_default(name: str, type: XMLSchemaType, desc: str, default_value: str) -> XMLSchemaAttribute: ...
    def default_value(self, setting: str) -> XMLSchemaAttribute: ...
    def description(self, setting: str) -> XMLSchemaAttribute: ...
    def element_name(self) -> str: ...
    def is_required(self, setting: bool) -> XMLSchemaAttribute: ...
    def name(self, setting: str) -> XMLSchemaAttribute: ...
    @overload
    def prepare_for_output(self, xsd) -> None: ...
    @overload
    def prepare_for_output(self, classutility) -> void: ...
    @staticmethod
    def required_attribute(name: str, type: XMLSchemaType, desc: str) -> XMLSchemaAttribute: ...
    @overload
    def type(self, setting: XMLSchemaType) -> XMLSchemaAttribute: ...
    @overload
    def type(self) -> XMLSchemaType: ...
    @overload
    def write_definition(self, indentation: int, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def write_definition(self, int, std) -> void: ...

class XMLSchemaCommonType:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    xsct_bool_cslist: ClassVar[XMLSchemaCommonType] = ...
    xsct_bool_wsslist: ClassVar[XMLSchemaCommonType] = ...
    xsct_canonical_res_char: ClassVar[XMLSchemaCommonType] = ...
    xsct_chain_cslist: ClassVar[XMLSchemaCommonType] = ...
    xsct_char: ClassVar[XMLSchemaCommonType] = ...
    xsct_dssp_string: ClassVar[XMLSchemaCommonType] = ...
    xsct_int_cslist: ClassVar[XMLSchemaCommonType] = ...
    xsct_int_wsslist: ClassVar[XMLSchemaCommonType] = ...
    xsct_minimizer_type: ClassVar[XMLSchemaCommonType] = ...
    xsct_nnegative_int_cslist: ClassVar[XMLSchemaCommonType] = ...
    xsct_nnegative_int_wsslist: ClassVar[XMLSchemaCommonType] = ...
    xsct_non_negative_integer: ClassVar[XMLSchemaCommonType] = ...
    xsct_none: ClassVar[XMLSchemaCommonType] = ...
    xsct_packer_palette: ClassVar[XMLSchemaCommonType] = ...
    xsct_pose_cached_task_operation: ClassVar[XMLSchemaCommonType] = ...
    xsct_positive_integer: ClassVar[XMLSchemaCommonType] = ...
    xsct_positive_integer_cslist: ClassVar[XMLSchemaCommonType] = ...
    xsct_positive_integer_wsslist: ClassVar[XMLSchemaCommonType] = ...
    xsct_real: ClassVar[XMLSchemaCommonType] = ...
    xsct_real_cslist: ClassVar[XMLSchemaCommonType] = ...
    xsct_real_cslist_w_ws: ClassVar[XMLSchemaCommonType] = ...
    xsct_real_wsslist: ClassVar[XMLSchemaCommonType] = ...
    xsct_refpose_enabled_residue_number: ClassVar[XMLSchemaCommonType] = ...
    xsct_refpose_enabled_residue_number_cslist: ClassVar[XMLSchemaCommonType] = ...
    xsct_residue_number: ClassVar[XMLSchemaCommonType] = ...
    xsct_residue_number_cslist: ClassVar[XMLSchemaCommonType] = ...
    xsct_rosetta_autobool: ClassVar[XMLSchemaCommonType] = ...
    xsct_rosetta_bool: ClassVar[XMLSchemaCommonType] = ...
    xsct_size_cs_pair: ClassVar[XMLSchemaCommonType] = ...
    xsct_string_cslist: ClassVar[XMLSchemaCommonType] = ...
    xsct_task_operation: ClassVar[XMLSchemaCommonType] = ...
    xsct_task_operation_comma_separated_list: ClassVar[XMLSchemaCommonType] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class XMLSchemaComplexType(XMLSchemaTopLevelElement):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaComplexType) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaComplexType) -> None: ...
    def add_attribute(self, attribute: XMLSchemaAttribute) -> XMLSchemaComplexType: ...
    def add_attributes(self, attributes: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> XMLSchemaComplexType: ...
    def assign(self) -> XMLSchemaComplexType: ...
    def description(self, setting: str) -> XMLSchemaComplexType: ...
    def element_name(self) -> str: ...
    def name(self, setting: str) -> XMLSchemaComplexType: ...
    @overload
    def prepare_for_output(self, xsd) -> None: ...
    @overload
    def prepare_for_output(self, classutility) -> void: ...
    def set_model_group(self, model_group: XMLSchemaModelGroup) -> XMLSchemaComplexType: ...
    @overload
    def write_definition(self, indentation: int, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def write_definition(self, int, std) -> void: ...

class XMLSchemaComplexTypeGenerator:
    def __init__(self) -> None: ...
    def add_attribute(self, attribute: XMLSchemaAttribute) -> XMLSchemaComplexTypeGenerator: ...
    def add_attributes(self, attributes: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> XMLSchemaComplexTypeGenerator: ...
    @overload
    def add_optional_name_attribute(self) -> XMLSchemaComplexTypeGenerator: ...
    @overload
    def add_optional_name_attribute(self, desc: str) -> XMLSchemaComplexTypeGenerator: ...
    def add_ordered_subelement_set_as_optional(self, subelements: XMLSchemaSimpleSubelementList) -> XMLSchemaComplexTypeGenerator: ...
    def add_ordered_subelement_set_as_pick_one(self, subelements: XMLSchemaSimpleSubelementList) -> XMLSchemaComplexTypeGenerator: ...
    def add_ordered_subelement_set_as_pick_one_or_none(self, subelements: XMLSchemaSimpleSubelementList) -> XMLSchemaComplexTypeGenerator: ...
    def add_ordered_subelement_set_as_repeatable(self, subelements: XMLSchemaSimpleSubelementList) -> XMLSchemaComplexTypeGenerator: ...
    def add_ordered_subelement_set_as_required(self, subelements: XMLSchemaSimpleSubelementList) -> XMLSchemaComplexTypeGenerator: ...
    @overload
    def add_required_name_attribute(self) -> XMLSchemaComplexTypeGenerator: ...
    @overload
    def add_required_name_attribute(self, desc: str) -> XMLSchemaComplexTypeGenerator: ...
    def complex_type_naming_func(self, *args, **kwargs): ...
    def description(self) -> XMLSchemaComplexTypeGenerator: ...
    def element_name(self) -> XMLSchemaComplexTypeGenerator: ...
    def set_subelements_pick_one(self, subelements: XMLSchemaSimpleSubelementList) -> XMLSchemaComplexTypeGenerator: ...
    def set_subelements_pick_one_or_none(self, subelements: XMLSchemaSimpleSubelementList) -> XMLSchemaComplexTypeGenerator: ...
    @overload
    def set_subelements_repeatable(self, subelements: XMLSchemaSimpleSubelementList) -> XMLSchemaComplexTypeGenerator: ...
    @overload
    def set_subelements_repeatable(self, subelements: XMLSchemaSimpleSubelementList, min_occurs: int) -> XMLSchemaComplexTypeGenerator: ...
    @overload
    def set_subelements_repeatable(self, subelements: XMLSchemaSimpleSubelementList, min_occurs: int, max_occurs: int) -> XMLSchemaComplexTypeGenerator: ...
    def set_subelements_single_appearance_optional(self, subelements: XMLSchemaSimpleSubelementList) -> XMLSchemaComplexTypeGenerator: ...
    def set_subelements_single_appearance_required(self, subelements: XMLSchemaSimpleSubelementList) -> XMLSchemaComplexTypeGenerator: ...
    def set_subelements_single_appearance_required_and_ordered(self, subelements: XMLSchemaSimpleSubelementList) -> XMLSchemaComplexTypeGenerator: ...
    def subelement_behavior(self) -> CTGenSubelementBehavior: ...
    @overload
    def write_complex_type_to_schema(self, xsd: XMLSchemaDefinition) -> None: ...
    @overload
    def write_complex_type_to_schema(self, classutility) -> void: ...

class XMLSchemaDataType:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    xs_boolean: ClassVar[XMLSchemaDataType] = ...
    xs_common: ClassVar[XMLSchemaDataType] = ...
    xs_custom: ClassVar[XMLSchemaDataType] = ...
    xs_date: ClassVar[XMLSchemaDataType] = ...
    xs_decimal: ClassVar[XMLSchemaDataType] = ...
    xs_integer: ClassVar[XMLSchemaDataType] = ...
    xs_string: ClassVar[XMLSchemaDataType] = ...
    xs_time: ClassVar[XMLSchemaDataType] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class XMLSchemaDefinition:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaDefinition) -> None: ...
    @overload
    def add_top_level_element(self, element: XMLSchemaTopLevelElement) -> None: ...
    @overload
    def add_top_level_element(self, constclassutility) -> void: ...
    def assign(self) -> XMLSchemaDefinition: ...
    def full_definition(self) -> str: ...
    @overload
    def has_top_level_element(self, element_name: str) -> bool: ...
    @overload
    def has_top_level_element(self, conststd) -> bool: ...
    @overload
    def human_readable_summary(self) -> str: ...
    @overload
    def human_readable_summary(self, component_name: str) -> str: ...
    @overload
    def human_readable_summary(self, component_name: str, component_type: str) -> str: ...
    @overload
    def human_readable_summary(self, component_name: str, component_type: str, citation_text: str) -> str: ...
    @overload
    def include_citation_info(self) -> bool: ...
    @overload
    def include_citation_info(self) -> bool: ...
    @overload
    def include_citation_info(self, setting: bool) -> None: ...
    @overload
    def include_citation_info(self, bool) -> void: ...

class XMLSchemaElement(XMLSchemaParticle):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaElement) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaElement) -> None: ...
    def assign(self) -> XMLSchemaElement: ...
    def element_name(self) -> str: ...
    def element_type_def(self, setting: XMLSchemaComplexType) -> XMLSchemaElement: ...
    def name(self, setting: str) -> XMLSchemaElement: ...
    @overload
    def prepare_for_output(self, xsd) -> None: ...
    @overload
    def prepare_for_output(self, classutility) -> void: ...
    def reference_name(self, setting: str) -> XMLSchemaElement: ...
    def set_abstract(self) -> XMLSchemaElement: ...
    def substitution_group(self, setting: str) -> XMLSchemaElement: ...
    def type_name(self, setting: XMLSchemaType) -> XMLSchemaElement: ...
    @overload
    def write_definition(self, indentation: int, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def write_definition(self, int, std) -> void: ...

class XMLSchemaElementCategory:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    xs_element_is_abstract: ClassVar[XMLSchemaElementCategory] = ...
    xs_element_is_complex_type_w_definition: ClassVar[XMLSchemaElementCategory] = ...
    xs_element_is_element_reference: ClassVar[XMLSchemaElementCategory] = ...
    xs_element_is_type_reference: ClassVar[XMLSchemaElementCategory] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class XMLSchemaMinOccursMaxOccurs:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    xsminmax_unbounded: ClassVar[XMLSchemaMinOccursMaxOccurs] = ...
    xsminmax_unspecified: ClassVar[XMLSchemaMinOccursMaxOccurs] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class XMLSchemaModelGroup(XMLSchemaParticle):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, type: XMLSchemaModelGroupType) -> None: ...
    @overload
    def __init__(self, type: XMLSchemaModelGroupType, particles: pyrosetta.rosetta.std.list_std_shared_ptr_const_utility_tag_XMLSchemaParticle_t) -> None: ...
    @overload
    def __init__(self, group_name: str) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaModelGroup) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaModelGroup) -> None: ...
    def append_particle(self, particle: XMLSchemaParticle) -> XMLSchemaModelGroup: ...
    def append_particles(self, particles: pyrosetta.rosetta.std.list_std_shared_ptr_const_utility_tag_XMLSchemaParticle_t) -> XMLSchemaModelGroup: ...
    def assign(self) -> XMLSchemaModelGroup: ...
    def element_name(self) -> str: ...
    def group_name(self, name: str) -> XMLSchemaModelGroup: ...
    @overload
    def prepare_for_output(self, xsd) -> None: ...
    @overload
    def prepare_for_output(self, classutility) -> void: ...
    def type(self, type: XMLSchemaModelGroupType) -> XMLSchemaModelGroup: ...
    @overload
    def write_definition(self, indentation: int, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def write_definition(self, int, std) -> void: ...

class XMLSchemaModelGroupType:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    xsmgt_all: ClassVar[XMLSchemaModelGroupType] = ...
    xsmgt_choice: ClassVar[XMLSchemaModelGroupType] = ...
    xsmgt_group: ClassVar[XMLSchemaModelGroupType] = ...
    xsmgt_sequence: ClassVar[XMLSchemaModelGroupType] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class XMLSchemaParticle(XMLSchemaTopLevelElement):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaParticle) -> None: ...
    def assign(self) -> XMLSchemaParticle: ...
    @overload
    def max_occurs(self, setting: int) -> XMLSchemaParticle: ...
    @overload
    def max_occurs(self) -> int: ...
    @overload
    def max_occurs(self) -> int: ...
    @overload
    def min_occurs(self, setting: int) -> XMLSchemaParticle: ...
    @overload
    def min_occurs(self) -> int: ...
    @overload
    def min_occurs(self) -> int: ...

class XMLSchemaRepeatableCTNode:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaRepeatableCTNode) -> None: ...
    def add_child(self, child_element: XMLSchemaRepeatableCTNode) -> XMLSchemaRepeatableCTNode: ...
    def assign(self) -> XMLSchemaRepeatableCTNode: ...
    def get_self_ptr(self) -> XMLSchemaRepeatableCTNode: ...
    def get_self_weak_ptr(self) -> pyrosetta.rosetta.std.weak_ptr_utility_tag_XMLSchemaRepeatableCTNode_t: ...
    @overload
    def recursively_write_ct_to_schema(self, xsd: XMLSchemaDefinition) -> None: ...
    @overload
    def recursively_write_ct_to_schema(self, classutility) -> void: ...
    def set_already_defined_element(self, *args, **kwargs): ...
    def set_already_defined_element_w_alt_name(self, *args, **kwargs): ...
    def set_element_w_attributes(self, name: str, atts: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t, description: str) -> XMLSchemaRepeatableCTNode: ...
    def set_group_subelement(self, *args, **kwargs): ...
    def set_kids_naming_func(self, *args, **kwargs): ...
    def set_root_node_naming_func(self, *args, **kwargs): ...

class XMLSchemaRestriction(XMLSchemaTopLevelElement):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaRestriction) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaRestriction) -> None: ...
    @overload
    def add_restriction(self, type: XMLSchemaRestrictionType, value: str) -> None: ...
    @overload
    def add_restriction(self, enumutility, conststd) -> void: ...
    def assign(self) -> XMLSchemaRestriction: ...
    @overload
    def base_type(self, setting: XMLSchemaType) -> None: ...
    @overload
    def base_type(self, classutility) -> void: ...
    def element_name(self) -> str: ...
    @overload
    def name(self, setting: str) -> None: ...
    @overload
    def name(self, conststd) -> void: ...
    @overload
    def prepare_for_output(self, xsd) -> None: ...
    @overload
    def prepare_for_output(self, classutility) -> void: ...
    @overload
    def write_definition(self, indentation: int, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def write_definition(self, int, std) -> void: ...

class XMLSchemaRestrictionType:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    xsr_enumeration: ClassVar[XMLSchemaRestrictionType] = ...
    xsr_fractionDigits: ClassVar[XMLSchemaRestrictionType] = ...
    xsr_length: ClassVar[XMLSchemaRestrictionType] = ...
    xsr_maxExclusive: ClassVar[XMLSchemaRestrictionType] = ...
    xsr_maxInclusive: ClassVar[XMLSchemaRestrictionType] = ...
    xsr_maxLength: ClassVar[XMLSchemaRestrictionType] = ...
    xsr_minExclusive: ClassVar[XMLSchemaRestrictionType] = ...
    xsr_minInclusive: ClassVar[XMLSchemaRestrictionType] = ...
    xsr_minLength: ClassVar[XMLSchemaRestrictionType] = ...
    xsr_pattern: ClassVar[XMLSchemaRestrictionType] = ...
    xsr_totalDigits: ClassVar[XMLSchemaRestrictionType] = ...
    xsr_whitespace: ClassVar[XMLSchemaRestrictionType] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class XMLSchemaSimpleSubelementList:
    class ElementSummary:
        class ElementType:
            __members__: ClassVar[dict] = ...  # read-only
            __entries: ClassVar[dict] = ...
            ct_group: ClassVar[XMLSchemaSimpleSubelementList.ElementSummary.ElementType] = ...
            ct_ref: ClassVar[XMLSchemaSimpleSubelementList.ElementSummary.ElementType] = ...
            ct_simple: ClassVar[XMLSchemaSimpleSubelementList.ElementSummary.ElementType] = ...
            def __init__(self, value: int) -> None: ...
            def __and__(self, other: object) -> object: ...
            def __eq__(self, other: object) -> bool: ...
            def __ge__(self, other: object) -> bool: ...
            def __gt__(self, other: object) -> bool: ...
            def __hash__(self) -> int: ...
            def __index__(self) -> int: ...
            def __int__(self) -> int: ...
            def __invert__(self) -> object: ...
            def __le__(self, other: object) -> bool: ...
            def __lt__(self, other: object) -> bool: ...
            def __ne__(self, other: object) -> bool: ...
            def __or__(self, other: object) -> object: ...
            def __rand__(self, other: object) -> object: ...
            def __ror__(self, other: object) -> object: ...
            def __rxor__(self, other: object) -> object: ...
            def __xor__(self, other: object) -> object: ...
            @property
            def name(self) -> str: ...
            @property
            def value(self) -> int: ...
        ct_group: ClassVar[XMLSchemaSimpleSubelementList.ElementSummary.ElementType] = ...
        ct_ref: ClassVar[XMLSchemaSimpleSubelementList.ElementSummary.ElementType] = ...
        ct_simple: ClassVar[XMLSchemaSimpleSubelementList.ElementSummary.ElementType] = ...
        attributes: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t
        ct_name: str
        description: str
        element_name: str
        element_type: XMLSchemaSimpleSubelementList.ElementSummary.ElementType
        max_occurs: int
        min_occurs: int
        min_or_max_occurs_set: bool
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: XMLSchemaSimpleSubelementList.ElementSummary) -> None: ...
        def assign(self) -> XMLSchemaSimpleSubelementList.ElementSummary: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaSimpleSubelementList) -> None: ...
    def add_already_defined_subelement(self, *args, **kwargs): ...
    def add_already_defined_subelement_w_alt_element_name(self, *args, **kwargs): ...
    def add_group_subelement(self, *args, **kwargs): ...
    @overload
    def add_simple_subelement(self, name: str, description: str) -> XMLSchemaSimpleSubelementList: ...
    @overload
    def add_simple_subelement(self, name: str, description: str, min_occurs: int) -> XMLSchemaSimpleSubelementList: ...
    @overload
    def add_simple_subelement(self, name: str, description: str, min_occurs: int, max_occurs: int) -> XMLSchemaSimpleSubelementList: ...
    def add_subelement(self, summary) -> XMLSchemaSimpleSubelementList: ...
    def assign(self, rhs: XMLSchemaSimpleSubelementList) -> XMLSchemaSimpleSubelementList: ...
    def complex_type_naming_func(self, *args, **kwargs): ...
    def complex_typename_for_element(self, element_name: str) -> str: ...
    def element_list(self) -> pyrosetta.rosetta.std.list_utility_tag_XMLSchemaSimpleSubelementList_ElementSummary_t: ...
    @staticmethod
    def element_summary_as_already_defined_subelement(*args, **kwargs): ...
    @staticmethod
    def element_summary_as_already_defined_subelement_w_alt_element_name(*args, **kwargs): ...
    @staticmethod
    def element_summary_as_group_subelement(*args, **kwargs): ...
    @staticmethod
    def element_summary_as_simple_subelement(*args, **kwargs): ...
    def naming_func(self, *args, **kwargs): ...
    @overload
    def simple_element_naming_func_has_been_set(self) -> bool: ...
    @overload
    def simple_element_naming_func_has_been_set(self) -> bool: ...

class XMLSchemaTopLevelElement:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaTopLevelElement) -> None: ...
    def assign(self) -> XMLSchemaTopLevelElement: ...
    def element_name(self) -> str: ...
    @overload
    def prepare_for_output(self, xsd) -> None: ...
    @overload
    def prepare_for_output(self, classutility) -> void: ...
    @overload
    def write_definition(self, indentation: int, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def write_definition(self, int, std) -> void: ...

class XMLSchemaType:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, setting: XMLSchemaDataType) -> None: ...
    @overload
    def __init__(self, setting: XMLSchemaCommonType) -> None: ...
    @overload
    def __init__(self, arg0: XMLSchemaType) -> None: ...
    def assign(self) -> XMLSchemaType: ...
    @overload
    def common_type(self, setting: XMLSchemaCommonType) -> None: ...
    @overload
    def common_type(self, enumutility) -> void: ...
    @overload
    def common_type(self) -> XMLSchemaCommonType: ...
    @overload
    def custom_type_name(self, setting: str) -> None: ...
    @overload
    def custom_type_name(self, conststd) -> void: ...
    @overload
    def type(self, setting: XMLSchemaDataType) -> None: ...
    @overload
    def type(self, enumutility) -> void: ...
    @overload
    def type(self) -> XMLSchemaDataType: ...
    def type_name(self) -> str: ...

class XMLValidationOutput:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: XMLValidationOutput) -> None: ...
    @overload
    def add_error(self, error: str) -> None: ...
    @overload
    def add_error(self, conststd) -> void: ...
    @overload
    def add_errors(self, error_list: pyrosetta.rosetta.std.list_std_string_t) -> None: ...
    @overload
    def add_errors(self, constclassstd) -> void: ...
    @overload
    def add_warnings(self, warning: str) -> None: ...
    @overload
    def add_warnings(self, conststd) -> void: ...
    @overload
    def add_warnings(self, warning_list: pyrosetta.rosetta.std.list_std_string_t) -> None: ...
    @overload
    def add_warnings(self, constclassstd) -> void: ...
    def assign(self) -> XMLValidationOutput: ...
    def error_messages(self) -> str: ...
    @overload
    def errors(self) -> pyrosetta.rosetta.std.list_std_string_t: ...
    @overload
    def errors(self, error_list: pyrosetta.rosetta.std.list_std_string_t) -> None: ...
    @overload
    def errors(self, constclassstd) -> void: ...
    @overload
    def valid(self) -> None: ...
    @overload
    def valid(self, bool) -> void: ...
    @overload
    def valid(self) -> bool: ...
    @overload
    def valid(self) -> bool: ...
    def warning_messages(self) -> str: ...
    @overload
    def warnings(self) -> pyrosetta.rosetta.std.list_std_string_t: ...
    @overload
    def warnings(self, warning_list: pyrosetta.rosetta.std.list_std_string_t) -> None: ...
    @overload
    def warnings(self, constclassstd) -> void: ...

class XMLValidator:
    def __init__(self) -> None: ...
    @overload
    def schema_has_been_set(self) -> bool: ...
    @overload
    def schema_has_been_set(self) -> bool: ...
    def set_schema(self, *args, **kwargs): ...
    def validate_xml_against_schema(self, *args, **kwargs): ...

@overload
def add_schema_restrictions_for_strings(xsd: XMLSchemaDefinition, type_name: str, restrictions: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
@overload
def add_schema_restrictions_for_strings(classutility, std, constclassutility) -> void: ...
@overload
def append_name_and_attributes_to_complex_type(attributes: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t, type_definition: XMLSchemaComplexType) -> None: ...
@overload
def append_name_and_attributes_to_complex_type(constclassstd, classutility) -> void: ...
@overload
def append_required_name_and_attributes_to_complex_type(attributes: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t, type_definition: XMLSchemaComplexType) -> None: ...
@overload
def append_required_name_and_attributes_to_complex_type(constclassstd, classutility) -> void: ...
@overload
def attribute_w_name_in_attribute_list(attname: str, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> bool: ...
@overload
def attribute_w_name_in_attribute_list(conststd, constclassstd) -> bool: ...
def chr_chains_nonrepeated() -> str: ...
def handle_structured_xml_error(ctxt: capsule, error: _xmlError) -> None: ...
def handle_xml_error(ctxt: capsule, message: str) -> None: ...
def handle_xml_warning(ctxt: capsule, message: str) -> None: ...
@overload
def indent_w_spaces(indentation: int, os: pyrosetta.rosetta.std.ostream) -> None: ...
@overload
def indent_w_spaces(int, std) -> void: ...
def integer_range_restriction(name: str, lower_inclusive: int, upper_inclusive: int) -> XMLSchemaRestriction: ...
def name_for_common_type(common_type: XMLSchemaCommonType) -> str: ...
@overload
def optional_name_attribute() -> XMLSchemaAttribute: ...
@overload
def optional_name_attribute(description: str) -> XMLSchemaAttribute: ...
def real_regex_pattern() -> str: ...
def refpose_enabled_residue_number_string() -> str: ...
@overload
def required_name_attribute() -> XMLSchemaAttribute: ...
@overload
def required_name_attribute(description: str) -> XMLSchemaAttribute: ...
def residue_number_string() -> str: ...
def restriction_type_name(type: XMLSchemaRestrictionType) -> str: ...
@overload
def string_contains_gt_lt_or_ampersand(s: str) -> str: ...
@overload
def string_contains_gt_lt_or_ampersand(conststd) -> char: ...
def test_if_schema_is_valid(xsd: str) -> XMLValidationOutput: ...
def validate_xml_against_xsd(xml: str, xsd: str) -> XMLValidationOutput: ...
def xs_model_group_name(xsmgt: XMLSchemaModelGroupType) -> str: ...
