import pyrosetta.rosetta
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import ClassVar, overload

RMOT_end_of_list: RosettaModuleOptionType
RMOT_general_string: RosettaModuleOptionType
RMOT_integer: RosettaModuleOptionType
RMOT_invalid: RosettaModuleOptionType
RMOT_nonnegative_integer: RosettaModuleOptionType
RMOT_real: RosettaModuleOptionType
RMOT_residue_selector: RosettaModuleOptionType
RMOT_residue_selector_list: RosettaModuleOptionType
RMOT_rosetta_bool: RosettaModuleOptionType
RMOT_task_operation: RosettaModuleOptionType
RMOT_task_operation_list: RosettaModuleOptionType
RMT_end_of_list: RosettaModuleType
RMT_filter: RosettaModuleType
RMT_invalid: RosettaModuleType
RMT_mover: RosettaModuleType
RMT_res_lvl_task_operation: RosettaModuleType
RMT_residue_selector: RosettaModuleType
RMT_sub_element: RosettaModuleType
RMT_task_operation: RosettaModuleType

class RosettaModuleOptionType:
    __members__: ClassVar[dict] = ...  # read-only
    RMOT_end_of_list: ClassVar[RosettaModuleOptionType] = ...
    RMOT_general_string: ClassVar[RosettaModuleOptionType] = ...
    RMOT_integer: ClassVar[RosettaModuleOptionType] = ...
    RMOT_invalid: ClassVar[RosettaModuleOptionType] = ...
    RMOT_nonnegative_integer: ClassVar[RosettaModuleOptionType] = ...
    RMOT_real: ClassVar[RosettaModuleOptionType] = ...
    RMOT_residue_selector: ClassVar[RosettaModuleOptionType] = ...
    RMOT_residue_selector_list: ClassVar[RosettaModuleOptionType] = ...
    RMOT_rosetta_bool: ClassVar[RosettaModuleOptionType] = ...
    RMOT_task_operation: ClassVar[RosettaModuleOptionType] = ...
    RMOT_task_operation_list: ClassVar[RosettaModuleOptionType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class RosettaModuleType:
    __members__: ClassVar[dict] = ...  # read-only
    RMT_end_of_list: ClassVar[RosettaModuleType] = ...
    RMT_filter: ClassVar[RosettaModuleType] = ...
    RMT_invalid: ClassVar[RosettaModuleType] = ...
    RMT_mover: ClassVar[RosettaModuleType] = ...
    RMT_res_lvl_task_operation: ClassVar[RosettaModuleType] = ...
    RMT_residue_selector: ClassVar[RosettaModuleType] = ...
    RMT_sub_element: ClassVar[RosettaModuleType] = ...
    RMT_task_operation: ClassVar[RosettaModuleType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

def generate_human_readable_documentation(doc_node: pyrosetta.rosetta._xmlNode, outstream: pyrosetta.rosetta.std.stringstream) -> None: ...
def generate_human_readable_recursive(rootnode: pyrosetta.rosetta._xmlNode, description: pyrosetta.rosetta.std.stringstream, tags: pyrosetta.rosetta.std.stringstream, options: pyrosetta.rosetta.std.stringstream, level: int, complextype: str, tag_name_to_print: str) -> None: ...
def generate_human_readable_summary(xsd: str, component_name: str, component_type: str) -> str: ...
def generate_tag_given_options(stringstream_out: pyrosetta.rosetta.std.stringstream, tag_name: str, option_list: pyrosetta.rosetta.utility.vector1_std_pair_std_string_std_string_t, terminal_slash: bool, triangular_brackets: bool) -> None: ...
def get_choice_min_and_max(choice_node: pyrosetta.rosetta._xmlNode, choice_min: int, choice_max: int) -> None: ...
@overload
def get_filter_names_from_xsd(xsd: str, filter_names_out: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
@overload
def get_filter_names_from_xsd(conststd, classutility) -> void: ...
def get_module_names_from_xsd(xsd: str, module_name: str, names_out: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
def get_module_type_as_it_appears_in_xsd(module_type: RosettaModuleType) -> str: ...
@overload
def get_mover_names_from_xsd(xsd: str, mover_names_out: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
@overload
def get_mover_names_from_xsd(conststd, classutility) -> void: ...
def get_node_option(node: pyrosetta.rosetta._xmlNode, optionname: str) -> str: ...
def get_option_type_from_name(name: str, type: str) -> RosettaModuleOptionType: ...
@overload
def get_residue_level_task_operation_names_from_xsd(xsd: str, rltaskop_names_out: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
@overload
def get_residue_level_task_operation_names_from_xsd(conststd, classutility) -> void: ...
@overload
def get_residue_selector_names_from_xsd(xsd: str, residue_selector_names_out: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
@overload
def get_residue_selector_names_from_xsd(conststd, classutility) -> void: ...
def get_specific_module_name_as_it_appears_in_xsd(module_name: str, module_type: RosettaModuleType) -> str: ...
def get_tag_name(node: pyrosetta.rosetta._xmlNode) -> str: ...
@overload
def get_task_operation_names_from_xsd(xsd: str, taskop_names_out: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
@overload
def get_task_operation_names_from_xsd(conststd, classutility) -> void: ...
def get_type_name(xsd_type: str) -> str: ...
def output_all_tag_options(node: pyrosetta.rosetta._xmlNode, tagname: str, level: int, tags: pyrosetta.rosetta.std.stringstream, options: pyrosetta.rosetta.std.stringstream) -> None: ...
