import pyrosetta.rosetta.std
from . import has_insertion_operator_implementation as has_insertion_operator_implementation

class is_string_constructible_char_(_ref_)[]_t(pyrosetta.rosetta.std.integral_constant_bool_true_t):
    def __init__(self) -> None: ...

class is_string_constructible_char__star__t(pyrosetta.rosetta.std.integral_constant_bool_true_t):
    def __init__(self) -> None: ...

class is_string_constructible_char_const_(_ref_)[]_t(pyrosetta.rosetta.std.integral_constant_bool_true_t):
    def __init__(self) -> None: ...

class is_string_constructible_const_char__star__t(pyrosetta.rosetta.std.integral_constant_bool_true_t):
    def __init__(self) -> None: ...

class is_string_constructible_const_std_string__ref__t(pyrosetta.rosetta.std.integral_constant_bool_true_t):
    def __init__(self) -> None: ...

class is_string_constructible_const_std_string_t(pyrosetta.rosetta.std.integral_constant_bool_true_t):
    def __init__(self) -> None: ...

class is_string_constructible_const_utility_tag_XMLSchemaType__ref__t(pyrosetta.rosetta.std.integral_constant_bool_false_t):
    def __init__(self) -> None: ...

class is_string_constructible_std_string__ref__t(pyrosetta.rosetta.std.integral_constant_bool_true_t):
    def __init__(self) -> None: ...

class is_string_constructible_std_string_t(pyrosetta.rosetta.std.integral_constant_bool_true_t):
    def __init__(self) -> None: ...

class is_string_constructible_utility_tag_XMLSchemaType_t(pyrosetta.rosetta.std.integral_constant_bool_false_t):
    def __init__(self) -> None: ...
