import pyrosetta.rosetta
import pyrosetta.rosetta.std
from . import backend as backend
from typing import overload

class connection_info:
    connection_string: str
    driver: str
    properties: pyrosetta.rosetta.std.map_std_string_std_string
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, cs: str) -> None: ...
    @overload
    def __init__(self, arg0: connection_info) -> None: ...
    def assign(self) -> connection_info: ...
    @overload
    def get(self, prop: str) -> str: ...
    @overload
    def get(self, prop: str, default_value: str) -> str: ...
    @overload
    def get(self, prop: str, default_value: int) -> int: ...
    @overload
    def get(self, conststd, int) -> int: ...
    @overload
    def has(self, prop: str) -> bool: ...
    @overload
    def has(self, conststd) -> bool: ...

class connection_specific_data:
    def __init__(self) -> None: ...

class pool(ref_counted):
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    @staticmethod
    def create(connection_string: str) -> ref_ptr_cppdb_pool_t: ...
    @overload
    @staticmethod
    def create(ci: connection_info) -> ref_ptr_cppdb_pool_t: ...
    @overload
    def gc(self) -> None: ...
    @overload
    def gc(self) -> void: ...
    def open(self) -> ref_ptr_cppdb_backend_connection_t: ...
    @overload
    def put(self, c_in) -> None: ...
    @overload
    def put(self, classcppdb) -> void: ...

class ref_counted:
    def __init__(self) -> None: ...
    @overload
    def add_ref(self) -> int: ...
    @overload
    def add_ref(self) -> long: ...
    @overload
    def del_ref(self) -> int: ...
    @overload
    def del_ref(self) -> long: ...
    @overload
    @staticmethod
    def dispose(p: ref_counted) -> None: ...
    @overload
    @staticmethod
    def dispose(classcppdb) -> void: ...
    @overload
    def use_count(self) -> int: ...
    @overload
    def use_count(self) -> long: ...

class ref_ptr_cppdb_backend_connection_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, v) -> None: ...
    @overload
    def __init__(self, arg0: ref_ptr_cppdb_backend_connection_t) -> None: ...
    def arrow(self, *args, **kwargs): ...
    def assign(self, other: ref_ptr_cppdb_backend_connection_t) -> ref_ptr_cppdb_backend_connection_t: ...
    def dereference(self, *args, **kwargs): ...
    def get(self, *args, **kwargs): ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self, v) -> None: ...
    @overload
    def reset(self, classcppdb) -> void: ...

class ref_ptr_cppdb_backend_loadable_driver_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, v) -> None: ...
    @overload
    def __init__(self, arg0: ref_ptr_cppdb_backend_loadable_driver_t) -> None: ...
    def arrow(self, *args, **kwargs): ...
    def assign(self, other: ref_ptr_cppdb_backend_loadable_driver_t) -> ref_ptr_cppdb_backend_loadable_driver_t: ...
    def dereference(self, *args, **kwargs): ...
    def get(self, *args, **kwargs): ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self, v) -> None: ...
    @overload
    def reset(self, classcppdb) -> void: ...

class ref_ptr_cppdb_backend_statement_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, v) -> None: ...
    @overload
    def __init__(self, arg0: ref_ptr_cppdb_backend_statement_t) -> None: ...
    def arrow(self, *args, **kwargs): ...
    def assign(self, other: ref_ptr_cppdb_backend_statement_t) -> ref_ptr_cppdb_backend_statement_t: ...
    def dereference(self, *args, **kwargs): ...
    def get(self, *args, **kwargs): ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self, v) -> None: ...
    @overload
    def reset(self, classcppdb) -> void: ...

class ref_ptr_cppdb_pool_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, v) -> None: ...
    @overload
    def __init__(self, arg0: ref_ptr_cppdb_pool_t) -> None: ...
    def arrow(self, *args, **kwargs): ...
    def assign(self, other: ref_ptr_cppdb_pool_t) -> ref_ptr_cppdb_pool_t: ...
    def dereference(self, *args, **kwargs): ...
    def get(self, *args, **kwargs): ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self, v) -> None: ...
    @overload
    def reset(self, classcppdb) -> void: ...

class result:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: result) -> None: ...
    def assign(self) -> result: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def cols(self) -> int: ...
    @overload
    def cols(self) -> int: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fetch(self, col: int, v: int) -> bool: ...
    @overload
    def fetch(self, col: int, v: int) -> bool: ...
    @overload
    def fetch(self, col: int, v: int) -> bool: ...
    @overload
    def fetch(self, col: int, v: int) -> bool: ...
    @overload
    def fetch(self, col: int, v: int) -> bool: ...
    @overload
    def fetch(self, col: int, v: int) -> bool: ...
    @overload
    def fetch(self, col: int, v: int) -> bool: ...
    @overload
    def fetch(self, col: int, v: int) -> bool: ...
    @overload
    def fetch(self, col: int, v: float) -> bool: ...
    @overload
    def fetch(self, col: int, v: float) -> bool: ...
    @overload
    def fetch(self, col: int, v: float) -> bool: ...
    @overload
    def fetch(self, col: int, v: str) -> bool: ...
    @overload
    def fetch(self, int, std) -> bool: ...
    @overload
    def fetch(self, col: int, v: pyrosetta.rosetta.tm) -> bool: ...
    @overload
    def fetch(self, col: int, v: pyrosetta.rosetta.std.ostream) -> bool: ...
    @overload
    def fetch(self, int, std) -> bool: ...
    @overload
    def fetch(self, n: str, v: int) -> bool: ...
    @overload
    def fetch(self, n: str, v: int) -> bool: ...
    @overload
    def fetch(self, n: str, v: int) -> bool: ...
    @overload
    def fetch(self, n: str, v: int) -> bool: ...
    @overload
    def fetch(self, n: str, v: int) -> bool: ...
    @overload
    def fetch(self, n: str, v: int) -> bool: ...
    @overload
    def fetch(self, n: str, v: int) -> bool: ...
    @overload
    def fetch(self, n: str, v: int) -> bool: ...
    @overload
    def fetch(self, n: str, v: float) -> bool: ...
    @overload
    def fetch(self, n: str, v: float) -> bool: ...
    @overload
    def fetch(self, n: str, v: float) -> bool: ...
    @overload
    def fetch(self, n: str, v: str) -> bool: ...
    @overload
    def fetch(self, conststd, std) -> bool: ...
    @overload
    def fetch(self, n: str, v: pyrosetta.rosetta.tm) -> bool: ...
    @overload
    def fetch(self, n: str, v: pyrosetta.rosetta.std.ostream) -> bool: ...
    @overload
    def fetch(self, conststd, std) -> bool: ...
    @overload
    def fetch(self, v: int) -> bool: ...
    @overload
    def fetch(self, v: int) -> bool: ...
    @overload
    def fetch(self, v: int) -> bool: ...
    @overload
    def fetch(self, v: int) -> bool: ...
    @overload
    def fetch(self, v: int) -> bool: ...
    @overload
    def fetch(self, v: int) -> bool: ...
    @overload
    def fetch(self, v: int) -> bool: ...
    @overload
    def fetch(self, v: int) -> bool: ...
    @overload
    def fetch(self, v: float) -> bool: ...
    @overload
    def fetch(self, v: float) -> bool: ...
    @overload
    def fetch(self, v: float) -> bool: ...
    @overload
    def fetch(self, v: str) -> bool: ...
    @overload
    def fetch(self, std) -> bool: ...
    @overload
    def fetch(self, v: pyrosetta.rosetta.tm) -> bool: ...
    @overload
    def fetch(self, v: pyrosetta.rosetta.std.ostream) -> bool: ...
    @overload
    def fetch(self, std) -> bool: ...
    @overload
    def find_column(self, name: str) -> int: ...
    @overload
    def find_column(self, conststd) -> int: ...
    @overload
    def index(self, n: str) -> int: ...
    @overload
    def index(self, conststd) -> int: ...
    @overload
    def is_null(self, col: int) -> bool: ...
    @overload
    def is_null(self, int) -> bool: ...
    @overload
    def is_null(self, n: str) -> bool: ...
    @overload
    def is_null(self, conststd) -> bool: ...
    def name(self, col: int) -> str: ...
    @overload
    def next(self) -> bool: ...
    @overload
    def next(self) -> bool: ...
    @overload
    def rewind_column(self) -> None: ...
    @overload
    def rewind_column(self) -> void: ...

class session:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: session) -> None: ...
    @overload
    def __init__(self, ci: connection_info) -> None: ...
    @overload
    def __init__(self, cs: str) -> None: ...
    @overload
    def __init__(self, conn: ref_ptr_cppdb_backend_connection_t) -> None: ...
    def assign(self) -> session: ...
    @overload
    def begin(self) -> None: ...
    @overload
    def begin(self) -> void: ...
    @overload
    def clear_cache(self) -> None: ...
    @overload
    def clear_cache(self) -> void: ...
    @overload
    def clear_pool(self) -> None: ...
    @overload
    def clear_pool(self) -> void: ...
    @overload
    def close(self) -> None: ...
    @overload
    def close(self) -> void: ...
    @overload
    def commit(self) -> None: ...
    @overload
    def commit(self) -> void: ...
    def create_prepared_statement(self, q: str) -> statement: ...
    def create_prepared_uncached_statement(self, q: str) -> statement: ...
    def create_statement(self, q: str) -> statement: ...
    def driver(self) -> str: ...
    def engine(self) -> str: ...
    @overload
    def escape(self, b: str, e: str) -> str: ...
    @overload
    def escape(self, s: str) -> str: ...
    @overload
    def escape(self, s: str) -> str: ...
    def get_specific(self, t: pyrosetta.rosetta.std.type_info) -> connection_specific_data: ...
    @overload
    def is_open(self) -> bool: ...
    @overload
    def is_open(self) -> bool: ...
    @overload
    def once_called(self) -> bool: ...
    @overload
    def once_called(self) -> bool: ...
    @overload
    def once_called(self, state: bool) -> None: ...
    @overload
    def once_called(self, bool) -> void: ...
    @overload
    def open(self, ci: connection_info) -> None: ...
    @overload
    def open(self, constclasscppdb) -> void: ...
    @overload
    def open(self, cs: str) -> None: ...
    @overload
    def open(self, conststd) -> void: ...
    def prepare(self, query: str) -> statement: ...
    @overload
    def recyclable(self) -> bool: ...
    @overload
    def recyclable(self) -> bool: ...
    @overload
    def recyclable(self, value: bool) -> None: ...
    @overload
    def recyclable(self, bool) -> void: ...
    def release_specific(self, t: pyrosetta.rosetta.std.type_info) -> connection_specific_data: ...
    @overload
    def reset_specific(self, t: pyrosetta.rosetta.std.type_info) -> None: ...
    @overload
    def reset_specific(self, t: pyrosetta.rosetta.std.type_info, p: connection_specific_data) -> None: ...
    @overload
    def reset_specific(self, constclassstd, classcppdb) -> void: ...
    @overload
    def rollback(self) -> None: ...
    @overload
    def rollback(self) -> void: ...
    @overload
    def __lshift__(self, q: str) -> statement: ...
    @overload
    def __lshift__(self, s: str) -> statement: ...

class statement:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: statement) -> None: ...
    @overload
    def affected(self) -> int: ...
    @overload
    def affected(self) -> unsignedlonglong: ...
    def assign(self) -> statement: ...
    @overload
    def bind(self, v: int) -> statement: ...
    @overload
    def bind(self, v: int) -> statement: ...
    @overload
    def bind(self, v: int) -> statement: ...
    @overload
    def bind(self, v: int) -> statement: ...
    @overload
    def bind(self, v: int) -> statement: ...
    @overload
    def bind(self, v: int) -> statement: ...
    @overload
    def bind(self, v: float) -> statement: ...
    @overload
    def bind(self, v: float) -> statement: ...
    @overload
    def bind(self, v: str) -> statement: ...
    @overload
    def bind(self, s: str) -> statement: ...
    @overload
    def bind(self, b: str, e: str) -> statement: ...
    @overload
    def bind(self, v: pyrosetta.rosetta.tm) -> statement: ...
    @overload
    def bind(self, v: pyrosetta.rosetta.std.istream) -> statement: ...
    @overload
    def bind(self, col: int, v: int) -> None: ...
    @overload
    def bind(self, col: int, v: int) -> None: ...
    @overload
    def bind(self, int, unsignedint) -> void: ...
    @overload
    def bind(self, col: int, v: int) -> None: ...
    @overload
    def bind(self, int, long) -> void: ...
    @overload
    def bind(self, col: int, v: int) -> None: ...
    @overload
    def bind(self, int, unsignedlong) -> void: ...
    @overload
    def bind(self, col: int, v: int) -> None: ...
    @overload
    def bind(self, int, longlong) -> void: ...
    @overload
    def bind(self, col: int, v: int) -> None: ...
    @overload
    def bind(self, int, unsignedlonglong) -> void: ...
    @overload
    def bind(self, col: int, v: float) -> None: ...
    @overload
    def bind(self, int, double) -> void: ...
    @overload
    def bind(self, col: int, v: float) -> None: ...
    @overload
    def bind(self, int, longdouble) -> void: ...
    @overload
    def bind(self, col: int, v: str) -> None: ...
    @overload
    def bind(self, int, conststd) -> void: ...
    @overload
    def bind(self, col: int, s: str) -> None: ...
    @overload
    def bind(self, col: int, b: str, e: str) -> None: ...
    @overload
    def bind(self, col: int, v: pyrosetta.rosetta.tm) -> None: ...
    @overload
    def bind(self, col: int, v: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def bind(self, int, std) -> void: ...
    @overload
    def bind_null(self) -> statement: ...
    @overload
    def bind_null(self, col: int) -> None: ...
    @overload
    def bind_null(self, int) -> void: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def exec(self) -> None: ...
    @overload
    def exec(self) -> void: ...
    @overload
    def last_insert_id(self) -> int: ...
    @overload
    def last_insert_id(self) -> longlong: ...
    def query(self) -> result: ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self) -> void: ...
    def row(self) -> result: ...
    @overload
    def sequence_last(self, seq: str) -> int: ...
    @overload
    def sequence_last(self, conststd) -> longlong: ...
    @overload
    def __lshift__(self, v: str) -> statement: ...
    @overload
    def __lshift__(self, s: str) -> statement: ...
    @overload
    def __lshift__(self, v: pyrosetta.rosetta.tm) -> statement: ...
    @overload
    def __lshift__(self, v: pyrosetta.rosetta.std.istream) -> statement: ...

class transaction:
    def __init__(self, s: session) -> None: ...
    @overload
    def commit(self) -> None: ...
    @overload
    def commit(self) -> void: ...
    @overload
    def rollback(self) -> None: ...
    @overload
    def rollback(self) -> void: ...
