import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.conformation.membrane
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.std
from typing import overload

class Bicelle(pyrosetta.rosetta.core.conformation.membrane.MembraneGeometry):
    @overload
    def __init__(self, steepness: float, conf: pyrosetta.rosetta.core.conformation.Conformation, membrane_pos: int) -> None: ...
    @overload
    def __init__(self, steepness: float, thickness: float, conf: pyrosetta.rosetta.core.conformation.Conformation, membrane_pos: int) -> None: ...
    @overload
    def __init__(self, steepness: float, thickness: float, bicelle_inner_radius: float) -> None: ...
    @overload
    def __init__(self, steepness: float, thickness: float, bicelle_inner_radius: float, aqueous_pore: pyrosetta.rosetta.core.conformation.membrane.AqueousPoreParameters) -> None: ...
    @overload
    def __init__(self, arg0: Bicelle) -> None: ...
    @overload
    def __init__(self, arg0: Bicelle) -> None: ...
    def assign(self) -> Bicelle: ...
    @overload
    def bicelle_edge_steepness(self) -> float: ...
    @overload
    def bicelle_edge_steepness(self) -> double: ...
    @overload
    def bicelle_inner_radius(self) -> float: ...
    @overload
    def bicelle_inner_radius(self) -> double: ...
    @overload
    def bicelle_outer_radius(self) -> float: ...
    @overload
    def bicelle_outer_radius(self) -> double: ...
    def clone(self) -> pyrosetta.rosetta.core.conformation.membrane.MembraneGeometry: ...
    def f_transition(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def f_transition_deriv(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def f_transition_deriv_m(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def f_transition_f1(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def f_transition_f2(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def fa_elec_lipid(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def fa_elec_lipid_deriv(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def geometry_enum(self) -> pyrosetta.rosetta.core.conformation.membrane.MP_GEOMETRY_TRANSITION: ...
    def geometry_string(self) -> str: ...
    @overload
    def protein_slice_diameter(self) -> float: ...
    @overload
    def protein_slice_diameter(self) -> double: ...
    def r_alpha(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def r_alpha_m(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def set_bicelle_edge_steepness(self, edge_steepness: float) -> None: ...
    @overload
    def set_bicelle_edge_steepness(self, double) -> void: ...
    @overload
    def set_inner_radius(self, inner_r: float) -> None: ...
    @overload
    def set_inner_radius(self, double) -> void: ...
    @overload
    def set_outer_radius(self, outer_r: float) -> None: ...
    @overload
    def set_outer_radius(self, double) -> void: ...
    @overload
    def set_protein_slice_diameter(self, diameter: float) -> None: ...
    @overload
    def set_protein_slice_diameter(self, double) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self) -> void: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def update_radii(self) -> None: ...
    @overload
    def update_radii(self) -> void: ...

class DoubleVesicle(pyrosetta.rosetta.core.conformation.membrane.MembraneGeometry):
    @overload
    def __init__(self, steepness: float) -> None: ...
    @overload
    def __init__(self, steepness: float, thickness: float) -> None: ...
    @overload
    def __init__(self, steepness: float, thickness: float, inner_radius: float, distance: float) -> None: ...
    @overload
    def __init__(self, steepness: float, thickness: float, inner_radius: float, distance: float, aqueous_pore: pyrosetta.rosetta.core.conformation.membrane.AqueousPoreParameters) -> None: ...
    @overload
    def __init__(self, arg0: DoubleVesicle) -> None: ...
    @overload
    def __init__(self, arg0: DoubleVesicle) -> None: ...
    def assign(self) -> DoubleVesicle: ...
    def clone(self) -> pyrosetta.rosetta.core.conformation.membrane.MembraneGeometry: ...
    def f_transition(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def f_transition_deriv(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def f_transition_f1(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def f_transition_f2(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def fa_elec_lipid(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def fa_elec_lipid_deriv(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def geometry_enum(self) -> pyrosetta.rosetta.core.conformation.membrane.MP_GEOMETRY_TRANSITION: ...
    def geometry_string(self) -> str: ...
    @overload
    def get_distance(self) -> float: ...
    @overload
    def get_distance(self) -> double: ...
    @overload
    def get_inner_radius(self) -> float: ...
    @overload
    def get_inner_radius(self) -> double: ...
    @overload
    def get_outer_radius(self) -> float: ...
    @overload
    def get_outer_radius(self) -> double: ...
    def r_alpha(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def set_distance(self, distance: float) -> None: ...
    @overload
    def set_distance(self, double) -> void: ...
    @overload
    def set_inner_radius(self, inner_r: float) -> None: ...
    @overload
    def set_inner_radius(self, double) -> void: ...
    @overload
    def set_outer_radius(self, outer_r: float) -> None: ...
    @overload
    def set_outer_radius(self, double) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self) -> void: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def update_radii(self) -> None: ...
    @overload
    def update_radii(self) -> void: ...

class Slab(pyrosetta.rosetta.core.conformation.membrane.MembraneGeometry):
    @overload
    def __init__(self, steepness: float) -> None: ...
    @overload
    def __init__(self, steepness: float, thickness: float) -> None: ...
    @overload
    def __init__(self, steepness: float, thickness: float, aqueous_pore: pyrosetta.rosetta.core.conformation.membrane.AqueousPoreParameters) -> None: ...
    @overload
    def __init__(self, arg0: Slab) -> None: ...
    @overload
    def __init__(self, arg0: Slab) -> None: ...
    def assign(self) -> Slab: ...
    def clone(self) -> pyrosetta.rosetta.core.conformation.membrane.MembraneGeometry: ...
    def f_transition(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def f_transition_deriv(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def f_transition_f1(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def f_transition_f2(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def fa_elec_lipid(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def fa_elec_lipid_deriv(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def geometry_enum(self) -> pyrosetta.rosetta.core.conformation.membrane.MP_GEOMETRY_TRANSITION: ...
    def geometry_string(self) -> str: ...
    def r_alpha(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self) -> void: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class Vesicle(pyrosetta.rosetta.core.conformation.membrane.MembraneGeometry):
    @overload
    def __init__(self, steepness: float) -> None: ...
    @overload
    def __init__(self, steepness: float, thickness: float) -> None: ...
    @overload
    def __init__(self, steepness: float, thickness: float, radius: float) -> None: ...
    @overload
    def __init__(self, steepness: float, thickness: float, radius: float, aqueous_pore: pyrosetta.rosetta.core.conformation.membrane.AqueousPoreParameters) -> None: ...
    @overload
    def __init__(self, arg0: Vesicle) -> None: ...
    @overload
    def __init__(self, arg0: Vesicle) -> None: ...
    def assign(self) -> Vesicle: ...
    def clone(self) -> pyrosetta.rosetta.core.conformation.membrane.MembraneGeometry: ...
    def f_transition(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def f_transition_deriv(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def f_transition_f1(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def f_transition_f2(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def fa_elec_lipid(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def fa_elec_lipid_deriv(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> float: ...
    def geometry_enum(self) -> pyrosetta.rosetta.core.conformation.membrane.MP_GEOMETRY_TRANSITION: ...
    def geometry_string(self) -> str: ...
    @overload
    def get_radius(self) -> float: ...
    @overload
    def get_radius(self) -> double: ...
    def r_alpha(self, conf: pyrosetta.rosetta.core.conformation.Conformation, resnum: int, atomnum: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def set_radius(self, r: float) -> None: ...
    @overload
    def set_radius(self, double) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self) -> void: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def update_radius(self) -> None: ...
    @overload
    def update_radius(self) -> void: ...
