from Bio import MissingPythonDependencyError as MissingPythonDependencyError

def to_networkx(tree): ...
def to_igraph(tree, vertex_attributes=None, edge_attributes=('color', 'width')): ...
def draw_ascii(tree, file=None, column_width: int = 80): ...
def draw(tree, label_func=..., do_show: bool = True, show_confidence: bool = True, axes=None, branch_labels=None, label_colors=None, *args, **kwargs): ...
