import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.utility
from typing import ClassVar, overload

CP_CROSSOVER_3: CPCrossoverBehavior
CP_CROSSOVER_34: CPCrossoverBehavior
CP_CROSSOVER_3FULL: CPCrossoverBehavior
CP_CROSSOVER_4: CPCrossoverBehavior
CP_MULTIPLE_BONDS_OR_PSEUDOBONDS: CPResidueConnectionType
CP_NO_BONDS: CPResidueConnectionType
CP_ONE_BOND: CPResidueConnectionType
nCPCrossoverBehaviors: CPCrossoverBehavior
nCPResidueConnectionTypes: CPResidueConnectionType

class CPCrossoverBehavior:
    __members__: ClassVar[dict] = ...  # read-only
    CP_CROSSOVER_3: ClassVar[CPCrossoverBehavior] = ...
    CP_CROSSOVER_34: ClassVar[CPCrossoverBehavior] = ...
    CP_CROSSOVER_3FULL: ClassVar[CPCrossoverBehavior] = ...
    CP_CROSSOVER_4: ClassVar[CPCrossoverBehavior] = ...
    __entries: ClassVar[dict] = ...
    nCPCrossoverBehaviors: ClassVar[CPCrossoverBehavior] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class CPResidueConnectionType:
    __members__: ClassVar[dict] = ...  # read-only
    CP_MULTIPLE_BONDS_OR_PSEUDOBONDS: ClassVar[CPResidueConnectionType] = ...
    CP_NO_BONDS: ClassVar[CPResidueConnectionType] = ...
    CP_ONE_BOND: ClassVar[CPResidueConnectionType] = ...
    __entries: ClassVar[dict] = ...
    nCPResidueConnectionTypes: ClassVar[CPResidueConnectionType] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class CountPairAll(CountPairFunction):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CountPairAll) -> None: ...
    @overload
    def __init__(self, arg0: CountPairAll) -> None: ...
    def assign(self) -> CountPairAll: ...
    def count(self, at1: int, at2: int, w: float, path_dist: int) -> bool: ...
    @overload
    def residue_atom_pair_energy(self) -> None: ...
    @overload
    def residue_atom_pair_energy(self) -> None: ...
    @overload
    def residue_atom_pair_energy_backbone_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_backbone_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_sidechain(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_sidechain(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_whole(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_whole(self) -> None: ...
    def __call__(self) -> bool: ...

class CountPairCrossover3(CountPairFunction):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CountPairCrossover3) -> None: ...
    def assign(self) -> CountPairCrossover3: ...
    @staticmethod
    def count_at_path_distance(path_distance: int, weight: float) -> bool: ...

class CountPairCrossover34(CountPairFunction):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CountPairCrossover34) -> None: ...
    def assign(self) -> CountPairCrossover34: ...
    @staticmethod
    def count_at_path_distance(path_distance: int, weight: float) -> bool: ...

class CountPairCrossover3full(CountPairFunction):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CountPairCrossover3full) -> None: ...
    def assign(self) -> CountPairCrossover3full: ...
    @staticmethod
    def count_at_path_distance(path_distance: int) -> bool: ...

class CountPairCrossover4(CountPairFunction):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CountPairCrossover4) -> None: ...
    def assign(self) -> CountPairCrossover4: ...
    @staticmethod
    def count_at_path_distance(path_distance: int, weight: float) -> bool: ...

class CountPairFactory:
    def __init__(self) -> None: ...
    @staticmethod
    def create_count_pair_function() -> CountPairFunction: ...
    @staticmethod
    def create_count_pair_function_and_invoke(invoker) -> None: ...
    @staticmethod
    def create_intrares_count_pair_function() -> CountPairFunction: ...
    @staticmethod
    def determine_residue_connection(res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue) -> CPResidueConnectionType: ...

class CountPairFunction:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CountPairFunction) -> None: ...
    def assign(self) -> CountPairFunction: ...
    def count(self, at1: int, at2: int, path_dist: int) -> bool: ...
    @overload
    def residue_atom_pair_energy(self) -> None: ...
    @overload
    def residue_atom_pair_energy(self) -> None: ...
    @overload
    def residue_atom_pair_energy_backbone_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_backbone_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_sidechain(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_sidechain(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_whole(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_whole(self) -> None: ...
    def __call__(self, at1: int, at2: int, path_dist: int) -> bool: ...

class CountPairGeneric(CountPairFunction):
    @overload
    def __init__(self, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def __init__(self, restype1: pyrosetta.rosetta.core.chemical.ResidueType, restype2: pyrosetta.rosetta.core.chemical.ResidueType, bond_pairs: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t) -> None: ...
    @overload
    def __init__(self, arg0: CountPairGeneric) -> None: ...
    @overload
    def __init__(self, arg0: CountPairGeneric) -> None: ...
    def assign(self) -> CountPairGeneric: ...
    def count(self, at1: int, at2: int, path_dist: int) -> bool: ...
    def path_distance(self, at1: int, at2: int) -> int: ...
    @overload
    def residue_atom_pair_energy(self, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def residue_atom_pair_energy(self, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def residue_atom_pair_energy_backbone_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_backbone_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_sidechain(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_sidechain(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_whole(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_whole(self) -> None: ...
    @overload
    def set_crossover(self) -> None: ...
    @overload
    def set_crossover(self, unsignedlong) -> void: ...
    def __call__(self, at1: int, at2: int, weight: float, minpathdist: int) -> bool: ...

class CountPairNone(CountPairFunction):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CountPairNone) -> None: ...
    @overload
    def __init__(self, arg0: CountPairNone) -> None: ...
    def assign(self) -> CountPairNone: ...
    def count(self, at1: int, at2: int, w: float, path_dist: int) -> bool: ...
    @overload
    def residue_atom_pair_energy(self) -> None: ...
    @overload
    def residue_atom_pair_energy(self) -> None: ...
    @overload
    def residue_atom_pair_energy_backbone_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_backbone_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_sidechain(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_sidechain(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_whole(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_whole(self) -> None: ...
    def __call__(self) -> bool: ...

class Invoker:
    def __init__(self) -> None: ...
    def assign(self) -> Invoker: ...
    @overload
    def invoke(self, cp: CountPairFunction) -> None: ...
    @overload
    def invoke(self, constclasscore) -> void: ...
