import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import overload

class ClashBasedShellSelector(pyrosetta.rosetta.core.select.residue_selector.ResidueSelector):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ClashBasedShellSelector) -> None: ...
    @overload
    def __init__(self, arg0: ClashBasedShellSelector) -> None: ...
    @overload
    def __init__(self, resnums: str) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def __init__(self, task_factory: pyrosetta.rosetta.core.pack.task.TaskFactory, focus_on_designable: bool) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def __init__(self, task: pyrosetta.rosetta.core.pack.task.PackerTask, focus_on_designable: bool) -> None: ...
    @overload
    def __init__(self, resnums: pyrosetta.rosetta.std.set_unsigned_long_t) -> None: ...
    @overload
    def __init__(self, mask: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def assign(self) -> ClashBasedShellSelector: ...
    @staticmethod
    def class_name() -> str: ...
    @overload
    def clear_focus(self) -> None: ...
    @overload
    def clear_focus(self) -> void: ...
    def clone(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    def get_bump_overlap_factor(self) -> float: ...
    @overload
    def get_bump_overlap_factor(self) -> double: ...
    @overload
    def get_include_focus(self) -> bool: ...
    @overload
    def get_include_focus(self) -> bool: ...
    def get_name(self) -> str: ...
    @overload
    def get_num_shells(self) -> int: ...
    @overload
    def get_num_shells(self) -> unsignedlong: ...
    def get_scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def invert(self) -> None: ...
    @overload
    def invert(self, inverted: bool) -> None: ...
    @overload
    def invert(self, bool) -> void: ...
    @overload
    def is_inverted(self) -> bool: ...
    @overload
    def is_inverted(self) -> bool: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, datamap: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema_attributes(attributes: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema_attributes(classstd) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_bump_overlap_factor(self, set_bump_overlap_factor: float) -> None: ...
    @overload
    def set_bump_overlap_factor(self, double) -> void: ...
    @overload
    def set_focus(self, resnums: str) -> None: ...
    @overload
    def set_focus(self, std) -> void: ...
    @overload
    def set_focus(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_focus(self, classstd) -> void: ...
    @overload
    def set_focus(self, task_factory: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_focus(self, task_factory: pyrosetta.rosetta.core.pack.task.TaskFactory, focus_on_designable: bool) -> None: ...
    @overload
    def set_focus(self, classstd, bool) -> void: ...
    @overload
    def set_focus(self, task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def set_focus(self, task: pyrosetta.rosetta.core.pack.task.PackerTask, focus_on_designable: bool) -> None: ...
    @overload
    def set_focus(self, classstd, bool) -> void: ...
    @overload
    def set_focus(self, resnums: pyrosetta.rosetta.std.set_unsigned_long_t) -> None: ...
    @overload
    def set_focus(self, classstd) -> void: ...
    @overload
    def set_focus(self, bool_mask: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def set_focus(self, classutility) -> void: ...
    @overload
    def set_include_focus(self, include_focus: bool) -> None: ...
    @overload
    def set_include_focus(self, bool) -> void: ...
    @overload
    def set_num_shells(self, num_shells: int) -> None: ...
    @overload
    def set_num_shells(self, unsignedlong) -> void: ...
    @overload
    def set_scorefxn(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn(self, classstd) -> void: ...

class ClashBasedShellSelectorCreator(pyrosetta.rosetta.core.select.residue_selector.ResidueSelectorCreator):
    def __init__(self) -> None: ...
    def assign(self) -> ClashBasedShellSelectorCreator: ...
    def create_residue_selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

@overload
def add_clashes_to_shell(pose: pyrosetta.rosetta.core.pose.Pose, rot1: pyrosetta.rosetta.core.conformation.Residue, focus: pyrosetta.rosetta.std.set_unsigned_long_t, shell: pyrosetta.rosetta.std.set_unsigned_long_t) -> None: ...
@overload
def add_clashes_to_shell(pose: pyrosetta.rosetta.core.pose.Pose, rot1: pyrosetta.rosetta.core.conformation.Residue, bump_factor: float, focus: pyrosetta.rosetta.std.set_unsigned_long_t, shell: pyrosetta.rosetta.std.set_unsigned_long_t) -> None: ...
def bool_mask_from_resnums(pose: pyrosetta.rosetta.core.pose.Pose, resis: pyrosetta.rosetta.std.set_unsigned_long_t) -> pyrosetta.rosetta.utility.vector1_bool: ...
def bool_mask_from_task(task: pyrosetta.rosetta.core.pack.task.PackerTask) -> pyrosetta.rosetta.utility.vector1_bool: ...
@overload
def find_clashing_shell(focus: pyrosetta.rosetta.core.pack.task.PackerTask, pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> pyrosetta.rosetta.std.set_unsigned_long_t: ...
@overload
def find_clashing_shell(focus: pyrosetta.rosetta.core.pack.task.PackerTask, pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, bump_factor: float) -> pyrosetta.rosetta.std.set_unsigned_long_t: ...
@overload
def find_clashing_shells(focus: pyrosetta.rosetta.core.pack.task.PackerTask, pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> pyrosetta.rosetta.std.set_unsigned_long_t: ...
@overload
def find_clashing_shells(focus: pyrosetta.rosetta.core.pack.task.PackerTask, pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, num_shells: int) -> pyrosetta.rosetta.std.set_unsigned_long_t: ...
@overload
def find_clashing_shells(focus: pyrosetta.rosetta.core.pack.task.PackerTask, pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, num_shells: int, include_focus: bool) -> pyrosetta.rosetta.std.set_unsigned_long_t: ...
@overload
def find_clashing_shells(focus: pyrosetta.rosetta.core.pack.task.PackerTask, pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, num_shells: int, include_focus: bool, bump_factor: float) -> pyrosetta.rosetta.std.set_unsigned_long_t: ...
@overload
def is_sc_bb_clash(sc_rsd: pyrosetta.rosetta.core.conformation.Residue, bb_rsd: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
@overload
def is_sc_bb_clash(sc_rsd: pyrosetta.rosetta.core.conformation.Residue, bb_rsd: pyrosetta.rosetta.core.conformation.Residue, bump_factor: float) -> bool: ...
@overload
def is_sc_sc_clash(rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
@overload
def is_sc_sc_clash(rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, bump_factor: float) -> bool: ...
def resnums_from_bool_mask(mask: pyrosetta.rosetta.utility.vector1_bool) -> pyrosetta.rosetta.std.set_unsigned_long_t: ...
def resnums_from_task(task: pyrosetta.rosetta.core.pack.task.PackerTask) -> pyrosetta.rosetta.std.set_unsigned_long_t: ...
def task_from_bool_mask(pose: pyrosetta.rosetta.core.pose.Pose, mask: pyrosetta.rosetta.utility.vector1_bool) -> pyrosetta.rosetta.core.pack.task.PackerTask: ...
def task_from_resnums(pose: pyrosetta.rosetta.core.pose.Pose, resnums: pyrosetta.rosetta.std.set_unsigned_long_t) -> pyrosetta.rosetta.core.pack.task.PackerTask: ...
