import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.pose.rna
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.utility
from . import options as options, params as params, sampler as sampler, scratch as scratch
from typing import overload

class Histogram:
    @overload
    def __init__(self, min: float, max: float, spacing: float) -> None: ...
    @overload
    def __init__(self, arg0: Histogram) -> None: ...
    @overload
    def add(self, value: float, n_items: int) -> None: ...
    @overload
    def add(self, constfloat, constunsignedlong) -> void: ...
    def assign(self) -> Histogram: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    def get_hist(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def get_scores(self) -> pyrosetta.rosetta.utility.vector1_double: ...

class RECCES_Mover(pyrosetta.rosetta.protocols.moves.Mover):
    def __init__(self, options) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def set_parameters(self, params) -> None: ...
    @overload
    def set_parameters(self, classstd) -> void: ...
    @overload
    def set_scorefxn(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn(self, classstd) -> void: ...

@overload
def data_dim(score_types: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> int: ...
@overload
def data_dim(constclassutility) -> unsignedlong: ...
@overload
def data_dim() -> int: ...
@overload
def data_dim() -> unsignedlong: ...
@overload
def fill_data(data: pyrosetta.rosetta.utility.vector1_float, count: int, scores: pyrosetta.rosetta.utility.vector1_float) -> None: ...
@overload
def fill_data(classutility, constunsignedlong, constclassutility) -> void: ...
def gaussian_stdev(n_rsd: float, temp: float, is_bp: bool) -> float: ...
def get_scoretypes() -> pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType: ...
def get_torsions(torsion_ids: pyrosetta.rosetta.utility.vector1_core_id_TorsionID, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_double: ...
def pose_setup_from_file(options: options.RECCES_Options) -> pyrosetta.rosetta.core.pose.Pose: ...
def pose_setup_turner(seq1: str, seq2: str) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def print_base_centroid_atoms_for_rb_entropy(rsd: pyrosetta.rosetta.core.conformation.Residue, filename_xyz: str) -> None: ...
@overload
def print_base_centroid_atoms_for_rb_entropy(constclasscore, std) -> void: ...
def recces_pose_setup(options: options.RECCES_Options) -> pyrosetta.rosetta.core.pose.Pose: ...
def set_gaussian_stdevs_recces_turner(sampler: sampler.MC_Comb, temperature: float, pose: pyrosetta.rosetta.core.pose.Pose, rna_secstruct: pyrosetta.rosetta.core.pose.rna.RNA_SecStruct, params: params.RECCES_Parameters) -> None: ...
def set_gaussian_stdevs_thermal_sampler(sampler: sampler.MC_Sampler, temperature: float, pose: pyrosetta.rosetta.core.pose.Pose, options: options.RECCES_Options) -> None: ...
def set_sampler_gaussian_stdev(sampler: sampler.MC_Comb, temperature: float, pose: pyrosetta.rosetta.core.pose.Pose, options: options.RECCES_Options, params: params.RECCES_Parameters) -> None: ...
@overload
def update_scores(scores: pyrosetta.rosetta.utility.vector1_float, pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
@overload
def update_scores(classutility, classcore, classstd) -> void: ...
@overload
def update_scores(scores: pyrosetta.rosetta.utility.vector1_float, pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, scoretypes: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
@overload
def update_scores(classutility, classcore, classstd, constclassutility) -> void: ...
