import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import overload

class ThermalMinimizer(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ThermalMinimizer) -> None: ...
    @overload
    def __init__(self, arg0: ThermalMinimizer) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> ThermalMinimizer: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def kic_sampling(self) -> bool: ...
    @overload
    def kic_sampling(self) -> bool: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def output_min_pose(self) -> bool: ...
    @overload
    def output_min_pose(self) -> bool: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def set_kic_sampling(self, setting: bool) -> None: ...
    @overload
    def set_mm(self, mm: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def set_mm(self, classstd) -> void: ...
    @overload
    def set_n_cycle(self, setting: int) -> None: ...
    @overload
    def set_n_cycle(self, constunsignedlong) -> void: ...
    def set_output_min_pose(self, setting: bool) -> None: ...
    @overload
    def set_scorefxn(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn(self, classstd) -> void: ...
    @overload
    def set_temp(self, temp: float) -> None: ...
    @overload
    def set_temp(self, constdouble) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class ThermalMinimizerCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ThermalMinimizerCreator) -> None: ...
    @overload
    def __init__(self, arg0: ThermalMinimizerCreator) -> None: ...
    def assign(self) -> ThermalMinimizerCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ThermalSamplingMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ThermalSamplingMover) -> None: ...
    @overload
    def __init__(self, arg0: ThermalSamplingMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> ThermalSamplingMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def free_rsd(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def residues(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def set_dump_pdb(self, setting: bool) -> None: ...
    @overload
    def set_dump_pdb(self, constbool) -> void: ...
    @overload
    def set_dump_silent(self, setting: bool) -> None: ...
    @overload
    def set_dump_silent(self, constbool) -> void: ...
    @overload
    def set_dumping_app(self, setting: bool) -> None: ...
    @overload
    def set_dumping_app(self, constbool) -> void: ...
    @overload
    def set_free_rsd(self, free_rsd: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_free_rsd(self, constclassutility) -> void: ...
    @overload
    def set_n_cycle(self, setting: int) -> None: ...
    @overload
    def set_n_cycle(self, constunsignedlong) -> void: ...
    @overload
    def set_recces_turner_mode(self, setting: bool) -> None: ...
    @overload
    def set_recces_turner_mode(self, constbool) -> void: ...
    def set_residue_sampling_from_pose_and_movemap(self, pose: pyrosetta.rosetta.core.pose.Pose, mm: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def set_residues(self, residues: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_residues(self, constclassutility) -> void: ...
    @overload
    def set_temps(self, temps: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_temps(self, constclassutility) -> void: ...
    @overload
    def set_weights(self, weights: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_weights(self, constclassutility) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class ThermalSamplingMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ThermalSamplingMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: ThermalSamplingMoverCreator) -> None: ...
    def assign(self) -> ThermalSamplingMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

def get_torsions(torsion_ids: pyrosetta.rosetta.utility.vector1_core_id_TorsionID, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_double: ...
