import pyrosetta.rosetta.ObjexxFCL
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.io.silent
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.scoring.constraints
import pyrosetta.rosetta.core.sequence
import pyrosetta.rosetta.protocols.evaluation
import pyrosetta.rosetta.protocols.jd2
import pyrosetta.rosetta.protocols.jd2.JobInputterInputSource
import pyrosetta.rosetta.protocols.loops
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from . import features as features
from typing import overload

class AlignRmsdTargetEvaluatorCreator(pyrosetta.rosetta.protocols.evaluation.EvaluatorCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AlignRmsdTargetEvaluatorCreator) -> None: ...
    @overload
    def __init__(self, arg0: AlignRmsdTargetEvaluatorCreator) -> None: ...
    @overload
    def add_evaluators(self, eval: pyrosetta.rosetta.protocols.evaluation.MetaPoseEvaluator) -> None: ...
    @overload
    def add_evaluators(self, classprotocols) -> void: ...
    def assign(self) -> AlignRmsdTargetEvaluatorCreator: ...
    @overload
    def register_options(self) -> None: ...
    @overload
    def register_options(self) -> void: ...
    def type_name(self) -> str: ...

class Align_RmsdEvaluator(pyrosetta.rosetta.protocols.evaluation.AlignEvaluator):
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: str, arg2: bool) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: str, arg2: bool, arg3: pyrosetta.rosetta.core.sequence.SequenceAlignment) -> None: ...
    @overload
    def __init__(self, native_pose: pyrosetta.rosetta.core.pose.Pose, tag: str, calc_gdt: bool, aln: pyrosetta.rosetta.core.sequence.SequenceAlignment, gdt_by_TM: bool) -> None: ...
    @overload
    def __init__(self, arg0: Align_RmsdEvaluator) -> None: ...
    @overload
    def __init__(self, arg0: Align_RmsdEvaluator) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose, tag: str, ss: pyrosetta.rosetta.core.io.silent.SilentStruct) -> None: ...
    @overload
    def apply(self) -> float: ...
    @overload
    def apply(self, classcore) -> double: ...
    def assign(self) -> Align_RmsdEvaluator: ...
    @overload
    def calc_gdt(self, setting: bool) -> None: ...
    @overload
    def calc_gdt(self, constbool) -> void: ...
    @overload
    def calc_gdt(self) -> bool: ...
    @overload
    def calc_gdt(self) -> bool: ...
    @overload
    def gdt_by_TM(self, setting: bool) -> None: ...
    @overload
    def gdt_by_TM(self, constbool) -> void: ...
    @overload
    def gdt_by_TM(self) -> bool: ...
    @overload
    def gdt_by_TM(self) -> bool: ...
    @overload
    def report_gdt_components(self, setting: bool) -> None: ...
    @overload
    def report_gdt_components(self, constbool) -> void: ...
    @overload
    def report_gdt_components(self) -> bool: ...
    @overload
    def report_gdt_components(self) -> bool: ...

class Align_RotamerEvaluator(pyrosetta.rosetta.protocols.evaluation.AlignEvaluator):
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: str, arg2: float) -> None: ...
    @overload
    def __init__(self, native_pose: pyrosetta.rosetta.core.pose.Pose, tag: str, chi_dev: float, aln: pyrosetta.rosetta.core.sequence.SequenceAlignment) -> None: ...
    @overload
    def __init__(self, arg0: Align_RotamerEvaluator) -> None: ...
    @overload
    def __init__(self, arg0: Align_RotamerEvaluator) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose, tag: str, ss: pyrosetta.rosetta.core.io.silent.SilentStruct) -> None: ...
    @overload
    def apply(self) -> float: ...
    @overload
    def apply(self, classcore) -> double: ...
    def assign(self) -> Align_RotamerEvaluator: ...
    @overload
    def chi_dev(self) -> float: ...
    @overload
    def chi_dev(self) -> double: ...

class AlignmentCluster:
    @overload
    def __init__(self, aln_in: pyrosetta.rosetta.core.sequence.SequenceAlignment) -> None: ...
    @overload
    def __init__(self, arg0: AlignmentCluster) -> None: ...
    @overload
    def add_aln(self, aln_in: pyrosetta.rosetta.core.sequence.SequenceAlignment) -> None: ...
    @overload
    def add_aln(self, classcore) -> void: ...
    def assign(self) -> AlignmentCluster: ...
    def get_aln(self, index: int) -> pyrosetta.rosetta.core.sequence.SequenceAlignment: ...
    def get_clusterCenter(self) -> pyrosetta.rosetta.core.sequence.SequenceAlignment: ...
    @overload
    def merge(self, cluster_in: AlignmentCluster) -> None: ...
    @overload
    def merge(self, classstd) -> void: ...
    @overload
    def output(self, alignment_out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def output(self, std) -> void: ...
    @overload
    def overlap(self, cluster_in: AlignmentCluster) -> float: ...
    @overload
    def overlap(self, classstd) -> double: ...
    @overload
    def size(self) -> float: ...
    @overload
    def size(self) -> double: ...

class AlignmentClustering:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AlignmentClustering) -> None: ...
    def assign(self) -> AlignmentClustering: ...

class AlignmentSet:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AlignmentSet) -> None: ...
    def alignments(self) -> pyrosetta.rosetta.utility.vector1_core_sequence_SequenceAlignment: ...
    def assign(self) -> AlignmentSet: ...
    @overload
    def insert(self, aln: pyrosetta.rosetta.core.sequence.SequenceAlignment) -> None: ...
    @overload
    def insert(self, classcore) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...

class ExtraThreadingMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, align: pyrosetta.rosetta.core.sequence.SequenceAlignment, template_pose: pyrosetta.rosetta.core.pose.Pose, residue_selection: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, arg0: ExtraThreadingMover) -> None: ...
    @overload
    def __init__(self, arg0: ExtraThreadingMover) -> None: ...
    def alignment(self) -> pyrosetta.rosetta.core.sequence.SequenceAlignment: ...
    @overload
    def apply(self, query_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> ExtraThreadingMover: ...
    def get_name(self) -> str: ...
    def get_qt_mapping(self, query_pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.id.SequenceMapping: ...
    @overload
    def query_index(self) -> int: ...
    @overload
    def query_index(self) -> unsignedlong: ...
    @overload
    def template_index(self) -> int: ...
    @overload
    def template_index(self) -> unsignedlong: ...

class GenericJobInputter(pyrosetta.rosetta.protocols.jd2.JobInputter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GenericJobInputter) -> None: ...
    @overload
    def __init__(self, arg0: GenericJobInputter) -> None: ...
    def assign(self) -> GenericJobInputter: ...
    @overload
    def fill_jobs(self, jobs) -> None: ...
    @overload
    def fill_jobs(self, classprotocols) -> void: ...
    def input_source(self, *args, **kwargs): ...
    @overload
    def pose_from_job(self, pose: pyrosetta.rosetta.core.pose.Pose, job) -> None: ...
    @overload
    def pose_from_job(self, classcore, classstd) -> void: ...

class GenericJobInputterCreator(pyrosetta.rosetta.protocols.jd2.JobInputterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GenericJobInputterCreator) -> None: ...
    @overload
    def __init__(self, arg0: GenericJobInputterCreator) -> None: ...
    def assign(self) -> GenericJobInputterCreator: ...
    def create_JobInputter(self) -> pyrosetta.rosetta.protocols.jd2.JobInputter: ...
    def keyname(self) -> str: ...

class IgnoreSubsetConstraintSet(pyrosetta.rosetta.core.scoring.constraints.ConstraintSet):
    @overload
    def __init__(self, arg0: IgnoreSubsetConstraintSet) -> None: ...
    @overload
    def __init__(self, arg0: IgnoreSubsetConstraintSet) -> None: ...
    @overload
    def __init__(self, residues_to_ignore: pyrosetta.rosetta.std.set_int_t, other: pyrosetta.rosetta.core.scoring.constraints.ConstraintSet) -> None: ...
    @overload
    def assign(self, rhs: pyrosetta.rosetta.core.scoring.constraints.ConstraintSet) -> pyrosetta.rosetta.core.scoring.constraints.ConstraintSet: ...
    @overload
    def assign(self) -> IgnoreSubsetConstraintSet: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.constraints.ConstraintSet: ...
    def detached_clone(self) -> pyrosetta.rosetta.core.scoring.constraints.ConstraintSet: ...
    @overload
    def detached_copy(self, src: pyrosetta.rosetta.core.scoring.constraints.ConstraintSet) -> None: ...
    @overload
    def detached_copy(self, constclasscore) -> void: ...
    @overload
    def ignore(self, pos: int) -> bool: ...
    @overload
    def ignore(self, constint) -> bool: ...
    def ignore_list(self) -> pyrosetta.rosetta.std.set_int_t: ...
    @overload
    def ignore_residue(self, pos: int) -> None: ...
    @overload
    def ignore_residue(self, constint) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def residue_pair_constraint_exists(self, pos1: int, pos2: int) -> bool: ...
    def residue_pair_energy(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.constraints.ConstraintSet) -> bool: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.constraints.ConstraintSet, recurse: bool) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore, bool) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def setup_for_minimizing_for_residue(self, rsd: pyrosetta.rosetta.core.conformation.Residue, pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, minmap: pyrosetta.rosetta.core.kinematics.MinimizerMapBase, res_data_cache: pyrosetta.rosetta.core.scoring.ResSingleMinimizationData) -> None: ...
    def setup_for_minimizing_for_residue_pair(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, minmap: pyrosetta.rosetta.core.kinematics.MinimizerMapBase, res1_data_cache: pyrosetta.rosetta.core.scoring.ResSingleMinimizationData, res2_data_cache: pyrosetta.rosetta.core.scoring.ResSingleMinimizationData, respair_data_cache: pyrosetta.rosetta.core.scoring.ResPairMinimizationData) -> None: ...

class LoopRelaxThreadingMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LoopRelaxThreadingMover) -> None: ...
    @overload
    def __init__(self, arg0: LoopRelaxThreadingMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> LoopRelaxThreadingMover: ...
    def get_name(self) -> str: ...
    @overload
    def setup(self) -> None: ...
    @overload
    def setup(self) -> void: ...

class MultiThreadingMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, aligns: pyrosetta.rosetta.utility.vector1_core_sequence_SequenceAlignment, template_poses: pyrosetta.rosetta.utility.vector1_core_pose_Pose) -> None: ...
    @overload
    def __init__(self, arg0: MultiThreadingMover) -> None: ...
    @overload
    def __init__(self, arg0: MultiThreadingMover) -> None: ...
    @overload
    def apply(self, query_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> MultiThreadingMover: ...
    @overload
    def build_loops(self, setting: bool) -> None: ...
    @overload
    def build_loops(self, bool) -> void: ...
    @overload
    def build_loops(self) -> bool: ...
    @overload
    def build_loops(self) -> bool: ...
    @overload
    def frag_libs(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_fragment_FragSet_t: ...
    @overload
    def frag_libs(self, new_libs: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_fragment_FragSet_t) -> None: ...
    @overload
    def frag_libs(self, classutility) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def min_loop_size(self, new_size: int) -> None: ...
    @overload
    def min_loop_size(self, constunsignedlong) -> void: ...
    @overload
    def min_loop_size(self) -> int: ...
    @overload
    def min_loop_size(self) -> unsignedlong: ...
    @overload
    def randomize_loop_coords(self, setting: bool) -> None: ...
    @overload
    def randomize_loop_coords(self, bool) -> void: ...
    @overload
    def randomize_loop_coords(self) -> bool: ...
    @overload
    def randomize_loop_coords(self) -> bool: ...
    @overload
    def repack_query(self, setting: bool) -> None: ...
    @overload
    def repack_query(self, bool) -> void: ...
    @overload
    def repack_query(self) -> bool: ...
    @overload
    def repack_query(self) -> bool: ...

class PartialThreadingMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.sequence.SequenceAlignment, arg1: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, align: pyrosetta.rosetta.core.sequence.SequenceAlignment, template_pose: pyrosetta.rosetta.core.pose.Pose, skip_repack: bool) -> None: ...
    @overload
    def __init__(self, arg0: PartialThreadingMover) -> None: ...
    @overload
    def __init__(self, arg0: PartialThreadingMover) -> None: ...
    @overload
    def apply(self, query_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> PartialThreadingMover: ...
    def get_name(self) -> str: ...

class RecoverSideChainsMover(pyrosetta.rosetta.protocols.moves.Mover):
    def __init__(self, mover: pyrosetta.rosetta.protocols.moves.Mover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def get_name(self) -> str: ...

class StealLigandMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, source: pyrosetta.rosetta.core.pose.Pose, anchor_atom_dest: pyrosetta.rosetta.core.id.NamedAtomID, anchor_atom_source: pyrosetta.rosetta.core.id.NamedAtomID, ligand_indices: pyrosetta.rosetta.utility.vector1_core_id_NamedAtomID) -> None: ...
    @overload
    def __init__(self, arg0: StealLigandMover) -> None: ...
    @overload
    def __init__(self, arg0: StealLigandMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def get_name(self) -> str: ...

class StealSideChainsMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, source: pyrosetta.rosetta.core.pose.Pose, map: pyrosetta.rosetta.core.id.SequenceMapping) -> None: ...
    @overload
    def __init__(self, arg0: StealSideChainsMover) -> None: ...
    @overload
    def __init__(self, arg0: StealSideChainsMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def get_name(self) -> str: ...

class ThreadingJob(pyrosetta.rosetta.protocols.jd2.InnerJob):
    @overload
    def __init__(self, template_pdb: pyrosetta.rosetta.core.pose.Pose, alignment: pyrosetta.rosetta.core.sequence.SequenceAlignment, input_tag: str, nstruct_max: int) -> None: ...
    @overload
    def __init__(self, arg0: ThreadingJob) -> None: ...
    @overload
    def __init__(self, arg0: ThreadingJob) -> None: ...
    def alignment(self) -> pyrosetta.rosetta.core.sequence.SequenceAlignment: ...
    def alignment_id(self) -> str: ...
    @staticmethod
    def current_job() -> ThreadingJob: ...
    @overload
    def extra_residues_to_steal(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def extra_residues_to_steal(self, res: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def extra_residues_to_steal(self, constclassutility) -> void: ...
    def loops(self, nres: int) -> pyrosetta.rosetta.protocols.loops.Loops: ...

class ThreadingJobInputter(pyrosetta.rosetta.protocols.jd2.JobInputter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ThreadingJobInputter) -> None: ...
    @overload
    def __init__(self, arg0: ThreadingJobInputter) -> None: ...
    def assign(self) -> ThreadingJobInputter: ...
    @overload
    def fill_jobs(self, jobs) -> None: ...
    @overload
    def fill_jobs(self, classprotocols) -> void: ...
    def input_source(self) -> pyrosetta.rosetta.protocols.jd2.JobInputterInputSource.Enum: ...
    @overload
    def pose_from_job(self, pose: pyrosetta.rosetta.core.pose.Pose, job) -> None: ...
    @overload
    def pose_from_job(self, classcore, classstd) -> void: ...

class ThreadingJobInputterCreator(pyrosetta.rosetta.protocols.jd2.JobInputterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ThreadingJobInputterCreator) -> None: ...
    @overload
    def __init__(self, arg0: ThreadingJobInputterCreator) -> None: ...
    def assign(self) -> ThreadingJobInputterCreator: ...
    def create_JobInputter(self) -> pyrosetta.rosetta.protocols.jd2.JobInputter: ...
    def keyname(self) -> str: ...

class ThreadingMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ThreadingMover) -> None: ...
    @overload
    def __init__(self, arg0: ThreadingMover) -> None: ...
    @overload
    def __init__(self, align: pyrosetta.rosetta.core.sequence.SequenceAlignment, template_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def alignment(self) -> pyrosetta.rosetta.core.sequence.SequenceAlignment: ...
    @overload
    def alignment(self, new_align: pyrosetta.rosetta.core.sequence.SequenceAlignment) -> None: ...
    @overload
    def alignment(self, classcore) -> void: ...
    @overload
    def apply(self, query_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> ThreadingMover: ...
    @overload
    def build_loops(self, setting: bool) -> None: ...
    @overload
    def build_loops(self, bool) -> void: ...
    @overload
    def build_loops(self) -> bool: ...
    @overload
    def build_loops(self) -> bool: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def frag_libs(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_fragment_FragSet_t: ...
    @overload
    def frag_libs(self, new_libs: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_fragment_FragSet_t) -> None: ...
    @overload
    def frag_libs(self, classutility) -> void: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    def get_qt_mapping(self, query_pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.id.SequenceMapping: ...
    @overload
    def min_loop_size(self, new_size: int) -> None: ...
    @overload
    def min_loop_size(self, constunsignedlong) -> void: ...
    @overload
    def min_loop_size(self) -> int: ...
    @overload
    def min_loop_size(self) -> unsignedlong: ...
    @overload
    def query_index(self) -> int: ...
    @overload
    def query_index(self) -> unsignedlong: ...
    @overload
    def query_index(self, new_index: int) -> None: ...
    @overload
    def query_index(self, unsignedlong) -> void: ...
    @overload
    def randomize_loop_coords(self, setting: bool) -> None: ...
    @overload
    def randomize_loop_coords(self, bool) -> void: ...
    @overload
    def randomize_loop_coords(self) -> bool: ...
    @overload
    def randomize_loop_coords(self) -> bool: ...
    @overload
    def repack_query(self, setting: bool) -> None: ...
    @overload
    def repack_query(self, bool) -> void: ...
    @overload
    def repack_query(self) -> bool: ...
    @overload
    def repack_query(self) -> bool: ...
    @overload
    def template_index(self) -> int: ...
    @overload
    def template_index(self) -> unsignedlong: ...
    @overload
    def template_index(self, new_index: int) -> None: ...
    @overload
    def template_index(self, unsignedlong) -> void: ...
    @overload
    def template_pose(self, template_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def template_pose(self, classcore) -> void: ...

def alignments_from_cmd_line() -> AlignmentSet: ...
def bounded_loops_from_alignment(num_residues: int, min_size: int, alignment: pyrosetta.rosetta.core.sequence.SequenceAlignment, unaligned_regions: pyrosetta.rosetta.protocols.loops.Loops) -> None: ...
@overload
def cm_main() -> None: ...
@overload
def cm_main() -> void: ...
@overload
def gather_coords(model: pyrosetta.rosetta.core.pose.Pose, native: pyrosetta.rosetta.core.pose.Pose, aln: pyrosetta.rosetta.core.sequence.SequenceAlignment, natoms: int, p1a: pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t, p2a: pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t) -> None: ...
@overload
def gather_coords(model: pyrosetta.rosetta.core.pose.Pose, native: pyrosetta.rosetta.core.pose.Pose, aln: pyrosetta.rosetta.core.sequence.SequenceAlignment, natoms: int, p1a: pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t, p2a: pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t, atom_name: str) -> None: ...
def get_qt_mapping_general(query_pose: pyrosetta.rosetta.core.pose.Pose, align: pyrosetta.rosetta.core.sequence.SequenceAlignment, template_pose: pyrosetta.rosetta.core.pose.Pose, query_index: int, template_index: int) -> pyrosetta.rosetta.core.id.SequenceMapping: ...
@overload
def initialize_ss(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def initialize_ss(classcore) -> void: ...
@overload
def loops_are_closed(pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
@overload
def loops_are_closed(classcore) -> bool: ...
def loops_from_alignment(nres: int, aln: pyrosetta.rosetta.core.sequence.SequenceAlignment, min_loop_size: int) -> pyrosetta.rosetta.protocols.loops.Loops: ...
def loops_from_transitive_alignments(nres1: int, aln1: pyrosetta.rosetta.core.sequence.SequenceAlignment, nres2: int, aln2: pyrosetta.rosetta.core.sequence.SequenceAlignment, min_loop_size: int) -> pyrosetta.rosetta.protocols.loops.Loops: ...
def poses_from_cmd_line(fn_list: pyrosetta.rosetta.utility.vector1_std_string) -> pyrosetta.rosetta.std.map_std_string_core_pose_Pose: ...
@overload
def randomize_selected_atoms(query_pose: pyrosetta.rosetta.core.pose.Pose, selected: pyrosetta.rosetta.core.id.AtomID_Map_bool_t) -> None: ...
@overload
def randomize_selected_atoms(classcore, constclasscore) -> void: ...
def rebuild_loops_until_closed(query_pose: pyrosetta.rosetta.core.pose.Pose, min_loop_size: int, max_times: int, loop_mover_name: str) -> None: ...
def steal_ligands(dest_pose: pyrosetta.rosetta.core.pose.Pose, source_pose_in: pyrosetta.rosetta.core.pose.Pose, anchor_atom_dest: pyrosetta.rosetta.core.id.NamedAtomID, anchor_atom_source: pyrosetta.rosetta.core.id.NamedAtomID, ligand_indices: pyrosetta.rosetta.utility.vector1_core_id_NamedAtomID) -> None: ...
def templates_from_cmd_line() -> pyrosetta.rosetta.utility.vector1_core_pose_Pose: ...
