import pyrosetta.rosetta.core.id
from _typeshed import Incomplete
from typing import ClassVar, overload

A: TorsionBin
B: TorsionBin
E: TorsionBin
E_SS: SSType
G: TorsionBin
H_SS: SSType
INVALID: TorsionBin
INVALID_SS: SSType
L_SS: SSType
O: TorsionBin
X: TorsionBin
n_ss_types: SSType
n_torsion_bins: TorsionBin

class ResidueFeature:
    def __init__(self, *args, **kwargs) -> None: ...
    def assign(self) -> ResidueFeature: ...
    def clone(self) -> ResidueFeature: ...
    @overload
    def remap(self, mapping: pyrosetta.rosetta.core.id.SequenceMapping) -> None: ...
    @overload
    def remap(self, constclasscore) -> void: ...
    @overload
    def resnum(self) -> int: ...
    @overload
    def resnum(self) -> unsignedlong: ...
    @overload
    def resnum(self, resnum: int) -> None: ...
    @overload
    def resnum(self, constunsignedlong) -> void: ...
    def type(self) -> str: ...

class ResidueFeatureFactory:
    feature_types_: Incomplete
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ResidueFeatureFactory) -> None: ...
    @overload
    def add_type(self, feature_: ResidueFeature) -> None: ...
    @overload
    def add_type(self, classstd) -> void: ...
    def assign(self) -> ResidueFeatureFactory: ...
    def get_residue_feature(self, type: str) -> ResidueFeature: ...

class SSFeature(ResidueFeature):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, bin: SSType) -> None: ...
    @overload
    def __init__(self, arg0: SSFeature) -> None: ...
    @overload
    def __init__(self, arg0: SSFeature) -> None: ...
    def assign(self) -> SSFeature: ...
    @staticmethod
    def char2ss_type(ss: str) -> SSType: ...
    def clone(self) -> ResidueFeature: ...
    def ss_type(self) -> SSType: ...
    def type(self) -> str: ...

class SSType:
    __members__: ClassVar[dict] = ...  # read-only
    E_SS: ClassVar[SSType] = ...
    H_SS: ClassVar[SSType] = ...
    INVALID_SS: ClassVar[SSType] = ...
    L_SS: ClassVar[SSType] = ...
    __entries: ClassVar[dict] = ...
    n_ss_types: ClassVar[SSType] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class TorsionBin:
    __members__: ClassVar[dict] = ...  # read-only
    A: ClassVar[TorsionBin] = ...
    B: ClassVar[TorsionBin] = ...
    E: ClassVar[TorsionBin] = ...
    G: ClassVar[TorsionBin] = ...
    INVALID: ClassVar[TorsionBin] = ...
    O: ClassVar[TorsionBin] = ...
    X: ClassVar[TorsionBin] = ...
    __entries: ClassVar[dict] = ...
    n_torsion_bins: ClassVar[TorsionBin] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class TorsionFeature(ResidueFeature):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, bin: TorsionBin) -> None: ...
    @overload
    def __init__(self, arg0: TorsionFeature) -> None: ...
    @overload
    def __init__(self, arg0: TorsionFeature) -> None: ...
    def assign(self) -> TorsionFeature: ...
    def clone(self) -> ResidueFeature: ...
    @staticmethod
    def torsion2big_bin(phi: float, psi: float, omega: float) -> TorsionBin: ...
    def torsion_bin(self) -> TorsionBin: ...
    def type(self) -> str: ...
