import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.kinematics.jacobian
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.protocols.loops
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility.tag
from typing import overload

class JacobiLoopClosureMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: JacobiLoopClosureMover) -> None: ...
    @overload
    def __init__(self, arg0: JacobiLoopClosureMover) -> None: ...
    @overload
    def __init__(self, loop: pyrosetta.rosetta.protocols.loops.Loop) -> None: ...
    @overload
    def __init__(self, loop: pyrosetta.rosetta.protocols.loops.Loop, mm: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> JacobiLoopClosureMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def current_closed_as_target(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def current_closed_as_target(self, constclasscore) -> void: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def get_allowed_norm_lin(self) -> float: ...
    @overload
    def get_allowed_norm_lin(self) -> double: ...
    @overload
    def get_allowed_norm_rot(self) -> float: ...
    @overload
    def get_allowed_norm_rot(self) -> double: ...
    def get_jacobian_chain(self) -> pyrosetta.rosetta.core.kinematics.jacobian.SeriesJacobians: ...
    def get_loop(self) -> pyrosetta.rosetta.protocols.loops.Loop: ...
    @overload
    def get_max_cycles(self) -> int: ...
    @overload
    def get_max_cycles(self) -> unsignedlong: ...
    def get_movemap(self) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    def get_name(self) -> str: ...
    @overload
    def init_apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def init_apply(self, classcore) -> void: ...
    @overload
    def last_closure_cycles(self) -> int: ...
    @overload
    def last_closure_cycles(self) -> unsignedlong: ...
    @overload
    def last_closure_success(self) -> bool: ...
    @overload
    def last_closure_success(self) -> bool: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def set_error_norms(self, error_norm_rot: float, error_norm_lin: float) -> None: ...
    @overload
    def set_loop(self, new_loop: pyrosetta.rosetta.protocols.loops.Loop) -> None: ...
    @overload
    def set_loop(self, constclassprotocols) -> void: ...
    @overload
    def set_max_cycles(self, max_cycles: int) -> None: ...
    @overload
    def set_max_cycles(self, unsignedlong) -> void: ...
    @overload
    def set_movemap(self, new_mm: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def set_movemap(self, constclassstd) -> void: ...
    @overload
    def set_verbose(self, setting: bool) -> None: ...
    @overload
    def set_verbose(self, bool) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class JacobiLoopClosureMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: JacobiLoopClosureMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: JacobiLoopClosureMoverCreator) -> None: ...
    def assign(self) -> JacobiLoopClosureMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
