import pyrosetta.rosetta.ObjexxFCL
import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.scoring.etable.coulomb
import pyrosetta.rosetta.core.scoring.etable.count_pair
import pyrosetta.rosetta.core.scoring.methods
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from . import electrie as electrie
from typing import overload

class CountPairRepMap:
    def __init__(self) -> None: ...
    def get_map(self, restype: pyrosetta.rosetta.core.chemical.ResidueType) -> pyrosetta.rosetta.std.map_unsigned_long_unsigned_long: ...
    @overload
    def has(self, restype: pyrosetta.rosetta.core.chemical.ResidueType) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def restype_destruction_observer(self, event: pyrosetta.rosetta.core.chemical.RestypeDestructionEvent) -> None: ...
    @overload
    def restype_destruction_observer(self, conststructcore) -> void: ...

class CountPairRepresentative(pyrosetta.rosetta.core.scoring.etable.count_pair.CountPairFunction):
    @overload
    def __init__(self, energy: FA_ElecEnergy, r1: pyrosetta.rosetta.core.conformation.Residue, r2: pyrosetta.rosetta.core.conformation.Residue, inner_cpfxn: pyrosetta.rosetta.core.scoring.etable.count_pair.CountPairFunction) -> None: ...
    @overload
    def __init__(self, arg0: CountPairRepresentative) -> None: ...
    @overload
    def __init__(self, arg0: CountPairRepresentative) -> None: ...
    def count(self, at1: int, at2: int, weight: float, path_dist: int) -> bool: ...
    @overload
    def residue_atom_pair_energy(self) -> None: ...
    @overload
    def residue_atom_pair_energy(self) -> None: ...
    @overload
    def residue_atom_pair_energy_backbone_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_backbone_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_backbone(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_sidechain(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_sidechain(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_whole(self) -> None: ...
    @overload
    def residue_atom_pair_energy_sidechain_whole(self) -> None: ...

class ElecGroup:
    atms: pyrosetta.rosetta.utility.vector1_unsigned_long
    comatms: pyrosetta.rosetta.utility.vector1_unsigned_long
    n_acceptor: int
    n_donor: int
    qeps: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ElecGroup) -> None: ...
    def assign(self) -> ElecGroup: ...

class FA_ElecEnergy(pyrosetta.rosetta.core.scoring.methods.ContextIndependentTwoBodyEnergy):
    @overload
    def __init__(self, options: pyrosetta.rosetta.core.scoring.methods.EnergyMethodOptions) -> None: ...
    @overload
    def __init__(self, arg0: FA_ElecEnergy) -> None: ...
    @overload
    def __init__(self, arg0: FA_ElecEnergy) -> None: ...
    def assign(self) -> FA_ElecEnergy: ...
    @overload
    def atomic_interaction_cutoff(self) -> float: ...
    @overload
    def atomic_interaction_cutoff(self) -> double: ...
    def atomistic_pair_energy(self) -> None: ...
    def backbone_backbone_energy(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, pose, sfxn, emap) -> None: ...
    def backbone_sidechain_energy(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, pose, sfxn, emap) -> None: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    def coulomb(self) -> pyrosetta.rosetta.core.scoring.etable.coulomb.Coulomb: ...
    @overload
    def defines_intrares_energy(self) -> bool: ...
    @overload
    def defines_intrares_energy(self, constclasscore) -> bool: ...
    def defines_score_for_residue_pair(self, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, res_moving_wrt_eachother: bool) -> bool: ...
    @overload
    def divides_backbone_and_sidechain_energetics(self) -> bool: ...
    @overload
    def divides_backbone_and_sidechain_energetics(self) -> bool: ...
    def elec_weight(self, intra_res: bool, at1isbb: bool, at2isbb: bool, wts: weight_triple) -> float: ...
    def eval_atom_derivative(self, atom_id: pyrosetta.rosetta.core.id.AtomID, pose, domain_map: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, weights, F1: pyrosetta.rosetta.numeric.xyzVector_double_t, F2: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def eval_intrares_ST_only(self) -> bool: ...
    @overload
    def eval_intrares_ST_only(self) -> bool: ...
    def eval_intrares_derivatives(self, rsd: pyrosetta.rosetta.core.conformation.Residue, min_data, pose, weights, atom_derivs: pyrosetta.rosetta.utility.vector1_core_scoring_DerivVectorPair) -> None: ...
    def eval_intrares_energy(self, rsd: pyrosetta.rosetta.core.conformation.Residue, pose, sf, emap) -> None: ...
    def eval_residue_pair_derivatives(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, min_data, pose, weights, r1_atom_derivs: pyrosetta.rosetta.utility.vector1_core_scoring_DerivVectorPair, r2_atom_derivs: pyrosetta.rosetta.utility.vector1_core_scoring_DerivVectorPair) -> None: ...
    def evaluate_rotamer_background_energies(self, set: pyrosetta.rosetta.core.conformation.RotamerSetBase, residue: pyrosetta.rosetta.core.conformation.Residue, pose, sfxn, weights, energy_vector: pyrosetta.rosetta.utility.vector1_float) -> None: ...
    def evaluate_rotamer_intrares_energies(self, set: pyrosetta.rosetta.core.conformation.RotamerSetBase, pose, sfxn, energies: pyrosetta.rosetta.utility.vector1_float) -> None: ...
    def evaluate_rotamer_pair_energies(self, set1: pyrosetta.rosetta.core.conformation.RotamerSetBase, set2: pyrosetta.rosetta.core.conformation.RotamerSetBase, pose, sfxn, weights, energy_table: pyrosetta.rosetta.ObjexxFCL.FArray2D_float_t) -> None: ...
    def finalize_total_energy(self, pose, totals) -> None: ...
    def get_count_pair_function(self, *args, **kwargs): ...
    @overload
    def get_countpair_representative_atom(self, restype: pyrosetta.rosetta.core.chemical.ResidueType, atm_i: int) -> int: ...
    @overload
    def get_countpair_representative_atom(self, constclasscore, unsignedlong) -> unsignedlong: ...
    def get_intrares_countpair(self, *args, **kwargs): ...
    @overload
    def has_atomistic_pairwise_energies(self) -> bool: ...
    @overload
    def has_atomistic_pairwise_energies(self) -> bool: ...
    @overload
    def hydrogen_interaction_cutoff(self) -> float: ...
    @overload
    def hydrogen_interaction_cutoff(self) -> double: ...
    @overload
    def hydrogen_interaction_cutoff2(self) -> float: ...
    @overload
    def hydrogen_interaction_cutoff2(self) -> double: ...
    @overload
    def indicate_required_context_graphs(self, context_graphs_required: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def indicate_required_context_graphs(self, classutility) -> void: ...
    @overload
    def initialize(self) -> None: ...
    @overload
    def initialize(self) -> void: ...
    @overload
    def minimize_in_whole_structure_context(self, pose) -> bool: ...
    @overload
    def minimize_in_whole_structure_context(self, constclasscore) -> bool: ...
    @overload
    def prepare_rotamers_for_packing(self, pose, set: pyrosetta.rosetta.core.conformation.RotamerSetBase) -> None: ...
    @overload
    def prepare_rotamers_for_packing(self, constclasscore, classcore) -> void: ...
    @overload
    def requires_a_setup_for_derivatives_for_residue_opportunity(self) -> bool: ...
    @overload
    def requires_a_setup_for_derivatives_for_residue_opportunity(self, constclasscore) -> bool: ...
    @overload
    def requires_a_setup_for_scoring_for_residue_opportunity_during_minimization(self) -> bool: ...
    @overload
    def requires_a_setup_for_scoring_for_residue_opportunity_during_minimization(self, constclasscore) -> bool: ...
    def residue_pair_energy(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, pose, emap) -> None: ...
    def residue_pair_energy_ext(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, min_data, pose, sfxn, emap) -> None: ...
    @overload
    def setup_for_derivatives(self, pose) -> None: ...
    @overload
    def setup_for_derivatives(self, classcore, constclasscore) -> void: ...
    def setup_for_derivatives_for_residue(self, rsd: pyrosetta.rosetta.core.conformation.Residue, pose, sfxn, min_data) -> None: ...
    def setup_for_minimizing(self, pose, sfxn, min_map) -> None: ...
    def setup_for_minimizing_for_residue(self, rsd: pyrosetta.rosetta.core.conformation.Residue, pose, scorefxn, min_map, resdata) -> None: ...
    def setup_for_minimizing_for_residue_pair(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, pose, sfxn, minmap, res1_data_cache, res2_data_cache, data_cache) -> None: ...
    def setup_for_packing(self, pose) -> None: ...
    @overload
    def setup_for_scoring(self, pose) -> None: ...
    @overload
    def setup_for_scoring(self, classcore, constclasscore) -> void: ...
    def setup_for_scoring_for_residue(self, rsd: pyrosetta.rosetta.core.conformation.Residue, sfxn, resdata) -> None: ...
    def sidechain_sidechain_energy(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, pose, sfxn, emap) -> None: ...
    @overload
    def update_residue_for_packing(self, pose, resid: int) -> None: ...
    @overload
    def update_residue_for_packing(self, classcore, unsignedlong) -> void: ...
    @overload
    def use_extended_residue_pair_energy_interface(self) -> bool: ...
    @overload
    def use_extended_residue_pair_energy_interface(self) -> bool: ...

class FA_ElecEnergyCreator(pyrosetta.rosetta.core.scoring.methods.EnergyMethodCreator):
    def __init__(self) -> None: ...
    def assign(self) -> FA_ElecEnergyCreator: ...
    def create_energy_method(self) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    def score_types_for_method(self) -> pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType: ...

class GroupElec:
    @overload
    def __init__(self, arg0: GroupElec) -> None: ...
    @overload
    def __init__(self, options: pyrosetta.rosetta.core.scoring.methods.EnergyMethodOptions) -> None: ...
    def eval_respair_group_coulomb(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue) -> float: ...
    def eval_respair_group_derivatives(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, r1_atom_derivs: pyrosetta.rosetta.utility.vector1_core_scoring_DerivVectorPair, r2_atom_derivs: pyrosetta.rosetta.utility.vector1_core_scoring_DerivVectorPair, elec_weight: float, Erespair: float) -> None: ...
    @overload
    def initialize(self, coulomb: pyrosetta.rosetta.core.scoring.etable.coulomb.Coulomb) -> None: ...
    @overload
    def initialize(self, constclasscore) -> void: ...

class weight_triple:
    w_intra_: float
    wbb_bb_: float
    wbb_sc_: float
    wsc_bb_: float
    wsc_sc_: float
    def __init__(self) -> None: ...

def read_cp_tables_from_db(filename: str) -> pyrosetta.rosetta.std.map_std_string_std_map_std_string_std_string_t_std_allocator_std_pair_const_std_string_std_map_std_string_std_string_t: ...
