class Type_to_type_bool_t:
    def __init__(self) -> None: ...

class Type_to_type_double_t:
    def __init__(self) -> None: ...

class Type_to_type_float_t:
    def __init__(self) -> None: ...

class Type_to_type_int_t:
    def __init__(self) -> None: ...

class Type_to_type_long_long_t:
    def __init__(self) -> None: ...

class Type_to_type_unsigned_long_long_t:
    def __init__(self) -> None: ...
