import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.fragment.rna
import pyrosetta.rosetta.core.import_pose
import pyrosetta.rosetta.core.import_pose.libraries
import pyrosetta.rosetta.core.import_pose.options
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.pose.toolbox
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.options
import pyrosetta.rosetta.utility.tag
from typing import overload

class RNA_DeNovoMasterMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, options: pyrosetta.rosetta.core.import_pose.options.RNA_FragmentMonteCarloOptions, atom_level_domain_map: pyrosetta.rosetta.core.pose.toolbox.AtomLevelDomainMap, rna_base_pair_handler: pyrosetta.rosetta.core.import_pose.RNA_BasePairHandler, rna_loop_closer, rna_chunk_library: pyrosetta.rosetta.core.import_pose.libraries.RNA_ChunkLibrary, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: RNA_DeNovoMasterMover) -> None: ...
    @overload
    def __init__(self, arg0: RNA_DeNovoMasterMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose, cycle_number: int) -> None: ...
    def assign(self) -> RNA_DeNovoMasterMover: ...
    @overload
    def close_loops(self) -> bool: ...
    @overload
    def close_loops(self) -> bool: ...
    @overload
    def do_random_moves(self, pose: pyrosetta.rosetta.core.pose.Pose, monte_carlo_cycles: int) -> None: ...
    @overload
    def do_random_moves(self, pose: pyrosetta.rosetta.core.pose.Pose, monte_carlo_cycles: int, check_num_rna_res: bool) -> None: ...
    @overload
    def frag_size(self) -> int: ...
    @overload
    def frag_size(self) -> unsignedlong: ...
    def get_name(self) -> str: ...
    def move_type(self) -> str: ...
    def rna_fragment_mover(self, *args, **kwargs): ...
    def rna_helix_mover(self, *args, **kwargs): ...
    def rna_jump_mover(self) -> pyrosetta.rosetta.core.import_pose.RNA_JumpMover: ...
    @overload
    def search_rigid_body_orientation(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def search_rigid_body_orientation(self, classcore) -> void: ...
    def set_close_loops(self, setting: bool) -> None: ...
    def set_frag_size(self, setting: int) -> None: ...
    def set_helix_mover_magnitude(self, rot_mag: float, trans_mag: float) -> None: ...
    @overload
    def set_rna_helix_mover(self, rna_helix_mover) -> None: ...
    @overload
    def set_rna_helix_mover(self, constclassstd) -> void: ...
    @overload
    def set_sfxn(self, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_sfxn(self, constclassstd) -> void: ...
    def setup_dock_into_density_mover(self, pose: pyrosetta.rosetta.core.pose.Pose, rot_mag: float, trans_mag: float) -> None: ...
    def setup_rigid_body_mover(self, pose: pyrosetta.rosetta.core.pose.Pose, rot_mag: float, trans_mag: float) -> None: ...
    def setup_rna_protein_docking_mover(self, pose: pyrosetta.rosetta.core.pose.Pose, rot_mag: float, trans_mag: float) -> None: ...
    def setup_rnp_fold_tree(self, pose: pyrosetta.rosetta.core.pose.Pose, refine_pose: bool, randomize: bool) -> None: ...
    @overload
    def success(self) -> bool: ...
    @overload
    def success(self) -> bool: ...

class RNA_DeNovoProtocolMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RNA_DeNovoProtocolMover) -> None: ...
    @overload
    def __init__(self, arg0: RNA_DeNovoProtocolMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RNA_DeNovoProtocolMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def de_novo_setup_from_command_line(self) -> None: ...
    @overload
    def de_novo_setup_from_command_line(self) -> void: ...
    @overload
    def de_novo_setup_from_options(self, opts: pyrosetta.rosetta.utility.options.OptionCollection) -> None: ...
    @overload
    def de_novo_setup_from_options(self, constclassutility) -> void: ...
    @overload
    def de_novo_setup_from_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def de_novo_setup_from_tag(self, constclassstd) -> void: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    @staticmethod
    def list_options_read(opts: pyrosetta.rosetta.std.list_utility_keys_VariantKey_utility_options_OptionKey_t) -> None: ...
    @overload
    @staticmethod
    def list_options_read(classstd) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    def options(self) -> pyrosetta.rosetta.core.import_pose.options.RNA_DeNovoProtocolOptions: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def rna_params(self) -> pyrosetta.rosetta.core.import_pose.RNA_DeNovoParameters: ...
    @overload
    def set_align_pdb(self, align_pdb: str) -> None: ...
    @overload
    def set_align_pdb(self, conststd) -> void: ...
    @overload
    def set_dock_chunks(self, dock_chunks: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_dock_chunks(self, constclassutility) -> void: ...
    @overload
    def set_fasta_files(self, fasta_files: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_fasta_files(self, constclassutility) -> void: ...
    @overload
    def set_helical_substructs(self, helical_substructs: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_helical_substructs(self, constclassutility) -> void: ...
    @overload
    def set_input_initialization_pdbs(self, input_initialization_pdbs: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_input_initialization_pdbs(self, constclassutility) -> void: ...
    @overload
    def set_input_pdbs(self, input_pdbs: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_input_pdbs(self, constclassutility) -> void: ...
    @overload
    def set_input_silent_files(self, input_silent_files: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_input_silent_files(self, constclassutility) -> void: ...
    @overload
    def set_minimize_rna(self, minimize_rna: bool) -> None: ...
    @overload
    def set_minimize_rna(self, constbool) -> void: ...
    @overload
    def set_nstruct(self, nstruct: int) -> None: ...
    @overload
    def set_nstruct(self, constunsignedlong) -> void: ...
    @overload
    def set_protocol_options(self, protocol_options: pyrosetta.rosetta.core.import_pose.options.RNA_DeNovoProtocolOptions) -> None: ...
    @overload
    def set_protocol_options(self, constclassstd) -> void: ...
    @overload
    def set_residue_type_set(self, rts: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def set_residue_type_set(self, constclassstd) -> void: ...
    @overload
    def set_sequence_strings(self, sequence_strings: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_sequence_strings(self, constclassutility) -> void: ...
    @overload
    def set_silent_file(self, silent_file: str) -> None: ...
    @overload
    def set_silent_file(self, conststd) -> void: ...

class RNA_DeNovoProtocolMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RNA_DeNovoProtocolMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: RNA_DeNovoProtocolMoverCreator) -> None: ...
    def assign(self) -> RNA_DeNovoProtocolMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class RNA_FragmentMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.fragment.rna.RNA_Fragments, arg1: pyrosetta.rosetta.core.pose.toolbox.AtomLevelDomainMap, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.fragment.rna.RNA_Fragments, arg1: pyrosetta.rosetta.core.pose.toolbox.AtomLevelDomainMap, arg2: int, arg3: int) -> None: ...
    @overload
    def __init__(self, all_rna_fragments: pyrosetta.rosetta.core.fragment.rna.RNA_Fragments, atom_level_domain_map: pyrosetta.rosetta.core.pose.toolbox.AtomLevelDomainMap, symm_hack_arity: int, exhaustive: int, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: RNA_FragmentMover) -> None: ...
    @overload
    def __init__(self, arg0: RNA_FragmentMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def random_fragment_insertion(self, pose: pyrosetta.rosetta.core.pose.Pose, frag_size: int) -> int: ...
    @overload
    def random_fragment_insertion(self, pose: pyrosetta.rosetta.core.pose.Pose, frag_size: int, heating: bool) -> int: ...
    @overload
    def random_fragment_insertion(self, classcore, constunsignedlong, constbool) -> unsignedlong: ...
    @overload
    def set_frag_size(self, fragment_size: int) -> None: ...
    @overload
    def set_frag_size(self, constunsignedlong) -> void: ...

class RNA_HelixMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, helix_regions: pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t, rna_base_pair_handler: pyrosetta.rosetta.core.import_pose.RNA_BasePairHandler, move_first_rigid_body: bool) -> None: ...
    @overload
    def __init__(self, arg0: RNA_HelixMover) -> None: ...
    @overload
    def __init__(self, arg0: RNA_HelixMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RNA_HelixMover: ...
    @overload
    def get_helix_ends(self) -> None: ...
    @overload
    def get_helix_ends(self) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def set_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_pose(self, constclasscore) -> void: ...
    def set_rot_magnitude(self, rot_mag: float) -> None: ...
    def set_trans_magnitude(self, trans_mag: float) -> None: ...

class RNA_Minimizer(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, options: pyrosetta.rosetta.core.import_pose.options.RNA_MinimizerOptions) -> None: ...
    @overload
    def __init__(self, arg0: RNA_Minimizer) -> None: ...
    @overload
    def __init__(self, arg0: RNA_Minimizer) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def clone_scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    def get_name(self) -> str: ...
    def score_function(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def set_atom_level_domain_map(self, atom_level_domain_map: pyrosetta.rosetta.core.pose.toolbox.AtomLevelDomainMap) -> None: ...
    @overload
    def set_atom_level_domain_map(self, classstd) -> void: ...
    @overload
    def set_include_default_linear_chainbreak(self, setting: bool) -> None: ...
    @overload
    def set_include_default_linear_chainbreak(self, constbool) -> void: ...
    def set_min_tol(self, setting: float) -> None: ...
    @overload
    def set_options(self, setting: pyrosetta.rosetta.core.import_pose.options.RNA_MinimizerOptions) -> None: ...
    @overload
    def set_options(self, classstd) -> void: ...
    @overload
    def set_perform_minimizer_run(self, setting: bool) -> None: ...
    @overload
    def set_perform_minimizer_run(self, constbool) -> void: ...
    @overload
    def set_score_function(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_score_function(self, classstd) -> void: ...
    def set_skip_chi_min(self, setting: bool) -> None: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def skip_chi_min(self) -> bool: ...
    @overload
    def skip_chi_min(self) -> bool: ...

class RNA_Relaxer(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, rna_fragment_mover: RNA_FragmentMover, rna_minimizer: RNA_Minimizer) -> None: ...
    @overload
    def __init__(self, arg0: RNA_Relaxer) -> None: ...
    @overload
    def __init__(self, arg0: RNA_Relaxer) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def simple_rmsd_cutoff_relax(self, setting: bool) -> None: ...
    @overload
    def simple_rmsd_cutoff_relax(self, constbool) -> void: ...

class RNP_HighResMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, rna_fragment_mover: RNA_FragmentMover, rna_loop_closer, options: pyrosetta.rosetta.core.import_pose.options.RNA_FragmentMonteCarloOptions) -> None: ...
    @overload
    def __init__(self, arg0: RNP_HighResMover) -> None: ...
    @overload
    def __init__(self, arg0: RNP_HighResMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def initialize(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def initialize(self, constclasscore) -> void: ...
