import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.scoring.annealing
import pyrosetta.rosetta.core.scoring.methods
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from . import graph as graph
from typing import Any, overload

class BuriedUnsatPenalty(pyrosetta.rosetta.core.scoring.methods.WholeStructureEnergy, pyrosetta.rosetta.core.scoring.annealing.ResidueArrayAnnealableEnergy):
    @overload
    def __init__(self, options: pyrosetta.rosetta.core.scoring.methods.EnergyMethodOptions) -> None: ...
    @overload
    def __init__(self, arg0: BuriedUnsatPenalty) -> None: ...
    @overload
    def __init__(self, arg0: BuriedUnsatPenalty) -> None: ...
    def assign(self) -> BuriedUnsatPenalty: ...
    @overload
    def calculate_energy(self, resvect: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t, rotamer_ids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> float: ...
    @overload
    def calculate_energy(self, resvect: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t, rotamer_ids: pyrosetta.rosetta.utility.vector1_unsigned_long, substitution_position: int) -> float: ...
    @overload
    def calculate_penalty_once_almost_from_scratch_using_reference_graph(self, resvect: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t, reference_graph, symm_multiplier: int) -> float: ...
    @overload
    def calculate_penalty_once_almost_from_scratch_using_reference_graph(self, constclassutility, constclasscore, constunsignedlong) -> double: ...
    @overload
    def calculate_penalty_once_from_scratch(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate_penalty_once_from_scratch(self, constclasscore) -> double: ...
    @overload
    def clean_up_residuearrayannealableenergy_after_packing(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def clean_up_residuearrayannealableenergy_after_packing(self, classcore) -> void: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    @overload
    def commit_considered_substitution(self) -> None: ...
    @overload
    def commit_considered_substitution(self) -> void: ...
    def compute_penalty(self, unsat_acceptor_count: int, unsat_donor_count: int, unsat_acceptor_and_donor_count: int, oversat_acceptor_count: int, oversat_donor_count: int, oversat_acceptor_and_donor_count: int) -> float: ...
    @overload
    def finalize_after_minimizing(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def finalize_after_minimizing(self, classcore) -> void: ...
    def finalize_total_energy(self, pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, totals: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def indicate_required_context_graphs(self, context_graphs_required: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def indicate_required_context_graphs(self, classutility) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    def provide_pymol_commands_to_show_groups(self, out: pyrosetta.rosetta.std.ostream, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def provide_pymol_commands_to_show_groups(self) -> Any: ...
    @overload
    def provide_pymol_commands_to_show_groups(self, std, constclasscore) -> void: ...
    @overload
    def report(self) -> None: ...
    @overload
    def report(self) -> void: ...
    @overload
    def set_prevent_pruning(self, setting: bool) -> None: ...
    @overload
    def set_prevent_pruning(self, constbool) -> void: ...
    def set_up_residuearrayannealableenergy_for_packing(self, pose: pyrosetta.rosetta.core.pose.Pose, rotamersets, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    def setup_for_minimizing(self, pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, minmap: pyrosetta.rosetta.core.kinematics.MinimizerMapBase) -> None: ...
    @overload
    def version(self) -> int: ...
    @overload
    def version(self) -> unsignedlong: ...

class BuriedUnsatPenaltyCreator(pyrosetta.rosetta.core.scoring.methods.EnergyMethodCreator):
    def __init__(self) -> None: ...
    def assign(self) -> BuriedUnsatPenaltyCreator: ...
    def create_energy_method(self, options: pyrosetta.rosetta.core.scoring.methods.EnergyMethodOptions) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    def score_types_for_method(self) -> pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType: ...
