import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.protocols.stepwise.sampler
import pyrosetta.rosetta.protocols.toolbox
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import overload

class CopyDofStepWiseSampler(pyrosetta.rosetta.protocols.stepwise.sampler.StepWiseSamplerSized):
    @overload
    def __init__(self, pose_list: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, res_map: pyrosetta.rosetta.std.map_unsigned_long_unsigned_long, starting_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, pose_list: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, res_map: pyrosetta.rosetta.std.map_unsigned_long_unsigned_long) -> None: ...
    @overload
    def __init__(self, arg0: CopyDofStepWiseSampler) -> None: ...
    @overload
    def __init__(self, arg0: CopyDofStepWiseSampler) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore, constunsignedlong) -> void: ...
    def assign(self) -> CopyDofStepWiseSampler: ...
    def get_name(self) -> str: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def type(self) -> pyrosetta.rosetta.protocols.toolbox.SamplerPlusPlusType: ...

class ResidueAlternativeSet:
    @overload
    def __init__(self, pose_list: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, res_map: pyrosetta.rosetta.std.map_unsigned_long_unsigned_long, representative_seqpos: int) -> None: ...
    @overload
    def __init__(self, pose_list: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, representative_seqpos: int) -> None: ...
    @overload
    def __init__(self, arg0: ResidueAlternativeSet) -> None: ...
    def assign(self) -> ResidueAlternativeSet: ...
    def pose(self, n: int) -> pyrosetta.rosetta.core.pose.Pose: ...
    def pose_list(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t: ...
    @overload
    def representative_seqpos(self) -> int: ...
    @overload
    def representative_seqpos(self) -> unsignedlong: ...
    def res_map(self) -> pyrosetta.rosetta.std.map_unsigned_long_unsigned_long: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...

class ResidueAlternativeStepWiseSampler(CopyDofStepWiseSampler):
    @overload
    def __init__(self, residue_alternative_set: ResidueAlternativeSet, starting_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, residue_alternative_set: ResidueAlternativeSet) -> None: ...
    @overload
    def __init__(self, pose_list: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, res_map: pyrosetta.rosetta.std.map_unsigned_long_unsigned_long, representative_seqpos: int, starting_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, pose_list: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, res_map: pyrosetta.rosetta.std.map_unsigned_long_unsigned_long, representative_seqpos: int) -> None: ...
    @overload
    def __init__(self, pose_list: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, seqpos: int) -> None: ...
    @overload
    def __init__(self, arg0: ResidueAlternativeStepWiseSampler) -> None: ...
    @overload
    def __init__(self, arg0: ResidueAlternativeStepWiseSampler) -> None: ...
    def get_name(self) -> str: ...
    def get_residue_at_origin(self) -> pyrosetta.rosetta.core.conformation.Residue: ...
    def get_residue_at_origin_with_matching_type(self, rsd_in: pyrosetta.rosetta.core.conformation.Residue) -> pyrosetta.rosetta.core.conformation.Residue: ...
    @overload
    def representative_seqpos(self) -> int: ...
    @overload
    def representative_seqpos(self) -> unsignedlong: ...
    def type(self) -> pyrosetta.rosetta.protocols.toolbox.SamplerPlusPlusType: ...

class ResidueAlternativeStepWiseSamplerComb(pyrosetta.rosetta.protocols.stepwise.sampler.StepWiseSamplerSizedComb):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ResidueAlternativeStepWiseSamplerComb) -> None: ...
    @overload
    def __init__(self, arg0: ResidueAlternativeStepWiseSamplerComb) -> None: ...
    @overload
    def add_residue_alternative_rotamer(self, rotamer: ResidueAlternativeStepWiseSampler) -> None: ...
    @overload
    def add_residue_alternative_rotamer(self, constclassstd) -> void: ...
    def assign(self) -> ResidueAlternativeStepWiseSamplerComb: ...
    @overload
    def fast_forward_to_next_residue(self, i: int) -> None: ...
    @overload
    def fast_forward_to_next_residue(self, constunsignedlong) -> void: ...
    def fast_forward_to_next_residue_pair(self, i: int, j: int) -> None: ...
    @overload
    def find_resnum(self, seqpos: int) -> int: ...
    @overload
    def find_resnum(self, constunsignedlong) -> unsignedlong: ...
    def get_name(self) -> str: ...
    def get_residue_at_origin(self, seqpos: int) -> pyrosetta.rosetta.core.conformation.Residue: ...
    def get_residue_at_origin_with_matching_type(self, seqpos: int, rsd_in: pyrosetta.rosetta.core.conformation.Residue) -> pyrosetta.rosetta.core.conformation.Residue: ...
    @overload
    def has_resnum(self, seqpos: int) -> bool: ...
    @overload
    def has_resnum(self, constunsignedlong) -> bool: ...
    @overload
    def id_for_resnum(self, seqpos: int) -> int: ...
    @overload
    def id_for_resnum(self, constunsignedlong) -> unsignedlong: ...
    def type(self) -> pyrosetta.rosetta.protocols.toolbox.SamplerPlusPlusType: ...

class ResidueListStepWiseSampler(pyrosetta.rosetta.protocols.stepwise.sampler.StepWiseSamplerSized):
    @overload
    def __init__(self, copy_dofs: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_conformation_Residue_t) -> None: ...
    @overload
    def __init__(self, arg0: ResidueListStepWiseSampler) -> None: ...
    @overload
    def __init__(self, arg0: ResidueListStepWiseSampler) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore, constunsignedlong) -> void: ...
    def assign(self) -> ResidueListStepWiseSampler: ...
    def get_name(self) -> str: ...
    def get_residue_at_origin(self) -> pyrosetta.rosetta.core.conformation.Residue: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def type(self) -> pyrosetta.rosetta.protocols.toolbox.SamplerPlusPlusType: ...
