import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.protocols.moves
from typing import overload

class PolarHydrogenPacker(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PolarHydrogenPacker) -> None: ...
    @overload
    def __init__(self, arg0: PolarHydrogenPacker) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> PolarHydrogenPacker: ...
    def get_name(self) -> str: ...
    @overload
    def set_allow_virtual_o2prime_hydrogens(self, setting: bool) -> None: ...
    @overload
    def set_allow_virtual_o2prime_hydrogens(self, constbool) -> void: ...

@overload
def check_if_proton_chi_atom(pose: pyrosetta.rosetta.core.pose.Pose, rsd: int, atomno: int) -> int: ...
@overload
def check_if_proton_chi_atom(rt: pyrosetta.rosetta.core.chemical.ResidueType, atomno: int) -> int: ...
@overload
def check_if_proton_chi_atom(constclasscore, constunsignedlong) -> unsignedlong: ...
@overload
def pack_polar_hydrogens(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def pack_polar_hydrogens(pose: pyrosetta.rosetta.core.pose.Pose, allow_virtual_o2prime_hydrogens_: bool) -> None: ...
@overload
def pack_polar_hydrogens(classcore, bool) -> void: ...
