# fix_pybind_stubs: rdkit 2026.3.5 5beea910
from _typeshed import Incomplete

rdkitStructureRendererJsUrl: str
minimalLibJsUrl: str
parentNodeQuery: str
def filterDefaultDrawOpts(molDrawOptions): ...
def setEnabled(shouldEnable: bool = ..., quiet: bool = ...): ...
def isEnabled(mol: Incomplete | None = ...): ...
def getOpts(mol): ...
def setOpts(mol, opts): ...
def setOpt(mol, key, value): ...
def clearOpts(mol): ...
def clearOpt(mol, key): ...
def setNoInteractive(mol, shouldSet: bool = ...): ...
def isNoInteractive(mol): ...
def injectHTMLFooterAfterTable(html): ...
def generateHTMLFooter(doc, element): ...
def newlineToXml(molblock): ...
def xmlToNewline(xmlblock): ...
def toDataMol(mol): ...
def camelCaseOptToDataTag(opt): ...
def generateHTMLBody(mol, size, **kwargs): ...
def MolsToHTMLTable(mols, molsPerRow: int = ..., subImgSize: tuple = ..., legends: Incomplete | None = ..., highlightAtomLists: Incomplete | None = ..., highlightBondLists: Incomplete | None = ..., useSVG: bool = ..., drawOptions: Incomplete | None = ..., **kwargs): ...

# present at runtime, absent from the generated stub:
from rdkit import Chem as Chem
from rdkit.Chem import Draw as Draw
from IPython.core.display import HTML as HTML
import base64 as base64
from IPython.core.display_functions import display as display
import json as json
import logging as logging
from xml.dom import minidom as minidom
from rdkit.Chem.Draw import rdMolDraw2D as rdMolDraw2D
import re as re
import uuid as uuid
