import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.excn
import pyrosetta.rosetta.utility.json_spirit
import typing
from typing import Any, ClassVar, overload

BB: TorsionType
BRANCH: TorsionType
CHI: TorsionType
D: DOF_Type
INVALID_DOF: DOF_Type
JUMP: TorsionType
NU: TorsionType
PHI: DOF_Type
RB1: DOF_Type
RB2: DOF_Type
RB3: DOF_Type
RB4: DOF_Type
RB5: DOF_Type
RB6: DOF_Type
THETA: DOF_Type
omega2_dihedral: MainchainTorsionType
omega3_dihedral: MainchainTorsionType
omega_dihedral: MainchainTorsionType
phi_dihedral: MainchainTorsionType
psi_dihedral: MainchainTorsionType

class AtomID:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AtomID) -> None: ...
    @overload
    def __init__(self, atomno_in: int, rsd_in: int) -> None: ...
    @staticmethod
    def BOGUS_ATOM_ID() -> AtomID: ...
    @staticmethod
    def CHAINBREAK_BOGUS_ATOM_ID() -> AtomID: ...
    def assign(self) -> AtomID: ...
    def atomno(self) -> int: ...
    @overload
    def deserialize(self, data: pyrosetta.rosetta.std.map_std_string_utility_json_spirit_Value_impl_utility_json_spirit_Config_map_std_string_t_std_allocator_std_pair_const_std_string_utility_json_spirit_Value_impl_utility_json_spirit_Config_map_std_string_t) -> None: ...
    @overload
    def deserialize(self, classstd, classutility) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def rsd(self) -> int: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def serialize(self) -> pyrosetta.rosetta.utility.json_spirit.Value_impl_utility_json_spirit_Config_vector_std_string_t: ...
    def set(self, atomno_in: int, rsd_in: int) -> None: ...
    @overload
    def valid(self) -> bool: ...
    @overload
    def valid(self) -> bool: ...

class AtomID_Map_AtomID(AtomID_Map_core_id_AtomID_t):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_AtomID) -> None: ...
    def assign(self) -> AtomID_Map_AtomID: ...

class AtomID_Map_Real(AtomID_Map_double_t):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_Real) -> None: ...
    def assign(self) -> AtomID_Map_Real: ...

class AtomID_Map_bool(AtomID_Map_bool_t):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_bool) -> None: ...
    def assign(self) -> AtomID_Map_bool: ...

class AtomID_Map_bool_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a: bool) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a: bool) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_bool_t) -> None: ...
    @overload
    def all_default(self) -> bool: ...
    @overload
    def all_default(self) -> bool: ...
    def assign(self) -> AtomID_Map_bool_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear(self, default_value_a: bool) -> None: ...
    @overload
    def default_value(self) -> bool: ...
    @overload
    def default_value(self, default_value_a: bool) -> None: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fill(self) -> None: ...
    @overload
    def fill(self) -> void: ...
    @overload
    def fill_with(self, value: bool) -> None: ...
    @overload
    def fill_with(self, seqpos: int, value: bool) -> None: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    @overload
    def get(self, id) -> bool: ...
    @overload
    def get(self, constclasscore) -> bool: ...
    @overload
    def has(self, id) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value: bool) -> None: ...
    def set(self, id, value: bool) -> None: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: AtomID_Map_bool_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    @overload
    def update_sequence_numbering(self, new_size: int, old2new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def update_sequence_numbering(self, constunsignedlong, constclassutility) -> void: ...
    def __call__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def __getitem__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.utility.vector1_bool]: ...

class AtomID_Map_core_id_AtomID_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_core_id_AtomID_t) -> None: ...
    @overload
    def all_default(self) -> bool: ...
    @overload
    def all_default(self) -> bool: ...
    def assign(self) -> AtomID_Map_core_id_AtomID_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear(self, default_value_a) -> None: ...
    @overload
    def clear(self, constclasscore) -> void: ...
    @overload
    def default_value(self, default_value_a) -> None: ...
    @overload
    def default_value(self, constclasscore) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fill(self) -> None: ...
    @overload
    def fill(self) -> void: ...
    @overload
    def fill_with(self, value) -> None: ...
    @overload
    def fill_with(self, constclasscore) -> void: ...
    @overload
    def fill_with(self, seqpos: int, value) -> None: ...
    @overload
    def fill_with(self, constunsignedlong, constclasscore) -> void: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    def get(self, *args, **kwargs): ...
    @overload
    def has(self, id) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value) -> None: ...
    def set(self, id, value) -> None: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: AtomID_Map_core_id_AtomID_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    @overload
    def update_sequence_numbering(self, new_size: int, old2new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def update_sequence_numbering(self, constunsignedlong, constclassutility) -> void: ...
    def __call__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_core_id_AtomID: ...
    def __getitem__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_core_id_AtomID: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.utility.vector1_core_id_AtomID]: ...

class AtomID_Map_core_id_TorsionID_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_core_id_TorsionID_t) -> None: ...
    @overload
    def all_default(self) -> bool: ...
    @overload
    def all_default(self) -> bool: ...
    def assign(self) -> AtomID_Map_core_id_TorsionID_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear(self, default_value_a) -> None: ...
    @overload
    def clear(self, constclasscore) -> void: ...
    @overload
    def default_value(self, default_value_a) -> None: ...
    @overload
    def default_value(self, constclasscore) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fill(self) -> None: ...
    @overload
    def fill(self) -> void: ...
    @overload
    def fill_with(self, value) -> None: ...
    @overload
    def fill_with(self, constclasscore) -> void: ...
    @overload
    def fill_with(self, seqpos: int, value) -> None: ...
    @overload
    def fill_with(self, constunsignedlong, constclasscore) -> void: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    def get(self, *args, **kwargs): ...
    @overload
    def has(self, id) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value) -> None: ...
    def set(self, id, value) -> None: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: AtomID_Map_core_id_TorsionID_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    @overload
    def update_sequence_numbering(self, new_size: int, old2new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def update_sequence_numbering(self, constunsignedlong, constclassutility) -> void: ...
    def __call__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_core_id_TorsionID: ...
    def __getitem__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_core_id_TorsionID: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.utility.vector1_core_id_TorsionID]: ...

class AtomID_Map_core_scoring_packstat_LR_AtomData_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_core_scoring_packstat_LR_AtomData_t) -> None: ...
    def assign(self) -> AtomID_Map_core_scoring_packstat_LR_AtomData_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear(self, default_value_a) -> None: ...
    @overload
    def clear(self, conststructcore) -> void: ...
    @overload
    def default_value(self, default_value_a) -> None: ...
    @overload
    def default_value(self, conststructcore) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fill(self) -> None: ...
    @overload
    def fill(self) -> void: ...
    @overload
    def fill_with(self, value) -> None: ...
    @overload
    def fill_with(self, conststructcore) -> void: ...
    @overload
    def fill_with(self, seqpos: int, value) -> None: ...
    @overload
    def fill_with(self, constunsignedlong, conststructcore) -> void: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    def get(self, *args, **kwargs): ...
    @overload
    def has(self, id) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value) -> None: ...
    @overload
    def set(self, id, value) -> None: ...
    @overload
    def set(self, constclasscore, conststructcore) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: AtomID_Map_core_scoring_packstat_LR_AtomData_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    @overload
    def update_sequence_numbering(self, new_size: int, old2new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def update_sequence_numbering(self, constunsignedlong, constclassutility) -> void: ...
    def __call__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_core_scoring_packstat_LR_AtomData: ...
    def __getitem__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_core_scoring_packstat_LR_AtomData: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.utility.vector1_core_scoring_packstat_LR_AtomData]: ...

class AtomID_Map_core_scoring_packstat_LR_MP_AtomData_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_core_scoring_packstat_LR_MP_AtomData_t) -> None: ...
    def assign(self) -> AtomID_Map_core_scoring_packstat_LR_MP_AtomData_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear(self, default_value_a) -> None: ...
    @overload
    def clear(self, conststructcore) -> void: ...
    @overload
    def default_value(self, default_value_a) -> None: ...
    @overload
    def default_value(self, conststructcore) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fill(self) -> None: ...
    @overload
    def fill(self) -> void: ...
    @overload
    def fill_with(self, value) -> None: ...
    @overload
    def fill_with(self, conststructcore) -> void: ...
    @overload
    def fill_with(self, seqpos: int, value) -> None: ...
    @overload
    def fill_with(self, constunsignedlong, conststructcore) -> void: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    def get(self, *args, **kwargs): ...
    @overload
    def has(self, id) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value) -> None: ...
    @overload
    def set(self, id, value) -> None: ...
    @overload
    def set(self, constclasscore, conststructcore) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: AtomID_Map_core_scoring_packstat_LR_MP_AtomData_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    @overload
    def update_sequence_numbering(self, new_size: int, old2new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def update_sequence_numbering(self, constunsignedlong, constclassutility) -> void: ...
    def __call__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_core_scoring_packstat_LR_MP_AtomData: ...
    def __getitem__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_core_scoring_packstat_LR_MP_AtomData: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.utility.vector1_core_scoring_packstat_LR_MP_AtomData]: ...

class AtomID_Map_double_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a: float) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a: float) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_double_t) -> None: ...
    @overload
    def all_default(self) -> bool: ...
    @overload
    def all_default(self) -> bool: ...
    def assign(self) -> AtomID_Map_double_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear(self, default_value_a: float) -> None: ...
    @overload
    def default_value(self) -> float: ...
    @overload
    def default_value(self, default_value_a: float) -> None: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fill(self) -> None: ...
    @overload
    def fill(self) -> void: ...
    @overload
    def fill_with(self, value: float) -> None: ...
    @overload
    def fill_with(self, seqpos: int, value: float) -> None: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    @overload
    def get(self, id) -> float: ...
    @overload
    def get(self, constclasscore) -> double: ...
    @overload
    def has(self, id) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value: float) -> None: ...
    def set(self, id, value: float) -> None: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: AtomID_Map_double_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    @overload
    def update_sequence_numbering(self, new_size: int, old2new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def update_sequence_numbering(self, constunsignedlong, constclassutility) -> void: ...
    @overload
    def __call__(self, id) -> float: ...
    @overload
    def __call__(self, i_res: int, i_atom: int) -> float: ...
    @overload
    def __call__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def __getitem__(self, id) -> float: ...
    @overload
    def __getitem__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_double: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.utility.vector1_double]: ...

class AtomID_Map_numeric_xyzVector_double_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_numeric_xyzVector_double_t) -> None: ...
    @overload
    def all_default(self) -> bool: ...
    @overload
    def all_default(self) -> bool: ...
    def assign(self) -> AtomID_Map_numeric_xyzVector_double_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear(self, default_value_a: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def clear(self, constclassnumeric) -> void: ...
    @overload
    def default_value(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def default_value(self, default_value_a: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def default_value(self, constclassnumeric) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fill(self) -> None: ...
    @overload
    def fill(self) -> void: ...
    @overload
    def fill_with(self, value: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def fill_with(self, constclassnumeric) -> void: ...
    @overload
    def fill_with(self, seqpos: int, value: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def fill_with(self, constunsignedlong, constclassnumeric) -> void: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    def get(self, id) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def has(self, id) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set(self, id, value: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set(self, constclasscore, constclassnumeric) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: AtomID_Map_numeric_xyzVector_double_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    @overload
    def update_sequence_numbering(self, new_size: int, old2new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def update_sequence_numbering(self, constunsignedlong, constclassutility) -> void: ...
    @overload
    def __call__(self, id) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def __call__(self, i_res: int, i_atom: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def __call__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t: ...
    @overload
    def __getitem__(self, id) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def __getitem__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t]: ...

class AtomID_Map_std_shared_ptr_core_kinematics_tree_Atom_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_std_shared_ptr_core_kinematics_tree_Atom_t) -> None: ...
    @overload
    def all_default(self) -> bool: ...
    @overload
    def all_default(self) -> bool: ...
    def assign(self) -> AtomID_Map_std_shared_ptr_core_kinematics_tree_Atom_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear(self, default_value_a) -> None: ...
    @overload
    def clear(self, constclassstd) -> void: ...
    @overload
    def default_value(self, default_value_a) -> None: ...
    @overload
    def default_value(self, constclassstd) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fill(self) -> None: ...
    @overload
    def fill(self) -> void: ...
    @overload
    def fill_with(self, value) -> None: ...
    @overload
    def fill_with(self, constclassstd) -> void: ...
    @overload
    def fill_with(self, seqpos: int, value) -> None: ...
    @overload
    def fill_with(self, constunsignedlong, constclassstd) -> void: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    def get(self, *args, **kwargs): ...
    @overload
    def has(self, id) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value) -> None: ...
    @overload
    def set(self, id, value) -> None: ...
    @overload
    def set(self, constclasscore, constclassstd) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: AtomID_Map_std_shared_ptr_core_kinematics_tree_Atom_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    @overload
    def update_sequence_numbering(self, new_size: int, old2new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def update_sequence_numbering(self, constunsignedlong, constclassutility) -> void: ...
    def __call__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_kinematics_tree_Atom_t: ...
    def __getitem__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_kinematics_tree_Atom_t: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_kinematics_tree_Atom_t]: ...

class AtomID_Map_std_shared_ptr_core_optimization_DOF_Node_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_std_shared_ptr_core_optimization_DOF_Node_t) -> None: ...
    @overload
    def all_default(self) -> bool: ...
    @overload
    def all_default(self) -> bool: ...
    def assign(self) -> AtomID_Map_std_shared_ptr_core_optimization_DOF_Node_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear(self, default_value_a) -> None: ...
    @overload
    def clear(self, constclassstd) -> void: ...
    @overload
    def default_value(self, default_value_a) -> None: ...
    @overload
    def default_value(self, constclassstd) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fill(self) -> None: ...
    @overload
    def fill(self) -> void: ...
    @overload
    def fill_with(self, value) -> None: ...
    @overload
    def fill_with(self, constclassstd) -> void: ...
    @overload
    def fill_with(self, seqpos: int, value) -> None: ...
    @overload
    def fill_with(self, constunsignedlong, constclassstd) -> void: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    def get(self, *args, **kwargs): ...
    @overload
    def has(self, id) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value) -> None: ...
    @overload
    def set(self, id, value) -> None: ...
    @overload
    def set(self, constclasscore, constclassstd) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: AtomID_Map_std_shared_ptr_core_optimization_DOF_Node_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    @overload
    def update_sequence_numbering(self, new_size: int, old2new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def update_sequence_numbering(self, constunsignedlong, constclassutility) -> void: ...
    def __call__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_optimization_DOF_Node_t: ...
    def __getitem__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_optimization_DOF_Node_t: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_optimization_DOF_Node_t]: ...

class AtomID_Map_utility_vector1_double_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_utility_vector1_double_t) -> None: ...
    @overload
    def all_default(self) -> bool: ...
    @overload
    def all_default(self) -> bool: ...
    def assign(self) -> AtomID_Map_utility_vector1_double_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear(self, default_value_a: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def clear(self, constclassutility) -> void: ...
    @overload
    def default_value(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def default_value(self, default_value_a: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def default_value(self, constclassutility) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fill(self) -> None: ...
    @overload
    def fill(self) -> void: ...
    @overload
    def fill_with(self, value: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def fill_with(self, constclassutility) -> void: ...
    @overload
    def fill_with(self, seqpos: int, value: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def fill_with(self, constunsignedlong, constclassutility) -> void: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    def get(self, id) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def has(self, id) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set(self, id, value: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set(self, constclasscore, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: AtomID_Map_utility_vector1_double_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    @overload
    def update_sequence_numbering(self, new_size: int, old2new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def update_sequence_numbering(self, constunsignedlong, constclassutility) -> void: ...
    @overload
    def __call__(self, id) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def __call__(self, i_res: int, i_atom: int) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def __call__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    @overload
    def __getitem__(self, id) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def __getitem__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.utility.vector1_utility_vector1_double_t]: ...

class AtomID_Map_utility_vector1_unsigned_long_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_utility_vector1_unsigned_long_t) -> None: ...
    @overload
    def all_default(self) -> bool: ...
    @overload
    def all_default(self) -> bool: ...
    def assign(self) -> AtomID_Map_utility_vector1_unsigned_long_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear(self, default_value_a: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def clear(self, constclassutility) -> void: ...
    @overload
    def default_value(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def default_value(self, default_value_a: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def default_value(self, constclassutility) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fill(self) -> None: ...
    @overload
    def fill(self) -> void: ...
    @overload
    def fill_with(self, value: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def fill_with(self, constclassutility) -> void: ...
    @overload
    def fill_with(self, seqpos: int, value: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def fill_with(self, constunsignedlong, constclassutility) -> void: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    def get(self, id) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def has(self, id) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set(self, id, value: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set(self, constclasscore, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: AtomID_Map_utility_vector1_unsigned_long_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    @overload
    def update_sequence_numbering(self, new_size: int, old2new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def update_sequence_numbering(self, constunsignedlong, constclassutility) -> void: ...
    @overload
    def __call__(self, id) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def __call__(self, i_res: int, i_atom: int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def __call__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t: ...
    @overload
    def __getitem__(self, id) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def __getitem__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t]: ...

class AtomID_Map_utility_vector1_utility_vector1_double_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def __init__(self, arg0: AtomID_Map_utility_vector1_utility_vector1_double_t) -> None: ...
    @overload
    def all_default(self) -> bool: ...
    @overload
    def all_default(self) -> bool: ...
    def assign(self) -> AtomID_Map_utility_vector1_utility_vector1_double_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear(self, default_value_a: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def clear(self, constclassutility) -> void: ...
    @overload
    def default_value(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    @overload
    def default_value(self, default_value_a: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def default_value(self, constclassutility) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fill(self) -> None: ...
    @overload
    def fill(self) -> void: ...
    @overload
    def fill_with(self, value: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def fill_with(self, constclassutility) -> void: ...
    @overload
    def fill_with(self, seqpos: int, value: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def fill_with(self, constunsignedlong, constclassutility) -> void: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    def get(self, id) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    @overload
    def has(self, id) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def set(self, id, value: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def set(self, constclasscore, constclassutility) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: AtomID_Map_utility_vector1_utility_vector1_double_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    @overload
    def update_sequence_numbering(self, new_size: int, old2new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def update_sequence_numbering(self, constunsignedlong, constclassutility) -> void: ...
    @overload
    def __call__(self, id) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    @overload
    def __call__(self, i_res: int, i_atom: int) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    @overload
    def __call__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_utility_vector1_utility_vector1_double_t: ...
    @overload
    def __getitem__(self, id) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    @overload
    def __getitem__(self, i_res: int) -> pyrosetta.rosetta.utility.vector1_utility_vector1_utility_vector1_double_t: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.utility.vector1_utility_vector1_utility_vector1_double_t]: ...

class BondID:
    atom1: AtomID
    atom2: AtomID
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, a1: AtomID, a2: AtomID) -> None: ...
    @overload
    def __init__(self, arg0: BondID) -> None: ...
    def assign(self) -> BondID: ...
    @overload
    def has(self, id: AtomID) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def other_atom(self, id: AtomID) -> AtomID: ...
    @overload
    def reverse(self) -> None: ...
    @overload
    def reverse(self) -> void: ...
    def reversed(self) -> BondID: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class CacheableAtomID_MapVector(pyrosetta.rosetta.basic.datacache.CacheableData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CacheableAtomID_MapVector) -> None: ...
    @overload
    def __init__(self, arg0: CacheableAtomID_MapVector) -> None: ...
    def assign(self) -> CacheableAtomID_MapVector: ...
    def clone(self) -> pyrosetta.rosetta.basic.datacache.CacheableData: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def map(self) -> AtomID_Map_numeric_xyzVector_double_t: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class DOF_ID:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, atom_id_in: AtomID, type_in: DOF_Type) -> None: ...
    @overload
    def __init__(self, arg0: DOF_ID) -> None: ...
    @staticmethod
    def BOGUS_DOF_ID() -> DOF_ID: ...
    def assign(self) -> DOF_ID: ...
    def atom_id(self) -> AtomID: ...
    @overload
    def atomno(self) -> int: ...
    @overload
    def atomno(self) -> unsignedlong: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def rsd(self) -> int: ...
    @overload
    def rsd(self) -> unsignedlong: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def type(self) -> DOF_Type: ...
    @overload
    def valid(self) -> bool: ...
    @overload
    def valid(self) -> bool: ...

class DOF_ID_Map_bool_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a: bool) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a: bool) -> None: ...
    @overload
    def __init__(self, arg0: DOF_ID_Map_bool_t) -> None: ...
    def assign(self) -> DOF_ID_Map_bool_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def default_value(self, dof: DOF_Type) -> bool: ...
    @overload
    def default_value(self, dof: DOF_Type, default_value_a: bool) -> None: ...
    @overload
    def default_value(self, default_value_a: bool) -> None: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value: bool) -> None: ...
    @overload
    def set(self, dof: DOF_Type) -> None: ...
    @overload
    def set(self, constenumcore) -> void: ...
    @overload
    def set(self, dof: DOF_Type, value: bool) -> None: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: DOF_ID_Map_bool_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    def __call__(self, dof: DOF_Type) -> AtomID_Map_bool_t: ...
    def __getitem__(self, dof: DOF_Type) -> AtomID_Map_bool_t: ...

class DOF_ID_Map_core_id_TorsionID_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a) -> None: ...
    @overload
    def __init__(self, arg0: DOF_ID_Map_core_id_TorsionID_t) -> None: ...
    def assign(self) -> DOF_ID_Map_core_id_TorsionID_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def default_value(self, dof: DOF_Type, default_value_a) -> None: ...
    @overload
    def default_value(self, constenumcore, constclasscore) -> void: ...
    @overload
    def default_value(self, default_value_a) -> None: ...
    @overload
    def default_value(self, constclasscore) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value) -> None: ...
    @overload
    def set(self, dof: DOF_Type) -> None: ...
    @overload
    def set(self, constenumcore) -> void: ...
    @overload
    def set(self, dof: DOF_Type, value) -> None: ...
    @overload
    def set(self, constenumcore, constclasscore) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: DOF_ID_Map_core_id_TorsionID_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    def __call__(self, dof: DOF_Type) -> AtomID_Map_core_id_TorsionID_t: ...
    def __getitem__(self, dof: DOF_Type) -> AtomID_Map_core_id_TorsionID_t: ...

class DOF_ID_Map_std_shared_ptr_core_optimization_DOF_Node_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a) -> None: ...
    @overload
    def __init__(self, arg0: DOF_ID_Map_std_shared_ptr_core_optimization_DOF_Node_t) -> None: ...
    def assign(self) -> DOF_ID_Map_std_shared_ptr_core_optimization_DOF_Node_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def default_value(self, dof: DOF_Type, default_value_a) -> None: ...
    @overload
    def default_value(self, constenumcore, constclassstd) -> void: ...
    @overload
    def default_value(self, default_value_a) -> None: ...
    @overload
    def default_value(self, constclassstd) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, i_res: int, n_atom: int) -> None: ...
    @overload
    def resize(self, i_res: int, n_atom: int, value) -> None: ...
    @overload
    def set(self, dof: DOF_Type) -> None: ...
    @overload
    def set(self, constenumcore) -> void: ...
    @overload
    def set(self, dof: DOF_Type, value) -> None: ...
    @overload
    def set(self, constenumcore, constclassstd) -> void: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: DOF_ID_Map_std_shared_ptr_core_optimization_DOF_Node_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    def __call__(self, dof: DOF_Type) -> AtomID_Map_std_shared_ptr_core_optimization_DOF_Node_t: ...
    def __getitem__(self, dof: DOF_Type) -> AtomID_Map_std_shared_ptr_core_optimization_DOF_Node_t: ...

class DOF_ID_Range:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, dof_id: DOF_ID, min: float, max: float) -> None: ...
    def dof_id(self) -> DOF_ID: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def max(self) -> float: ...
    @overload
    def max(self) -> double: ...
    @overload
    def min(self) -> float: ...
    @overload
    def min(self) -> double: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class DOF_Type:
    __members__: ClassVar[dict] = ...  # read-only
    D: ClassVar[DOF_Type] = ...
    INVALID_DOF: ClassVar[DOF_Type] = ...
    PHI: ClassVar[DOF_Type] = ...
    RB1: ClassVar[DOF_Type] = ...
    RB2: ClassVar[DOF_Type] = ...
    RB3: ClassVar[DOF_Type] = ...
    RB4: ClassVar[DOF_Type] = ...
    RB5: ClassVar[DOF_Type] = ...
    RB6: ClassVar[DOF_Type] = ...
    THETA: ClassVar[DOF_Type] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class EXCN_AtomNotFound(pyrosetta.rosetta.utility.excn.Exception):
    @overload
    def __init__(self, file: str, line: int) -> None: ...
    @overload
    def __init__(self, arg0: EXCN_AtomNotFound) -> None: ...
    @overload
    def __init__(self, arg0: EXCN_AtomNotFound) -> None: ...
    def assign(self) -> EXCN_AtomNotFound: ...
    def atom(self) -> NamedAtomID: ...

class JumpID:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rsd1_in: int, rsd2_in: int) -> None: ...
    @overload
    def __init__(self, arg0: JumpID) -> None: ...
    def assign(self) -> JumpID: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def rsd1(self) -> int: ...
    @overload
    def rsd1(self) -> unsignedlong: ...
    def rsd2(self) -> int: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def valid(self) -> bool: ...
    @overload
    def valid(self) -> bool: ...

class MainchainTorsionType:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    omega2_dihedral: ClassVar[MainchainTorsionType] = ...
    omega3_dihedral: ClassVar[MainchainTorsionType] = ...
    omega_dihedral: ClassVar[MainchainTorsionType] = ...
    phi_dihedral: ClassVar[MainchainTorsionType] = ...
    psi_dihedral: ClassVar[MainchainTorsionType] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class NamedAtomID:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: NamedAtomID) -> None: ...
    @overload
    def __init__(self, atom_in: str, rsd_in: int) -> None: ...
    @staticmethod
    def BOGUS_NAMED_ATOM_ID() -> NamedAtomID: ...
    @staticmethod
    def CHAINBREAK_BOGUS_NAMED_ATOM_ID() -> NamedAtomID: ...
    def assign(self) -> NamedAtomID: ...
    def atom(self) -> str: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def rsd(self) -> int: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def to_string(self) -> str: ...
    @overload
    def valid(self) -> bool: ...
    @overload
    def valid(self) -> bool: ...

class NamedAtomID_Map_NamedAtomID(NamedAtomID_Map_core_id_NamedAtomID_t):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: NamedAtomID_Map_NamedAtomID) -> None: ...

class NamedAtomID_Map_bool_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a: bool) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a: bool) -> None: ...
    @overload
    def __init__(self, arg0: NamedAtomID_Map_bool_t) -> None: ...
    def assign(self) -> NamedAtomID_Map_bool_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear(self, default_value_a: bool) -> None: ...
    @overload
    def default_value(self) -> bool: ...
    @overload
    def default_value(self, default_value_a: bool) -> None: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fill(self) -> None: ...
    @overload
    def fill(self) -> void: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    @overload
    def get(self, id: NamedAtomID) -> bool: ...
    @overload
    def get(self, constclasscore) -> constbool: ...
    @overload
    def has(self, id: NamedAtomID) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self) -> None: ...
    @overload
    def resize(self) -> None: ...
    def set(self, id: NamedAtomID, value: bool) -> None: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: NamedAtomID_Map_bool_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    @overload
    def update_sequence_numbering(self, new_size: int, old2new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def update_sequence_numbering(self, constunsignedlong, constclassutility) -> void: ...
    @overload
    def __call__(self, id: NamedAtomID) -> bool: ...
    @overload
    def __call__(self, i_res: int, atom: str) -> bool: ...
    @overload
    def __call__(self, i_res: int) -> pyrosetta.rosetta.std.map_std_string_bool: ...
    @overload
    def __getitem__(self, id: NamedAtomID) -> bool: ...
    @overload
    def __getitem__(self, i_res: int) -> pyrosetta.rosetta.std.map_std_string_bool: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.std.map_std_string_bool]: ...

class NamedAtomID_Map_core_id_NamedAtomID_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, default_value_a: NamedAtomID) -> None: ...
    @overload
    def __init__(self, n_res: int) -> None: ...
    @overload
    def __init__(self, n_res: int, default_value_a: NamedAtomID) -> None: ...
    @overload
    def __init__(self, arg0: NamedAtomID_Map_core_id_NamedAtomID_t) -> None: ...
    def assign(self) -> NamedAtomID_Map_core_id_NamedAtomID_t: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear(self, default_value_a: NamedAtomID) -> None: ...
    @overload
    def clear(self, constclasscore) -> void: ...
    @overload
    def default_value(self) -> NamedAtomID: ...
    @overload
    def default_value(self, default_value_a: NamedAtomID) -> None: ...
    @overload
    def default_value(self, constclasscore) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def fill(self) -> None: ...
    @overload
    def fill(self) -> void: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...
    def get(self, id: NamedAtomID) -> NamedAtomID: ...
    @overload
    def has(self, id: NamedAtomID) -> bool: ...
    @overload
    def has(self, constclasscore) -> bool: ...
    @overload
    def n_atom(self, i_res: int) -> int: ...
    @overload
    def n_atom(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def n_residue(self) -> int: ...
    @overload
    def n_residue(self) -> unsignedlong: ...
    @overload
    def resize(self, n_res: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def resize(self) -> None: ...
    @overload
    def resize(self) -> None: ...
    def set(self, id: NamedAtomID, value: NamedAtomID) -> None: ...
    @overload
    def shrink(self) -> None: ...
    @overload
    def shrink(self) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def swap(self, s: NamedAtomID_Map_core_id_NamedAtomID_t) -> None: ...
    @overload
    def swap(self, classcore) -> void: ...
    @overload
    def update_sequence_numbering(self, new_size: int, old2new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def update_sequence_numbering(self, constunsignedlong, constclassutility) -> void: ...
    @overload
    def __call__(self, id: NamedAtomID) -> NamedAtomID: ...
    @overload
    def __call__(self, i_res: int, atom: str) -> NamedAtomID: ...
    @overload
    def __call__(self, i_res: int) -> pyrosetta.rosetta.std.map_std_string_core_id_NamedAtomID: ...
    @overload
    def __getitem__(self, id: NamedAtomID) -> NamedAtomID: ...
    @overload
    def __getitem__(self, i_res: int) -> pyrosetta.rosetta.std.map_std_string_core_id_NamedAtomID: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.std.map_std_string_core_id_NamedAtomID]: ...

class NamedStubID:
    atom1: NamedAtomID
    atom2: NamedAtomID
    atom3: NamedAtomID
    center_: NamedAtomID
    @overload
    def __init__(self, a1: NamedAtomID, a2: NamedAtomID, a3: NamedAtomID) -> None: ...
    @overload
    def __init__(self, c: NamedAtomID, a1: NamedAtomID, a2: NamedAtomID, a3: NamedAtomID) -> None: ...
    @overload
    def __init__(self, a1: str, a2: str, a3: str, rsd: int) -> None: ...
    @overload
    def __init__(self, c: str, a1: str, a2: str, a3: str, rsd: int) -> None: ...
    @overload
    def __init__(self, a1: str, rsd1: int, a2: str, rsd2: int, a3: str, rsd3: int) -> None: ...
    @overload
    def __init__(self, rsd: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: NamedStubID) -> None: ...
    def assign(self) -> NamedStubID: ...
    def atom(self, index: int) -> NamedAtomID: ...
    def center(self) -> NamedAtomID: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def valid(self) -> bool: ...
    @overload
    def valid(self) -> bool: ...

class PartialAtomID:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PartialAtomID) -> None: ...
    @overload
    def __init__(self, atomno_in: int, rsd_in: int) -> None: ...
    @overload
    def __init__(self, resconnid_in: int, rsd_in: int, bonds_from_resconn_in: int) -> None: ...
    @staticmethod
    def BOGUS_PARTIAL_ATOM_ID() -> PartialAtomID: ...
    @staticmethod
    def CHAINBREAK_BOGUS_PARTIAL_ATOM_ID() -> PartialAtomID: ...
    def assign(self) -> PartialAtomID: ...
    @overload
    def atomno(self) -> int: ...
    @overload
    def atomno(self) -> unsignedlong: ...
    @overload
    def bonds_from_resconn(self) -> int: ...
    @overload
    def bonds_from_resconn(self) -> unsignedlong: ...
    @overload
    def complete(self) -> bool: ...
    @overload
    def complete(self) -> bool: ...
    @overload
    def deserialize(self, data: pyrosetta.rosetta.std.map_std_string_utility_json_spirit_Value_impl_utility_json_spirit_Config_map_std_string_t_std_allocator_std_pair_const_std_string_utility_json_spirit_Value_impl_utility_json_spirit_Config_map_std_string_t) -> None: ...
    @overload
    def deserialize(self, classstd, classutility) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def partial(self) -> bool: ...
    @overload
    def partial(self) -> bool: ...
    @overload
    def resconnid(self) -> int: ...
    @overload
    def resconnid(self) -> unsignedlong: ...
    @overload
    def rsd(self) -> int: ...
    @overload
    def rsd(self) -> unsignedlong: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def serialize(self) -> pyrosetta.rosetta.utility.json_spirit.Value_impl_utility_json_spirit_Config_vector_std_string_t: ...
    def set_complete(self, atomno_in: int, rsd_in: int) -> None: ...
    def set_partial(self, resconnid_in: int, bonds_from_resconn_in: int, rsd_in: int) -> None: ...
    @overload
    def valid(self) -> bool: ...
    @overload
    def valid(self) -> bool: ...

class SequenceMapping:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, s1: int, s2: int) -> None: ...
    @overload
    def __init__(self, mapping: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, event) -> None: ...
    @overload
    def __init__(self, arg0: SequenceMapping) -> None: ...
    @overload
    def __init__(self, arg0: SequenceMapping) -> None: ...
    @overload
    def all_aligned(self) -> bool: ...
    @overload
    def all_aligned(self) -> bool: ...
    def assign(self, src: SequenceMapping) -> SequenceMapping: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def delete_source_residue(self, pos1: int) -> None: ...
    @overload
    def delete_source_residue(self, constunsignedlong) -> void: ...
    @overload
    def delete_target_residue(self, pos: int) -> None: ...
    @overload
    def delete_target_residue(self, constunsignedlong) -> void: ...
    @overload
    def downstream_combine(self, smap_to_add: SequenceMapping) -> None: ...
    @overload
    def downstream_combine(self, constclasscore) -> void: ...
    @overload
    def get_corresponding_residue_in_current(self, original_resnum: int) -> int: ...
    @overload
    def get_corresponding_residue_in_current(self, unsignedlong) -> unsignedlong: ...
    @staticmethod
    def identity(size: int) -> SequenceMapping: ...
    def insert_aligned_residue(self, pos1: int, pos2: int) -> None: ...
    def insert_aligned_residue_safe(self, pos1: int, pos2: int) -> None: ...
    @overload
    def insert_source_residue(self, pos1: int) -> None: ...
    @overload
    def insert_source_residue(self, constunsignedlong) -> void: ...
    @overload
    def insert_target_residue(self, pos: int) -> None: ...
    @overload
    def insert_target_residue(self, constunsignedlong) -> void: ...
    @overload
    def is_identity(self) -> bool: ...
    @overload
    def is_identity(self) -> bool: ...
    @overload
    def is_identity_ignore_gaps(self) -> bool: ...
    @overload
    def is_identity_ignore_gaps(self) -> bool: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def mapping(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def mapping(self, mapping: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def mapping(self, constclassutility) -> void: ...
    @overload
    def push_back(self, al: int) -> None: ...
    @overload
    def push_back(self, constunsignedlong) -> void: ...
    @overload
    def resize(self, s1: int, s2: int) -> None: ...
    @overload
    def resize(self, s1: int, s2: int, clear_values: bool) -> None: ...
    @overload
    def reverse(self) -> None: ...
    @overload
    def reverse(self) -> void: ...
    @overload
    def same_type_as_me(self, other: SequenceMapping) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_offset(self, setting: int) -> None: ...
    @overload
    def set_offset(self, int) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self) -> void: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def size1(self) -> int: ...
    @overload
    def size1(self) -> unsignedlong: ...
    @overload
    def size2(self) -> int: ...
    @overload
    def size2(self) -> unsignedlong: ...
    @overload
    def size2(self, s2: int) -> None: ...
    @overload
    def size2(self, constunsignedlong) -> void: ...
    def to_string(self) -> str: ...
    @overload
    def upstream_combine(self, smap_to_add: SequenceMapping) -> None: ...
    @overload
    def upstream_combine(self, constclasscore) -> void: ...
    def __eq__(self, rhs: SequenceMapping) -> bool: ...
    def __getitem__(self, pos1: int) -> int: ...
    def __iter__(self) -> typing.Iterator[int]: ...

class StubID:
    atom1: AtomID
    atom2: AtomID
    atom3: AtomID
    center_: AtomID
    @overload
    def __init__(self, a1: AtomID, a2: AtomID, a3: AtomID) -> None: ...
    @overload
    def __init__(self, c: AtomID, a1: AtomID, a2: AtomID, a3: AtomID) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: StubID) -> None: ...
    @staticmethod
    def BOGUS_STUB_ID() -> StubID: ...
    def assign(self) -> StubID: ...
    def atom(self, index: int) -> AtomID: ...
    def center(self) -> AtomID: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def valid(self) -> bool: ...
    @overload
    def valid(self) -> bool: ...
    def __eq__(self, rhs: StubID) -> bool: ...
    def __ne__(self, rhs: StubID) -> bool: ...

class TorsionID:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TorsionID) -> None: ...
    @overload
    def __init__(self, rsd_in: int, type_in: TorsionType, torsion_in: int) -> None: ...
    @staticmethod
    def BOGUS_TORSION_ID() -> TorsionID: ...
    def assign(self) -> TorsionID: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def rsd(self) -> int: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def str(self) -> str: ...
    def torsion(self) -> int: ...
    @overload
    def type(self) -> TorsionType: ...
    @overload
    def type(self, BB, CHI, NU, BRANCH, JUMP) -> Any: ...
    @overload
    def valid(self) -> bool: ...
    @overload
    def valid(self) -> bool: ...

class TorsionID_Range:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, torsion_id: TorsionID, min: float, max: float) -> None: ...
    @overload
    def __init__(self, arg0: TorsionID_Range) -> None: ...
    def assign(self) -> TorsionID_Range: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def max(self) -> float: ...
    @overload
    def max(self) -> double: ...
    @overload
    def min(self) -> float: ...
    @overload
    def min(self) -> double: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def torsion_id(self) -> TorsionID: ...

class TorsionType:
    __members__: ClassVar[dict] = ...  # read-only
    BB: ClassVar[TorsionType] = ...
    BRANCH: ClassVar[TorsionType] = ...
    CHI: ClassVar[TorsionType] = ...
    JUMP: ClassVar[TorsionType] = ...
    NU: ClassVar[TorsionType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

@overload
def DOF_type_is_rb(t: DOF_Type) -> bool: ...
@overload
def DOF_type_is_rb(constenumcore) -> bool: ...
@overload
def combine_sequence_mappings(smap: SequenceMapping, smap_to_add: SequenceMapping) -> None: ...
@overload
def combine_sequence_mappings(classcore, constclasscore) -> void: ...
@overload
def get_rb_number(t: DOF_Type) -> int: ...
@overload
def get_rb_number(constenumcore) -> unsignedlong: ...
def get_rb_type(k: int) -> DOF_Type: ...
@overload
def initialize_core_id_globals() -> None: ...
@overload
def initialize_core_id_globals() -> void: ...
@overload
def to_string(type: DOF_Type) -> str: ...
@overload
def to_string(type: TorsionType) -> str: ...
