import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.conformation.symmetry
import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import overload

class ChainbreakUtil:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ChainbreakUtil) -> None: ...
    def assign(self) -> ChainbreakUtil: ...
    @overload
    def has_chainbreak(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def has_chainbreak(self, constclasscore) -> bool: ...

def add_constraints_to_metal(pose: pyrosetta.rosetta.core.pose.Pose, metal_position: int, distance_constraint_multiplier: float, angle_constraint_multiplier: float, binders: pyrosetta.rosetta.utility.vector1_core_id_AtomID) -> None: ...
def add_covalent_linkage(pose: pyrosetta.rosetta.core.pose.Pose, resA_pos: int, resB_pos: int, resA_At: int, resB_At: int, remove_hydrogens: bool) -> None: ...
@overload
def add_covalent_linkages_to_metal(pose: pyrosetta.rosetta.core.pose.Pose, metal_position: int, liganding_atomids: pyrosetta.rosetta.utility.vector1_core_id_AtomID) -> None: ...
@overload
def add_covalent_linkages_to_metal(pose: pyrosetta.rosetta.core.pose.Pose, metal_position: int, liganding_atomids: pyrosetta.rosetta.utility.vector1_core_id_AtomID, remove_hydrogens: bool) -> None: ...
@overload
def add_covalent_linkages_to_metal(classcore, constunsignedlong, classutility, constbool) -> void: ...
@overload
def auto_setup_all_metal_bonds(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def auto_setup_all_metal_bonds(pose: pyrosetta.rosetta.core.pose.Pose, dist_cutoff_multiplier: float) -> None: ...
@overload
def auto_setup_all_metal_bonds(pose: pyrosetta.rosetta.core.pose.Pose, dist_cutoff_multiplier: float, remove_hydrogens: bool) -> None: ...
@overload
def auto_setup_all_metal_bonds(classcore, constdouble, constbool) -> void: ...
@overload
def auto_setup_all_metal_constraints(pose: pyrosetta.rosetta.core.pose.Pose, distance_constraint_multiplier: float, angle_constraint_multiplier: float) -> None: ...
@overload
def auto_setup_all_metal_constraints(pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, distance_constraint_multiplier: float, angle_constraint_multiplie: float) -> None: ...
@overload
def find_metalbinding_atoms(pose: pyrosetta.rosetta.core.pose.Pose, metal_position: int) -> pyrosetta.rosetta.utility.vector1_core_id_AtomID: ...
@overload
def find_metalbinding_atoms(pose: pyrosetta.rosetta.core.pose.Pose, metal_position: int, dist_cutoff_multiplier: float) -> pyrosetta.rosetta.utility.vector1_core_id_AtomID: ...
def find_metalbinding_atoms_for_complex(pose: pyrosetta.rosetta.core.pose.Pose, metal_position: int, dist_cutoff_multiplier: float) -> pyrosetta.rosetta.std.map_unsigned_long_utility_vector1_core_id_AtomID_t_std_allocator_std_pair_const_unsigned_long_utility_vector1_core_id_AtomID_t: ...
def find_metalbinding_atoms_helper(pose: pyrosetta.rosetta.core.pose.Pose, metal_atom: pyrosetta.rosetta.core.id.AtomID, dist_cutoff_multiplier: float) -> pyrosetta.rosetta.utility.vector1_core_id_AtomID: ...
def generate_replacement_restype(restype: pyrosetta.rosetta.core.chemical.ResidueType, mode: pyrosetta.rosetta.core.chemical.TypeSetMode) -> pyrosetta.rosetta.core.chemical.MutableResidueType: ...
@overload
def getMLweight(scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> float: ...
@overload
def getMLweight(scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> float: ...
@overload
def getMLweight_cart(scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> float: ...
@overload
def getMLweight_cart(scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> float: ...
@overload
def rebuild_disulfide(pose: pyrosetta.rosetta.core.pose.Pose, lower_res: int, upper_res: int, threads_to_request: int) -> None: ...
@overload
def rebuild_disulfide(pose: pyrosetta.rosetta.core.pose.Pose, lower_res: int, upper_res: int, threads_to_request: int, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
@overload
def rebuild_disulfide(pose: pyrosetta.rosetta.core.pose.Pose, lower_res: int, upper_res: int, threads_to_request: int, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask, packer_score: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
@overload
def rebuild_disulfide(pose: pyrosetta.rosetta.core.pose.Pose, lower_res: int, upper_res: int, threads_to_request: int, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask, packer_score: pyrosetta.rosetta.core.scoring.ScoreFunction, mm: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
@overload
def rebuild_disulfide(pose: pyrosetta.rosetta.core.pose.Pose, lower_res: int, upper_res: int, threads_to_request: int, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask, packer_score: pyrosetta.rosetta.core.scoring.ScoreFunction, mm: pyrosetta.rosetta.core.kinematics.MoveMap, minimizer_score: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
@overload
def rebuild_disulfide(pose: pyrosetta.rosetta.core.pose.Pose, disulfides: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t, threads_to_request: int) -> None: ...
@overload
def rebuild_disulfide(pose: pyrosetta.rosetta.core.pose.Pose, disulfides: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t, threads_to_request: int, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
@overload
def rebuild_disulfide(pose: pyrosetta.rosetta.core.pose.Pose, disulfides: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t, threads_to_request: int, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask, packer_score: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
@overload
def rebuild_disulfide(pose: pyrosetta.rosetta.core.pose.Pose, disulfides: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t, threads_to_request: int, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask, packer_score: pyrosetta.rosetta.core.scoring.ScoreFunction, mm: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
@overload
def rebuild_disulfide(pose: pyrosetta.rosetta.core.pose.Pose, disulfides: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t, threads_to_request: int, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask, packer_score: pyrosetta.rosetta.core.scoring.ScoreFunction, mm: pyrosetta.rosetta.core.kinematics.MoveMap, minimizer_score: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
@overload
def rebuild_fa_disulfides(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def rebuild_fa_disulfides(pose: pyrosetta.rosetta.core.pose.Pose, threads_to_request: int) -> None: ...
@overload
def rebuild_fa_disulfides(classcore, constunsignedlong) -> void: ...
@overload
def remove_cutpoint_variants(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def remove_cutpoint_variants(classcore) -> void: ...
@overload
def switch_to_centroid_rot_set(pose: pyrosetta.rosetta.core.pose.Pose, symm_info: pyrosetta.rosetta.core.conformation.symmetry.SymmetryInfo, rsd_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
@overload
def switch_to_centroid_rot_set(pose: pyrosetta.rosetta.core.pose.Pose, symm_info: pyrosetta.rosetta.core.conformation.symmetry.SymmetryInfo, rsd_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, allow_sloppy_match: bool) -> None: ...
@overload
def switch_to_centroid_rot_set(classcore, classstd, constclasscore, bool) -> void: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, threads_to_request: int) -> None: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, threads_to_request: int, allow_sloppy_match: bool) -> None: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, threads_to_request: int, allow_sloppy_match: bool, switch_protein_res_only: bool) -> None: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, threads_to_request: int, allow_sloppy_match: bool, switch_protein_res_only: bool, keep_energies: bool) -> None: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set_mode: pyrosetta.rosetta.core.chemical.TypeSetMode) -> None: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set_mode: pyrosetta.rosetta.core.chemical.TypeSetMode, threads_to_request: int) -> None: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set_mode: pyrosetta.rosetta.core.chemical.TypeSetMode, threads_to_request: int, allow_sloppy_match: bool) -> None: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set_mode: pyrosetta.rosetta.core.chemical.TypeSetMode, threads_to_request: int, allow_sloppy_match: bool, switch_protein_res_only: bool) -> None: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set_mode: pyrosetta.rosetta.core.chemical.TypeSetMode, threads_to_request: int, allow_sloppy_match: bool, switch_protein_res_only: bool, keep_energies: bool) -> None: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set_name: str) -> None: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set_name: str, threads_to_request: int) -> None: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set_name: str, threads_to_request: int, allow_sloppy_match: bool) -> None: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set_name: str, threads_to_request: int, allow_sloppy_match: bool, switch_protein_res_only: bool) -> None: ...
@overload
def switch_to_residue_type_set(pose: pyrosetta.rosetta.core.pose.Pose, type_set_name: str, threads_to_request: int, allow_sloppy_match: bool, switch_protein_res_only: bool, keep_energies: bool) -> None: ...
