from pyrosetta.bindings.utility import bind_method as bind_method
from pyrosetta.rosetta.core.select import get_residues_from_subset as get_residues_from_subset
from pyrosetta.rosetta.core.select.residue_selector import AndResidueSelector as AndResidueSelector, NotResidueSelector as NotResidueSelector, OrResidueSelector as OrResidueSelector, ResidueSelector as ResidueSelector

def get_residues(self, pose): ...
def __and__(self, selector): ...
def __or__(self, selector): ...
def __invert__(self): ...
def __xor__(self, selector): ...
def __iand__(self, selector): ...
def __ior__(self, selector): ...
def __ixor__(self, selector): ...
