import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.pack.dunbrack
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.canonical_sampling
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import overload

class JumpRotamerSidechainMover(PerturbRotamerSidechainMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rotamer_library: pyrosetta.rosetta.core.pack.dunbrack.RotamerLibrary) -> None: ...
    @overload
    def __init__(self, arg0: JumpRotamerSidechainMover) -> None: ...
    @overload
    def __init__(self, arg0: JumpRotamerSidechainMover) -> None: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def compute_proposal_density(self, new_residue: pyrosetta.rosetta.core.conformation.Residue, resnum: int, old_res_type: pyrosetta.rosetta.core.chemical.ResidueType, old_chi: pyrosetta.rosetta.utility.vector1_double) -> float: ...
    def get_name(self) -> str: ...
    @overload
    def make_chi_move(self, residue: pyrosetta.rosetta.core.conformation.Residue, old_chi: pyrosetta.rosetta.utility.vector1_double, new_chi: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def make_chi_move(self, constclasscore, constclassutility, classutility) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class JumpRotamerSidechainMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: JumpRotamerSidechainMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: JumpRotamerSidechainMoverCreator) -> None: ...
    def assign(self) -> JumpRotamerSidechainMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class PerturbChiSidechainMover(SidechainMoverBase):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rotamer_library: pyrosetta.rosetta.core.pack.dunbrack.RotamerLibrary) -> None: ...
    @overload
    def __init__(self, arg0: PerturbChiSidechainMover) -> None: ...
    @overload
    def __init__(self, arg0: PerturbChiSidechainMover) -> None: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def compute_proposal_density(self) -> float: ...
    def get_name(self) -> str: ...
    @overload
    def make_chi_move(self, residue: pyrosetta.rosetta.core.conformation.Residue, old_chi: pyrosetta.rosetta.utility.vector1_double, new_chi: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def make_chi_move(self, constclasscore, constclassutility, classutility) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_gaussian(self, setting: bool) -> None: ...
    @overload
    def set_gaussian(self, bool) -> void: ...
    @overload
    def set_magnitude(self, setting: float) -> None: ...
    @overload
    def set_magnitude(self, double) -> void: ...

class PerturbChiSidechainMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PerturbChiSidechainMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: PerturbChiSidechainMoverCreator) -> None: ...
    def assign(self) -> PerturbChiSidechainMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class PerturbRotamerSidechainMover(SidechainMoverBase):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rotamer_library: pyrosetta.rosetta.core.pack.dunbrack.RotamerLibrary) -> None: ...
    @overload
    def __init__(self, arg0: PerturbRotamerSidechainMover) -> None: ...
    @overload
    def __init__(self, arg0: PerturbRotamerSidechainMover) -> None: ...
    @overload
    def build_rotamer_list(self, filter: bool) -> None: ...
    @overload
    def build_rotamer_list(self, constclasscore, bool, classutility) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def compute_proposal_density(self, new_residue: pyrosetta.rosetta.core.conformation.Residue, resnum: int, old_res_type: pyrosetta.rosetta.core.chemical.ResidueType, old_chi: pyrosetta.rosetta.utility.vector1_double) -> float: ...
    def compute_rotdensities(self, old_chi: pyrosetta.rosetta.utility.vector1_double, new_chi: pyrosetta.rosetta.utility.vector1_double, within_rot_density: float) -> None: ...
    def get_name(self) -> str: ...
    @overload
    def make_chi_move(self, residue: pyrosetta.rosetta.core.conformation.Residue, old_chi: pyrosetta.rosetta.utility.vector1_double, new_chi: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def make_chi_move(self, constclasscore, constclassutility, classutility) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_temperature(self, setting: float) -> None: ...
    @overload
    def set_temperature(self, double) -> void: ...
    @overload
    def temperature(self) -> float: ...
    @overload
    def temperature(self) -> double: ...

class PerturbRotamerSidechainMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PerturbRotamerSidechainMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: PerturbRotamerSidechainMoverCreator) -> None: ...
    def assign(self) -> PerturbRotamerSidechainMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SetChiMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SetChiMover) -> None: ...
    @overload
    def __init__(self, arg0: SetChiMover) -> None: ...
    @overload
    def angle(self) -> float: ...
    @overload
    def angle(self) -> double: ...
    @overload
    def angle(self, a: float) -> None: ...
    @overload
    def angle(self, constdouble) -> void: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> SetChiMover: ...
    @overload
    def chinum(self) -> int: ...
    @overload
    def chinum(self) -> unsignedlong: ...
    @overload
    def chinum(self, c: int) -> None: ...
    @overload
    def chinum(self, constunsignedlong) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def resnum(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def resnum(self, constclasscore) -> unsignedlong: ...
    @overload
    def resnum(self, r: pyrosetta.rosetta.core.pose.ResidueIndexDescription) -> None: ...
    @overload
    def resnum(self, classstd) -> void: ...
    @overload
    def resnum(self, r: int) -> None: ...
    @overload
    def resnum(self, constunsignedlong) -> void: ...

class SetChiMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SetChiMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: SetChiMoverCreator) -> None: ...
    def assign(self) -> SetChiMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SidechainMCMover(SidechainMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rotamer_library: pyrosetta.rosetta.core.pack.dunbrack.RotamerLibrary) -> None: ...
    @overload
    def __init__(self, arg0: SidechainMCMover) -> None: ...
    @overload
    def __init__(self, arg0: SidechainMCMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def inherit_scorefxn_temperature(self) -> bool: ...
    @overload
    def inherit_scorefxn_temperature(self) -> bool: ...
    @overload
    def initialize_simulation(self, pose: pyrosetta.rosetta.core.pose.Pose, metropolis_hastings_mover: pyrosetta.rosetta.protocols.canonical_sampling.MetropolisHastingsMover, cycle: int) -> None: ...
    @overload
    def initialize_simulation(self, classcore, constclassprotocols, unsignedlong) -> void: ...
    @overload
    def is_multi_trial(self) -> bool: ...
    @overload
    def is_multi_trial(self) -> bool: ...
    @overload
    def last_inner_score_delta_over_temperature(self) -> float: ...
    @overload
    def last_inner_score_delta_over_temperature(self) -> double: ...
    @overload
    def last_proposal_density_ratio(self) -> float: ...
    @overload
    def last_proposal_density_ratio(self) -> double: ...
    def metropolis_hastings_mover(self) -> pyrosetta.rosetta.std.weak_ptr_protocols_canonical_sampling_MetropolisHastingsMover_t: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def ntrials(self) -> int: ...
    @overload
    def ntrials(self) -> unsignedlong: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def scorefunction(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def set_inherit_scorefxn_temperature(self, inherit_scorefxn_temperature: bool) -> None: ...
    @overload
    def set_inherit_scorefxn_temperature(self, bool) -> void: ...
    @overload
    def set_metropolis_hastings_mover(self, metropolis_hastings_mover: pyrosetta.rosetta.std.weak_ptr_protocols_canonical_sampling_MetropolisHastingsMover_t) -> None: ...
    @overload
    def set_metropolis_hastings_mover(self, classstd) -> void: ...
    @overload
    def set_ntrials(self, ntrial: int) -> None: ...
    @overload
    def set_ntrials(self, unsignedlong) -> void: ...
    @overload
    def set_scorefunction(self, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefunction(self, constclasscore) -> void: ...
    @overload
    def set_temperature(self, temp: float) -> None: ...
    @overload
    def set_temperature(self, double) -> void: ...
    @overload
    def setup(self, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def setup(self, classstd) -> void: ...
    @overload
    def show_counters(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_counters(self, std) -> void: ...
    @overload
    def temperature(self) -> float: ...
    @overload
    def temperature(self) -> double: ...

class SidechainMCMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SidechainMCMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: SidechainMCMoverCreator) -> None: ...
    def assign(self) -> SidechainMCMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SidechainMover(pyrosetta.rosetta.protocols.canonical_sampling.ThermodynamicMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rotamer_library: pyrosetta.rosetta.core.pack.dunbrack.RotamerLibrary) -> None: ...
    @overload
    def __init__(self, arg0: SidechainMover) -> None: ...
    @overload
    def __init__(self, arg0: SidechainMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    @overload
    def change_chi_without_replacing_residue(self) -> bool: ...
    @overload
    def change_chi_without_replacing_residue(self) -> bool: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def idealize_sidechains(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def idealize_sidechains(self, classcore) -> void: ...
    @overload
    def init_task(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def init_task(self, constclasscore) -> void: ...
    @overload
    def initialize_simulation(self, pose: pyrosetta.rosetta.core.pose.Pose, metropolis_hastings_mover: pyrosetta.rosetta.protocols.canonical_sampling.MetropolisHastingsMover, cycle: int) -> None: ...
    @overload
    def initialize_simulation(self, classcore, constclassprotocols, unsignedlong) -> void: ...
    @overload
    def last_mutation(self) -> bool: ...
    @overload
    def last_mutation(self) -> bool: ...
    @overload
    def last_nchi(self) -> int: ...
    @overload
    def last_nchi(self) -> unsignedlong: ...
    @overload
    def last_proposal_density_ratio(self) -> float: ...
    @overload
    def last_proposal_density_ratio(self) -> double: ...
    @overload
    def last_uniform(self) -> bool: ...
    @overload
    def last_uniform(self) -> bool: ...
    @overload
    def last_withinrot(self) -> bool: ...
    @overload
    def last_withinrot(self) -> bool: ...
    def make_move(self, res: pyrosetta.rosetta.core.conformation.Residue, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.conformation.Residue: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def next_resnum(self) -> int: ...
    @overload
    def next_resnum(self) -> unsignedlong: ...
    @overload
    def next_resnum(self, resnum: int) -> None: ...
    @overload
    def next_resnum(self, unsignedlong) -> void: ...
    def packed_residues(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def preserve_detailed_balance(self) -> bool: ...
    @overload
    def preserve_detailed_balance(self) -> bool: ...
    @overload
    def prob_random_pert_current(self) -> float: ...
    @overload
    def prob_random_pert_current(self) -> double: ...
    @overload
    def prob_uniform(self) -> float: ...
    @overload
    def prob_uniform(self) -> double: ...
    @overload
    def prob_withinrot(self) -> float: ...
    @overload
    def prob_withinrot(self) -> double: ...
    def proposal_density(self, proposed_residue: pyrosetta.rosetta.core.conformation.Residue, proposed_resnum: int, initial_residue_type: pyrosetta.rosetta.core.chemical.ResidueType, initial_chi_angles: pyrosetta.rosetta.utility.vector1_double) -> float: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def residue_packed(self) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def rotamer_library(self) -> pyrosetta.rosetta.core.pack.dunbrack.RotamerLibrary: ...
    @overload
    def sampling_temperature(self) -> float: ...
    @overload
    def sampling_temperature(self) -> double: ...
    @overload
    def set_change_chi_without_replacing_residue(self, change_chi_without_replacing_residue: bool) -> None: ...
    @overload
    def set_change_chi_without_replacing_residue(self, constbool) -> void: ...
    @overload
    def set_preserve_detailed_balance(self, preserve_detailed_balance: bool) -> None: ...
    @overload
    def set_preserve_detailed_balance(self, bool) -> void: ...
    @overload
    def set_prob_random_pert_current(self, prob_pert: float) -> None: ...
    @overload
    def set_prob_random_pert_current(self, double) -> void: ...
    @overload
    def set_prob_uniform(self, prob_uniform: float) -> None: ...
    @overload
    def set_prob_uniform(self, double) -> void: ...
    @overload
    def set_prob_withinrot(self, prob_withinrot: float) -> None: ...
    @overload
    def set_prob_withinrot(self, double) -> void: ...
    @overload
    def set_sampling_temperature(self, temp: float) -> None: ...
    @overload
    def set_sampling_temperature(self, double) -> void: ...
    @overload
    def set_task(self, task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def set_task(self, classstd) -> void: ...
    @overload
    def set_task_factory(self, task_factory: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...
    def task(self) -> pyrosetta.rosetta.core.pack.task.PackerTask: ...
    def task_factory(self) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    @overload
    def task_initialized(self) -> bool: ...
    @overload
    def task_initialized(self) -> bool: ...
    @overload
    def test_move(self) -> None: ...
    @overload
    def test_move(self, classcore) -> void: ...
    def torsion_id_ranges(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_core_id_TorsionID_Range: ...
    @overload
    def update_type(self) -> None: ...
    @overload
    def update_type(self) -> void: ...

class SidechainMoverBase(pyrosetta.rosetta.protocols.canonical_sampling.ThermodynamicMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rotamer_library: pyrosetta.rosetta.core.pack.dunbrack.RotamerLibrary) -> None: ...
    @overload
    def __init__(self, arg0: SidechainMoverBase) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    @overload
    def change_chi_without_replacing_residue(self) -> bool: ...
    @overload
    def change_chi_without_replacing_residue(self) -> bool: ...
    def compute_proposal_density(self, new_residue: pyrosetta.rosetta.core.conformation.Residue, resnum: int, old_res_type: pyrosetta.rosetta.core.chemical.ResidueType, old_chi: pyrosetta.rosetta.utility.vector1_double) -> float: ...
    def get_name(self) -> str: ...
    @overload
    def have_mutated_residue(self) -> bool: ...
    @overload
    def have_mutated_residue(self) -> bool: ...
    @overload
    def idealize_sidechains(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def idealize_sidechains(self, classcore) -> void: ...
    @overload
    def init_task(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def init_task(self, constclasscore) -> void: ...
    @overload
    def initialize_simulation(self, pose: pyrosetta.rosetta.core.pose.Pose, metropolis_hastings_mover: pyrosetta.rosetta.protocols.canonical_sampling.MetropolisHastingsMover, cycle: int) -> None: ...
    @overload
    def initialize_simulation(self, classcore, constclassprotocols, unsignedlong) -> void: ...
    @overload
    def last_proposal_density_ratio(self) -> float: ...
    @overload
    def last_proposal_density_ratio(self) -> double: ...
    @overload
    def make_chi_move(self, residue: pyrosetta.rosetta.core.conformation.Residue, old_chi: pyrosetta.rosetta.utility.vector1_double, new_chi: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def make_chi_move(self, constclasscore, constclassutility, classutility) -> void: ...
    def make_move(self, res: pyrosetta.rosetta.core.conformation.Residue) -> pyrosetta.rosetta.core.conformation.Residue: ...
    def packed_residues(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def preserve_detailed_balance(self) -> bool: ...
    @overload
    def preserve_detailed_balance(self) -> bool: ...
    def residue_packed(self) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def rotamer_library(self) -> pyrosetta.rosetta.core.pack.dunbrack.RotamerLibrary: ...
    @overload
    def set_change_chi_without_replacing_residue(self, setting: bool) -> None: ...
    @overload
    def set_change_chi_without_replacing_residue(self, bool) -> void: ...
    @overload
    def set_preserve_detailed_balance(self, setting: bool) -> None: ...
    @overload
    def set_preserve_detailed_balance(self, bool) -> void: ...
    @overload
    def set_task(self, task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def set_task(self, classstd) -> void: ...
    @overload
    def set_task_factory(self, task_factory: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...
    @overload
    def suggest_residue_number(self) -> int: ...
    @overload
    def suggest_residue_number(self, constclasscore) -> unsignedlong: ...
    def task(self) -> pyrosetta.rosetta.core.pack.task.PackerTask: ...
    def task_factory(self) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    def torsion_id_ranges(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_core_id_TorsionID_Range: ...

class SidechainMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SidechainMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: SidechainMoverCreator) -> None: ...
    def assign(self) -> SidechainMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
