import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.utility
from typing import overload

class TriazolamerMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, triazolamer_seq_position: int) -> None: ...
    @overload
    def __init__(self, triazolamer_seq_position: int, phi_angle: float, psi_angle: float) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def set_phi(self, angle: float) -> None: ...
    @overload
    def set_phi(self, double) -> void: ...
    @overload
    def set_psi(self, angle: float) -> None: ...
    @overload
    def set_psi(self, double) -> void: ...
    @overload
    def update_hydrogens(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def update_hydrogens(self, classcore) -> void: ...

class TriazolamerRandomSmallMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, triazolamer_seq_positions: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, triazolamer_seq_positions: pyrosetta.rosetta.utility.vector1_unsigned_long, max_small_angle: float) -> None: ...
    @overload
    def __init__(self, arg0: TriazolamerRandomSmallMover) -> None: ...
    @overload
    def __init__(self, arg0: TriazolamerRandomSmallMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def set_max_small_angle(self, angle: float) -> None: ...
    @overload
    def set_max_small_angle(self, double) -> void: ...
