import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.pose
from typing import overload

class RNA_SecStructLegacyInfo(pyrosetta.rosetta.basic.datacache.CacheableData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rna_secstruct_legacy_string: str) -> None: ...
    @overload
    def __init__(self, arg0: RNA_SecStructLegacyInfo) -> None: ...
    @overload
    def __init__(self, arg0: RNA_SecStructLegacyInfo) -> None: ...
    def assign(self) -> RNA_SecStructLegacyInfo: ...
    def clone(self) -> pyrosetta.rosetta.basic.datacache.CacheableData: ...
    def get_secstruct(self) -> str: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_secstruct(self, secstruct: str) -> None: ...
    @overload
    def set_secstruct(self, conststd) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...

@overload
def clear_rna_secstruct_legacy_info(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def clear_rna_secstruct_legacy_info(classcore) -> void: ...
def get_rna_secstruct_legacy(pose: pyrosetta.rosetta.core.pose.Pose) -> str: ...
def get_rna_secstruct_legacy_from_const_pose(pose: pyrosetta.rosetta.core.pose.Pose) -> str: ...
@overload
def has_rna_secstruct_legacy(pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
@overload
def has_rna_secstruct_legacy(constclasscore) -> bool: ...
@overload
def set_rna_secstruct_legacy(pose: pyrosetta.rosetta.core.pose.Pose, rna_secstruct_legacy_string: str) -> None: ...
@overload
def set_rna_secstruct_legacy(classcore, conststd) -> void: ...
