def generate_resfile_from_pose(pack_or_pose, resfilename, pack: bool = True, design: bool = False, input_sc: bool = True, freeze=..., specific=...) -> None: ...
def generate_resfile_from_pdb(pdbfilename, resfilename, pack: bool = True, design: bool = False, input_sc: bool = True, freeze=..., specific=...) -> None: ...
