from pyrosetta import Pose as Pose, init as init, pose_from_file as pose_from_file

def load_from_pubchem(cid, sdffilename: str = '') -> None: ...
def sdf2mdl(sdfile, mdlfilename) -> None: ...
def molfile2params_quick(mdlfile, name) -> None: ...
def params_from_pubchem(cid, name) -> None: ...
def add_cid_to_database(cid, name) -> None: ...
def pose_from_pubchem(cid, name, temporary: bool = True): ...
def pose_from_params(filename, params_list): ...
