import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pack.task.operation
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import overload

class AAFrequencies:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AAFrequencies) -> None: ...
    def assign(self) -> AAFrequencies: ...
    def frequency(self, aa: str) -> AAFrequency: ...
    @overload
    def has_frequency(self, aa: str) -> bool: ...
    @overload
    def has_frequency(self, constchar) -> bool: ...
    @overload
    def set_frequency(self, aa: str, frequency: AAFrequency) -> None: ...
    @overload
    def set_frequency(self, constchar, classstd) -> void: ...

class AAFrequency:
    @overload
    def __init__(self, frequency: float, enrichment: float) -> None: ...
    @overload
    def __init__(self, arg0: AAFrequency) -> None: ...
    def assign(self) -> AAFrequency: ...
    @overload
    def enrichment(self) -> float: ...
    @overload
    def enrichment(self) -> double: ...
    @overload
    def frequency(self) -> float: ...
    @overload
    def frequency(self) -> double: ...

class ConsensusLoopDatabase(pyrosetta.rosetta.utility.SingletonBase_protocols_denovo_design_task_operations_ConsensusLoopDatabase_t):
    def __init__(self) -> None: ...
    def frequencies(self, surrounding_ss: SurroundingSS, abego: str, loop_resid: int) -> AAFrequencies: ...
    def frequency(self, surrounding_ss: SurroundingSS, abego: str, loop_resid: int, aa: str) -> AAFrequency: ...
    @overload
    def has_frequencies(self, surrounding_ss: SurroundingSS, abego: str) -> bool: ...
    @overload
    def has_frequencies(self, conststructprotocols, conststd) -> bool: ...
    @overload
    def has_frequencies(self, surrounding_ss: SurroundingSS, abego: str, loop_resid: int) -> bool: ...
    @overload
    def has_frequencies(self, conststructprotocols, conststd, constunsignedlong) -> bool: ...
    @overload
    def has_frequency(self, surrounding_ss: SurroundingSS, abego: str, loop_resid: int, aa: str) -> bool: ...
    @overload
    def has_frequency(self, conststructprotocols, conststd, constunsignedlong, constchar) -> bool: ...
    @overload
    def set_frequency(self, surrounding_ss: SurroundingSS, abego: str, loop_resid: int, aa: str, frequency: AAFrequency) -> None: ...
    @overload
    def set_frequency(self, conststructprotocols, conststd, constunsignedlong, constchar, constclassstd) -> void: ...

class ConsensusLoopDesignOperation(pyrosetta.rosetta.core.pack.task.operation.TaskOperation):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ConsensusLoopDesignOperation) -> None: ...
    @overload
    def __init__(self, arg0: ConsensusLoopDesignOperation) -> None: ...
    def aa_frequencies(self, info: LoopInfo, resid: int) -> AAFrequencies: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose, task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def apply(self, constclasscore, classcore) -> void: ...
    def assign(self) -> ConsensusLoopDesignOperation: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.core.pack.task.operation.TaskOperation: ...
    @overload
    def disallow_aas(self, task: pyrosetta.rosetta.core.pack.task.PackerTask, info: LoopInfo) -> None: ...
    @overload
    def disallow_aas(self, classcore, conststructprotocols) -> void: ...
    def forbidden_aas(self, frequencies: AAFrequencies) -> str: ...
    def get_name(self) -> str: ...
    @overload
    def parse_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data_map: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_enrichment_threshold(self, threshold: float) -> None: ...
    @overload
    def set_enrichment_threshold(self, constdouble) -> void: ...
    @overload
    def set_include_adjacent_residues(self, include_res: bool) -> None: ...
    @overload
    def set_include_adjacent_residues(self, constbool) -> void: ...
    def set_residue_selector(self, *args, **kwargs): ...
    def set_secstruct(self, *args, **kwargs): ...
    @overload
    def set_secstruct_from_blueprint(self, bp_file: str) -> None: ...
    @overload
    def set_secstruct_from_blueprint(self, conststd) -> void: ...
    @overload
    def set_use_dssp(self, use_dssp: bool) -> None: ...
    @overload
    def set_use_dssp(self, constbool) -> void: ...

class ConsensusLoopDesignOperationCreator(pyrosetta.rosetta.core.pack.task.operation.TaskOperationCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ConsensusLoopDesignOperationCreator) -> None: ...
    @overload
    def __init__(self, arg0: ConsensusLoopDesignOperationCreator) -> None: ...
    def assign(self) -> ConsensusLoopDesignOperationCreator: ...
    def create_task_operation(self) -> pyrosetta.rosetta.core.pack.task.operation.TaskOperation: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class LoopInfo:
    abego: str
    ss_around: SurroundingSS
    startres: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LoopInfo) -> None: ...
    def assign(self) -> LoopInfo: ...

class SurroundingSS:
    after: str
    before: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, bef: str, aft: str) -> None: ...
    @overload
    def __init__(self, arg0: SurroundingSS) -> None: ...
    def assign(self) -> SurroundingSS: ...
