import pyrosetta.rosetta.utility
from typing import overload

class Column:
    @overload
    def __init__(self, name: str, type) -> None: ...
    @overload
    def __init__(self, name: str, type, allow_null: bool) -> None: ...
    @overload
    def __init__(self, name: str, type, allow_null: bool, auto_increment: bool) -> None: ...
    @overload
    def __init__(self, name: str, type, allow_null: bool, auto_increment: bool, auto_increment_base: int) -> None: ...
    @overload
    def __init__(self, arg0: Column) -> None: ...
    def assign(self) -> Column: ...
    @overload
    def auto_increment(self) -> bool: ...
    @overload
    def auto_increment(self) -> bool: ...
    @overload
    def auto_increment_base(self) -> int: ...
    @overload
    def auto_increment_base(self) -> unsignedlong: ...
    def name(self) -> str: ...
    def print(self, db_session) -> str: ...
    def __eq__(self, other: Column) -> bool: ...

class Constraint:
    @overload
    def __init__(self, column: Column) -> None: ...
    @overload
    def __init__(self, columns: pyrosetta.rosetta.utility.vector1_basic_database_schema_generator_Column) -> None: ...
    @overload
    def __init__(self, arg0: Constraint) -> None: ...
    def assign(self) -> Constraint: ...
    def print(self) -> str: ...

class DbBigInt(DbDataType):
    def __init__(self) -> None: ...
    def assign(self) -> DbBigInt: ...
    def print(self) -> str: ...

class DbDataType:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: int) -> None: ...
    @overload
    def __init__(self, arg0: DbDataType) -> None: ...
    def assign(self) -> DbDataType: ...
    def print(self) -> str: ...

class DbDouble(DbDataType):
    def __init__(self) -> None: ...
    def assign(self) -> DbDouble: ...
    def print(self) -> str: ...

class DbInteger(DbDataType):
    def __init__(self) -> None: ...
    def assign(self) -> DbInteger: ...
    def print(self) -> str: ...

class DbReal(DbDataType):
    def __init__(self) -> None: ...
    def assign(self) -> DbReal: ...
    def print(self) -> str: ...

class DbText(DbDataType):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: int) -> None: ...
    def assign(self) -> DbText: ...
    def print(self) -> str: ...

class DbTextKey(DbDataType):
    def __init__(self) -> None: ...
    def assign(self) -> DbTextKey: ...
    def print(self) -> str: ...

class DbUUID(DbDataType):
    def __init__(self) -> None: ...
    def assign(self) -> DbUUID: ...
    def print(self) -> str: ...

class ForeignKey:
    @overload
    def __init__(self, column: Column, reference_table: str, reference_column: str) -> None: ...
    @overload
    def __init__(self, column: Column, reference_table: str, reference_column: str, defer: bool) -> None: ...
    @overload
    def __init__(self, columns: pyrosetta.rosetta.utility.vector1_basic_database_schema_generator_Column, reference_table: str, reference_columns: pyrosetta.rosetta.utility.vector1_std_string, defer: bool) -> None: ...
    @overload
    def __init__(self, arg0: ForeignKey) -> None: ...
    def assign(self) -> ForeignKey: ...
    def columns(self) -> pyrosetta.rosetta.utility.vector1_basic_database_schema_generator_Column: ...
    def print(self) -> str: ...

class GreaterThanConstraint(Constraint):
    @overload
    def __init__(self, column: Column, value: float) -> None: ...
    @overload
    def __init__(self, arg0: GreaterThanConstraint) -> None: ...
    @overload
    def __init__(self, arg0: GreaterThanConstraint) -> None: ...
    def assign(self) -> GreaterThanConstraint: ...
    def print(self) -> str: ...

class Index:
    @overload
    def __init__(self, column: Column) -> None: ...
    @overload
    def __init__(self, column: Column, unique: bool) -> None: ...
    @overload
    def __init__(self, columns: pyrosetta.rosetta.utility.vector1_basic_database_schema_generator_Column) -> None: ...
    @overload
    def __init__(self, columns: pyrosetta.rosetta.utility.vector1_basic_database_schema_generator_Column, unique: bool) -> None: ...
    @overload
    def __init__(self, arg0: Index) -> None: ...
    def assign(self) -> Index: ...
    def columns(self) -> pyrosetta.rosetta.utility.vector1_basic_database_schema_generator_Column: ...
    def print(self, table_name: str, db_session) -> str: ...
    @overload
    def unique(self) -> bool: ...
    @overload
    def unique(self) -> bool: ...

class PrimaryKey:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, column: Column) -> None: ...
    @overload
    def __init__(self, columns: pyrosetta.rosetta.utility.vector1_basic_database_schema_generator_Column) -> None: ...
    @overload
    def __init__(self, arg0: PrimaryKey) -> None: ...
    @overload
    def add_column(self, column: Column) -> None: ...
    @overload
    def add_column(self, classbasic) -> void: ...
    def assign(self) -> PrimaryKey: ...
    def columns(self) -> pyrosetta.rosetta.utility.vector1_basic_database_schema_generator_Column: ...
    def print(self, db_session) -> str: ...

class Schema:
    @overload
    def __init__(self, table_name: str) -> None: ...
    @overload
    def __init__(self, table_name: str, primary_key: PrimaryKey) -> None: ...
    @overload
    def __init__(self, arg0: Schema) -> None: ...
    @overload
    def add_column(self, column: Column) -> None: ...
    @overload
    def add_column(self, classbasic) -> void: ...
    @overload
    def add_constraint(self, constraint: Constraint) -> None: ...
    @overload
    def add_constraint(self, classstd) -> void: ...
    @overload
    def add_foreign_key(self, key: ForeignKey) -> None: ...
    @overload
    def add_foreign_key(self, classbasic) -> void: ...
    @overload
    def add_index(self, index: Index) -> None: ...
    @overload
    def add_index(self, classbasic) -> void: ...
    def assign(self) -> Schema: ...
    def print(self, db_session) -> str: ...
    @overload
    def write(self, db_session) -> None: ...
    @overload
    def write(self, classstd) -> void: ...

class UniqueConstraint(Constraint):
    @overload
    def __init__(self, column: Column) -> None: ...
    @overload
    def __init__(self, columns: pyrosetta.rosetta.utility.vector1_basic_database_schema_generator_Column) -> None: ...
    @overload
    def __init__(self, arg0: UniqueConstraint) -> None: ...
    @overload
    def __init__(self, arg0: UniqueConstraint) -> None: ...
    def assign(self) -> UniqueConstraint: ...
    def print(self) -> str: ...
