from ._paml import Paml as Paml
from _typeshed import Incomplete

class BasemlError(EnvironmentError): ...

class Baseml(Paml):
    tree: Incomplete
    ctl_file: str
    def __init__(self, alignment=None, tree=None, working_dir=None, out_file=None) -> None: ...
    def write_ctl_file(self) -> None: ...
    alignment: Incomplete
    out_file: Incomplete
    def read_ctl_file(self, ctl_file) -> None: ...
    def run(self, ctl_file=None, verbose: bool = False, command: str = 'baseml', parse: bool = True): ...

def read(results_file): ...
