import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.io.silent
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.protocols.jd3
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.options
import pyrosetta.rosetta.utility.tag
from typing import overload

class PDBPoseInputter(PoseInputter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PDBPoseInputter) -> None: ...
    @overload
    def __init__(self, arg0: PDBPoseInputter) -> None: ...
    def assign(self) -> PDBPoseInputter: ...
    @overload
    def job_available_on_command_line(self) -> bool: ...
    @overload
    def job_available_on_command_line(self) -> bool: ...
    @staticmethod
    def keyname() -> str: ...
    @overload
    @staticmethod
    def list_options_read(read_options: pyrosetta.rosetta.std.list_utility_keys_VariantKey_utility_options_OptionKey_t) -> None: ...
    @overload
    @staticmethod
    def list_options_read(classstd) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def pose_from_input_source(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class PDBPoseInputterCreator(PoseInputterCreator):
    def __init__(self) -> None: ...
    def assign(self) -> PDBPoseInputterCreator: ...
    def create_inputter(self) -> PoseInputter: ...
    def keyname(self) -> str: ...
    @overload
    def list_options_read(self, read_options: pyrosetta.rosetta.std.list_utility_keys_VariantKey_utility_options_OptionKey_t) -> None: ...
    @overload
    def list_options_read(self, classstd) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class PoseInputSource(pyrosetta.rosetta.protocols.jd3.InputSource):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, origin: str) -> None: ...
    @overload
    def __init__(self, arg0: PoseInputSource) -> None: ...
    def assign(self) -> PoseInputSource: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def store_string_pair(self, key: str, value: str) -> None: ...
    def string_string_map(self) -> pyrosetta.rosetta.std.map_std_string_std_string: ...
    def __eq__(self, rhs: PoseInputSource) -> bool: ...
    def __ne__(self, rhs: PoseInputSource) -> bool: ...

class PoseInputter:
    def __init__(self, *args, **kwargs) -> None: ...
    def assign(self) -> PoseInputter: ...
    @overload
    def job_available_on_command_line(self) -> bool: ...
    @overload
    def job_available_on_command_line(self) -> bool: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def pose_from_input_source(self, input_source, options: pyrosetta.rosetta.utility.options.OptionCollection, tag: pyrosetta.rosetta.utility.tag.Tag) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class PoseInputterCreator:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PoseInputterCreator) -> None: ...
    def assign(self) -> PoseInputterCreator: ...
    def create_inputter(self) -> PoseInputter: ...
    def keyname(self) -> str: ...
    @overload
    def list_options_read(self, read_options: pyrosetta.rosetta.std.list_utility_keys_VariantKey_utility_options_OptionKey_t) -> None: ...
    @overload
    def list_options_read(self, classstd) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class PoseInputterFactory(pyrosetta.rosetta.utility.SingletonBase_protocols_jd3_pose_inputters_PoseInputterFactory_t):
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def complex_type_name_for_pose_inputter(inputter_key: str) -> str: ...
    @overload
    def define_pose_inputter_xml_schema(self, xsd) -> None: ...
    @overload
    def define_pose_inputter_xml_schema(self, classutility) -> void: ...
    @overload
    def factory_register(self, creator: PoseInputterCreator) -> None: ...
    @overload
    def factory_register(self, classstd) -> void: ...
    @overload
    def list_options_read(self, read_options: pyrosetta.rosetta.std.list_utility_keys_VariantKey_utility_options_OptionKey_t) -> None: ...
    @overload
    def list_options_read(self, classstd) -> void: ...
    def new_pose_inputter(self) -> PoseInputter: ...
    def pose_inputter_creators(self) -> pyrosetta.rosetta.std.list_std_shared_ptr_const_protocols_jd3_pose_inputters_PoseInputterCreator_t: ...
    @staticmethod
    def pose_inputter_xml_schema_group_name() -> str: ...
    @overload
    def set_throw_on_double_registration(self) -> None: ...
    @overload
    def set_throw_on_double_registration(self) -> void: ...

class SilentFilePoseInputter(PoseInputter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SilentFilePoseInputter) -> None: ...
    @overload
    def __init__(self, arg0: SilentFilePoseInputter) -> None: ...
    def assign(self) -> SilentFilePoseInputter: ...
    @overload
    def job_available_on_command_line(self) -> bool: ...
    @overload
    def job_available_on_command_line(self) -> bool: ...
    @staticmethod
    def keyname() -> str: ...
    @overload
    @staticmethod
    def list_options_read(read_options: pyrosetta.rosetta.std.list_utility_keys_VariantKey_utility_options_OptionKey_t) -> None: ...
    @overload
    @staticmethod
    def list_options_read(classstd) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def pose_from_input_source(self, input_source: PoseInputSource, options: pyrosetta.rosetta.utility.options.OptionCollection, tag: pyrosetta.rosetta.utility.tag.Tag) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def silent_file_data(self) -> pyrosetta.rosetta.core.io.silent.SilentFileData: ...

class SilentFilePoseInputterCreator(PoseInputterCreator):
    def __init__(self) -> None: ...
    def assign(self) -> SilentFilePoseInputterCreator: ...
    def create_inputter(self) -> PoseInputter: ...
    def keyname(self) -> str: ...
    @overload
    def list_options_read(self, read_options: pyrosetta.rosetta.std.list_utility_keys_VariantKey_utility_options_OptionKey_t) -> None: ...
    @overload
    def list_options_read(self, classstd) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

def pose_inputter_xsd_type_definition_w_attributes(xsd, inputter_type: str, description: str, attributes: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
