// Generated by symbols.js.py from rdkit 2026.03.5.

const bareAliphatic = ["B", "C", "N", "O", "F", "P", "S", "Cl", "Br", "I"];
const bareAromatic = ["b", "c", "n", "o", "p", "s"];
const bracketElement = ["H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne", "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar", "K", "Ca", "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr", "Rb", "Sr", "Y", "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te", "I", "Xe", "Cs", "Ba", "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu", "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra", "Ac", "Th", "Pa", "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr", "Rf", "Db", "Sg", "Bh", "Hs", "Mt", "Ds", "Rg", "Cn", "Fl", "Mc", "Lv", "Ts", "Og"];
const bracketAromatic = ["b", "c", "n", "o", "si", "p", "s", "as", "se", "te"];
const propertyPrimitives = ["d", "h", "k", "r", "v", "x", "z", "D", "R", "X", "Z"];
const propertyPrimitivesWithDigit = ["^"];

module.exports = { bareAliphatic, bareAromatic, bracketElement, bracketAromatic, propertyPrimitives, propertyPrimitivesWithDigit };
