import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.numeric.conversions
import pyrosetta.rosetta.protocols.canonical_sampling
import pyrosetta.rosetta.protocols.loop_modeling
import pyrosetta.rosetta.protocols.loops
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from . import perturbers as perturbers, pivot_pickers as pivot_pickers, solution_pickers as solution_pickers
from typing import overload

class BalancedKicMover(pyrosetta.rosetta.protocols.canonical_sampling.ThermodynamicMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: BalancedKicMover) -> None: ...
    @overload
    def __init__(self, arg0: BalancedKicMover) -> None: ...
    @overload
    def add_perturber(self, perturber) -> None: ...
    @overload
    def add_perturber(self, classstd) -> void: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> BalancedKicMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @staticmethod
    def complex_type_generator_for_balancedKIC_mover(*args, **kwargs): ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def is_solution_trivial(problem, solution, unperturbed_solutions: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_protocols_kinematic_closure_ClosureSolution_t, perturbed_solutions: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_protocols_kinematic_closure_ClosureSolution_t) -> bool: ...
    @overload
    def last_proposal_density_ratio(self) -> float: ...
    @overload
    def last_proposal_density_ratio(self) -> double: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @staticmethod
    def pick_solution(*args, **kwargs): ...
    @overload
    def preserve_detailed_balance(self) -> bool: ...
    @overload
    def preserve_detailed_balance(self) -> bool: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def residue_selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    def set_loop(self, loop: pyrosetta.rosetta.protocols.loops.Loop) -> None: ...
    @overload
    def set_loop(self, constclassprotocols) -> void: ...
    @overload
    def set_loops(self, loops: pyrosetta.rosetta.protocols.loops.Loops) -> None: ...
    @overload
    def set_loops(self, constclassstd) -> void: ...
    @overload
    def set_pivot_picker(self, picker) -> None: ...
    @overload
    def set_pivot_picker(self, classstd) -> void: ...
    @overload
    def set_preserve_detailed_balance(self) -> None: ...
    @overload
    def set_preserve_detailed_balance(self, bool) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    def torsion_id_ranges(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_core_id_TorsionID_Range: ...

class BalancedKicMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: BalancedKicMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: BalancedKicMoverCreator) -> None: ...
    def assign(self) -> BalancedKicMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ChainedSolutionList:
    class Iterator:
        def __init__(self, arg0: ChainedSolutionList.Iterator) -> None: ...
    def __init__(self, a: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_protocols_kinematic_closure_ClosureSolution_t, b: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_protocols_kinematic_closure_ClosureSolution_t) -> None: ...
    def back(self) -> ClosureSolution: ...
    def begin(self, *args, **kwargs): ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def end(self, *args, **kwargs): ...
    def front(self) -> ClosureSolution: ...
    @overload
    def not_empty(self) -> bool: ...
    @overload
    def not_empty(self) -> bool: ...
    @overload
    def size(self) -> bool: ...
    @overload
    def size(self) -> bool: ...

class ClosureProblem:
    class Memento:
        @overload
        def __init__(self, problem: ClosureProblem) -> None: ...
        @overload
        def __init__(self, arg0: ClosureProblem.Memento) -> None: ...
        @overload
        def restore(self) -> None: ...
        @overload
        def restore(self) -> void: ...
    def __init__(self) -> None: ...
    @overload
    def c_n(self, residue: int) -> float: ...
    @overload
    def c_n(self, unsignedlong) -> double: ...
    @overload
    def c_n_ca(self, residue: int, unit: pyrosetta.rosetta.numeric.conversions.AngleUnit) -> float: ...
    @overload
    def c_n_ca(self, unsignedlong, enumnumeric) -> double: ...
    @overload
    def ca_c(self, residue: int) -> float: ...
    @overload
    def ca_c(self, unsignedlong) -> double: ...
    @overload
    def ca_c_n(self, residue: int, unit: pyrosetta.rosetta.numeric.conversions.AngleUnit) -> float: ...
    @overload
    def ca_c_n(self, unsignedlong, enumnumeric) -> double: ...
    @overload
    def cut_residue(self) -> int: ...
    @overload
    def cut_residue(self) -> unsignedlong: ...
    @overload
    def first_residue(self) -> int: ...
    @overload
    def first_residue(self) -> unsignedlong: ...
    @overload
    def frame(self, pose: pyrosetta.rosetta.core.pose.Pose, loop: pyrosetta.rosetta.protocols.loops.Loop, pivot_picker) -> None: ...
    @overload
    def frame(self, constclasscore, constclassprotocols, classstd) -> void: ...
    @overload
    def is_nonpivot_residue(self, residue: int) -> bool: ...
    @overload
    def is_nonpivot_residue(self, unsignedlong) -> bool: ...
    @overload
    def is_pivot_residue(self, residue: int) -> bool: ...
    @overload
    def is_pivot_residue(self, unsignedlong) -> bool: ...
    @overload
    def last_residue(self) -> int: ...
    @overload
    def last_residue(self) -> unsignedlong: ...
    @overload
    def n_ca(self, residue: int) -> float: ...
    @overload
    def n_ca(self, unsignedlong) -> double: ...
    @overload
    def n_ca_c(self, residue: int, unit: pyrosetta.rosetta.numeric.conversions.AngleUnit) -> float: ...
    @overload
    def n_ca_c(self, unsignedlong, enumnumeric) -> double: ...
    def nonpivot_residues(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def num_atoms(self) -> int: ...
    @overload
    def num_atoms(self) -> unsignedlong: ...
    @overload
    def num_residues(self) -> int: ...
    @overload
    def num_residues(self) -> unsignedlong: ...
    @overload
    def omega(self, residue: int, unit: pyrosetta.rosetta.numeric.conversions.AngleUnit) -> float: ...
    @overload
    def omega(self, unsignedlong, enumnumeric) -> double: ...
    def perturb_angles(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def perturb_c_n(self, residue: int, value: float) -> None: ...
    @overload
    def perturb_c_n(self, unsignedlong, double) -> void: ...
    @overload
    def perturb_c_n_ca(self, residue: int, value: float, unit: pyrosetta.rosetta.numeric.conversions.AngleUnit) -> None: ...
    @overload
    def perturb_c_n_ca(self, unsignedlong, double, enumnumeric) -> void: ...
    @overload
    def perturb_ca_c(self, residue: int, value: float) -> None: ...
    @overload
    def perturb_ca_c(self, unsignedlong, double) -> void: ...
    @overload
    def perturb_ca_c_n(self, residue: int, value: float, unit: pyrosetta.rosetta.numeric.conversions.AngleUnit) -> None: ...
    @overload
    def perturb_ca_c_n(self, unsignedlong, double, enumnumeric) -> void: ...
    def perturb_lengths(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def perturb_n_ca(self, residue: int, value: float) -> None: ...
    @overload
    def perturb_n_ca(self, unsignedlong, double) -> void: ...
    @overload
    def perturb_n_ca_c(self, residue: int, value: float, unit: pyrosetta.rosetta.numeric.conversions.AngleUnit) -> None: ...
    @overload
    def perturb_n_ca_c(self, unsignedlong, double, enumnumeric) -> void: ...
    @overload
    def perturb_omega(self, residue: int, value: float, unit: pyrosetta.rosetta.numeric.conversions.AngleUnit) -> None: ...
    @overload
    def perturb_omega(self, unsignedlong, double, enumnumeric) -> void: ...
    @overload
    def perturb_phi(self, residue: int, value: float, unit: pyrosetta.rosetta.numeric.conversions.AngleUnit) -> None: ...
    @overload
    def perturb_phi(self, unsignedlong, double, enumnumeric) -> void: ...
    @overload
    def perturb_psi(self, residue: int, value: float, unit: pyrosetta.rosetta.numeric.conversions.AngleUnit) -> None: ...
    @overload
    def perturb_psi(self, unsignedlong, double, enumnumeric) -> void: ...
    def perturb_torsions(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def perturbed_sequence(self, values: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def perturbed_sequence(self, constclassutility) -> void: ...
    @overload
    def perturbed_sequence(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def phi(self, residue: int, unit: pyrosetta.rosetta.numeric.conversions.AngleUnit) -> float: ...
    @overload
    def phi(self, unsignedlong, enumnumeric) -> double: ...
    def pivot_atoms(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def pivot_loop(self) -> pyrosetta.rosetta.protocols.loops.Loop: ...
    def pivot_residues(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def psi(self, residue: int, unit: pyrosetta.rosetta.numeric.conversions.AngleUnit) -> float: ...
    @overload
    def psi(self, unsignedlong, enumnumeric) -> double: ...
    def residues(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def restore(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def restore(self, classcore) -> void: ...
    @overload
    def sequence_mutated(self) -> bool: ...
    @overload
    def sequence_mutated(self) -> bool: ...
    def solve(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_protocols_kinematic_closure_ClosureSolution_t: ...
    def unperturbed_sequence(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...

class ClosureSolution:
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    @overload
    def apply_if_reasonable(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def apply_if_reasonable(self, pose: pyrosetta.rosetta.core.pose.Pose, rama_on: bool) -> bool: ...
    @overload
    def apply_if_reasonable(self, pose: pyrosetta.rosetta.core.pose.Pose, rama_on: bool, bump_on: bool) -> bool: ...
    @overload
    def apply_if_reasonable(self, pose: pyrosetta.rosetta.core.pose.Pose, rama_on: bool, bump_on: bool, be_lenient: bool) -> bool: ...
    @overload
    def get_distance(self, problem: ClosureProblem) -> float: ...
    @overload
    def get_distance(self, constclassprotocols) -> double: ...
    @overload
    def get_index(self) -> int: ...
    @overload
    def get_index(self) -> unsignedlong: ...
    @overload
    def get_jacobian(self) -> float: ...
    @overload
    def get_jacobian(self) -> double: ...

class IdealParameters:
    def __init__(self) -> None: ...

class KicMover(pyrosetta.rosetta.protocols.loop_modeling.LoopMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: KicMover) -> None: ...
    @overload
    def __init__(self, arg0: KicMover) -> None: ...
    @overload
    def add_perturber(self, perturber) -> None: ...
    @overload
    def add_perturber(self, classstd) -> void: ...
    def assign(self) -> KicMover: ...
    @overload
    def clear_perturbers(self) -> None: ...
    @overload
    def clear_perturbers(self) -> void: ...
    @overload
    def get_children_names(self, names: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def get_children_names(self, names: pyrosetta.rosetta.utility.vector1_std_string, indent: str) -> None: ...
    @overload
    def get_children_names(self, classutility, std) -> void: ...
    def get_name(self) -> str: ...
    def get_pivot_picker(self, *args, **kwargs): ...
    def get_solution_picker(self, *args, **kwargs): ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def request_fold_tree(self) -> pyrosetta.rosetta.protocols.loop_modeling.FoldTreeRequest: ...
    @overload
    def set_pivot_picker(self, picker) -> None: ...
    @overload
    def set_pivot_picker(self, classstd) -> void: ...
    @overload
    def set_solution_picker(self, picker) -> None: ...
    @overload
    def set_solution_picker(self, classstd) -> void: ...

class KicMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: KicMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: KicMoverCreator) -> None: ...
    def assign(self) -> KicMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
