import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.conformation.parametric
import pyrosetta.rosetta.std
from typing import Any, overload

class BundleParameters(pyrosetta.rosetta.core.conformation.parametric.Parameters):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: BundleParameters) -> None: ...
    @overload
    def __init__(self, arg0: BundleParameters) -> None: ...
    def assign(self) -> BundleParameters: ...
    def clone(self) -> pyrosetta.rosetta.core.conformation.parametric.Parameters: ...
    @overload
    def get_pdb_remark(self, remark: pyrosetta.rosetta.std.stringstream) -> None: ...
    @overload
    def get_pdb_remark(self, std) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class BundleParametersSet(pyrosetta.rosetta.core.conformation.parametric.ParametersSet):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: BundleParametersSet) -> None: ...
    @overload
    def __init__(self, arg0: BundleParametersSet) -> None: ...
    def assign(self) -> BundleParametersSet: ...
    @overload
    def bundle_symmetry(self) -> int: ...
    @overload
    def bundle_symmetry(self) -> unsignedlong: ...
    @overload
    def bundle_symmetry_copies(self) -> int: ...
    @overload
    def bundle_symmetry_copies(self) -> unsignedlong: ...
    def clone(self) -> pyrosetta.rosetta.core.conformation.parametric.ParametersSet: ...
    @overload
    def get_pdb_remark(self, remark: pyrosetta.rosetta.std.stringstream) -> None: ...
    @overload
    def get_pdb_remark(self, std) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def n_helices(self) -> int: ...
    @overload
    def n_helices(self) -> unsignedlong: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_bundle_symmetry(self, val: int) -> None: ...
    @overload
    def set_bundle_symmetry(self, constunsignedlong) -> void: ...
    @overload
    def set_bundle_symmetry_copies(self, val: int) -> None: ...
    @overload
    def set_bundle_symmetry_copies(self, constunsignedlong) -> void: ...
    @overload
    def set_n_helices(self, val: int) -> None: ...
    @overload
    def set_n_helices(self, constunsignedlong) -> void: ...

class OmegaBundleParameter(pyrosetta.rosetta.core.conformation.parametric.RealValuedParameter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: OmegaBundleParameter) -> None: ...
    @overload
    def __init__(self, arg0: OmegaBundleParameter) -> None: ...
    def assign(self) -> OmegaBundleParameter: ...
    def clone(self) -> pyrosetta.rosetta.core.conformation.parametric.Parameter: ...
    @overload
    def copies_pitch(self) -> bool: ...
    @overload
    def copies_pitch(self) -> bool: ...
    def copy_value_from_parameter(self, other_parameter: pyrosetta.rosetta.core.conformation.parametric.Parameter, other_parameter_collection: pyrosetta.rosetta.core.conformation.parametric.Parameters, this_parameter_collection: pyrosetta.rosetta.core.conformation.parametric.Parameters) -> bool: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def provide_xsd_information(self, xsd: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t, provide_setting: bool, provide_copying: bool, provide_grid_sampling: bool, provide_perturbation: bool) -> None: ...
    @overload
    def reset_copying_settings(self) -> None: ...
    @overload
    def reset_copying_settings(self) -> Any: ...
    @overload
    def reset_copying_settings(self) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_copies_pitch(self, setting: bool) -> None: ...
    @overload
    def set_copies_pitch(self, constbool) -> void: ...
