from _typeshed import Incomplete

class TimeDelayEmbedding:
    def __init__(self, dim: int = ..., delay: int = ..., skip: int = ...) -> None: ...
    def __call__(self, ts): ...
    def fit(self, ts, y: Incomplete | None = ...): ...
    def transform(self, ts): ...
