import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.scoring.constraints
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import ClassVar, overload

tf_constant: TailFunction
tf_end_of_list: TailFunction
tf_linear: TailFunction
tf_quadratic: TailFunction
tf_unknown: TailFunction

class AACompositionConstraint(SequenceConstraint):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AACompositionConstraint) -> None: ...
    @overload
    def __init__(self, arg0: AACompositionConstraint) -> None: ...
    def aa_composition_energy_setup(self) -> AACompositionEnergySetup: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    @overload
    def initialize_from_file(self, filename: str) -> None: ...
    @overload
    def initialize_from_file(self, conststd) -> void: ...
    @overload
    def initialize_from_file_contents(self, filecontents: str) -> None: ...
    @overload
    def initialize_from_file_contents(self, conststd) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.constraints.Constraint) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    def set_selector(self, selector_in: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_selector(self, classstd) -> void: ...
    @overload
    def show_def(self, TO: pyrosetta.rosetta.std.ostream, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def show_def(self, std, constclasscore) -> void: ...
    def __eq__(self) -> bool: ...

class AACompositionEnergySetup:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AACompositionEnergySetup) -> None: ...
    @overload
    def __init__(self, arg0: AACompositionEnergySetup) -> None: ...
    def assign(self) -> AACompositionEnergySetup: ...
    def clone(self) -> AACompositionEnergySetup: ...
    @overload
    def expected_by_properties_absolute(self, index: int) -> int: ...
    @overload
    def expected_by_properties_absolute(self, constunsignedlong) -> long: ...
    @overload
    def expected_by_properties_fraction(self, index: int) -> float: ...
    @overload
    def expected_by_properties_fraction(self, constunsignedlong) -> double: ...
    @overload
    def fract_property_penalty(self, delta_fract: float, property_set_index: int) -> float: ...
    @overload
    def fract_property_penalty(self, constdouble, constunsignedlong) -> double: ...
    def get_tailfunction_from_name(self, name: str) -> TailFunction: ...
    def get_tailfunction_name(self, tf: TailFunction) -> str: ...
    @overload
    def initialize_from_file(self, filename: str) -> None: ...
    @overload
    def initialize_from_file(self, conststd) -> void: ...
    @overload
    def initialize_from_file_contents(self, filecontents: str) -> None: ...
    @overload
    def initialize_from_file_contents(self, conststd) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def n_property_sets(self) -> int: ...
    @overload
    def n_property_sets(self) -> unsignedlong: ...
    @overload
    def property_penalty(self, delta_expected: int, property_set_index: int) -> float: ...
    @overload
    def property_penalty(self, constlong, constunsignedlong) -> double: ...
    @overload
    def property_set_indices_matching_residue(self, rsd_type: pyrosetta.rosetta.core.chemical.ResidueType, indices_out: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def property_set_indices_matching_residue(self, constclasscore, classutility) -> void: ...
    def report(self) -> str: ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def use_fract_expected_values_any(self) -> bool: ...
    @overload
    def use_fract_expected_values_any(self) -> bool: ...
    @overload
    def use_fract_ranges(self, index: int) -> bool: ...
    @overload
    def use_fract_ranges(self, constunsignedlong) -> bool: ...
    @overload
    def use_fract_ranges_any(self) -> bool: ...
    @overload
    def use_fract_ranges_any(self) -> bool: ...

class AACompositionPropertiesSet:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, included_type_strings: pyrosetta.rosetta.utility.vector1_std_string, excluded_type_strings: pyrosetta.rosetta.utility.vector1_std_string, included_properties_strings: pyrosetta.rosetta.utility.vector1_std_string, or_properties_strings: pyrosetta.rosetta.utility.vector1_std_string, excluded_properties_strings: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def __init__(self, arg0: AACompositionPropertiesSet) -> None: ...
    @overload
    def __init__(self, arg0: AACompositionPropertiesSet) -> None: ...
    def assign(self) -> AACompositionPropertiesSet: ...
    def clone(self) -> AACompositionPropertiesSet: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def one_line_report(self) -> str: ...
    @overload
    def parse_excluded_properites(self, proplist: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def parse_excluded_properites(self, constclassutility) -> void: ...
    @overload
    def parse_excluded_types(self, typelist: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def parse_excluded_types(self, constclassutility) -> void: ...
    @overload
    def parse_included_properites(self, proplist: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def parse_included_properites(self, constclassutility) -> void: ...
    @overload
    def parse_included_types(self, typelist: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def parse_included_types(self, constclassutility) -> void: ...
    @overload
    def parse_or_properties(self, proplist: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def parse_or_properties(self, constclassutility) -> void: ...
    @overload
    def properties_match_this(self, rsd_type: pyrosetta.rosetta.core.chemical.ResidueType) -> bool: ...
    @overload
    def properties_match_this(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class SequenceConstraint(pyrosetta.rosetta.core.scoring.constraints.Constraint):
    @overload
    def __init__(self, t: pyrosetta.rosetta.core.scoring.ScoreType) -> None: ...
    @overload
    def __init__(self, arg0: SequenceConstraint) -> None: ...
    def atom(self) -> pyrosetta.rosetta.core.id.AtomID: ...
    @overload
    def dist(self) -> float: ...
    @overload
    def dist(self) -> float: ...
    @overload
    def dist(self, constclasscore) -> double: ...
    def fill_f1_f2(self) -> None: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def natoms(self) -> int: ...
    @overload
    def natoms(self) -> unsignedlong: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def score(self, pose: pyrosetta.rosetta.core.pose.Pose, weights: pyrosetta.rosetta.core.scoring.EMapVector) -> float: ...
    @overload
    def score(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def score(self) -> None: ...

class TailFunction:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    tf_constant: ClassVar[TailFunction] = ...
    tf_end_of_list: ClassVar[TailFunction] = ...
    tf_linear: ClassVar[TailFunction] = ...
    tf_quadratic: ClassVar[TailFunction] = ...
    tf_unknown: ClassVar[TailFunction] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
