import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.scoring.func
import pyrosetta.rosetta.core.scoring.methods
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from _typeshed import Incomplete
from typing import overload

class AtomPairFuncList:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AtomPairFuncList) -> None: ...
    @overload
    def add_interaction(self, interacting_pair: atoms_and_func_struct) -> None: ...
    @overload
    def add_interaction(self, conststructcore) -> void: ...
    def assign(self) -> AtomPairFuncList: ...
    def ats_n_func_list(self) -> pyrosetta.rosetta.std.list_core_scoring_custom_pair_distance_atoms_and_func_struct_t: ...

class DistanceFunc(pyrosetta.rosetta.core.scoring.func.Func):
    @overload
    def __init__(self, name: str) -> None: ...
    @overload
    def __init__(self, arg0: DistanceFunc) -> None: ...
    @overload
    def __init__(self, arg0: DistanceFunc) -> None: ...
    def assign(self) -> DistanceFunc: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.func.Func: ...
    @overload
    def dfunc(self) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def max_dis(self) -> float: ...
    @overload
    def max_dis(self) -> double: ...
    @overload
    def min_dis(self) -> float: ...
    @overload
    def min_dis(self) -> double: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def __eq__(self, rhs: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...

class FullatomCustomPairDistanceEnergy(pyrosetta.rosetta.core.scoring.methods.ContextIndependentTwoBodyEnergy):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FullatomCustomPairDistanceEnergy) -> None: ...
    @overload
    def __init__(self, arg0: FullatomCustomPairDistanceEnergy) -> None: ...
    def assign(self) -> FullatomCustomPairDistanceEnergy: ...
    @overload
    def atomic_interaction_cutoff(self) -> float: ...
    @overload
    def atomic_interaction_cutoff(self) -> double: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    @overload
    def defines_intrares_energy(self) -> bool: ...
    @overload
    def defines_intrares_energy(self, constclasscore) -> bool: ...
    def defines_score_for_residue_pair(self, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, res_moving_wrt_eachother: bool) -> bool: ...
    def eval_intrares_energy(self) -> None: ...
    def eval_residue_pair_derivatives(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, min_data: pyrosetta.rosetta.core.scoring.ResPairMinimizationData, pose: pyrosetta.rosetta.core.pose.Pose, weights: pyrosetta.rosetta.core.scoring.EMapVector, r1_atom_derivs: pyrosetta.rosetta.utility.vector1_core_scoring_DerivVectorPair, r2_atom_derivs: pyrosetta.rosetta.utility.vector1_core_scoring_DerivVectorPair) -> None: ...
    @overload
    def indicate_required_context_graphs(self) -> None: ...
    @overload
    def indicate_required_context_graphs(self, classutility) -> void: ...
    @overload
    def minimize_in_whole_structure_context(self) -> bool: ...
    @overload
    def minimize_in_whole_structure_context(self, constclasscore) -> bool: ...
    def residue_pair_energy(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, pose: pyrosetta.rosetta.core.pose.Pose, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    def residue_pair_energy_ext(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, min_data: pyrosetta.rosetta.core.scoring.ResPairMinimizationData, pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    def setup_for_minimizing_for_residue_pair(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, minmap: pyrosetta.rosetta.core.kinematics.MinimizerMapBase, res1_data_cache: pyrosetta.rosetta.core.scoring.ResSingleMinimizationData, res2_data_cache: pyrosetta.rosetta.core.scoring.ResSingleMinimizationData, data_cache: pyrosetta.rosetta.core.scoring.ResPairMinimizationData) -> None: ...
    @overload
    def use_extended_residue_pair_energy_interface(self) -> bool: ...
    @overload
    def use_extended_residue_pair_energy_interface(self) -> bool: ...

class FullatomCustomPairDistanceEnergyCreator(pyrosetta.rosetta.core.scoring.methods.EnergyMethodCreator):
    def __init__(self) -> None: ...
    def assign(self) -> FullatomCustomPairDistanceEnergyCreator: ...
    def create_energy_method(self) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    def score_types_for_method(self) -> pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType: ...

class PairFuncMap:
    def __init__(self) -> None: ...
    @overload
    def get_atom_pair_func_list(self, rsdtype1: pyrosetta.rosetta.core.chemical.ResidueType, rsdtype2: pyrosetta.rosetta.core.chemical.ResidueType) -> AtomPairFuncList: ...
    @overload
    def get_atom_pair_func_list(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue) -> AtomPairFuncList: ...
    @overload
    def restype_destruction_observer(self, event: pyrosetta.rosetta.core.chemical.RestypeDestructionEvent) -> None: ...
    @overload
    def restype_destruction_observer(self, conststructcore) -> void: ...
    def set_atom_pair_func(self, rsdtype1: pyrosetta.rosetta.core.chemical.ResidueType, rsdtype2: pyrosetta.rosetta.core.chemical.ResidueType, func_list: AtomPairFuncList) -> None: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...

class atoms_and_func_struct:
    func_: Incomplete
    resA_atom_index_: int
    resB_atom_index_: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: atoms_and_func_struct) -> None: ...
    def assign(self) -> atoms_and_func_struct: ...

class resatom_and_func_struct:
    atom_index_: int
    func_: Incomplete
    res_index_: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: resatom_and_func_struct) -> None: ...
    def assign(self) -> resatom_and_func_struct: ...
