import pyrosetta.rosetta.ObjexxFCL
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.scoring.func
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.utility
from typing import ClassVar, overload

CYS_CEN: DisulfideDerivativeAtom
CYS_C_ALPHA: DisulfideDerivativeAtom
CYS_C_BETA: DisulfideDerivativeAtom
CYS_S_GAMMA: DisulfideDerivativeAtom
NO_DERIVATIVES_FOR_ATOM: DisulfideDerivativeAtom

class CBSG_Dihedral_Func(pyrosetta.rosetta.core.scoring.func.Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CBSG_Dihedral_Func) -> None: ...
    @overload
    def __init__(self, arg0: CBSG_Dihedral_Func) -> None: ...
    def assign(self) -> CBSG_Dihedral_Func: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.func.Func: ...
    @overload
    def dfunc(self) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...

class CB_Angle_Func(pyrosetta.rosetta.core.scoring.func.Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CB_Angle_Func) -> None: ...
    @overload
    def __init__(self, arg0: CB_Angle_Func) -> None: ...
    def assign(self) -> CB_Angle_Func: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.func.Func: ...
    @overload
    def dfunc(self) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...

class CaCbCbCa_Dihedral_Func(pyrosetta.rosetta.core.scoring.func.Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CaCbCbCa_Dihedral_Func) -> None: ...
    @overload
    def __init__(self, arg0: CaCbCbCa_Dihedral_Func) -> None: ...
    def assign(self) -> CaCbCbCa_Dihedral_Func: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.func.Func: ...
    @overload
    def dfunc(self) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...

class CaCbCb_Angle_Func(pyrosetta.rosetta.core.scoring.func.Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CaCbCb_Angle_Func) -> None: ...
    @overload
    def __init__(self, arg0: CaCbCb_Angle_Func) -> None: ...
    def assign(self) -> CaCbCb_Angle_Func: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.func.Func: ...
    @overload
    def dfunc(self) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...

class Cb_Distance_Func(pyrosetta.rosetta.core.scoring.func.Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Cb_Distance_Func) -> None: ...
    @overload
    def __init__(self, arg0: Cb_Distance_Func) -> None: ...
    def assign(self) -> Cb_Distance_Func: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.func.Func: ...
    @overload
    def dfunc(self) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...

class Cen_Distance_Func(pyrosetta.rosetta.core.scoring.func.Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Cen_Distance_Func) -> None: ...
    @overload
    def __init__(self, arg0: Cen_Distance_Func) -> None: ...
    def assign(self) -> Cen_Distance_Func: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.func.Func: ...
    @overload
    def dfunc(self) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...

class CentroidDisulfideEnergyComponents:
    def __init__(self) -> None: ...
    def dslfc_ang(self) -> float: ...
    def dslfc_bb_dih(self) -> float: ...
    def dslfc_cb_dih(self) -> float: ...
    def dslfc_cb_dst(self) -> float: ...
    def dslfc_cen_dst(self) -> float: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class CentroidDisulfideEnergyContainer(pyrosetta.rosetta.core.scoring.LREnergyContainer):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CentroidDisulfideEnergyContainer) -> None: ...
    @overload
    def __init__(self, arg0: CentroidDisulfideEnergyContainer) -> None: ...
    @overload
    def accumulate_energy(self, disulfide_index: int, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def accumulate_energy(self, unsignedlong, classcore) -> void: ...
    @overload
    def any_neighbors_for_residue(self, resid: int) -> bool: ...
    @overload
    def any_neighbors_for_residue(self, int) -> bool: ...
    @overload
    def any_upper_neighbors_for_residue(self, resid: int) -> bool: ...
    @overload
    def any_upper_neighbors_for_residue(self, int) -> bool: ...
    def assign(self) -> CentroidDisulfideEnergyContainer: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.LREnergyContainer: ...
    def const_neighbor_iterator_begin(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    def const_neighbor_iterator_end(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    def const_upper_neighbor_iterator_begin(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    def const_upper_neighbor_iterator_end(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    def disulfide_atom_indices(self, *args, **kwargs): ...
    def disulfide_bonded(self, res1id: int, res2id: int) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def energy_computed(self, disulfide_index: int) -> bool: ...
    @overload
    def energy_computed(self, unsignedlong) -> bool: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def lower_neighbor_id(self, disulfide_index: int) -> int: ...
    @overload
    def lower_neighbor_id(self, unsignedlong) -> unsignedlong: ...
    @overload
    def mark_energy_computed(self, disulfide_index: int) -> None: ...
    @overload
    def mark_energy_computed(self, unsignedlong) -> void: ...
    @overload
    def mark_energy_uncomputed(self, disulfide_index: int) -> None: ...
    @overload
    def mark_energy_uncomputed(self, unsignedlong) -> void: ...
    def neighbor_iterator_begin(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    def neighbor_iterator_end(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    def other_neighbor_atom_indices(self, *args, **kwargs): ...
    @overload
    def other_neighbor_id(self, resid: int) -> int: ...
    @overload
    def other_neighbor_id(self, unsignedlong) -> unsignedlong: ...
    @overload
    def other_neighbor_id(self, disulfide_index: int, resid: int) -> int: ...
    @overload
    def residue_forms_disulfide(self, resid: int) -> bool: ...
    @overload
    def residue_forms_disulfide(self, unsignedlong) -> bool: ...
    @overload
    def retrieve_energy(self, disulfide_index: int, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def retrieve_energy(self, unsignedlong, classcore) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def save_energy(self, disulfide_index: int, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def save_energy(self, unsignedlong, constclasscore) -> void: ...
    @overload
    def update(self) -> None: ...
    @overload
    def update(self, constclasscore) -> void: ...
    @overload
    def upper_neighbor_id(self, disulfide_index: int) -> int: ...
    @overload
    def upper_neighbor_id(self, unsignedlong) -> unsignedlong: ...
    def upper_neighbor_iterator_begin(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    def upper_neighbor_iterator_end(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...

class CentroidDisulfideNeighborConstIterator(pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator):
    @overload
    def __init__(self, owner, focused_node: int, disulfide_index: int) -> None: ...
    @overload
    def __init__(self, owner) -> None: ...
    @overload
    def __init__(self, arg0: CentroidDisulfideNeighborConstIterator) -> None: ...
    @overload
    def __init__(self, arg0: CentroidDisulfideNeighborConstIterator) -> None: ...
    @overload
    def accumulate_energy(self) -> None: ...
    @overload
    def accumulate_energy(self, classcore) -> void: ...
    def assign(self) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    @overload
    def energy_computed(self) -> bool: ...
    @overload
    def energy_computed(self) -> bool: ...
    @overload
    def lower_neighbor_id(self) -> int: ...
    @overload
    def lower_neighbor_id(self) -> unsignedlong: ...
    @overload
    def neighbor_id(self) -> int: ...
    @overload
    def neighbor_id(self) -> unsignedlong: ...
    def pre_increment(self) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    @overload
    def residue_iterated_on(self) -> int: ...
    @overload
    def residue_iterated_on(self) -> unsignedlong: ...
    @overload
    def retrieve_energy(self) -> None: ...
    @overload
    def retrieve_energy(self, classcore) -> void: ...
    @overload
    def upper_neighbor_id(self) -> int: ...
    @overload
    def upper_neighbor_id(self) -> unsignedlong: ...
    def __eq__(self) -> bool: ...
    def __ne__(self) -> bool: ...

class CentroidDisulfideNeighborIterator(pyrosetta.rosetta.core.scoring.ResidueNeighborIterator):
    @overload
    def __init__(self, owner, focused_node: int, disulfide_index: int) -> None: ...
    @overload
    def __init__(self, owner) -> None: ...
    @overload
    def __init__(self, arg0: CentroidDisulfideNeighborIterator) -> None: ...
    @overload
    def __init__(self, arg0: CentroidDisulfideNeighborIterator) -> None: ...
    @overload
    def accumulate_energy(self) -> None: ...
    @overload
    def accumulate_energy(self, classcore) -> void: ...
    def assign(self) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    @overload
    def energy_computed(self) -> bool: ...
    @overload
    def energy_computed(self) -> bool: ...
    @overload
    def lower_neighbor_id(self) -> int: ...
    @overload
    def lower_neighbor_id(self) -> unsignedlong: ...
    @overload
    def mark_energy_computed(self) -> None: ...
    @overload
    def mark_energy_computed(self) -> void: ...
    @overload
    def mark_energy_uncomputed(self) -> None: ...
    @overload
    def mark_energy_uncomputed(self) -> void: ...
    @overload
    def neighbor_id(self) -> int: ...
    @overload
    def neighbor_id(self) -> unsignedlong: ...
    def pre_increment(self) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    @overload
    def residue_iterated_on(self) -> int: ...
    @overload
    def residue_iterated_on(self) -> unsignedlong: ...
    @overload
    def retrieve_energy(self) -> None: ...
    @overload
    def retrieve_energy(self, classcore) -> void: ...
    @overload
    def save_energy(self) -> None: ...
    @overload
    def save_energy(self, constclasscore) -> void: ...
    @overload
    def upper_neighbor_id(self) -> int: ...
    @overload
    def upper_neighbor_id(self) -> unsignedlong: ...
    def __eq__(self) -> bool: ...
    def __ne__(self) -> bool: ...

class CentroidDisulfidePotential:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CentroidDisulfidePotential) -> None: ...
    def assign(self) -> CentroidDisulfidePotential: ...
    def is_disulfide(self, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    @overload
    def score_disulfide(self, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, cbcb_distance_score: float, centroid_distance_score: float, cacbcb_angle_1_score: float, cacbcb_angle_2_score: float, cacbcbca_dihedral_score: float, backbone_dihedral_score: float) -> None: ...
    @overload
    def score_disulfide(self, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, cbcb_distance_sq: float, centroid_distance_sq: float, cacbcb_angle_1: float, cacbcb_angle_2: float, cacbcbca_dihedral: float, backbone_dihedral: float, cbcb_distance_score: float, centroid_distance_score: float, cacbcb_angle_1_score: float, cacbcb_angle_2_score: float, cacbcbca_dihedral_score: float, backbone_dihedral_score: float, cb_score_factor: float) -> None: ...

class DisulfResNeighbConstIterator(pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator):
    @overload
    def __init__(self, owner, focused_node: int, disulfide_index: int) -> None: ...
    @overload
    def __init__(self, owner) -> None: ...
    @overload
    def __init__(self, arg0: DisulfResNeighbConstIterator) -> None: ...
    @overload
    def __init__(self, arg0: DisulfResNeighbConstIterator) -> None: ...
    @overload
    def accumulate_energy(self) -> None: ...
    @overload
    def accumulate_energy(self, classcore) -> void: ...
    def assign(self) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    @overload
    def energy_computed(self) -> bool: ...
    @overload
    def energy_computed(self) -> bool: ...
    @overload
    def lower_neighbor_id(self) -> int: ...
    @overload
    def lower_neighbor_id(self) -> unsignedlong: ...
    @overload
    def neighbor_id(self) -> int: ...
    @overload
    def neighbor_id(self) -> unsignedlong: ...
    def pre_increment(self) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    @overload
    def residue_iterated_on(self) -> int: ...
    @overload
    def residue_iterated_on(self) -> unsignedlong: ...
    @overload
    def retrieve_energy(self) -> None: ...
    @overload
    def retrieve_energy(self, classcore) -> void: ...
    @overload
    def upper_neighbor_id(self) -> int: ...
    @overload
    def upper_neighbor_id(self) -> unsignedlong: ...
    def __eq__(self) -> bool: ...
    def __ne__(self) -> bool: ...

class DisulfResNeighbIterator(pyrosetta.rosetta.core.scoring.ResidueNeighborIterator):
    @overload
    def __init__(self, owner, focused_node: int, disulfide_index: int) -> None: ...
    @overload
    def __init__(self, owner) -> None: ...
    @overload
    def __init__(self, arg0: DisulfResNeighbIterator) -> None: ...
    @overload
    def __init__(self, arg0: DisulfResNeighbIterator) -> None: ...
    @overload
    def accumulate_energy(self) -> None: ...
    @overload
    def accumulate_energy(self, classcore) -> void: ...
    def assign(self) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    @overload
    def energy_computed(self) -> bool: ...
    @overload
    def energy_computed(self) -> bool: ...
    @overload
    def lower_neighbor_id(self) -> int: ...
    @overload
    def lower_neighbor_id(self) -> unsignedlong: ...
    @overload
    def mark_energy_computed(self) -> None: ...
    @overload
    def mark_energy_computed(self) -> void: ...
    @overload
    def mark_energy_uncomputed(self) -> None: ...
    @overload
    def mark_energy_uncomputed(self) -> void: ...
    @overload
    def neighbor_id(self) -> int: ...
    @overload
    def neighbor_id(self) -> unsignedlong: ...
    def pre_increment(self) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    @overload
    def residue_iterated_on(self) -> int: ...
    @overload
    def residue_iterated_on(self) -> unsignedlong: ...
    @overload
    def retrieve_energy(self) -> None: ...
    @overload
    def retrieve_energy(self, classcore) -> void: ...
    @overload
    def save_energy(self) -> None: ...
    @overload
    def save_energy(self, constclasscore) -> void: ...
    @overload
    def upper_neighbor_id(self) -> int: ...
    @overload
    def upper_neighbor_id(self) -> unsignedlong: ...
    def __eq__(self) -> bool: ...
    def __ne__(self) -> bool: ...

class DisulfideAtomIndices:
    @overload
    def __init__(self, res: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DisulfideAtomIndices) -> None: ...
    def assign(self) -> DisulfideAtomIndices: ...
    @overload
    def atom_gets_derivatives(self, atom_index: int) -> bool: ...
    @overload
    def atom_gets_derivatives(self, unsignedlong) -> bool: ...
    @overload
    def c_alpha_index(self) -> int: ...
    @overload
    def c_alpha_index(self) -> unsignedlong: ...
    @overload
    def c_beta_index(self) -> int: ...
    @overload
    def c_beta_index(self) -> unsignedlong: ...
    def derivative_atom(self, atom_index: int) -> DisulfideDerivativeAtom: ...
    @overload
    def disulf_atom_index(self) -> int: ...
    @overload
    def disulf_atom_index(self) -> unsignedlong: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class DisulfideDerivativeAtom:
    __members__: ClassVar[dict] = ...  # read-only
    CYS_CEN: ClassVar[DisulfideDerivativeAtom] = ...
    CYS_C_ALPHA: ClassVar[DisulfideDerivativeAtom] = ...
    CYS_C_BETA: ClassVar[DisulfideDerivativeAtom] = ...
    CYS_S_GAMMA: ClassVar[DisulfideDerivativeAtom] = ...
    NO_DERIVATIVES_FOR_ATOM: ClassVar[DisulfideDerivativeAtom] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class DisulfideMatchingDatabase:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DisulfideMatchingDatabase) -> None: ...
    def assign(self) -> DisulfideMatchingDatabase: ...
    def get_all_disulfides(self) -> pyrosetta.rosetta.utility.vector1_core_kinematics_RT: ...
    @overload
    def read_disulfide_database(self) -> None: ...
    @overload
    def read_disulfide_database(self) -> void: ...

class DisulfideMatchingEnergyComponents:
    def __init__(self) -> None: ...
    def dslfc_RT(self) -> float: ...
    def dslfc_rot(self) -> float: ...
    def dslfc_trans(self) -> float: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class DisulfideMatchingEnergyContainer(pyrosetta.rosetta.core.scoring.LREnergyContainer):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DisulfideMatchingEnergyContainer) -> None: ...
    @overload
    def __init__(self, arg0: DisulfideMatchingEnergyContainer) -> None: ...
    @overload
    def accumulate_energy(self, disulfide_index: int, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def accumulate_energy(self, unsignedlong, classcore) -> void: ...
    @overload
    def any_neighbors_for_residue(self, resid: int) -> bool: ...
    @overload
    def any_neighbors_for_residue(self, int) -> bool: ...
    @overload
    def any_upper_neighbors_for_residue(self, resid: int) -> bool: ...
    @overload
    def any_upper_neighbors_for_residue(self, int) -> bool: ...
    def assign(self) -> DisulfideMatchingEnergyContainer: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.LREnergyContainer: ...
    def const_neighbor_iterator_begin(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    def const_neighbor_iterator_end(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    def const_upper_neighbor_iterator_begin(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    def const_upper_neighbor_iterator_end(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    def disulfide_atom_indices(self, resid: int) -> DisulfideAtomIndices: ...
    def disulfide_bonded(self, res1id: int, res2id: int) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def energy_computed(self, disulfide_index: int) -> bool: ...
    @overload
    def energy_computed(self, unsignedlong) -> bool: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def lower_neighbor_id(self, disulfide_index: int) -> int: ...
    @overload
    def lower_neighbor_id(self, unsignedlong) -> unsignedlong: ...
    @overload
    def mark_energy_computed(self, disulfide_index: int) -> None: ...
    @overload
    def mark_energy_computed(self, unsignedlong) -> void: ...
    @overload
    def mark_energy_uncomputed(self, disulfide_index: int) -> None: ...
    @overload
    def mark_energy_uncomputed(self, unsignedlong) -> void: ...
    def neighbor_iterator_begin(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    def neighbor_iterator_end(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    def other_neighbor_atom_indices(self, resid: int) -> DisulfideAtomIndices: ...
    @overload
    def other_neighbor_id(self, resid: int) -> int: ...
    @overload
    def other_neighbor_id(self, unsignedlong) -> unsignedlong: ...
    @overload
    def other_neighbor_id(self, disulfide_index: int, resid: int) -> int: ...
    @overload
    def residue_forms_disulfide(self, resid: int) -> bool: ...
    @overload
    def residue_forms_disulfide(self, unsignedlong) -> bool: ...
    @overload
    def retrieve_energy(self, disulfide_index: int, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def retrieve_energy(self, unsignedlong, classcore) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def save_energy(self, disulfide_index: int, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def save_energy(self, unsignedlong, constclasscore) -> void: ...
    @overload
    def update(self) -> None: ...
    @overload
    def update(self, constclasscore) -> void: ...
    @overload
    def upper_neighbor_id(self, disulfide_index: int) -> int: ...
    @overload
    def upper_neighbor_id(self, unsignedlong) -> unsignedlong: ...
    def upper_neighbor_iterator_begin(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    def upper_neighbor_iterator_end(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...

class DisulfideMatchingNeighborConstIterator(pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator):
    @overload
    def __init__(self, owner, focused_node: int, disulfide_index: int) -> None: ...
    @overload
    def __init__(self, owner) -> None: ...
    @overload
    def __init__(self, arg0: DisulfideMatchingNeighborConstIterator) -> None: ...
    @overload
    def __init__(self, arg0: DisulfideMatchingNeighborConstIterator) -> None: ...
    @overload
    def accumulate_energy(self) -> None: ...
    @overload
    def accumulate_energy(self, classcore) -> void: ...
    def assign(self) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    @overload
    def energy_computed(self) -> bool: ...
    @overload
    def energy_computed(self) -> bool: ...
    @overload
    def lower_neighbor_id(self) -> int: ...
    @overload
    def lower_neighbor_id(self) -> unsignedlong: ...
    @overload
    def neighbor_id(self) -> int: ...
    @overload
    def neighbor_id(self) -> unsignedlong: ...
    def pre_increment(self) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    @overload
    def residue_iterated_on(self) -> int: ...
    @overload
    def residue_iterated_on(self) -> unsignedlong: ...
    @overload
    def retrieve_energy(self) -> None: ...
    @overload
    def retrieve_energy(self, classcore) -> void: ...
    @overload
    def upper_neighbor_id(self) -> int: ...
    @overload
    def upper_neighbor_id(self) -> unsignedlong: ...
    def __eq__(self) -> bool: ...
    def __ne__(self) -> bool: ...

class DisulfideMatchingNeighborIterator(pyrosetta.rosetta.core.scoring.ResidueNeighborIterator):
    @overload
    def __init__(self, owner, focused_node: int, disulfide_index: int) -> None: ...
    @overload
    def __init__(self, owner) -> None: ...
    @overload
    def __init__(self, arg0: DisulfideMatchingNeighborIterator) -> None: ...
    @overload
    def __init__(self, arg0: DisulfideMatchingNeighborIterator) -> None: ...
    @overload
    def accumulate_energy(self) -> None: ...
    @overload
    def accumulate_energy(self, classcore) -> void: ...
    def assign(self) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    @overload
    def energy_computed(self) -> bool: ...
    @overload
    def energy_computed(self) -> bool: ...
    @overload
    def lower_neighbor_id(self) -> int: ...
    @overload
    def lower_neighbor_id(self) -> unsignedlong: ...
    @overload
    def mark_energy_computed(self) -> None: ...
    @overload
    def mark_energy_computed(self) -> void: ...
    @overload
    def mark_energy_uncomputed(self) -> None: ...
    @overload
    def mark_energy_uncomputed(self) -> void: ...
    @overload
    def neighbor_id(self) -> int: ...
    @overload
    def neighbor_id(self) -> unsignedlong: ...
    def pre_increment(self) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    @overload
    def residue_iterated_on(self) -> int: ...
    @overload
    def residue_iterated_on(self) -> unsignedlong: ...
    @overload
    def retrieve_energy(self) -> None: ...
    @overload
    def retrieve_energy(self, classcore) -> void: ...
    @overload
    def save_energy(self) -> None: ...
    @overload
    def save_energy(self, constclasscore) -> void: ...
    @overload
    def upper_neighbor_id(self) -> int: ...
    @overload
    def upper_neighbor_id(self) -> unsignedlong: ...
    def __eq__(self) -> bool: ...
    def __ne__(self) -> bool: ...

class DisulfideMatchingPotential:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DisulfideMatchingPotential) -> None: ...
    def assign(self) -> DisulfideMatchingPotential: ...
    @overload
    def compute_matching_energy(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def compute_matching_energy(self, constclasscore) -> double: ...
    @overload
    def score_disulfide(self, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, match_t: float, match_r: float, match_rt: float) -> None: ...
    @overload
    def score_disulfide(self, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, match_t: float, match_r: float, match_rt: float, mirror: bool) -> None: ...

class FullatomDisulfideEnergyComponents:
    def __init__(self) -> None: ...
    def dslf_ca_dih(self) -> float: ...
    def dslf_cbs_ds(self) -> float: ...
    def dslf_cs_ang(self) -> float: ...
    def dslf_fa13(self) -> float: ...
    def dslf_ss_dih(self) -> float: ...
    def dslf_ss_dst(self) -> float: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class FullatomDisulfideEnergyContainer(pyrosetta.rosetta.core.scoring.LREnergyContainer):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FullatomDisulfideEnergyContainer) -> None: ...
    @overload
    def __init__(self, arg0: FullatomDisulfideEnergyContainer) -> None: ...
    @overload
    def accumulate_energy(self, disulfide_index: int, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def accumulate_energy(self, unsignedlong, classcore) -> void: ...
    @overload
    def any_neighbors_for_residue(self, resid: int) -> bool: ...
    @overload
    def any_neighbors_for_residue(self, int) -> bool: ...
    @overload
    def any_upper_neighbors_for_residue(self, resid: int) -> bool: ...
    @overload
    def any_upper_neighbors_for_residue(self, int) -> bool: ...
    def assign(self) -> FullatomDisulfideEnergyContainer: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.LREnergyContainer: ...
    def const_neighbor_iterator_begin(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    def const_neighbor_iterator_end(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    def const_upper_neighbor_iterator_begin(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    def const_upper_neighbor_iterator_end(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborConstIterator: ...
    def disulfide_atom_indices(self, resid: int) -> DisulfideAtomIndices: ...
    def disulfide_bonded(self, res1id: int, res2id: int) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def energy_computed(self, disulfide_index: int) -> bool: ...
    @overload
    def energy_computed(self, unsignedlong) -> bool: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def lower_neighbor_id(self, disulfide_index: int) -> int: ...
    @overload
    def lower_neighbor_id(self, unsignedlong) -> unsignedlong: ...
    @overload
    def mark_energy_computed(self, disulfide_index: int) -> None: ...
    @overload
    def mark_energy_computed(self, unsignedlong) -> void: ...
    @overload
    def mark_energy_uncomputed(self, disulfide_index: int) -> None: ...
    @overload
    def mark_energy_uncomputed(self, unsignedlong) -> void: ...
    def neighbor_iterator_begin(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    def neighbor_iterator_end(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    @overload
    def num_residues(self) -> int: ...
    @overload
    def num_residues(self) -> unsignedlong: ...
    def other_neighbor_atom_indices(self, resid: int) -> DisulfideAtomIndices: ...
    @overload
    def other_neighbor_id(self, resid: int) -> int: ...
    @overload
    def other_neighbor_id(self, unsignedlong) -> unsignedlong: ...
    @overload
    def other_neighbor_id(self, disulfide_index: int, resid: int) -> int: ...
    @overload
    def residue_forms_disulfide(self, resid: int) -> bool: ...
    @overload
    def residue_forms_disulfide(self, unsignedlong) -> bool: ...
    @overload
    def retrieve_energy(self, disulfide_index: int, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def retrieve_energy(self, unsignedlong, classcore) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def save_energy(self, disulfide_index: int, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def save_energy(self, unsignedlong, constclasscore) -> void: ...
    @overload
    def set_num_nodes(self) -> None: ...
    @overload
    def set_num_nodes(self, unsignedlong) -> void: ...
    @overload
    def update(self) -> None: ...
    @overload
    def update(self, constclasscore) -> void: ...
    @overload
    def upper_neighbor_id(self, disulfide_index: int) -> int: ...
    @overload
    def upper_neighbor_id(self, unsignedlong) -> unsignedlong: ...
    def upper_neighbor_iterator_begin(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...
    def upper_neighbor_iterator_end(self, resid: int) -> pyrosetta.rosetta.core.scoring.ResidueNeighborIterator: ...

class FullatomDisulfideParams13:
    a_kappa: float
    a_logA: float
    a_mu: float
    d_location: float
    d_scale: float
    d_shape: float
    dcs_kappa1: float
    dcs_kappa2: float
    dcs_kappa3: float
    dcs_logA1: float
    dcs_logA2: float
    dcs_logA3: float
    dcs_mu1: float
    dcs_mu2: float
    dcs_mu3: float
    dss_kappa1: float
    dss_kappa2: float
    dss_logA1: float
    dss_logA2: float
    dss_mixed_kappa1: float
    dss_mixed_kappa2: float
    dss_mixed_logA1: float
    dss_mixed_logA2: float
    dss_mixed_mu1: float
    dss_mixed_mu2: float
    dss_mu1: float
    dss_mu2: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FullatomDisulfideParams13) -> None: ...

class FullatomDisulfidePotential:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FullatomDisulfidePotential) -> None: ...
    def get_disulfide_derivatives(self, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, res1_atom_indices: DisulfideAtomIndices, res2_atom_indices: DisulfideAtomIndices, weights: pyrosetta.rosetta.core.scoring.EMapVector, r1_atom_derivs: pyrosetta.rosetta.utility.vector1_core_scoring_DerivVectorPair, r2_atom_derivs: pyrosetta.rosetta.utility.vector1_core_scoring_DerivVectorPair) -> None: ...
    def get_disulfide_derivatives_old(self, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, res1_atom_indices: DisulfideAtomIndices, res2_atom_indices: DisulfideAtomIndices, at1: int, weights: pyrosetta.rosetta.core.scoring.EMapVector, F1: pyrosetta.rosetta.numeric.xyzVector_double_t, F2: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def print_score_functions(self) -> None: ...
    @overload
    def print_score_functions(self) -> void: ...
    def score_this_disulfide(self, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, res1_atom_indices: DisulfideAtomIndices, res2_atom_indices: DisulfideAtomIndices, score: float) -> None: ...
    def score_this_disulfide_old(self, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, res1_atom_indices: DisulfideAtomIndices, res2_atom_indices: DisulfideAtomIndices, distance_score_this_disulfide: float, csangles_score_this_disulfide: float, dihedral_score_this_disulfide: float, ca_dihedral_sc_this_disulf: float, truefalse_fa_disulf: bool) -> None: ...

class NCaCaC_Dihedral_Func(pyrosetta.rosetta.core.scoring.func.Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: NCaCaC_Dihedral_Func) -> None: ...
    @overload
    def __init__(self, arg0: NCaCaC_Dihedral_Func) -> None: ...
    def assign(self) -> NCaCaC_Dihedral_Func: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.func.Func: ...
    @overload
    def dfunc(self) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...

class RT_helper:
    def __init__(self) -> None: ...
    @staticmethod
    def RT_from_epos(Epos1: pyrosetta.rosetta.ObjexxFCL.FArray2A_float_t, Epos2: pyrosetta.rosetta.ObjexxFCL.FArray2A_float_t) -> pyrosetta.rosetta.core.kinematics.RT: ...

class SGSG_Dihedral_Func(pyrosetta.rosetta.core.scoring.func.Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SGSG_Dihedral_Func) -> None: ...
    @overload
    def __init__(self, arg0: SGSG_Dihedral_Func) -> None: ...
    def assign(self) -> SGSG_Dihedral_Func: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.func.Func: ...
    @overload
    def dfunc(self) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...

class SG_Dist_Func(pyrosetta.rosetta.core.scoring.func.Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SG_Dist_Func) -> None: ...
    @overload
    def __init__(self, arg0: SG_Dist_Func) -> None: ...
    def assign(self) -> SG_Dist_Func: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.func.Func: ...
    @overload
    def dfunc(self) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...
