import pyrosetta.rosetta.ObjexxFCL
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import overload

class Dssp:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, asu_only: bool) -> None: ...
    @overload
    def __init__(self, arg0: Dssp) -> None: ...
    def assign(self) -> Dssp: ...
    def bb_pair_score(self, res1: int, res2: int) -> float: ...
    @overload
    def dssp(self, dssp_secstruct: pyrosetta.rosetta.ObjexxFCL.FArray1_char_t) -> None: ...
    @overload
    def dssp(self, classObjexxFCL) -> void: ...
    @overload
    def dssp_featurizer(self, secstruct: pyrosetta.rosetta.ObjexxFCL.FArray1_char_t) -> None: ...
    @overload
    def dssp_featurizer(self, classObjexxFCL) -> void: ...
    @overload
    def dssp_reduced(self, secstruct: pyrosetta.rosetta.ObjexxFCL.FArray1_char_t) -> None: ...
    @overload
    def dssp_reduced(self, classObjexxFCL) -> void: ...
    @overload
    def dssp_reduced(self) -> None: ...
    @overload
    def dssp_reduced(self) -> void: ...
    @overload
    def dssp_reduced_IG_as_L(self, secstruct: pyrosetta.rosetta.ObjexxFCL.FArray1_char_t) -> None: ...
    @overload
    def dssp_reduced_IG_as_L(self, classObjexxFCL) -> void: ...
    @overload
    def dssp_reduced_IG_as_L_if_adjcent_H(self, secstruct: pyrosetta.rosetta.ObjexxFCL.FArray1_char_t) -> None: ...
    @overload
    def dssp_reduced_IG_as_L_if_adjcent_H(self, classObjexxFCL) -> void: ...
    def get_dssp_plus_abego_L_def(self, pose: pyrosetta.rosetta.core.pose.Pose) -> str: ...
    def get_dssp_reduced_IG_as_L_secstruct(self) -> str: ...
    @overload
    def get_dssp_secstruct(self, resid: int) -> str: ...
    @overload
    def get_dssp_secstruct(self, unsignedlong) -> char: ...
    @overload
    def get_dssp_secstruct(self) -> str: ...
    def get_dssp_unreduced_secstruct(self) -> str: ...
    def in_paired_strands(self, res1: int, res2: int) -> bool: ...
    @overload
    def insert_dssp_ss_into_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def insert_dssp_ss_into_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, recompute: bool) -> None: ...
    @overload
    def insert_dssp_ss_into_pose(self, classcore, bool) -> void: ...
    @overload
    def insert_edge_ss_into_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def insert_edge_ss_into_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, recompute: bool) -> None: ...
    @overload
    def insert_edge_ss_into_pose(self, classcore, bool) -> void: ...
    @overload
    def insert_ss_into_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def insert_ss_into_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, recompute: bool) -> None: ...
    @overload
    def insert_ss_into_pose(self, classcore, bool) -> void: ...
    @overload
    def insert_ss_into_pose_no_IG_helix(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def insert_ss_into_pose_no_IG_helix(self, pose: pyrosetta.rosetta.core.pose.Pose, recompute: bool) -> None: ...
    @overload
    def insert_ss_into_pose_no_IG_helix(self, classcore, bool) -> void: ...
    @overload
    def num_pairings(self, resi: int) -> int: ...
    @overload
    def num_pairings(self, unsignedlong) -> unsignedlong: ...
    def paired(self, res1: int, res2: int, antiparallel: bool) -> bool: ...
    def strand_pairing_set(self, *args, **kwargs): ...

class Pairing:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pos1_in: int, pos2_in: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pos1_in: int, pos2_in: int, ori_in: int, pleat_in: int) -> None: ...
    @overload
    def __init__(self, arg0: Pairing) -> None: ...
    @overload
    def Orientation(self) -> int: ...
    @overload
    def Orientation(self) -> unsignedlong: ...
    @overload
    def Orientation(self, orientation: int) -> None: ...
    @overload
    def Orientation(self, unsignedlong) -> void: ...
    @overload
    def Pleating(self) -> int: ...
    @overload
    def Pleating(self) -> unsignedlong: ...
    @overload
    def Pleating(self, pleating: int) -> None: ...
    @overload
    def Pleating(self, unsignedlong) -> void: ...
    @overload
    def Pos1(self) -> int: ...
    @overload
    def Pos1(self) -> unsignedlong: ...
    @overload
    def Pos1(self, pos1: int) -> None: ...
    @overload
    def Pos1(self, unsignedlong) -> void: ...
    @overload
    def Pos2(self) -> int: ...
    @overload
    def Pos2(self) -> unsignedlong: ...
    @overload
    def Pos2(self, pos2: int) -> None: ...
    @overload
    def Pos2(self, unsignedlong) -> void: ...
    def assign(self) -> Pairing: ...
    def generate_reversed(self) -> Pairing: ...
    @overload
    def get_register(self) -> int: ...
    @overload
    def get_register(self) -> unsignedlong: ...
    @overload
    def is_anti(self) -> bool: ...
    @overload
    def is_anti(self) -> bool: ...
    @overload
    def is_inwards(self) -> bool: ...
    @overload
    def is_inwards(self) -> bool: ...
    @overload
    def is_outwards(self) -> bool: ...
    @overload
    def is_outwards(self) -> bool: ...
    @overload
    def is_parallel(self) -> bool: ...
    @overload
    def is_parallel(self) -> bool: ...
    def reverse(self) -> Pairing: ...
    def __eq__(self, p: Pairing) -> bool: ...

class StrandPairing:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, res1: int, res2: int, antiparallel: bool, pleating: int) -> None: ...
    @overload
    def __init__(self, arg0: StrandPairing) -> None: ...
    @overload
    def antiparallel(self) -> bool: ...
    @overload
    def antiparallel(self) -> bool: ...
    def assign(self) -> StrandPairing: ...
    @overload
    def begin1(self) -> int: ...
    @overload
    def begin1(self) -> unsignedlong: ...
    @overload
    def check_pleat(self) -> bool: ...
    @overload
    def check_pleat(self) -> bool: ...
    @overload
    def contact_order(self) -> int: ...
    @overload
    def contact_order(self) -> unsignedlong: ...
    @overload
    def contains(self, res: int) -> bool: ...
    @overload
    def contains(self, unsignedlong) -> bool: ...
    @overload
    def end1(self) -> int: ...
    @overload
    def end1(self) -> unsignedlong: ...
    def extend(self, res: int, res2: int, antiparallel: bool, pleating: int) -> bool: ...
    @overload
    def extend_to(self, res: int) -> None: ...
    @overload
    def extend_to(self, unsignedlong) -> void: ...
    def get_all_register_and_bulges(self, regs: pyrosetta.rosetta.utility.vector1_unsigned_long, bulges: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def get_begin2(self) -> int: ...
    @overload
    def get_begin2(self) -> unsignedlong: ...
    @overload
    def get_beta_pairs(self) -> None: ...
    @overload
    def get_beta_pairs(self, classutility) -> void: ...
    @overload
    def get_end2(self) -> int: ...
    @overload
    def get_end2(self) -> unsignedlong: ...
    @overload
    def get_pair(self, res: int) -> int: ...
    @overload
    def get_pair(self, unsignedlong) -> unsignedlong: ...
    def get_pairing1_(self) -> pyrosetta.rosetta.std.vector_unsigned_long: ...
    def get_pairing2_(self) -> pyrosetta.rosetta.std.vector_unsigned_long: ...
    @overload
    def get_pleating(self) -> pyrosetta.rosetta.std.vector_unsigned_long: ...
    @overload
    def get_pleating(self, res: int) -> int: ...
    @overload
    def get_pleating(self, unsignedlong) -> unsignedlong: ...
    @overload
    def get_register(self) -> int: ...
    @overload
    def get_register(self) -> unsignedlong: ...
    @overload
    def has_common_pairing(self, other: StrandPairing) -> bool: ...
    @overload
    def has_common_pairing(self, constclasscore) -> bool: ...
    @overload
    def has_pairing(self) -> bool: ...
    @overload
    def has_pairing(self, constclasscore) -> bool: ...
    def hash_value(self) -> int: ...
    @overload
    def is_bulge(self, res: int) -> bool: ...
    @overload
    def is_bulge(self, unsignedlong) -> bool: ...
    @overload
    def is_ladder(self) -> bool: ...
    @overload
    def is_ladder(self) -> bool: ...
    @overload
    def merge(self, other: StrandPairing) -> bool: ...
    @overload
    def merge(self, other: StrandPairing, domerge: bool) -> bool: ...
    @overload
    def merge(self, constclasscore, bool) -> bool: ...
    @overload
    def mergeable(self, other: StrandPairing) -> bool: ...
    @overload
    def mergeable(self, constclasscore) -> bool: ...
    def paired(self, res1: int, res2: int, anti: bool) -> bool: ...
    @overload
    def range_check(self) -> bool: ...
    @overload
    def range_check(self) -> bool: ...
    @overload
    def show_internals(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_internals(self, std) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def valid_ends(self) -> bool: ...
    @overload
    def valid_ends(self) -> bool: ...
    def __eq__(self, rhs: StrandPairing) -> int: ...

class StrandPairingSet:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, hbonds: pyrosetta.rosetta.ObjexxFCL.FArray2_float_t, threshold: float) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, threshold: float) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: StrandPairingSet) -> None: ...
    def assign(self) -> StrandPairingSet: ...
    @overload
    def check_pleat(self) -> bool: ...
    @overload
    def check_pleat(self) -> bool: ...
    @overload
    def dssp_state(self, res: int) -> str: ...
    @overload
    def dssp_state(self, unsignedlong) -> char: ...
    @overload
    def featurizer_state(self, res: int) -> str: ...
    @overload
    def featurizer_state(self, unsignedlong) -> char: ...
    @overload
    def get_beta_pairs(self) -> None: ...
    @overload
    def get_beta_pairs(self, classutility) -> void: ...
    @overload
    def has_pairing(self) -> bool: ...
    @overload
    def has_pairing(self, constclasscore) -> bool: ...
    @overload
    def has_pairing(self) -> bool: ...
    @overload
    def has_pairing(self, constclasscore) -> bool: ...
    @overload
    def merge(self, other: StrandPairingSet) -> bool: ...
    @overload
    def merge(self, other: StrandPairingSet, domerge: bool) -> bool: ...
    @overload
    def merge(self, constclasscore, bool) -> bool: ...
    def paired(self, res1: int, res2: int, antiparallel: bool) -> bool: ...
    @overload
    def push_back(self, sp: StrandPairing) -> None: ...
    @overload
    def push_back(self, constclasscore) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def strand_pairing(self, i: int) -> StrandPairing: ...

@overload
def fill_hbond_bb_pair_score_dssp(hbond_bb_pair_score_: pyrosetta.rosetta.ObjexxFCL.FArray2D_float_t) -> None: ...
@overload
def fill_hbond_bb_pair_score_dssp(constclasscore, classObjexxFCL) -> void: ...
def get_CA_vectors(ca1: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t, ca2: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t, a: pyrosetta.rosetta.numeric.xyzVector_double_t, b: pyrosetta.rosetta.numeric.xyzVector_double_t, c: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
def get_pairing_geometry(pose: pyrosetta.rosetta.core.pose.Pose, res1: int, res2: int, orientation: float, pleating1: float, pleating2: float) -> None: ...
def get_pleating(pose: pyrosetta.rosetta.core.pose.Pose, pos1: int, pos2: int, orientation: int, pleating: int) -> None: ...
@overload
def has_orientation_and_pleating() -> bool: ...
@overload
def has_orientation_and_pleating(constclassutility) -> bool: ...
@overload
def read_pairing_list(pairing_file: str, pairings: pyrosetta.rosetta.utility.vector1_core_scoring_dssp_Pairing) -> None: ...
@overload
def read_pairing_list(std, classutility) -> void: ...
@overload
def read_pairing_list(_is: pyrosetta.rosetta.std.istream, pairings: pyrosetta.rosetta.utility.vector1_core_scoring_dssp_Pairing) -> None: ...
@overload
def read_pairing_list(std, classutility) -> void: ...
