import pyrosetta.rosetta.ObjexxFCL
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import overload

class AmberPeriodicFunc(Func):
    @overload
    def __init__(self, x0_in: float, k_in: float, n_periodic_in: float) -> None: ...
    @overload
    def __init__(self, arg0: AmberPeriodicFunc) -> None: ...
    @overload
    def __init__(self, arg0: AmberPeriodicFunc) -> None: ...
    def assign(self) -> AmberPeriodicFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    def __eq__(self, other: Func) -> bool: ...

class CharmmPeriodicFunc(Func):
    @overload
    def __init__(self, x0_in: float, k_in: float, n_periodic_in: float) -> None: ...
    @overload
    def __init__(self, arg0: CharmmPeriodicFunc) -> None: ...
    @overload
    def __init__(self, arg0: CharmmPeriodicFunc) -> None: ...
    def assign(self) -> CharmmPeriodicFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    def __eq__(self, other: Func) -> bool: ...

class CircularGeneral1D_Func(Func):
    @overload
    def __init__(self, data: pyrosetta.rosetta.ObjexxFCL.FArray1D_double_t, xmin: float, xbin: float) -> None: ...
    @overload
    def __init__(self, filename: str) -> None: ...
    @overload
    def __init__(self, arg0: CircularGeneral1D_Func) -> None: ...
    @overload
    def __init__(self, arg0: CircularGeneral1D_Func) -> None: ...
    def assign(self) -> CircularGeneral1D_Func: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class CircularHarmonicFunc(Func):
    @overload
    def __init__(self, x0_radians: float, sd_radians: float) -> None: ...
    @overload
    def __init__(self, x0_radians: float, sd_radians: float, offset: float) -> None: ...
    @overload
    def __init__(self, arg0: CircularHarmonicFunc) -> None: ...
    @overload
    def __init__(self, arg0: CircularHarmonicFunc) -> None: ...
    def assign(self) -> CircularHarmonicFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def sd(self) -> float: ...
    @overload
    def sd(self) -> double: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def x0(self) -> float: ...
    @overload
    def x0(self) -> double: ...
    def __eq__(self, other: Func) -> bool: ...

class CircularPowerFunc(Func):
    @overload
    def __init__(self, x0_radians: float, sd_radians: float, power: int, weight: float) -> None: ...
    @overload
    def __init__(self, arg0: CircularPowerFunc) -> None: ...
    @overload
    def __init__(self, arg0: CircularPowerFunc) -> None: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    def __eq__(self, other: Func) -> bool: ...

class CircularSigmoidalFunc(Func):
    @overload
    def __init__(self, center_radians: float, width_radians: float, slope_radians: float) -> None: ...
    @overload
    def __init__(self, center_radians: float, width_radians: float, slope_radians: float, offset: float) -> None: ...
    @overload
    def __init__(self, arg0: CircularSigmoidalFunc) -> None: ...
    @overload
    def __init__(self, arg0: CircularSigmoidalFunc) -> None: ...
    def assign(self) -> CircularSigmoidalFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class CircularSplineFunc(Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: float, arg1: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, weight_in: float, energies_in: pyrosetta.rosetta.utility.vector1_double, convert_to_degrees: bool) -> None: ...
    @overload
    def __init__(self, arg0: CircularSplineFunc) -> None: ...
    @overload
    def __init__(self, arg0: CircularSplineFunc) -> None: ...
    def assign(self) -> CircularSplineFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def get_weight(self) -> float: ...
    @overload
    def get_weight(self) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    @overload
    def train(self, energies_in: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def train(self, classutility) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class ConformationXYZ(XYZ_Func):
    @overload
    def __init__(self, conformation_in: pyrosetta.rosetta.core.conformation.Conformation) -> None: ...
    @overload
    def __init__(self, arg0: ConformationXYZ) -> None: ...
    @overload
    def __init__(self, arg0: ConformationXYZ) -> None: ...
    def residue(self, seqpos: int) -> pyrosetta.rosetta.core.conformation.Residue: ...
    def __call__(self, id: pyrosetta.rosetta.core.id.AtomID) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...

class ConstantFunc(Func):
    @overload
    def __init__(self, return_val: float) -> None: ...
    @overload
    def __init__(self, arg0: ConstantFunc) -> None: ...
    @overload
    def __init__(self, arg0: ConstantFunc) -> None: ...
    def assign(self) -> ConstantFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class CountViolFunc(Func):
    @overload
    def __init__(self, weight: float, myfunc: Func) -> None: ...
    @overload
    def __init__(self, arg0: CountViolFunc) -> None: ...
    @overload
    def __init__(self, arg0: CountViolFunc) -> None: ...
    def assign(self) -> CountViolFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, r: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, r: float, verbose_level: int, threshold: float) -> int: ...
    @overload
    def viols(self) -> int: ...
    @overload
    def viols(self) -> unsignedlong: ...
    def __eq__(self, other: Func) -> bool: ...

class EtableFunc(Func):
    @overload
    def __init__(self, min: float, max: float, stepsize: float) -> None: ...
    @overload
    def __init__(self, arg0: EtableFunc) -> None: ...
    @overload
    def __init__(self, arg0: EtableFunc) -> None: ...
    def assign(self) -> EtableFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class FadeFunc(Func):
    @overload
    def __init__(self, cutoff_lower: float, cutoff_upper: float, fade_zone: float, well_depth: float, well_offset: float) -> None: ...
    @overload
    def __init__(self, cutoff_lower: float, cutoff_upper: float, fade_zone: float, well_depth: float) -> None: ...
    @overload
    def __init__(self, cutoff_lower: float, cutoff_upper: float, fade_zone: float) -> None: ...
    @overload
    def __init__(self, arg0: FadeFunc) -> None: ...
    @overload
    def __init__(self, arg0: FadeFunc) -> None: ...
    def assign(self) -> FadeFunc: ...
    def clone(self) -> Func: ...
    @overload
    def cutoff_lower(self) -> float: ...
    @overload
    def cutoff_lower(self) -> double: ...
    @overload
    def cutoff_lower(self, x: float) -> None: ...
    @overload
    def cutoff_lower(self, double) -> void: ...
    @overload
    def cutoff_upper(self) -> float: ...
    @overload
    def cutoff_upper(self) -> double: ...
    @overload
    def cutoff_upper(self, x: float) -> None: ...
    @overload
    def cutoff_upper(self, double) -> void: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def fade_zone(self) -> float: ...
    @overload
    def fade_zone(self) -> double: ...
    @overload
    def fade_zone(self, x: float) -> None: ...
    @overload
    def fade_zone(self, double) -> void: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    def __eq__(self, other: Func) -> bool: ...

class FlatHarmonicFunc(Func):
    @overload
    def __init__(self, x0_in: float, sd_in: float, tol_in: float) -> None: ...
    @overload
    def __init__(self, arg0: FlatHarmonicFunc) -> None: ...
    @overload
    def __init__(self, arg0: FlatHarmonicFunc) -> None: ...
    def assign(self) -> FlatHarmonicFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def sd(self) -> float: ...
    @overload
    def sd(self) -> double: ...
    @overload
    def sd(self, sd: float) -> None: ...
    @overload
    def sd(self, double) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    @overload
    def tol(self) -> float: ...
    @overload
    def tol(self) -> double: ...
    @overload
    def tol(self, tol: float) -> None: ...
    @overload
    def tol(self, double) -> void: ...
    @overload
    def x0(self) -> float: ...
    @overload
    def x0(self) -> double: ...
    @overload
    def x0(self, x: float) -> None: ...
    @overload
    def x0(self, double) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class FourPointsFunc(XYZ_Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FourPointsFunc) -> None: ...
    @overload
    def __init__(self, arg0: FourPointsFunc) -> None: ...
    def assign(self) -> FourPointsFunc: ...
    def residue(self, seqpos: int) -> pyrosetta.rosetta.core.conformation.Residue: ...
    @overload
    def xyz(self, atomid: int, coord: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def xyz(self, unsignedlong, constclassnumeric) -> void: ...
    def __call__(self, id: pyrosetta.rosetta.core.id.AtomID) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...

class Func:
    @overload
    def __init__(self, arg0: Func) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def assign(self) -> Func: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def estimate_dfunc(self, r: float) -> float: ...
    @overload
    def estimate_dfunc(self, constdouble) -> double: ...
    @overload
    def estimate_dfunc(self, r: float, h: float) -> float: ...
    @overload
    def func(self) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, r: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, r: float, verbose_level: int, threshold: float) -> int: ...
    def __eq__(self, other: Func) -> bool: ...
    def __ne__(self, other: Func) -> bool: ...

class FuncFactory:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FuncFactory) -> None: ...
    @overload
    def add_type(self, type_name: str, new_func: Func) -> None: ...
    @overload
    def add_type(self, std, classstd) -> void: ...
    def assign(self) -> FuncFactory: ...
    def new_func(self, type: str) -> Func: ...

class GaussianChainDoubleFunc(Func):
    @overload
    def __init__(self, gaussian_variance: float, loop_fixed_cost: float, D2: float) -> None: ...
    @overload
    def __init__(self, arg0: GaussianChainDoubleFunc) -> None: ...
    @overload
    def __init__(self, arg0: GaussianChainDoubleFunc) -> None: ...
    def assign(self) -> GaussianChainDoubleFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class GaussianChainFunc(Func):
    @overload
    def __init__(self, gaussian_variance: float, loop_fixed_cost: float, other_distances: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, gaussian_variance: float, loop_fixed_cost: float) -> None: ...
    @overload
    def __init__(self, arg0: GaussianChainFunc) -> None: ...
    @overload
    def __init__(self, arg0: GaussianChainFunc) -> None: ...
    def assign(self) -> GaussianChainFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def force_combined_gaussian_approximation(self) -> bool: ...
    @overload
    def force_combined_gaussian_approximation(self) -> bool: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def set_force_combined_gaussian_approximation(self, setting: bool) -> None: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class GaussianChainGeneralFunc(Func):
    @overload
    def __init__(self, gaussian_variance_: float, loop_fixed_cost: float, other_distances: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, arg0: GaussianChainGeneralFunc) -> None: ...
    @overload
    def __init__(self, arg0: GaussianChainGeneralFunc) -> None: ...
    def assign(self) -> GaussianChainGeneralFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, z: float, calc_deriv: bool, deriv: float) -> float: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class GaussianChainQuadrupleFunc(Func):
    @overload
    def __init__(self, gaussian_variance_: float, loop_fixed_cost: float, D2: float, D3: float, D4: float) -> None: ...
    @overload
    def __init__(self, arg0: GaussianChainQuadrupleFunc) -> None: ...
    @overload
    def __init__(self, arg0: GaussianChainQuadrupleFunc) -> None: ...
    def assign(self) -> GaussianChainQuadrupleFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class GaussianChainSingleFunc(Func):
    @overload
    def __init__(self, gaussian_variance_: float, loop_fixed_cost: float) -> None: ...
    @overload
    def __init__(self, arg0: GaussianChainSingleFunc) -> None: ...
    @overload
    def __init__(self, arg0: GaussianChainSingleFunc) -> None: ...
    def assign(self) -> GaussianChainSingleFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class GaussianChainTripleFunc(Func):
    @overload
    def __init__(self, gaussian_variance_: float, loop_fixed_cost: float, D2: float, D3: float) -> None: ...
    @overload
    def __init__(self, arg0: GaussianChainTripleFunc) -> None: ...
    @overload
    def __init__(self, arg0: GaussianChainTripleFunc) -> None: ...
    def assign(self) -> GaussianChainTripleFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class GaussianFunc(Func):
    @overload
    def __init__(self, mean: float, sd: float) -> None: ...
    @overload
    def __init__(self, arg0: GaussianFunc) -> None: ...
    @overload
    def __init__(self, arg0: GaussianFunc) -> None: ...
    def assign(self) -> GaussianFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class HarmonicFunc(Func):
    @overload
    def __init__(self, x0_in: float, sd_in: float) -> None: ...
    @overload
    def __init__(self, arg0: HarmonicFunc) -> None: ...
    @overload
    def __init__(self, arg0: HarmonicFunc) -> None: ...
    def assign(self) -> HarmonicFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def sd(self) -> float: ...
    @overload
    def sd(self) -> double: ...
    @overload
    def sd(self, sd: float) -> None: ...
    @overload
    def sd(self, double) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    @overload
    def x0(self) -> float: ...
    @overload
    def x0(self) -> double: ...
    @overload
    def x0(self, x: float) -> None: ...
    @overload
    def x0(self, double) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class IdentityFunc(Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: IdentityFunc) -> None: ...
    @overload
    def __init__(self, arg0: IdentityFunc) -> None: ...
    def assign(self) -> IdentityFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    def __eq__(self, other: Func) -> bool: ...

class KarplusFunc(Func):
    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float) -> None: ...
    @overload
    def __init__(self, A_Hertz: float, B_Hertz: float, C_Hertz: float, Dphi_radians: float, x0_Hertz: float, sd_Hertz: float, offset: float) -> None: ...
    @overload
    def __init__(self, arg0: KarplusFunc) -> None: ...
    @overload
    def __init__(self, arg0: KarplusFunc) -> None: ...
    def assign(self) -> KarplusFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class LinearPenaltyFunction(Func):
    @overload
    def __init__(self, x_middle: float, well_depth: float, half_width: float, slope: float) -> None: ...
    @overload
    def __init__(self, arg0: LinearPenaltyFunction) -> None: ...
    @overload
    def __init__(self, arg0: LinearPenaltyFunction) -> None: ...
    def assign(self) -> LinearPenaltyFunction: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def get_half_width(self) -> float: ...
    @overload
    def get_half_width(self) -> double: ...
    @overload
    def get_slope(self) -> float: ...
    @overload
    def get_slope(self) -> double: ...
    @overload
    def get_well_depth(self) -> float: ...
    @overload
    def get_well_depth(self) -> double: ...
    @overload
    def get_x_middle(self) -> float: ...
    @overload
    def get_x_middle(self) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_half_width(self, half_width: float) -> None: ...
    @overload
    def set_half_width(self, double) -> void: ...
    @overload
    def set_slope(self, slope: float) -> None: ...
    @overload
    def set_slope(self, double) -> void: ...
    @overload
    def set_well_depth(self, well_depth: float) -> None: ...
    @overload
    def set_well_depth(self, double) -> void: ...
    @overload
    def set_x_middle(self, x: float) -> None: ...
    @overload
    def set_x_middle(self, double) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    def __eq__(self, other: Func) -> bool: ...

class MinMultiHarmonicFunc(Func):
    @overload
    def __init__(self, x0_in: pyrosetta.rosetta.utility.vector1_double, sd_in: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, arg0: MinMultiHarmonicFunc) -> None: ...
    @overload
    def __init__(self, arg0: MinMultiHarmonicFunc) -> None: ...
    def assign(self) -> MinMultiHarmonicFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def sd(self, n: int) -> float: ...
    @overload
    def sd(self, int) -> double: ...
    @overload
    def sd(self, n: int, sd: float) -> None: ...
    @overload
    def sd(self, int, double) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    @overload
    def x0(self, n: int) -> float: ...
    @overload
    def x0(self, int) -> double: ...
    @overload
    def x0(self, n: int, x: float) -> None: ...
    @overload
    def x0(self, int, double) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class MixtureFunc(Func):
    @overload
    def __init__(self, anchor: float, gaussian_param: float, exp_param: float, mixture_param: float, bg_mean: float, bg_sd: float) -> None: ...
    @overload
    def __init__(self, arg0: MixtureFunc) -> None: ...
    @overload
    def __init__(self, arg0: MixtureFunc) -> None: ...
    def assign(self) -> MixtureFunc: ...
    @overload
    def calc_kl_divergence(self) -> float: ...
    @overload
    def calc_kl_divergence(self) -> double: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    def dfunc_component(self, x: float, g: float, h: float, g_prime: float, h_prime: float) -> float: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def func_(self, x: float) -> float: ...
    @overload
    def func_(self, double) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class PeriodicFunc(Func):
    @overload
    def __init__(self, x0_in: float, k_in: float, n_periodic_in: float, C_in: float) -> None: ...
    @overload
    def __init__(self, arg0: PeriodicFunc) -> None: ...
    @overload
    def __init__(self, arg0: PeriodicFunc) -> None: ...
    def assign(self) -> PeriodicFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    def __eq__(self, other: Func) -> bool: ...

class ResiduePairXYZ(XYZ_Func):
    @overload
    def __init__(self, rsd1_in: pyrosetta.rosetta.core.conformation.Residue, rsd2_in: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def __init__(self, arg0: ResiduePairXYZ) -> None: ...
    @overload
    def __init__(self, arg0: ResiduePairXYZ) -> None: ...
    def residue(self, seqpos: int) -> pyrosetta.rosetta.core.conformation.Residue: ...
    def __call__(self, id: pyrosetta.rosetta.core.id.AtomID) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...

class ResidueXYZ(XYZ_Func):
    @overload
    def __init__(self, rsd_in: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def __init__(self, arg0: ResidueXYZ) -> None: ...
    @overload
    def __init__(self, arg0: ResidueXYZ) -> None: ...
    def residue(self, seqpos: int) -> pyrosetta.rosetta.core.conformation.Residue: ...
    def __call__(self, id: pyrosetta.rosetta.core.id.AtomID) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...

class SOGFunc(Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, means: pyrosetta.rosetta.utility.vector1_double, sdevs: pyrosetta.rosetta.utility.vector1_double, weights: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, mean: float, sdev: float) -> None: ...
    @overload
    def __init__(self, arg0: SOGFunc) -> None: ...
    @overload
    def __init__(self, arg0: SOGFunc) -> None: ...
    def assign(self) -> SOGFunc: ...
    def check_bounds(self, x: float, val: float) -> None: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class SOGFunc_Impl:
    @overload
    def __init__(self, means: pyrosetta.rosetta.utility.vector1_double, sdevs: pyrosetta.rosetta.utility.vector1_double, weights: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SOGFunc_Impl) -> None: ...
    def assign(self) -> SOGFunc_Impl: ...
    def check_bounds(self, x: float, val: float) -> None: ...
    @overload
    def clear_(self) -> None: ...
    @overload
    def clear_(self) -> void: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def get_alt_score_(self, x: float) -> float: ...
    @overload
    def get_alt_score_(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def prob_sum_of_gaussians(self, x: float) -> float: ...
    @overload
    def prob_sum_of_gaussians(self, constdouble) -> double: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def renormalize_weights(self) -> None: ...
    @overload
    def renormalize_weights(self) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def smooth_to_zero(self, setting: bool) -> None: ...
    @overload
    def smooth_to_zero(self, constbool) -> void: ...
    @overload
    def smooth_to_zero(self) -> bool: ...
    @overload
    def smooth_to_zero(self) -> bool: ...
    @overload
    def sog_cst_param(self) -> float: ...
    @overload
    def sog_cst_param(self) -> double: ...
    @overload
    def sog_cst_param(self, param: float) -> None: ...
    @overload
    def sog_cst_param(self, constdouble) -> void: ...
    @overload
    def upper_bound(self, r: float) -> None: ...
    @overload
    def upper_bound(self, constdouble) -> void: ...
    @overload
    def upper_bound(self) -> float: ...
    @overload
    def upper_bound(self) -> double: ...
    @overload
    def upper_bound_score(self) -> float: ...
    @overload
    def upper_bound_score(self) -> double: ...
    def __eq__(self, other: SOGFunc_Impl) -> bool: ...

class ScalarWeightedFunc(Func):
    @overload
    def __init__(self, weight: float, myfunc: Func) -> None: ...
    @overload
    def __init__(self, arg0: ScalarWeightedFunc) -> None: ...
    @overload
    def __init__(self, arg0: ScalarWeightedFunc) -> None: ...
    def assign(self) -> ScalarWeightedFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    def __eq__(self, other: Func) -> bool: ...

class SigmoidFunc(Func):
    @overload
    def __init__(self, x0_in: float, slope_in: float) -> None: ...
    @overload
    def __init__(self, arg0: SigmoidFunc) -> None: ...
    @overload
    def __init__(self, arg0: SigmoidFunc) -> None: ...
    def assign(self) -> SigmoidFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    @overload
    def slope(self) -> float: ...
    @overload
    def slope(self) -> double: ...
    @overload
    def slope(self, slope: float) -> None: ...
    @overload
    def slope(self, double) -> void: ...
    @overload
    def x0(self) -> float: ...
    @overload
    def x0(self) -> double: ...
    @overload
    def x0(self, x: float) -> None: ...
    @overload
    def x0(self, double) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class SkipViolFunc(Func):
    @overload
    def __init__(self, weight: float, myfunc: Func) -> None: ...
    @overload
    def __init__(self, arg0: SkipViolFunc) -> None: ...
    @overload
    def __init__(self, arg0: SkipViolFunc) -> None: ...
    def assign(self) -> SkipViolFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, r: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, r: float, verbose_level: int, threshold: float) -> int: ...
    @overload
    def viols(self) -> int: ...
    @overload
    def viols(self) -> unsignedlong: ...
    def __eq__(self, other: Func) -> bool: ...

class SmoothStepFunc(Func):
    @overload
    def __init__(self, low: float, high: float) -> None: ...
    @overload
    def __init__(self, arg0: SmoothStepFunc) -> None: ...
    @overload
    def __init__(self, arg0: SmoothStepFunc) -> None: ...
    def assign(self) -> SmoothStepFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class SoedingFunc(Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SoedingFunc) -> None: ...
    @overload
    def __init__(self, arg0: SoedingFunc) -> None: ...
    def assign(self) -> SoedingFunc: ...
    def clone(self) -> Func: ...
    @overload
    def compute_func(self, x: float) -> float: ...
    @overload
    def compute_func(self, constdouble) -> double: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class SplineFunc(Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: float, arg2: float, arg3: float, arg4: pyrosetta.rosetta.utility.vector1_double, arg5: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, KB_description: str, weight: float, exp_val: float, bin_size: float, bins_vect: pyrosetta.rosetta.utility.vector1_double, potential_vect: pyrosetta.rosetta.utility.vector1_double, boundary_functions: pyrosetta.rosetta.utility.vector1_std_tuple_std_string_double_double_double_t) -> None: ...
    @overload
    def __init__(self, arg0: SplineFunc) -> None: ...
    @overload
    def __init__(self, arg0: SplineFunc) -> None: ...
    def assign(self) -> SplineFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    def get_KB_description(self) -> str: ...
    @overload
    def get_bin_size(self) -> float: ...
    @overload
    def get_bin_size(self) -> double: ...
    def get_bins_vect(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def get_bins_vect_size(self) -> int: ...
    @overload
    def get_bins_vect_size(self) -> unsignedlong: ...
    @overload
    def get_exp_val(self) -> float: ...
    @overload
    def get_exp_val(self) -> double: ...
    def get_filename(self) -> str: ...
    @overload
    def get_lower_bound_dy(self) -> float: ...
    @overload
    def get_lower_bound_dy(self) -> double: ...
    @overload
    def get_lower_bound_x(self) -> float: ...
    @overload
    def get_lower_bound_x(self) -> double: ...
    @overload
    def get_lower_bound_y(self) -> float: ...
    @overload
    def get_lower_bound_y(self) -> double: ...
    def get_potential_vect(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def get_potential_vect_size(self) -> int: ...
    @overload
    def get_potential_vect_size(self) -> unsignedlong: ...
    @overload
    def get_upper_bound_dy(self) -> float: ...
    @overload
    def get_upper_bound_dy(self) -> double: ...
    @overload
    def get_upper_bound_x(self) -> float: ...
    @overload
    def get_upper_bound_x(self) -> double: ...
    @overload
    def get_upper_bound_y(self) -> float: ...
    @overload
    def get_upper_bound_y(self) -> double: ...
    @overload
    def get_weight(self) -> float: ...
    @overload
    def get_weight(self) -> double: ...
    @overload
    def is_approximately_equal(self, other: SplineFunc, float_threshold: float) -> bool: ...
    @overload
    def is_approximately_equal(self, constclasscore, constdouble) -> bool: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    def __eq__(self, other: Func) -> bool: ...

class SquareWell2Func(Func):
    @overload
    def __init__(self, x0_in: float, x_range_in: float, well_depth_in: float) -> None: ...
    @overload
    def __init__(self, arg0: SquareWell2Func) -> None: ...
    @overload
    def __init__(self, arg0: SquareWell2Func) -> None: ...
    def assign(self) -> SquareWell2Func: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    @overload
    def well_depth(self) -> float: ...
    @overload
    def well_depth(self) -> double: ...
    @overload
    def well_depth(self, well_depth: float) -> None: ...
    @overload
    def well_depth(self, double) -> void: ...
    @overload
    def x0(self) -> float: ...
    @overload
    def x0(self) -> double: ...
    @overload
    def x0(self, x: float) -> None: ...
    @overload
    def x0(self, double) -> void: ...
    @overload
    def x_range(self) -> float: ...
    @overload
    def x_range(self) -> double: ...
    @overload
    def x_range(self, x_range: float) -> None: ...
    @overload
    def x_range(self, double) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class SquareWellFunc(Func):
    @overload
    def __init__(self, x0_in: float, well_depth_in: float) -> None: ...
    @overload
    def __init__(self, arg0: SquareWellFunc) -> None: ...
    @overload
    def __init__(self, arg0: SquareWellFunc) -> None: ...
    def assign(self) -> SquareWellFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    @overload
    def well_depth(self) -> float: ...
    @overload
    def well_depth(self) -> double: ...
    @overload
    def well_depth(self, well_depth: float) -> None: ...
    @overload
    def well_depth(self, double) -> void: ...
    @overload
    def x0(self) -> float: ...
    @overload
    def x0(self) -> double: ...
    @overload
    def x0(self, x: float) -> None: ...
    @overload
    def x0(self, double) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class SumFunc(Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SumFunc) -> None: ...
    @overload
    def __init__(self, arg0: SumFunc) -> None: ...
    @overload
    def add_func(self, f: Func) -> None: ...
    @overload
    def add_func(self, classstd) -> void: ...
    def assign(self) -> SumFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def funcs(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_scoring_func_Func_t: ...
    @overload
    def funcs(self, funcs: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_scoring_func_Func_t) -> None: ...
    @overload
    def funcs(self, classutility) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class TopOutFunc(Func):
    @overload
    def __init__(self, weight_in: float, x0_in: float, limit_in: float) -> None: ...
    @overload
    def __init__(self, arg0: TopOutFunc) -> None: ...
    @overload
    def __init__(self, arg0: TopOutFunc) -> None: ...
    def assign(self) -> TopOutFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def limit(self) -> float: ...
    @overload
    def limit(self) -> double: ...
    @overload
    def limit(self, limit: float) -> None: ...
    @overload
    def limit(self, double) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, x: float, verbose_level: int, threshold: float) -> int: ...
    @overload
    def weight(self) -> float: ...
    @overload
    def weight(self) -> double: ...
    @overload
    def weight(self, weight: float) -> None: ...
    @overload
    def weight(self, double) -> void: ...
    @overload
    def x0(self) -> float: ...
    @overload
    def x0(self) -> double: ...
    @overload
    def x0(self, x: float) -> None: ...
    @overload
    def x0(self, double) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class USOGFunc(Func):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: float, arg1: float) -> None: ...
    @overload
    def __init__(self, mean: float, std_dev: float, weight: float) -> None: ...
    @overload
    def __init__(self, means: pyrosetta.rosetta.utility.vector1_double, std_devs: pyrosetta.rosetta.utility.vector1_double, weights: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, arg0: USOGFunc) -> None: ...
    @overload
    def __init__(self, arg0: USOGFunc) -> None: ...
    def assign(self) -> USOGFunc: ...
    def clone(self) -> Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def numGaussians(self) -> int: ...
    @overload
    def numGaussians(self) -> unsignedlong: ...
    @overload
    def read_data(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def read_data(self, std) -> void: ...
    @overload
    def same_type_as_me(self, other: Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show_definition(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_definition(self, std) -> void: ...
    def __eq__(self, other: Func) -> bool: ...

class XYZ_Func:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: XYZ_Func) -> None: ...
    def assign(self) -> XYZ_Func: ...
    def residue(self, seqpos: int) -> pyrosetta.rosetta.core.conformation.Residue: ...
    def __call__(self, id: pyrosetta.rosetta.core.id.AtomID) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...

@overload
def readValueOrDie(_in: pyrosetta.rosetta.std.istream) -> float: ...
@overload
def readValueOrDie(std) -> double: ...
