#!/usr/bin/env zsh
set -euo pipefail
cd $0:h
# Generated by activating env with pyrosetta (huge) then running multiple times 
# and installing things it complains about.
# Then checking in script which imports things like FastRelax to see if it gets understood.
# Here use any env with pyrosetta in it or install from channel e.g. https://conda.rosettacommons.org:
mamba activate ~/Documents/mferla/.venv
mamba install mypy numpy py3Dmol ipywidgets dask psutil pymol-open-source billiard gitpython toolz attrs distributed
./stubgen.sh pyrosetta
stubgen --package pyrosetta --out .
stubgen --package pyrosetta.rosetta --out .
stubgen --package pyrosetta.rosetta.std --out .
stubgen --package pyrosetta.rosetta.core --out .
stubgen --package pyrosetta.rosetta.protocols --out .
