import pyrosetta.rosetta.basic
import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.filters
import pyrosetta.rosetta.protocols.loop_modeling
import pyrosetta.rosetta.protocols.loops
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import overload

class AcceptanceCheck(pyrosetta.rosetta.protocols.loop_modeling.LoopMover):
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.protocols.moves.MonteCarlo) -> None: ...
    @overload
    def __init__(self, monte_carlo: pyrosetta.rosetta.protocols.moves.MonteCarlo, name: str) -> None: ...
    @overload
    def __init__(self, arg0: AcceptanceCheck) -> None: ...
    @overload
    def __init__(self, arg0: AcceptanceCheck) -> None: ...
    def assign(self) -> AcceptanceCheck: ...
    def get_name(self) -> str: ...

class LoopFilter(pyrosetta.rosetta.protocols.loop_modeling.LoopMover):
    @overload
    def __init__(self, filter: pyrosetta.rosetta.protocols.filters.Filter) -> None: ...
    @overload
    def __init__(self, arg0: LoopFilter) -> None: ...
    @overload
    def __init__(self, arg0: LoopFilter) -> None: ...
    def assign(self) -> LoopFilter: ...
    @overload
    def do_apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def do_apply(self, classcore) -> bool: ...
    def get_name(self) -> str: ...

class LoopMoverGroup(pyrosetta.rosetta.protocols.loop_modeling.LoopMover):
    def __init__(self) -> None: ...
    def add_filter(self, filter: pyrosetta.rosetta.protocols.filters.Filter) -> pyrosetta.rosetta.protocols.loop_modeling.LoopMover: ...
    def add_mover(self, task: pyrosetta.rosetta.protocols.loop_modeling.LoopMover) -> pyrosetta.rosetta.protocols.loop_modeling.LoopMover: ...
    def add_mover_group(self) -> LoopMoverGroup: ...
    def assign(self) -> LoopMoverGroup: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def get_children_names(self, names: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def get_children_names(self, names: pyrosetta.rosetta.utility.vector1_std_string, indent: str) -> None: ...
    @overload
    def get_children_names(self, classutility, std) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def mark_as_default(self) -> None: ...
    @overload
    def mark_as_default(self) -> void: ...

class PrepareForCentroid(pyrosetta.rosetta.protocols.loop_modeling.LoopMover):
    def __init__(self) -> None: ...
    def assign(self) -> PrepareForCentroid: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class PrepareForCentroidCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PrepareForCentroidCreator) -> None: ...
    @overload
    def __init__(self, arg0: PrepareForCentroidCreator) -> None: ...
    def assign(self) -> PrepareForCentroidCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class PrepareForFullatom(pyrosetta.rosetta.protocols.loop_modeling.LoopMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PrepareForFullatom) -> None: ...
    @overload
    def __init__(self, arg0: PrepareForFullatom) -> None: ...
    def assign(self) -> PrepareForFullatom: ...
    def get_name(self) -> str: ...
    def get_score_function(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_force_repack(self, value: bool) -> None: ...
    @overload
    def set_force_repack(self, bool) -> void: ...
    @overload
    def set_original_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_original_pose(self, constclasscore) -> void: ...
    @overload
    def set_score_function(self, score_function: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_score_function(self, classstd) -> void: ...

class PrepareForFullatomCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PrepareForFullatomCreator) -> None: ...
    @overload
    def __init__(self, arg0: PrepareForFullatomCreator) -> None: ...
    def assign(self) -> PrepareForFullatomCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class TrajectoryLogger:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, prefix: str) -> None: ...
    @overload
    def __init__(self, mover: pyrosetta.rosetta.protocols.loop_modeling.LoopMover) -> None: ...
    @overload
    def __init__(self, mover: pyrosetta.rosetta.protocols.loop_modeling.LoopMover, prefix: str) -> None: ...
    @overload
    def __init__(self, loops: pyrosetta.rosetta.protocols.loops.Loops, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, loops: pyrosetta.rosetta.protocols.loops.Loops, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, prefix: str) -> None: ...
    @overload
    def __init__(self, arg0: TrajectoryLogger) -> None: ...
    def assign(self) -> TrajectoryLogger: ...
    def get_loops(self) -> pyrosetta.rosetta.protocols.loops.Loops: ...
    def get_native_pose(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    def get_prefix(self) -> str: ...
    def get_score_function(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def get_timer(self) -> int: ...
    @overload
    def get_timer(self) -> long: ...
    @overload
    def init(self, mover: pyrosetta.rosetta.protocols.loop_modeling.LoopMover) -> None: ...
    @overload
    def init(self, constclassprotocols) -> void: ...
    @overload
    def init(self, loops: pyrosetta.rosetta.protocols.loops.Loops, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def record_endpoint(self, tr: pyrosetta.rosetta.basic.Tracer, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def record_endpoint(self, classbasic, classcore) -> void: ...
    @overload
    def record_move(self, tr: pyrosetta.rosetta.basic.Tracer, pose: pyrosetta.rosetta.core.pose.Pose, i: int, j: int, k: int, proposed: bool, accepted: bool) -> None: ...
    @overload
    def record_move(self, tr: pyrosetta.rosetta.basic.Tracer, pose: pyrosetta.rosetta.core.pose.Pose, iteration: int, proposed: bool, accepted: bool) -> None: ...
    @overload
    def record_new_pose(self, tr: pyrosetta.rosetta.basic.Tracer, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def record_new_pose(self, classbasic, classcore) -> void: ...
    @overload
    def record_new_score_function(self, tr: pyrosetta.rosetta.basic.Tracer, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def record_new_score_function(self, classbasic, classcore) -> void: ...
    @overload
    def record_new_temperature(self, tr: pyrosetta.rosetta.basic.Tracer, temperature: float) -> None: ...
    @overload
    def record_new_temperature(self, classbasic, double) -> void: ...
    @overload
    def reset_timer(self) -> None: ...
    @overload
    def reset_timer(self) -> void: ...
    @overload
    def set_loops(self) -> None: ...
    @overload
    def set_loops(self, classstd) -> void: ...
    @overload
    def set_native_pose(self) -> None: ...
    @overload
    def set_native_pose(self, constclasscore) -> void: ...
    @overload
    def set_prefix(self) -> None: ...
    @overload
    def set_prefix(self, std) -> void: ...
    @overload
    def set_score_function(self) -> None: ...
    @overload
    def set_score_function(self, classstd) -> void: ...
    @overload
    def unset_native_pose(self) -> None: ...
    @overload
    def unset_native_pose(self) -> void: ...

def append_subelement_and_attributes_for_parse_loops_from_tag(xsd, subelements, attributes: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
@overload
def attributes_for_set_scorefxn_from_tag(attributes: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
@overload
def attributes_for_set_scorefxn_from_tag(classstd) -> void: ...
@overload
def attributes_for_set_task_factory_from_tag(attributes: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
@overload
def attributes_for_set_task_factory_from_tag(classstd) -> void: ...
def loop_mover_from_tag(tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> pyrosetta.rosetta.protocols.loop_modeling.LoopMover: ...
def parse_loops_from_tag(tag: pyrosetta.rosetta.utility.tag.Tag) -> pyrosetta.rosetta.protocols.loops.Loops: ...
