import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import ClassVar, overload

ALIGNMENT_ANCHOR_RES: FullModelParameterType
CALC_RMS: FullModelParameterType
CUTPOINT_OPEN: FullModelParameterType
CYCLIZE_RES: FullModelParameterType
DISULFIDE: FullModelParameterType
DOCK_DOMAIN: FullModelParameterType
EXTRA_MINIMIZE: FullModelParameterType
EXTRA_MINIMIZE_JUMP: FullModelParameterType
FIVEPRIME_CAP: FullModelParameterType
FIXED_DOMAIN: FullModelParameterType
INPUT_DOMAIN: FullModelParameterType
JUMP: FullModelParameterType
LAST_TYPE: FullModelParameterType
NO_TYPE: FullModelParameterType
PREFERRED_ROOT: FullModelParameterType
RNA_ANTI_CHI: FullModelParameterType
RNA_BLOCK_STACK_ABOVE: FullModelParameterType
RNA_BLOCK_STACK_BELOW: FullModelParameterType
RNA_BULGE: FullModelParameterType
RNA_NORTH_SUGAR: FullModelParameterType
RNA_SAMPLE_SUGAR: FullModelParameterType
RNA_SOUTH_SUGAR: FullModelParameterType
RNA_SYN_CHI: FullModelParameterType
RNA_TERMINAL: FullModelParameterType
SAMPLE: FullModelParameterType
TWOPRIME_RES: FullModelParameterType
WORKING: FullModelParameterType

class FullModelInfo(pyrosetta.rosetta.basic.datacache.CacheableData):
    @overload
    def __init__(self, full_sequence: str, cutpoint_open_in_full_model: pyrosetta.rosetta.utility.vector1_unsigned_long, res_numbers_in_pose: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, full_model_parameters) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: FullModelInfo) -> None: ...
    @overload
    def __init__(self, arg0: FullModelInfo) -> None: ...
    @overload
    def add_other_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def add_other_pose(self, classstd) -> void: ...
    @overload
    def add_submotif_info(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, tag: str) -> None: ...
    @overload
    def add_submotif_info(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, tag: str, seed: bool) -> None: ...
    @overload
    def add_submotif_info(self, submotif_info_list: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_full_model_info_SubMotifInfo_t) -> None: ...
    @overload
    def add_submotif_info(self, classutility) -> void: ...
    @overload
    def add_submotif_info(self, submotif_info_op) -> None: ...
    @overload
    def add_submotif_info(self, classstd) -> void: ...
    def alignment_anchor_res(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def assign(self) -> FullModelInfo: ...
    def calc_rms_res(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def chains_in_full_model(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def clear_other_pose_list(self) -> None: ...
    @overload
    def clear_other_pose_list(self) -> void: ...
    @overload
    def clear_res_list(self) -> None: ...
    @overload
    def clear_res_list(self) -> void: ...
    def clone(self) -> pyrosetta.rosetta.basic.datacache.CacheableData: ...
    def clone_info(self) -> FullModelInfo: ...
    def conventional_chains(self) -> pyrosetta.rosetta.utility.vector1_char: ...
    def conventional_numbering(self) -> pyrosetta.rosetta.utility.vector1_int: ...
    def conventional_segids(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    def cutpoint_open_in_full_model(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def cyclize_res(self) -> pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t: ...
    @overload
    def delete_submotif_info(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, tag: str) -> None: ...
    @overload
    def delete_submotif_info(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, tag: str, seed: bool) -> None: ...
    @overload
    def delete_submotif_info(self, submotif_info_list: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_full_model_info_SubMotifInfo_t) -> None: ...
    @overload
    def delete_submotif_info(self, classutility) -> void: ...
    @overload
    def delete_submotif_info(self, submotif_info_op) -> None: ...
    @overload
    def delete_submotif_info(self, classstd) -> void: ...
    def disulfide_pairs(self) -> pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t: ...
    def dock_domain_map(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def extra_minimize_res(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def find_index_in_other_pose_list(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def find_index_in_other_pose_list(self, constclasscore) -> unsignedlong: ...
    def fiveprime_cap(self) -> pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t: ...
    def fixed_domain_map(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def full_model_parameters(self, *args, **kwargs): ...
    def full_sequence(self) -> str: ...
    @overload
    def full_to_sub(self, res_in_full_model_numbering: pyrosetta.rosetta.utility.vector1_unsigned_long) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def full_to_sub(self, res_in_full_model_numbering: int) -> int: ...
    @overload
    def full_to_sub(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def full_to_sub(self) -> pyrosetta.rosetta.std.map_unsigned_long_unsigned_long: ...
    @overload
    def get_idx_for_other_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def get_idx_for_other_pose(self, constclasscore) -> unsignedlong: ...
    @overload
    def get_idx_for_other_pose_with_residue(self, input_res: int) -> int: ...
    @overload
    def get_idx_for_other_pose_with_residue(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def get_idx_for_other_pose_with_residues(self, input_res: pyrosetta.rosetta.utility.vector1_unsigned_long) -> int: ...
    @overload
    def get_idx_for_other_pose_with_residues(self, constclassutility) -> unsignedlong: ...
    def global_mapping(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def global_sequence(self) -> str: ...
    @overload
    def in_a_submotif(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long) -> bool: ...
    @overload
    def in_a_submotif(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, check_other_poses: bool) -> bool: ...
    @overload
    def in_a_submotif_seed(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long) -> bool: ...
    @overload
    def in_a_submotif_seed(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, check_other_poses: bool) -> bool: ...
    def input_domain_map(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def is_a_submotif(self) -> bool: ...
    @overload
    def is_a_submotif(self) -> bool: ...
    @overload
    def is_a_submotif(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long) -> bool: ...
    @overload
    def is_a_submotif(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, check_other_poses: bool) -> bool: ...
    @overload
    def is_a_submotif_seed(self) -> bool: ...
    @overload
    def is_a_submotif_seed(self) -> bool: ...
    @overload
    def is_a_submotif_seed(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long) -> bool: ...
    @overload
    def is_a_submotif_seed(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, check_other_poses: bool) -> bool: ...
    def jump_pairs(self) -> pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t: ...
    def jump_res_map(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def other_pose_list(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t: ...
    def preferred_root_res(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def remove_other_pose_at_idx(self, idx: int) -> None: ...
    @overload
    def remove_other_pose_at_idx(self, constunsignedlong) -> void: ...
    def res_list(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def rna_anti_chi_res(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def rna_block_stack_above_res(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def rna_block_stack_below_res(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def rna_bulge_res(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def rna_sample_sugar_res(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def rna_syn_chi_res(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def rna_terminal_res(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def sample_res(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_full_model_parameters(self, setting) -> None: ...
    @overload
    def set_full_model_parameters(self, classstd) -> void: ...
    @overload
    def set_other_pose_list(self, setting: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t) -> None: ...
    @overload
    def set_other_pose_list(self, constclassutility) -> void: ...
    @overload
    def set_res_list(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_res_list(self, constclassutility) -> void: ...
    @overload
    def show_submotif_info_list(self) -> None: ...
    @overload
    def show_submotif_info_list(self, for_all_poses: bool) -> None: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def sub_to_full(self, res: pyrosetta.rosetta.utility.vector1_unsigned_long) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def sub_to_full(self, res: int) -> int: ...
    def submotif_info(self, *args, **kwargs): ...
    def submotif_info_containing_residues(self, *args, **kwargs): ...
    def submotif_info_list(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_full_model_info_SubMotifInfo_t: ...
    def twoprime_res(self) -> pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t: ...
    @overload
    def update_submotif_info_list(self) -> None: ...
    @overload
    def update_submotif_info_list(self) -> void: ...
    def working_res(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...

class FullModelParameterType:
    __members__: ClassVar[dict] = ...  # read-only
    ALIGNMENT_ANCHOR_RES: ClassVar[FullModelParameterType] = ...
    CALC_RMS: ClassVar[FullModelParameterType] = ...
    CUTPOINT_OPEN: ClassVar[FullModelParameterType] = ...
    CYCLIZE_RES: ClassVar[FullModelParameterType] = ...
    DISULFIDE: ClassVar[FullModelParameterType] = ...
    DOCK_DOMAIN: ClassVar[FullModelParameterType] = ...
    EXTRA_MINIMIZE: ClassVar[FullModelParameterType] = ...
    EXTRA_MINIMIZE_JUMP: ClassVar[FullModelParameterType] = ...
    FIVEPRIME_CAP: ClassVar[FullModelParameterType] = ...
    FIXED_DOMAIN: ClassVar[FullModelParameterType] = ...
    INPUT_DOMAIN: ClassVar[FullModelParameterType] = ...
    JUMP: ClassVar[FullModelParameterType] = ...
    LAST_TYPE: ClassVar[FullModelParameterType] = ...
    NO_TYPE: ClassVar[FullModelParameterType] = ...
    PREFERRED_ROOT: ClassVar[FullModelParameterType] = ...
    RNA_ANTI_CHI: ClassVar[FullModelParameterType] = ...
    RNA_BLOCK_STACK_ABOVE: ClassVar[FullModelParameterType] = ...
    RNA_BLOCK_STACK_BELOW: ClassVar[FullModelParameterType] = ...
    RNA_BULGE: ClassVar[FullModelParameterType] = ...
    RNA_NORTH_SUGAR: ClassVar[FullModelParameterType] = ...
    RNA_SAMPLE_SUGAR: ClassVar[FullModelParameterType] = ...
    RNA_SOUTH_SUGAR: ClassVar[FullModelParameterType] = ...
    RNA_SYN_CHI: ClassVar[FullModelParameterType] = ...
    RNA_TERMINAL: ClassVar[FullModelParameterType] = ...
    SAMPLE: ClassVar[FullModelParameterType] = ...
    TWOPRIME_RES: ClassVar[FullModelParameterType] = ...
    WORKING: ClassVar[FullModelParameterType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class FullModelParameters:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, full_sequence: str) -> None: ...
    @overload
    def __init__(self, full_sequence: str, cutpoint_open_in_full_model: pyrosetta.rosetta.utility.vector1_unsigned_long, res_numbers_in_pose: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, arg0: FullModelParameters) -> None: ...
    def assign(self) -> FullModelParameters: ...
    def chains_in_full_model(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def clone(self) -> FullModelParameters: ...
    def conventional_chains(self) -> pyrosetta.rosetta.utility.vector1_char: ...
    def conventional_numbering(self) -> pyrosetta.rosetta.utility.vector1_int: ...
    def conventional_segids(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def conventional_to_full(self, res_list: pyrosetta.rosetta.utility.vector1_int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def conventional_to_full(self, resnum_and_chain_and_segid: tuple[pyrosetta.rosetta.utility.vector1_int, pyrosetta.rosetta.utility.vector1_char, pyrosetta.rosetta.utility.vector1_std_string]) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def conventional_to_full(self, res_num: int) -> int: ...
    @overload
    def conventional_to_full(self, constint) -> unsignedlong: ...
    @overload
    def conventional_to_full(self, res_num: int, chain: str) -> int: ...
    @overload
    def conventional_to_full(self, res_num: int, chain: str, segid: str) -> int: ...
    @overload
    def conventional_to_full(self, constint, constchar, conststd) -> unsignedlong: ...
    def cst_set(self, *args, **kwargs): ...
    def cst_string(self) -> str: ...
    def full_annotated_sequence(self) -> str: ...
    def full_model_pose_for_constraints(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    def full_sequence(self) -> str: ...
    @overload
    def full_to_conventional(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long) -> pyrosetta.rosetta.utility.vector1_int: ...
    @overload
    def full_to_conventional(self, res_num: int) -> int: ...
    @overload
    def full_to_conventional(self, constunsignedlong) -> int: ...
    @overload
    def full_to_conventional_resnum_and_chain_and_segid(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long) -> tuple[pyrosetta.rosetta.utility.vector1_int, pyrosetta.rosetta.utility.vector1_char, pyrosetta.rosetta.utility.vector1_std_string]: ...
    @overload
    def full_to_conventional_resnum_and_chain_and_segid(self, res_num: int) -> tuple[int, str, str]: ...
    def get_parameter(self, type: FullModelParameterType) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def get_parameter_as_res_lists(self, type: FullModelParameterType) -> pyrosetta.rosetta.std.map_unsigned_long_utility_vector1_unsigned_long_t_std_allocator_std_pair_const_unsigned_long_utility_vector1_unsigned_long_t: ...
    @overload
    def get_res_list(self, type: FullModelParameterType, value: int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def get_res_list(self, type: FullModelParameterType) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def get_res_list_as_pairs(self, type: FullModelParameterType) -> pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t: ...
    def global_mapping(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def global_sequence(self) -> str: ...
    @overload
    def has_conventional_residue(self, res_num: int) -> bool: ...
    @overload
    def has_conventional_residue(self, constint) -> bool: ...
    @overload
    def has_conventional_residue(self, res_num: int, chain: str) -> bool: ...
    @overload
    def has_conventional_residue(self, res_num: int, chain: str, segid: str) -> bool: ...
    @overload
    def has_conventional_residue(self, constint, constchar, conststd) -> bool: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def non_standard_residue_map(self) -> pyrosetta.rosetta.std.map_unsigned_long_std_string: ...
    def non_standard_residue_map_nonconst(self) -> pyrosetta.rosetta.std.map_unsigned_long_std_string: ...
    def parent_full_model_parameters(self) -> FullModelParameters: ...
    @overload
    def read_cst_file(self, cst_file: str) -> None: ...
    @overload
    def read_cst_file(self, conststd) -> void: ...
    @overload
    def read_disulfides(self, disulfide_file: str) -> None: ...
    @overload
    def read_disulfides(self, conststd) -> void: ...
    @overload
    def read_global_seq_info(self, global_seq_file: str) -> None: ...
    @overload
    def read_global_seq_info(self, conststd) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_conventional_chains(self, setting: pyrosetta.rosetta.utility.vector1_char) -> None: ...
    @overload
    def set_conventional_chains(self, constclassutility) -> void: ...
    @overload
    def set_conventional_numbering(self, setting: pyrosetta.rosetta.utility.vector1_int) -> None: ...
    @overload
    def set_conventional_numbering(self, constclassutility) -> void: ...
    @overload
    def set_conventional_segids(self, setting: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_conventional_segids(self, constclassutility) -> void: ...
    @overload
    def set_cst_string(self, setting: str) -> None: ...
    @overload
    def set_cst_string(self, conststd) -> void: ...
    @overload
    def set_non_standard_residue_map(self, setting: pyrosetta.rosetta.std.map_unsigned_long_std_string) -> None: ...
    @overload
    def set_non_standard_residue_map(self, constclassstd, std) -> void: ...
    @overload
    def set_parameter(self, type: FullModelParameterType, setting: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_parameter(self, constenumcore, constclassutility) -> void: ...
    @overload
    def set_parameter_as_res_list(self, type: FullModelParameterType, setting: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_parameter_as_res_list(self, constenumcore, constclassutility) -> void: ...
    @overload
    def set_parameter_as_res_list_in_pairs(self, type: FullModelParameterType, setting: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_parameter_as_res_list_in_pairs(self, constenumcore, constclassutility) -> void: ...
    @overload
    def set_parameter_as_res_lists(self, type: FullModelParameterType, setting: pyrosetta.rosetta.std.map_unsigned_long_utility_vector1_unsigned_long_t_std_allocator_std_pair_const_unsigned_long_utility_vector1_unsigned_long_t) -> None: ...
    @overload
    def set_parameter_as_res_lists(self, constenumcore, constclassstd, classutility) -> void: ...
    @overload
    def set_parent_full_model_parameters(self, setting: FullModelParameters) -> None: ...
    @overload
    def set_parent_full_model_parameters(self, classstd) -> void: ...
    @overload
    def set_slice_res_list(self, setting: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_slice_res_list(self, constclassutility) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def slice(self, slice_res: pyrosetta.rosetta.utility.vector1_unsigned_long) -> FullModelParameters: ...
    def slice_res_list(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def update_pose_and_cst_set_from_cst_string(self, rsd_type_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def update_pose_and_cst_set_from_cst_string(self, constclasscore) -> void: ...

class SubMotifInfo:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, tag: str) -> None: ...
    @overload
    def __init__(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, tag: str, seed: bool) -> None: ...
    @overload
    def __init__(self, arg0: SubMotifInfo) -> None: ...
    def assign(self) -> SubMotifInfo: ...
    def clone(self) -> SubMotifInfo: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def res_list(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def res_list(self, index: int) -> int: ...
    @overload
    def res_list(self, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def res_list(self, constclassutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def seed(self) -> bool: ...
    @overload
    def seed(self, seed: bool) -> None: ...
    @overload
    def sorted_res_list(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def sorted_res_list(self, index: int) -> int: ...
    @overload
    def tag(self) -> str: ...
    @overload
    def tag(self, tag: str) -> None: ...
    @overload
    def tag(self, conststd) -> void: ...

@overload
def add_new_sequence_into_global_sequence(pose: pyrosetta.rosetta.core.pose.Pose, current_global_sequence: str) -> None: ...
@overload
def add_new_sequence_into_global_sequence(constclasscore, std) -> void: ...
@overload
def append_virtual_residue_to_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def append_virtual_residue_to_full_model_info(classcore) -> void: ...
@overload
def check_all_residues_sampled(pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
@overload
def check_all_residues_sampled(constclasscore) -> bool: ...
@overload
def check_full_model_info_OK(pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
@overload
def check_full_model_info_OK(constclasscore) -> bool: ...
@overload
def check_sample_sugar_in_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose, i: int) -> bool: ...
@overload
def check_sample_sugar_in_full_model_info(constclasscore, constunsignedlong) -> bool: ...
def const_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose) -> FullModelInfo: ...
def figure_out_chain_numbers_from_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def figure_out_chain_numbers_from_full_model_info_const(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def figure_out_conventional_chains_from_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_char: ...
def figure_out_conventional_segids_from_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_std_string: ...
def figure_out_dock_domain_map_from_full_model_info_const(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def figure_out_pose_domain_map(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def figure_out_pose_domain_map_const(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def full_model_info_defined(pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
@overload
def full_model_info_defined(constclasscore) -> bool: ...
def full_model_parameter_type_from_string(name: str) -> FullModelParameterType: ...
@overload
def full_model_size(pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
@overload
def full_model_size(classcore) -> unsignedlong: ...
@overload
def full_to_sub(i: int, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
@overload
def full_to_sub(constunsignedlong, constclasscore) -> unsignedlong: ...
@overload
def full_to_sub(res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_chain_connections(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t: ...
def get_chain_for_full_model_resnum(resnum: int, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
def get_chain_for_resnum(resnum: int, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
def get_chains_from_cutpoint_open(cutpoint_open: pyrosetta.rosetta.utility.vector1_unsigned_long, nres: int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_chains_from_pdb_info(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_char: ...
def get_chains_full(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_connection_domains(chain_connections: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t, nchains: int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_current_global_sequence(pose: pyrosetta.rosetta.core.pose.Pose) -> str: ...
@overload
def get_current_global_sequence(resvect: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t, global_mapping: pyrosetta.rosetta.utility.vector1_unsigned_long, res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, native_sequence: str) -> str: ...
def get_cutpoint_open_from_chains(chains: pyrosetta.rosetta.utility.vector1_unsigned_long) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_fixed_domain_from_full_model_info_const(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_input_domain_from_full_model_info_const(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_move_elements_from_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t: ...
def get_move_elements_from_full_model_info_const(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t: ...
def get_moving_res_from_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_moving_res_from_full_model_info_const(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_number_missing_residues_and_connections(pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
@overload
def get_number_missing_residues_and_connections(classcore) -> unsignedlong: ...
@overload
def get_number_missing_residues_and_connections(pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
@overload
def get_number_missing_residues_and_connections(constclasscore) -> unsignedlong: ...
@overload
def get_number_missing_residues_and_connections(pose: pyrosetta.rosetta.core.pose.Pose, missing_residues: pyrosetta.rosetta.utility.vector1_char) -> int: ...
@overload
def get_number_missing_residues_and_connections(constclasscore, classutility) -> unsignedlong: ...
@overload
def get_number_missing_residues_and_connections(pose: pyrosetta.rosetta.core.pose.Pose, loop_suites: pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t) -> int: ...
@overload
def get_number_missing_residues_and_connections(constclasscore, classutility) -> unsignedlong: ...
@overload
def get_number_missing_residues_and_connections(pose: pyrosetta.rosetta.core.pose.Pose, missing_residues: pyrosetta.rosetta.utility.vector1_char, loop_suites: pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t) -> int: ...
def get_res_list_const(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_res_list_from_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_res_list_from_full_model_info_const(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_res_num_from_pdb_info(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_int: ...
def get_residue(seqpos_in_full_model: int, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.conformation.Residue: ...
def get_sample_res_for_pose(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_segids_from_pdb_info(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def initialize_parameters(full_model_parameters) -> None: ...
@overload
def initialize_parameters(classcore) -> void: ...
def make_sure_full_model_info_is_setup(pose: pyrosetta.rosetta.core.pose.Pose) -> FullModelInfo: ...
def nonconst_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose) -> FullModelInfo: ...
@overload
def reorder_full_model_info_after_append(pose: pyrosetta.rosetta.core.pose.Pose, res_to_add: int) -> None: ...
@overload
def reorder_full_model_info_after_append(pose: pyrosetta.rosetta.core.pose.Pose, res_to_add: int, offset: int) -> None: ...
@overload
def reorder_full_model_info_after_delete(pose: pyrosetta.rosetta.core.pose.Pose, res_to_delete: int) -> None: ...
@overload
def reorder_full_model_info_after_delete(classcore, constunsignedlong) -> void: ...
@overload
def reorder_full_model_info_after_prepend(pose: pyrosetta.rosetta.core.pose.Pose, res_to_add: int) -> None: ...
@overload
def reorder_full_model_info_after_prepend(pose: pyrosetta.rosetta.core.pose.Pose, res_to_add: int, offset: int) -> None: ...
@overload
def set_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose, full_model_info: FullModelInfo) -> None: ...
@overload
def set_full_model_info(classcore, classstd) -> void: ...
@overload
def sub_to_full(i: int, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
@overload
def sub_to_full(constunsignedlong, constclasscore) -> unsignedlong: ...
@overload
def sub_to_full(res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def to_string(type: FullModelParameterType) -> str: ...
@overload
def update_constraint_set_from_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def update_constraint_set_from_full_model_info(classcore) -> void: ...
@overload
def update_disulfides_from_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def update_disulfides_from_full_model_info(classcore) -> void: ...
@overload
def update_full_model_info_from_pose(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def update_full_model_info_from_pose(classcore) -> void: ...
@overload
def update_pdb_info_from_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def update_pdb_info_from_full_model_info(classcore) -> void: ...
@overload
def update_pose_objects_from_full_model_info(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def update_pose_objects_from_full_model_info(classcore) -> void: ...
@overload
def update_res_list_in_full_model_info_and_pdb_info(pose: pyrosetta.rosetta.core.pose.Pose, res_list_new: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
@overload
def update_res_list_in_full_model_info_and_pdb_info(classcore, constclassutility) -> void: ...
