import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.std
from typing import overload

class ReferencePose:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ReferencePose) -> None: ...
    @overload
    def __init__(self, arg0: ReferencePose) -> None: ...
    def assign(self) -> ReferencePose: ...
    def clone(self) -> ReferencePose: ...
    @overload
    def corresponding_residue_in_current(self, res_in_ref: int) -> int: ...
    @overload
    def corresponding_residue_in_current(self, constunsignedlong) -> unsignedlong: ...
    @overload
    def decrement_reference_pose_mapping_after_seqpos(self, seqpos: int) -> None: ...
    @overload
    def decrement_reference_pose_mapping_after_seqpos(self, constunsignedlong) -> void: ...
    def get_self_ptr(self) -> ReferencePose: ...
    def get_self_weak_ptr(self) -> pyrosetta.rosetta.std.weak_ptr_core_pose_reference_pose_ReferencePose_t: ...
    @overload
    def increment_reference_pose_mapping_after_seqpos(self, seqpos: int) -> None: ...
    @overload
    def increment_reference_pose_mapping_after_seqpos(self, constunsignedlong) -> void: ...
    @overload
    def initialize_residue_map_from_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def initialize_residue_map_from_pose(self, constclasscore) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def stores_residue_map(self) -> bool: ...
    @overload
    def stores_residue_map(self) -> bool: ...
    @overload
    def zero_reference_pose_mapping_at_seqpos(self, seqpos: int) -> None: ...
    @overload
    def zero_reference_pose_mapping_at_seqpos(self, constunsignedlong) -> void: ...

class ReferencePoseSet:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ReferencePoseSet) -> None: ...
    @overload
    def __init__(self, arg0: ReferencePoseSet) -> None: ...
    @overload
    def add_and_initialize_reference_pose(self, key_string: str, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def add_and_initialize_reference_pose(self, key_string: str, pose: pyrosetta.rosetta.core.pose.Pose, override_current: bool) -> None: ...
    @overload
    def add_and_initialize_reference_pose(self, conststd, constclasscore, bool) -> void: ...
    def assign(self) -> ReferencePoseSet: ...
    def clone(self) -> ReferencePoseSet: ...
    @overload
    def corresponding_residue_in_current(self, res_index_in_ref: int, ref_pose_key_string: str) -> int: ...
    @overload
    def corresponding_residue_in_current(self, constunsignedlong, conststd) -> unsignedlong: ...
    @overload
    def decrement_reference_pose_mapping_after_seqpos(self, seqpos: int) -> None: ...
    @overload
    def decrement_reference_pose_mapping_after_seqpos(self, constunsignedlong) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def get_self_ptr(self) -> ReferencePoseSet: ...
    def get_self_weak_ptr(self) -> pyrosetta.rosetta.std.weak_ptr_core_pose_reference_pose_ReferencePoseSet_t: ...
    @overload
    def increment_reference_pose_mapping_after_seqpos(self, seqpos: int) -> None: ...
    @overload
    def increment_reference_pose_mapping_after_seqpos(self, constunsignedlong) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def n_reference_pose(self) -> int: ...
    @overload
    def n_reference_pose(self) -> unsignedlong: ...
    def reference_pose(self, key_string: str) -> ReferencePose: ...
    def reference_pose_cop(self, key_string: str) -> ReferencePose: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def zero_reference_pose_mapping_at_seqpos(self, seqpos: int) -> None: ...
    @overload
    def zero_reference_pose_mapping_at_seqpos(self, constunsignedlong) -> void: ...
