import pyrosetta.rosetta.ObjexxFCL
import pyrosetta.rosetta.core.conformation.symmetry
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.utility
from typing import overload

def extract_asymmetric_unit(*args, **kwargs): ...
def extract_asymmetric_unit_pdb_info(pose: pyrosetta.rosetta.core.pose.Pose, pdb_info_src: pyrosetta.rosetta.core.pose.PDBInfo, pdb_info_target: pyrosetta.rosetta.core.pose.PDBInfo) -> None: ...
@overload
def find_new_symmetric_jump_residues(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def find_new_symmetric_jump_residues(classcore) -> void: ...
@overload
def find_symmetric_basejump_anchor(pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
@overload
def find_symmetric_basejump_anchor(classcore) -> int: ...
def get_asymmetric_pose_copy_from_symmetric_pose(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.pose.Pose: ...
def get_buildingblock_and_neighbor_subs(pose_in: pyrosetta.rosetta.core.pose.Pose, intra_subs: pyrosetta.rosetta.utility.vector1_unsigned_long) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_component_lower_bound(pose: pyrosetta.rosetta.core.pose.Pose, c: str) -> int: ...
@overload
def get_component_lower_bound(constclasscore, char) -> unsignedlong: ...
@overload
def get_component_of_residue(pose: pyrosetta.rosetta.core.pose.Pose, ir: int) -> str: ...
@overload
def get_component_of_residue(constclasscore, unsignedlong) -> char: ...
@overload
def get_component_upper_bound(pose: pyrosetta.rosetta.core.pose.Pose, c: str) -> int: ...
@overload
def get_component_upper_bound(constclasscore, char) -> unsignedlong: ...
@overload
def get_full_intracomponent_and_neighbor_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_full_intracomponent_and_neighbor_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_full_intracomponent_and_neighbor_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_full_intracomponent_and_neighbor_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_full_intracomponent_and_neighbor_subs(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def get_full_intracomponent_and_neighbor_subs(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def get_full_intracomponent_neighbor_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_full_intracomponent_neighbor_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_full_intracomponent_neighbor_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_full_intracomponent_neighbor_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_full_intracomponent_neighbor_subs(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def get_full_intracomponent_neighbor_subs(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.utility.vector1_std_string: ...
def get_full_intracomponent_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_full_intracomponent_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.core.pose.Pose: ...
def get_full_intracomponent_subs(pose: pyrosetta.rosetta.core.pose.Pose, jname: str) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def get_intracomponent_and_interneighbor_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_intracomponent_and_interneighbor_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_intracomponent_and_interneighbor_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_intracomponent_and_interneighbor_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_intracomponent_and_interneighbor_subs(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def get_intracomponent_and_interneighbor_subs(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def get_intracomponent_and_intraneighbor_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_intracomponent_and_intraneighbor_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_intracomponent_and_intraneighbor_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_intracomponent_and_intraneighbor_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_intracomponent_and_intraneighbor_subs(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def get_intracomponent_and_intraneighbor_subs(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def get_intracomponent_and_neighbor_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_intracomponent_and_neighbor_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_intracomponent_and_neighbor_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_intracomponent_and_neighbor_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_intracomponent_and_neighbor_subs(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def get_intracomponent_and_neighbor_subs(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def get_intracomponent_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_intracomponent_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_intracomponent_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_intracomponent_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_intracomponent_subs(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def get_intracomponent_subs(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.utility.vector1_std_string: ...
def get_jump_name_to_components(pose: pyrosetta.rosetta.core.pose.Pose, jname: str) -> pyrosetta.rosetta.utility.vector1_char: ...
def get_jump_name_to_subunits(pose: pyrosetta.rosetta.core.pose.Pose, jname: str) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_neighbor_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_neighbor_resis(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_neighbor_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_neighbor_subpose(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_neighbor_subs(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def get_neighbor_subs(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def get_nres_asymmetric_unit(pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
@overload
def get_nres_asymmetric_unit(constclasscore) -> unsignedlong: ...
def get_resis(pose: pyrosetta.rosetta.core.pose.Pose, subs: pyrosetta.rosetta.utility.vector1_std_string) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_resnum_to_subunit_component(pose: pyrosetta.rosetta.core.pose.Pose, resnum: int) -> str: ...
def get_subpose(pose: pyrosetta.rosetta.core.pose.Pose, subs: pyrosetta.rosetta.utility.vector1_std_string) -> pyrosetta.rosetta.core.pose.Pose: ...
@overload
def get_subunit_name_to_component(pose: pyrosetta.rosetta.core.pose.Pose, vname: str) -> str: ...
@overload
def get_subunit_name_to_component(constclasscore, conststd) -> char: ...
@overload
def get_sym_aware_jump_num(pose: pyrosetta.rosetta.core.pose.Pose, jump_num: int) -> int: ...
@overload
def get_sym_aware_jump_num(constclasscore, unsignedlong) -> int: ...
def get_symdof_subunits(pose: pyrosetta.rosetta.core.pose.Pose, jname: str) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_symm_axis(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
@overload
def intracomponent_contact(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str) -> bool: ...
@overload
def intracomponent_contact(pose: pyrosetta.rosetta.core.pose.Pose, sym_dof_name: str, contact_dist: float) -> bool: ...
@overload
def intracomponent_contact(constclasscore, conststd, double) -> bool: ...
@overload
def is_mirror_symmetric(pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
@overload
def is_mirror_symmetric(constclasscore) -> bool: ...
@overload
def is_multicomponent(pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
@overload
def is_multicomponent(constclasscore) -> bool: ...
@overload
def is_singlecomponent(pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
@overload
def is_singlecomponent(constclasscore) -> bool: ...
@overload
def is_symmetric(pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
@overload
def is_symmetric(constclasscore) -> bool: ...
@overload
def is_symmetric(energies: pyrosetta.rosetta.core.scoring.Energies) -> bool: ...
@overload
def is_symmetric(constclasscore) -> bool: ...
def jump_num_sym_dof(pose: pyrosetta.rosetta.core.pose.Pose, jnum: int) -> str: ...
@overload
def make_asymmetric_pose(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def make_asymmetric_pose(classcore) -> void: ...
@overload
def make_residue_mask_symmetric(p: pyrosetta.rosetta.core.pose.Pose, msk: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
@overload
def make_residue_mask_symmetric(constclasscore, classutility) -> void: ...
@overload
def make_symmetric_movemap(pose: pyrosetta.rosetta.core.pose.Pose, movemap: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
@overload
def make_symmetric_movemap(constclasscore, classcore) -> void: ...
@overload
def make_symmetric_pdb_info(pose: pyrosetta.rosetta.core.pose.Pose, pdb_info_src: pyrosetta.rosetta.core.pose.PDBInfo, pdb_info_target: pyrosetta.rosetta.core.pose.PDBInfo) -> None: ...
@overload
def make_symmetric_pdb_info(pose: pyrosetta.rosetta.core.pose.Pose, pdb_info_src: pyrosetta.rosetta.core.pose.PDBInfo, pdb_info_target: pyrosetta.rosetta.core.pose.PDBInfo, keep_pdb_info_labels: bool) -> None: ...
@overload
def make_symmetric_pose(pose: pyrosetta.rosetta.core.pose.Pose, symmetry_info: pyrosetta.rosetta.core.conformation.symmetry.SymmetryInfo) -> None: ...
@overload
def make_symmetric_pose(pose: pyrosetta.rosetta.core.pose.Pose, symmdata: pyrosetta.rosetta.core.conformation.symmetry.SymmData) -> None: ...
@overload
def make_symmetric_pose(pose: pyrosetta.rosetta.core.pose.Pose, symmdata: pyrosetta.rosetta.core.conformation.symmetry.SymmData, keep_pdb_info_labels: bool) -> None: ...
@overload
def make_symmetric_pose(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def make_symmetric_pose(pose: pyrosetta.rosetta.core.pose.Pose, symmdef_file: str) -> None: ...
@overload
def make_symmetric_pose(classcore, std) -> void: ...
@overload
def partition_by_symm_jumps(jump_numbers: pyrosetta.rosetta.utility.vector1_int, ft: pyrosetta.rosetta.core.kinematics.FoldTree, symm_info: pyrosetta.rosetta.core.conformation.symmetry.SymmetryInfo, partner1: pyrosetta.rosetta.ObjexxFCL.FArray1D_bool_t) -> None: ...
@overload
def partition_by_symm_jumps(classutility, constclasscore, classstd, classObjexxFCL) -> void: ...
@overload
def rotate_anchor_to_x_axis(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def rotate_anchor_to_x_axis(classcore) -> void: ...
def sealed_symmetric_fold_tree(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
@overload
def set_asymm_unit_fold_tree(p: pyrosetta.rosetta.core.pose.Pose, f: pyrosetta.rosetta.core.kinematics.FoldTree) -> None: ...
@overload
def set_asymm_unit_fold_tree(classcore, constclasscore) -> void: ...
@overload
def sym_dof_jump_num(pose: pyrosetta.rosetta.core.pose.Pose, jname: str) -> int: ...
@overload
def sym_dof_jump_num(constclasscore, conststd) -> int: ...
def sym_dof_names(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_std_string: ...
def symmetric_components(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_char: ...
def symmetrize_fold_tree(*args, **kwargs): ...
def symmetry_info(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.conformation.symmetry.SymmetryInfo: ...
