import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.scoring.methods
import pyrosetta.rosetta.utility
from typing import overload

class PDDFEnergy(pyrosetta.rosetta.core.scoring.methods.WholeStructureEnergy):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PDDFEnergy) -> None: ...
    @overload
    def __init__(self, arg0: PDDFEnergy) -> None: ...
    def assign(self) -> PDDFEnergy: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    def compute_L1(self) -> float: ...
    def compute_chi(self) -> float: ...
    def compute_pddf(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    def compute_pddf_without_ff(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    def create_energy_method(self) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    def create_pddf(self) -> None: ...
    @overload
    def evaluate_pddf_energy(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def evaluate_pddf_energy(self, constclasscore) -> double: ...
    def finalize_total_energy(self, pose: pyrosetta.rosetta.core.pose.Pose, totals: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    def get_dist_bins(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    def get_pddf(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def indicate_required_context_graphs(self) -> None: ...
    @overload
    def indicate_required_context_graphs(self, classutility) -> void: ...

class PDDFEnergyCreator(pyrosetta.rosetta.core.scoring.methods.EnergyMethodCreator):
    def __init__(self) -> None: ...
    def assign(self) -> PDDFEnergyCreator: ...
    def create_energy_method(self) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    def score_types_for_method(self) -> pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType: ...
