import gemmi as gemmi
from _typeshed import Incomplete

def get_url_for_code(pdb_id: str, use_cif: bool = ..., pdb_site: str = ...) -> str: ...
def read_structure_with_code(pdb_id: str, use_cif: bool = ..., pdb_site: str = ...) -> Incomplete: ...
def main(): ...
