__version__: str

class MissingExternalDependencyError(Exception): ...
class MissingPythonDependencyError(MissingExternalDependencyError, ImportError): ...
class StreamModeError(ValueError): ...
class BiopythonWarning(Warning): ...
class BiopythonParserWarning(BiopythonWarning): ...
class BiopythonDeprecationWarning(BiopythonWarning): ...
class BiopythonExperimentalWarning(BiopythonWarning): ...
