import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.protocols.backbone_moves.local_backbone_mover
from typing import overload

class CircularPermuteFreePeptideMover(FreePeptideMover):
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, off_set: int, direction: bool) -> None: ...
    @overload
    def apply(self, free_peptide: pyrosetta.rosetta.protocols.backbone_moves.local_backbone_mover.FreePeptide) -> None: ...
    @overload
    def apply(self, classprotocols) -> void: ...

class FreePeptideMover:
    def __init__(self) -> None: ...
    @overload
    def apply(self, free_peptide: pyrosetta.rosetta.protocols.backbone_moves.local_backbone_mover.FreePeptide) -> None: ...
    @overload
    def apply(self, classprotocols) -> void: ...

class LongAxisRotationFreePeptideMover(FreePeptideMover):
    @overload
    def __init__(self, arg0: float) -> None: ...
    @overload
    def __init__(self, radian: float, random: bool) -> None: ...
    @overload
    def apply(self, free_peptide: pyrosetta.rosetta.protocols.backbone_moves.local_backbone_mover.FreePeptide) -> None: ...
    @overload
    def apply(self, classprotocols) -> void: ...

class ShearFreePeptideMover(FreePeptideMover):
    @overload
    def __init__(self, arg0: int, arg1: float) -> None: ...
    @overload
    def __init__(self, seqpos: int, torsion_degree: float, random: bool) -> None: ...
    @overload
    def apply(self, free_peptide: pyrosetta.rosetta.protocols.backbone_moves.local_backbone_mover.FreePeptide) -> None: ...
    @overload
    def apply(self, classprotocols) -> void: ...

class TranslationFreePeptideMover(FreePeptideMover):
    @overload
    def __init__(self, v_translate: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def __init__(self, max_amplitude: float) -> None: ...
    @overload
    def apply(self, free_peptide: pyrosetta.rosetta.protocols.backbone_moves.local_backbone_mover.FreePeptide) -> None: ...
    @overload
    def apply(self, classprotocols) -> void: ...
