import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.scoring.methods
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.protocols.stepwise.modeler.rna
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import overload

class RNA_AtrRepChecker:
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, working_parameters) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, working_parameters, loose_rep_cutoff: bool) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, working_parameters, loose_rep_cutoff: bool, energy_method_options: pyrosetta.rosetta.core.scoring.methods.EnergyMethodOptions) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, moving_res: int, reference_res: int, gap_size: int) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, moving_res: int, reference_res: int, gap_size: int, energy_method_options: pyrosetta.rosetta.core.scoring.methods.EnergyMethodOptions) -> None: ...
    @overload
    def __init__(self, arg0: RNA_AtrRepChecker) -> None: ...
    @overload
    def base_atr_score(self) -> float: ...
    @overload
    def base_atr_score(self) -> double: ...
    @overload
    def base_rep_score(self) -> float: ...
    @overload
    def base_rep_score(self) -> double: ...
    @overload
    def check_screen(self, current_pose_screen: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def check_screen(self, classcore) -> bool: ...
    def count_data(self) -> pyrosetta.rosetta.protocols.stepwise.modeler.rna.StepWiseRNA_CountStruct: ...
    @overload
    def delta_atr_score(self) -> float: ...
    @overload
    def delta_atr_score(self) -> double: ...
    @overload
    def delta_rep_score(self) -> float: ...
    @overload
    def delta_rep_score(self) -> double: ...
    def set_extra_loose_rep_cutoff(self, setting: bool) -> None: ...
    def set_loose_rep_cutoff(self, setting: bool) -> None: ...

class RNA_BaseCentroidChecker:
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, working_parameters) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, working_parameters, tether_jump: bool) -> None: ...
    @overload
    def __init__(self, arg0: RNA_BaseCentroidChecker) -> None: ...
    def allow_base_pair_only_screen(self) -> bool: ...
    @overload
    def check_centroid_interaction(self, moving_res_base_stub: pyrosetta.rosetta.core.kinematics.Stub, count_data: pyrosetta.rosetta.protocols.stepwise.modeler.rna.StepWiseRNA_CountStruct) -> bool: ...
    @overload
    def check_centroid_interaction(self, constclasscore, classprotocols) -> bool: ...
    @overload
    def check_that_terminal_res_are_unstacked(self) -> bool: ...
    @overload
    def check_that_terminal_res_are_unstacked(self, verbose: bool) -> bool: ...
    @overload
    def check_that_terminal_res_are_unstacked(self, constbool) -> bool: ...
    @overload
    def found_centroid_interaction(self) -> bool: ...
    @overload
    def found_centroid_interaction(self) -> bool: ...
    @overload
    def set_allow_base_pair_only_screen(self, setting: bool) -> None: ...
    @overload
    def set_allow_base_pair_only_screen(self, constbool) -> void: ...
    @overload
    def set_floating_base(self, setting: bool) -> None: ...
    @overload
    def set_floating_base(self, constbool) -> void: ...
    @overload
    def update_base_stub_list_and_check_centroid_interaction(self, pose: pyrosetta.rosetta.core.pose.Pose, count_data: pyrosetta.rosetta.protocols.stepwise.modeler.rna.StepWiseRNA_CountStruct) -> bool: ...
    @overload
    def update_base_stub_list_and_check_centroid_interaction(self, constclasscore, classprotocols) -> bool: ...
    @overload
    def update_base_stub_list_and_check_that_terminal_res_are_unstacked(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def update_base_stub_list_and_check_that_terminal_res_are_unstacked(self, pose: pyrosetta.rosetta.core.pose.Pose, reinitialize: bool) -> bool: ...
    @overload
    def update_base_stub_list_and_check_that_terminal_res_are_unstacked(self, constclasscore, constbool) -> bool: ...

class RNA_ChainClosableGeometryChecker:
    @overload
    def __init__(self, five_prime_chain_break_res: int, gap_size: int) -> None: ...
    @overload
    def __init__(self, five_prime_chain_break_res: int, three_prime_chain_break_res: int, gap_size: int) -> None: ...
    @overload
    def __init__(self, arg0: RNA_ChainClosableGeometryChecker) -> None: ...
    @overload
    def check_chain_closable_geometry(self, xyz_1: pyrosetta.rosetta.numeric.xyzVector_double_t, xyz_2: pyrosetta.rosetta.numeric.xyzVector_double_t) -> bool: ...
    @overload
    def check_chain_closable_geometry(self, five_prime_residue: pyrosetta.rosetta.core.conformation.Residue, three_prime_residue: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    @overload
    def check_screen(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def check_screen(self, pose: pyrosetta.rosetta.core.pose.Pose, strict: bool) -> bool: ...
    @overload
    def check_screen(self, constclasscore, constbool) -> bool: ...
    @overload
    def check_screen(self, moving_pose: pyrosetta.rosetta.core.pose.Pose, reference_pose: pyrosetta.rosetta.core.pose.Pose, is_prepend: bool) -> bool: ...
    @overload
    def check_screen(self, moving_pose: pyrosetta.rosetta.core.pose.Pose, reference_pose: pyrosetta.rosetta.core.pose.Pose, is_prepend: bool, strict: bool) -> bool: ...
    @overload
    def check_screen(self, pose: pyrosetta.rosetta.core.pose.Pose, rsd_at_origin_list: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_conformation_Residue_t, moving_res_base_stub: pyrosetta.rosetta.core.kinematics.Stub, reference_res: int) -> bool: ...
    @overload
    def check_screen(self, pose_data_list: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, rsd_at_origin_list: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_conformation_Residue_t, moving_res_base_stub: pyrosetta.rosetta.core.kinematics.Stub, reference_res: int) -> bool: ...
    def dist_squared(self) -> float: ...
    def five_prime_chain_break_res(self) -> int: ...
    def max_dist_squared(self) -> float: ...
    def three_prime_chain_break_res(self) -> int: ...

class RNA_ChainClosureChecker(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, five_prime_res: int) -> None: ...
    @overload
    def __init__(self, arg0: RNA_ChainClosureChecker) -> None: ...
    @overload
    def __init__(self, arg0: RNA_ChainClosureChecker) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    @overload
    def chain_break_screening_general(self, chain_break_screening_pose: pyrosetta.rosetta.core.pose.Pose, chainbreak_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, five_: int) -> bool: ...
    @overload
    def chain_break_screening_general(self, classcore, constclassstd, constunsignedlong) -> bool: ...
    @overload
    def check_loop_closed(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def check_loop_closed(self, constclasscore) -> bool: ...
    @overload
    def check_screen(self) -> bool: ...
    @overload
    def check_screen(self) -> bool: ...
    @overload
    def check_screen(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def check_screen(self, classcore) -> bool: ...
    @overload
    def copy_CCD_torsions(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def copy_CCD_torsions(self, classcore) -> void: ...
    def copy_CCD_torsions_general(self, pose: pyrosetta.rosetta.core.pose.Pose, five_prime_res: int, three_prime_res: int) -> None: ...
    def five_prime_res(self) -> int: ...
    def get_name(self) -> str: ...
    def pose(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    def set_reinitialize_CCD_torsions(self, setting: bool) -> None: ...

class RNA_VDW_BinChecker:
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RNA_VDW_BinChecker) -> None: ...
    @overload
    def FARFAR_setup_using_user_input_VDW_pose(self, VDW_rep_screen_pose_info: pyrosetta.rosetta.utility.vector1_std_string, const_working_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def FARFAR_setup_using_user_input_VDW_pose(self, constclassutility, constclasscore) -> void: ...
    @overload
    def FARFAR_setup_using_user_input_VDW_pose(self, All_VDW_rep_screen_pose_info: pyrosetta.rosetta.utility.vector1_std_string, const_working_pose: pyrosetta.rosetta.core.pose.Pose, include_side_chains: bool) -> None: ...
    @overload
    def FARFAR_setup_using_user_input_VDW_pose(self, constclassutility, constclasscore, constbool) -> void: ...
    @overload
    def VDW_rep_screen(self, screening_pose: pyrosetta.rosetta.core.pose.Pose, moving_res: int, rsd_at_origin: pyrosetta.rosetta.core.conformation.Residue, moving_res_base_stub: pyrosetta.rosetta.core.kinematics.Stub) -> bool: ...
    @overload
    def VDW_rep_screen(self, screening_pose: pyrosetta.rosetta.core.pose.Pose, moving_res: int) -> bool: ...
    @overload
    def VDW_rep_screen_with_act_pose(self, screening_pose: pyrosetta.rosetta.core.pose.Pose, moving_res_list: pyrosetta.rosetta.utility.vector1_unsigned_long) -> bool: ...
    @overload
    def VDW_rep_screen_with_act_pose(self, screening_pose: pyrosetta.rosetta.core.pose.Pose, moving_res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, local_verbose: bool) -> bool: ...
    @overload
    def VDW_rep_screen_with_act_pose(self, constclasscore, constclassutility, constbool) -> bool: ...
    @overload
    def align_working_pose(self, working_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def align_working_pose(self, classcore) -> void: ...
    @overload
    def create_VDW_screen_bin(self, pose: pyrosetta.rosetta.core.pose.Pose, ignore_res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, is_prepend: bool, reference_xyz: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def create_VDW_screen_bin(self, pose: pyrosetta.rosetta.core.pose.Pose, ignore_res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, is_prepend: bool, reference_xyz: pyrosetta.rosetta.numeric.xyzVector_double_t, verbose: bool) -> None: ...
    @overload
    def create_VDW_screen_bin(self, VDW_rep_screen_info_list: pyrosetta.rosetta.utility.vector1_core_pose_rna_VDW_RepScreenInfo, reference_xyz: pyrosetta.rosetta.numeric.xyzVector_double_t, verbose: bool) -> None: ...
    @overload
    def create_VDW_screen_bin(self, constclassutility, constclassnumeric, constbool) -> void: ...
    @overload
    def create_VDW_screen_bin(self, pose_list: pyrosetta.rosetta.utility.vector1_core_pose_Pose, list_of_ignore_res_list: pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t, list_of_is_prepend: pyrosetta.rosetta.utility.vector1_bool, reference_xyz: pyrosetta.rosetta.numeric.xyzVector_double_t, verbose: bool) -> None: ...
    def get_VDW_align_res(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def reference_xyz_consistency_check(self, inputted_reference_xyz: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def reference_xyz_consistency_check(self, constclassnumeric) -> void: ...
    def set_VDW_rep_alignment_RMSD_CUTOFF(self, setting: float) -> None: ...
    @overload
    def set_VDW_rep_delete_matching_res(self, setting: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_VDW_rep_delete_matching_res(self, constclassutility) -> void: ...
    @overload
    def set_num_clash_atom_cutoff(self, setting: int) -> None: ...
    @overload
    def set_num_clash_atom_cutoff(self, constunsignedlong) -> void: ...
    @overload
    def set_output_pdb(self, setting: bool) -> None: ...
    @overload
    def set_output_pdb(self, constbool) -> void: ...
    def set_physical_pose_clash_dist_cutoff(self, setting: float) -> None: ...
    @overload
    def setup_using_user_input_VDW_pose(self, All_VDW_rep_screen_pose_info: pyrosetta.rosetta.utility.vector1_std_string, const_working_pose: pyrosetta.rosetta.core.pose.Pose, working_parameters) -> None: ...
    @overload
    def setup_using_user_input_VDW_pose(self, constclassutility, constclasscore, constclassstd) -> void: ...
    @overload
    def setup_using_working_pose(self, const_working_pose: pyrosetta.rosetta.core.pose.Pose, working_parameters) -> None: ...
    @overload
    def setup_using_working_pose(self, constclasscore, constclassstd) -> void: ...
    @overload
    def setup_working_alignment(self, working_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def setup_working_alignment(self, classcore) -> void: ...
    @overload
    def update_VDW_screen_bin(self, pose: pyrosetta.rosetta.core.pose.Pose, ignore_res_list: pyrosetta.rosetta.utility.vector1_unsigned_long, is_prepend: bool, outfile_act: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def update_VDW_screen_bin(self, constclasscore, constclassutility, constbool, std) -> void: ...
    @overload
    def user_inputted_VDW_screen_pose(self) -> bool: ...
    @overload
    def user_inputted_VDW_screen_pose(self) -> bool: ...
