import pyrosetta.rosetta.ObjexxFCL
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.utility
from typing import overload

class O2PrimePacker(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: pyrosetta.rosetta.core.scoring.ScoreFunction, arg2: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, moving_res: pyrosetta.rosetta.utility.vector1_unsigned_long, pack_virtual_o2prime_hydrogen: bool) -> None: ...
    @overload
    def __init__(self, arg0: O2PrimePacker) -> None: ...
    @overload
    def __init__(self, arg0: O2PrimePacker) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    @overload
    def copy_all_o2prime_torsions(self, mod_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def copy_all_o2prime_torsions(self, classcore) -> void: ...
    def get_name(self) -> str: ...
    def pose(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    def sample_o2prime_hydrogen(self) -> None: ...
    @overload
    def sample_o2prime_hydrogen(self) -> void: ...
    @overload
    def set_partition_definition(self, setting: pyrosetta.rosetta.ObjexxFCL.FArray1D_bool_t) -> None: ...
    @overload
    def set_partition_definition(self, constclassObjexxFCL) -> void: ...
    def set_use_green_packer(self, setting: bool) -> None: ...
