import gudhi._nerve_gic_ext
from gudhi.simplex_tree import SimplexTree as SimplexTree

class CoverComplex(gudhi._nerve_gic_ext._Nerve_gic_interface):
    def __init__(self) -> None: ...
    def create_simplex_tree(self): ...
    def read_point_cloud(self, off_file): ...
    def set_color_from_file(self, color_file_name): ...
    def set_cover_from_file(self, cover_file_name): ...
    def set_function_from_file(self, func_file_name): ...
    def set_graph_from_file(self, graph_file_name): ...
