import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.optimization
import pyrosetta.rosetta.core.pack.annealer
import pyrosetta.rosetta.core.pack.rotamer_set
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.select.movemap
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.options
import pyrosetta.rosetta.utility.tag
from . import symmetry as symmetry
from typing import Any, overload

class BoltzmannRotamerMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, scorefxn_in: pyrosetta.rosetta.core.scoring.ScoreFunction, task_in: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def __init__(self, scorefxn_in: pyrosetta.rosetta.core.scoring.ScoreFunction, factory_in: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def __init__(self, arg0: BoltzmannRotamerMover) -> None: ...
    @overload
    def __init__(self, arg0: BoltzmannRotamerMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> BoltzmannRotamerMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def get_bias_sampling(self) -> bool: ...
    @overload
    def get_bias_sampling(self) -> bool: ...
    @overload
    def get_bump_check(self) -> bool: ...
    @overload
    def get_bump_check(self) -> bool: ...
    @overload
    def get_ligand_resnum(self) -> int: ...
    @overload
    def get_ligand_resnum(self) -> unsignedlong: ...
    @overload
    def get_ligand_weight(self) -> float: ...
    @overload
    def get_ligand_weight(self) -> double: ...
    def get_name(self) -> str: ...
    @overload
    def get_randomize_resnum(self) -> bool: ...
    @overload
    def get_randomize_resnum(self) -> bool: ...
    @overload
    def get_resnum(self) -> int: ...
    @overload
    def get_resnum(self) -> unsignedlong: ...
    def get_scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    def get_task(self) -> pyrosetta.rosetta.core.pack.task.PackerTask: ...
    @overload
    def get_temperature(self) -> float: ...
    @overload
    def get_temperature(self) -> double: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def select_rotamer(self, boltzmann_factors: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_double_t, partition_function: float) -> int: ...
    @overload
    def set_bias_sampling(self, bias_sampling: bool) -> None: ...
    @overload
    def set_bias_sampling(self, bool) -> void: ...
    @overload
    def set_bump_check(self, bump_check: bool) -> None: ...
    @overload
    def set_bump_check(self, bool) -> void: ...
    @overload
    def set_ligand_resnum(self, ligand_resnum: int) -> None: ...
    @overload
    def set_ligand_resnum(self, unsignedlong) -> void: ...
    @overload
    def set_ligand_weight(self, ligand_weight: float) -> None: ...
    @overload
    def set_ligand_weight(self, double) -> void: ...
    @overload
    def set_randomize_resnum(self, randomize_resnum: bool) -> None: ...
    @overload
    def set_randomize_resnum(self, bool) -> void: ...
    @overload
    def set_resnum(self, resnum: int) -> None: ...
    @overload
    def set_resnum(self, unsignedlong) -> void: ...
    @overload
    def set_score_function(self, sf: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_score_function(self, classstd) -> void: ...
    @overload
    def set_scorefxn(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn(self, classstd) -> void: ...
    @overload
    def set_task(self, task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def set_task(self, classstd) -> void: ...
    @overload
    def set_task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...
    @overload
    def set_temperature(self, temperature: float) -> None: ...
    @overload
    def set_temperature(self, double) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class BoltzmannRotamerMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: BoltzmannRotamerMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: BoltzmannRotamerMoverCreator) -> None: ...
    def assign(self) -> BoltzmannRotamerMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ChainGroupDiscriminator(GroupDiscriminator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ChainGroupDiscriminator) -> None: ...
    @overload
    def __init__(self, arg0: ChainGroupDiscriminator) -> None: ...
    def assign(self) -> ChainGroupDiscriminator: ...
    def clone(self) -> GroupDiscriminator: ...
    @overload
    def group_id(self, pose: pyrosetta.rosetta.core.pose.Pose, seqpos: int) -> int: ...
    @overload
    def group_id(self, constclasscore, unsignedlong) -> unsignedlong: ...

class DisulfideOptimizationMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DisulfideOptimizationMover) -> None: ...
    @overload
    def __init__(self, arg0: DisulfideOptimizationMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> DisulfideOptimizationMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def interaction_graph_threads(self) -> int: ...
    @overload
    def interaction_graph_threads(self) -> unsignedlong: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_final_optimization_n_iter(self, final_optimization_n_iter: int) -> None: ...
    @overload
    def set_final_optimization_n_iter(self, constunsignedlong) -> void: ...
    @overload
    def set_interaction_graph_threads(self, setting: int) -> None: ...
    @overload
    def set_interaction_graph_threads(self, constunsignedlong) -> void: ...
    @overload
    def set_score_function(self, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_score_function(self, constclassstd) -> void: ...
    @overload
    def set_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_selector(self, constclassstd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class DisulfideOptimizationMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DisulfideOptimizationMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: DisulfideOptimizationMoverCreator) -> None: ...
    def assign(self) -> DisulfideOptimizationMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class EnergyCutRotamerTrialsMinMover(RotamerTrialsMinMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, scorefxn_in: pyrosetta.rosetta.core.scoring.ScoreFunction, task_in: pyrosetta.rosetta.core.pack.task.PackerTask, mc_in: pyrosetta.rosetta.protocols.moves.MonteCarlo, energycut_in: float) -> None: ...
    @overload
    def __init__(self, scorefxn_in: pyrosetta.rosetta.core.scoring.ScoreFunction, factory_in: pyrosetta.rosetta.core.pack.task.TaskFactory, mc_in: pyrosetta.rosetta.protocols.moves.MonteCarlo, energycut_in: float) -> None: ...
    @overload
    def __init__(self, arg0: EnergyCutRotamerTrialsMinMover) -> None: ...
    @overload
    def __init__(self, arg0: EnergyCutRotamerTrialsMinMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> EnergyCutRotamerTrialsMinMover: ...
    def get_name(self) -> str: ...

class EnergyCutRotamerTrialsMover(RotamerTrialsMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, scorefxn_in: pyrosetta.rosetta.core.scoring.ScoreFunction, task_in: pyrosetta.rosetta.core.pack.task.PackerTask, mc_in: pyrosetta.rosetta.protocols.moves.MonteCarlo, energycut_in: float) -> None: ...
    @overload
    def __init__(self, scorefxn_in: pyrosetta.rosetta.core.scoring.ScoreFunction, factory_in: pyrosetta.rosetta.core.pack.task.TaskFactory, mc_in: pyrosetta.rosetta.protocols.moves.MonteCarlo, energycut_in: float) -> None: ...
    @overload
    def __init__(self, arg0: EnergyCutRotamerTrialsMover) -> None: ...
    @overload
    def __init__(self, arg0: EnergyCutRotamerTrialsMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> EnergyCutRotamerTrialsMover: ...
    def get_name(self) -> str: ...

class GreenPacker(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GreenPacker) -> None: ...
    @overload
    def __init__(self, arg0: GreenPacker) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> GreenPacker: ...
    def get_name(self) -> str: ...
    @overload
    def set_group_discriminator(self) -> None: ...
    @overload
    def set_group_discriminator(self, classstd) -> void: ...
    @overload
    def set_reference_round_task_factory(self) -> None: ...
    @overload
    def set_reference_round_task_factory(self, classstd) -> void: ...
    @overload
    def set_scorefunction(self) -> None: ...
    @overload
    def set_scorefunction(self, constclasscore) -> void: ...
    @overload
    def set_task_factory(self) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...

class GroupDiscriminator:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GroupDiscriminator) -> None: ...
    def assign(self) -> GroupDiscriminator: ...
    def clone(self) -> GroupDiscriminator: ...
    @overload
    def group_id(self, pose: pyrosetta.rosetta.core.pose.Pose, seqpos: int) -> int: ...
    @overload
    def group_id(self, constclasscore, unsignedlong) -> unsignedlong: ...

class MinMover(pyrosetta.rosetta.protocols.moves.MoveMapMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.kinematics.MoveMap, arg1: pyrosetta.rosetta.core.scoring.ScoreFunction, arg2: str, arg3: float, arg4: bool) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.kinematics.MoveMap, arg1: pyrosetta.rosetta.core.scoring.ScoreFunction, arg2: str, arg3: float, arg4: bool, arg5: bool) -> None: ...
    @overload
    def __init__(self, movemap_in: pyrosetta.rosetta.core.kinematics.MoveMap, scorefxn_in: pyrosetta.rosetta.core.scoring.ScoreFunction, min_type_in: str, tolerance_in: float, use_nb_list_in: bool, deriv_check_in: bool, deriv_check_verbose_in: bool) -> None: ...
    @overload
    def __init__(self, arg0: MinMover) -> None: ...
    @overload
    def __init__(self, arg0: MinMover) -> None: ...
    @overload
    def abs_score_convergence_threshold(self, newval: float) -> None: ...
    @overload
    def abs_score_convergence_threshold(self, double) -> void: ...
    @overload
    def abs_score_convergence_threshold(self) -> float: ...
    @overload
    def abs_score_convergence_threshold(self) -> double: ...
    @overload
    def abs_score_diff_after_minimization(self) -> float: ...
    @overload
    def abs_score_diff_after_minimization(self) -> double: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, pose) -> Any: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> MinMover: ...
    @overload
    def cartesian(self, newval: bool) -> None: ...
    @overload
    def cartesian(self, bool) -> void: ...
    @overload
    def cartesian(self) -> bool: ...
    @overload
    def cartesian(self) -> bool: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @staticmethod
    def complex_type_generator_for_min_mover(*args, **kwargs): ...
    @overload
    def deriv_check(self, deriv_check_in: bool) -> None: ...
    @overload
    def deriv_check(self, bool) -> void: ...
    @overload
    def deriv_check(self) -> bool: ...
    @overload
    def deriv_check(self) -> bool: ...
    def explicitly_set_movemap(self) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def max_iter(self, max_iter_in: int) -> None: ...
    @overload
    def max_iter(self, unsignedlong) -> void: ...
    @overload
    def min_options(self) -> pyrosetta.rosetta.core.optimization.MinimizerOptions: ...
    @overload
    def min_options(self, min_options: pyrosetta.rosetta.core.optimization.MinimizerOptions) -> None: ...
    @overload
    def min_options(self, classstd) -> void: ...
    @overload
    def min_type(self, min_type_in: str) -> None: ...
    @overload
    def min_type(self, std) -> void: ...
    @overload
    def min_type(self) -> str: ...
    @overload
    def movemap(self, movemap_in: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def movemap(self, movemap1) -> Any: ...
    @overload
    def movemap(self, classstd) -> void: ...
    @overload
    def movemap(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def movemap_factory(self, mmf: pyrosetta.rosetta.core.select.movemap.MoveMapFactory) -> None: ...
    @overload
    def movemap_factory(self, classstd) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def nb_list(self, nb_list_in: bool) -> None: ...
    @overload
    def nb_list(self, bool) -> void: ...
    @overload
    def nb_list(self) -> bool: ...
    @overload
    def nb_list(self) -> bool: ...
    @overload
    def omega(self) -> bool: ...
    @overload
    def omega(self) -> bool: ...
    @overload
    def omega(self, b: bool) -> None: ...
    @overload
    def omega(self, constbool) -> void: ...
    def parse_dof_task_type(self, tag_name: str, dof_type: pyrosetta.rosetta.core.id.DOF_Type, torsion_type: pyrosetta.rosetta.core.id.TorsionType, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_dof_tasks(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_dof_tasks(self, classstd, classbasic) -> void: ...
    @overload
    def parse_movemap_factory(self) -> None: ...
    @overload
    def parse_movemap_factory(self, classstd, classbasic) -> void: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def parse_opts(self, data_map: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_opts(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def score_diff_after_minimization(self) -> float: ...
    @overload
    def score_diff_after_minimization(self) -> double: ...
    @overload
    def score_function(self, scorefxn_in: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def score_function(self, scorefxn) -> Any: ...
    @overload
    def score_function(self, classstd) -> void: ...
    @overload
    def score_function(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def set_movemap(self, movemap_in: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def set_movemap(self, classstd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def tolerance(self, tolerance_in: float) -> None: ...
    @overload
    def tolerance(self, double) -> void: ...
    @overload
    def tolerance(self) -> float: ...
    @overload
    def tolerance(self) -> double: ...

class MinMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MinMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: MinMoverCreator) -> None: ...
    def assign(self) -> MinMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class MinPackMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def __init__(self, arg0: MinPackMover) -> None: ...
    @overload
    def __init__(self, arg0: MinPackMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> MinPackMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def init(self) -> None: ...
    @overload
    def init(self) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def off_rotamer_pack(self) -> None: ...
    @overload
    def off_rotamer_pack(self, bool) -> void: ...
    @overload
    def off_rotamer_pack(self) -> bool: ...
    @overload
    def off_rotamer_pack(self) -> bool: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def parse_score_function(self) -> None: ...
    @overload
    def parse_score_function(self, classstd, constclassbasic) -> void: ...
    @overload
    def parse_task_operations(self) -> None: ...
    @overload
    def parse_task_operations(self, classstd, constclassbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def score_function(self, sf: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def score_function(self, classstd) -> void: ...
    @overload
    def score_function(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def task(self, t: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def task(self, classstd) -> void: ...
    @overload
    def task(self) -> pyrosetta.rosetta.core.pack.task.PackerTask: ...
    @overload
    def task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def task_factory(self, classstd) -> void: ...
    @overload
    def task_factory(self) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    @overload
    def task_is_valid(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def task_is_valid(self, constclasscore) -> bool: ...

class MinPackMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MinPackMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: MinPackMoverCreator) -> None: ...
    def assign(self) -> MinPackMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class MinimalRotamer:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MinimalRotamer) -> None: ...
    def aa(self) -> pyrosetta.rosetta.core.chemical.AA: ...
    @overload
    def same(self) -> bool: ...
    @overload
    def same(self, constclassprotocols) -> bool: ...
    @overload
    def same_residue_type(self) -> bool: ...
    @overload
    def same_residue_type(self, constclassprotocols) -> bool: ...

class PackRotamersMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, options: pyrosetta.rosetta.utility.options.OptionCollection) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.scoring.ScoreFunction, arg1: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, task_factory: pyrosetta.rosetta.core.pack.task.TaskFactory, nloop: int) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.scoring.ScoreFunction, arg1: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, task: pyrosetta.rosetta.core.pack.task.PackerTask, nloop: int) -> None: ...
    @overload
    def __init__(self, arg0: PackRotamersMover) -> None: ...
    @overload
    def __init__(self, arg0: PackRotamersMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, pose) -> Any: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> PackRotamersMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @staticmethod
    def complex_type_generator_for_pack_rotamers_mover(*args, **kwargs): ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def initialize_task_factory_with_operations(self) -> None: ...
    @overload
    def initialize_task_factory_with_operations(self, constclassstd) -> void: ...
    @overload
    @staticmethod
    def list_options_read(opts: pyrosetta.rosetta.std.list_utility_keys_VariantKey_utility_options_OptionKey_t) -> None: ...
    @overload
    @staticmethod
    def list_options_read(classstd) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def nloop(self, nloop_in: int) -> None: ...
    @overload
    def nloop(self, unsignedlong) -> void: ...
    @overload
    def nloop(self) -> int: ...
    @overload
    def nloop(self) -> unsignedlong: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def parse_score_function(self) -> None: ...
    @overload
    def parse_score_function(self, classstd, constclassbasic) -> void: ...
    @overload
    def parse_task_operations(self) -> None: ...
    @overload
    def parse_task_operations(self, classstd, constclassbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def rotamer_sets(self) -> pyrosetta.rosetta.core.pack.rotamer_set.RotamerSets: ...
    @overload
    def score_function(self, sf: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def score_function(self, scorefxn) -> Any: ...
    @overload
    def score_function(self, classstd) -> void: ...
    @overload
    def score_function(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def score_function(self) -> Any: ...
    @overload
    def set_annealer_observer(self, observer: pyrosetta.rosetta.core.pack.annealer.AnnealerObserver) -> None: ...
    @overload
    def set_annealer_observer(self, classstd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def task(self, t: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def task(self, task_pack) -> Any: ...
    @overload
    def task(self, classstd) -> void: ...
    @overload
    def task(self) -> pyrosetta.rosetta.core.pack.task.PackerTask: ...
    @overload
    def task(self) -> Any: ...
    @overload
    def task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def task_factory(self, task_design) -> Any: ...
    @overload
    def task_factory(self, classstd) -> void: ...
    @overload
    def task_factory(self) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    @overload
    def task_factory(self) -> Any: ...
    @overload
    def task_is_valid(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def task_is_valid(self, constclasscore) -> bool: ...

class PackRotamersMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PackRotamersMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: PackRotamersMoverCreator) -> None: ...
    def assign(self) -> PackRotamersMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class PackRotamersMoverLazy(PackRotamersMover):
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.scoring.ScoreFunction, arg1: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, task: pyrosetta.rosetta.core.pack.task.PackerTask, nloop: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PackRotamersMoverLazy) -> None: ...
    @overload
    def __init__(self, arg0: PackRotamersMoverLazy) -> None: ...
    @overload
    def apply_to_rotpack(self, pose: pyrosetta.rosetta.core.pose.Pose, rot_to_pack: pyrosetta.rosetta.utility.vector0_int) -> None: ...
    @overload
    def apply_to_rotpack(self, classcore, classutility) -> void: ...
    def assign(self) -> PackRotamersMoverLazy: ...
    @overload
    def call_setup(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def call_setup(self, classcore) -> void: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...

class PackRotamersMoverLazyCreator(PackRotamersMoverCreator):
    def __init__(self) -> None: ...
    def assign(self) -> PackRotamersMoverLazyCreator: ...
    @staticmethod
    def mover_name() -> str: ...

class PertMinMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PertMinMover) -> None: ...
    @overload
    def __init__(self, arg0: PertMinMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> PertMinMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def min(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def min(self, classcore) -> void: ...
    def movemap(self) -> pyrosetta.rosetta.core.select.movemap.MoveMapFactory: ...
    @overload
    def movemap_factory(self, setting: pyrosetta.rosetta.core.select.movemap.MoveMapFactory) -> None: ...
    @overload
    def movemap_factory(self, classstd) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def pert(self, pose: pyrosetta.rosetta.core.pose.Pose, resi: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def pert(self, classcore, constclassutility) -> void: ...
    @overload
    def pert_size(self) -> float: ...
    @overload
    def pert_size(self) -> double: ...
    @overload
    def pert_size(self, setting: float) -> None: ...
    @overload
    def pert_size(self, double) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def residues(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    def residues(self, setting: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def residues(self, classstd) -> void: ...
    @overload
    def sc_only(self) -> bool: ...
    @overload
    def sc_only(self) -> bool: ...
    @overload
    def sc_only(self, setting: bool) -> None: ...
    @overload
    def sc_only(self, bool) -> void: ...
    @overload
    def scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def scorefxn(self, setting: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def scorefxn(self, classstd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def uniform(self) -> bool: ...
    @overload
    def uniform(self) -> bool: ...
    @overload
    def uniform(self, setting: bool) -> None: ...
    @overload
    def uniform(self, bool) -> void: ...

class PertMinMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PertMinMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: PertMinMoverCreator) -> None: ...
    def assign(self) -> PertMinMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class RepackSidechainsMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: RepackSidechainsMover) -> None: ...
    @overload
    def __init__(self, arg0: RepackSidechainsMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RepackSidechainsMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def parse_score_function(self) -> None: ...
    @overload
    def parse_score_function(self, classstd, constclassbasic) -> void: ...
    def scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def set_scorefxn(self, sf: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn(self, classstd) -> void: ...

class RepackSidechainsMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RepackSidechainsMoverCreator) -> None: ...
    def assign(self) -> RepackSidechainsMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...

class RotamerTrialsMinMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, scorefxn_in: pyrosetta.rosetta.core.scoring.ScoreFunction, task_in: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def __init__(self, scorefxn_in: pyrosetta.rosetta.core.scoring.ScoreFunction, factory_in: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def __init__(self, arg0: RotamerTrialsMinMover) -> None: ...
    @overload
    def __init__(self, arg0: RotamerTrialsMinMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RotamerTrialsMinMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def init(self) -> None: ...
    @overload
    def init(self) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def score_function(self, sf: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def score_function(self, classstd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def task_factory(self, classstd) -> void: ...

class RotamerTrialsMinMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RotamerTrialsMinMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: RotamerTrialsMinMoverCreator) -> None: ...
    def assign(self) -> RotamerTrialsMinMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class RotamerTrialsMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, scorefxn_in: pyrosetta.rosetta.core.scoring.ScoreFunction, task_in: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def __init__(self, scorefxn_in: pyrosetta.rosetta.core.scoring.ScoreFunction, factory_in: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def __init__(self, arg0: RotamerTrialsMover) -> None: ...
    @overload
    def __init__(self, arg0: RotamerTrialsMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RotamerTrialsMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @staticmethod
    def complex_type_generator_for_rotamer_trials_mover(*args, **kwargs): ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def score_function(self, sf: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def score_function(self, classstd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def task_factory(self, classstd) -> void: ...

class RotamerTrialsMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RotamerTrialsMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: RotamerTrialsMoverCreator) -> None: ...
    def assign(self) -> RotamerTrialsMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class RotamerizeMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def __init__(self, arg0: RotamerizeMover) -> None: ...
    @overload
    def __init__(self, arg0: RotamerizeMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RotamerizeMover: ...
    def get_name(self) -> str: ...
    def rotamer_sets(self) -> pyrosetta.rosetta.core.pack.rotamer_set.RotamerSets: ...
    @overload
    def task(self, t: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def task(self, classstd) -> void: ...
    @overload
    def task(self) -> pyrosetta.rosetta.core.pack.task.PackerTask: ...
    @overload
    def task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def task_factory(self, classstd) -> void: ...
    @overload
    def task_factory(self) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    @overload
    def task_is_valid(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def task_is_valid(self, constclasscore) -> bool: ...

class SaneMinMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, name: str) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.kinematics.MoveMap, arg1: pyrosetta.rosetta.core.scoring.ScoreFunction, arg2: pyrosetta.rosetta.core.optimization.MinimizerOptions) -> None: ...
    @overload
    def __init__(self, movemap_in: pyrosetta.rosetta.core.kinematics.MoveMap, scorefxn_in: pyrosetta.rosetta.core.scoring.ScoreFunction, min_options_in: pyrosetta.rosetta.core.optimization.MinimizerOptions, cartesian: bool) -> None: ...
    @overload
    def __init__(self, arg0: SaneMinMover) -> None: ...
    @overload
    def __init__(self, arg0: SaneMinMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> SaneMinMover: ...
    @overload
    def cartesian(self) -> bool: ...
    @overload
    def cartesian(self) -> bool: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    def min_options(self) -> pyrosetta.rosetta.core.optimization.MinimizerOptions: ...
    def move_map(self) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def score_function(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...

class SaneMinMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SaneMinMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: SaneMinMoverCreator) -> None: ...
    def assign(self) -> SaneMinMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SetReturningPackRotamersMover(PackRotamersMover):
    @overload
    def __init__(self, ndruns: int) -> None: ...
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, task: pyrosetta.rosetta.core.pack.task.PackerTask, ndruns: int) -> None: ...
    @overload
    def __init__(self, arg0: SetReturningPackRotamersMover) -> None: ...
    @overload
    def __init__(self, arg0: SetReturningPackRotamersMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> SetReturningPackRotamersMover: ...
    def get_name(self) -> str: ...
    @overload
    def get_repacked_poses(self, v: pyrosetta.rosetta.utility.vector1_core_pose_Pose) -> None: ...
    @overload
    def get_repacked_poses(self, classutility) -> void: ...
    @overload
    def output_repacked_poses(self, filename_prefix: str) -> None: ...
    @overload
    def output_repacked_poses(self, std) -> void: ...

class TaskAwareMinMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, minmover_in: MinMover, factory_in: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def __init__(self, minmover_in: MinMover, task_in: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def __init__(self, arg0: TaskAwareMinMover) -> None: ...
    @overload
    def __init__(self, arg0: TaskAwareMinMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> TaskAwareMinMover: ...
    @overload
    def bb(self, val: bool) -> None: ...
    @overload
    def bb(self, bool) -> void: ...
    @overload
    def bb(self) -> bool: ...
    @overload
    def bb(self) -> bool: ...
    @overload
    def chi(self, val: bool) -> None: ...
    @overload
    def chi(self, bool) -> void: ...
    @overload
    def chi(self) -> bool: ...
    @overload
    def chi(self) -> bool: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def jump(self, j: bool) -> None: ...
    @overload
    def jump(self, constbool) -> void: ...
    @overload
    def jump(self) -> bool: ...
    @overload
    def jump(self) -> bool: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def parse_task_operations(self) -> None: ...
    @overload
    def parse_task_operations(self, classstd, constclassbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class TaskAwareMinMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TaskAwareMinMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: TaskAwareMinMoverCreator) -> None: ...
    def assign(self) -> TaskAwareMinMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class UserDefinedGroupDiscriminator(GroupDiscriminator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: UserDefinedGroupDiscriminator) -> None: ...
    @overload
    def __init__(self, arg0: UserDefinedGroupDiscriminator) -> None: ...
    def assign(self) -> UserDefinedGroupDiscriminator: ...
    def clone(self) -> GroupDiscriminator: ...
    @overload
    def group_id(self, pose: pyrosetta.rosetta.core.pose.Pose, seqpos: int) -> int: ...
    @overload
    def group_id(self, constclasscore, unsignedlong) -> unsignedlong: ...
    @overload
    def set_group_ids(self, group_ids_input: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_group_ids(self, constclassutility) -> void: ...
