import functools
from _typeshed import Incomplete
from pyrosetta.distributed import requires_init
from pyrosetta.distributed.packed_pose import pack_result as pack_result, pose_result as pose_result, to_base64 as to_base64, to_pickle as to_pickle

__all__ = ['pack_result', 'pose_result', 'pose_from_file', 'pose_from_sequence', 'pose_from_pdbstring', 'pose_from_pdb', 'pose_from_base64', 'pose_from_pickle', 'poses_from_files', 'poses_from_sequences', 'poses_from_multimodel_pdb', 'poses_from_silent', 'to_base64', 'to_pickle', 'to_silent', 'to_pdbstring', 'to_output_recorddump_file', 'dump_pdb', 'dump_scored_pdb', 'dump_multimodel_pdb', 'dump_cif', 'dump_mmtf', 'dump_base64', 'dump_pickle', 'create_score_function', 'get_fa_scorefxn', 'get_score_function']

@requires_init
@pack_result
def pose_from_file(*args, **kwargs): ...

pose_from_sequence: Incomplete
poses_from_files: Incomplete
poses_from_sequences: Incomplete
poses_from_silent: Incomplete
poses_from_multimodel_pdb: Incomplete

@requires_init
@pack_result
def pose_from_pdbstring(*args, **kwargs): ...
@functools.singledispatch
@requires_init
@pack_result
def pose_from_pdb(*args, **kwargs): ...
@functools.singledispatch
def pose_from_base64(filename) -> None: ...
@functools.singledispatch
def pose_from_pickle(filename) -> None: ...
@functools.singledispatch
@requires_init
def to_silent(inp, output_filename) -> None: ...
@functools.singledispatch
@requires_init
def to_pdbstring(inp): ...
@requires_init
def dump_pdb(inp, output_filename): ...
@requires_init
def dump_scored_pdb(inp, output_filename, scorefxn): ...
@requires_init
def dump_multimodel_pdb(inp, output_filename): ...
@requires_init
def dump_cif(inp, output_filename): ...
@requires_init
def dump_mmtf(inp, output_filename): ...
@requires_init
def dump_base64(inp, output_filename): ...
@requires_init
def dump_pickle(inp, output_filename): ...
def create_score_function(*args, **kwargs): ...
def get_fa_scorefxn(): ...
def get_score_function(): ...

# Names in __all__ with no definition:
#   to_output_recorddump_file
