import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.graph
from typing import overload

class AtomInfo:
    @overload
    def __init__(self, atomid: int, atom_position: pyrosetta.rosetta.numeric.xyzVector_float_t, is_hydrogen_setting: bool, is_donor_setting: bool, is_acceptor_setting: bool, is_hydroxyl_setting: bool, is_backbone_setting: bool) -> None: ...
    @overload
    def __init__(self, arg0: AtomInfo) -> None: ...
    def assign(self) -> AtomInfo: ...
    @overload
    def is_acceptor(self, setting: bool) -> None: ...
    @overload
    def is_acceptor(self, bool) -> void: ...
    @overload
    def is_acceptor(self) -> bool: ...
    @overload
    def is_acceptor(self) -> bool: ...
    @overload
    def is_backbone(self, setting: bool) -> None: ...
    @overload
    def is_backbone(self, bool) -> void: ...
    @overload
    def is_backbone(self) -> bool: ...
    @overload
    def is_backbone(self) -> bool: ...
    @overload
    def is_donor(self, setting: bool) -> None: ...
    @overload
    def is_donor(self, bool) -> void: ...
    @overload
    def is_donor(self) -> bool: ...
    @overload
    def is_donor(self) -> bool: ...
    @overload
    def is_hydrogen(self, setting: bool) -> None: ...
    @overload
    def is_hydrogen(self, bool) -> void: ...
    @overload
    def is_hydrogen(self) -> bool: ...
    @overload
    def is_hydrogen(self) -> bool: ...
    @overload
    def is_hydroxyl(self, setting: bool) -> None: ...
    @overload
    def is_hydroxyl(self, bool) -> void: ...
    @overload
    def is_hydroxyl(self) -> bool: ...
    @overload
    def is_hydroxyl(self) -> bool: ...
    @overload
    def local_atom_id(self, local_atom_id: int) -> None: ...
    @overload
    def local_atom_id(self, unsignedshort) -> void: ...
    @overload
    def local_atom_id(self) -> int: ...
    @overload
    def local_atom_id(self) -> unsignedshort: ...
    @overload
    def xyz(self, setting: pyrosetta.rosetta.numeric.xyzVector_float_t) -> None: ...
    @overload
    def xyz(self, constclassnumeric) -> void: ...
    @overload
    def xyz(self) -> pyrosetta.rosetta.numeric.xyzVector_float_t: ...

class AtomInfoSet:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AtomInfoSet) -> None: ...
    def assign(self) -> AtomInfoSet: ...
    @overload
    def contains(self, local_atom_id: int) -> bool: ...
    @overload
    def contains(self, unsignedshort) -> bool: ...

class HBondEdge(pyrosetta.rosetta.utility.graph.LowMemEdge):
    @overload
    def __init__(self, first_node_ind: int, second_node_ind: int) -> None: ...
    @overload
    def __init__(self, first_node_ind: int, second_node_ind: int, energy: float) -> None: ...
    @overload
    def __init__(self, arg0: HBondEdge) -> None: ...
    def assign(self, src: HBondEdge) -> HBondEdge: ...
    @overload
    def count_dynamic_memory(self) -> int: ...
    @overload
    def count_dynamic_memory(self) -> unsignedlong: ...
    @overload
    def count_static_memory(self) -> int: ...
    @overload
    def count_static_memory(self) -> unsignedlong: ...
    @overload
    def energy(self) -> float: ...
    @overload
    def energy(self) -> float: ...
    def hbonds(self) -> pyrosetta.rosetta.std.vector_core_scoring_hbonds_graph_HBondInfo: ...
    def merge_data(self, *args, **kwargs): ...
    def register_hbond(self, first_node_is_donor: bool, local_atom_id_A: int, local_atom_id_D: int, local_atom_id_H: int, energy: float) -> None: ...
    @overload
    def score(self) -> float: ...
    @overload
    def score(self) -> float: ...
    @overload
    def set_energy(self, energy: float) -> None: ...
    @overload
    def set_energy(self, double) -> void: ...
    @overload
    def set_score(self, energy: float) -> None: ...
    @overload
    def set_score(self, double) -> void: ...

class HBondGraph(pyrosetta.rosetta.utility.graph.LowMemGraph_core_scoring_hbonds_graph_HBondNode_core_scoring_hbonds_graph_HBondEdge_t):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, num_nodes: int) -> None: ...
    @overload
    def __init__(self, arg0: HBondGraph) -> None: ...
    @overload
    def __init__(self, arg0: HBondGraph) -> None: ...
    def assign(self) -> HBondGraph: ...
    @overload
    def count_dynamic_memory(self) -> int: ...
    @overload
    def count_dynamic_memory(self) -> unsignedlong: ...
    @overload
    def count_static_memory(self) -> int: ...
    @overload
    def count_static_memory(self) -> unsignedlong: ...
    def merge(self, *args, **kwargs): ...
    def register_hbond(self, rotamerA: int, rotamerB: int, score: float) -> HBondEdge: ...

class HBondInfo:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, score: float, first_node_is_donor: bool, local_atom_id_A: int, local_atom_id_D: int, local_atom_id_H: int) -> None: ...
    @overload
    def __init__(self, first_node_is_donor: bool, local_atom_id_A: int, local_atom_id_D: int, local_atom_id_H: int) -> None: ...
    @overload
    def __init__(self, arg0: HBondInfo) -> None: ...
    def assign(self) -> HBondInfo: ...
    @overload
    def first_node_is_donor(self) -> bool: ...
    @overload
    def first_node_is_donor(self) -> bool: ...
    @overload
    def first_node_is_donor(self, setting: bool) -> None: ...
    @overload
    def first_node_is_donor(self, bool) -> void: ...
    @overload
    def local_atom_id_A(self) -> int: ...
    @overload
    def local_atom_id_A(self) -> unsignedshort: ...
    @overload
    def local_atom_id_A(self, setting: int) -> None: ...
    @overload
    def local_atom_id_A(self, unsignedshort) -> void: ...
    @overload
    def local_atom_id_D(self) -> int: ...
    @overload
    def local_atom_id_D(self) -> unsignedshort: ...
    @overload
    def local_atom_id_D(self, setting: int) -> None: ...
    @overload
    def local_atom_id_D(self, unsignedshort) -> void: ...
    @overload
    def local_atom_id_H(self) -> int: ...
    @overload
    def local_atom_id_H(self) -> unsignedshort: ...
    @overload
    def local_atom_id_H(self, setting: int) -> None: ...
    @overload
    def local_atom_id_H(self, unsignedshort) -> void: ...
    @overload
    def score(self) -> float: ...
    @overload
    def score(self) -> float: ...
    @overload
    def score(self, score: float) -> None: ...
    @overload
    def score(self, float) -> void: ...
    def __eq__(self, ot: HBondInfo) -> bool: ...

class HBondNode(pyrosetta.rosetta.utility.graph.LowMemNode):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: HBondNode) -> None: ...
    @overload
    def __init__(self, node_id: int) -> None: ...
    @overload
    def __init__(self, node_id: pyrosetta.rosetta.utility.StrongT_unsigned_long_core_scoring_hbonds_graph_NodeIDSize_t, mres_id: pyrosetta.rosetta.utility.StrongT_unsigned_long_core_scoring_hbonds_graph_MResIDSize_t, rotamer_id: pyrosetta.rosetta.utility.StrongT_unsigned_long_core_scoring_hbonds_graph_RotamerIDSize_t) -> None: ...
    def add_polar_atom(self, local_atom_id: int, atom_position: pyrosetta.rosetta.numeric.xyzVector_float_t, is_hydrogen: bool, is_donor: bool, is_acceptor: bool, is_hydroxyl: bool, is_backbone: bool) -> None: ...
    @overload
    def add_polar_atom_if_doesnt_exist(self, info: AtomInfo) -> None: ...
    @overload
    def add_polar_atom_if_doesnt_exist(self, constclasscore) -> void: ...
    def assign(self, src: HBondNode) -> HBondNode: ...
    @overload
    def clashes(self, node_id: pyrosetta.rosetta.utility.StrongT_unsigned_long_core_scoring_hbonds_graph_NodeIDSize_t) -> bool: ...
    @overload
    def clashes(self, structutility, structcore) -> bool: ...
    @overload
    def count_dynamic_memory(self) -> int: ...
    @overload
    def count_dynamic_memory(self) -> unsignedlong: ...
    @overload
    def count_static_memory(self) -> int: ...
    @overload
    def count_static_memory(self) -> unsignedlong: ...
    @overload
    def global_rotamer_id(self) -> int: ...
    @overload
    def global_rotamer_id(self) -> unsignedlong: ...
    @overload
    def local_rotamer_id(self) -> int: ...
    @overload
    def local_rotamer_id(self) -> unsignedint: ...
    def merge_data(self, *args, **kwargs): ...
    @overload
    def moltenres(self) -> int: ...
    @overload
    def moltenres(self) -> unsignedint: ...
    def polar_sc_atoms_not_satisfied_by_background(self) -> AtomInfoSet: ...
    @overload
    def print(self) -> None: ...
    @overload
    def print(self) -> void: ...
    @overload
    def register_clash(self, node_id: pyrosetta.rosetta.utility.StrongT_unsigned_long_core_scoring_hbonds_graph_NodeIDSize_t) -> None: ...
    @overload
    def register_clash(self, structutility, structcore) -> void: ...
    @overload
    def remove_atom_info(self, local_atom_id: int) -> None: ...
    @overload
    def remove_atom_info(self, unsignedshort) -> void: ...
    @overload
    def set_local_rotamer_id(self, rot_id: pyrosetta.rosetta.utility.StrongT_unsigned_long_core_scoring_hbonds_graph_RotamerIDSize_t) -> None: ...
    @overload
    def set_local_rotamer_id(self, structutility, structcore) -> void: ...
    @overload
    def set_moltenres(self, mres: pyrosetta.rosetta.utility.StrongT_unsigned_long_core_scoring_hbonds_graph_MResIDSize_t) -> None: ...
    @overload
    def set_moltenres(self, structutility, structcore) -> void: ...

class LKHBondInfo:
    def __init__(self, arg0: LKHBondInfo) -> None: ...
    def assign(self) -> LKHBondInfo: ...
    def __eq__(self) -> bool: ...
