import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.io
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.utility
from typing import overload

class PoseToStructFileRepConverter:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, options_in: pyrosetta.rosetta.core.io.StructFileRepOptions) -> None: ...
    @overload
    def __init__(self, arg0: PoseToStructFileRepConverter) -> None: ...
    @overload
    def append_residue_to_sfr(self, pose: pyrosetta.rosetta.core.pose.Pose, resnum: int) -> None: ...
    @overload
    def append_residue_to_sfr(self, constclasscore, constunsignedlong) -> void: ...
    @overload
    def append_residue_to_sfr(self, pose: pyrosetta.rosetta.core.pose.Pose, resnum: int, new_atom_num: int, new_tercount: int) -> None: ...
    def assign(self) -> PoseToStructFileRepConverter: ...
    @overload
    def get_connectivity_annotation_info(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def get_connectivity_annotation_info(self, constclasscore) -> void: ...
    def get_link_record(self, pose: pyrosetta.rosetta.core.pose.Pose, ii: int, conn: int) -> pyrosetta.rosetta.core.io.LinkInformation: ...
    @overload
    def get_parametric_info(self, remarks: pyrosetta.rosetta.core.io.Remarks, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def get_parametric_info(self, classstd, constclasscore) -> void: ...
    def get_ssbond_record(self, pose: pyrosetta.rosetta.core.pose.Pose, ii: int, conn: int) -> pyrosetta.rosetta.core.io.SSBondInformation: ...
    @overload
    def grab_additional_pose_data(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def grab_additional_pose_data(self, constclasscore) -> void: ...
    @overload
    def grab_pose_cache_data(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def grab_pose_cache_data(self, constclasscore) -> void: ...
    @overload
    def grab_pose_energies_table(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def grab_pose_energies_table(self, constclasscore) -> void: ...
    @overload
    def grab_simple_metric_data(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def grab_simple_metric_data(self, constclasscore) -> void: ...
    @overload
    def init_from_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def init_from_pose(self, constclasscore) -> void: ...
    @overload
    def init_from_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, options: pyrosetta.rosetta.core.io.StructFileRepOptions) -> None: ...
    @overload
    def init_from_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_indices: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def init_from_pose(self, constclasscore, constclassutility) -> void: ...
    @overload
    def init_from_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, mask: pyrosetta.rosetta.core.id.AtomID_Map_bool_t) -> None: ...
    @overload
    def init_from_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, mask: pyrosetta.rosetta.core.id.AtomID_Map_bool_t, options: pyrosetta.rosetta.core.io.StructFileRepOptions) -> None: ...
    def new_sfr(self) -> pyrosetta.rosetta.core.io.StructFileRep: ...
    def sfr(self) -> pyrosetta.rosetta.core.io.StructFileRep: ...

def restrict_prec(inval: float) -> str: ...
