import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import ClassVar, overload

class DecoyFileData(RawFileData):
    @overload
    def __init__(self, filename: str) -> None: ...
    @overload
    def __init__(self, arg0: DecoyFileData) -> None: ...
    def assign(self) -> DecoyFileData: ...
    def write_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, score_map: pyrosetta.rosetta.std.map_std_string_double, tag: str, fullatom: bool) -> bool: ...
    def write_struct(self, s, score_map: pyrosetta.rosetta.std.map_std_string_double) -> bool: ...

class DecoyStruct(RawStruct):
    @overload
    def __init__(self, nres_in: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: str) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, tag: str, fa: bool) -> None: ...
    @overload
    def __init__(self, arg0: DecoyStruct) -> None: ...
    @overload
    def __init__(self, arg0: DecoyStruct) -> None: ...
    def assign(self) -> DecoyStruct: ...
    @overload
    def chi(self, seqpos: int) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def chi(self, seqpos: int, chis: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def chi(self, unsignedint, classutility) -> void: ...
    @overload
    def coords(self, seqpos: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def coords(self, seqpos: int, coords: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def coords(self, unsignedint, classnumeric) -> void: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def fill_pose(self, classcore) -> void: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore) -> void: ...
    @overload
    def fullatom(self) -> bool: ...
    @overload
    def fullatom(self) -> bool: ...
    @overload
    def fullatom(self, fullatom: bool) -> None: ...
    @overload
    def fullatom(self, bool) -> void: ...
    @overload
    def get_debug_rmsd(self) -> float: ...
    @overload
    def get_debug_rmsd(self) -> double: ...
    @overload
    def omega(self, seqpos: int) -> float: ...
    @overload
    def omega(self, unsignedint) -> double: ...
    @overload
    def omega(self, seqpos: int, omega: float) -> None: ...
    @overload
    def omega(self, unsignedint, double) -> void: ...
    @overload
    def phi(self, seqpos: int) -> float: ...
    @overload
    def phi(self, unsignedint) -> double: ...
    @overload
    def phi(self, seqpos: int, phi: float) -> None: ...
    @overload
    def phi(self, unsignedint, double) -> void: ...
    @overload
    def print_conformation(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_conformation(self, std) -> void: ...
    @overload
    def psi(self, seqpos: int) -> float: ...
    @overload
    def psi(self, unsignedint) -> double: ...
    @overload
    def psi(self, seqpos: int, psi: float) -> None: ...
    @overload
    def psi(self, unsignedint, double) -> void: ...
    @overload
    def resize(self, nres_in: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def secstruct(self, seqpos: int) -> str: ...
    @overload
    def secstruct(self, unsignedint) -> char: ...
    @overload
    def secstruct(self, seqpos: int, ss: str) -> None: ...
    @overload
    def secstruct(self, unsignedint, char) -> void: ...

class DisulfideFile:
    class NumberingSystem:
        __members__: ClassVar[dict] = ...  # read-only
        __entries: ClassVar[dict] = ...
        pdb_num: ClassVar[DisulfideFile.NumberingSystem] = ...
        rosetta_num: ClassVar[DisulfideFile.NumberingSystem] = ...
        unknown_num: ClassVar[DisulfideFile.NumberingSystem] = ...
        def __init__(self, value: int) -> None: ...
        def __and__(self, other: object) -> object: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> int: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> object: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: object) -> object: ...
        def __rand__(self, other: object) -> object: ...
        def __ror__(self, other: object) -> object: ...
        def __rxor__(self, other: object) -> object: ...
        def __xor__(self, other: object) -> object: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...

    class ResNum:
        chain: str
        n: int
        type: DisulfideFile.NumberingSystem
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: DisulfideFile.ResNum) -> None: ...
        def assign(self) -> DisulfideFile.ResNum: ...
    pdb_num: ClassVar[DisulfideFile.NumberingSystem] = ...
    rosetta_num: ClassVar[DisulfideFile.NumberingSystem] = ...
    unknown_num: ClassVar[DisulfideFile.NumberingSystem] = ...
    @overload
    def __init__(self, filename: str) -> None: ...
    @overload
    def __init__(self, arg0: DisulfideFile) -> None: ...
    @overload
    def disulfides(self, disulfides: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t) -> None: ...
    @overload
    def disulfides(self, disulfides: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    def filename(self) -> str: ...
    def read_in_and_set_disulfides(self, *args, **kwargs): ...

class RawFileData:
    class const_iterator:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: RawFileData.const_iterator) -> None: ...
        def arrow(self) -> RawStruct: ...
        def assign(self, src: RawFileData.const_iterator) -> RawFileData.const_iterator: ...
        def dereference(self) -> RawStruct: ...
        def pre_increment(self) -> RawFileData.const_iterator: ...
        def __eq__(self, other: RawFileData.const_iterator) -> bool: ...
        def __ne__(self, other: RawFileData.const_iterator) -> bool: ...

    class iterator:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: RawFileData.iterator) -> None: ...
        def arrow(self) -> RawStruct: ...
        def assign(self, src: RawFileData.iterator) -> RawFileData.iterator: ...
        def dereference(self) -> RawStruct: ...
        def pre_increment(self) -> RawFileData.iterator: ...
        def __eq__(self, other: RawFileData.iterator) -> bool: ...
        def __ne__(self, other: RawFileData.iterator) -> bool: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RawFileData) -> None: ...
    def assign(self) -> RawFileData: ...
    def begin(self, *args, **kwargs): ...
    def begin_const(self, *args, **kwargs): ...
    @overload
    def clear_structure_map(self) -> None: ...
    @overload
    def clear_structure_map(self) -> void: ...
    def end(self, *args, **kwargs): ...
    def end_const(self, *args, **kwargs): ...
    @overload
    def nres(self) -> int: ...
    @overload
    def nres(self) -> int: ...
    def read_tags_fast(self, filename: str) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    def sequence(self) -> str: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> int: ...
    def write_all(self, filename: str, score_map: pyrosetta.rosetta.std.map_std_string_double) -> None: ...

class RawStruct:
    @overload
    def __init__(self, arg0: RawStruct) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def assign(self) -> RawStruct: ...
    @overload
    def decoy_tag(self) -> str: ...
    @overload
    def decoy_tag(self, tag: str) -> None: ...
    @overload
    def decoy_tag(self, std) -> void: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def fill_pose(self, classcore) -> void: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore) -> void: ...
    @overload
    def get_debug_rmsd(self) -> float: ...
    @overload
    def get_debug_rmsd(self) -> double: ...
    @overload
    def nres(self) -> int: ...
    @overload
    def nres(self) -> unsignedlong: ...
    @overload
    def nres(self, nres: int) -> None: ...
    @overload
    def nres(self, unsignedlong) -> void: ...
    @overload
    def print_conformation(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_conformation(self, std) -> void: ...
    @overload
    def print_header(self, out: pyrosetta.rosetta.std.ostream, score_map: pyrosetta.rosetta.std.map_std_string_double) -> None: ...
    @overload
    def print_header(self, out: pyrosetta.rosetta.std.ostream, score_map: pyrosetta.rosetta.std.map_std_string_double, string_map: pyrosetta.rosetta.std.map_std_string_std_string) -> None: ...
    @overload
    def print_header(self, out: pyrosetta.rosetta.std.ostream, score_map: pyrosetta.rosetta.std.map_std_string_double, string_map: pyrosetta.rosetta.std.map_std_string_std_string, print_sequence: bool) -> None: ...
    @overload
    def print_scores(self, out: pyrosetta.rosetta.std.ostream, score_map: pyrosetta.rosetta.std.map_std_string_double) -> None: ...
    @overload
    def print_scores(self, out: pyrosetta.rosetta.std.ostream, score_map: pyrosetta.rosetta.std.map_std_string_double, string_map: pyrosetta.rosetta.std.map_std_string_std_string) -> None: ...
    @overload
    def sequence(self) -> str: ...
    @overload
    def sequence(self, sequence: str) -> None: ...
    @overload
    def sequence(self, std) -> void: ...

class ScoreFileData(RawFileData):
    @overload
    def __init__(self, filename: str) -> None: ...
    @overload
    def __init__(self, arg0: ScoreFileData) -> None: ...
    def assign(self) -> ScoreFileData: ...
    @overload
    def write_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, score_map: pyrosetta.rosetta.std.map_std_string_double, tag: str) -> bool: ...
    @overload
    def write_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, score_map: pyrosetta.rosetta.std.map_std_string_double, tag: str, string_map: pyrosetta.rosetta.std.map_std_string_std_string) -> bool: ...
    @overload
    def write_struct(self, s: RawStruct, score_map: pyrosetta.rosetta.std.map_std_string_double) -> bool: ...
    @overload
    def write_struct(self, s: RawStruct, score_map: pyrosetta.rosetta.std.map_std_string_double, string_map: pyrosetta.rosetta.std.map_std_string_std_string) -> bool: ...

class ScoreMap:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ScoreMap) -> None: ...
    @staticmethod
    def add_arbitrary_score_data_from_pose(pose: pyrosetta.rosetta.core.pose.Pose, score_map: pyrosetta.rosetta.std.map_std_string_double) -> None: ...
    @overload
    @staticmethod
    def add_arbitrary_string_data_from_pose(pose: pyrosetta.rosetta.core.pose.Pose, string_map: pyrosetta.rosetta.std.map_std_string_std_string) -> None: ...
    @overload
    @staticmethod
    def add_arbitrary_string_data_from_pose(constclasscore, classstd, std) -> void: ...
    @staticmethod
    def add_energies_data_from_scored_pose(pose: pyrosetta.rosetta.core.pose.Pose, scores: pyrosetta.rosetta.std.map_std_string_double) -> None: ...
    def assign(self) -> ScoreMap: ...
    @staticmethod
    def get_arbitrary_score_data_from_pose(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.map_std_string_double: ...
    @staticmethod
    def get_arbitrary_string_data_from_pose(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.map_std_string_std_string: ...
    @staticmethod
    def get_energies_map_from_scored_pose(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.map_std_string_double: ...
    @staticmethod
    def print(score_map: pyrosetta.rosetta.std.map_std_string_double, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @staticmethod
    def score_and_add_energies_to_map(score_map: pyrosetta.rosetta.std.map_std_string_double, score_fxn: pyrosetta.rosetta.core.scoring.ScoreFunction, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...

class ScoreStructJSON(RawStruct):
    @overload
    def __init__(self, tag: str) -> None: ...
    @overload
    def __init__(self, arg0: ScoreStructJSON) -> None: ...
    @overload
    def __init__(self, arg0: ScoreStructJSON) -> None: ...
    def assign(self) -> ScoreStructJSON: ...
    @overload
    def fill_pose(self) -> None: ...
    @overload
    def fill_pose(self, classcore) -> void: ...
    @overload
    def fill_pose(self) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore) -> void: ...
    @overload
    def get_debug_rmsd(self) -> float: ...
    @overload
    def get_debug_rmsd(self) -> double: ...
    @overload
    def print_conformation(self) -> None: ...
    @overload
    def print_conformation(self, std) -> void: ...
    def print_header(self) -> None: ...
    @overload
    def print_scores(self, out: pyrosetta.rosetta.std.ostream, score_map: pyrosetta.rosetta.std.map_std_string_double) -> None: ...
    @overload
    def print_scores(self, out: pyrosetta.rosetta.std.ostream, score_map: pyrosetta.rosetta.std.map_std_string_double, string_map: pyrosetta.rosetta.std.map_std_string_std_string) -> None: ...

class ScoreStructText(RawStruct):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, tag: str) -> None: ...
    @overload
    def __init__(self, arg0: ScoreStructText) -> None: ...
    @overload
    def __init__(self, arg0: ScoreStructText) -> None: ...
    def assign(self) -> ScoreStructText: ...
    @overload
    def fill_pose(self) -> None: ...
    @overload
    def fill_pose(self, classcore) -> void: ...
    @overload
    def fill_pose(self, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore) -> void: ...
    @overload
    def get_debug_rmsd(self) -> float: ...
    @overload
    def get_debug_rmsd(self) -> double: ...
    @overload
    def print_conformation(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_conformation(self, std) -> void: ...
