import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.pose.rna
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.io
from typing import overload

class RDAT:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, filename: str) -> None: ...
    @overload
    def __init__(self, name: str, sequence: str, offset: int, seqpos: pyrosetta.rosetta.utility.vector1_unsigned_long, structure: str, annotations: pyrosetta.rosetta.utility.vector1_std_pair_std_string_std_string_t, data_annotations: pyrosetta.rosetta.utility.vector1_utility_vector1_std_pair_std_string_std_string_t, reactivity: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t, reactivity_error: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t, comments: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def __init__(self, arg0: RDAT) -> None: ...
    def annotations(self) -> pyrosetta.rosetta.utility.vector1_std_pair_std_string_std_string_t: ...
    def assign(self) -> RDAT: ...
    @overload
    def check_rdat(self) -> bool: ...
    @overload
    def check_rdat(self) -> bool: ...
    def comments(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    def data_annotations(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_std_pair_std_string_std_string_t: ...
    def fill_data_from_features(self, seqchars: pyrosetta.rosetta.utility.vector1_char, resnums: pyrosetta.rosetta.utility.vector1_unsigned_long, feature_names: pyrosetta.rosetta.utility.vector1_std_string, all_feature_vals: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def fill_header_information(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def fill_header_information(self, classcore) -> void: ...
    def name(self) -> str: ...
    def offset(self) -> int: ...
    @overload
    def output_data(self, out: pyrosetta.rosetta.utility.io.ozstream) -> None: ...
    @overload
    def output_data(self, classutility) -> void: ...
    @overload
    def output_rdat_to_file(self, filename: str) -> None: ...
    @overload
    def output_rdat_to_file(self, conststd) -> void: ...
    def reactivity(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    def reactivity_error(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    @overload
    def read_rdat_file(self, filename: str) -> None: ...
    @overload
    def read_rdat_file(self, conststd) -> void: ...
    def seqpos(self) -> pyrosetta.rosetta.utility.vector1_int: ...
    def sequence(self) -> str: ...
    def sequences(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def set_annotations(self, setting: pyrosetta.rosetta.utility.vector1_std_pair_std_string_std_string_t) -> None: ...
    @overload
    def set_annotations(self, constclassutility, std) -> void: ...
    @overload
    def set_comments(self, setting: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_comments(self, constclassutility) -> void: ...
    @overload
    def set_data_annotations(self, setting: pyrosetta.rosetta.utility.vector1_utility_vector1_std_pair_std_string_std_string_t) -> None: ...
    @overload
    def set_data_annotations(self, constclassutility, std) -> void: ...
    @overload
    def set_name(self, setting: str) -> None: ...
    @overload
    def set_name(self, conststd) -> void: ...
    def set_offset(self, setting: int) -> None: ...
    @overload
    def set_reactivity(self, setting: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def set_reactivity(self, constclassutility) -> void: ...
    @overload
    def set_reactivity_error(self, setting: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def set_reactivity_error(self, constclassutility) -> void: ...
    @overload
    def set_seqpos(self, setting: pyrosetta.rosetta.utility.vector1_int) -> None: ...
    @overload
    def set_seqpos(self, constclassutility) -> void: ...
    @overload
    def set_sequence(self, setting: str) -> None: ...
    @overload
    def set_sequence(self, conststd) -> void: ...
    @overload
    def set_sequences(self, setting: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_sequences(self, constclassutility) -> void: ...
    @overload
    def set_structure(self, setting: str) -> None: ...
    @overload
    def set_structure(self, conststd) -> void: ...
    @overload
    def set_structures(self, setting: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_structures(self, constclassutility) -> void: ...
    @overload
    def set_trace(self, setting: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def set_trace(self, constclassutility) -> void: ...
    @overload
    def set_version(self, setting: str) -> None: ...
    @overload
    def set_version(self, conststd) -> void: ...
    @overload
    def set_xsel(self, setting: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_xsel(self, constclassutility) -> void: ...
    @overload
    def set_xsel_refine(self, setting: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def set_xsel_refine(self, constclassutility) -> void: ...
    def structure(self) -> str: ...
    def structures(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    def trace(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    def version(self) -> str: ...
    def xsel(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    def xsel_refine(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...

class RNA_DataReader:
    @overload
    def __init__(self, rna_data_file: str) -> None: ...
    @overload
    def __init__(self, arg0: RNA_DataReader) -> None: ...
    def assign(self) -> RNA_DataReader: ...
    @overload
    def fill_rna_data_info(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def fill_rna_data_info(self, classcore) -> void: ...
    @overload
    def has_reactivities(self) -> bool: ...
    @overload
    def has_reactivities(self) -> bool: ...
    @overload
    def initialize(self, rna_data_file: str) -> None: ...
    @overload
    def initialize(self, conststd) -> void: ...

@overload
def get_rna_data_info(pose: pyrosetta.rosetta.core.pose.Pose, rna_data_file: str) -> pyrosetta.rosetta.core.pose.rna.RNA_DataInfo: ...
@overload
def get_rna_data_info(pose: pyrosetta.rosetta.core.pose.Pose, rna_data_file: str, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> pyrosetta.rosetta.core.pose.rna.RNA_DataInfo: ...
def get_tag(annotations: pyrosetta.rosetta.utility.vector1_std_pair_std_string_std_string_t, tag: str) -> str: ...
def get_tags(data_annotations: pyrosetta.rosetta.utility.vector1_utility_vector1_std_pair_std_string_std_string_t, tag: str) -> pyrosetta.rosetta.utility.vector1_std_string: ...
