import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import overload

class DesignContrast:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DesignContrast) -> None: ...
    def assign(self) -> DesignContrast: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    def getListNames(self) -> pyrosetta.rosetta.utility.vector1_utility_file_FileName: ...
    def getNeighbors(self) -> pyrosetta.rosetta.utility.vector1_int: ...
    def getPdbCodes(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    def getPdbNames(self) -> pyrosetta.rosetta.utility.vector1_utility_file_FileName: ...
    def getSecStruct(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    def output_sqc_file(self, native_pose: pyrosetta.rosetta.core.pose.Pose, decoy_pose: pyrosetta.rosetta.core.pose.Pose, single_code: str, sqc: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def setNames(self) -> None: ...
    @overload
    def setNames(self) -> void: ...
    @overload
    def setNeighbors(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def setNeighbors(self, classcore) -> void: ...
    @overload
    def setPdbCodes(self) -> None: ...
    @overload
    def setPdbCodes(self) -> void: ...
    @overload
    def setSecStruct(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def setSecStruct(self, classcore) -> void: ...
