import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import overload

class BUFFER:
    @overload
    def __init__(self, size: int) -> None: ...
    @overload
    def __init__(self, buf: str, size: int) -> None: ...
    def read(self, out_buf: str, nchar: int) -> int: ...
    def write(self, x: str, nchar: int) -> int: ...

def check_binary_chars(x: str, buf: BUFFER) -> None: ...
@overload
def check_binary_unsigned_int(x: int, buf: BUFFER) -> None: ...
@overload
def check_binary_unsigned_int(unsignedint, structcore) -> void: ...
@overload
def read_binary(x: str, buf: BUFFER) -> None: ...
@overload
def read_binary(x: bool, buf: BUFFER) -> None: ...
@overload
def read_binary(x: float, buf: BUFFER) -> None: ...
@overload
def read_binary(x: float, buf: BUFFER) -> None: ...
@overload
def read_binary(x: int, buf: BUFFER) -> None: ...
@overload
def read_binary(x: pyrosetta.rosetta.utility.vector1_bool, buf: BUFFER) -> None: ...
@overload
def read_binary(classutility, structcore) -> void: ...
@overload
def read_binary(x: pyrosetta.rosetta.std.vector_std_string, buf: BUFFER) -> None: ...
@overload
def read_binary(classstd, structcore) -> void: ...
@overload
def read_binary(x: str, buf: BUFFER) -> None: ...
@overload
def read_binary(std, structcore) -> void: ...
@overload
def read_binary(x: pyrosetta.rosetta.numeric.xyzVector_double_t, buf: BUFFER) -> None: ...
@overload
def read_binary(classnumeric, structcore) -> void: ...
@overload
def read_binary(pose: pyrosetta.rosetta.core.pose.Pose, buf: BUFFER) -> None: ...
@overload
def read_binary(classcore, structcore) -> void: ...
@overload
def write_binary(x: str, buf: BUFFER) -> None: ...
@overload
def write_binary(char, structcore) -> void: ...
@overload
def write_binary(x: bool, buf: BUFFER) -> None: ...
@overload
def write_binary(bool, structcore) -> void: ...
@overload
def write_binary(x: float, buf: BUFFER) -> None: ...
@overload
def write_binary(float, structcore) -> void: ...
@overload
def write_binary(x: float, buf: BUFFER) -> None: ...
@overload
def write_binary(double, structcore) -> void: ...
@overload
def write_binary(x: int, buf: BUFFER) -> None: ...
@overload
def write_binary(unsignedint, structcore) -> void: ...
@overload
def write_binary(x: pyrosetta.rosetta.utility.vector1_bool, buf: BUFFER) -> None: ...
@overload
def write_binary(constclassutility, structcore) -> void: ...
@overload
def write_binary(x: pyrosetta.rosetta.std.vector_std_string, buf: BUFFER) -> None: ...
@overload
def write_binary(constclassstd, structcore) -> void: ...
@overload
def write_binary(x: str, buf: BUFFER) -> None: ...
@overload
def write_binary(conststd, structcore) -> void: ...
@overload
def write_binary(x: pyrosetta.rosetta.numeric.xyzVector_double_t, buf: BUFFER) -> None: ...
@overload
def write_binary(constclassnumeric, structcore) -> void: ...
@overload
def write_binary(pose: pyrosetta.rosetta.core.pose.Pose, buf: BUFFER) -> None: ...
@overload
def write_binary(constclasscore, structcore) -> void: ...
def write_binary_chars(x: str, buf: BUFFER) -> None: ...
