import pyrosetta.rosetta.ObjexxFCL
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.conformation.symmetry
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.sequence
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.options
from typing import Any, ClassVar, overload

SFHEADER_SCORE_LINE: SilentFileHeaderLine
SFHEADER_SCORE_TYPE_LINE: SilentFileHeaderLine
SFHEADER_SEQUENCE_LINE: SilentFileHeaderLine
energynames: SharedSilentDataType
simplesequencedata: SharedSilentDataType

class BinarySilentStruct(SilentStruct):
    @overload
    def __init__(self, opts: SilentFileOptions, nres_in: int) -> None: ...
    @overload
    def __init__(self, opts: SilentFileOptions) -> None: ...
    @overload
    def __init__(self, arg0: SilentFileOptions, arg1: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, opts: SilentFileOptions, pose: pyrosetta.rosetta.core.pose.Pose, tag: str) -> None: ...
    @overload
    def __init__(self, arg0: BinarySilentStruct) -> None: ...
    @overload
    def __init__(self, arg0: BinarySilentStruct) -> None: ...
    @overload
    def CA_rmsd(self, other_pss: BinarySilentStruct) -> float: ...
    @overload
    def CA_rmsd(self, classcore) -> double: ...
    @overload
    def add_chain_ending(self, seqpos: int) -> None: ...
    @overload
    def add_chain_ending(self, constunsignedlong) -> void: ...
    @overload
    def add_jump(self, jump: pyrosetta.rosetta.core.kinematics.Jump) -> None: ...
    @overload
    def add_jump(self, classcore) -> void: ...
    def assign(self, src: BinarySilentStruct) -> BinarySilentStruct: ...
    @overload
    def chain_endings(self, endings: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def chain_endings(self, constclassutility) -> void: ...
    @overload
    def chain_endings(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def chain_endings_str(self) -> str: ...
    def clone(self) -> SilentStruct: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constbool) -> void: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore, constbool) -> void: ...
    @overload
    def fill_struct(self, pose: pyrosetta.rosetta.core.pose.Pose, tag: str) -> None: ...
    @overload
    def fill_struct(self, constclasscore, conststd) -> void: ...
    @overload
    def fold_tree(self, f: pyrosetta.rosetta.core.kinematics.FoldTree) -> None: ...
    @overload
    def fold_tree(self, classcore) -> void: ...
    @overload
    def fold_tree(self) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    @overload
    def fullatom(self) -> bool: ...
    @overload
    def fullatom(self) -> bool: ...
    @overload
    def fullatom(self, fullatom: bool) -> None: ...
    @overload
    def fullatom(self, bool) -> void: ...
    def get_CA_xyz(self) -> pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t: ...
    @overload
    def get_debug_rmsd(self) -> float: ...
    @overload
    def get_debug_rmsd(self) -> double: ...
    @overload
    def init_from_lines(self, lines: pyrosetta.rosetta.utility.vector1_std_string, container: SilentFileData) -> bool: ...
    @overload
    def init_from_lines(self, constclassutility, classcore) -> bool: ...
    @overload
    def init_from_lines(self, lines: pyrosetta.rosetta.utility.vector1_std_string, container: SilentFileData, skip_read_from_container: bool) -> bool: ...
    @overload
    def init_from_lines(self, constclassutility, classcore, constbool) -> bool: ...
    @overload
    def is_symmetric(self) -> bool: ...
    @overload
    def is_symmetric(self) -> bool: ...
    def jump(self, jump_num: int) -> pyrosetta.rosetta.core.kinematics.RT: ...
    @overload
    def parse_chain_endings(self, stream: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def parse_chain_endings(self, std) -> void: ...
    @overload
    def print_conformation(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_conformation(self, std) -> void: ...
    @overload
    def print_header(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_header(self, std) -> void: ...
    @overload
    def resize(self, nres_in: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def secstruct(self, seqpos: int) -> str: ...
    @overload
    def secstruct(self, unsignedint) -> char: ...
    @overload
    def secstruct(self, seqpos: int, ss: str) -> None: ...
    @overload
    def secstruct(self, unsignedint, char) -> void: ...
    @overload
    def setup_other_poses(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def setup_other_poses(self, classcore, constclasscore) -> void: ...
    def shared_from_this(self) -> BinarySilentStruct: ...
    @overload
    def symmetry_info(self, s: pyrosetta.rosetta.core.conformation.symmetry.SymmetryInfo) -> None: ...
    @overload
    def symmetry_info(self, classcore) -> void: ...
    @overload
    def symmetry_info(self) -> pyrosetta.rosetta.core.conformation.symmetry.SymmetryInfo: ...

class BinarySilentStructCreator(SilentStructCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: BinarySilentStructCreator) -> None: ...
    @overload
    def __init__(self, arg0: BinarySilentStructCreator) -> None: ...
    def assign(self) -> BinarySilentStructCreator: ...
    def create_silent_struct(self) -> SilentStruct: ...
    def keyname(self) -> str: ...

class EnergyNames(SharedSilentData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, line: str) -> None: ...
    @overload
    def __init__(self, arg0: EnergyNames) -> None: ...
    def assign(self) -> EnergyNames: ...
    @overload
    def energy_names(self, new_e_names: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def energy_names(self, classutility) -> void: ...
    @overload
    def energy_names(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    def __eq__(self, other: EnergyNames) -> bool: ...

class ProteinSilentStructCreator(SilentStructCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ProteinSilentStructCreator) -> None: ...
    @overload
    def __init__(self, arg0: ProteinSilentStructCreator) -> None: ...
    def assign(self) -> ProteinSilentStructCreator: ...
    def create_silent_struct(self) -> SilentStruct: ...
    def keyname(self) -> str: ...

class ProteinSilentStruct_SinglePrecCreator(SilentStructCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ProteinSilentStruct_SinglePrecCreator) -> None: ...
    @overload
    def __init__(self, arg0: ProteinSilentStruct_SinglePrecCreator) -> None: ...
    def assign(self) -> ProteinSilentStruct_SinglePrecCreator: ...
    def create_silent_struct(self) -> SilentStruct: ...
    def keyname(self) -> str: ...

class RNA_SilentStruct(SilentStruct):
    @overload
    def __init__(self, opts: SilentFileOptions, nres_in: int) -> None: ...
    @overload
    def __init__(self, opts: SilentFileOptions) -> None: ...
    @overload
    def __init__(self, arg0: SilentFileOptions, arg1: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: SilentFileOptions, arg1: pyrosetta.rosetta.core.pose.Pose, arg2: str) -> None: ...
    @overload
    def __init__(self, opts: SilentFileOptions, pose: pyrosetta.rosetta.core.pose.Pose, tag: str, fa: bool) -> None: ...
    @overload
    def __init__(self, arg0: RNA_SilentStruct) -> None: ...
    @overload
    def __init__(self, arg0: RNA_SilentStruct) -> None: ...
    @overload
    def CA_rmsd(self, other_pss: RNA_SilentStruct) -> float: ...
    @overload
    def CA_rmsd(self, classcore) -> double: ...
    @overload
    def add_jump(self, jump: pyrosetta.rosetta.core.kinematics.Jump) -> None: ...
    @overload
    def add_jump(self, constclasscore) -> void: ...
    def assign(self, src: RNA_SilentStruct) -> RNA_SilentStruct: ...
    def chi(self, seqpos: int, torsion_num: int) -> float: ...
    def chi_torsions(self, seqpos: int) -> pyrosetta.rosetta.utility.vector1_double: ...
    def clone(self) -> SilentStruct: ...
    @overload
    def coords(self, seqpos: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def coords(self) -> pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constbool) -> void: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore, constbool) -> void: ...
    @overload
    def fill_struct(self, pose: pyrosetta.rosetta.core.pose.Pose, tag: str) -> None: ...
    @overload
    def fill_struct(self, constclasscore, conststd) -> void: ...
    def fold_tree(self) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    @overload
    def fullatom(self) -> bool: ...
    @overload
    def fullatom(self) -> bool: ...
    @overload
    def fullatom(self, fullatom: bool) -> None: ...
    @overload
    def fullatom(self, bool) -> void: ...
    def get_CA_xyz(self) -> pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t: ...
    @overload
    def get_debug_rmsd(self) -> float: ...
    @overload
    def get_debug_rmsd(self) -> double: ...
    @overload
    def init_from_lines(self, lines: pyrosetta.rosetta.utility.vector1_std_string, container: SilentFileData) -> bool: ...
    @overload
    def init_from_lines(self, constclassutility, classcore) -> bool: ...
    def jump(self, jump_num: int) -> pyrosetta.rosetta.core.kinematics.Jump: ...
    def mainchain_torsion(self, seqpos: int, torsion_num: int) -> float: ...
    def mainchain_torsions(self, seqpos: int) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def print_conformation(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_conformation(self, std) -> void: ...
    @overload
    def print_header(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_header(self, std) -> void: ...
    @overload
    def resize(self, nres_in: int) -> None: ...
    @overload
    def resize(self, constunsignedlong) -> void: ...
    @overload
    def secstruct(self, seqpos: int) -> str: ...
    @overload
    def secstruct(self, unsignedlong) -> char: ...
    def set_chi_torsions(self, seqpos: int, torsions: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    def set_coords(self, seqpos: int, coords: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_fold_tree(self, f: pyrosetta.rosetta.core.kinematics.FoldTree) -> None: ...
    @overload
    def set_fold_tree(self, constclasscore) -> void: ...
    def set_mainchain_torsions(self, seqpos: int, torsions: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    def set_non_main_chain_sugar_coords(self, seqpos: int, vecs: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t) -> None: ...
    def set_secstruct(self, seqpos: int, ss: str) -> None: ...

class RNA_SilentStructCreator(SilentStructCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RNA_SilentStructCreator) -> None: ...
    @overload
    def __init__(self, arg0: RNA_SilentStructCreator) -> None: ...
    def assign(self) -> RNA_SilentStructCreator: ...
    def create_silent_struct(self) -> SilentStruct: ...
    def keyname(self) -> str: ...

class RigidBodySilentStruct(SilentStruct):
    @overload
    def __init__(self, arg0: SilentFileOptions, arg1: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, opts: SilentFileOptions, pose: pyrosetta.rosetta.core.pose.Pose, tag: str) -> None: ...
    @overload
    def __init__(self, opts: SilentFileOptions) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodySilentStruct) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodySilentStruct) -> None: ...
    @overload
    def add_jump(self, jump: pyrosetta.rosetta.core.kinematics.Jump) -> None: ...
    @overload
    def add_jump(self, constclasscore) -> void: ...
    @overload
    def add_rt(self, rt: pyrosetta.rosetta.core.kinematics.RT) -> None: ...
    @overload
    def add_rt(self, constclasscore) -> void: ...
    def assign(self, src: RigidBodySilentStruct) -> RigidBodySilentStruct: ...
    def clone(self) -> SilentStruct: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constbool) -> void: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore, constbool) -> void: ...
    @overload
    def fill_struct(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def fill_struct(self, pose: pyrosetta.rosetta.core.pose.Pose, tag: str) -> None: ...
    @overload
    def fill_struct(self, constclasscore, conststd) -> void: ...
    @overload
    def fold_tree(self) -> None: ...
    @overload
    def fold_tree(self, constclasscore) -> void: ...
    @overload
    def fold_tree(self) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    def get_CA_xyz(self) -> pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t: ...
    @overload
    def get_debug_rmsd(self) -> float: ...
    @overload
    def get_debug_rmsd(self) -> double: ...
    @overload
    def init_from_lines(self, lines: pyrosetta.rosetta.utility.vector1_std_string, container: SilentFileData) -> bool: ...
    @overload
    def init_from_lines(self, constclassutility, classcore) -> bool: ...
    @overload
    def is_symmetric(self) -> bool: ...
    @overload
    def is_symmetric(self) -> bool: ...
    def jump(self, jump_num: int) -> pyrosetta.rosetta.core.kinematics.RT: ...
    @overload
    def njumps(self) -> int: ...
    @overload
    def njumps(self) -> unsignedlong: ...
    @overload
    def print_conformation(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_conformation(self, std) -> void: ...
    @overload
    def symmetry_info(self, s: pyrosetta.rosetta.core.conformation.symmetry.SymmetryInfo) -> None: ...
    @overload
    def symmetry_info(self, classcore) -> void: ...
    @overload
    def symmetry_info(self) -> pyrosetta.rosetta.core.conformation.symmetry.SymmetryInfo: ...

class RigidBodySilentStructCreator(SilentStructCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodySilentStructCreator) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodySilentStructCreator) -> None: ...
    def assign(self) -> RigidBodySilentStructCreator: ...
    def create_silent_struct(self) -> SilentStruct: ...
    def keyname(self) -> str: ...

class ScoreFileSilentStruct(SilentStruct):
    @overload
    def __init__(self, opts: SilentFileOptions) -> None: ...
    @overload
    def __init__(self, arg0: SilentFileOptions, arg1: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, opts: SilentFileOptions, pose: pyrosetta.rosetta.core.pose.Pose, tag: str) -> None: ...
    @overload
    def __init__(self, arg0: ScoreFileSilentStruct) -> None: ...
    @overload
    def __init__(self, arg0: ScoreFileSilentStruct) -> None: ...
    def assign(self, src: ScoreFileSilentStruct) -> ScoreFileSilentStruct: ...
    def clone(self) -> SilentStruct: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore, constbool) -> void: ...
    @overload
    def fill_struct(self, pose: pyrosetta.rosetta.core.pose.Pose, tag: str) -> None: ...
    @overload
    def fill_struct(self, constclasscore, conststd) -> void: ...
    def get_CA_xyz(self) -> pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t: ...
    @overload
    def get_debug_rmsd(self) -> float: ...
    @overload
    def get_debug_rmsd(self) -> double: ...
    @overload
    def init_from_lines(self, lines: pyrosetta.rosetta.utility.vector1_std_string, container: SilentFileData) -> bool: ...
    @overload
    def init_from_lines(self, constclassutility, classcore) -> bool: ...
    @overload
    def print_conformation(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_conformation(self, std) -> void: ...
    @overload
    def print_header(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_header(self, std) -> void: ...

class ScoreFileSilentStructCreator(SilentStructCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ScoreFileSilentStructCreator) -> None: ...
    @overload
    def __init__(self, arg0: ScoreFileSilentStructCreator) -> None: ...
    def assign(self) -> ScoreFileSilentStructCreator: ...
    def create_silent_struct(self) -> SilentStruct: ...
    def keyname(self) -> str: ...

class ScoreJumpFileSilentStruct(SilentStruct):
    @overload
    def __init__(self, opts: SilentFileOptions) -> None: ...
    @overload
    def __init__(self, arg0: SilentFileOptions, arg1: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, opts: SilentFileOptions, pose: pyrosetta.rosetta.core.pose.Pose, tag: str) -> None: ...
    @overload
    def __init__(self, arg0: ScoreJumpFileSilentStruct) -> None: ...
    @overload
    def __init__(self, arg0: ScoreJumpFileSilentStruct) -> None: ...
    @overload
    def add_jump(self, jump: pyrosetta.rosetta.core.kinematics.Jump) -> None: ...
    @overload
    def add_jump(self, classcore) -> void: ...
    def clone(self) -> SilentStruct: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore, constbool) -> void: ...
    @overload
    def fill_struct(self, pose: pyrosetta.rosetta.core.pose.Pose, tag: str) -> None: ...
    @overload
    def fill_struct(self, constclasscore, conststd) -> void: ...
    @overload
    def fold_tree(self, f: pyrosetta.rosetta.core.kinematics.FoldTree) -> None: ...
    @overload
    def fold_tree(self, constclasscore) -> void: ...
    @overload
    def fold_tree(self) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    def get_CA_xyz(self) -> pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t: ...
    @overload
    def get_debug_rmsd(self) -> float: ...
    @overload
    def get_debug_rmsd(self) -> double: ...
    @overload
    def init_from_lines(self, lines: pyrosetta.rosetta.utility.vector1_std_string, container: SilentFileData) -> bool: ...
    @overload
    def init_from_lines(self, constclassutility, classcore) -> bool: ...
    def jump(self, jump_num: int) -> pyrosetta.rosetta.core.kinematics.RT: ...
    @overload
    def print_conformation(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_conformation(self, std) -> void: ...
    @overload
    def print_header(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_header(self, std) -> void: ...
    def shared_from_this(self) -> ScoreJumpFileSilentStruct: ...

class ScoreJumpFileSilentStructCreator(SilentStructCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ScoreJumpFileSilentStructCreator) -> None: ...
    @overload
    def __init__(self, arg0: ScoreJumpFileSilentStructCreator) -> None: ...
    def assign(self) -> ScoreJumpFileSilentStructCreator: ...
    def create_silent_struct(self) -> SilentStruct: ...
    def keyname(self) -> str: ...

class SharedSilentData:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SharedSilentData) -> None: ...
    def assign(self) -> SharedSilentData: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class SharedSilentDataType:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    energynames: ClassVar[SharedSilentDataType] = ...
    simplesequencedata: ClassVar[SharedSilentDataType] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class SilentEnergy:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, name: str, value: float, weight: float, width: int) -> None: ...
    @overload
    def __init__(self, name: str, value: str, width: int) -> None: ...
    @overload
    def __init__(self, arg0: SilentEnergy) -> None: ...
    def assign(self) -> SilentEnergy: ...
    @overload
    def name(self) -> str: ...
    @overload
    def name(self, new_name: str) -> None: ...
    @overload
    def name(self, conststd) -> void: ...
    def string_value(self) -> str: ...
    @overload
    def value(self) -> float: ...
    @overload
    def value(self) -> double: ...
    @overload
    def value(self, new_value: float) -> None: ...
    @overload
    def value(self, new_string_value: str) -> None: ...
    @overload
    def value(self, conststd) -> void: ...
    @overload
    def weight(self) -> float: ...
    @overload
    def weight(self) -> double: ...
    @overload
    def weight(self, new_weight: float) -> None: ...
    @overload
    def width(self) -> int: ...
    @overload
    def width(self) -> int: ...
    @overload
    def width(self, new_width: int) -> None: ...

class SilentFileData:
    class const_iterator:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: SilentFileData.const_iterator) -> None: ...
        def arrow(self) -> SilentStruct: ...
        def dereference(self) -> SilentStruct: ...
        def pre_decrement(self) -> SilentFileData.const_iterator: ...
        def pre_increment(self) -> SilentFileData.const_iterator: ...
        def __eq__(self, other: SilentFileData.const_iterator) -> bool: ...
        def __ne__(self, other: SilentFileData.const_iterator) -> bool: ...

    class iterator:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: SilentFileData.iterator) -> None: ...
        def arrow(self) -> SilentStruct: ...
        def assign(self) -> SilentFileData.iterator: ...
        def dereference(self) -> SilentStruct: ...
        def pre_decrement(self) -> SilentFileData.iterator: ...
        def pre_increment(self) -> SilentFileData.iterator: ...
        def __eq__(self, other: SilentFileData.iterator) -> bool: ...
        def __ne__(self, other: SilentFileData.iterator) -> bool: ...
    @overload
    def __init__(self, options: SilentFileOptions) -> None: ...
    @overload
    def __init__(self, filename: str, options: SilentFileOptions) -> None: ...
    @overload
    def __init__(self, filename: str, store_argv_in_file: bool, strict_column_mode: bool, silent_struct_type: str, options: SilentFileOptions) -> None: ...
    @overload
    def __init__(self, arg0: SilentFileData) -> None: ...
    @overload
    def add_as_other_struct_if_relevant(self, new_struct: SilentStruct) -> bool: ...
    @overload
    def add_as_other_struct_if_relevant(self, constclassstd) -> bool: ...
    @overload
    def add_structure(self, new_struct: SilentStruct) -> None: ...
    @overload
    def add_structure(self, constclassstd) -> void: ...
    @overload
    def add_structure(self, new_struct: SilentStruct) -> None: ...
    @overload
    def add_structure(self, constclasscore) -> void: ...
    @overload
    def add_structure_replace_tag_if_necessary(self, new_struct: SilentStruct) -> None: ...
    @overload
    def add_structure_replace_tag_if_necessary(self, classstd) -> void: ...
    def assign(self) -> SilentFileData: ...
    def begin(self, *args, **kwargs): ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def clear_shared_silent_data(self) -> None: ...
    @overload
    def clear_shared_silent_data(self) -> void: ...
    @overload
    def clear_structure_map(self) -> None: ...
    @overload
    def clear_structure_map(self) -> void: ...
    @overload
    def comment_line(self, line: str) -> None: ...
    @overload
    def comment_line(self, conststd) -> void: ...
    def comment_lines(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    def create_SilentStructOP(self) -> SilentStruct: ...
    def end(self, *args, **kwargs): ...
    def filename(self) -> str: ...
    def get_iterator_for_tag(self, *args, **kwargs): ...
    def get_resnum(self, filename: str) -> tuple[pyrosetta.rosetta.utility.vector1_int, pyrosetta.rosetta.utility.vector1_char, pyrosetta.rosetta.utility.vector1_std_string]: ...
    def get_sequence(self, filename: str) -> str: ...
    def get_shared_silent_data(self, ssdt: SharedSilentDataType) -> SharedSilentData: ...
    def get_structure(self, tag: str) -> SilentStruct: ...
    @overload
    def has_shared_silent_data(self, ssdt: SharedSilentDataType) -> bool: ...
    @overload
    def has_shared_silent_data(self, enumcore) -> bool: ...
    @overload
    def has_tag(self, tag: str) -> bool: ...
    @overload
    def has_tag(self, conststd) -> bool: ...
    def input_filename(self) -> str: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def matched_tags(self, expression: str, mode: str, tags_in_file: pyrosetta.rosetta.utility.vector1_std_string) -> bool: ...
    @overload
    def nres(self) -> int: ...
    @overload
    def nres(self) -> int: ...
    @overload
    def order_by_energy(self) -> None: ...
    @overload
    def order_by_energy(self) -> void: ...
    @overload
    def push_back(self, new_struct: SilentStruct) -> None: ...
    @overload
    def push_back(self, constclassstd) -> void: ...
    @overload
    def read_file(self, filename: str) -> bool: ...
    @overload
    def read_file(self, conststd) -> bool: ...
    @overload
    def read_file(self, filename: str, tags: pyrosetta.rosetta.utility.vector1_std_string) -> bool: ...
    @overload
    def read_file(self, conststd, constclassutility) -> bool: ...
    @overload
    def read_stream(self, data: pyrosetta.rosetta.std.istream, tags: pyrosetta.rosetta.utility.vector1_std_string, throw_exception_on_bad_structs: bool) -> bool: ...
    @overload
    def read_stream(self, data: pyrosetta.rosetta.std.istream, tags: pyrosetta.rosetta.utility.vector1_std_string, throw_exception_on_bad_structs: bool, filename: str) -> bool: ...
    @overload
    def read_tags_fast(self, filename: str) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def read_tags_fast(self, conststd, classutility) -> bool: ...
    @overload
    def renumber_all_decoys(self) -> None: ...
    @overload
    def renumber_all_decoys(self) -> void: ...
    @overload
    def reverse_score_filter(self, score_fraction: float) -> None: ...
    @overload
    def reverse_score_filter(self, constdouble) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def score_filter(self, score_fraction: float) -> None: ...
    @overload
    def score_filter(self, constdouble) -> void: ...
    @overload
    def set_filename(self, filename: str) -> None: ...
    @overload
    def set_filename(self, std) -> void: ...
    def set_record_source(self, new_mode: bool) -> None: ...
    @overload
    def set_shared_silent_data(self, ssdt: SharedSilentDataType, ssd_op: SharedSilentData) -> None: ...
    @overload
    def set_shared_silent_data(self, enumcore, classstd) -> void: ...
    @overload
    def set_verbose(self, setting: bool) -> None: ...
    @overload
    def set_verbose(self, constbool) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def store_argv_in_file(self) -> bool: ...
    @overload
    def store_argv_in_file(self) -> bool: ...
    @overload
    def store_argv_in_file(self, new_setting: bool) -> None: ...
    @overload
    def store_argv_in_file(self, bool) -> void: ...
    @overload
    def strict_column_mode(self) -> bool: ...
    @overload
    def strict_column_mode(self) -> Any: ...
    @overload
    def strict_column_mode(self) -> Any: ...
    @overload
    def strict_column_mode(self) -> bool: ...
    @overload
    def strict_column_mode(self, new_mode: bool) -> None: ...
    @overload
    def strict_column_mode(self) -> Any: ...
    @overload
    def strict_column_mode(self, bool) -> void: ...
    def structure_list(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_io_silent_SilentStruct_t: ...
    def tags(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def write_all(self, filename: str) -> None: ...
    @overload
    def write_all(self, filename: str, bWriteScoreOnly: bool) -> None: ...
    @overload
    def write_all(self, conststd, bool) -> void: ...
    @overload
    def write_comment(self, out: pyrosetta.rosetta.std.ostream, line: str) -> None: ...
    @overload
    def write_comment(self, std, conststd) -> void: ...
    @overload
    def write_silent_struct(self, s: SilentStruct, filename: str) -> bool: ...
    @overload
    def write_silent_struct(self, s: SilentStruct, filename: str, bWriteScoreOnly: bool) -> bool: ...
    @overload
    def write_silent_struct(self, classcore, conststd, bool) -> bool: ...
    @overload
    def write_silent_struct(self, s: SilentStruct, out: pyrosetta.rosetta.std.ostream) -> bool: ...
    @overload
    def write_silent_struct(self, s: SilentStruct, out: pyrosetta.rosetta.std.ostream, bWriteScoreOnly: bool) -> bool: ...
    @overload
    def write_silent_struct(self, classcore, std, bool) -> bool: ...
    def __getitem__(self, tag: str) -> SilentStruct: ...

class SilentFileHeaderLine:
    __members__: ClassVar[dict] = ...  # read-only
    SFHEADER_SCORE_LINE: ClassVar[SilentFileHeaderLine] = ...
    SFHEADER_SCORE_TYPE_LINE: ClassVar[SilentFileHeaderLine] = ...
    SFHEADER_SEQUENCE_LINE: ClassVar[SilentFileHeaderLine] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class SilentFileOptions:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, options: pyrosetta.rosetta.utility.options.OptionCollection) -> None: ...
    @overload
    def __init__(self, arg0: SilentFileOptions) -> None: ...
    @overload
    @staticmethod
    def append_attributes_for_tag_parsing(xsd, attributes: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    @staticmethod
    def append_attributes_for_tag_parsing(classutility, classstd) -> void: ...
    def assign(self) -> SilentFileOptions: ...
    @overload
    def binary_output(self) -> bool: ...
    @overload
    def binary_output(self) -> bool: ...
    @overload
    def force_silent_bitflip_on_read(self) -> bool: ...
    @overload
    def force_silent_bitflip_on_read(self) -> bool: ...
    @overload
    def force_silent_bitflip_on_read(self, setting: bool) -> None: ...
    @overload
    def force_silent_bitflip_on_read(self, bool) -> void: ...
    @overload
    def force_silent_bitflip_on_read_set(self) -> bool: ...
    @overload
    def force_silent_bitflip_on_read_set(self) -> bool: ...
    @overload
    def in_fullatom(self) -> bool: ...
    @overload
    def in_fullatom(self) -> bool: ...
    @overload
    def in_fullatom(self, setting: bool) -> None: ...
    @overload
    def in_fullatom(self, bool) -> void: ...
    @overload
    def in_silent_score_prefix(self) -> str: ...
    @overload
    def in_silent_score_prefix(self, setting: str) -> None: ...
    @overload
    def in_silent_score_prefix(self, std) -> void: ...
    @overload
    def in_silent_scores_wanted(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def in_silent_scores_wanted(self, setting: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def in_silent_scores_wanted(self, constclassutility) -> void: ...
    @overload
    def in_silent_scores_wanted_set(self) -> bool: ...
    @overload
    def in_silent_scores_wanted_set(self) -> bool: ...
    @overload
    def in_silent_struct_type(self) -> str: ...
    @overload
    def in_silent_struct_type(self, setting: str) -> None: ...
    @overload
    def in_silent_struct_type(self, std) -> void: ...
    @overload
    def in_silent_struct_type_set(self) -> bool: ...
    @overload
    def in_silent_struct_type_set(self) -> bool: ...
    @overload
    def keep_input_scores(self) -> bool: ...
    @overload
    def keep_input_scores(self) -> bool: ...
    @overload
    def keep_input_scores(self, setting: bool) -> None: ...
    @overload
    def keep_input_scores(self, bool) -> void: ...
    @overload
    @staticmethod
    def list_read_options(read_options: pyrosetta.rosetta.std.list_utility_keys_VariantKey_utility_options_OptionKey_t) -> None: ...
    @overload
    @staticmethod
    def list_read_options(classstd) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def out_silent_struct_type(self) -> str: ...
    @overload
    def out_silent_struct_type(self, setting: str) -> None: ...
    @overload
    def out_silent_struct_type(self, std) -> void: ...
    @overload
    def out_silent_struct_type_set(self) -> bool: ...
    @overload
    def out_silent_struct_type_set(self) -> bool: ...
    @overload
    def out_user_tag(self) -> str: ...
    @overload
    def out_user_tag(self, setting: str) -> None: ...
    @overload
    def out_user_tag(self, std) -> void: ...
    @overload
    def out_user_tag_set(self) -> bool: ...
    @overload
    def out_user_tag_set(self) -> bool: ...
    @overload
    def out_weight_silent_scores(self) -> bool: ...
    @overload
    def out_weight_silent_scores(self) -> bool: ...
    @overload
    def out_weight_silent_scores(self, setting: bool) -> None: ...
    @overload
    def out_weight_silent_scores(self, bool) -> void: ...
    @overload
    def print_all_score_headers(self) -> bool: ...
    @overload
    def print_all_score_headers(self) -> bool: ...
    @overload
    def print_all_score_headers(self, setting: bool) -> None: ...
    @overload
    def print_all_score_headers(self, bool) -> void: ...
    @overload
    def read_from_global_options(self) -> None: ...
    @overload
    def read_from_global_options(self) -> void: ...
    @overload
    def read_from_options(self, options: pyrosetta.rosetta.utility.options.OptionCollection) -> None: ...
    @overload
    def read_from_options(self, constclassutility) -> void: ...
    @overload
    def read_from_tag(self, tag) -> None: ...
    @overload
    def read_from_tag(self, classstd) -> void: ...
    @overload
    def read_through_errors(self) -> bool: ...
    @overload
    def read_through_errors(self) -> bool: ...
    @overload
    def read_through_errors(self, setting: bool) -> None: ...
    @overload
    def read_through_errors(self, bool) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def select_random(self) -> int: ...
    @overload
    def select_random(self) -> int: ...
    @overload
    def select_random(self, setting: int) -> None: ...
    @overload
    def select_random(self, int) -> void: ...
    @overload
    def select_random_set(self) -> bool: ...
    @overload
    def select_random_set(self) -> bool: ...
    @overload
    def select_range_len(self) -> int: ...
    @overload
    def select_range_len(self) -> int: ...
    @overload
    def select_range_len(self, setting: int) -> None: ...
    @overload
    def select_range_len(self, int) -> void: ...
    @overload
    def select_range_mul(self) -> int: ...
    @overload
    def select_range_mul(self) -> int: ...
    @overload
    def select_range_mul(self, setting: int) -> None: ...
    @overload
    def select_range_mul(self, int) -> void: ...
    @overload
    def select_range_start(self) -> int: ...
    @overload
    def select_range_start(self) -> int: ...
    @overload
    def select_range_start(self, setting: int) -> None: ...
    @overload
    def select_range_start(self, int) -> void: ...
    @overload
    def set_binary_output(self, setting: bool) -> None: ...
    @overload
    def set_binary_output(self, bool) -> void: ...
    @overload
    def write_failures(self) -> bool: ...
    @overload
    def write_failures(self) -> bool: ...
    @overload
    def write_failures(self, setting: bool) -> None: ...
    @overload
    def write_failures(self, bool) -> void: ...
    @overload
    def write_failures_set(self) -> bool: ...
    @overload
    def write_failures_set(self) -> bool: ...

class SilentStruct:
    @overload
    def __init__(self, opts: SilentFileOptions) -> None: ...
    @overload
    def __init__(self, arg0: SilentStruct) -> None: ...
    def add_comment(self, name: str, value: str) -> None: ...
    @overload
    def add_energy(self, scorename: str, value: float) -> None: ...
    @overload
    def add_energy(self, scorename: str, value: float, weight: float) -> None: ...
    @overload
    def add_other_struct(self, silent_struct: SilentStruct) -> None: ...
    @overload
    def add_other_struct(self, classstd) -> void: ...
    def add_parent_remark(self, name: str, value: str) -> None: ...
    @overload
    def add_string_value(self, scorename: str, value: str) -> None: ...
    @overload
    def add_string_value(self, scorename: str, value: str, index: int) -> None: ...
    @overload
    def add_submotif_info_from_line(self, line_stream: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def add_submotif_info_from_line(self, std) -> void: ...
    def assign(self) -> SilentStruct: ...
    @overload
    def clear_comments(self) -> None: ...
    @overload
    def clear_comments(self) -> void: ...
    @overload
    def clear_energies(self) -> None: ...
    @overload
    def clear_energies(self) -> void: ...
    def clone(self) -> SilentStruct: ...
    def comment_from_line(self, *args, **kwargs): ...
    @overload
    def copy_scores(self, src_ss: SilentStruct) -> None: ...
    @overload
    def copy_scores(self, constclasscore) -> void: ...
    @overload
    def decoy_tag(self) -> str: ...
    @overload
    def decoy_tag(self, tag: str) -> None: ...
    @overload
    def decoy_tag(self, conststd) -> void: ...
    def energies(self) -> pyrosetta.rosetta.utility.vector1_core_io_silent_SilentEnergy: ...
    @overload
    def energies_from_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def energies_from_pose(self, constclasscore) -> void: ...
    @overload
    def energies_into_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def energies_into_pose(self, classcore) -> void: ...
    def energy_names(self, *args, **kwargs): ...
    @overload
    def erase_comment(self, name: str) -> None: ...
    @overload
    def erase_comment(self, conststd) -> void: ...
    @overload
    def figure_out_residue_numbers_from_line(self, line_stream: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def figure_out_residue_numbers_from_line(self, std) -> void: ...
    @overload
    def figure_out_segment_ids_from_line(self, line_stream: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def figure_out_segment_ids_from_line(self, std) -> void: ...
    @overload
    def fill_other_struct_list(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def fill_other_struct_list(self, constclasscore) -> void: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constbool) -> void: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, classstd, constbool) -> void: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet) -> None: ...
    @overload
    def fill_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue_set: pyrosetta.rosetta.core.chemical.ResidueTypeSet, metapatches: bool) -> None: ...
    @overload
    def fill_pose(self, classcore, constclasscore, constbool) -> void: ...
    @overload
    def fill_struct(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def fill_struct(self, pose: pyrosetta.rosetta.core.pose.Pose, tag: str) -> None: ...
    @overload
    def fill_struct(self, constclasscore, conststd) -> void: ...
    @overload
    def fill_struct_with_residue_numbers(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def fill_struct_with_residue_numbers(self, constclasscore) -> void: ...
    @overload
    def fill_struct_with_submotif_info_list(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def fill_struct_with_submotif_info_list(self, constclasscore) -> void: ...
    @overload
    def finish_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def finish_pose(self, classcore) -> void: ...
    @overload
    def force_bitflip(self) -> bool: ...
    @overload
    def force_bitflip(self) -> bool: ...
    @overload
    def full_model_info_into_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def full_model_info_into_pose(self, classcore) -> void: ...
    def full_model_parameters(self, *args, **kwargs): ...
    def get_CA_xyz(self) -> pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t: ...
    def get_all_comments(self) -> pyrosetta.rosetta.std.map_std_string_std_string: ...
    def get_comment(self, name: str) -> str: ...
    @overload
    def get_debug_rmsd(self) -> float: ...
    @overload
    def get_debug_rmsd(self) -> double: ...
    @overload
    def get_energy(self, scorename: str) -> float: ...
    @overload
    def get_energy(self, conststd) -> double: ...
    def get_parent_remark(self, name: str) -> str: ...
    @overload
    def get_parent_remark_from_line(self, line: str) -> None: ...
    @overload
    def get_parent_remark_from_line(self, conststd) -> void: ...
    def get_self_ptr(self) -> SilentStruct: ...
    def get_silent_energies(self) -> pyrosetta.rosetta.utility.vector1_core_io_silent_SilentEnergy: ...
    def get_silent_energy(self, scorename: str) -> SilentEnergy: ...
    def get_string_value(self, scorename: str) -> str: ...
    @overload
    def has_comment(self, name: str) -> bool: ...
    @overload
    def has_comment(self, conststd) -> bool: ...
    @overload
    def has_energy(self, scorename: str) -> bool: ...
    @overload
    def has_energy(self, conststd) -> bool: ...
    @overload
    def has_parent_remark(self, name: str) -> bool: ...
    @overload
    def has_parent_remark(self, conststd) -> bool: ...
    @overload
    def init_from_lines(self, lines: pyrosetta.rosetta.utility.vector1_std_string, container) -> bool: ...
    @overload
    def init_from_lines(self, constclassutility, classcore) -> bool: ...
    @overload
    def mem_footprint(self) -> int: ...
    @overload
    def mem_footprint(self) -> unsignedlong: ...
    def nonconst_other_struct_list(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_io_silent_SilentStruct_t: ...
    @overload
    def nres(self) -> int: ...
    @overload
    def nres(self) -> unsignedlong: ...
    @overload
    def nres(self, nres: int) -> None: ...
    @overload
    def nres(self, unsignedlong) -> void: ...
    def one_letter_sequence(self) -> str: ...
    def options(self) -> SilentFileOptions: ...
    def other_struct_list(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_io_silent_SilentStruct_t: ...
    @overload
    def parse_energies(self, input: pyrosetta.rosetta.std.istream, energy_names: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def parse_energies(self, std, constclassutility) -> void: ...
    @overload
    def precision(self, precision: int) -> None: ...
    @overload
    def precision(self, unsignedlong) -> void: ...
    @overload
    def precision(self) -> int: ...
    @overload
    def precision(self) -> unsignedlong: ...
    @overload
    def print_comments(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_comments(self, std) -> void: ...
    @overload
    def print_conformation(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_conformation(self, std) -> void: ...
    @overload
    def print_header(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_header(self, std) -> void: ...
    @overload
    def print_parent_remarks(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_parent_remarks(self, std) -> void: ...
    @overload
    def print_residue_numbers(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_residue_numbers(self, std) -> void: ...
    @overload
    def print_score_header(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_score_header(self, std) -> void: ...
    @overload
    def print_scores(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_scores(self, std) -> void: ...
    @overload
    def print_submotif_info(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_submotif_info(self, std) -> void: ...
    @overload
    def read_score_headers(self, line: str, enames: pyrosetta.rosetta.utility.vector1_std_string, container) -> None: ...
    @overload
    def read_score_headers(self, conststd, classutility, classcore) -> void: ...
    @overload
    def read_sequence(self, line: str) -> bool: ...
    @overload
    def read_sequence(self, conststd) -> bool: ...
    @overload
    def rename_energies(self) -> None: ...
    @overload
    def rename_energies(self) -> void: ...
    @overload
    def residue_numbers_into_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def residue_numbers_into_pose(self, classcore) -> void: ...
    @overload
    def scoreline_prefix(self, prefix: str) -> None: ...
    @overload
    def scoreline_prefix(self, conststd) -> void: ...
    @overload
    def scoreline_prefix(self) -> str: ...
    @overload
    def sequence(self) -> pyrosetta.rosetta.core.sequence.AnnotatedSequence: ...
    @overload
    def sequence(self, sequence: pyrosetta.rosetta.core.sequence.AnnotatedSequence) -> None: ...
    @overload
    def sequence(self, constclasscore) -> void: ...
    @overload
    def set_chains(self, chains: pyrosetta.rosetta.utility.vector1_char) -> None: ...
    @overload
    def set_chains(self, constclassutility) -> void: ...
    @overload
    def set_decoy_tag(self, tag: str) -> None: ...
    @overload
    def set_decoy_tag(self, conststd) -> void: ...
    @overload
    def set_force_bitflip(self, setting: bool) -> None: ...
    @overload
    def set_force_bitflip(self, constbool) -> void: ...
    @overload
    def set_full_model_parameters(self, setting) -> None: ...
    @overload
    def set_full_model_parameters(self, classstd) -> void: ...
    @overload
    def set_residue_numbers(self, residue_numbers: pyrosetta.rosetta.utility.vector1_int) -> None: ...
    @overload
    def set_residue_numbers(self, constclassutility) -> void: ...
    @overload
    def set_segment_IDs(self, segids: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_segment_IDs(self, constclassutility) -> void: ...
    @overload
    def set_tag_from_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_tag_from_pose(self, constclasscore) -> void: ...
    @overload
    def set_valid_energies(self, valid: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_valid_energies(self, classutility) -> void: ...
    @overload
    def silent_energies(self, new_se: pyrosetta.rosetta.utility.vector1_core_io_silent_SilentEnergy) -> None: ...
    @overload
    def silent_energies(self, constclassutility) -> void: ...
    @overload
    def sort_silent_scores(self) -> None: ...
    @overload
    def sort_silent_scores(self) -> void: ...

class SilentStructCreator:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SilentStructCreator) -> None: ...
    def assign(self) -> SilentStructCreator: ...
    def create_silent_struct(self) -> SilentStruct: ...
    def keyname(self) -> str: ...

class SilentStructFactory(pyrosetta.rosetta.utility.SingletonBase_core_io_silent_SilentStructFactory_t):
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def factory_register(self, creator: SilentStructCreator) -> None: ...
    @overload
    def factory_register(self, classstd) -> void: ...
    def get_creator(self, type_name: str) -> SilentStructCreator: ...
    def get_silent_struct(self, type_name: str) -> SilentStruct: ...
    def get_silent_struct_in(self) -> SilentStruct: ...
    def get_silent_struct_out(self) -> SilentStruct: ...
    def get_ss_names(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def has_silent_struct_type(self, type_name: str) -> bool: ...
    @overload
    def has_silent_struct_type(self, conststd) -> bool: ...
    @overload
    def show_available_silent_struct_types(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show_available_silent_struct_types(self, std) -> void: ...

class SimpleSequenceData(SharedSilentData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SimpleSequenceData) -> None: ...
    def assign(self) -> SimpleSequenceData: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def sequence(self) -> str: ...
    @overload
    def set_sequence(self, sequence: str) -> None: ...
    @overload
    def set_sequence(self, std) -> void: ...

def figure_out_residue_numbers_from_line(line_stream: pyrosetta.rosetta.std.istream, residue_numbers: pyrosetta.rosetta.utility.vector1_int, chains: pyrosetta.rosetta.utility.vector1_char, segids: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
def get_outfile_name_with_tag(silent_file: str, tag: str) -> str: ...
@overload
def gzip() -> None: ...
@overload
def gzip() -> void: ...
def initialize_tag_is_done(silent_file: str) -> pyrosetta.rosetta.std.map_std_string_bool: ...
@overload
def remove_silent_file_if_it_exists(silent_file: str) -> None: ...
@overload
def remove_silent_file_if_it_exists(conststd) -> void: ...
