from typing import overload

class LengthGen(VallFragmentGen):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, frag_size: int) -> None: ...
    @overload
    def __init__(self, arg0: LengthGen) -> None: ...
    @overload
    def __init__(self, arg0: LengthGen) -> None: ...
    def assign(self, rval: LengthGen) -> LengthGen: ...
    def clone(self) -> VallFragmentGen: ...

class SecStructGen(VallFragmentGen):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ss: str) -> None: ...
    @overload
    def __init__(self, arg0: SecStructGen) -> None: ...
    @overload
    def __init__(self, arg0: SecStructGen) -> None: ...
    def assign(self, rval: SecStructGen) -> SecStructGen: ...
    def clone(self) -> VallFragmentGen: ...

class VallFragmentGen:
    def __init__(self, *args, **kwargs) -> None: ...
    def assign(self, rval: VallFragmentGen) -> VallFragmentGen: ...
    def clone(self) -> VallFragmentGen: ...
