import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from . import mpi_stream as mpi_stream
from typing import Any, overload

class FileContentsMap:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, fcontents: pyrosetta.rosetta.std.map_std_string_std_string) -> None: ...
    @overload
    def __init__(self, arg0: FileContentsMap) -> None: ...
    def assign(self) -> FileContentsMap: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def delete_contents_at_nread_limit(self, setting: bool) -> None: ...
    @overload
    def delete_contents_at_nread_limit(self, bool) -> void: ...
    @overload
    def delete_contents_at_nread_limit(self) -> bool: ...
    @overload
    def delete_contents_at_nread_limit(self) -> bool: ...
    @overload
    def delete_file_contents(self, fname: str) -> None: ...
    @overload
    def delete_file_contents(self, conststd) -> void: ...
    def get_file_contents(self, fname: str) -> str: ...
    def get_file_contents_ref(self, fname: str) -> str: ...
    @overload
    def has_file_contents(self, fname: str) -> bool: ...
    @overload
    def has_file_contents(self, conststd) -> bool: ...
    @overload
    def has_read_limit_for_file(self, fname: str) -> bool: ...
    @overload
    def has_read_limit_for_file(self, conststd) -> bool: ...
    @overload
    def increment_nread_limit(self, fname: str) -> None: ...
    @overload
    def increment_nread_limit(self, conststd) -> void: ...
    @overload
    def nread_limit_for_file(self, fname: str) -> int: ...
    @overload
    def nread_limit_for_file(self, conststd) -> unsignedlong: ...
    @overload
    def nreads_for_file(self, fname: str) -> int: ...
    @overload
    def nreads_for_file(self, conststd) -> unsignedlong: ...
    @overload
    def refuse_unexpected_files(self, setting: bool) -> None: ...
    @overload
    def refuse_unexpected_files(self, bool) -> void: ...
    @overload
    def refuse_unexpected_files(self) -> bool: ...
    @overload
    def refuse_unexpected_files(self) -> bool: ...
    def set_file_contents(self, fname: str, contents: str) -> None: ...
    @overload
    def set_nread_limit_for_file(self, fname: str, limit: int) -> None: ...
    @overload
    def set_nread_limit_for_file(self, conststd, unsignedlong) -> void: ...

class GeneralFileContents:
    @overload
    def __init__(self, filename: str) -> None: ...
    @overload
    def __init__(self, arg0: GeneralFileContents) -> None: ...
    def assign(self) -> GeneralFileContents: ...
    def clone(self) -> GeneralFileContents: ...
    def get_file_contents(self) -> str: ...

class GeneralFileContentsVector:
    @overload
    def __init__(self, filename: str) -> None: ...
    @overload
    def __init__(self, arg0: GeneralFileContentsVector) -> None: ...
    def assign(self) -> GeneralFileContentsVector: ...
    def clone(self) -> GeneralFileContentsVector: ...
    def get_file_contents(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...

class GeneralFileManager(pyrosetta.rosetta.utility.SingletonBase_utility_io_GeneralFileManager_t):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_file_contents(self, filename: str) -> str: ...

class GeneralFileManagerVector(pyrosetta.rosetta.utility.SingletonBase_utility_io_GeneralFileManagerVector_t):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_file_contents(self, filename: str) -> pyrosetta.rosetta.utility.vector1_std_string: ...

class TarFileHeader:
    def __init__(self) -> None: ...

class TarParser:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TarParser) -> None: ...
    @overload
    @staticmethod
    def parseFileSize(tarHeader: TarFileHeader) -> int: ...
    @overload
    @staticmethod
    def parseFileSize(conststructutility) -> unsignedlonglong: ...
    def read(self, datastream: pyrosetta.rosetta.std.istream, filename: str, currentData: str) -> None: ...

class icstream(irstream):
    def __init__(self, i_stream_a: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def bad(self) -> bool: ...
    @overload
    def bad(self) -> bool: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def compressed(self) -> bool: ...
    @overload
    def compressed(self) -> bool: ...
    @overload
    def eof(self) -> bool: ...
    @overload
    def eof(self) -> bool: ...
    @overload
    def fail(self) -> bool: ...
    @overload
    def fail(self) -> bool: ...
    @overload
    def get(self) -> int: ...
    @overload
    def get(self) -> int: ...
    @overload
    def get(self, c: str) -> icstream: ...
    @overload
    def get(self, str: str, count: int) -> icstream: ...
    @overload
    def get(self, str: str, count: int, delim: str) -> icstream: ...
    @overload
    def get(self, str: str, count: int) -> icstream: ...
    @overload
    def get(self, str: str, count: int, delim: str) -> icstream: ...
    @overload
    def getline(self, line: str, count: int) -> icstream: ...
    @overload
    def getline(self, line: str, count: int, delim: str) -> icstream: ...
    @overload
    def getline(self, line: str) -> icstream: ...
    @overload
    def getline(self, line: str, delim: str) -> icstream: ...
    @overload
    def good(self) -> bool: ...
    @overload
    def good(self) -> bool: ...
    @overload
    def gzipped(self) -> bool: ...
    @overload
    def gzipped(self) -> bool: ...
    @overload
    def ignore(self) -> icstream: ...
    @overload
    def ignore(self, count: int) -> icstream: ...
    @overload
    def ignore(self, count: int, delim: str) -> icstream: ...
    @overload
    def peek(self) -> int: ...
    @overload
    def peek(self) -> int: ...
    def putback(self, c: str) -> icstream: ...
    def rdbuf(self) -> pyrosetta.rosetta.std.streambuf: ...
    @overload
    def read(self, str: str, count: int) -> icstream: ...
    @overload
    def read(self, str: str, count: int) -> icstream: ...
    @overload
    def readsome(self, str: str, count: int) -> int: ...
    @overload
    def readsome(self, str: str, count: int) -> int: ...
    @overload
    def readsome(self, std, constlong) -> long: ...
    @overload
    def seek_beg(self) -> None: ...
    @overload
    def seek_beg(self) -> void: ...
    def stream(self) -> pyrosetta.rosetta.std.istream: ...
    @overload
    def uncompressed(self) -> bool: ...
    @overload
    def uncompressed(self) -> bool: ...
    def unget(self) -> icstream: ...
    def __call__(self) -> pyrosetta.rosetta.std.istream: ...

class irstream:
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def bad(self) -> bool: ...
    @overload
    def bad(self) -> bool: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def compressed(self) -> bool: ...
    @overload
    def compressed(self) -> bool: ...
    @overload
    def eof(self) -> bool: ...
    @overload
    def eof(self) -> bool: ...
    @overload
    def fail(self) -> bool: ...
    @overload
    def fail(self) -> bool: ...
    @overload
    def get(self) -> int: ...
    @overload
    def get(self) -> int: ...
    @overload
    def get(self, c: str) -> irstream: ...
    @overload
    def get(self, str: str, count: int) -> irstream: ...
    @overload
    def get(self, str: str, count: int, delim: str) -> irstream: ...
    @overload
    def get(self, str: str, count: int) -> irstream: ...
    @overload
    def get(self, str: str, count: int, delim: str) -> irstream: ...
    @overload
    def getline(self, line: str, count: int) -> irstream: ...
    @overload
    def getline(self, line: str, count: int, delim: str) -> irstream: ...
    @overload
    def getline(self, line: str) -> irstream: ...
    @overload
    def getline(self, line: str, delim: str) -> irstream: ...
    @overload
    def good(self) -> bool: ...
    @overload
    def good(self) -> bool: ...
    @overload
    def gzipped(self) -> bool: ...
    @overload
    def gzipped(self) -> bool: ...
    @overload
    def ignore(self) -> irstream: ...
    @overload
    def ignore(self, count: int) -> irstream: ...
    @overload
    def ignore(self, count: int, delim: str) -> irstream: ...
    @overload
    def peek(self) -> int: ...
    @overload
    def peek(self) -> int: ...
    def putback(self, c: str) -> irstream: ...
    def rdbuf(self) -> pyrosetta.rosetta.std.streambuf: ...
    @overload
    def read(self, str: str, count: int) -> irstream: ...
    @overload
    def read(self, str: str, count: int) -> irstream: ...
    @overload
    def readsome(self, str: str, count: int) -> int: ...
    @overload
    def readsome(self, str: str, count: int) -> int: ...
    @overload
    def readsome(self, std, constlong) -> long: ...
    @overload
    def seek_beg(self) -> None: ...
    @overload
    def seek_beg(self) -> void: ...
    def stream(self) -> pyrosetta.rosetta.std.istream: ...
    @overload
    def uncompressed(self) -> bool: ...
    @overload
    def uncompressed(self) -> bool: ...
    def unget(self) -> irstream: ...
    def __call__(self) -> pyrosetta.rosetta.std.istream: ...

class izstream(irstream):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, filename_a: str, open_mode: int) -> None: ...
    @overload
    def bad(self) -> bool: ...
    @overload
    def bad(self) -> bool: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def close(self) -> None: ...
    @overload
    def close(self) -> void: ...
    @overload
    def compressed(self) -> bool: ...
    @overload
    def compressed(self) -> bool: ...
    @overload
    def eof(self) -> bool: ...
    @overload
    def eof(self) -> bool: ...
    @overload
    def fail(self) -> bool: ...
    @overload
    def fail(self) -> bool: ...
    def filename(self) -> str: ...
    @overload
    def gcount(self) -> int: ...
    @overload
    def gcount(self) -> long: ...
    @overload
    def get(self) -> int: ...
    @overload
    def get(self) -> int: ...
    @overload
    def get(self, c: str) -> izstream: ...
    @overload
    def get(self, str: str, count: int) -> izstream: ...
    @overload
    def get(self, str: str, count: int, delim: str) -> izstream: ...
    @overload
    def get(self, str: str, count: int) -> izstream: ...
    @overload
    def get(self, str: str, count: int, delim: str) -> izstream: ...
    @staticmethod
    def get_alternative_search_paths() -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def getline(self, line: str, count: int) -> izstream: ...
    @overload
    def getline(self, line: str, count: int, delim: str) -> izstream: ...
    @overload
    def getline(self, line: str) -> izstream: ...
    @overload
    def getline(self, line: str, delim: str) -> izstream: ...
    @overload
    def good(self) -> bool: ...
    @overload
    def good(self) -> bool: ...
    @overload
    def gzipped(self) -> bool: ...
    @overload
    def gzipped(self) -> bool: ...
    @overload
    def ignore(self) -> izstream: ...
    @overload
    def ignore(self, count: int) -> izstream: ...
    @overload
    def ignore(self, count: int, delim: str) -> izstream: ...
    @overload
    def open(self, filename_a: str) -> None: ...
    @overload
    def open(self, filename_a: str, open_mode: int) -> None: ...
    @overload
    def open(self, conststd, unsignedint) -> void: ...
    @overload
    def peek(self) -> int: ...
    @overload
    def peek(self) -> int: ...
    def putback(self, c: str) -> izstream: ...
    def rdbuf(self) -> pyrosetta.rosetta.std.streambuf: ...
    @overload
    def read(self, str: str, count: int) -> izstream: ...
    @overload
    def read(self, str: str, count: int) -> izstream: ...
    @overload
    def readsome(self, str: str, count: int) -> int: ...
    @overload
    def readsome(self, str: str, count: int) -> int: ...
    @overload
    def readsome(self, std, constlong) -> long: ...
    @overload
    def seek_beg(self) -> None: ...
    @overload
    def seek_beg(self) -> void: ...
    @overload
    @staticmethod
    def set_alternative_search_paths(alternative_search_paths: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    @staticmethod
    def set_alternative_search_paths(classutility) -> void: ...
    def stream(self) -> pyrosetta.rosetta.std.istream: ...
    @overload
    def uncompressed(self) -> bool: ...
    @overload
    def uncompressed(self) -> bool: ...
    def unget(self) -> izstream: ...
    def __call__(self) -> pyrosetta.rosetta.std.istream: ...
    @overload
    def __rshift__(self, t: str) -> pyrosetta.rosetta.std.istream: ...
    @overload
    def __rshift__(self, t: int) -> pyrosetta.rosetta.std.istream: ...
    @overload
    def __rshift__(self, t: str) -> pyrosetta.rosetta.std.istream: ...
    @overload
    def __rshift__(self, t: float) -> pyrosetta.rosetta.std.istream: ...
    @overload
    def __rshift__(self, t: float) -> pyrosetta.rosetta.std.istream: ...

class ocstream(orstream):
    def __init__(self, o_stream_a: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def bad(self) -> bool: ...
    @overload
    def bad(self) -> bool: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def compressed(self) -> bool: ...
    @overload
    def compressed(self) -> bool: ...
    @overload
    def eof(self) -> bool: ...
    @overload
    def eof(self) -> bool: ...
    @overload
    def fail(self) -> bool: ...
    @overload
    def fail(self) -> bool: ...
    def flush(self) -> ocstream: ...
    @overload
    def good(self) -> bool: ...
    @overload
    def good(self) -> bool: ...
    @overload
    def gzipped(self) -> bool: ...
    @overload
    def gzipped(self) -> bool: ...
    def put(self, c: str) -> ocstream: ...
    def rdbuf(self) -> pyrosetta.rosetta.std.streambuf: ...
    def stream(self) -> pyrosetta.rosetta.std.ostream: ...
    @overload
    def uncompressed(self) -> bool: ...
    @overload
    def uncompressed(self) -> bool: ...
    @overload
    def write(self, str: str, count: int) -> ocstream: ...
    @overload
    def write(self, str: str, count: int) -> ocstream: ...
    def __call__(self) -> pyrosetta.rosetta.std.ostream: ...

class orstream:
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def bad(self) -> bool: ...
    @overload
    def bad(self) -> bool: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def compressed(self) -> bool: ...
    @overload
    def compressed(self) -> bool: ...
    @overload
    def eof(self) -> bool: ...
    @overload
    def eof(self) -> bool: ...
    @overload
    def fail(self) -> bool: ...
    @overload
    def fail(self) -> bool: ...
    def flush(self) -> orstream: ...
    @overload
    def good(self) -> bool: ...
    @overload
    def good(self) -> bool: ...
    @overload
    def gzipped(self) -> bool: ...
    @overload
    def gzipped(self) -> bool: ...
    def put(self, c: str) -> orstream: ...
    def rdbuf(self) -> pyrosetta.rosetta.std.streambuf: ...
    def stream(self) -> pyrosetta.rosetta.std.ostream: ...
    @overload
    def uncompressed(self) -> bool: ...
    @overload
    def uncompressed(self) -> bool: ...
    @overload
    def write(self, str: str, count: int) -> orstream: ...
    @overload
    def write(self, str: str, count: int) -> orstream: ...
    def __call__(self) -> pyrosetta.rosetta.std.ostream: ...

class ozstream(orstream):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: int) -> None: ...
    @overload
    def __init__(self, filename_a: str, open_mode: int, buf_size: int) -> None: ...
    @overload
    @staticmethod
    def MPI_reroute_rank() -> int: ...
    @overload
    @staticmethod
    def MPI_reroute_rank() -> int: ...
    @overload
    def bad(self) -> bool: ...
    @overload
    def bad(self) -> bool: ...
    @overload
    def buffer_size(self) -> int: ...
    @overload
    def buffer_size(self) -> long: ...
    @overload
    def buffer_size(self, buf_size: int) -> None: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def close(self) -> None: ...
    @overload
    def close(self) -> void: ...
    @overload
    def compressed(self) -> bool: ...
    @overload
    def compressed(self) -> bool: ...
    @staticmethod
    def enable_MPI_reroute(min_client_rank: int, master_rank: int) -> None: ...
    @overload
    def eof(self) -> bool: ...
    @overload
    def eof(self) -> bool: ...
    @overload
    def fail(self) -> bool: ...
    @overload
    def fail(self) -> bool: ...
    def filename(self) -> str: ...
    def flush(self) -> ozstream: ...
    @overload
    def flush_finalize(self) -> ozstream: ...
    @overload
    def flush_finalize(self) -> Any: ...
    @overload
    def good(self) -> bool: ...
    @overload
    def good(self) -> bool: ...
    @overload
    def gzipped(self) -> bool: ...
    @overload
    def gzipped(self) -> bool: ...
    @overload
    def open(self, filename_a: str) -> None: ...
    @overload
    def open(self, filename_a: str, open_mode: int) -> None: ...
    @overload
    def open(self, conststd, unsignedint) -> void: ...
    @overload
    def open_append(self, filename_a: str) -> None: ...
    @overload
    def open_append(self, conststd) -> void: ...
    @overload
    def open_append_if_existed(self, filename_a: str, preprinted_header: pyrosetta.rosetta.std.stringstream) -> None: ...
    @overload
    def open_append_if_existed(self, conststd, std) -> void: ...
    def put(self, c: str) -> ozstream: ...
    def rdbuf(self) -> pyrosetta.rosetta.std.streambuf: ...
    def stream(self) -> pyrosetta.rosetta.std.ostream: ...
    @overload
    def uncompressed(self) -> bool: ...
    @overload
    def uncompressed(self) -> bool: ...
    @overload
    def write(self, str: str, count: int) -> ozstream: ...
    @overload
    def write(self, str: str, count: int) -> ozstream: ...
    @overload
    def zflush(self) -> None: ...
    @overload
    def zflush(self) -> void: ...
    @overload
    def zflush_finalize(self) -> None: ...
    @overload
    def zflush_finalize(self) -> Any: ...
    @overload
    def zflush_finalize(self) -> void: ...
    def __call__(self) -> pyrosetta.rosetta.std.ostream: ...
    def __lshift__(self, t: str) -> ozstream: ...

def base64_decode(s: str) -> str: ...
def base64_encode(len: int) -> str: ...
def get_lines_from_file_data(filename: str) -> pyrosetta.rosetta.utility.vector1_std_string: ...
@overload
def getline(stream: izstream, line: str) -> izstream: ...
@overload
def getline(stream: izstream, line: str, delim: str) -> izstream: ...
@overload
def remove_inline_comments(line: str) -> None: ...
@overload
def remove_inline_comments(std) -> void: ...
@overload
def skip(stream: izstream) -> pyrosetta.rosetta.std.istream: ...
@overload
def skip(stream: pyrosetta.rosetta.std.istream) -> pyrosetta.rosetta.std.istream: ...
