import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.protocols.sewing.data_storage
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import overload

class AlignmentFGMSettings:
    match_segments: str
    pose_segment_ends: str
    pose_segment_starts: str
    recursive_depth: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AlignmentFGMSettings) -> None: ...
    def assign(self) -> AlignmentFGMSettings: ...

class AlignmentFileGeneratorMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AlignmentFileGeneratorMover) -> None: ...
    @overload
    def __init__(self, arg0: AlignmentFileGeneratorMover) -> None: ...
    @overload
    def __init__(self, edge_file_reader, model_file_name: str, alignment_file_name: str) -> None: ...
    @overload
    def __init__(self, edge_file_reader, model_file_name: str) -> None: ...
    @overload
    def __init__(self, model_file_name: str, edge_file_name: str, match_segments: pyrosetta.rosetta.utility.vector1_unsigned_long, pose_segment_starts: pyrosetta.rosetta.utility.vector1_unsigned_long, pose_segment_ends: pyrosetta.rosetta.utility.vector1_unsigned_long, recursive_depth: int) -> None: ...
    @overload
    def __init__(self, bmg) -> None: ...
    @overload
    @staticmethod
    def add_pose_segments_to_segment_vector(pose: pyrosetta.rosetta.core.pose.Pose, partner_pose: pyrosetta.rosetta.core.pose.Pose, segvec: SegmentVector, pdb_segments: pyrosetta.rosetta.std.map_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t_std_allocator_std_pair_const_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t, pose_segment_starts_string: str, pose_segment_ends_string: str, pose_segment_dssp: str, ligands: pyrosetta.rosetta.utility.vector1_protocols_sewing_data_storage_LigandDescription, partner_ligands: pyrosetta.rosetta.std.map_unsigned_long_std_shared_ptr_const_protocols_sewing_data_storage_LigandResidue_t_std_allocator_std_pair_const_unsigned_long_std_shared_ptr_const_protocols_sewing_data_storage_LigandResidue_t, expanded_ligands: pyrosetta.rosetta.utility.vector1_protocols_sewing_data_storage_LigandDescription, required_resnums: str, required_selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, strict_dssp_changes: bool) -> int: ...
    @overload
    @staticmethod
    def add_pose_segments_to_segment_vector(pose: pyrosetta.rosetta.core.pose.Pose, partner_pose: pyrosetta.rosetta.core.pose.Pose, bmg, ligands: pyrosetta.rosetta.utility.vector1_protocols_sewing_data_storage_LigandDescription, partner_ligands: pyrosetta.rosetta.std.map_unsigned_long_std_shared_ptr_const_protocols_sewing_data_storage_LigandResidue_t_std_allocator_std_pair_const_unsigned_long_std_shared_ptr_const_protocols_sewing_data_storage_LigandResidue_t, expanded_ligands: pyrosetta.rosetta.utility.vector1_protocols_sewing_data_storage_LigandDescription, required_resnums: str, required_selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, set_segments_from_dssp: bool) -> int: ...
    @staticmethod
    def alignment_settings_from_tag(tag: pyrosetta.rosetta.utility.tag.Tag) -> AlignmentFGMSettings: ...
    @staticmethod
    def append_ligands_subelement(subs: pyrosetta.rosetta.utility.tag.XMLSchemaSimpleSubelementList, xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition, include_coord: bool) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> AlignmentFileGeneratorMover: ...
    @overload
    @staticmethod
    def basis_map_from_alignment(alignment: AlignmentFGMSettings, pose: pyrosetta.rosetta.core.pose.Pose, bmg) -> None: ...
    @overload
    @staticmethod
    def basis_map_from_alignment(conststructprotocols, constclasscore, classstd) -> void: ...
    @overload
    def basis_map_generator(self, bmg) -> None: ...
    @overload
    def basis_map_generator(self, classstd) -> void: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    def get_required_resnums(self) -> str: ...
    def get_required_selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @staticmethod
    def ligands_subtag_ct_namer() -> str: ...
    @overload
    @staticmethod
    def parse_ligand_conformers(ligands: pyrosetta.rosetta.utility.vector1_protocols_sewing_data_storage_LigandDescription) -> None: ...
    @overload
    @staticmethod
    def parse_ligand_conformers(classutility) -> void: ...
    @overload
    @staticmethod
    def parse_ligands_tag(ligands_tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap, ligands: pyrosetta.rosetta.utility.vector1_protocols_sewing_data_storage_LigandDescription) -> None: ...
    @overload
    @staticmethod
    def parse_ligands_tag(classstd, constclassbasic, classutility) -> void: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_required_resnums(self) -> None: ...
    @overload
    def set_required_resnums(self, std) -> void: ...
    @overload
    def set_required_selector(self) -> None: ...
    @overload
    def set_required_selector(self, classstd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class AlignmentFileGeneratorMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AlignmentFileGeneratorMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: AlignmentFileGeneratorMoverCreator) -> None: ...
    def assign(self) -> AlignmentFileGeneratorMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class AlignmentGenerator:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, hasher_settings: HasherSettings, segment_vector: SegmentVector) -> None: ...
    @overload
    def __init__(self, hasher_settings: HasherSettings, segment_vector: SegmentVector, pdbsegs: pyrosetta.rosetta.std.map_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t_std_allocator_std_pair_const_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t) -> None: ...
    @overload
    def __init__(self, arg0: AlignmentGenerator) -> None: ...
    def assign(self) -> AlignmentGenerator: ...
    def clone(self) -> AlignmentGenerator: ...
    def const_pdb_segments(self) -> pyrosetta.rosetta.std.map_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t_std_allocator_std_pair_const_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t: ...
    def get_all_alignments(self, s1: pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment, s2: pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment) -> pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t: ...
    @overload
    def hasher_settings(self) -> HasherSettings: ...
    @overload
    def hasher_settings(self, hs: HasherSettings) -> None: ...
    @overload
    def hasher_settings(self, structprotocols) -> void: ...
    @overload
    def pdb_segments(self) -> pyrosetta.rosetta.std.map_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t_std_allocator_std_pair_const_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t: ...
    @overload
    def pdb_segments(self) -> None: ...
    @overload
    def segment_vector(self) -> SegmentVector: ...
    @overload
    def segment_vector(self, segvec: SegmentVector) -> None: ...
    @overload
    def segment_vector(self, classstd) -> void: ...

class AlignmentSettings:
    match_segments_: pyrosetta.rosetta.utility.vector1_unsigned_long
    recursive_depth_: int
    segments_: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, match_segments: pyrosetta.rosetta.utility.vector1_unsigned_long, segments: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t, recursive_depth: int) -> None: ...
    @overload
    def __init__(self, arg0: AlignmentSettings) -> None: ...
    def assign(self) -> AlignmentSettings: ...

class BasisMapGenerator:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: BasisMapGenerator) -> None: ...
    @overload
    def __init__(self, edge_file_reader, segments: SegmentVector) -> None: ...
    @overload
    def __init__(self, edge_file_reader, model_file_name: str, alignment_file_name: str) -> None: ...
    @overload
    def __init__(self, edge_file_reader, model_file_name: str) -> None: ...
    @overload
    def __init__(self, model_file_name: str, edge_file_name: str, match_segments: pyrosetta.rosetta.utility.vector1_unsigned_long, pose_segment_starts: pyrosetta.rosetta.utility.vector1_unsigned_long, pose_segment_ends: pyrosetta.rosetta.utility.vector1_unsigned_long, recursive_depth: int) -> None: ...
    @overload
    def alignment_generator(self) -> AlignmentGenerator: ...
    @overload
    def alignment_generator(self, ag: AlignmentGenerator) -> None: ...
    @overload
    def alignment_generator(self, classstd) -> void: ...
    @overload
    def alignment_settings(self) -> AlignmentSettings: ...
    @overload
    def alignment_settings(self, _as: AlignmentSettings) -> None: ...
    @overload
    def alignment_settings(self, structprotocols) -> void: ...
    @overload
    def alignment_settings_from_options(self) -> None: ...
    @overload
    def alignment_settings_from_options(self) -> void: ...
    def assign(self) -> BasisMapGenerator: ...
    def basis_map(self, *args, **kwargs): ...
    @overload
    def basis_pair_is_valid(self, basis_pair: tuple[pyrosetta.rosetta.protocols.sewing.data_storage.Basis, pyrosetta.rosetta.protocols.sewing.data_storage.Basis], first_is_N: bool) -> bool: ...
    @overload
    def basis_pair_is_valid(self, structstd, classprotocols, bool) -> bool: ...
    def clone(self) -> BasisMapGenerator: ...
    def const_pdb_segments(self) -> pyrosetta.rosetta.std.map_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t_std_allocator_std_pair_const_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t: ...
    @overload
    def delete_segment_basis_pairs(self) -> None: ...
    @overload
    def delete_segment_basis_pairs(self, unsignedlong) -> void: ...
    @overload
    def edge_file_from_options(self) -> None: ...
    @overload
    def edge_file_from_options(self) -> void: ...
    def edge_file_reader(self, *args, **kwargs): ...
    def get_basis_pair_for_local_segments(self, seg1: pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment, seg2: pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment, first_is_N: bool) -> tuple[bool, tuple[pyrosetta.rosetta.protocols.sewing.data_storage.Basis, pyrosetta.rosetta.protocols.sewing.data_storage.Basis]]: ...
    def get_basis_pair_for_segment(self, segment_id: int) -> tuple[pyrosetta.rosetta.protocols.sewing.data_storage.Basis, pyrosetta.rosetta.protocols.sewing.data_storage.Basis]: ...
    def get_basis_pair_for_segment_pair(self, seg1: int, seg2: int, first_is_N: bool) -> tuple[pyrosetta.rosetta.protocols.sewing.data_storage.Basis, pyrosetta.rosetta.protocols.sewing.data_storage.Basis]: ...
    def get_basis_res_bounds(self, seg1: pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment, seg2: pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment, first_is_N: bool) -> tuple[tuple[int, int], tuple[int, int]]: ...
    @overload
    def hasher_settings(self) -> HasherSettings: ...
    @overload
    def hasher_settings(self, hs: HasherSettings) -> None: ...
    @overload
    def hasher_settings(self, structprotocols) -> void: ...
    @overload
    def initialize_from_options(self) -> None: ...
    @overload
    def initialize_from_options(self) -> void: ...
    @overload
    def model_file_from_options(self) -> None: ...
    @overload
    def model_file_from_options(self) -> void: ...
    @overload
    def pdb_segments(self) -> pyrosetta.rosetta.std.map_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t_std_allocator_std_pair_const_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t: ...
    @overload
    def pdb_segments(self) -> None: ...
    @overload
    def read_alignments_from_file(self, file_name: str) -> None: ...
    @overload
    def read_alignments_from_file(self, std) -> void: ...
    @overload
    def segment_vector(self) -> SegmentVector: ...
    @overload
    def segment_vector(self, segvec: SegmentVector) -> None: ...
    @overload
    def segment_vector(self, classstd) -> void: ...
    def segs_can_chimerize(self, seg1: pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment, seg2: pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment, first_is_N: bool) -> tuple[bool, bool]: ...
    def set_alignment_settings(self, match_segments: pyrosetta.rosetta.utility.vector1_unsigned_long, pose_segment_starts: pyrosetta.rosetta.utility.vector1_unsigned_long, pose_segment_ends: pyrosetta.rosetta.utility.vector1_unsigned_long, recursive_depth: int) -> None: ...
    @overload
    def set_edge_file(self, edge_file: str) -> None: ...
    @overload
    def set_edge_file(self, std) -> void: ...
    @overload
    def set_edge_file_reader(self, edge_file_reader) -> None: ...
    @overload
    def set_edge_file_reader(self, classstd) -> void: ...
    @overload
    def set_model_file(self, model_file_name: str) -> None: ...
    @overload
    def set_model_file(self, std) -> void: ...
    def set_private_data(self, model_file_name: str, edge_file_name: str, match_segments: pyrosetta.rosetta.utility.vector1_unsigned_long, pose_segment_starts: pyrosetta.rosetta.utility.vector1_unsigned_long, pose_segment_ends: pyrosetta.rosetta.utility.vector1_unsigned_long, recursive_depth: int) -> None: ...
    @overload
    def version(self) -> int: ...
    @overload
    def version(self) -> unsignedlong: ...
    @overload
    def version(self, ver: int) -> None: ...
    @overload
    def version(self, unsignedlong) -> void: ...
    @overload
    def write_alignments_to_file(self, file_name: str) -> None: ...
    @overload
    def write_alignments_to_file(self, std) -> void: ...

class EdgeMapGenerator:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, model_file_name: str, boxes_per_dimension: int, min_hash_score: int, max_clash_score: int, edge_file_name: str, hash_opposite_termini: bool) -> None: ...
    @overload
    def __init__(self, arg0: EdgeMapGenerator) -> None: ...
    @overload
    def __init__(self, edge_file_name: str) -> None: ...
    @overload
    def append_to_edge_map(self, base_seg_id: int) -> None: ...
    @overload
    def append_to_edge_map(self, unsignedlong) -> void: ...
    def assign(self) -> EdgeMapGenerator: ...
    def clone(self) -> EdgeMapGenerator: ...
    def const_pdb_segments(self) -> pyrosetta.rosetta.std.map_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t_std_allocator_std_pair_const_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t: ...
    def edge_exists(self, seg1: pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment, seg2: pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment, hasher) -> bool: ...
    @overload
    def edge_file_name(self) -> str: ...
    @overload
    def edge_file_name(self, name: str) -> None: ...
    @overload
    def edge_file_name(self, std) -> void: ...
    def edge_map(self, *args, **kwargs): ...
    @overload
    def generate_edge_file(self) -> None: ...
    @overload
    def generate_edge_file(self) -> void: ...
    def get_terminal_segments(self) -> tuple[pyrosetta.rosetta.utility.vector1_unsigned_long, pyrosetta.rosetta.utility.vector1_unsigned_long]: ...
    @overload
    def hasher_settings(self) -> HasherSettings: ...
    @overload
    def hasher_settings(self, hs: HasherSettings) -> None: ...
    @overload
    def hasher_settings(self, structprotocols) -> void: ...
    @overload
    def initialize_from_options(self) -> None: ...
    @overload
    def initialize_from_options(self) -> void: ...
    @overload
    def is_edge_file_loaded(self) -> bool: ...
    @overload
    def is_edge_file_loaded(self) -> bool: ...
    @overload
    def load_edge_file(self, edge_file_name: str) -> None: ...
    @overload
    def load_edge_file(self, std) -> void: ...
    @overload
    def pdb_segments(self) -> pyrosetta.rosetta.std.map_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t_std_allocator_std_pair_const_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t: ...
    @overload
    def pdb_segments(self) -> None: ...
    @overload
    def read_edge_file(self) -> None: ...
    @overload
    def read_edge_file(self) -> void: ...
    @overload
    def segment_vector(self) -> SegmentVector: ...
    @overload
    def segment_vector(self, segvector: SegmentVector) -> None: ...
    @overload
    def segment_vector(self, classstd) -> void: ...
    def set_private_data(self, model_file_name: str, boxes_per_dimension: int, min_hash_score: int, max_clash_score: int, hash_opposite_termini: bool) -> None: ...
    @overload
    def version(self) -> int: ...
    @overload
    def version(self) -> unsignedlong: ...
    @overload
    def version(self, ver: int) -> None: ...
    @overload
    def version(self, unsignedlong) -> void: ...
    @overload
    def write_edges_for_segment(self, current_n_segment: int, hasher, output_file: pyrosetta.rosetta.std.ostream, c_segs: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def write_edges_for_segment(self, unsignedlong, classstd, std, constclassutility) -> void: ...

class HashValue:
    atomno: int
    basis_resnum: int
    basis_segment_id: int
    resnum: int
    segment_id: int
    def __init__(self) -> None: ...

class Hasher:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, hasher_settings: HasherSettings, segment_vector: SegmentVector) -> None: ...
    @overload
    def __init__(self, hasher_settings: HasherSettings, segment_vector: SegmentVector, pdb_segments: pyrosetta.rosetta.std.map_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t_std_allocator_std_pair_const_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t) -> None: ...
    @overload
    def __init__(self, arg0: Hasher) -> None: ...
    def assign(self) -> Hasher: ...
    def can_hash(self, seg1: pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment, seg2: pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment) -> bool: ...
    def clone(self) -> Hasher: ...
    def const_pdb_segments(self) -> pyrosetta.rosetta.std.map_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t_std_allocator_std_pair_const_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t: ...
    def generate_key(self, atom: pyrosetta.rosetta.core.conformation.Atom) -> pyrosetta.rosetta.utility.fixedsizearray1_int_3UL_t: ...
    @overload
    def get_hash_map_size(self) -> int: ...
    @overload
    def get_hash_map_size(self) -> unsignedlong: ...
    def get_seg1(self) -> pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment: ...
    def get_seg2(self) -> pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment: ...
    @overload
    def hash_segments(self, transformed_segment: pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment, basis_residue: pyrosetta.rosetta.protocols.sewing.data_storage.Basis) -> None: ...
    @overload
    def hash_segments(self, constclassstd, constclassprotocols) -> void: ...
    @overload
    def hasher_settings(self) -> HasherSettings: ...
    @overload
    def hasher_settings(self, hasher_settings: HasherSettings) -> None: ...
    @overload
    def hasher_settings(self, conststructprotocols) -> void: ...
    @overload
    def initialize_from_options(self) -> None: ...
    @overload
    def initialize_from_options(self) -> void: ...
    def initialize_hashmap(self, basis_pair: tuple[pyrosetta.rosetta.protocols.sewing.data_storage.Basis, pyrosetta.rosetta.protocols.sewing.data_storage.Basis]) -> pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment: ...
    def iterate_over_basis_pairs(self, *args, **kwargs): ...
    @overload
    def pdb_segments(self) -> pyrosetta.rosetta.std.map_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t_std_allocator_std_pair_const_unsigned_long_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t: ...
    @overload
    def pdb_segments(self) -> None: ...
    @overload
    def score_basis_pair(self, basis_pair: tuple[pyrosetta.rosetta.protocols.sewing.data_storage.Basis, pyrosetta.rosetta.protocols.sewing.data_storage.Basis]) -> bool: ...
    @overload
    def score_basis_pair(self, conststructstd, classprotocols) -> bool: ...
    @overload
    def segment_vector(self) -> SegmentVector: ...
    @overload
    def segment_vector(self, segment_vector: SegmentVector) -> None: ...
    @overload
    def segment_vector(self, classstd) -> void: ...
    @overload
    def transform_segments(self, current_basis: pyrosetta.rosetta.protocols.sewing.data_storage.Basis, first: bool) -> None: ...
    @overload
    def transform_segments(self, classprotocols, bool) -> void: ...

class HasherSettings:
    boxes_per_dimension: int
    hash_between_termini: bool
    max_clash_score: int
    min_hash_score: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, max_clash_score_temp: int, min_hash_score_temp: int, boxes_per_dimension_temp: int, hash_between_termini_temp: bool) -> None: ...
    def assign(self) -> HasherSettings: ...

class IdealContact:
    ligand_atom: int
    max_contacts: int
    preferred_contact_angle: float
    preferred_dihedral_1: float
    preferred_dihedral_2: float
    preferred_distance: float
    @overload
    def __init__(self, arg0: IdealContact) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def assign(self) -> IdealContact: ...

class LigandBindingResPlacer:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LigandBindingResPlacer) -> None: ...
    def assign(self) -> LigandBindingResPlacer: ...
    def choose_best_metal_coordinator(self, assembly: pyrosetta.rosetta.protocols.sewing.data_storage.SmartAssembly) -> tuple[pyrosetta.rosetta.protocols.sewing.data_storage.SmartSegment, bool]: ...
    @overload
    def contacts_remaining(self) -> int: ...
    @overload
    def contacts_remaining(self) -> unsignedlong: ...
    @staticmethod
    def define_ideal_contacts_subelement(subs: pyrosetta.rosetta.utility.tag.XMLSchemaSimpleSubelementList, xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @staticmethod
    def generate_ligand_key() -> pyrosetta.rosetta.utility.fixedsizearray1_int_3UL_t: ...
    @overload
    def get_best_geometry_score(self) -> float: ...
    @overload
    def get_best_geometry_score(self) -> double: ...
    @overload
    def get_geometry_score_weight(self) -> float: ...
    @overload
    def get_geometry_score_weight(self) -> double: ...
    def get_ligand(self, *args, **kwargs): ...
    def get_possible_coordinations(self) -> pyrosetta.rosetta.std.map_std_pair_unsigned_long_unsigned_long_t_std_set_protocols_sewing_hashing_LigandCoordInfo_t_std_less_std_pair_unsigned_long_unsigned_long_t_std_allocator_std_pair_const_std_pair_unsigned_long_unsigned_long_std_set_protocols_sewing_hashing_LigandCoordInfo_t: ...
    def identify_possible_binders(self, assembly: pyrosetta.rosetta.protocols.sewing.data_storage.SmartAssembly) -> pyrosetta.rosetta.std.map_std_pair_unsigned_long_unsigned_long_t_std_set_protocols_sewing_hashing_LigandCoordInfo_t_std_less_std_pair_unsigned_long_unsigned_long_t_std_allocator_std_pair_const_std_pair_unsigned_long_unsigned_long_std_set_protocols_sewing_hashing_LigandCoordInfo_t: ...
    @staticmethod
    def ligand_subtag_ct_namer(tag: str) -> str: ...
    def make_aligned_residue(self) -> pyrosetta.rosetta.core.conformation.Residue: ...
    @overload
    @staticmethod
    def parse_ideal_contacts(tag: pyrosetta.rosetta.utility.tag.Tag, ligands: pyrosetta.rosetta.utility.vector1_protocols_sewing_data_storage_LigandDescription) -> None: ...
    @overload
    @staticmethod
    def parse_ideal_contacts(classstd, classutility) -> void: ...
    @overload
    @staticmethod
    def parse_ligand_files(ligands: pyrosetta.rosetta.utility.vector1_protocols_sewing_data_storage_LigandDescription) -> None: ...
    @overload
    @staticmethod
    def parse_ligand_files(classutility) -> void: ...
    @overload
    def revert_last_added_contact(self, assembly: pyrosetta.rosetta.protocols.sewing.data_storage.SmartAssembly) -> None: ...
    @overload
    def revert_last_added_contact(self, classstd) -> void: ...
    @overload
    def set_best_geometry_score(self) -> None: ...
    @overload
    def set_best_geometry_score(self, double) -> void: ...
    @overload
    def set_geometry_score_weight(self) -> None: ...
    @overload
    def set_geometry_score_weight(self, double) -> void: ...
    @overload
    def set_ligand(self, lig) -> None: ...
    @overload
    def set_ligand(self, classstd) -> void: ...

class LigandCoordInfo:
    chis: pyrosetta.rosetta.utility.fixedsizearray1_double_4UL_t
    coord_atom_index: int
    coord_res_name: str
    ligand_atom_index: int
    local_coords: pyrosetta.rosetta.numeric.xyzVector_double_t
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LigandCoordInfo) -> None: ...
    def assign(self) -> LigandCoordInfo: ...

class ModelFileReader:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ModelFileReader) -> None: ...
    def assign(self) -> ModelFileReader: ...
    def clone(self) -> ModelFileReader: ...
    @staticmethod
    def read_model_file(filename: str) -> SegmentVector: ...

class SegmentVector(pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_sewing_data_storage_SmartSegment_t):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SegmentVector) -> None: ...
    def assign(self) -> SegmentVector: ...
    @overload
    def get_version(self) -> int: ...
    @overload
    def get_version(self) -> unsignedlong: ...
    @overload
    def set_version(self, ver: int) -> None: ...
    @overload
    def set_version(self, unsignedlong) -> void: ...

class coord_equal_to:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: coord_equal_to) -> None: ...
    def assign(self) -> coord_equal_to: ...
    def __call__(self, key1: pyrosetta.rosetta.utility.fixedsizearray1_int_3UL_t, key2: pyrosetta.rosetta.utility.fixedsizearray1_int_3UL_t) -> bool: ...

class coord_hash:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: coord_hash) -> None: ...
    def assign(self) -> coord_hash: ...
    def __call__(self, key: pyrosetta.rosetta.utility.fixedsizearray1_int_3UL_t) -> int: ...
