import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.utility
from . import evaluator as evaluator
from typing import overload

class Loop:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, takeoff_pos: int, landing_pos: int, takeoff_domain: int, landing_domain: int) -> None: ...
    @overload
    def __init__(self, arg0: Loop) -> None: ...
    def assign(self, src: Loop) -> Loop: ...
    @overload
    def landing_domain(self) -> int: ...
    @overload
    def landing_domain(self) -> unsignedlong: ...
    @overload
    def landing_pos(self) -> int: ...
    @overload
    def landing_pos(self) -> unsignedlong: ...
    def set_landing_domain(self, setting: int) -> None: ...
    def set_landing_pos(self, setting: int) -> None: ...
    def set_takeoff_domain(self, setting: int) -> None: ...
    def set_takeoff_pos(self, setting: int) -> None: ...
    @overload
    def takeoff_domain(self) -> int: ...
    @overload
    def takeoff_domain(self) -> unsignedlong: ...
    @overload
    def takeoff_pos(self) -> int: ...
    @overload
    def takeoff_pos(self) -> unsignedlong: ...

class LoopCycle:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, loops: pyrosetta.rosetta.utility.vector1_core_scoring_loop_graph_Loop) -> None: ...
    @overload
    def __init__(self, arg0: LoopCycle) -> None: ...
    def assign(self) -> LoopCycle: ...
    def find_index_for_loop_landing_at_domain(self, takeoff_domain: int) -> int: ...
    def loop(self, n: int) -> Loop: ...
    def loops(self) -> pyrosetta.rosetta.utility.vector1_core_scoring_loop_graph_Loop: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...

class LoopGraph:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LoopGraph) -> None: ...
    def assign(self) -> LoopGraph: ...
    @overload
    def check_loop_cycles_are_disjoint(self) -> None: ...
    @overload
    def check_loop_cycles_are_disjoint(self, verbose: bool) -> None: ...
    @overload
    def check_loop_cycles_are_disjoint(self, constbool) -> void: ...
    @overload
    def has_just_simple_cycles(self) -> bool: ...
    @overload
    def has_just_simple_cycles(self) -> bool: ...
    def loop_cycles(self) -> pyrosetta.rosetta.utility.vector1_core_scoring_loop_graph_LoopCycle: ...
    def loop_score_evaluator(self, *args, **kwargs): ...
    @overload
    def loop_suites(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t: ...
    @overload
    def loop_suites(self, include_free_loops: bool) -> pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t: ...
    def missing_residues(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_char: ...
    @overload
    def nmissing(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def nmissing(self, constclasscore) -> unsignedlong: ...
    @overload
    def num_current_pose_loops(self) -> int: ...
    @overload
    def num_current_pose_loops(self) -> unsignedlong: ...
    def set_error_out_on_complex_cycles(self, setting: bool) -> None: ...
    def set_use_6D_potential(self, setting: bool) -> None: ...
    @overload
    def total_energy(self) -> float: ...
    @overload
    def total_energy(self) -> double: ...
    @overload
    def update(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def update(self, pose: pyrosetta.rosetta.core.pose.Pose, verbose: bool) -> None: ...
    @overload
    def update(self, classcore, constbool) -> void: ...
    @overload
    def update_loops(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def update_loops(self, constclasscore) -> void: ...
    def update_loops_and_cycles(self, pose_domain_map: pyrosetta.rosetta.utility.vector1_unsigned_long, cutpoint_open: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...

def get_6D_trans_rot_potential_evaluator(loop_cycle: LoopCycle, loop_fixed_cost: float, pose: pyrosetta.rosetta.core.pose.Pose) -> evaluator.LoopClosePotentialEvaluator: ...
@overload
def get_loop_atom(res: int, pose: pyrosetta.rosetta.core.pose.Pose, atom_id: pyrosetta.rosetta.core.id.AtomID, xyz: pyrosetta.rosetta.numeric.xyzVector_double_t, takeoff: bool) -> None: ...
@overload
def get_loop_atom(constunsignedlong, constclasscore, classcore, classnumeric, constbool) -> void: ...
@overload
def get_loop_atom(res: int, pose: pyrosetta.rosetta.core.pose.Pose, atom_name: str, atom_id: pyrosetta.rosetta.core.id.AtomID, xyz: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
@overload
def get_loop_atom(constunsignedlong, constclasscore, conststd, classcore, classnumeric) -> void: ...
def get_loop_close_potential(pose: pyrosetta.rosetta.core.pose.Pose, loop_cycle: LoopCycle, loop_fixed_cost: float, use_6D_potential: bool) -> evaluator.LoopClosePotentialEvaluator: ...
