import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring.loop_graph
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import overload

class GaussianChainFuncPotentialEvaluator(LoopClosePotentialEvaluator):
    @overload
    def __init__(self, loop_cycle: pyrosetta.rosetta.core.scoring.loop_graph.LoopCycle, loop_fixed_cost: float, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: GaussianChainFuncPotentialEvaluator) -> None: ...
    @overload
    def __init__(self, arg0: GaussianChainFuncPotentialEvaluator) -> None: ...
    def get_f1_f2(self, f1: pyrosetta.rosetta.numeric.xyzVector_double_t, f2: pyrosetta.rosetta.numeric.xyzVector_double_t, takeoff: bool) -> None: ...

class LoopClosePotentialEvaluator:
    @overload
    def __init__(self, loop_fixed_cost: float) -> None: ...
    @overload
    def __init__(self, arg0: LoopClosePotentialEvaluator) -> None: ...
    def current_pose_landing_atom(self) -> pyrosetta.rosetta.core.id.AtomID: ...
    def current_pose_landing_xyz(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def current_pose_takeoff_atom(self) -> pyrosetta.rosetta.core.id.AtomID: ...
    def current_pose_takeoff_xyz(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def get_f1_f2(self, f1: pyrosetta.rosetta.numeric.xyzVector_double_t, f2: pyrosetta.rosetta.numeric.xyzVector_double_t, takeoff: bool) -> None: ...
    @overload
    def involves_current_pose(self) -> bool: ...
    @overload
    def involves_current_pose(self) -> bool: ...
    @overload
    def loop_closure_energy(self) -> float: ...
    @overload
    def loop_closure_energy(self) -> double: ...
    def loop_fixed_cost(self) -> float: ...
    @overload
    def set_current_pose_landing_atom(self, setting: pyrosetta.rosetta.core.id.AtomID) -> None: ...
    @overload
    def set_current_pose_landing_atom(self, constclasscore) -> void: ...
    @overload
    def set_current_pose_landing_xyz(self, setting: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_current_pose_landing_xyz(self, constclassnumeric) -> void: ...
    @overload
    def set_current_pose_takeoff_atom(self, setting: pyrosetta.rosetta.core.id.AtomID) -> None: ...
    @overload
    def set_current_pose_takeoff_atom(self, constclasscore) -> void: ...
    @overload
    def set_current_pose_takeoff_xyz(self, setting: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_current_pose_takeoff_xyz(self, constclassnumeric) -> void: ...
    def set_involves_current_pose(self, setting: bool) -> None: ...
    def set_loop_closure_energy(self, setting: float) -> None: ...

class SixDTransRotPotential:
    @overload
    def __init__(self, filename: str) -> None: ...
    @overload
    def __init__(self, tensor: pyrosetta.rosetta.numeric.MathNTensor_double_6UL_t, json: pyrosetta.rosetta.std.map_std_string_utility_json_spirit_Value_impl_utility_json_spirit_Config_map_std_string_t_std_allocator_std_pair_const_std_string_utility_json_spirit_Value_impl_utility_json_spirit_Config_map_std_string_t) -> None: ...
    @overload
    def __init__(self, arg0: SixDTransRotPotential) -> None: ...
    @overload
    def enforce_continuity_at_pi(self) -> bool: ...
    @overload
    def enforce_continuity_at_pi(self) -> bool: ...
    @overload
    def evaluate(self, j: pyrosetta.rosetta.core.kinematics.Jump) -> float: ...
    @overload
    def evaluate(self, constclasscore) -> double: ...
    def get_derivative(self, j: pyrosetta.rosetta.core.kinematics.Jump) -> tuple[pyrosetta.rosetta.numeric.xyzVector_double_t, pyrosetta.rosetta.numeric.xyzVector_double_t]: ...
    def set_enforce_continuity_at_pi(self, setting: bool) -> None: ...

class SixDTransRotPotentialEvaluator(LoopClosePotentialEvaluator):
    @overload
    def __init__(self, takeoff_pos: int, landing_pos: int, pose: pyrosetta.rosetta.core.pose.Pose, loop_fixed_cost: float, potential: SixDTransRotPotential) -> None: ...
    @overload
    def __init__(self, arg0: SixDTransRotPotentialEvaluator) -> None: ...
    @overload
    def __init__(self, arg0: SixDTransRotPotentialEvaluator) -> None: ...

def get_minval_binwidth(T: pyrosetta.rosetta.numeric.MathNTensor_double_6UL_t, json: pyrosetta.rosetta.std.map_std_string_utility_json_spirit_Value_impl_utility_json_spirit_Config_map_std_string_t_std_allocator_std_pair_const_std_string_utility_json_spirit_Value_impl_utility_json_spirit_Config_map_std_string_t, minval: pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t, binwidth: pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t) -> None: ...
