import pyrosetta.rosetta.ObjexxFCL
import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.pose.rna
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.scoring.methods
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.io
import pyrosetta.rosetta.utility.options
from . import methods as methods
from typing import Any, overload

class ImplicitFastClashCheck:
    @overload
    def __init__(self, pose_in: pyrosetta.rosetta.core.pose.Pose, clash_dis: float) -> None: ...
    @overload
    def __init__(self, pose_in: pyrosetta.rosetta.core.pose.Pose, clash_dis: float, ignore: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, poses_in: pyrosetta.rosetta.utility.vector1_core_pose_Pose, clash_dis: float, ignore: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, arg0: ImplicitFastClashCheck) -> None: ...
    def assign(self) -> ImplicitFastClashCheck: ...
    @overload
    def clash_check(self, pp: pyrosetta.rosetta.numeric.xyzVector_double_t) -> bool: ...
    @overload
    def clash_check(self, constclassnumeric) -> bool: ...
    @overload
    def clash_check(self, pp: pyrosetta.rosetta.numeric.xyzVector_double_t, resno: int) -> bool: ...
    @overload
    def clash_check(self, constclassnumeric, unsignedlong) -> bool: ...
    @overload
    def clash_check_test(self, pp: pyrosetta.rosetta.numeric.xyzVector_double_t) -> bool: ...
    @overload
    def clash_check_test(self, constclassnumeric) -> bool: ...
    @overload
    def clash_check_trimer(self, pose: pyrosetta.rosetta.core.pose.Pose, refrsd: int) -> bool: ...
    @overload
    def clash_check_trimer(self, constclasscore, unsignedlong) -> bool: ...
    @overload
    def clash_count(self, pp: pyrosetta.rosetta.numeric.xyzVector_double_t) -> int: ...
    @overload
    def clash_count(self, constclassnumeric) -> unsignedlong: ...
    @overload
    def dump_debug_pdb(self, out: pyrosetta.rosetta.utility.io.ozstream, stub: pyrosetta.rosetta.core.kinematics.Stub) -> None: ...
    @overload
    def dump_debug_pdb(self, out: pyrosetta.rosetta.utility.io.ozstream, stub: pyrosetta.rosetta.core.kinematics.Stub, chain: str) -> None: ...
    @overload
    def dump_debug_pdb(self, classutility, constclasscore, char) -> void: ...
    @overload
    def dump_debug_pdb(self, fname: str, stub: pyrosetta.rosetta.core.kinematics.Stub) -> None: ...
    @overload
    def dump_debug_pdb(self, fname: str, stub: pyrosetta.rosetta.core.kinematics.Stub, chain: str) -> None: ...
    @overload
    def dump_debug_pdb(self, conststd, constclasscore, char) -> void: ...
    @overload
    def init_clash_check(self, poses: pyrosetta.rosetta.utility.vector1_core_pose_Pose, neighbor_cutoff: float, ignore: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def init_clash_check(self, constclassutility, double, classutility) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...

class InterchainPotential(pyrosetta.rosetta.utility.SingletonBase_protocols_scoring_InterchainPotential_t):
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def compute_interface(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def compute_interface(self, classcore) -> void: ...
    def evaluate_contact_score(self, pose: pyrosetta.rosetta.core.pose.Pose, contact_score: float) -> None: ...
    def evaluate_env_score(self, pose: pyrosetta.rosetta.core.pose.Pose, rsd: pyrosetta.rosetta.core.conformation.Residue, env_score: float) -> None: ...
    def evaluate_pair_and_vdw_score(self, pose: pyrosetta.rosetta.core.pose.Pose, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, pair_score: float, vdw_score: float) -> None: ...
    @overload
    def finalize(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def finalize(self, classcore) -> void: ...
    def interface_from_pose(self, *args, **kwargs): ...
    def nonconst_interface_from_pose(self, *args, **kwargs): ...

class Interface:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, jump_number_in: int) -> None: ...
    @overload
    def __init__(self, partner: pyrosetta.rosetta.ObjexxFCL.FArray1D_bool_t) -> None: ...
    @overload
    def __init__(self, arg0: Interface) -> None: ...
    def assign(self) -> Interface: ...
    @overload
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def calculate(self, constclasscore) -> void: ...
    def center(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def closest_interface_residue(self, pose: pyrosetta.rosetta.core.pose.Pose, src_rsd: int, distance: float) -> int: ...
    def contact_list(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t: ...
    @overload
    def distance(self, distance_in: float) -> None: ...
    @overload
    def distance(self, constdouble) -> void: ...
    @overload
    def interface_nres(self) -> int: ...
    @overload
    def interface_nres(self) -> unsignedlong: ...
    @overload
    def is_interface(self, rsd: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    @overload
    def is_interface(self, constclasscore) -> bool: ...
    @overload
    def is_interface(self, position: int) -> bool: ...
    @overload
    def is_interface(self, constunsignedlong) -> bool: ...
    def is_pair(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    @overload
    def jump(self, jump_number: int) -> None: ...
    @overload
    def jump(self, constunsignedlong) -> void: ...
    @overload
    def jump_id(self) -> int: ...
    @overload
    def jump_id(self) -> unsignedlong: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def pair_list(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_int_t: ...
    @overload
    def pair_list(self) -> Any: ...
    @overload
    def print(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def print(self, constclasscore) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_pack(self, pose: pyrosetta.rosetta.core.pose.Pose, task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def set_pack(self, constclasscore, classstd) -> void: ...
    @overload
    def set_symmetric_pack(self, pose: pyrosetta.rosetta.core.pose.Pose, task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def set_symmetric_pack(self, constclasscore, classstd) -> void: ...
    @overload
    def show(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def show(self, constclasscore) -> void: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def show(self, std, constclasscore) -> void: ...

class InterfaceInfo(pyrosetta.rosetta.basic.datacache.CacheableData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rb_jump_in: int) -> None: ...
    @overload
    def __init__(self, rb_jump_in: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, arg0: InterfaceInfo) -> None: ...
    @overload
    def __init__(self, arg0: InterfaceInfo) -> None: ...
    @overload
    def add_jump(self, jump_in: int) -> None: ...
    @overload
    def add_jump(self, unsignedlong) -> void: ...
    def assign(self) -> InterfaceInfo: ...
    @overload
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def calculate(self, constclasscore) -> void: ...
    def calculated(self) -> bool: ...
    @overload
    def clear_jumps(self) -> None: ...
    @overload
    def clear_jumps(self) -> void: ...
    def clone(self) -> pyrosetta.rosetta.basic.datacache.CacheableData: ...
    def closest_interface_residue(self, pose: pyrosetta.rosetta.core.pose.Pose, src_rsd: int, distance: float) -> int: ...
    @overload
    def distance(self, distance_in: float) -> None: ...
    @overload
    def distance(self, double) -> void: ...
    @overload
    def distance(self) -> float: ...
    @overload
    def distance(self) -> double: ...
    @overload
    def initialize(self) -> None: ...
    @overload
    def initialize(self) -> void: ...
    def interface(self, interface_num: int) -> Interface: ...
    @overload
    def interface_nres(self, jump_num: int) -> int: ...
    @overload
    def interface_nres(self, unsignedlong) -> unsignedlong: ...
    @overload
    def is_interface(self, rsd: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    @overload
    def is_interface(self, classcore) -> bool: ...
    def is_pair(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def num_jump(self) -> int: ...
    @overload
    def num_jump(self) -> unsignedlong: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class ResidualDipolarCouplingRigidSegments(pyrosetta.rosetta.basic.datacache.CacheableData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ResidualDipolarCouplingRigidSegments) -> None: ...
    @overload
    def __init__(self, arg0: ResidualDipolarCouplingRigidSegments) -> None: ...
    def assign(self) -> ResidualDipolarCouplingRigidSegments: ...
    def clone(self) -> pyrosetta.rosetta.basic.datacache.CacheableData: ...
    @overload
    def compute_pairwise_score(self) -> float: ...
    @overload
    def compute_pairwise_score(self) -> double: ...
    @overload
    def compute_total_score(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def compute_total_score(self, constclasscore) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, std) -> void: ...

class VDW_CachedRepScreenInfo(pyrosetta.rosetta.basic.datacache.CacheableData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: VDW_CachedRepScreenInfo) -> None: ...
    @overload
    def __init__(self, arg0: VDW_CachedRepScreenInfo) -> None: ...
    def VDW_rep_screen_info_list(self) -> pyrosetta.rosetta.utility.vector1_core_pose_rna_VDW_RepScreenInfo: ...
    def VDW_screen_bin(self) -> pyrosetta.rosetta.core.pose.rna.VDW_Grid: ...
    def assign(self) -> VDW_CachedRepScreenInfo: ...
    def clone(self) -> pyrosetta.rosetta.basic.datacache.CacheableData: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def read_in_VDW_rep_screen_pose(self, VDW_rep_screen_info: pyrosetta.rosetta.core.pose.rna.VDW_RepScreenInfo) -> None: ...
    @overload
    def read_in_VDW_rep_screen_pose(self, classcore) -> void: ...
    @overload
    def read_in_VDW_rep_screen_pose_from_command_line(self) -> None: ...
    @overload
    def read_in_VDW_rep_screen_pose_from_command_line(self) -> void: ...
    @overload
    def read_in_VDW_rep_screen_pose_from_options(self, options: pyrosetta.rosetta.utility.options.OptionCollection) -> None: ...
    @overload
    def read_in_VDW_rep_screen_pose_from_options(self, constclassutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class VDW_GridEnergy(pyrosetta.rosetta.core.scoring.methods.WholeStructureEnergy):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: VDW_GridEnergy) -> None: ...
    @overload
    def __init__(self, arg0: VDW_GridEnergy) -> None: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    def finalize_total_energy(self, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def indicate_required_context_graphs(self) -> None: ...
    @overload
    def indicate_required_context_graphs(self, classutility) -> void: ...
    @overload
    def setup_for_scoring(self) -> None: ...
    @overload
    def setup_for_scoring(self, classcore, constclasscore) -> void: ...
    @overload
    def version(self) -> int: ...
    @overload
    def version(self) -> unsignedlong: ...

class VDW_GridEnergyCreator(pyrosetta.rosetta.core.scoring.methods.EnergyMethodCreator):
    def __init__(self) -> None: ...
    def assign(self) -> VDW_GridEnergyCreator: ...
    def create_energy_method(self) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    def score_types_for_method(self) -> pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType: ...

def const_vdw_cached_rep_screen_info_from_pose(pose: pyrosetta.rosetta.core.pose.Pose) -> VDW_CachedRepScreenInfo: ...
@overload
def fill_vdw_cached_rep_screen_info_from_command_line(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def fill_vdw_cached_rep_screen_info_from_command_line(classcore) -> void: ...
@overload
def fill_vdw_cached_rep_screen_info_from_options(pose: pyrosetta.rosetta.core.pose.Pose, options: pyrosetta.rosetta.utility.options.OptionCollection) -> None: ...
@overload
def fill_vdw_cached_rep_screen_info_from_options(classcore, constclassutility) -> void: ...
def make_sure_vdw_cached_rep_screen_info_is_setup(pose: pyrosetta.rosetta.core.pose.Pose) -> VDW_CachedRepScreenInfo: ...
def nonconst_vdw_cached_rep_screen_info_from_pose(pose: pyrosetta.rosetta.core.pose.Pose) -> VDW_CachedRepScreenInfo: ...
@overload
def option_vdw_rep_screen_info_user(options: pyrosetta.rosetta.utility.options.OptionCollection) -> bool: ...
@overload
def option_vdw_rep_screen_info_user(constclassutility) -> bool: ...
def retrieve_RDC_segments_from_pose(*args, **kwargs): ...
@overload
def set_vdw_cached_rep_screen_info(pose: pyrosetta.rosetta.core.pose.Pose, vdw_cached_rep_screen_info: VDW_CachedRepScreenInfo) -> None: ...
@overload
def set_vdw_cached_rep_screen_info(classcore, classstd) -> void: ...
@overload
def set_vdw_cached_rep_screen_info_from_pose(new_pose: pyrosetta.rosetta.core.pose.Pose, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def set_vdw_cached_rep_screen_info_from_pose(classcore, constclasscore) -> void: ...
@overload
def store_RDC_segments_in_pose() -> None: ...
@overload
def store_RDC_segments_in_pose(classstd, classcore) -> void: ...
@overload
def vdw_cached_rep_screen_info_is_setup(pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
@overload
def vdw_cached_rep_screen_info_is_setup(constclasscore) -> bool: ...
