import pyrosetta.rosetta.core.fragment
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.loops
import pyrosetta.rosetta.protocols.moves
from typing import overload

class Anchor:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, start: int, end: int) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, filename: str) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: Anchor) -> None: ...
    def assign(self, rhs: Anchor) -> Anchor: ...
    @overload
    def end(self) -> int: ...
    @overload
    def end(self) -> unsignedlong: ...
    def get_filename(self) -> str: ...
    @overload
    def read_anchorfile(self, pose: pyrosetta.rosetta.core.pose.Pose, filename: str) -> None: ...
    @overload
    def read_anchorfile(self, constclasscore, conststd) -> void: ...
    @overload
    def read_anchorfile(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def read_anchorfile(self, constclasscore) -> void: ...
    @overload
    def read_options(self) -> None: ...
    @overload
    def read_options(self) -> void: ...
    @overload
    def set_filename(self, filename: str) -> None: ...
    @overload
    def set_filename(self, conststd) -> void: ...
    @overload
    def start(self) -> int: ...
    @overload
    def start(self) -> unsignedlong: ...

class AnchorMoversData:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, anchor: Anchor, loops: pyrosetta.rosetta.protocols.loops.Loops) -> None: ...
    @overload
    def __init__(self, anchor: Anchor, loops: pyrosetta.rosetta.protocols.loops.Loops, options: bool) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: AnchorMoversData) -> None: ...
    @overload
    def anchor_end(self) -> int: ...
    @overload
    def anchor_end(self) -> unsignedlong: ...
    @overload
    def anchor_noise_constraints_setup(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def anchor_noise_constraints_setup(self, classcore) -> void: ...
    @overload
    def anchor_start(self) -> int: ...
    @overload
    def anchor_start(self) -> unsignedlong: ...
    def anchored_loop(self) -> pyrosetta.rosetta.protocols.loops.Loop: ...
    def assign(self, rhs: AnchorMoversData) -> AnchorMoversData: ...
    def autogenerate_constseq_frags(self, seq: str) -> pyrosetta.rosetta.core.fragment.FragSet: ...
    def autogenerate_design_frags(self) -> pyrosetta.rosetta.core.fragment.FragSet: ...
    @overload
    def autogenerate_frags(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def autogenerate_frags(self, constclasscore) -> void: ...
    def clone(self) -> AnchorMoversData: ...
    @overload
    def get_VDW_weight(self) -> float: ...
    @overload
    def get_VDW_weight(self) -> double: ...
    @overload
    def get_akash_dyepos(self) -> int: ...
    @overload
    def get_akash_dyepos(self) -> unsignedlong: ...
    @overload
    def get_allow_anchor_repack(self) -> bool: ...
    @overload
    def get_allow_anchor_repack(self) -> bool: ...
    @overload
    def get_anchor_noise_constraints_mode(self) -> bool: ...
    @overload
    def get_anchor_noise_constraints_mode(self) -> bool: ...
    @overload
    def get_anchor_via_constraints(self) -> bool: ...
    @overload
    def get_anchor_via_constraints(self) -> bool: ...
    def get_centroid_scorefunction(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    def get_centroid_scorefunction_min(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def get_chainbreak_weight(self) -> float: ...
    @overload
    def get_chainbreak_weight(self) -> double: ...
    def get_frag3(self) -> str: ...
    def get_frags(self) -> pyrosetta.rosetta.core.fragment.FragSet: ...
    def get_fullatom_scorefunction(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    def get_late_factory(self) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    def get_loop_file(self) -> str: ...
    @overload
    def get_no_frags(self) -> bool: ...
    @overload
    def get_no_frags(self) -> bool: ...
    def get_resfile_1(self) -> str: ...
    def get_resfile_2(self) -> str: ...
    @overload
    def get_super_secret_fixed_interface_mode(self) -> bool: ...
    @overload
    def get_super_secret_fixed_interface_mode(self) -> bool: ...
    def get_task(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.pack.task.PackerTask: ...
    def get_task_factory(self) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    @overload
    def get_unbound_mode(self) -> bool: ...
    @overload
    def get_unbound_mode(self) -> bool: ...
    def interface_calc(self) -> str: ...
    def loop(self, i: int) -> pyrosetta.rosetta.protocols.loops.Loop: ...
    def loops(self) -> pyrosetta.rosetta.protocols.loops.Loops: ...
    def movemap_cen(self, i: int) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    def movemap_cen_all(self) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    def movemap_cen_omegafixed(self, i: int) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    def movemap_fa(self, i: int) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    def movemap_fa_all(self) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    def movemap_fa_omegafixed(self, i: int) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    def neighborhood_calc(self) -> str: ...
    @overload
    def num_loops(self) -> int: ...
    @overload
    def num_loops(self) -> unsignedlong: ...
    @overload
    def pick_new_cutpoints(self, reset_always: bool) -> None: ...
    @overload
    def pick_new_cutpoints(self, bool) -> void: ...
    @overload
    def read_options(self) -> None: ...
    @overload
    def read_options(self) -> void: ...
    @overload
    def set_VDW_weight(self, VDW_weight: float) -> None: ...
    @overload
    def set_VDW_weight(self, double) -> void: ...
    @overload
    def set_akash_dyepos(self, akash_dyepos: int) -> None: ...
    @overload
    def set_akash_dyepos(self, constunsignedlong) -> void: ...
    @overload
    def set_allow_anchor_repack(self, allow_anchor_repack: bool) -> None: ...
    @overload
    def set_allow_anchor_repack(self, bool) -> void: ...
    @overload
    def set_anchor_noise_constraints_mode(self, anchor_noise_constraints_mode: bool) -> None: ...
    @overload
    def set_anchor_noise_constraints_mode(self, bool) -> void: ...
    @overload
    def set_anchor_via_constraints(self, anchor_via_constraints: bool) -> None: ...
    @overload
    def set_anchor_via_constraints(self, bool) -> void: ...
    @overload
    def set_centroid_scorefunction(self) -> None: ...
    @overload
    def set_centroid_scorefunction(self, classstd) -> void: ...
    @overload
    def set_chainbreak_weight(self, chainbreak_weight: float) -> None: ...
    @overload
    def set_chainbreak_weight(self, double) -> void: ...
    @overload
    def set_frag3(self, frag3: str) -> None: ...
    @overload
    def set_frag3(self, conststd) -> void: ...
    @overload
    def set_frags(self) -> None: ...
    @overload
    def set_frags(self, classstd) -> void: ...
    @overload
    def set_fullatom_scorefunction(self) -> None: ...
    @overload
    def set_fullatom_scorefunction(self, classstd) -> void: ...
    @overload
    def set_loops_and_anchor(self, anchor: Anchor, loops: pyrosetta.rosetta.protocols.loops.Loops) -> None: ...
    @overload
    def set_loops_and_anchor(self, classstd, classprotocols) -> void: ...
    @overload
    def set_no_frags(self, no_frags: bool) -> None: ...
    @overload
    def set_no_frags(self, bool) -> void: ...
    @overload
    def set_resfile_1(self, resfile_1: str) -> None: ...
    @overload
    def set_resfile_1(self, conststd) -> void: ...
    @overload
    def set_resfile_2(self, resfile_2: str) -> None: ...
    @overload
    def set_resfile_2(self, conststd) -> void: ...
    @overload
    def set_super_secret_fixed_interface_mode(self, super_secret_fixed_interface_mode: bool) -> None: ...
    @overload
    def set_super_secret_fixed_interface_mode(self, bool) -> void: ...
    @overload
    def set_task_factory(self) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...
    @overload
    def set_unbound_mode(self, unbound_mode: bool) -> None: ...
    @overload
    def set_unbound_mode(self, bool) -> void: ...

class AnchoredDesignMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, interface_in) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AnchoredDesignMover) -> None: ...
    @overload
    def __init__(self, arg0: AnchoredDesignMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self, rhs: AnchoredDesignMover) -> AnchoredDesignMover: ...
    @overload
    def calculate_rmsd(self, pose: pyrosetta.rosetta.core.pose.Pose, start_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def calculate_rmsd(self, constclasscore, classstd) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def delete_interface_native_sidechains(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def delete_interface_native_sidechains(self, classcore) -> void: ...
    @overload
    def filter(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def filter(self, classcore) -> void: ...
    @overload
    def forget_initial_loops(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def forget_initial_loops(self, classcore) -> void: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_RMSD_only_this(self) -> str: ...
    @overload
    def get_autoinitialize(self) -> bool: ...
    @overload
    def get_autoinitialize(self) -> bool: ...
    @overload
    def get_delete_interface_native_sidechains(self) -> bool: ...
    @overload
    def get_delete_interface_native_sidechains(self) -> bool: ...
    @overload
    def get_filter_SASA(self) -> float: ...
    @overload
    def get_filter_SASA(self) -> double: ...
    @overload
    def get_filter_omega(self) -> bool: ...
    @overload
    def get_filter_omega(self) -> bool: ...
    @overload
    def get_filter_score(self) -> float: ...
    @overload
    def get_filter_score(self) -> double: ...
    def get_name(self) -> str: ...
    @overload
    def get_randomize_input_sequence(self) -> bool: ...
    @overload
    def get_randomize_input_sequence(self) -> bool: ...
    @overload
    def get_refine_only(self) -> bool: ...
    @overload
    def get_refine_only(self) -> bool: ...
    @overload
    def get_rmsd(self) -> bool: ...
    @overload
    def get_rmsd(self) -> bool: ...
    @overload
    def get_show_extended(self) -> bool: ...
    @overload
    def get_show_extended(self) -> bool: ...
    @overload
    def get_vary_cutpoints(self) -> bool: ...
    @overload
    def get_vary_cutpoints(self) -> bool: ...
    @overload
    def perturb_anchor(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def perturb_anchor(self, classcore) -> void: ...
    @overload
    def randomize_input_sequence(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def randomize_input_sequence(self, classcore) -> void: ...
    @overload
    def read_options(self) -> None: ...
    @overload
    def read_options(self) -> void: ...
    @overload
    def reinitialize_for_each_job(self) -> bool: ...
    @overload
    def reinitialize_for_each_job(self) -> bool: ...
    @overload
    def reinitialize_for_new_input(self) -> bool: ...
    @overload
    def reinitialize_for_new_input(self) -> bool: ...
    @overload
    def set_RMSD_only_this(self, RMSD_only_this: str) -> None: ...
    @overload
    def set_RMSD_only_this(self, conststd) -> void: ...
    @overload
    def set_autoinitialize(self, autoinitialize: bool) -> None: ...
    @overload
    def set_autoinitialize(self, constbool) -> void: ...
    @overload
    def set_delete_interface_native_sidechains(self, delete_interface_native_sidechains: bool) -> None: ...
    @overload
    def set_delete_interface_native_sidechains(self, constbool) -> void: ...
    @overload
    def set_filter_SASA(self, filter_SASA: float) -> None: ...
    @overload
    def set_filter_SASA(self, constdouble) -> void: ...
    @overload
    def set_filter_omega(self, filter_omega: bool) -> None: ...
    @overload
    def set_filter_omega(self, constbool) -> void: ...
    @overload
    def set_filter_score(self, filter_score: float) -> None: ...
    @overload
    def set_filter_score(self, constdouble) -> void: ...
    @overload
    def set_fold_tree_and_cutpoints(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_fold_tree_and_cutpoints(self, classcore) -> void: ...
    @overload
    def set_randomize_input_sequence(self, randomize_input_sequence: bool) -> None: ...
    @overload
    def set_randomize_input_sequence(self, constbool) -> void: ...
    @overload
    def set_refine_only(self, refine_only: bool) -> None: ...
    @overload
    def set_refine_only(self, constbool) -> void: ...
    @overload
    def set_rmsd(self, rmsd: bool) -> None: ...
    @overload
    def set_rmsd(self, constbool) -> void: ...
    @overload
    def set_show_extended(self, show_extended: bool) -> None: ...
    @overload
    def set_show_extended(self, constbool) -> void: ...
    @overload
    def set_vary_cutpoints(self, vary_cutpoints: bool) -> None: ...
    @overload
    def set_vary_cutpoints(self, constbool) -> void: ...

class AnchoredPerturbMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, interface_in) -> None: ...
    @overload
    def __init__(self, arg0: AnchoredPerturbMover) -> None: ...
    @overload
    def __init__(self, arg0: AnchoredPerturbMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> AnchoredPerturbMover: ...
    @overload
    def get_debug(self) -> bool: ...
    @overload
    def get_debug(self) -> bool: ...
    def get_min_type(self) -> str: ...
    def get_name(self) -> str: ...
    @overload
    def get_no_frags(self) -> bool: ...
    @overload
    def get_no_frags(self) -> bool: ...
    @overload
    def get_nonpivot_torsion_sampling(self) -> bool: ...
    @overload
    def get_nonpivot_torsion_sampling(self) -> bool: ...
    @overload
    def get_perturb_CCD_off(self) -> bool: ...
    @overload
    def get_perturb_CCD_off(self) -> bool: ...
    @overload
    def get_perturb_KIC_off(self) -> bool: ...
    @overload
    def get_perturb_KIC_off(self) -> bool: ...
    @overload
    def get_perturb_cycles(self) -> int: ...
    @overload
    def get_perturb_cycles(self) -> unsignedlong: ...
    @overload
    def get_perturb_show(self) -> bool: ...
    @overload
    def get_perturb_show(self) -> bool: ...
    @overload
    def get_perturb_temp(self) -> float: ...
    @overload
    def get_perturb_temp(self) -> double: ...
    @overload
    def read_options(self) -> None: ...
    @overload
    def read_options(self) -> void: ...
    @overload
    def set_debug(self, debug: bool) -> None: ...
    @overload
    def set_debug(self, constbool) -> void: ...
    @overload
    def set_min_type(self, min_type: str) -> None: ...
    @overload
    def set_min_type(self, conststd) -> void: ...
    @overload
    def set_no_frags(self, no_frags: bool) -> None: ...
    @overload
    def set_no_frags(self, constbool) -> void: ...
    @overload
    def set_nonpivot_torsion_sampling(self, nonpivot_torsion_sampling: bool) -> None: ...
    @overload
    def set_nonpivot_torsion_sampling(self, constbool) -> void: ...
    @overload
    def set_perturb_CCD_off(self, perturb_CCD_off: bool) -> None: ...
    @overload
    def set_perturb_CCD_off(self, constbool) -> void: ...
    @overload
    def set_perturb_KIC_off(self, perturb_KIC_off: bool) -> None: ...
    @overload
    def set_perturb_KIC_off(self, constbool) -> void: ...
    @overload
    def set_perturb_cycles(self, perturb_cycles: int) -> None: ...
    @overload
    def set_perturb_cycles(self, constunsignedlong) -> void: ...
    @overload
    def set_perturb_show(self, perturb_show: bool) -> None: ...
    @overload
    def set_perturb_show(self, constbool) -> void: ...
    @overload
    def set_perturb_temp(self, perturb_temp: float) -> None: ...
    @overload
    def set_perturb_temp(self, constdouble) -> void: ...

class AnchoredRefineMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, interface_in) -> None: ...
    @overload
    def __init__(self, arg0: AnchoredRefineMover) -> None: ...
    @overload
    def __init__(self, arg0: AnchoredRefineMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> AnchoredRefineMover: ...
    @overload
    def get_debug(self) -> bool: ...
    @overload
    def get_debug(self) -> bool: ...
    def get_min_type(self) -> str: ...
    def get_name(self) -> str: ...
    @overload
    def get_nonpivot_torsion_sampling(self) -> bool: ...
    @overload
    def get_nonpivot_torsion_sampling(self) -> bool: ...
    @overload
    def get_refine_CCD_off(self) -> bool: ...
    @overload
    def get_refine_CCD_off(self) -> bool: ...
    @overload
    def get_refine_KIC_off(self) -> bool: ...
    @overload
    def get_refine_KIC_off(self) -> bool: ...
    @overload
    def get_refine_cycles(self) -> int: ...
    @overload
    def get_refine_cycles(self) -> unsignedlong: ...
    @overload
    def get_refine_repack_cycles(self) -> int: ...
    @overload
    def get_refine_repack_cycles(self) -> unsignedlong: ...
    @overload
    def get_refine_temp(self) -> float: ...
    @overload
    def get_refine_temp(self) -> double: ...
    @overload
    def get_vicinity_degree(self) -> float: ...
    @overload
    def get_vicinity_degree(self) -> double: ...
    @overload
    def get_vicinity_sampling(self) -> bool: ...
    @overload
    def get_vicinity_sampling(self) -> bool: ...
    @overload
    def read_options(self) -> None: ...
    @overload
    def read_options(self) -> void: ...
    @overload
    def set_debug(self, debug: bool) -> None: ...
    @overload
    def set_debug(self, constbool) -> void: ...
    @overload
    def set_min_type(self, min_type: str) -> None: ...
    @overload
    def set_min_type(self, conststd) -> void: ...
    @overload
    def set_nonpivot_torsion_sampling(self, nonpivot_torsion_sampling: bool) -> None: ...
    @overload
    def set_nonpivot_torsion_sampling(self, constbool) -> void: ...
    @overload
    def set_refine_CCD_off(self, refine_CCD_off: bool) -> None: ...
    @overload
    def set_refine_CCD_off(self, constbool) -> void: ...
    @overload
    def set_refine_KIC_off(self, refine_KIC_off: bool) -> None: ...
    @overload
    def set_refine_KIC_off(self, constbool) -> void: ...
    @overload
    def set_refine_cycles(self, refine_cycles: int) -> None: ...
    @overload
    def set_refine_cycles(self, constunsignedlong) -> void: ...
    @overload
    def set_refine_repack_cycles(self, refine_repack_cycles: int) -> None: ...
    @overload
    def set_refine_repack_cycles(self, constunsignedlong) -> void: ...
    @overload
    def set_refine_temp(self, refine_temp: float) -> None: ...
    @overload
    def set_refine_temp(self, constdouble) -> void: ...
    @overload
    def set_vicinity_degree(self, vicinity_degree: int) -> None: ...
    @overload
    def set_vicinity_degree(self, constunsignedlong) -> void: ...
    @overload
    def set_vicinity_sampling(self, vicinity_sampling: bool) -> None: ...
    @overload
    def set_vicinity_sampling(self, constbool) -> void: ...
