import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.loops
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.utility
from typing import overload

class Antibody:
    Fv: pyrosetta.rosetta.core.pose.Pose
    Fv_sequence_: pyrosetta.rosetta.utility.vector1_char
    ab_movemap: pyrosetta.rosetta.core.kinematics.MoveMap
    all_cdr_loops: pyrosetta.rosetta.protocols.loops.Loops
    current_end: int
    current_start: int
    extended_: bool
    kinked_: bool
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, pose_in: pyrosetta.rosetta.core.pose.Pose, camelid: bool) -> None: ...
    @overload
    def __init__(self, pose_in: pyrosetta.rosetta.core.pose.Pose, cdr_name: str) -> None: ...
    @overload
    def __init__(self, arg0: Antibody) -> None: ...
    @overload
    def align_to_native(self, native: Antibody) -> None: ...
    @overload
    def align_to_native(self, classprotocols) -> void: ...
    @overload
    def all_cdr_fold_tree(self) -> None: ...
    @overload
    def all_cdr_fold_tree(self) -> void: ...
    def assign(self) -> Antibody: ...
    @overload
    def populate_all_cdrs(self) -> None: ...
    @overload
    def populate_all_cdrs(self) -> void: ...
    @overload
    def set_Fv(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_Fv(self, classcore) -> void: ...
    @overload
    def set_Fv(self, pose_in: pyrosetta.rosetta.core.pose.Pose, camelid: bool) -> None: ...
    @overload
    def set_Fv(self, classcore, bool) -> void: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...

class AntibodyModeler(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyModeler) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyModeler) -> None: ...
    @overload
    def all_cdr_VL_VH_fold_tree(self, pose_in: pyrosetta.rosetta.core.pose.Pose, loops: pyrosetta.rosetta.protocols.loops.Loops) -> None: ...
    @overload
    def all_cdr_VL_VH_fold_tree(self, classcore, constclassprotocols) -> void: ...
    @overload
    def apply(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> AntibodyModeler: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def display_constraint_residues(self) -> None: ...
    @overload
    def display_constraint_residues(self) -> void: ...
    def get_name(self) -> str: ...
    def global_loop_rmsd(self, pose_in: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, cdr_type: str) -> float: ...
    @overload
    def init_from_options(self) -> None: ...
    @overload
    def init_from_options(self) -> void: ...
    @overload
    def init_on_new_input(self) -> None: ...
    @overload
    def init_on_new_input(self) -> void: ...
    @overload
    def read_and_store_fragments(self) -> None: ...
    @overload
    def read_and_store_fragments(self) -> void: ...
    @overload
    def relax_cdrs(self) -> None: ...
    @overload
    def relax_cdrs(self) -> void: ...
    @overload
    def repulsive_ramp(self, pose_in: pyrosetta.rosetta.core.pose.Pose, loops_in: pyrosetta.rosetta.protocols.loops.Loops) -> None: ...
    @overload
    def repulsive_ramp(self, classcore, classprotocols) -> void: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_snugdock_foldtree(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_snugdock_foldtree(self, classcore) -> void: ...
    @overload
    def setup_packer_task(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def setup_packer_task(self, classcore) -> void: ...
    def setup_simple_fold_tree(self, jumppoint1: int, cutpoint: int, jumppoint2: int, nres: int, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    def snugfit_MC_min(self, pose_in: pyrosetta.rosetta.core.pose.Pose, cdr_dock_map: pyrosetta.rosetta.core.kinematics.MoveMap, cycles: int, minimization_threshold: float, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, pack_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, is_flexible: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def snugfit_mcm_protocol(self, pose_in: pyrosetta.rosetta.core.pose.Pose, loops_in: pyrosetta.rosetta.protocols.loops.Loops) -> None: ...
    @overload
    def snugfit_mcm_protocol(self, classcore, classprotocols) -> void: ...

class CDRH3Modeler(pyrosetta.rosetta.protocols.moves.Mover):
    H3_base_library: pyrosetta.rosetta.utility.vector1_core_fragment_FragData
    @overload
    def __init__(self, cdr_h3_frags: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_fragment_FragSet_t) -> None: ...
    @overload
    def __init__(self, arg0: CDRH3Modeler) -> None: ...
    @overload
    def __init__(self, arg0: CDRH3Modeler) -> None: ...
    @overload
    def CDR_H3_filter(self, pose_in: pyrosetta.rosetta.core.pose.Pose, loop_begin: int, size: int) -> bool: ...
    @overload
    def CDR_H3_filter(self, pose_in: pyrosetta.rosetta.core.pose.Pose, loop_begin: int, size: int, light_chain: str) -> bool: ...
    @overload
    def antibody_modeling_insert_ter(self) -> None: ...
    @overload
    def antibody_modeling_insert_ter(self) -> void: ...
    @overload
    def apply(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> CDRH3Modeler: ...
    @overload
    def build_centroid_loop(self) -> None: ...
    @overload
    def build_centroid_loop(self) -> void: ...
    @overload
    def build_fullatom_loop(self) -> None: ...
    @overload
    def build_fullatom_loop(self) -> void: ...
    @overload
    def cutpoint_separation(self, pose_in: pyrosetta.rosetta.core.pose.Pose, cutpoint: int) -> float: ...
    @overload
    def cutpoint_separation(self, classcore, unsignedlong) -> double: ...
    @overload
    def cutpoints_separation(self) -> bool: ...
    @overload
    def cutpoints_separation(self) -> bool: ...
    @overload
    def enable_benchmark_mode(self, setting: bool) -> None: ...
    @overload
    def enable_benchmark_mode(self, bool) -> void: ...
    def get_name(self) -> str: ...
    def loop_centroid_relax(self, pose_in: pyrosetta.rosetta.core.pose.Pose, loop_begin: int, loop_end: int) -> None: ...
    def loop_fa_relax(self, pose_in: pyrosetta.rosetta.core.pose.Pose, loop_begin: int, loop_end: int) -> None: ...
    @overload
    def model_h3(self, setting: bool) -> None: ...
    @overload
    def model_h3(self, bool) -> void: ...
    @overload
    def scored_frag_close(self, pose_in: pyrosetta.rosetta.core.pose.Pose, trimmed_cdr_h3: pyrosetta.rosetta.protocols.loops.Loop) -> None: ...
    @overload
    def scored_frag_close(self, classcore, constclassprotocols) -> void: ...
    @overload
    def set_camelid(self, setting: bool) -> None: ...
    @overload
    def set_camelid(self, bool) -> void: ...
    @overload
    def set_centroid_loop_building(self, setting: bool) -> None: ...
    @overload
    def set_centroid_loop_building(self, bool) -> void: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_fullatom_loop_building(self, setting: bool) -> None: ...
    @overload
    def set_fullatom_loop_building(self, bool) -> void: ...
    @overload
    def set_highres_score_func(self, highres_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_highres_score_func(self, classstd) -> void: ...
    @overload
    def set_lowres_score_func(self, lowres_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_lowres_score_func(self, classstd) -> void: ...
    @overload
    def setup_packer_task(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def setup_packer_task(self, classcore) -> void: ...
    @overload
    def store_H3_cter_fragment(self, base_library_in: pyrosetta.rosetta.utility.vector1_core_fragment_FragData) -> None: ...
    @overload
    def store_H3_cter_fragment(self, classutility) -> void: ...

class CloseOneMover(pyrosetta.rosetta.protocols.moves.Mover):
    def __init__(self, query_start: int, query_end: int) -> None: ...
    @overload
    def apply(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> CloseOneMover: ...
    @overload
    def close_one_loop_stem(self, pose_in: pyrosetta.rosetta.core.pose.Pose, cutpoint_in: int, nter: bool) -> None: ...
    @overload
    def close_one_loop_stem(self, classcore, unsignedlong, bool) -> void: ...
    @overload
    def close_one_loop_stem(self, pose_in: pyrosetta.rosetta.core.pose.Pose, loop_begin: int, loop_end: int, cutpoint: int) -> None: ...
    def close_one_loop_stem_helper(self, loop_begin: int, loop_end: int, cutpoint: int, pose_in: pyrosetta.rosetta.core.pose.Pose, loop_map: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def enable_benchmark_mode(self, setting: bool) -> None: ...
    @overload
    def enable_benchmark_mode(self, bool) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...

class GraftMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GraftMover) -> None: ...
    @overload
    def __init__(self, arg0: GraftMover) -> None: ...
    @overload
    def apply(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> GraftMover: ...
    @overload
    def enable_benchmark_mode(self, setting: bool) -> None: ...
    @overload
    def enable_benchmark_mode(self, bool) -> void: ...
    @overload
    def enable_graft_h1(self, setting: bool) -> None: ...
    @overload
    def enable_graft_h1(self, bool) -> void: ...
    @overload
    def enable_graft_h2(self, setting: bool) -> None: ...
    @overload
    def enable_graft_h2(self, bool) -> void: ...
    @overload
    def enable_graft_h3(self, setting: bool) -> None: ...
    @overload
    def enable_graft_h3(self, bool) -> void: ...
    @overload
    def enable_graft_l1(self, setting: bool) -> None: ...
    @overload
    def enable_graft_l1(self, bool) -> void: ...
    @overload
    def enable_graft_l2(self, setting: bool) -> None: ...
    @overload
    def enable_graft_l2(self, bool) -> void: ...
    @overload
    def enable_graft_l3(self, setting: bool) -> None: ...
    @overload
    def enable_graft_l3(self, bool) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def relax_optimized_CDR_grafts(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def relax_optimized_CDR_grafts(self, classcore) -> void: ...
    @overload
    def set_camelid(self, setting: bool) -> None: ...
    @overload
    def set_camelid(self, bool) -> void: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...

class GraftOneMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, query_start: int, query_end: int, template_name: str) -> None: ...
    @overload
    def __init__(self, arg0: GraftOneMover) -> None: ...
    @overload
    def __init__(self, arg0: GraftOneMover) -> None: ...
    @overload
    def apply(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> GraftOneMover: ...
    @overload
    def enable_benchmark_mode(self, setting: bool) -> None: ...
    @overload
    def enable_benchmark_mode(self, bool) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...

class LoopRlxMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, query_start: int, query_end: int) -> None: ...
    @overload
    def __init__(self, arg0: LoopRlxMover) -> None: ...
    @overload
    def __init__(self, arg0: LoopRlxMover) -> None: ...
    @overload
    def apply(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> LoopRlxMover: ...
    @overload
    def enable_benchmark_mode(self, setting: bool) -> None: ...
    @overload
    def enable_benchmark_mode(self, bool) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def setup_packer_task(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def setup_packer_task(self, classcore) -> void: ...

@overload
def read_H3_cter_fragment(antibody_in: Antibody, H3_base_library: pyrosetta.rosetta.utility.vector1_core_fragment_FragData, is_camelid: bool) -> None: ...
@overload
def read_H3_cter_fragment(classprotocols, classutility, bool) -> void: ...
def simple_fold_tree(pose_in: pyrosetta.rosetta.core.pose.Pose, jumppoint1: int, cutpoint: int, jumppoint2: int) -> None: ...
@overload
def simple_one_loop_fold_tree(pose: pyrosetta.rosetta.core.pose.Pose, loop: pyrosetta.rosetta.protocols.loops.Loop) -> None: ...
@overload
def simple_one_loop_fold_tree(classcore, constclassprotocols) -> void: ...
