import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.select.movemap
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import ClassVar, overload

backward: QuenchDirection
c_linked_NxC: GlycanSequon
c_linked_WSTxC: GlycanSequon
c_linked_WxxW: GlycanSequon
forward: QuenchDirection
n_linked_basic_enhanced: GlycanSequon
n_linked_best_enhanced: GlycanSequon
n_linked_typical: GlycanSequon

class CreateGlycanSequonMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: CreateGlycanSequonMover) -> None: ...
    @overload
    def __init__(self, arg0: CreateGlycanSequonMover) -> None: ...
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    def assign(self) -> CreateGlycanSequonMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_design_neighbors(self, design_neighbors: bool) -> None: ...
    @overload
    def set_design_neighbors(self, constbool) -> void: ...
    @overload
    def set_design_x_positions(self, design_x_positions: bool) -> None: ...
    @overload
    def set_design_x_positions(self, constbool) -> void: ...
    @overload
    def set_glycan_sequon_type(self, sequon: GlycanSequon) -> None: ...
    @overload
    def set_glycan_sequon_type(self, enumprotocols) -> void: ...
    @overload
    def set_glycosylation_position(self, position: int, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_glycosylation_position(self, unsignedlong, constclasscore) -> void: ...
    @overload
    def set_pack_distance(self, pack_distance: float) -> None: ...
    @overload
    def set_pack_distance(self, constdouble) -> void: ...
    @overload
    def set_pack_neighbors(self, pack_neighbors: bool) -> None: ...
    @overload
    def set_pack_neighbors(self, constbool) -> void: ...
    @overload
    def set_pack_rounds(self, pack_rounds: int) -> None: ...
    @overload
    def set_pack_rounds(self, unsignedlong) -> void: ...
    def set_positions_as_start_of_sequon(self, *args, **kwargs): ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    @overload
    def set_score_function(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_score_function(self, classstd) -> void: ...
    @overload
    def set_use_basic_enhanced_n_linked_sequon(self, enhanced: bool) -> None: ...
    @overload
    def set_use_basic_enhanced_n_linked_sequon(self, bool) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class CreateGlycanSequonMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CreateGlycanSequonMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: CreateGlycanSequonMoverCreator) -> None: ...
    def assign(self) -> CreateGlycanSequonMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class GlycanSampler(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, arg1: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, rounds: int) -> None: ...
    @overload
    def __init__(self, arg0: GlycanSampler) -> None: ...
    @overload
    def __init__(self, arg0: GlycanSampler) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> GlycanSampler: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def force_total_rounds(self, total_rounds: int) -> None: ...
    @overload
    def force_total_rounds(self, unsignedlong) -> void: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def get_glycan_sampler_rounds(self) -> int: ...
    @overload
    def get_glycan_sampler_rounds(self) -> unsignedlong: ...
    def get_name(self) -> str: ...
    @overload
    def idealize_glycan_residues(self, pose: pyrosetta.rosetta.core.pose.Pose, tree_subset: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def idealize_glycan_residues(self, classcore, constclassutility) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def randomize_glycan_torsions(self, pose: pyrosetta.rosetta.core.pose.Pose, subset: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def randomize_glycan_torsions(self, classcore, constclassutility) -> void: ...
    @overload
    def reinitialize_for_each_job(self) -> bool: ...
    @overload
    def reinitialize_for_each_job(self) -> bool: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...
    @overload
    def set_inner_bb_cycles(self, inner_bb_cycles: int) -> None: ...
    @overload
    def set_inner_bb_cycles(self, unsignedlong) -> void: ...
    @overload
    def set_kt(self, kt: float) -> None: ...
    @overload
    def set_kt(self, double) -> void: ...
    @overload
    def set_min_rings(self, min_rings: bool) -> None: ...
    @overload
    def set_min_rings(self, bool) -> void: ...
    @overload
    def set_population_based_conformer_sampling(self, pop_based_sampling: bool) -> None: ...
    @overload
    def set_population_based_conformer_sampling(self, bool) -> void: ...
    @overload
    def set_protein_linkage_prob_sampling(self, root_probs: bool) -> None: ...
    @overload
    def set_protein_linkage_prob_sampling(self, bool) -> void: ...
    @overload
    def set_randomize_first(self, randomize_first: bool) -> None: ...
    @overload
    def set_randomize_first(self, bool) -> void: ...
    @overload
    def set_refine(self, refine: bool) -> None: ...
    @overload
    def set_refine(self, bool) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    @overload
    def set_rounds(self, rounds: int) -> None: ...
    @overload
    def set_rounds(self, unsignedlong) -> void: ...
    @overload
    def set_scorefunction(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefunction(self, classstd) -> void: ...
    @overload
    def set_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_selector(self, classstd) -> void: ...
    @overload
    def set_taskfactory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_taskfactory(self, classstd) -> void: ...
    @overload
    def set_use_gaussian_sampling(self, use_gaussian_sampling: bool) -> None: ...
    @overload
    def set_use_gaussian_sampling(self, bool) -> void: ...
    @overload
    def set_use_shear(self, use_shear: bool) -> None: ...
    @overload
    def set_use_shear(self, bool) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def use_cartmin(self, use_cartmin: bool) -> None: ...
    @overload
    def use_cartmin(self, bool) -> void: ...

class GlycanSamplerCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GlycanSamplerCreator) -> None: ...
    @overload
    def __init__(self, arg0: GlycanSamplerCreator) -> None: ...
    def assign(self) -> GlycanSamplerCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class GlycanSequon:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    c_linked_NxC: ClassVar[GlycanSequon] = ...
    c_linked_WSTxC: ClassVar[GlycanSequon] = ...
    c_linked_WxxW: ClassVar[GlycanSequon] = ...
    n_linked_basic_enhanced: ClassVar[GlycanSequon] = ...
    n_linked_best_enhanced: ClassVar[GlycanSequon] = ...
    n_linked_typical: ClassVar[GlycanSequon] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class GlycanTreeMinMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, arg1: bool) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, arg1: bool, arg2: bool) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, min_rings: bool, min_bb: bool, min_chi: bool) -> None: ...
    @overload
    def __init__(self, arg0: GlycanTreeMinMover) -> None: ...
    @overload
    def __init__(self, arg0: GlycanTreeMinMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> GlycanTreeMinMover: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_min_bb(self, min_bb: bool) -> None: ...
    @overload
    def set_min_bb(self, bool) -> void: ...
    @overload
    def set_min_chi(self, min_chi: bool) -> None: ...
    @overload
    def set_min_chi(self, bool) -> void: ...
    @overload
    def set_min_rings(self, min_rings: bool) -> None: ...
    @overload
    def set_min_rings(self, bool) -> void: ...
    @overload
    def set_minmover(self, min_mover) -> None: ...
    @overload
    def set_minmover(self, classstd) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...

class GlycanTreeMinMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GlycanTreeMinMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: GlycanTreeMinMoverCreator) -> None: ...
    def assign(self) -> GlycanTreeMinMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class GlycanTreeModeler(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GlycanTreeModeler) -> None: ...
    @overload
    def __init__(self, arg0: GlycanTreeModeler) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> GlycanTreeModeler: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_final_min_pack_min(self, minpackmin: bool) -> None: ...
    @overload
    def set_final_min_pack_min(self, constbool) -> void: ...
    @overload
    def set_force_virts_for_refinement(self, force_virts: bool) -> None: ...
    @overload
    def set_force_virts_for_refinement(self, bool) -> void: ...
    @overload
    def set_glycan_sampler_kt(self, kT: float) -> None: ...
    @overload
    def set_glycan_sampler_kt(self, double) -> void: ...
    @overload
    def set_glycan_sampler_rounds(self, glycan_sampler_rounds: int) -> None: ...
    @overload
    def set_glycan_sampler_rounds(self, unsignedlong) -> void: ...
    @overload
    def set_hybrid_protocol(self, hybrid_protocol: bool) -> None: ...
    @overload
    def set_hybrid_protocol(self, bool) -> void: ...
    @overload
    def set_layer_size(self, layer_size: int) -> None: ...
    @overload
    def set_layer_size(self, constunsignedlong) -> void: ...
    @overload
    def set_protein_linkage_prob_sampling(self, root_probs: bool) -> None: ...
    @overload
    def set_protein_linkage_prob_sampling(self, bool) -> void: ...
    @overload
    def set_quench_mode(self, quench_mode: bool) -> None: ...
    @overload
    def set_quench_mode(self, bool) -> void: ...
    def set_refine(self, *args, **kwargs): ...
    @overload
    def set_rounds(self, rounds: int) -> None: ...
    @overload
    def set_rounds(self, constunsignedlong) -> void: ...
    @overload
    def set_scorefxn(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn(self, classstd) -> void: ...
    @overload
    def set_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_selector(self, classstd) -> void: ...
    @overload
    def set_use_conformer_probabilities(self, conformer_probs: bool) -> None: ...
    @overload
    def set_use_conformer_probabilities(self, bool) -> void: ...
    @overload
    def set_use_gaussian_sampling(self, gaussian_sampling: bool) -> None: ...
    @overload
    def set_use_gaussian_sampling(self, bool) -> void: ...
    @overload
    def set_use_shear(self, use_shear: bool) -> None: ...
    @overload
    def set_use_shear(self, bool) -> void: ...
    @overload
    def set_window_size(self, window_size: int) -> None: ...
    @overload
    def set_window_size(self, constunsignedlong) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class GlycanTreeModelerCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GlycanTreeModelerCreator) -> None: ...
    @overload
    def __init__(self, arg0: GlycanTreeModelerCreator) -> None: ...
    def assign(self) -> GlycanTreeModelerCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class IdealizeAnomericHydrogens(pyrosetta.rosetta.protocols.moves.Mover):
    def __init__(self) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> IdealizeAnomericHydrogens: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class IdealizeAnomericHydrogensCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: IdealizeAnomericHydrogensCreator) -> None: ...
    @overload
    def __init__(self, arg0: IdealizeAnomericHydrogensCreator) -> None: ...
    def assign(self) -> IdealizeAnomericHydrogensCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class LinkageConformerMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: LinkageConformerMover) -> None: ...
    @overload
    def __init__(self, arg0: LinkageConformerMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> LinkageConformerMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def conformer_found(self) -> bool: ...
    @overload
    def conformer_found(self) -> bool: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def reinitialize_for_each_job(self) -> bool: ...
    @overload
    def reinitialize_for_each_job(self) -> bool: ...
    @overload
    def reinitialize_for_new_input(self) -> bool: ...
    @overload
    def reinitialize_for_new_input(self) -> bool: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...
    @overload
    def set_idealize_torsions(self, idealize_torsions: bool) -> None: ...
    @overload
    def set_idealize_torsions(self, bool) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    @overload
    def set_root_prob_sampling(self, root_prob_sampling: bool) -> None: ...
    @overload
    def set_root_prob_sampling(self, bool) -> void: ...
    @overload
    def set_single_resnum(self, pose: pyrosetta.rosetta.core.pose.Pose, resnum: int) -> None: ...
    @overload
    def set_single_resnum(self, constclasscore, unsignedlong) -> void: ...
    @overload
    def set_use_conformer_population_stats(self, setting: bool) -> None: ...
    @overload
    def set_use_conformer_population_stats(self, constbool) -> void: ...
    @overload
    def set_use_gaussian_sampling(self, prob_sd_sample: bool) -> None: ...
    @overload
    def set_use_gaussian_sampling(self, bool) -> void: ...
    @overload
    def set_use_sugar_bb_data_if_needed(self, use_sugar_bb: bool) -> None: ...
    @overload
    def set_use_sugar_bb_data_if_needed(self, bool) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class LinkageConformerMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LinkageConformerMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: LinkageConformerMoverCreator) -> None: ...
    def assign(self) -> LinkageConformerMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class QuenchDirection:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    backward: ClassVar[QuenchDirection] = ...
    forward: ClassVar[QuenchDirection] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class RingPlaneFlipMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RingPlaneFlipMover) -> None: ...
    @overload
    def __init__(self, arg0: RingPlaneFlipMover) -> None: ...
    @overload
    def __init__(self, input_movemap: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def apply(self, input_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self, object_to_copy: RingPlaneFlipMover) -> RingPlaneFlipMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def movemap(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def movemap(self, new_movemap: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def movemap(self, classstd) -> void: ...
    @overload
    def movemap_factory(self, new_movemap_factory: pyrosetta.rosetta.core.select.movemap.MoveMapFactory) -> None: ...
    @overload
    def movemap_factory(self, classstd) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    @staticmethod
    def register_options() -> None: ...
    @overload
    @staticmethod
    def register_options() -> void: ...
    @overload
    def selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    def selector(self, new_selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def selector(self, classstd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class RingPlaneFlipMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RingPlaneFlipMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: RingPlaneFlipMoverCreator) -> None: ...
    def assign(self) -> RingPlaneFlipMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SimpleGlycosylateMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SimpleGlycosylateMover) -> None: ...
    @overload
    def __init__(self, arg0: SimpleGlycosylateMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> SimpleGlycosylateMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_glycosylation(self, iupac_or_common_string: str) -> None: ...
    @overload
    def set_glycosylation(self, conststd) -> void: ...
    @overload
    def set_glycosylation_weights(self, weights: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_glycosylation_weights(self, constclassutility) -> void: ...
    @overload
    def set_glycosylations(self, iupac_or_common_strings: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_glycosylations(self, constclassutility) -> void: ...
    @overload
    def set_position(self, position: int) -> None: ...
    @overload
    def set_position(self, unsignedlong) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    @overload
    def set_strip_existing_glycans(self, strip_existing: bool) -> None: ...
    @overload
    def set_strip_existing_glycans(self, bool) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class SimpleGlycosylateMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SimpleGlycosylateMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: SimpleGlycosylateMoverCreator) -> None: ...
    def assign(self) -> SimpleGlycosylateMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class TautomerizeAnomerMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TautomerizeAnomerMover) -> None: ...
    @overload
    def __init__(self, arg0: TautomerizeAnomerMover) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def apply(self, input_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self, object_to_copy: TautomerizeAnomerMover) -> TautomerizeAnomerMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    @staticmethod
    def register_options() -> None: ...
    @overload
    @staticmethod
    def register_options() -> void: ...
    @overload
    def selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    def selector(self, new_selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def selector(self, classstd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class TautomerizeAnomerMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TautomerizeAnomerMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: TautomerizeAnomerMoverCreator) -> None: ...
    def assign(self) -> TautomerizeAnomerMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

def create_sequons() -> pyrosetta.rosetta.std.map_protocols_carbohydrates_GlycanSequon_std_string: ...
@overload
def get_all_glycans_and_neighbor_res_task_factory(subset: pyrosetta.rosetta.utility.vector1_bool) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
@overload
def get_all_glycans_and_neighbor_res_task_factory(subset: pyrosetta.rosetta.utility.vector1_bool, pack_distance: float) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
@overload
def get_all_glycans_and_neighbor_res_task_factory(subset: pyrosetta.rosetta.utility.vector1_bool, pack_distance: float, read_resfile: bool) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
@overload
def get_total_rounds_for_overlap_one_layer_two(pose: pyrosetta.rosetta.core.pose.Pose, residue_subset: pyrosetta.rosetta.utility.vector1_bool, sampler_rounds: int) -> int: ...
@overload
def get_total_rounds_for_overlap_one_layer_two(constclasscore, constclassutility, unsignedlong) -> unsignedlong: ...
@overload
def run_shear_min_pack(min_mover, packer, shear, mc: pyrosetta.rosetta.protocols.moves.MonteCarlo, n_glycan_residues: int, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def run_shear_min_pack(min_mover, packer, shear, mc: pyrosetta.rosetta.protocols.moves.MonteCarlo, n_glycan_residues: int, pose: pyrosetta.rosetta.core.pose.Pose, use_shear: bool) -> None: ...
