import pyrosetta.rosetta.core.pose
from typing import overload

class CheckPointer:
    @overload
    def __init__(self, type: str) -> None: ...
    @overload
    def __init__(self, arg0: CheckPointer) -> None: ...
    def assign(self) -> CheckPointer: ...
    @overload
    def checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, mc, current_tag: str, id: str) -> None: ...
    @overload
    def checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, mc, current_tag: str, id: str, foldtree: bool) -> None: ...
    @overload
    def checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, mc, current_tag: str, id: str) -> None: ...
    @overload
    def checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, mc, current_tag: str, id: str, foldtree: bool) -> None: ...
    @overload
    def checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, current_tag: str, id: str) -> None: ...
    @overload
    def checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, current_tag: str, id: str, foldtree: bool) -> None: ...
    @overload
    def clear_checkpoints(self) -> None: ...
    @overload
    def clear_checkpoints(self, no_tracer: bool) -> None: ...
    @overload
    def clear_checkpoints(self, bool) -> void: ...
    @overload
    def debug(self, tag: str, label: str, data1: float) -> None: ...
    @overload
    def debug(self, tag: str, label: str, data1: float, data2: float) -> None: ...
    @overload
    def debug(self, tag: str, label: str, data1: float, data2: float, data3: float) -> None: ...
    @overload
    def flush_checkpoints(self) -> None: ...
    @overload
    def flush_checkpoints(self) -> void: ...
    @overload
    def get_checkpoint_recoveries(self) -> int: ...
    @overload
    def get_checkpoint_recoveries(self) -> unsignedlong: ...
    @overload
    def get_disabled(self) -> bool: ...
    @overload
    def get_disabled(self) -> bool: ...
    @overload
    def recover_checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, mc, current_tag: str, id: str) -> bool: ...
    @overload
    def recover_checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, mc, current_tag: str, id: str, fullatom: bool) -> bool: ...
    @overload
    def recover_checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, mc, current_tag: str, id: str, fullatom: bool, foldtree: bool) -> bool: ...
    @overload
    def recover_checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, mc, current_tag: str, id: str) -> bool: ...
    @overload
    def recover_checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, mc, current_tag: str, id: str, fullatom: bool) -> bool: ...
    @overload
    def recover_checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, mc, current_tag: str, id: str, fullatom: bool, foldtree: bool) -> bool: ...
    @overload
    def recover_checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, current_tag: str, id: str) -> bool: ...
    @overload
    def recover_checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, current_tag: str, id: str, fullatom: bool) -> bool: ...
    @overload
    def recover_checkpoint(self, pose: pyrosetta.rosetta.core.pose.Pose, current_tag: str, id: str, fullatom: bool, foldtree: bool) -> bool: ...
    @overload
    def set_disabled(self) -> None: ...
    @overload
    def set_disabled(self, value: bool) -> None: ...
    @overload
    def set_disabled(self, bool) -> void: ...
    @overload
    def set_type(self, new_type: str) -> None: ...
    @overload
    def set_type(self, conststd) -> void: ...
    def type(self) -> str: ...

class FileBuffer:
    @overload
    def __init__(self, filename: str) -> None: ...
    @overload
    def __init__(self, filename: str, gzipped: bool) -> None: ...
    @overload
    def __init__(self, arg0: FileBuffer) -> None: ...
    def assign(self) -> FileBuffer: ...
    @overload
    def dump(self) -> None: ...
    @overload
    def dump(self) -> void: ...
    @overload
    def set_contents(self, contents: str) -> None: ...
    @overload
    def set_contents(self, conststd) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...

class Timer:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def instance() -> Timer: ...
    @overload
    @staticmethod
    def is_on() -> bool: ...
    @overload
    @staticmethod
    def is_on() -> bool: ...
    @overload
    @staticmethod
    def reset() -> None: ...
    @overload
    @staticmethod
    def reset() -> void: ...
    @overload
    def set_interval(self, interval_in: int) -> None: ...
    @overload
    def set_interval(self, constint) -> void: ...
    @overload
    @staticmethod
    def time_to_checkpoint() -> bool: ...
    @overload
    @staticmethod
    def time_to_checkpoint() -> bool: ...

@overload
def checkpoint_with_interval(interval_in: int) -> None: ...
@overload
def checkpoint_with_interval(constint) -> void: ...
