import pyrosetta.rosetta.ObjexxFCL
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.io.silent
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.scoring.constraints
import pyrosetta.rosetta.core.scoring.func
import pyrosetta.rosetta.core.sequence
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.protocols.evaluation
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import overload

class AmbiguousMultiConstraint(pyrosetta.rosetta.core.scoring.constraints.AmbiguousConstraint):
    @overload
    def __init__(self, num_act_csts: int) -> None: ...
    @overload
    def __init__(self, num_act_csts: int, cst_in: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_scoring_constraints_Constraint_t) -> None: ...
    @overload
    def __init__(self, arg0: AmbiguousMultiConstraint) -> None: ...
    @overload
    def __init__(self, arg0: AmbiguousMultiConstraint) -> None: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    def fill_f1_f2(self, atom: pyrosetta.rosetta.core.id.AtomID, xyz: pyrosetta.rosetta.core.scoring.func.XYZ_Func, F1: pyrosetta.rosetta.numeric.xyzVector_double_t, F2: pyrosetta.rosetta.numeric.xyzVector_double_t, weights: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def remap_resid(self, seqmap: pyrosetta.rosetta.core.id.SequenceMapping) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.constraints.Constraint) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def score(self, xyz_func: pyrosetta.rosetta.core.scoring.func.XYZ_Func, weights: pyrosetta.rosetta.core.scoring.EMapVector, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, pose: pyrosetta.rosetta.core.pose.Pose, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, pose: pyrosetta.rosetta.core.pose.Pose, verbose_level: int, threshold: float) -> int: ...
    @overload
    def show_violations(self, std, constclasscore, unsignedlong, double) -> unsignedlong: ...
    def type(self) -> str: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.constraints.Constraint) -> bool: ...

class BindingSiteConstraint(pyrosetta.rosetta.core.scoring.constraints.Constraint):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.utility.vector1_core_id_AtomID, arg1: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, atms: pyrosetta.rosetta.utility.vector1_core_id_AtomID, start_pose: pyrosetta.rosetta.core.pose.Pose, scoretype: pyrosetta.rosetta.core.scoring.ScoreType) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.utility.vector1_core_id_AtomID, arg1: pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t, arg2: pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t) -> None: ...
    @overload
    def __init__(self, atms: pyrosetta.rosetta.utility.vector1_core_id_AtomID, tgt_pos: pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t, tgt_pos_centroid: pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t, scoretype: pyrosetta.rosetta.core.scoring.ScoreType) -> None: ...
    @overload
    def __init__(self, arg0: BindingSiteConstraint) -> None: ...
    @overload
    def __init__(self, arg0: BindingSiteConstraint) -> None: ...
    def atom(self, n: int) -> pyrosetta.rosetta.core.id.AtomID: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    @overload
    def dist(self) -> float: ...
    @overload
    def dist(self) -> float: ...
    @overload
    def dist(self, constclasscore) -> double: ...
    def fill_f1_f2(self, atom: pyrosetta.rosetta.core.id.AtomID, xyz: pyrosetta.rosetta.core.scoring.func.XYZ_Func, F1: pyrosetta.rosetta.numeric.xyzVector_double_t, F2: pyrosetta.rosetta.numeric.xyzVector_double_t, weights: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def natoms(self) -> int: ...
    @overload
    def natoms(self) -> unsignedlong: ...
    def pre_align(self, templ_atms: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t) -> None: ...
    def read_def(self, _in: pyrosetta.rosetta.std.istream, pose: pyrosetta.rosetta.core.pose.Pose, func_factory: pyrosetta.rosetta.core.scoring.func.FuncFactory) -> None: ...
    def remap_resid(self, seqmap: pyrosetta.rosetta.core.id.SequenceMapping) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.constraints.Constraint) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def score(self, pose: pyrosetta.rosetta.core.pose.Pose, weights: pyrosetta.rosetta.core.scoring.EMapVector) -> float: ...
    @overload
    def score(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def score(self, xyz: pyrosetta.rosetta.core.scoring.func.XYZ_Func, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    def setup_for_derivatives(self, xyz: pyrosetta.rosetta.core.scoring.func.XYZ_Func, scfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    def setup_for_scoring(self, xyz: pyrosetta.rosetta.core.scoring.func.XYZ_Func, scfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def show_def(self, out: pyrosetta.rosetta.std.ostream, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def show_def(self, std, constclasscore) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, pose: pyrosetta.rosetta.core.pose.Pose, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, pose: pyrosetta.rosetta.core.pose.Pose, verbose_level: int, threshold: float) -> int: ...
    @overload
    def show_violations(self, std, constclasscore, unsignedlong, double) -> unsignedlong: ...
    def type(self) -> str: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.constraints.Constraint) -> bool: ...

class BindingSiteConstraintCreator(pyrosetta.rosetta.core.scoring.constraints.ConstraintCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: BindingSiteConstraintCreator) -> None: ...
    @overload
    def __init__(self, arg0: BindingSiteConstraintCreator) -> None: ...
    def assign(self) -> BindingSiteConstraintCreator: ...
    def create_constraint(self) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    def keyname(self) -> str: ...

class COMCoordinateConstraint(pyrosetta.rosetta.core.scoring.constraints.Constraint):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.utility.vector1_core_id_AtomID, arg1: pyrosetta.rosetta.numeric.xyzVector_double_t, arg2: float, arg3: float) -> None: ...
    @overload
    def __init__(self, atms: pyrosetta.rosetta.utility.vector1_core_id_AtomID, COM_target: pyrosetta.rosetta.numeric.xyzVector_double_t, stdv: float, interval: float, scoretype: pyrosetta.rosetta.core.scoring.ScoreType) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.utility.vector1_core_id_AtomID, arg1: pyrosetta.rosetta.numeric.xyzVector_double_t, arg2: float) -> None: ...
    @overload
    def __init__(self, atms: pyrosetta.rosetta.utility.vector1_core_id_AtomID, COM_target: pyrosetta.rosetta.numeric.xyzVector_double_t, stdv: float, scoretype: pyrosetta.rosetta.core.scoring.ScoreType) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.utility.vector1_core_id_AtomID, arg1: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def __init__(self, atms: pyrosetta.rosetta.utility.vector1_core_id_AtomID, COM_target: pyrosetta.rosetta.numeric.xyzVector_double_t, scoretype: pyrosetta.rosetta.core.scoring.ScoreType) -> None: ...
    @overload
    def __init__(self, arg0: COMCoordinateConstraint) -> None: ...
    @overload
    def __init__(self, arg0: COMCoordinateConstraint) -> None: ...
    def atom(self, n: int) -> pyrosetta.rosetta.core.id.AtomID: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    @overload
    def dist(self) -> float: ...
    @overload
    def dist(self, xyz: pyrosetta.rosetta.core.scoring.func.XYZ_Func) -> float: ...
    @overload
    def dist(self, constclasscore) -> double: ...
    def fill_f1_f2(self, atom: pyrosetta.rosetta.core.id.AtomID, xyz: pyrosetta.rosetta.core.scoring.func.XYZ_Func, F1: pyrosetta.rosetta.numeric.xyzVector_double_t, F2: pyrosetta.rosetta.numeric.xyzVector_double_t, weights: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def natoms(self) -> int: ...
    @overload
    def natoms(self) -> unsignedlong: ...
    def read_def(self, _in: pyrosetta.rosetta.std.istream, pose: pyrosetta.rosetta.core.pose.Pose, func_factory: pyrosetta.rosetta.core.scoring.func.FuncFactory) -> None: ...
    def remap_resid(self) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    def remapped_clone(self, src: pyrosetta.rosetta.core.pose.Pose, dest: pyrosetta.rosetta.core.pose.Pose, smap: pyrosetta.rosetta.core.id.SequenceMapping) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.constraints.Constraint) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def score(self, pose: pyrosetta.rosetta.core.pose.Pose, weights: pyrosetta.rosetta.core.scoring.EMapVector) -> float: ...
    @overload
    def score(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def score(self, xyz: pyrosetta.rosetta.core.scoring.func.XYZ_Func, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    def setup_for_derivatives(self, xyz: pyrosetta.rosetta.core.scoring.func.XYZ_Func, scfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    def setup_for_scoring(self, xyz: pyrosetta.rosetta.core.scoring.func.XYZ_Func, scfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def show_def(self, out: pyrosetta.rosetta.std.ostream, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def show_def(self, std, constclasscore) -> void: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, pose: pyrosetta.rosetta.core.pose.Pose, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, pose: pyrosetta.rosetta.core.pose.Pose, verbose_level: int, threshold: float) -> int: ...
    @overload
    def show_violations(self, std, constclasscore, unsignedlong, double) -> unsignedlong: ...
    def type(self) -> str: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.constraints.Constraint) -> bool: ...

class CombinedConstraintEvaluator(pyrosetta.rosetta.protocols.evaluation.PoseEvaluator):
    @overload
    def __init__(self, arg0: str, arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: int) -> None: ...
    @overload
    def __init__(self, tag: str, filename: str, constraints_combine_ratio_: int, repeat: int) -> None: ...
    @overload
    def __init__(self, arg0: CombinedConstraintEvaluator) -> None: ...
    @overload
    def __init__(self, arg0: CombinedConstraintEvaluator) -> None: ...
    @overload
    def apply(self, pss: pyrosetta.rosetta.core.io.silent.SilentStruct) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose, tag: str, pss: pyrosetta.rosetta.core.io.silent.SilentStruct) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def apply(self, classcore) -> double: ...
    def assign(self) -> CombinedConstraintEvaluator: ...
    def name(self, i: int) -> str: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...

class CombinedConstraintEvaluatorCreator(pyrosetta.rosetta.protocols.evaluation.EvaluatorCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CombinedConstraintEvaluatorCreator) -> None: ...
    @overload
    def __init__(self, arg0: CombinedConstraintEvaluatorCreator) -> None: ...
    @overload
    def add_evaluators(self, eval: pyrosetta.rosetta.protocols.evaluation.MetaPoseEvaluator) -> None: ...
    @overload
    def add_evaluators(self, classprotocols) -> void: ...
    def assign(self) -> CombinedConstraintEvaluatorCreator: ...
    @overload
    def register_options(self) -> None: ...
    @overload
    def register_options(self) -> void: ...
    def type_name(self) -> str: ...

class ConstraintEvaluator(pyrosetta.rosetta.protocols.evaluation.PoseEvaluator):
    @overload
    def __init__(self, arg0: str, arg1: pyrosetta.rosetta.core.scoring.constraints.ConstraintSet) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: pyrosetta.rosetta.core.scoring.constraints.ConstraintSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: pyrosetta.rosetta.core.scoring.constraints.ConstraintSet, arg2: int, arg3: float) -> None: ...
    @overload
    def __init__(self, tag: str, viol_level: int, threshold: float, max_seq_sep: int) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_scoring_constraints_Constraint_t) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_scoring_constraints_Constraint_t, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_scoring_constraints_Constraint_t, arg2: int, arg3: float) -> None: ...
    @overload
    def __init__(self, tag: str, viol_level: int, threshold: float, max_seq_sep: int) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: int, arg3: float) -> None: ...
    @overload
    def __init__(self, tag: str, filename: str, viol_level: int, threshold: float, max_seq_sep: int) -> None: ...
    @overload
    def __init__(self, arg0: ConstraintEvaluator) -> None: ...
    @overload
    def __init__(self, arg0: ConstraintEvaluator) -> None: ...
    @overload
    def apply(self, pss: pyrosetta.rosetta.core.io.silent.SilentStruct) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose, tag: str, pss: pyrosetta.rosetta.core.io.silent.SilentStruct) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def apply(self, classcore) -> double: ...
    def assign(self) -> ConstraintEvaluator: ...
    def name(self, i: int) -> str: ...
    @overload
    def set_combine_ratio(self, setting: int) -> None: ...
    @overload
    def set_combine_ratio(self, unsignedlong) -> void: ...
    @overload
    def set_cst_source(self, tag: str) -> None: ...
    @overload
    def set_cst_source(self, conststd) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...

class ConstraintEvaluatorCreator(pyrosetta.rosetta.protocols.evaluation.EvaluatorCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ConstraintEvaluatorCreator) -> None: ...
    @overload
    def __init__(self, arg0: ConstraintEvaluatorCreator) -> None: ...
    @overload
    def add_evaluators(self, eval: pyrosetta.rosetta.protocols.evaluation.MetaPoseEvaluator) -> None: ...
    @overload
    def add_evaluators(self, classprotocols) -> void: ...
    def assign(self) -> ConstraintEvaluatorCreator: ...
    @overload
    def register_options(self) -> None: ...
    @overload
    def register_options(self) -> void: ...
    def type_name(self) -> str: ...

class MaxSeqSepConstraintSet(pyrosetta.rosetta.core.scoring.constraints.ConstraintSet):
    @overload
    def __init__(self, other: pyrosetta.rosetta.core.scoring.constraints.ConstraintSet, f: pyrosetta.rosetta.core.kinematics.FoldTree) -> None: ...
    @overload
    def __init__(self, arg0: MaxSeqSepConstraintSet) -> None: ...
    @overload
    def __init__(self, arg0: MaxSeqSepConstraintSet) -> None: ...
    @overload
    def assign(self, rhs: pyrosetta.rosetta.core.scoring.constraints.ConstraintSet) -> pyrosetta.rosetta.core.scoring.constraints.ConstraintSet: ...
    @overload
    def assign(self) -> MaxSeqSepConstraintSet: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.constraints.ConstraintSet: ...
    def detached_clone(self) -> pyrosetta.rosetta.core.scoring.constraints.ConstraintSet: ...
    @overload
    def detached_copy(self, src: pyrosetta.rosetta.core.scoring.constraints.ConstraintSet) -> None: ...
    @overload
    def detached_copy(self, constclasscore) -> void: ...
    def eval_non_residue_pair_energy(self, pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def largest_possible_sequence_sep(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def largest_possible_sequence_sep(self, constclasscore) -> unsignedlong: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def max_seq_sep(self) -> int: ...
    @overload
    def max_seq_sep(self) -> unsignedlong: ...
    @overload
    def remapped_clone(self, src: pyrosetta.rosetta.core.pose.Pose, dest: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.scoring.constraints.ConstraintSet: ...
    @overload
    def remapped_clone(self, src: pyrosetta.rosetta.core.pose.Pose, dest: pyrosetta.rosetta.core.pose.Pose, smap: pyrosetta.rosetta.core.id.SequenceMapping) -> pyrosetta.rosetta.core.scoring.constraints.ConstraintSet: ...
    def residue_pair_constraint_exists(self, pos1: int, pos2: int) -> bool: ...
    def residue_pair_energy(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, emap: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.constraints.ConstraintSet) -> bool: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.constraints.ConstraintSet, recurse: bool) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore, bool) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_max_seq_sep(self, setting: int) -> None: ...
    @overload
    def set_max_seq_sep(self, unsignedlong) -> void: ...
    def setup_for_minimizing_for_residue_pair(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, minmap: pyrosetta.rosetta.core.kinematics.MinimizerMapBase, res1_data_cache: pyrosetta.rosetta.core.scoring.ResSingleMinimizationData, res2_data_cache: pyrosetta.rosetta.core.scoring.ResSingleMinimizationData, respair_data_cache: pyrosetta.rosetta.core.scoring.ResPairMinimizationData) -> None: ...
    def shortest_path(self) -> pyrosetta.rosetta.core.kinematics.ShortestPathInFoldTree: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, verbose_level: int, threshold: float) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, verbose_level: int) -> int: ...
    @overload
    def show_violations(self, out: pyrosetta.rosetta.std.ostream, verbose_level: int, threshold: float) -> int: ...
    @overload
    def show_violations(self, std, classcore, unsignedlong, double) -> unsignedlong: ...
    def too_far(self, pos1: int, pos2: int) -> bool: ...

class NamedAtomPairConstraintCreator(pyrosetta.rosetta.core.scoring.constraints.ConstraintCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: NamedAtomPairConstraintCreator) -> None: ...
    @overload
    def __init__(self, arg0: NamedAtomPairConstraintCreator) -> None: ...
    def assign(self) -> NamedAtomPairConstraintCreator: ...
    def create_constraint(self) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    def keyname(self) -> str: ...

class SequenceCoupling1BDConstraint(pyrosetta.rosetta.core.scoring.constraints.SequenceProfileConstraint):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, profile: pyrosetta.rosetta.core.sequence.SequenceProfile) -> None: ...
    @overload
    def __init__(self, profile: pyrosetta.rosetta.core.sequence.SequenceProfile) -> None: ...
    @overload
    def __init__(self, arg0: SequenceCoupling1BDConstraint) -> None: ...
    @overload
    def __init__(self, arg0: SequenceCoupling1BDConstraint) -> None: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    def fill_f1_f2(self) -> None: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def read_def(self) -> None: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.constraints.Constraint) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def score(self) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def type(self) -> str: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.constraints.Constraint) -> bool: ...

class SequenceCoupling1BDConstraintCreator(pyrosetta.rosetta.core.scoring.constraints.ConstraintCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SequenceCoupling1BDConstraintCreator) -> None: ...
    @overload
    def __init__(self, arg0: SequenceCoupling1BDConstraintCreator) -> None: ...
    def assign(self) -> SequenceCoupling1BDConstraintCreator: ...
    def create_constraint(self) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    def keyname(self) -> str: ...

class SequenceCouplingConstraint(pyrosetta.rosetta.core.scoring.constraints.Constraint):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, profile: pyrosetta.rosetta.core.sequence.SequenceCoupling) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, profile: pyrosetta.rosetta.core.sequence.SequenceCoupling) -> None: ...
    @overload
    def __init__(self, arg0: SequenceCouplingConstraint) -> None: ...
    @overload
    def __init__(self, arg0: SequenceCouplingConstraint) -> None: ...
    def atom(self) -> pyrosetta.rosetta.core.id.AtomID: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    @overload
    def dist(self) -> float: ...
    @overload
    def dist(self) -> float: ...
    @overload
    def dist(self, constclasscore) -> double: ...
    def fill_f1_f2(self) -> None: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def natoms(self) -> int: ...
    @overload
    def natoms(self) -> unsignedlong: ...
    def read_def(self) -> None: ...
    def residues(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.constraints.Constraint) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def score(self, pose: pyrosetta.rosetta.core.pose.Pose, weights: pyrosetta.rosetta.core.scoring.EMapVector) -> float: ...
    @overload
    def score(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def score(self) -> None: ...
    @overload
    def seqpos1(self) -> int: ...
    @overload
    def seqpos1(self) -> unsignedlong: ...
    @overload
    def seqpos2(self) -> int: ...
    @overload
    def seqpos2(self) -> unsignedlong: ...
    def sequence_coupling(self) -> pyrosetta.rosetta.core.sequence.SequenceCoupling: ...
    @overload
    def set_sequence_coupling(self) -> None: ...
    @overload
    def set_sequence_coupling(self, classstd) -> void: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def show_def(self) -> None: ...
    @overload
    def show_def(self, std, constclasscore) -> void: ...
    def type(self) -> str: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.constraints.Constraint) -> bool: ...

class SequenceCouplingConstraintCreator(pyrosetta.rosetta.core.scoring.constraints.ConstraintCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SequenceCouplingConstraintCreator) -> None: ...
    @overload
    def __init__(self, arg0: SequenceCouplingConstraintCreator) -> None: ...
    def assign(self) -> SequenceCouplingConstraintCreator: ...
    def create_constraint(self) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    def keyname(self) -> str: ...
