import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import overload

class CoupledMovesProtocol(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CoupledMovesProtocol) -> None: ...
    @overload
    def __init__(self, arg0: CoupledMovesProtocol) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> CoupledMovesProtocol: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def compute_ligand_score_bonus(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def compute_ligand_score_bonus(self, classstd) -> double: ...
    @overload
    def configure_score_fxn(self) -> None: ...
    @overload
    def configure_score_fxn(self) -> void: ...
    @overload
    def exclude_nonclashing_positions(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def exclude_nonclashing_positions(self, classstd) -> void: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_backbone_mover(self) -> str: ...
    def get_design_positions(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def get_ligand_mode(self) -> bool: ...
    @overload
    def get_ligand_mode(self) -> bool: ...
    @overload
    def get_ligand_prob(self) -> float: ...
    @overload
    def get_ligand_prob(self) -> double: ...
    def get_ligand_resnums(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def get_ligand_weight(self) -> float: ...
    @overload
    def get_ligand_weight(self) -> double: ...
    @overload
    def get_loop_size(self) -> int: ...
    @overload
    def get_loop_size(self) -> unsignedlong: ...
    def get_move_positions(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def get_move_type(self) -> str: ...
    def get_name(self) -> str: ...
    @overload
    def get_ntrials(self) -> int: ...
    @overload
    def get_ntrials(self) -> unsignedlong: ...
    @overload
    def get_number_ligands(self) -> int: ...
    @overload
    def get_number_ligands(self) -> unsignedlong: ...
    def get_perturber(self, *args, **kwargs): ...
    def get_repack_neighborhood(self) -> bool: ...
    def get_unique_sequences(self) -> pyrosetta.rosetta.std.map_std_string_double: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_backbone_mover(self, backbone_mover: str) -> None: ...
    @overload
    def set_backbone_mover(self, conststd) -> void: ...
    @overload
    def set_ligand_mode(self, ligand_mode: bool) -> None: ...
    @overload
    def set_ligand_mode(self, constbool) -> void: ...
    @overload
    def set_ligand_prob(self, ligand_prob: float) -> None: ...
    @overload
    def set_ligand_prob(self, constdouble) -> void: ...
    @overload
    def set_ligand_weight(self, ligand_weight: float) -> None: ...
    @overload
    def set_ligand_weight(self, constdouble) -> void: ...
    @overload
    def set_loop_size(self, loop_size: int) -> None: ...
    @overload
    def set_loop_size(self, unsignedlong) -> void: ...
    @overload
    def set_main_task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_main_task_factory(self, constclassstd) -> void: ...
    @overload
    def set_ntrials(self, ntrials: int) -> None: ...
    @overload
    def set_ntrials(self, unsignedlong) -> void: ...
    @overload
    def set_number_ligands(self, number_ligands: int) -> None: ...
    @overload
    def set_number_ligands(self, constunsignedlong) -> void: ...
    @overload
    def set_perturber(self, perturber) -> None: ...
    @overload
    def set_perturber(self, classstd) -> void: ...
    @overload
    def set_repack_neighborhood(self, repack_neighborhood: bool) -> None: ...
    @overload
    def set_repack_neighborhood(self, bool) -> void: ...
    @overload
    def set_score_fxn(self, sf: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_score_fxn(self, constclassstd) -> void: ...
    def setup_coupled_mover(self, *args, **kwargs): ...
    def setup_coupled_mover_for_ligand(self, *args, **kwargs): ...
    def setup_move_and_design_positions(self, task: pyrosetta.rosetta.core.pack.task.PackerTask, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def setup_move_type(self, move_prob: float) -> None: ...
    @overload
    def setup_move_type(self, constdouble) -> void: ...
    def setup_resnum(self, move_prob: float, coupled_mover, pose_copy: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def write_info_to_log(self, pose_copy: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def write_info_to_log(self, classstd) -> void: ...

class CoupledMovesProtocolCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CoupledMovesProtocolCreator) -> None: ...
    @overload
    def __init__(self, arg0: CoupledMovesProtocolCreator) -> None: ...
    def assign(self) -> CoupledMovesProtocolCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
