import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import ClassVar, overload

SCPA_cterm_isopeptide_lariat: SCPA_cyclization_type
SCPA_invalid_type: SCPA_cyclization_type
SCPA_lanthipeptide: SCPA_cyclization_type
SCPA_n_to_c_amide_bond: SCPA_cyclization_type
SCPA_nterm_isopeptide_lariat: SCPA_cyclization_type
SCPA_number_of_types: SCPA_cyclization_type
SCPA_sidechain_isopeptide: SCPA_cyclization_type
SCPA_terminal_disulfide: SCPA_cyclization_type
SCPA_thioether_lariat: SCPA_cyclization_type
SORT_BY_CIS_PEPTIDE_BONDS: HIERARCHICAL_HYBRID_JD_MPI_SORT_TYPE
SORT_BY_ENERGIES: HIERARCHICAL_HYBRID_JD_MPI_SORT_TYPE
SORT_BY_HBONDS: HIERARCHICAL_HYBRID_JD_MPI_SORT_TYPE
SORT_BY_RMSD: HIERARCHICAL_HYBRID_JD_MPI_SORT_TYPE

class HIERARCHICAL_HYBRID_JD_MPI_SORT_TYPE:
    __members__: ClassVar[dict] = ...  # read-only
    SORT_BY_CIS_PEPTIDE_BONDS: ClassVar[HIERARCHICAL_HYBRID_JD_MPI_SORT_TYPE] = ...
    SORT_BY_ENERGIES: ClassVar[HIERARCHICAL_HYBRID_JD_MPI_SORT_TYPE] = ...
    SORT_BY_HBONDS: ClassVar[HIERARCHICAL_HYBRID_JD_MPI_SORT_TYPE] = ...
    SORT_BY_RMSD: ClassVar[HIERARCHICAL_HYBRID_JD_MPI_SORT_TYPE] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class HierarchicalHybridJD_JobResultsSummary(HierarchicalHybridJD_ResultsSummaryBase):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: HierarchicalHybridJD_JobResultsSummary) -> None: ...
    @overload
    def __init__(self, arg0: HierarchicalHybridJD_JobResultsSummary) -> None: ...
    @overload
    def __init__(self, originating_node_MPI_rank: int, jobindex_on_originating_node: int, pose_energy: float, rmsd: float, hbonds: int, cis_peptide_bonds: int) -> None: ...
    def assign(self) -> HierarchicalHybridJD_JobResultsSummary: ...
    @overload
    def cis_peptide_bonds(self) -> int: ...
    @overload
    def cis_peptide_bonds(self) -> unsignedlong: ...
    def clone(self) -> HierarchicalHybridJD_ResultsSummaryBase: ...
    @overload
    def hbonds(self) -> int: ...
    @overload
    def hbonds(self) -> unsignedlong: ...
    def pose_energy(self) -> float: ...
    def rmsd(self) -> float: ...
    @overload
    def set_cis_peptide_bonds(self, val: int) -> None: ...
    @overload
    def set_cis_peptide_bonds(self, constunsignedlong) -> void: ...
    @overload
    def set_hbonds(self, val: int) -> None: ...
    @overload
    def set_hbonds(self, constunsignedlong) -> void: ...
    def set_pose_energy(self, val: float) -> None: ...
    def set_rmsd(self, val: float) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class HierarchicalHybridJD_PNearToArbitraryStateSummary:
    @overload
    def __init__(self, pnear: float, Keq: float, deltaG_folding: float, originating_mpi_node: int, jobindex_on_originating_node: int) -> None: ...
    @overload
    def __init__(self, arg0: HierarchicalHybridJD_PNearToArbitraryStateSummary) -> None: ...
    @overload
    def Keq(self) -> float: ...
    @overload
    def Keq(self) -> double: ...
    def assign(self) -> HierarchicalHybridJD_PNearToArbitraryStateSummary: ...
    def clone(self) -> HierarchicalHybridJD_PNearToArbitraryStateSummary: ...
    @overload
    def deltaG_folding(self) -> float: ...
    @overload
    def deltaG_folding(self) -> double: ...
    @overload
    def jobindex_on_originating_node(self) -> int: ...
    @overload
    def jobindex_on_originating_node(self) -> unsignedlong: ...
    @overload
    def originating_mpi_node(self) -> int: ...
    @overload
    def originating_mpi_node(self) -> unsignedlong: ...
    @overload
    def pnear(self) -> float: ...
    @overload
    def pnear(self) -> double: ...

class HierarchicalHybridJD_RMSDToBestSummary(HierarchicalHybridJD_ResultsSummaryBase):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, originating_node_MPI_rank: int, jobindex_on_originating_node: int, rmsd_to_best: float) -> None: ...
    @overload
    def __init__(self, arg0: HierarchicalHybridJD_RMSDToBestSummary) -> None: ...
    @overload
    def __init__(self, arg0: HierarchicalHybridJD_RMSDToBestSummary) -> None: ...
    def assign(self) -> HierarchicalHybridJD_RMSDToBestSummary: ...
    def clone(self) -> HierarchicalHybridJD_ResultsSummaryBase: ...
    def rmsd_to_best(self) -> float: ...
    def set_rmsd_to_best(self, setting: float) -> None: ...

class HierarchicalHybridJD_ResultsSummaryBase:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: HierarchicalHybridJD_ResultsSummaryBase) -> None: ...
    @overload
    def __init__(self, originating_node_MPI_rank: int, jobindex_on_originating_node: int) -> None: ...
    def MPI_ranks_handling_message(self) -> pyrosetta.rosetta.utility.vector1_int: ...
    @overload
    def add_MPI_rank_handling_message(self, new_proc: int) -> None: ...
    @overload
    def add_MPI_rank_handling_message(self, constint) -> void: ...
    def assign(self) -> HierarchicalHybridJD_ResultsSummaryBase: ...
    def clone(self) -> HierarchicalHybridJD_ResultsSummaryBase: ...
    @overload
    def jobindex_on_originating_node(self) -> int: ...
    @overload
    def jobindex_on_originating_node(self) -> unsignedlong: ...
    @overload
    def originating_node_MPI_rank(self) -> int: ...
    @overload
    def originating_node_MPI_rank(self) -> int: ...
    @overload
    def set_jobindex_on_originating_node(self, index: int) -> None: ...
    @overload
    def set_jobindex_on_originating_node(self, constunsignedlong) -> void: ...
    @overload
    def set_originating_node_MPI_rank(self, rank: int) -> None: ...
    @overload
    def set_originating_node_MPI_rank(self, constint) -> void: ...

class HierarchicalHybridJD_SASASummary(HierarchicalHybridJD_ResultsSummaryBase):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, originating_node_MPI_rank: int, jobindex_on_originating_node: int, sasa: float, polar_sasa: float, hydrophobic_sasa: float) -> None: ...
    @overload
    def __init__(self, arg0: HierarchicalHybridJD_SASASummary) -> None: ...
    @overload
    def __init__(self, arg0: HierarchicalHybridJD_SASASummary) -> None: ...
    def assign(self) -> HierarchicalHybridJD_SASASummary: ...
    def clone(self) -> HierarchicalHybridJD_ResultsSummaryBase: ...
    def fraction_hydrophobic_sasa(self) -> float: ...
    def fraction_polar_sasa(self) -> float: ...
    def hydrophobic_sasa(self) -> float: ...
    def polar_sasa(self) -> float: ...
    def sasa(self) -> float: ...
    def set(self, sasa: float, polar_sasa: float, hydrophobic_sasa: float) -> None: ...

class PNearCalculator:
    @overload
    def __init__(self, _lambda: float, kbt: float) -> None: ...
    @overload
    def __init__(self, arg0: PNearCalculator) -> None: ...
    def add_data_point(self, energy: float, rmsd: float) -> None: ...
    def assign(self) -> PNearCalculator: ...
    def clone(self) -> PNearCalculator: ...
    def compute_pnear_and_dgfolding(self, pnear: float, Keq: float, dgfolding: float) -> None: ...

class SCPA_cyclization_type:
    __members__: ClassVar[dict] = ...  # read-only
    SCPA_cterm_isopeptide_lariat: ClassVar[SCPA_cyclization_type] = ...
    SCPA_invalid_type: ClassVar[SCPA_cyclization_type] = ...
    SCPA_lanthipeptide: ClassVar[SCPA_cyclization_type] = ...
    SCPA_n_to_c_amide_bond: ClassVar[SCPA_cyclization_type] = ...
    SCPA_nterm_isopeptide_lariat: ClassVar[SCPA_cyclization_type] = ...
    SCPA_number_of_types: ClassVar[SCPA_cyclization_type] = ...
    SCPA_sidechain_isopeptide: ClassVar[SCPA_cyclization_type] = ...
    SCPA_terminal_disulfide: ClassVar[SCPA_cyclization_type] = ...
    SCPA_thioether_lariat: ClassVar[SCPA_cyclization_type] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class SimpleCycpepPredictApplication:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, allow_file_read: bool) -> None: ...
    @overload
    def __init__(self, arg0: SimpleCycpepPredictApplication) -> None: ...
    def add_entry_to_octahedral_metal_positions(self, res1: int, res2: int, res3: int, res4: int, res5: int, res6: int, metal_type: str) -> None: ...
    def add_entry_to_square_planar_metal_positions(self, res1: int, res2: int, res3: int, res4: int, metal_type: str) -> None: ...
    def add_entry_to_square_pyramidal_metal_positions(self, res1: int, res2: int, res3: int, res4: int, res5: int, metal_type: str) -> None: ...
    def add_entry_to_tetrahedral_metal_positions(self, res1: int, res2: int, res3: int, res4: int, metal_type: str) -> None: ...
    def add_entry_to_trigonal_planar_metal_positions(self, res1: int, res2: int, res3: int, metal_type: str) -> None: ...
    def add_entry_to_trigonal_pyramidal_metal_positions(self, res1: int, res2: int, res3: int, metal_type: str) -> None: ...
    @overload
    def align_and_calculate_rmsd(self, pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def align_and_calculate_rmsd(self, pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, skip_seq_comparison: bool) -> float: ...
    @overload
    def align_and_calculate_rmsd(self, classcore, constclasscore, constbool) -> double: ...
    def assign(self) -> SimpleCycpepPredictApplication: ...
    @overload
    def disable_cis_pro_sampling(self) -> None: ...
    @overload
    def disable_cis_pro_sampling(self) -> void: ...
    @overload
    def disable_total_energy_cutoff(self) -> None: ...
    @overload
    def disable_total_energy_cutoff(self) -> void: ...
    @staticmethod
    def get_cyclization_name_from_type(type: SCPA_cyclization_type) -> str: ...
    @staticmethod
    def get_cyclization_type_from_name(name: str) -> SCPA_cyclization_type: ...
    @overload
    def initialize_from_options(self) -> None: ...
    @overload
    def initialize_from_options(self) -> void: ...
    @overload
    @staticmethod
    def register_options() -> None: ...
    @overload
    @staticmethod
    def register_options() -> void: ...
    @overload
    def reset_octahedral_metal_positions(self) -> None: ...
    @overload
    def reset_octahedral_metal_positions(self) -> void: ...
    @overload
    def reset_square_planar_metal_positions(self) -> None: ...
    @overload
    def reset_square_planar_metal_positions(self) -> void: ...
    @overload
    def reset_square_pyramidal_metal_positions(self) -> None: ...
    @overload
    def reset_square_pyramidal_metal_positions(self) -> void: ...
    @overload
    def reset_tetrahedral_metal_positions(self) -> None: ...
    @overload
    def reset_tetrahedral_metal_positions(self) -> void: ...
    @overload
    def reset_trigonal_planar_metal_positions(self) -> None: ...
    @overload
    def reset_trigonal_planar_metal_positions(self) -> void: ...
    @overload
    def reset_trigonal_pyramidal_metal_positions(self) -> None: ...
    @overload
    def reset_trigonal_pyramidal_metal_positions(self) -> void: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def set_D_alpha_compfile_contents(self, contents_in: str) -> None: ...
    @overload
    def set_D_alpha_compfile_contents(self, conststd) -> void: ...
    @overload
    def set_D_beta_compfile_contents(self, contents_in: str) -> None: ...
    @overload
    def set_D_beta_compfile_contents(self, conststd) -> void: ...
    @overload
    def set_L_alpha_compfile_contents(self, contents_in: str) -> None: ...
    @overload
    def set_L_alpha_compfile_contents(self, conststd) -> void: ...
    @overload
    def set_L_beta_compfile_contents(self, contents_in: str) -> None: ...
    @overload
    def set_L_beta_compfile_contents(self, conststd) -> void: ...
    @overload
    def set_abba_bins_binfile(self, binfile_in: str) -> None: ...
    @overload
    def set_abba_bins_binfile(self, conststd) -> void: ...
    def set_allowed_residues_by_position(self, allowed_canonicals: pyrosetta.rosetta.std.map_unsigned_long_utility_vector1_std_string_t_std_allocator_std_pair_const_unsigned_long_utility_vector1_std_string_t, allowed_noncanonicals: pyrosetta.rosetta.std.map_unsigned_long_utility_vector1_std_string_t_std_allocator_std_pair_const_unsigned_long_utility_vector1_std_string_t) -> None: ...
    @overload
    def set_already_completed_job_count(self, count_in: int) -> None: ...
    @overload
    def set_already_completed_job_count(self, constunsignedlong) -> void: ...
    @overload
    def set_angle_length_relax_rounds(self, rounds_in: int) -> None: ...
    @overload
    def set_angle_length_relax_rounds(self, constunsignedlong) -> void: ...
    @overload
    def set_angle_relax_rounds(self, rounds_in: int) -> None: ...
    @overload
    def set_angle_relax_rounds(self, constunsignedlong) -> void: ...
    @overload
    def set_cartesian_relax_rounds(self, rounds_in: int) -> None: ...
    @overload
    def set_cartesian_relax_rounds(self, constunsignedlong) -> void: ...
    @overload
    def set_cyclization_type(self, type_in: SCPA_cyclization_type) -> None: ...
    @overload
    def set_cyclization_type(self, constenumprotocols) -> void: ...
    @overload
    def set_my_rank(self, rank_in: int) -> None: ...
    @overload
    def set_my_rank(self, constint) -> void: ...
    @overload
    def set_native(self, native: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_native(self, classstd) -> void: ...
    def set_nstruct(self, nstruct_in: int) -> None: ...
    @overload
    def set_octahedral_metal_positions_from_string_vector(self, vect: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_octahedral_metal_positions_from_string_vector(self, constclassutility) -> void: ...
    def set_sample_cis_pro_frequency(self, freq_in: float) -> None: ...
    @overload
    def set_scorefxn(self, sfxn_in: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn(self, classstd) -> void: ...
    @overload
    def set_sequence(self, seq: str) -> None: ...
    @overload
    def set_sequence(self, conststd) -> void: ...
    @overload
    def set_square_planar_metal_positions_from_string_vector(self, vect: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_square_planar_metal_positions_from_string_vector(self, constclassutility) -> void: ...
    @overload
    def set_square_pyramidal_metal_positions_from_string_vector(self, vect: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_square_pyramidal_metal_positions_from_string_vector(self, constclassutility) -> void: ...
    @overload
    def set_suppress_checkpoints(self, suppress_checkpoints: bool) -> None: ...
    @overload
    def set_suppress_checkpoints(self, constbool) -> void: ...
    @overload
    def set_tetrahedral_metal_positions_from_string_vector(self, vect: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_tetrahedral_metal_positions_from_string_vector(self, constclassutility) -> void: ...
    def set_total_energy_cutoff(self, value_in: float) -> None: ...
    @overload
    def set_trigonal_planar_metal_positions_from_string_vector(self, vect: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_trigonal_planar_metal_positions_from_string_vector(self, constclassutility) -> void: ...
    @overload
    def set_trigonal_pyramidal_metal_positions_from_string_vector(self, vect: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_trigonal_pyramidal_metal_positions_from_string_vector(self, constclassutility) -> void: ...
    @overload
    def set_use_chainbreak_energy(self, setting: bool) -> None: ...
    @overload
    def set_use_chainbreak_energy(self, constbool) -> void: ...
    @overload
    def set_use_rama_prepro_for_sampling(self, setting: bool) -> None: ...
    @overload
    def set_use_rama_prepro_for_sampling(self, constbool) -> void: ...

@overload
def is_canonical(resname: str) -> bool: ...
@overload
def is_canonical(conststd) -> bool: ...
@overload
def read_file_into_string(output_string: str, filename: str, from_database: bool) -> None: ...
@overload
def read_file_into_string(std, conststd, constbool) -> void: ...
def read_peptide_design_file(filename: str, allowed_canonicals_by_position: pyrosetta.rosetta.std.map_unsigned_long_utility_vector1_std_string_t_std_allocator_std_pair_const_unsigned_long_utility_vector1_std_string_t, allowed_noncanonicals_by_position: pyrosetta.rosetta.std.map_unsigned_long_utility_vector1_std_string_t_std_allocator_std_pair_const_unsigned_long_utility_vector1_std_string_t) -> None: ...
@overload
def register_with_citation_manager() -> None: ...
@overload
def register_with_citation_manager() -> void: ...
