import pyrosetta.rosetta.basic.citation_manager
import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.basic.tensorflow_manager
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.core.simple_metrics
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility.tag
from typing import overload

class EsmPerplexityTensorflowProtocol(pyrosetta.rosetta.basic.tensorflow_manager.RosettaTensorflowProtocolBase):
    model_name_: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: EsmPerplexityTensorflowProtocol) -> None: ...
    @overload
    def __init__(self, arg0: EsmPerplexityTensorflowProtocol) -> None: ...
    @overload
    def __init__(self, model: str) -> None: ...
    def assign(self) -> EsmPerplexityTensorflowProtocol: ...
    @overload
    def auto_download(self) -> bool: ...
    @overload
    def auto_download(self) -> bool: ...
    @overload
    def auto_download(self, setting: bool) -> None: ...
    @overload
    def auto_download(self, bool) -> void: ...
    def clone(self) -> pyrosetta.rosetta.basic.tensorflow_manager.RosettaTensorflowProtocolBase: ...
    @staticmethod
    def download_model_if_not_existing(path_to_model: str, base_url: str, auto_download: bool) -> None: ...
    @staticmethod
    def get_ESM_neural_net_citation() -> pyrosetta.rosetta.basic.citation_manager.CitationCollectionBase: ...
    def name(self) -> str: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...
    @staticmethod
    def softmax(logit_map: pyrosetta.rosetta.std.map_unsigned_long_utility_vector1_double_t_std_allocator_std_pair_const_unsigned_long_utility_vector1_double_t, softmax_map: pyrosetta.rosetta.std.map_unsigned_long_utility_vector1_double_t_std_allocator_std_pair_const_unsigned_long_utility_vector1_double_t) -> None: ...

class PerResidueEsmProbabilitiesMetric(pyrosetta.rosetta.core.simple_metrics.PerResidueProbabilitiesMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PerResidueEsmProbabilitiesMetric) -> None: ...
    @overload
    def __init__(self, arg0: PerResidueEsmProbabilitiesMetric) -> None: ...
    def assign(self) -> PerResidueEsmProbabilitiesMetric: ...
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def metric(self) -> str: ...
    def model(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self, citations: pyrosetta.rosetta.basic.citation_manager.CitationCollectionList) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def residue_selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_residue_selector(self, selector_in: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    @overload
    def set_residue_selector2(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector2(self, classstd) -> void: ...
    def write_pssm(self) -> str: ...

class PerResidueEsmProbabilitiesMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> PerResidueEsmProbabilitiesMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class PseudoPerplexityMetric(pyrosetta.rosetta.core.simple_metrics.RealMetric):
    cache_prefix_: str
    cache_suffix_: str
    fail_on_missing_cache_: bool
    metric_: pyrosetta.rosetta.core.simple_metrics.PerResidueProbabilitiesMetric
    use_cache_: bool
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, metric: pyrosetta.rosetta.core.simple_metrics.PerResidueProbabilitiesMetric) -> None: ...
    @overload
    def __init__(self, arg0: PseudoPerplexityMetric) -> None: ...
    @overload
    def __init__(self, arg0: PseudoPerplexityMetric) -> None: ...
    def assign(self) -> PseudoPerplexityMetric: ...
    @overload
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate(self, constclasscore) -> double: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    @staticmethod
    def compute_perplexity(pose: pyrosetta.rosetta.core.pose.Pose, values: pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t) -> float: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self, citations: pyrosetta.rosetta.basic.citation_manager.CitationCollectionList) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_fail_on_missing_cache(self, fail: bool) -> None: ...
    @overload
    def set_fail_on_missing_cache(self, bool) -> void: ...
    @overload
    def set_metric(self, metric: pyrosetta.rosetta.core.simple_metrics.PerResidueProbabilitiesMetric) -> None: ...
    @overload
    def set_metric(self, classstd) -> void: ...
    @overload
    def set_use_cached_data(self, use_cache: bool) -> None: ...
    @overload
    def set_use_cached_data(self, use_cache: bool, prefix: str) -> None: ...
    @overload
    def set_use_cached_data(self, use_cache: bool, prefix: str, suffix: str) -> None: ...

class PseudoPerplexityMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> PseudoPerplexityMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
