import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.factory
from typing import overload

class DiscreteRandomizer(EntityRandomizer):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DiscreteRandomizer) -> None: ...
    @overload
    def __init__(self, arg0: DiscreteRandomizer) -> None: ...
    @overload
    def add_choice(self, choice: EntityElement) -> None: ...
    @overload
    def add_choice(self, constclassstd) -> void: ...
    def assign(self) -> DiscreteRandomizer: ...
    def choices(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_genetic_algorithm_EntityElement_t: ...
    @overload
    def library_size(self) -> int: ...
    @overload
    def library_size(self) -> unsignedlong: ...
    @overload
    def mutate(self, entity: Entity) -> None: ...
    @overload
    def mutate(self, classprotocols) -> void: ...
    @overload
    def set_choices(self, choices: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_genetic_algorithm_EntityElement_t) -> None: ...
    @overload
    def set_choices(self, constclassutility) -> void: ...

class Entity:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Entity) -> None: ...
    @overload
    def __init__(self, arg0: Entity) -> None: ...
    @overload
    def __init__(self, line: str) -> None: ...
    def assign(self) -> Entity: ...
    def clone(self) -> Entity: ...
    @overload
    def fitness(self) -> float: ...
    @overload
    def fitness(self) -> double: ...
    @overload
    def fitness_valid(self) -> bool: ...
    @overload
    def fitness_valid(self) -> bool: ...
    @overload
    def read_checkpoint(self, _is: pyrosetta.rosetta.std.istream) -> bool: ...
    @overload
    def read_checkpoint(self, std) -> bool: ...
    @overload
    def set_entity_element(self, index: int, element: EntityElement) -> None: ...
    @overload
    def set_entity_element(self, unsignedlong, classstd) -> void: ...
    @overload
    def set_fitness(self, val: float) -> None: ...
    @overload
    def set_fitness(self, double) -> void: ...
    @overload
    def set_traits(self, traits: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_genetic_algorithm_EntityElement_t) -> None: ...
    @overload
    def set_traits(self, constclassutility) -> void: ...
    @overload
    def set_traits_size(self, size: int) -> None: ...
    @overload
    def set_traits_size(self, unsignedlong) -> void: ...
    @overload
    def show(self, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def to_string(self) -> str: ...
    def traits(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_genetic_algorithm_EntityElement_t: ...
    def traits_string(self) -> str: ...
    @overload
    def write_checkpoint(self, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def write_checkpoint(self, std) -> void: ...
    def __eq__(self, other: Entity) -> bool: ...

class EntityElement:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, index: int) -> None: ...
    @overload
    def __init__(self, word: str) -> None: ...
    @overload
    def __init__(self, arg0: EntityElement) -> None: ...
    def assign(self) -> EntityElement: ...
    def clone(self) -> EntityElement: ...
    def fresh_instance(self) -> EntityElement: ...
    @overload
    def hash(self) -> int: ...
    @overload
    def hash(self) -> unsignedlong: ...
    @overload
    def index(self) -> int: ...
    @overload
    def index(self) -> unsignedlong: ...
    @overload
    def index(self, index: int) -> None: ...
    @overload
    def index(self, unsignedlong) -> void: ...
    def name(self) -> str: ...
    def to_string(self) -> str: ...
    def __eq__(self, rhs: EntityElement) -> bool: ...

class EntityElementCreator:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: EntityElementCreator) -> None: ...
    def assign(self) -> EntityElementCreator: ...
    def new_entity(self, word: str) -> EntityElement: ...
    def widget_name(self) -> str: ...

class EntityElementFactory(pyrosetta.rosetta.utility.factory.WidgetFactory_protocols_genetic_algorithm_EntityElementCreator_t, pyrosetta.rosetta.utility.SingletonBase_protocols_genetic_algorithm_EntityElementFactory_t):
    def __init__(self, *args, **kwargs) -> None: ...
    def element_from_string(self) -> EntityElement: ...
    def factory_name(self) -> str: ...

class EntityElementsEqual:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: EntityElementsEqual) -> None: ...
    def assign(self) -> EntityElementsEqual: ...
    def __call__(self, elems1: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_genetic_algorithm_EntityElement_t, elems2: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_genetic_algorithm_EntityElement_t) -> bool: ...

class EntityRandomizer:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: EntityRandomizer) -> None: ...
    def assign(self) -> EntityRandomizer: ...
    def crossover(self, entity1: Entity, entity2: Entity) -> None: ...
    @overload
    def entity_length(self) -> int: ...
    @overload
    def entity_length(self) -> unsignedlong: ...
    def entity_template(self) -> Entity: ...
    @overload
    def library_size(self) -> int: ...
    @overload
    def library_size(self) -> unsignedlong: ...
    @overload
    def mutate(self, entity: Entity) -> None: ...
    @overload
    def mutate(self, classprotocols) -> void: ...
    @overload
    def mutation_rate(self) -> float: ...
    @overload
    def mutation_rate(self) -> double: ...
    def random_entity(self) -> Entity: ...
    @overload
    def set_entity_template(self, entity: Entity) -> None: ...
    @overload
    def set_entity_template(self, classstd) -> void: ...
    @overload
    def set_mutation_rate(self, rate: float) -> None: ...
    @overload
    def set_mutation_rate(self, double) -> void: ...

class FitnessFunction:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FitnessFunction) -> None: ...
    def assign(self) -> FitnessFunction: ...
    @overload
    def evaluate(self, entity: Entity) -> float: ...
    @overload
    def evaluate(self, classprotocols) -> double: ...

class GeneticAlgorithm(GeneticAlgorithmBase):
    fitness_function_: FitnessFunction
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GeneticAlgorithm) -> None: ...
    @overload
    def __init__(self, arg0: GeneticAlgorithm) -> None: ...
    def assign(self) -> GeneticAlgorithm: ...
    @overload
    def evaluate_fitnesses(self) -> None: ...
    @overload
    def evaluate_fitnesses(self) -> void: ...
    @overload
    def set_func(self, f: FitnessFunction) -> None: ...
    @overload
    def set_func(self, classstd) -> void: ...

class GeneticAlgorithmBase:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GeneticAlgorithmBase) -> None: ...
    @overload
    def __init__(self, arg0: GeneticAlgorithmBase) -> None: ...
    @overload
    def add_entity(self, traits: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_genetic_algorithm_EntityElement_t) -> Entity: ...
    @overload
    def add_entity(self, entity: Entity) -> Entity: ...
    @overload
    def add_parent_entity(self, traits: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_genetic_algorithm_EntityElement_t) -> Entity: ...
    @overload
    def add_parent_entity(self, entity: Entity) -> Entity: ...
    @overload
    def add_parents_from_current_generation(self) -> None: ...
    @overload
    def add_parents_from_current_generation(self) -> void: ...
    def assign(self) -> GeneticAlgorithmBase: ...
    @overload
    def best_fitness_from_current_generation(self) -> float: ...
    @overload
    def best_fitness_from_current_generation(self) -> double: ...
    @overload
    def clear_parents(self) -> None: ...
    @overload
    def clear_parents(self) -> void: ...
    @overload
    def complete(self) -> bool: ...
    @overload
    def complete(self) -> bool: ...
    def curr_gen_entity(self, index: int) -> Entity: ...
    @overload
    def current_generation(self) -> int: ...
    @overload
    def current_generation(self) -> unsignedlong: ...
    @overload
    def current_generation_complete(self) -> bool: ...
    @overload
    def current_generation_complete(self) -> bool: ...
    @overload
    def entities_checkpoint_filename(self) -> str: ...
    @overload
    def entities_checkpoint_filename(self, suffix: str) -> str: ...
    def entity_template(self) -> Entity: ...
    @overload
    def evolve_next_generation(self) -> None: ...
    @overload
    def evolve_next_generation(self) -> void: ...
    @overload
    def fill_by_crossover(self) -> None: ...
    @overload
    def fill_by_crossover(self, size: int) -> None: ...
    @overload
    def fill_by_crossover(self, unsignedlong) -> void: ...
    @overload
    def fill_by_mutation(self) -> None: ...
    @overload
    def fill_by_mutation(self, size: int) -> None: ...
    @overload
    def fill_by_mutation(self, unsignedlong) -> void: ...
    @overload
    def fill_with_perturbations_of_existing_entities(self) -> None: ...
    @overload
    def fill_with_perturbations_of_existing_entities(self, size: int) -> None: ...
    @overload
    def fill_with_perturbations_of_existing_entities(self, unsignedlong) -> void: ...
    @overload
    def fill_with_random_entities(self) -> None: ...
    @overload
    def fill_with_random_entities(self, size: int) -> None: ...
    @overload
    def fill_with_random_entities(self, unsignedlong) -> void: ...
    @overload
    def fraction_by_recombination(self) -> float: ...
    @overload
    def fraction_by_recombination(self) -> double: ...
    def generations(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_std_shared_ptr_protocols_genetic_algorithm_Entity_t: ...
    @overload
    def generations_checkpoint_filename(self) -> str: ...
    @overload
    def generations_checkpoint_filename(self, suffix: str) -> str: ...
    @overload
    def max_generations(self) -> int: ...
    @overload
    def max_generations(self) -> unsignedlong: ...
    @overload
    def max_population_size(self) -> int: ...
    @overload
    def max_population_size(self) -> unsignedlong: ...
    def new_entity(self) -> Entity: ...
    @overload
    def number_to_propagate(self) -> int: ...
    @overload
    def number_to_propagate(self) -> unsignedlong: ...
    def population(self, gen_num: int) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_protocols_genetic_algorithm_Entity_t: ...
    @overload
    def print_cache(self) -> None: ...
    @overload
    def print_cache(self, std) -> void: ...
    @overload
    def print_generation_statistics(self, os: pyrosetta.rosetta.std.ostream, gen_num: int) -> None: ...
    @overload
    def print_generation_statistics(self, std, unsignedlong) -> void: ...
    @overload
    def print_population(self) -> None: ...
    @overload
    def print_population(self, std) -> void: ...
    @overload
    def propagate_best_from_previous_generation(self) -> None: ...
    @overload
    def propagate_best_from_previous_generation(self, size: int) -> None: ...
    @overload
    def propagate_best_from_previous_generation(self, size: int, unique: bool) -> None: ...
    @overload
    def propagate_best_from_previous_generation(self, unsignedlong, bool) -> void: ...
    @overload
    def read_checkpoint(self) -> bool: ...
    @overload
    def read_checkpoint(self) -> bool: ...
    @overload
    def read_entities_checkpoint(self) -> bool: ...
    @overload
    def read_entities_checkpoint(self, overwrite: bool) -> bool: ...
    @overload
    def read_entities_checkpoint(self, bool) -> bool: ...
    @overload
    def read_generations_checkpoint(self) -> bool: ...
    @overload
    def read_generations_checkpoint(self) -> bool: ...
    @overload
    def rename_checkpoint_files(self) -> None: ...
    @overload
    def rename_checkpoint_files(self) -> void: ...
    @overload
    def set_checkpoint_gzip(self, b: bool) -> None: ...
    @overload
    def set_checkpoint_gzip(self, bool) -> void: ...
    @overload
    def set_checkpoint_prefix(self, p: str) -> None: ...
    @overload
    def set_checkpoint_prefix(self, conststd) -> void: ...
    @overload
    def set_checkpoint_rename(self, b: bool) -> None: ...
    @overload
    def set_checkpoint_rename(self, bool) -> void: ...
    @overload
    def set_checkpoint_write_interval(self, i: int) -> None: ...
    @overload
    def set_checkpoint_write_interval(self, unsignedlong) -> void: ...
    @overload
    def set_entity_template(self, entity: Entity) -> None: ...
    @overload
    def set_entity_template(self, classstd) -> void: ...
    @overload
    def set_frac_by_recomb(self, f: float) -> None: ...
    @overload
    def set_frac_by_recomb(self, double) -> void: ...
    @overload
    def set_max_generations(self, s: int) -> None: ...
    @overload
    def set_max_generations(self, unsignedlong) -> void: ...
    @overload
    def set_max_pop_size(self, s: int) -> None: ...
    @overload
    def set_max_pop_size(self, unsignedlong) -> void: ...
    @overload
    def set_num_to_propagate(self, s: int) -> None: ...
    @overload
    def set_num_to_propagate(self, unsignedlong) -> void: ...
    @overload
    def set_rand(self, r: EntityRandomizer) -> None: ...
    @overload
    def set_rand(self, classstd) -> void: ...
    def tournament_select(self, pvec: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_protocols_genetic_algorithm_Entity_t) -> Entity: ...
    @overload
    def write_entities_checkpoint(self) -> bool: ...
    @overload
    def write_entities_checkpoint(self) -> bool: ...
    @overload
    def write_generations_checkpoint(self) -> bool: ...
    @overload
    def write_generations_checkpoint(self) -> bool: ...

class Mutate1Randomizer(PositionSpecificRandomizer):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Mutate1Randomizer) -> None: ...
    @overload
    def __init__(self, arg0: Mutate1Randomizer) -> None: ...
    def assign(self) -> Mutate1Randomizer: ...
    @overload
    def mutate(self, entity: Entity) -> None: ...
    @overload
    def mutate(self, classprotocols) -> void: ...

class PositionSpecificRandomizer(EntityRandomizer):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PositionSpecificRandomizer) -> None: ...
    @overload
    def __init__(self, arg0: PositionSpecificRandomizer) -> None: ...
    @overload
    def append_choices(self, choices: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_genetic_algorithm_EntityElement_t) -> None: ...
    @overload
    def append_choices(self, constclassutility) -> void: ...
    def assign(self) -> PositionSpecificRandomizer: ...
    def choices(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_std_shared_ptr_protocols_genetic_algorithm_EntityElement_t: ...
    @overload
    def library_size(self) -> int: ...
    @overload
    def library_size(self) -> unsignedlong: ...
    @overload
    def mutate(self, entity: Entity) -> None: ...
    @overload
    def mutate(self, classprotocols) -> void: ...

class Vec1Hash:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Vec1Hash) -> None: ...
    def assign(self) -> Vec1Hash: ...
    def __call__(self, vec1: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_genetic_algorithm_EntityElement_t) -> int: ...
