import pyrosetta.rosetta.ObjexxFCL
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.fragment
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring.dssp
import pyrosetta.rosetta.core.scoring.func
import pyrosetta.rosetta.protocols.checkpoint
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import ClassVar, overload

angleA: cstType
angleB: cstType
cstJump: dofType
dihedralA: cstType
dihedralAB: cstType
dihedralB: cstType
disAB: cstType
num_cstType: cstType
num_dofType: dofType
rot1: dofType
rot2: dofType

class BaseDisulfPairingLibrary:
    @overload
    def __init__(self, arg0: BaseDisulfPairingLibrary) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def assign(self) -> BaseDisulfPairingLibrary: ...

class BaseJumpSetup:
    @overload
    def __init__(self, arg0: BaseJumpSetup) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def assign(self) -> BaseJumpSetup: ...
    def clean_jumps(self) -> JumpSample: ...
    def create_jump_sample(self) -> JumpSample: ...
    def generate_jump_frags(self, mm: pyrosetta.rosetta.core.kinematics.MoveMap) -> pyrosetta.rosetta.core.fragment.FragSet: ...
    def type_name(self) -> str: ...

class BasePairingLibrary:
    @overload
    def __init__(self, arg0: BasePairingLibrary) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def assign(self) -> BasePairingLibrary: ...
    def create_jump_fragments(self, orientation: int, pleating: int, bWithTorsion: bool) -> None: ...
    @overload
    def generate_jump_frags(self, pairings: pyrosetta.rosetta.utility.vector1_core_scoring_dssp_Pairing, mm: pyrosetta.rosetta.core.kinematics.MoveMap, bWithTorsion: bool, frags_accumulator: pyrosetta.rosetta.core.fragment.FragSet) -> None: ...
    @overload
    def generate_jump_frags(self, constclassutility, constclasscore, bool, classcore) -> void: ...

class ChainbreakDistFunc(pyrosetta.rosetta.core.scoring.func.Func):
    @overload
    def __init__(self, x0_in: float) -> None: ...
    @overload
    def __init__(self, arg0: ChainbreakDistFunc) -> None: ...
    @overload
    def __init__(self, arg0: ChainbreakDistFunc) -> None: ...
    def assign(self) -> ChainbreakDistFunc: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.func.Func: ...
    @overload
    def dfunc(self, x: float) -> float: ...
    @overload
    def dfunc(self, constdouble) -> double: ...
    @overload
    def func(self, x: float) -> float: ...
    @overload
    def func(self, constdouble) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore) -> bool: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def __eq__(self, other: pyrosetta.rosetta.core.scoring.func.Func) -> bool: ...

class DisulfPairing:
    pos1: int
    pos2: int
    seq_sep: int
    ss_type: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pos1_in: int, pos2_in: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pos1_in: int, pos2_in: int, ori_in: int, pleat_in: int) -> None: ...
    @overload
    def __init__(self, arg0: DisulfPairing) -> None: ...
    def __eq__(self, p: DisulfPairing) -> bool: ...

class DisulfPairingLibrary(BaseDisulfPairingLibrary):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DisulfPairingLibrary) -> None: ...
    def assign(self) -> DisulfPairingLibrary: ...
    @overload
    def create_jump_fragments(self, bWithTorsion: bool, frags: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_fragment_FragData_t) -> None: ...
    @overload
    def create_jump_fragments(self, bool, classutility) -> void: ...
    @overload
    def generate_jump_frags(self, pairings: pyrosetta.rosetta.utility.vector1_protocols_jumping_DisulfPairing, mm: pyrosetta.rosetta.core.kinematics.MoveMap, bWithTorsion: bool, frags_accumulator: pyrosetta.rosetta.core.fragment.FragSet) -> None: ...
    @overload
    def generate_jump_frags(self, constclassutility, constclasscore, bool, classcore) -> void: ...
    @overload
    def read_from_file(self, fn: str) -> None: ...
    @overload
    def read_from_file(self, conststd) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...

class DisulfTemplate:
    atoms_downstream_: pyrosetta.rosetta.utility.vector1_std_string
    atoms_upstream_: pyrosetta.rosetta.utility.vector1_std_string
    omega: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t
    phi: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t
    psi: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t
    rt_: pyrosetta.rosetta.core.kinematics.RT
    secstruct: pyrosetta.rosetta.ObjexxFCL.FArray1D_char_t
    @overload
    def __init__(self, c: str, s1: str, s2: str, s3: str) -> None: ...
    @overload
    def __init__(self, s1: str, s2: str, s3: str) -> None: ...
    @overload
    def __init__(self, arg0: DisulfTemplate) -> None: ...
    def assign(self) -> DisulfTemplate: ...

class Interval:
    end_: int
    start_: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, start: int, end: int) -> None: ...
    @overload
    def __init__(self, arg0: Interval) -> None: ...
    @overload
    def end(self) -> int: ...
    @overload
    def end(self) -> unsignedlong: ...
    @overload
    def start(self) -> int: ...
    @overload
    def start(self) -> unsignedlong: ...
    @overload
    def stop(self) -> int: ...
    @overload
    def stop(self) -> unsignedlong: ...

class JumpSample:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, total_residue: int, njump: int, jumps: pyrosetta.rosetta.ObjexxFCL.FArray2D_int_t, cuts: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t) -> None: ...
    @overload
    def __init__(self, total_residue: int, njump: int, jumps: pyrosetta.rosetta.ObjexxFCL.FArray2D_int_t, cuts: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, root: int) -> None: ...
    @overload
    def __init__(self, total_residue: int, njump: int, jumps: pyrosetta.rosetta.ObjexxFCL.FArray2D_int_t, jump_atoms: pyrosetta.rosetta.ObjexxFCL.FArray2D_std_string_t, cuts: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t) -> None: ...
    @overload
    def __init__(self, total_residue: int, njump: int, jumps: pyrosetta.rosetta.ObjexxFCL.FArray2D_int_t, jump_atoms: pyrosetta.rosetta.ObjexxFCL.FArray2D_std_string_t, cuts: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, root: int) -> None: ...
    @overload
    def __init__(self, total_residue: int, jumps: pyrosetta.rosetta.utility.vector1_core_scoring_dssp_Pairing, cut_probability: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    @overload
    def __init__(self, total_residue: int, jumps: pyrosetta.rosetta.utility.vector1_core_scoring_dssp_Pairing, cut_probability: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t, root: int) -> None: ...
    @overload
    def __init__(self, total_residue: int, jumps: pyrosetta.rosetta.utility.vector1_core_scoring_dssp_Pairing, ss_def: pyrosetta.rosetta.core.fragment.SecondaryStructure) -> None: ...
    @overload
    def __init__(self, total_residue: int, jumps: pyrosetta.rosetta.utility.vector1_core_scoring_dssp_Pairing, ss_def: pyrosetta.rosetta.core.fragment.SecondaryStructure, root: int) -> None: ...
    @overload
    def __init__(self, f: pyrosetta.rosetta.core.kinematics.FoldTree) -> None: ...
    @overload
    def __init__(self, f: pyrosetta.rosetta.core.kinematics.FoldTree) -> None: ...
    @overload
    def __init__(self, arg0: JumpSample) -> None: ...
    @overload
    def add_chainbreaks(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def add_chainbreaks(self, classcore) -> void: ...
    @overload
    def add_chainbreaks(self, pose: pyrosetta.rosetta.core.pose.Pose, max_dist: int) -> None: ...
    @overload
    def add_chainbreaks(self, classcore, unsignedlong, constclasscore) -> void: ...
    @overload
    def add_chainbreaks_as_distance_constraint(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def add_chainbreaks_as_distance_constraint(self, classcore) -> void: ...
    @overload
    def add_chainbreaks_as_distance_constraint(self, pose: pyrosetta.rosetta.core.pose.Pose, max_dist: int, sp: pyrosetta.rosetta.core.kinematics.ShortestPathInFoldTree) -> None: ...
    @overload
    def add_chainbreaks_as_distance_constraint(self, classcore, unsignedlong, constclasscore) -> void: ...
    def assign(self) -> JumpSample: ...
    def cuts(self) -> pyrosetta.rosetta.ObjexxFCL.FArray1D_unsigned_long_t: ...
    @overload
    def downstream_res_nr(self, jump_nr: int) -> int: ...
    @overload
    def downstream_res_nr(self, unsignedlong) -> unsignedlong: ...
    @overload
    def dump_pymol(self, fn: str) -> None: ...
    @overload
    def dump_pymol(self, std) -> void: ...
    def fold_tree(self) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    @overload
    def generate_jump_frags(self, pairings, bWithTorsion: bool) -> None: ...
    @overload
    def generate_jump_frags(self, constclassprotocols, constclasscore, bool, classcore) -> void: ...
    @overload
    def generate_jump_frames(self) -> None: ...
    @overload
    def generate_jump_frames(self, bWithTorsion: bool) -> None: ...
    @overload
    def generate_jump_frames(self, classcore, constclasscore, bool) -> void: ...
    def get_pairing(self, res1: int, res2: int) -> pyrosetta.rosetta.core.scoring.dssp.Pairing: ...
    @overload
    def has_orientation_and_pleating(self) -> bool: ...
    @overload
    def has_orientation_and_pleating(self) -> bool: ...
    @overload
    def is_valid(self) -> bool: ...
    @overload
    def is_valid(self) -> bool: ...
    def jump_atoms(self) -> pyrosetta.rosetta.ObjexxFCL.FArray2D_std_string_t: ...
    def jumps(self) -> pyrosetta.rosetta.ObjexxFCL.FArray2D_unsigned_long_t: ...
    @overload
    def remove_chainbreaks(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def remove_chainbreaks(self, classcore) -> void: ...
    @overload
    def resize(self, njump: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def safe_secstruct(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def safe_secstruct(self, classcore) -> void: ...
    @overload
    def set_fold_tree_and_chainbreaks(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_fold_tree_and_chainbreaks(self, classcore) -> void: ...
    @overload
    def set_fold_tree_in_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_fold_tree_in_pose(self, classcore) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def steal_jumps(self, native_pose: pyrosetta.rosetta.core.pose.Pose, begin: pyrosetta.rosetta.core.fragment.FrameIterator, end: pyrosetta.rosetta.core.fragment.FrameIterator) -> None: ...
    @overload
    def steal_orientation_and_pleating(self, native_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def steal_orientation_and_pleating(self, classcore) -> void: ...
    @overload
    def total_residue(self) -> int: ...
    @overload
    def total_residue(self) -> unsignedlong: ...
    def transfer_jumps(self, pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...

class JumpSelector(BaseJumpSetup):
    class JumpWeightDef:
        jump_: Interval
        weight_: float
        @overload
        def __init__(self, jump: Interval, weight: float) -> None: ...
        @overload
        def __init__(self, arg0: JumpSelector.JumpWeightDef) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ss: str) -> None: ...
    @overload
    def __init__(self, arg0: JumpSelector) -> None: ...
    @overload
    def __init__(self, arg0: JumpSelector) -> None: ...
    @overload
    def add_jump(self, jd) -> None: ...
    @overload
    def add_jump(self, constclassprotocols) -> void: ...
    @overload
    def add_jump(self, jump: Interval, weight: float) -> None: ...
    @overload
    def add_jump(self, constclassprotocols, double) -> void: ...
    @overload
    def add_jump(self, js: int, je: int, weight: float) -> None: ...
    def assign(self) -> JumpSelector: ...
    def clean_jumps(self, js: JumpSample) -> JumpSample: ...
    def create_jump_sample(self) -> JumpSample: ...
    @overload
    def read_file(self, file: str) -> None: ...
    @overload
    def read_file(self, std) -> void: ...
    def select_random(self) -> Interval: ...
    @overload
    def set_secstruct(self, ss: str) -> None: ...
    @overload
    def set_secstruct(self, std) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def type_name(self) -> str: ...

class JumpSetup(BaseJumpSetup):
    class JumpDef:
        cut_reg_: Interval
        jump_: Interval
        @overload
        def __init__(self, jump: Interval, cut_reg: Interval) -> None: ...
        @overload
        def __init__(self, arg0: JumpSetup.JumpDef) -> None: ...
    @overload
    def __init__(self, total_residue: int) -> None: ...
    @overload
    def __init__(self, arg0: JumpSetup) -> None: ...
    @overload
    def __init__(self, arg0: JumpSetup) -> None: ...
    @overload
    def add_jump(self, jd) -> None: ...
    @overload
    def add_jump(self, constclassprotocols) -> void: ...
    @overload
    def add_jump(self, jump: Interval, cut_reg: Interval) -> None: ...
    @overload
    def add_jump(self, js: int, je: int, crs: int, cre: int) -> None: ...
    def assign(self) -> JumpSetup: ...
    def clean_jumps(self, js: JumpSample) -> JumpSample: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    def create_jump_sample(self) -> JumpSample: ...
    @overload
    def read_file(self, file: str) -> None: ...
    @overload
    def read_file(self, std) -> void: ...
    @overload
    def set_jump_sample(self, jump_sample: JumpSample) -> None: ...
    @overload
    def set_jump_sample(self, constclassprotocols) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def total_residue(self) -> int: ...
    @overload
    def total_residue(self) -> unsignedlong: ...
    def type_name(self) -> str: ...

class JumpsFromAllPairings(BaseJumpSetup):
    @overload
    def __init__(self, total_residue: int, jumps: pyrosetta.rosetta.utility.vector1_core_scoring_dssp_Pairing, cut_probability: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    @overload
    def __init__(self, arg0: JumpsFromAllPairings) -> None: ...
    def assign(self) -> JumpsFromAllPairings: ...
    def create_jump_sample(self) -> JumpSample: ...

class MembraneJump:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MembraneJump) -> None: ...
    def assign(self) -> MembraneJump: ...
    @overload
    def defined(self) -> bool: ...
    @overload
    def defined(self) -> bool: ...
    def init(self, template_file: str, pairings_file: str) -> None: ...
    @overload
    def pairings_size(self) -> int: ...
    @overload
    def pairings_size(self) -> unsignedlong: ...
    @overload
    def rt_templates(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def rt_templates(self, classcore) -> void: ...
    @overload
    def setup_fold_tree(self, pose: pyrosetta.rosetta.core.pose.Pose, njumps: int) -> None: ...
    @overload
    def setup_fold_tree(self, classcore, unsignedlong) -> void: ...
    @overload
    def template_size(self) -> int: ...
    @overload
    def template_size(self) -> unsignedlong: ...

class PairingLibrary(BasePairingLibrary):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PairingLibrary) -> None: ...
    @overload
    def __init__(self, arg0: PairingLibrary) -> None: ...
    def assign(self) -> PairingLibrary: ...
    def create_jump_fragments(self, orientation: int, pleating: int, bWithTorsion: bool) -> None: ...
    @overload
    def generate_jump_frags(self, pairings: pyrosetta.rosetta.utility.vector1_core_scoring_dssp_Pairing, mm: pyrosetta.rosetta.core.kinematics.MoveMap, bWithTorsion: bool, frags_accumulator: pyrosetta.rosetta.core.fragment.FragSet) -> None: ...
    @overload
    def generate_jump_frags(self, constclassutility, constclasscore, bool, classcore) -> void: ...
    def get_random_beta_sheet_jump(self, orientation: int, pleating: int) -> pyrosetta.rosetta.core.kinematics.RT: ...
    def get_random_tmh_jump(self, orientation: int, pos1: int, pos2: int) -> pyrosetta.rosetta.core.kinematics.RT: ...
    @overload
    def read_from_file(self, fn: str) -> None: ...
    @overload
    def read_from_file(self, conststd) -> void: ...
    @overload
    def read_from_file_no_filters(self, fn: str) -> None: ...
    @overload
    def read_from_file_no_filters(self, conststd) -> void: ...
    def set_tmh_jump(self, pose: pyrosetta.rosetta.core.pose.Pose, jump_number: int, orientation: int, pos1: int, pos2: int) -> None: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...

class PairingTemplate:
    atoms_downstream_: pyrosetta.rosetta.utility.vector1_std_string
    atoms_upstream_: pyrosetta.rosetta.utility.vector1_std_string
    omega: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t
    phi: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t
    psi: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t
    rt_: pyrosetta.rosetta.core.kinematics.RT
    secstruct: pyrosetta.rosetta.ObjexxFCL.FArray1D_char_t
    @overload
    def __init__(self, c: str, s1: str, s2: str, s3: str) -> None: ...
    @overload
    def __init__(self, s1: str, s2: str, s3: str) -> None: ...
    @overload
    def __init__(self, arg0: PairingTemplate) -> None: ...
    def assign(self) -> PairingTemplate: ...

class RandomSheetBuilder(SheetBuilder):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RandomSheetBuilder) -> None: ...
    @overload
    def __init__(self, arg0: RandomSheetBuilder) -> None: ...
    def assign(self) -> RandomSheetBuilder: ...

class ResiduePairJump:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, residue1: pyrosetta.rosetta.core.chemical.ResidueType, residue2: pyrosetta.rosetta.core.chemical.ResidueType) -> None: ...
    @overload
    def __init__(self, arg0: ResiduePairJump) -> None: ...
    def add_residue_pair(self, residue1: pyrosetta.rosetta.core.chemical.ResidueType, residue2: pyrosetta.rosetta.core.chemical.ResidueType) -> None: ...
    @overload
    def add_residue_single(self, residue: pyrosetta.rosetta.core.chemical.ResidueType) -> None: ...
    @overload
    def add_residue_single(self, constclasscore) -> void: ...
    def assign(self) -> ResiduePairJump: ...
    @overload
    def build_cst_conformer_jumps(self) -> None: ...
    @overload
    def build_cst_conformer_jumps(self) -> void: ...
    @overload
    def build_sidechain_rotamers(self) -> None: ...
    @overload
    def build_sidechain_rotamers(self) -> void: ...
    def cstAtoms(self, i: int) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def cstAtoms_defined(self) -> bool: ...
    @overload
    def cstAtoms_defined(self) -> bool: ...
    @overload
    def cstInfoMap_defined(self) -> bool: ...
    @overload
    def cstInfoMap_defined(self) -> bool: ...
    @overload
    def diversify_cst_conformers(self, type: cstType, max_index: int) -> None: ...
    @overload
    def diversify_cst_conformers(self, enumprotocols, unsignedlong) -> void: ...
    @overload
    def diversify_cst_conformers(self) -> None: ...
    @overload
    def diversify_cst_conformers(self) -> void: ...
    @overload
    def diversify_dof_conformers(self, type: dofType, max_index: int) -> None: ...
    @overload
    def diversify_dof_conformers(self, enumprotocols, unsignedlong) -> void: ...
    @overload
    def diversify_dof_conformers(self) -> None: ...
    @overload
    def diversify_dof_conformers(self) -> void: ...
    def generate_frame(self) -> pyrosetta.rosetta.core.fragment.Frame: ...
    @overload
    def init_mini_pose(self) -> None: ...
    @overload
    def init_mini_pose(self) -> void: ...
    def jumpAtoms(self, i: int) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def jumpAtoms_defined(self) -> bool: ...
    @overload
    def jumpAtoms_defined(self) -> bool: ...
    def set_cstAtoms(self, rsd: int, atom: int, name: str) -> None: ...
    @overload
    def set_cstInfo(self, type: cstType, value: float) -> None: ...
    @overload
    def set_cstInfo(self, enumprotocols, double) -> void: ...
    @overload
    def set_cstInfo(self, type: cstType, values: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_cstInfo(self, enumprotocols, constclassutility) -> void: ...
    def set_jumpAtoms(self, rsd: int, atom: int, name: str) -> None: ...

class ResiduePairJumpSetup(BaseJumpSetup):
    class JumpDef:
        cut_reg_: Interval
        jump_: Interval
        @overload
        def __init__(self, jump: Interval, cut_reg: Interval) -> None: ...
        @overload
        def __init__(self, arg0: ResiduePairJumpSetup.JumpDef) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, total_residue: int) -> None: ...
    @overload
    def __init__(self, arg0: ResiduePairJumpSetup) -> None: ...
    @overload
    def __init__(self, arg0: ResiduePairJumpSetup) -> None: ...
    @overload
    def add_jump(self, jd) -> None: ...
    @overload
    def add_jump(self, constclassprotocols) -> void: ...
    @overload
    def add_jump(self, jump: Interval, cut_reg: Interval) -> None: ...
    @overload
    def add_jump(self, js: int, je: int, crs: int, cre: int) -> None: ...
    @overload
    def add_residue_pair_jump(self, ptr: ResiduePairJump) -> None: ...
    @overload
    def add_residue_pair_jump(self, classstd) -> void: ...
    def assign(self) -> ResiduePairJumpSetup: ...
    def clean_jumps(self, js: JumpSample) -> JumpSample: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    def create_jump_sample(self) -> JumpSample: ...
    def generate_jump_frags(self, mm: pyrosetta.rosetta.core.kinematics.MoveMap) -> pyrosetta.rosetta.core.fragment.FragSet: ...
    @overload
    def read_file(self, file: str) -> None: ...
    @overload
    def read_file(self, std) -> void: ...
    @overload
    def root(self) -> int: ...
    @overload
    def root(self) -> unsignedlong: ...
    @overload
    def set_root(self, root: int) -> None: ...
    @overload
    def set_root(self, unsignedlong) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def total_residue(self) -> int: ...
    @overload
    def total_residue(self) -> unsignedlong: ...
    def type_name(self) -> str: ...

class ResiduePairJumpSingle:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, residue_type: pyrosetta.rosetta.core.chemical.ResidueType) -> None: ...
    @overload
    def __init__(self, arg0: ResiduePairJumpSingle) -> None: ...
    def assign(self) -> ResiduePairJumpSingle: ...
    @overload
    def cstAtoms(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def cstAtoms(self, i: int) -> str: ...
    @overload
    def cstAtoms_defined(self) -> bool: ...
    @overload
    def cstAtoms_defined(self) -> bool: ...
    @overload
    def fixResidue(self) -> bool: ...
    @overload
    def fixResidue(self) -> bool: ...
    @overload
    def jumpAtoms(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def jumpAtoms(self, i: int) -> str: ...
    @overload
    def jumpAtoms_defined(self) -> bool: ...
    @overload
    def jumpAtoms_defined(self) -> bool: ...
    def residueType(self) -> pyrosetta.rosetta.core.chemical.ResidueType: ...
    @overload
    def set_cstAtoms(self, cst_atoms: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_cstAtoms(self, constclassutility) -> void: ...
    @overload
    def set_cstAtoms(self, i: int, atom_name: str) -> None: ...
    @overload
    def set_cstAtoms(self, unsignedlong, conststd) -> void: ...
    @overload
    def set_jumpAtoms(self, jump_atoms: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_jumpAtoms(self, constclassutility) -> void: ...
    @overload
    def set_jumpAtoms(self, i: int, atom_name: str) -> None: ...
    @overload
    def set_jumpAtoms(self, unsignedlong, conststd) -> void: ...

class SameStrand:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SameStrand) -> None: ...
    def assign(self) -> SameStrand: ...
    def eval(self, i: int, j: int) -> bool: ...
    @overload
    def redo(self) -> None: ...
    @overload
    def redo(self) -> void: ...
    @overload
    def show(self, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def total_residue(self) -> int: ...
    @overload
    def total_residue(self) -> unsignedlong: ...

class SheetBuilder(BaseJumpSetup):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SheetBuilder) -> None: ...
    @overload
    def __init__(self, arg0: SheetBuilder) -> None: ...
    def assign(self) -> SheetBuilder: ...
    def clean_jumps(self, js: JumpSample) -> JumpSample: ...
    def create_jump_sample(self) -> JumpSample: ...
    @overload
    def total_residue(self) -> int: ...
    @overload
    def total_residue(self) -> unsignedlong: ...
    def type_name(self) -> str: ...

class SpecificGeometryLibrary(PairingLibrary):
    def __init__(self) -> None: ...
    def assign(self) -> SpecificGeometryLibrary: ...

class StandardDisulfPairingLibrary(DisulfPairingLibrary, pyrosetta.rosetta.utility.SingletonBase_protocols_jumping_StandardDisulfPairingLibrary_t):
    def __init__(self, *args, **kwargs) -> None: ...

class StandardPairingLibrary(PairingLibrary, pyrosetta.rosetta.utility.SingletonBase_protocols_jumping_StandardPairingLibrary_t):
    def __init__(self, *args, **kwargs) -> None: ...

class cstType:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    angleA: ClassVar[cstType] = ...
    angleB: ClassVar[cstType] = ...
    dihedralA: ClassVar[cstType] = ...
    dihedralAB: ClassVar[cstType] = ...
    dihedralB: ClassVar[cstType] = ...
    disAB: ClassVar[cstType] = ...
    num_cstType: ClassVar[cstType] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class dofType:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    cstJump: ClassVar[dofType] = ...
    num_dofType: ClassVar[dofType] = ...
    rot1: ClassVar[dofType] = ...
    rot2: ClassVar[dofType] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

@overload
def assign_ss_dssp(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def assign_ss_dssp(classcore) -> void: ...
@overload
def close_chainbreaks(closure_protocol, pose: pyrosetta.rosetta.core.pose.Pose, checkpoint: pyrosetta.rosetta.protocols.checkpoint.CheckPointer, decoy_tag: str) -> None: ...
@overload
def close_chainbreaks(closure_protocol, pose: pyrosetta.rosetta.core.pose.Pose, checkpoint: pyrosetta.rosetta.protocols.checkpoint.CheckPointer, decoy_tag: str, final_fold_tree: pyrosetta.rosetta.core.kinematics.FoldTree) -> None: ...
@overload
def close_chainbreaks(classstd, classcore, classprotocols, conststd, constclasscore) -> void: ...
def generate_empty_jump_frame(startpos: int, endpos: int, length: int) -> pyrosetta.rosetta.core.fragment.JumpingFrame: ...
def generate_jump_frame(startpos: int, endpos: int, bWithTorsion: bool) -> pyrosetta.rosetta.core.fragment.JumpingFrame: ...
def get_pairing_geometry(pose: pyrosetta.rosetta.core.pose.Pose, res1: int, res2: int, orientation: float, pleating1: float, pleating2: float) -> None: ...
def get_pleating(pose: pyrosetta.rosetta.core.pose.Pose, pos1: int, pos2: int, orientation: int, pleating: int) -> None: ...
@overload
def read_disulf_pairing_list(_is: pyrosetta.rosetta.std.istream, disulf_pairings: pyrosetta.rosetta.utility.vector1_protocols_jumping_DisulfPairing) -> None: ...
@overload
def read_disulf_pairing_list(std, classutility) -> void: ...
@overload
def remove_cut(cutpoint: int, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
@overload
def remove_cut(cutpoint: int, pose: pyrosetta.rosetta.core.pose.Pose, final_fold_tree: pyrosetta.rosetta.core.kinematics.FoldTree) -> bool: ...
@overload
def remove_cut(unsignedlong, classcore, constclasscore) -> bool: ...
@overload
def remove_cut(cutpoint: int, fold_tree: pyrosetta.rosetta.core.kinematics.FoldTree) -> bool: ...
@overload
def remove_cut(cutpoint: int, fold_tree: pyrosetta.rosetta.core.kinematics.FoldTree, final_fold_tree: pyrosetta.rosetta.core.kinematics.FoldTree) -> bool: ...
@overload
def remove_cut(unsignedlong, classcore, constclasscore) -> bool: ...
@overload
def safe_secstruct(pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def safe_secstruct(classcore) -> void: ...
