import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.loops
import pyrosetta.rosetta.protocols.loops.loop_mover
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.protocols.relax.loop
import pyrosetta.rosetta.utility.tag
from typing import overload

class LoopBuildMover(pyrosetta.rosetta.protocols.moves.Mover):
    def __init__(self, loop_relax_mover: pyrosetta.rosetta.protocols.relax.loop.LoopRelaxMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> LoopBuildMover: ...
    def get_name(self) -> str: ...

class LoopMover_SlidingWindow(pyrosetta.rosetta.protocols.loops.loop_mover.IndependentLoopMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, loops_in: pyrosetta.rosetta.protocols.loops.Loops) -> None: ...
    @overload
    def __init__(self, loops_in: pyrosetta.rosetta.protocols.loops.Loops, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: LoopMover_SlidingWindow) -> None: ...
    @overload
    def __init__(self, arg0: LoopMover_SlidingWindow) -> None: ...
    def assign(self) -> LoopMover_SlidingWindow: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def randomize_loop(self) -> bool: ...
    @overload
    def randomize_loop(self) -> bool: ...
    @overload
    def randomize_loop(self, flag: bool) -> None: ...
    @overload
    def randomize_loop(self, constbool) -> void: ...
    @overload
    def set_default_settings(self) -> None: ...
    @overload
    def set_default_settings(self) -> void: ...

class LoopMover_SlidingWindowCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LoopMover_SlidingWindowCreator) -> None: ...
    @overload
    def __init__(self, arg0: LoopMover_SlidingWindowCreator) -> None: ...
    def assign(self) -> LoopMover_SlidingWindowCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class LoopmodelWrapper(pyrosetta.rosetta.protocols.moves.Mover):
    def __init__(self) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> LoopmodelWrapper: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class LoopmodelWrapperCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LoopmodelWrapperCreator) -> None: ...
    @overload
    def __init__(self, arg0: LoopmodelWrapperCreator) -> None: ...
    def assign(self) -> LoopmodelWrapperCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

@overload
def LoopBuild_main(boinc_mode: bool) -> int: ...
@overload
def LoopBuild_main(bool) -> int: ...
