import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.optimization
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import overload

class CartesianMD(MDBase):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, movemap: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, movemap: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def __init__(self, arg0: CartesianMD) -> None: ...
    @overload
    def __init__(self, arg0: CartesianMD) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> CartesianMD: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def cst_on_pose_dynamic(self, pose: pyrosetta.rosetta.core.pose.Pose, ref_xyz: pyrosetta.rosetta.utility.vector1_double, curr_eqxyz: pyrosetta.rosetta.utility.vector1_double, prv_eqxyz: pyrosetta.rosetta.utility.vector1_double, min_map: pyrosetta.rosetta.core.optimization.CartesianMinimizerMap) -> None: ...
    @overload
    def cst_on_pose_simple(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def cst_on_pose_simple(self, classcore) -> void: ...
    def dump_poses(self, pose_ref: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_core_pose_Pose: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_current_eqxyz(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_movemap(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_movemap(self, classstd, classbasic) -> void: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def parse_opts(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_opts(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def update_restraint(self, pose: pyrosetta.rosetta.core.pose.Pose, min_map: pyrosetta.rosetta.core.optimization.CartesianMinimizerMap) -> None: ...
    @overload
    def update_restraint(self, classcore, constclasscore) -> void: ...
    @overload
    def use_rattle(self, value: bool) -> None: ...
    @overload
    def use_rattle(self, constbool) -> void: ...

class CartesianMDCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CartesianMDCreator) -> None: ...
    @overload
    def __init__(self, arg0: CartesianMDCreator) -> None: ...
    def assign(self) -> CartesianMDCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class Constraint:
    a: int
    b: int
    k: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Constraint) -> None: ...

class MDBase(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MDBase) -> None: ...
    @overload
    def Emin_obj(self) -> float: ...
    @overload
    def Emin_obj(self) -> double: ...
    @overload
    def Gamma(self) -> float: ...
    @overload
    def Gamma(self) -> double: ...
    @overload
    def Kappa(self) -> float: ...
    @overload
    def Kappa(self) -> double: ...
    @overload
    def acc(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def acc(self, idof: int) -> float: ...
    @overload
    def add_trj(self, xyz: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def add_trj(self, classutility) -> void: ...
    @overload
    def add_trj_scratch(self, xyz: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def add_trj_scratch(self, classutility) -> void: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> MDBase: ...
    @overload
    def context_update_step(self) -> int: ...
    @overload
    def context_update_step(self) -> unsignedlong: ...
    @overload
    def cst_sdev(self) -> float: ...
    @overload
    def cst_sdev(self) -> double: ...
    @overload
    def cummulative_time(self) -> float: ...
    @overload
    def cummulative_time(self) -> double: ...
    @overload
    def dt(self) -> float: ...
    @overload
    def dt(self) -> double: ...
    def get_name(self) -> str: ...
    @overload
    def init(self) -> None: ...
    @overload
    def init(self) -> void: ...
    @overload
    def kinetic_energy(self) -> float: ...
    @overload
    def kinetic_energy(self) -> double: ...
    @overload
    def mass(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def mass(self, iatm: int) -> float: ...
    @overload
    def mass(self, unsignedlong) -> double: ...
    @overload
    def md_energy_report_stepsize(self) -> int: ...
    @overload
    def md_energy_report_stepsize(self) -> unsignedlong: ...
    @overload
    def md_report_stepsize(self) -> int: ...
    @overload
    def md_report_stepsize(self) -> unsignedlong: ...
    @overload
    def md_rsr_update_stepsize(self) -> int: ...
    @overload
    def md_rsr_update_stepsize(self) -> unsignedlong: ...
    @overload
    def mdsch(self) -> pyrosetta.rosetta.utility.vector1_protocols_md_MDscheduleData: ...
    @overload
    def mdsch(self, istep: int) -> MDscheduleData: ...
    def movemap(self) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def n_dof(self) -> int: ...
    @overload
    def n_dof(self) -> unsignedlong: ...
    @overload
    def n_dof_temp(self) -> int: ...
    @overload
    def n_dof_temp(self) -> unsignedlong: ...
    @overload
    def ncyc_postmin(self) -> int: ...
    @overload
    def ncyc_postmin(self) -> unsignedlong: ...
    @overload
    def ncyc_premin(self) -> int: ...
    @overload
    def ncyc_premin(self) -> unsignedlong: ...
    @overload
    def nstep(self) -> int: ...
    @overload
    def nstep(self) -> unsignedlong: ...
    @overload
    def parse_schfile(self, schfile: str) -> None: ...
    @overload
    def parse_schfile(self, conststd) -> void: ...
    def pose0(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    def pose_minobj(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    def potential_energy(self) -> float: ...
    @overload
    def potential_energy(self) -> double: ...
    def prv_eqxyz(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    def ref_xyz(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def renew_trj_scratch(self) -> None: ...
    @overload
    def renew_trj_scratch(self) -> void: ...
    @overload
    def report_as_silent(self) -> bool: ...
    @overload
    def report_as_silent(self) -> bool: ...
    @overload
    def report_scorecomp(self) -> bool: ...
    @overload
    def report_scorecomp(self) -> bool: ...
    @overload
    def report_silent(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def report_silent(self, pose: pyrosetta.rosetta.core.pose.Pose, rmsd: float) -> None: ...
    @overload
    def report_silent(self, pose: pyrosetta.rosetta.core.pose.Pose, rmsd: float, gdttm: float) -> None: ...
    @overload
    def report_silent(self, pose: pyrosetta.rosetta.core.pose.Pose, rmsd: float, gdttm: float, gdtha: float) -> None: ...
    @overload
    def resize_natm_variables(self) -> None: ...
    @overload
    def resize_natm_variables(self) -> void: ...
    def rsrfilename(self) -> str: ...
    @overload
    def scheduled(self) -> bool: ...
    @overload
    def scheduled(self) -> bool: ...
    def scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    def scorefxn_obj(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    def selectmode(self) -> str: ...
    @overload
    def set_Emin_obj(self, setting: float) -> None: ...
    @overload
    def set_Emin_obj(self, double) -> void: ...
    @overload
    def set_Gamma(self, setting: float) -> None: ...
    @overload
    def set_Gamma(self, double) -> void: ...
    @overload
    def set_Kappa(self, setting: float) -> None: ...
    @overload
    def set_Kappa(self, double) -> void: ...
    @overload
    def set_acc(self, setting: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_acc(self, classutility) -> void: ...
    @overload
    def set_constraint(self, sdev: float) -> None: ...
    @overload
    def set_constraint(self, constdouble) -> void: ...
    @overload
    def set_context_update_step(self, setting: int) -> None: ...
    @overload
    def set_context_update_step(self, unsignedlong) -> void: ...
    @overload
    def set_cst_sdev(self, setting: float) -> None: ...
    @overload
    def set_cst_sdev(self, double) -> void: ...
    @overload
    def set_cummulative_time(self, setting: float) -> None: ...
    @overload
    def set_cummulative_time(self, double) -> void: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...
    @overload
    def set_dt(self, setting: float) -> None: ...
    @overload
    def set_dt(self, double) -> void: ...
    @overload
    def set_kinetic_energy(self, setting: float) -> None: ...
    @overload
    def set_kinetic_energy(self, double) -> void: ...
    @overload
    def set_mass(self, iatm: int, setting: float) -> None: ...
    @overload
    def set_mass(self, unsignedlong, double) -> void: ...
    @overload
    def set_md_energy_report_stepsize(self, setting: int) -> None: ...
    @overload
    def set_md_energy_report_stepsize(self, unsignedlong) -> void: ...
    @overload
    def set_md_report_stepsize(self, setting: int) -> None: ...
    @overload
    def set_md_report_stepsize(self, unsignedlong) -> void: ...
    @overload
    def set_md_rsr_update_stepsize(self, setting: int) -> None: ...
    @overload
    def set_md_rsr_update_stepsize(self, unsignedlong) -> void: ...
    @overload
    def set_mdsch(self, setting: pyrosetta.rosetta.utility.vector1_protocols_md_MDscheduleData) -> None: ...
    @overload
    def set_mdsch(self, classutility) -> void: ...
    @overload
    def set_movemap(self, pose: pyrosetta.rosetta.core.pose.Pose, movemap: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def set_movemap(self, constclasscore, classstd) -> void: ...
    @overload
    def set_n_dof(self, setting: int) -> None: ...
    @overload
    def set_n_dof(self, unsignedlong) -> void: ...
    @overload
    def set_n_dof_temp(self, setting: int) -> None: ...
    @overload
    def set_n_dof_temp(self, unsignedlong) -> void: ...
    @overload
    def set_ncyc_postmin(self, setting: int) -> None: ...
    @overload
    def set_ncyc_postmin(self, unsignedlong) -> void: ...
    @overload
    def set_ncyc_premin(self, setting: int) -> None: ...
    @overload
    def set_ncyc_premin(self, unsignedlong) -> void: ...
    @overload
    def set_nstep(self, setting: int) -> None: ...
    @overload
    def set_nstep(self, unsignedlong) -> void: ...
    @overload
    def set_pose0(self, setting: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_pose0(self, classcore) -> void: ...
    @overload
    def set_pose_minobj(self, setting: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_pose_minobj(self, classcore) -> void: ...
    @overload
    def set_potential_energy(self, setting: float) -> None: ...
    @overload
    def set_potential_energy(self, double) -> void: ...
    @overload
    def set_prv_eqxyz(self, setting: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_prv_eqxyz(self, classutility) -> void: ...
    @overload
    def set_ref_xyz(self, setting: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_ref_xyz(self, classutility) -> void: ...
    @overload
    def set_report_as_silent(self, setting: bool) -> None: ...
    @overload
    def set_report_as_silent(self, bool) -> void: ...
    @overload
    def set_report_scorecomp(self, setting: bool) -> None: ...
    @overload
    def set_report_scorecomp(self, bool) -> void: ...
    @overload
    def set_rsrfilename(self, setting: str) -> None: ...
    @overload
    def set_rsrfilename(self, std) -> void: ...
    @overload
    def set_scheduled(self, setting: bool) -> None: ...
    @overload
    def set_scheduled(self, bool) -> void: ...
    @overload
    def set_scorefxn(self, setting: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn(self, classstd) -> void: ...
    @overload
    def set_scorefxn(self, setting: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn(self, constclasscore) -> void: ...
    @overload
    def set_scorefxn_obj(self, setting: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn_obj(self, classstd) -> void: ...
    @overload
    def set_scorefxn_obj(self, setting: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn_obj(self, constclasscore) -> void: ...
    @overload
    def set_selectmode(self, setting: str) -> None: ...
    @overload
    def set_selectmode(self, std) -> void: ...
    @overload
    def set_silentname(self, setting: str) -> None: ...
    @overload
    def set_silentname(self, std) -> void: ...
    @overload
    def set_store_trj(self, setting: bool) -> None: ...
    @overload
    def set_store_trj(self, bool) -> void: ...
    @overload
    def set_temp0(self, setting: float) -> None: ...
    @overload
    def set_temp0(self, double) -> void: ...
    @overload
    def set_temperature(self, setting: float) -> None: ...
    @overload
    def set_temperature(self, double) -> void: ...
    @overload
    def set_time_minobj(self, setting: float) -> None: ...
    @overload
    def set_time_minobj(self, double) -> void: ...
    @overload
    def set_trj(self, setting: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def set_trj(self, classutility) -> void: ...
    @overload
    def set_trj_score_only(self, setting: bool) -> None: ...
    @overload
    def set_trj_score_only(self, bool) -> void: ...
    @overload
    def set_trj_scratch(self, setting: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def set_trj_scratch(self, classutility) -> void: ...
    @overload
    def set_uniform_coord_constrained(self, setting: bool) -> None: ...
    @overload
    def set_uniform_coord_constrained(self, bool) -> void: ...
    @overload
    def set_vel(self, setting: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_vel(self, classutility) -> void: ...
    @overload
    def set_write_dynamic_rsr(self, setting: bool) -> None: ...
    @overload
    def set_write_dynamic_rsr(self, bool) -> void: ...
    @overload
    def set_write_dynamic_rsr(self, filename: str) -> None: ...
    @overload
    def set_write_dynamic_rsr(self, conststd) -> void: ...
    @overload
    def set_xyz(self, setting: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_xyz(self, classutility) -> void: ...
    def silentname(self) -> str: ...
    @overload
    def store_trj(self) -> bool: ...
    @overload
    def store_trj(self) -> bool: ...
    @overload
    def temp0(self) -> float: ...
    @overload
    def temp0(self) -> double: ...
    @overload
    def temperature(self) -> float: ...
    @overload
    def temperature(self) -> double: ...
    @overload
    def time_minobj(self) -> float: ...
    @overload
    def time_minobj(self) -> double: ...
    @overload
    def trj(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    @overload
    def trj(self, itrj: int) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def trj_score_only(self) -> bool: ...
    @overload
    def trj_score_only(self) -> bool: ...
    def trj_scratch(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    @overload
    def uniform_coord_constrained(self) -> bool: ...
    @overload
    def uniform_coord_constrained(self) -> bool: ...
    @overload
    def vel(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def vel(self, idof: int) -> float: ...
    @overload
    def write_dynamic_rsr(self) -> bool: ...
    @overload
    def write_dynamic_rsr(self) -> bool: ...
    @overload
    def xyz(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def xyz(self, idof: int) -> float: ...

class MDscheduleData:
    nstep: int
    temp0: float
    type: str
    @overload
    def __init__(self, arg0: MDscheduleData) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def assign(self) -> MDscheduleData: ...

class Rattle:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, min_map: pyrosetta.rosetta.core.optimization.CartesianMinimizerMap) -> None: ...
    @overload
    def __init__(self, arg0: Rattle) -> None: ...
    def assign(self) -> Rattle: ...
    @overload
    def ncst(self) -> int: ...
    @overload
    def ncst(self) -> unsignedlong: ...
    def run_rattle1(self, dt: float, xyz: pyrosetta.rosetta.utility.vector1_double, vel: pyrosetta.rosetta.utility.vector1_double, mass: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    def run_rattle2(self, dt: float, xyz: pyrosetta.rosetta.utility.vector1_double, vel: pyrosetta.rosetta.utility.vector1_double, mass: pyrosetta.rosetta.utility.vector1_double) -> None: ...

class Thermostat:
    @overload
    def __init__(self, temperature0: float, ndof: int) -> None: ...
    @overload
    def __init__(self, temperature0: float, tau: float, ndof: int) -> None: ...
    def get_temperature(self, vel: pyrosetta.rosetta.utility.vector1_double, mass: pyrosetta.rosetta.utility.vector1_double) -> float: ...
    @overload
    def nstep_per_update(self) -> int: ...
    @overload
    def nstep_per_update(self) -> unsignedlong: ...
    def rescale(self, vel: pyrosetta.rosetta.utility.vector1_double, dt: float, mass: pyrosetta.rosetta.utility.vector1_double) -> None: ...
