import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.pack.rotamer_set
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.pose.metrics
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
import typing
from typing import Any, overload

class AAMatrix(jagged_array_protocols_mean_field_AAProb_std_allocator_protocols_mean_field_AAProb_t):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, aa_matrix_file: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def __init__(self, rm, em: jagged_array_double_std_allocator_double_t, temp: float) -> None: ...
    @overload
    def __init__(self, arg0: AAMatrix) -> None: ...
    def assign(self, object_to_copy: AAMatrix) -> AAMatrix: ...
    def ave_abs_diff(self, aa_matrix: AAMatrix) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def build_aa_matrix(self, rm, em: jagged_array_double_std_allocator_double_t, temp: float) -> None: ...
    @overload
    def build_aa_matrix(self, constclassprotocols, classprotocols, double) -> void: ...
    @overload
    def build_aa_matrix(self, aa_matrix_file: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def build_aa_matrix(self, std) -> void: ...
    def cosine_distance(self, aa_matrix: AAMatrix) -> pyrosetta.rosetta.utility.vector1_double: ...
    def curr_aa(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def dump_transfac(self, filename: str) -> None: ...
    @overload
    def dump_transfac(self, conststd) -> void: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    def frob_distance(self, aa_matrix: AAMatrix) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class AAProb:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, prob: float, aa_ind: pyrosetta.rosetta.core.chemical.AA, pos: int, nrot: int) -> None: ...
    @overload
    def __init__(self, rp) -> None: ...
    @overload
    def __init__(self, arg0: AAProb) -> None: ...
    @overload
    def aa_ind(self) -> pyrosetta.rosetta.core.chemical.AA: ...
    @overload
    def aa_ind(self, aa: pyrosetta.rosetta.core.chemical.AA) -> None: ...
    @overload
    def aa_ind(self, enumcore) -> void: ...
    def assign(self, object_to_copy: AAProb) -> AAProb: ...
    @overload
    def nrot(self) -> int: ...
    @overload
    def nrot(self) -> unsignedlong: ...
    @overload
    def nrot(self, n: int) -> None: ...
    @overload
    def nrot(self, unsignedlong) -> void: ...
    @overload
    def pos(self) -> int: ...
    @overload
    def pos(self) -> unsignedlong: ...
    @overload
    def pos(self, p: int) -> None: ...
    @overload
    def pos(self, unsignedlong) -> void: ...
    @overload
    def probability(self) -> float: ...
    @overload
    def probability(self) -> double: ...
    @overload
    def probability(self, prob: float) -> None: ...
    @overload
    def probability(self, double) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def __add__(self, prob: float) -> AAProb: ...
    def __eq__(self, obj: AAProb) -> bool: ...
    @overload
    def __iadd__(self, obj: AAProb) -> None: ...
    @overload
    def __iadd__(self, prob: float) -> None: ...
    @overload
    def __imul__(self, obj: AAProb) -> None: ...
    @overload
    def __imul__(self, prob: float) -> None: ...
    @overload
    def __isub__(self, obj: AAProb) -> None: ...
    @overload
    def __isub__(self, prob: float) -> None: ...
    @overload
    def __itruediv__(self, obj: AAProb) -> None: ...
    @overload
    def __itruediv__(self, prob: float) -> None: ...
    def __mul__(self, prob: float) -> AAProb: ...
    def __ne__(self, obj: AAProb) -> bool: ...
    def __sub__(self, prob: float) -> AAProb: ...
    def __truediv__(self, prob: float) -> AAProb: ...

class DesignMeanField(MeanField):
    @overload
    def __init__(self, option: int, poses: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, tasks: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_PackerTask_t, scfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, option: int, poses: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, tasks: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_PackerTask_t, scfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, lambda_mem: float, tolerance: float, temp: float, threshold: float) -> None: ...
    def aa_matrix(self) -> AAMatrix: ...
    @overload
    def process(self) -> None: ...
    @overload
    def process(self) -> Any: ...
    @overload
    def process(self) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class EnergiesByTaskCalculator(pyrosetta.rosetta.core.pose.metrics.EnergyDependentCalculator):
    @overload
    def __init__(self, task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def __init__(self, arg0: EnergiesByTaskCalculator) -> None: ...
    @overload
    def __init__(self, arg0: EnergiesByTaskCalculator) -> None: ...
    def assign(self) -> EnergiesByTaskCalculator: ...
    def clone(self) -> pyrosetta.rosetta.core.pose.metrics.PoseMetricCalculator: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def task(self) -> pyrosetta.rosetta.core.pack.task.PackerTask: ...
    @overload
    def total(self) -> float: ...
    @overload
    def total(self) -> double: ...

class FlexBBDesignMeanField(FlexBBMeanField):
    @overload
    def __init__(self, option: int, poses: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, tasks: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_PackerTask_t, scfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, option: int, poses: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, tasks: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_PackerTask_t, scfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, lambda_mem: float, tolerance: float, temp: float, threshold: float) -> None: ...
    def aa_matrices(self) -> pyrosetta.rosetta.utility.vector1_protocols_mean_field_AAMatrix: ...
    def aa_matrix(self) -> AAMatrix: ...
    @overload
    def calc_bb_boltz_probs(self) -> None: ...
    @overload
    def calc_bb_boltz_probs(self) -> void: ...
    @overload
    def calc_exp_value_aa_matrix(self) -> None: ...
    @overload
    def calc_exp_value_aa_matrix(self) -> void: ...
    @overload
    def delete_pose(self, pose_ind: int) -> None: ...
    @overload
    def delete_pose(self, unsignedlong) -> void: ...
    @overload
    def process(self) -> None: ...
    @overload
    def process(self) -> Any: ...
    @overload
    def process(self) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class FlexBBMeanField(MeanField):
    @overload
    def __init__(self, option: int, poses: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, tasks: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_PackerTask_t, scfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, option: int, poses: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, tasks: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_PackerTask_t, scfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, lambda_mem: float, tolerance: float, temp: float, threshold: float) -> None: ...
    def bb_boltz_probs(self) -> jagged_array_double_std_allocator_double_t: ...
    def bb_boltz_probs_per_aa(self) -> pyrosetta.rosetta.utility.vector1_protocols_mean_field_jagged_array_double_t: ...
    @overload
    def calc_bb_boltz_probs(self) -> None: ...
    @overload
    def calc_bb_boltz_probs(self) -> void: ...
    @overload
    def calc_exp_value_rot_matrix(self) -> None: ...
    @overload
    def calc_exp_value_rot_matrix(self) -> void: ...
    @overload
    def delete_pose(self, pose_ind: int) -> None: ...
    @overload
    def delete_pose(self, unsignedlong) -> void: ...
    def energy_matrices(self) -> pyrosetta.rosetta.utility.vector1_protocols_mean_field_jagged_array_double_t: ...
    def energy_matrix(self) -> jagged_array_double_std_allocator_double_t: ...
    @overload
    def process(self) -> None: ...
    @overload
    def process(self) -> Any: ...
    @overload
    def process(self) -> void: ...
    @overload
    def renumber_rotamers(self) -> None: ...
    @overload
    def renumber_rotamers(self) -> void: ...
    def rot_matrices(self) -> pyrosetta.rosetta.utility.vector1_protocols_mean_field_RotMatrix: ...
    def rot_matrix(self) -> RotMatrix: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class GenMeanFieldMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GenMeanFieldMover) -> None: ...
    @overload
    def __init__(self, arg0: GenMeanFieldMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> GenMeanFieldMover: ...
    @overload
    def calc_mean_field(self) -> None: ...
    @overload
    def calc_mean_field(self) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    @staticmethod
    def default_value_for_init_option() -> int: ...
    @overload
    @staticmethod
    def default_value_for_init_option() -> unsignedlong: ...
    @overload
    @staticmethod
    def default_value_for_lambda_memory() -> float: ...
    @overload
    @staticmethod
    def default_value_for_lambda_memory() -> double: ...
    @overload
    @staticmethod
    def default_value_for_temperature() -> float: ...
    @overload
    @staticmethod
    def default_value_for_temperature() -> double: ...
    @overload
    @staticmethod
    def default_value_for_threshold() -> float: ...
    @overload
    @staticmethod
    def default_value_for_threshold() -> double: ...
    @overload
    @staticmethod
    def default_value_for_tolerance() -> float: ...
    @overload
    @staticmethod
    def default_value_for_tolerance() -> double: ...
    @overload
    @staticmethod
    def default_value_for_unbound() -> bool: ...
    @overload
    @staticmethod
    def default_value_for_unbound() -> bool: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def init_option(self) -> int: ...
    @overload
    def init_option(self) -> unsignedlong: ...
    @overload
    def init_option(self, iopt: int) -> None: ...
    @overload
    def init_option(self, constunsignedlong) -> void: ...
    @overload
    def lambda_memory(self) -> float: ...
    @overload
    def lambda_memory(self) -> double: ...
    @overload
    def lambda_memory(self, lm: float) -> None: ...
    @overload
    def lambda_memory(self, constdouble) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def prepare_task_poses(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def prepare_task_poses(self, constclasscore) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def read_aa_matrix(self) -> None: ...
    @overload
    def read_aa_matrix(self) -> void: ...
    @overload
    def read_input_pdbs(self) -> None: ...
    @overload
    def read_input_pdbs(self) -> void: ...
    @overload
    def report_aa_matrix(self) -> None: ...
    @overload
    def report_aa_matrix(self) -> void: ...
    @overload
    def report_dist(self, am: AAMatrix) -> None: ...
    @overload
    def report_dist(self, constclassprotocols) -> void: ...
    @overload
    def report_rot_prob(self) -> None: ...
    @overload
    def report_rot_prob(self) -> void: ...
    @overload
    def scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def scorefxn(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def scorefxn(self, classstd) -> void: ...
    @overload
    def task_factory(self) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    @overload
    def task_factory(self, task_factory: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def task_factory(self, classstd) -> void: ...
    @overload
    def temperature(self) -> float: ...
    @overload
    def temperature(self) -> double: ...
    @overload
    def temperature(self, temp: float) -> None: ...
    @overload
    def temperature(self, constdouble) -> void: ...
    @overload
    def threshold(self) -> float: ...
    @overload
    def threshold(self) -> double: ...
    @overload
    def threshold(self, threshold: float) -> None: ...
    @overload
    def threshold(self, constdouble) -> void: ...
    @overload
    def tolerance(self) -> float: ...
    @overload
    def tolerance(self) -> double: ...
    @overload
    def tolerance(self, tol: float) -> None: ...
    @overload
    def tolerance(self, constdouble) -> void: ...
    @overload
    def type(self) -> str: ...
    @overload
    def type(self, s: str) -> None: ...
    @overload
    def type(self, conststd) -> void: ...
    @overload
    def unbound(self) -> bool: ...
    @overload
    def unbound(self) -> bool: ...
    @overload
    def unbound(self, ub: bool) -> None: ...
    @overload
    def unbound(self, constbool) -> void: ...

class GenMeanFieldMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GenMeanFieldMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: GenMeanFieldMoverCreator) -> None: ...
    def assign(self) -> GenMeanFieldMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class MeanField:
    @overload
    def __init__(self, option: int, poses: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, tasks: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_PackerTask_t, scfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, option: int, poses: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, tasks: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_PackerTask_t, scfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, lambda_mem: float, tolerance: float, temp: float, threshold: float) -> None: ...
    def alt_rot_matrix(self, *args, **kwargs): ...
    @overload
    def build_rot_matrix_for_pose(self, pose_ind: int) -> None: ...
    @overload
    def build_rot_matrix_for_pose(self, unsignedlong) -> void: ...
    @overload
    def converge(self) -> None: ...
    @overload
    def converge(self) -> void: ...
    @overload
    def delete_pose(self, pose_ind: int) -> None: ...
    @overload
    def delete_pose(self, unsignedlong) -> void: ...
    def energies_matrix(self) -> jagged_array_double_std_allocator_double_t: ...
    @overload
    def init_option(self) -> float: ...
    @overload
    def init_option(self) -> double: ...
    @overload
    def lambda_memory(self) -> float: ...
    @overload
    def lambda_memory(self) -> double: ...
    @overload
    def num_packed(self) -> int: ...
    @overload
    def num_packed(self) -> unsignedlong: ...
    @overload
    def num_poses(self) -> int: ...
    @overload
    def num_poses(self) -> unsignedlong: ...
    @overload
    def process(self) -> None: ...
    @overload
    def process(self) -> void: ...
    def rot_matrix(self, *args, **kwargs): ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def temperature(self) -> float: ...
    @overload
    def temperature(self, kT) -> Any: ...
    @overload
    def temperature(self) -> double: ...
    @overload
    def threshold(self) -> float: ...
    @overload
    def threshold(self) -> double: ...
    @overload
    def tolerance(self) -> float: ...
    @overload
    def tolerance(self) -> double: ...

class MeanFieldFactory:
    def __init__(self) -> None: ...
    @staticmethod
    def create_mean_field(option: int, poses: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t, tasks: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_PackerTask_t, scfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, lambda_mem: float, conv_diff: float, temp: float, threshold: float) -> MeanField: ...

class ResHashMap:
    def __init__(self) -> None: ...
    @overload
    def attempt_insert(self, res: pyrosetta.rosetta.core.conformation.Residue) -> int: ...
    @overload
    def attempt_insert(self, classstd) -> long: ...
    @overload
    def get_rot_ind(self, res: pyrosetta.rosetta.core.conformation.Residue) -> int: ...
    @overload
    def get_rot_ind(self, classstd) -> long: ...
    @overload
    def last_ind_assigned(self) -> int: ...
    @overload
    def last_ind_assigned(self) -> long: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class ResHasher:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ResHasher) -> None: ...
    def assign(self) -> ResHasher: ...
    def __call__(self, res: pyrosetta.rosetta.core.conformation.Residue) -> int: ...

class ResPred:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ResPred) -> None: ...
    def assign(self) -> ResPred: ...
    def __call__(self, first_res: pyrosetta.rosetta.core.conformation.Residue, second_res: pyrosetta.rosetta.core.conformation.Residue) -> bool: ...

class RotMatrix(jagged_array_protocols_mean_field_RotProb_std_allocator_protocols_mean_field_RotProb_t):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, option: int, rs: pyrosetta.rosetta.core.pack.rotamer_set.RotamerSets) -> None: ...
    @overload
    def __init__(self, arg0: RotMatrix) -> None: ...
    def assign(self, object_to_copy: RotMatrix) -> RotMatrix: ...
    @overload
    def build_rot_matrix(self, option: int, rs: pyrosetta.rosetta.core.pack.rotamer_set.RotamerSets) -> None: ...
    @overload
    def build_rot_matrix(self, constunsignedlong, classstd) -> void: ...
    @overload
    def curr_rot(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def curr_rot(self, cr: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def curr_rot(self, classutility) -> void: ...
    @overload
    def is_designed(self) -> pyrosetta.rosetta.utility.vector1_bool: ...
    @overload
    def is_designed(self, id: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def is_designed(self, classutility) -> void: ...
    @overload
    def is_designed(self, pos: int) -> bool: ...
    @overload
    def is_designed(self, unsignedlong) -> bool: ...
    @overload
    def n_designed(self) -> int: ...
    @overload
    def n_designed(self) -> unsignedlong: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class RotProb:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, prob: float, rot_ind: int, pos: int, res: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def __init__(self, arg0: RotProb) -> None: ...
    def aa_ind(self) -> pyrosetta.rosetta.core.chemical.AA: ...
    def assign(self, object_to_copy: RotProb) -> RotProb: ...
    @overload
    def pos(self) -> int: ...
    @overload
    def pos(self) -> unsignedlong: ...
    @overload
    def pos(self, p: int) -> None: ...
    @overload
    def pos(self, unsignedlong) -> void: ...
    @overload
    def probability(self) -> float: ...
    @overload
    def probability(self) -> double: ...
    @overload
    def probability(self, prob: float) -> None: ...
    @overload
    def probability(self, double) -> void: ...
    @overload
    def res(self) -> pyrosetta.rosetta.core.conformation.Residue: ...
    @overload
    def res(self, r: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def res(self, classstd) -> void: ...
    @overload
    def rot_ind(self) -> int: ...
    @overload
    def rot_ind(self) -> unsignedlong: ...
    @overload
    def rot_ind(self, aa: int) -> None: ...
    @overload
    def rot_ind(self, unsignedlong) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def __add__(self, prob: float) -> RotProb: ...
    def __eq__(self, obj: RotProb) -> bool: ...
    @overload
    def __iadd__(self, obj: RotProb) -> None: ...
    @overload
    def __iadd__(self, prob: float) -> None: ...
    @overload
    def __imul__(self, obj: RotProb) -> None: ...
    @overload
    def __imul__(self, prob: float) -> None: ...
    @overload
    def __isub__(self, obj: RotProb) -> None: ...
    @overload
    def __isub__(self, prob: float) -> None: ...
    @overload
    def __itruediv__(self, obj: RotProb) -> None: ...
    @overload
    def __itruediv__(self, prob: float) -> None: ...
    def __mul__(self, prob: float) -> RotProb: ...
    def __ne__(self, obj: RotProb) -> bool: ...
    def __sub__(self, prob: float) -> RotProb: ...
    def __truediv__(self, prob: float) -> RotProb: ...

class jagged_array_double_std_allocator_double_t(pyrosetta.rosetta.utility.vector1_utility_vector1_double_t):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, alloc, std) -> None: ...
    @overload
    def __init__(self, arg0: jagged_array_double_std_allocator_double_t) -> None: ...
    @overload
    def __init__(self, v: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, num: int, vals: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, dims: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, dims: pyrosetta.rosetta.utility.vector1_unsigned_long, vals: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def assign(self, __n: int, __u: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def assign(self, v: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    @overload
    def assign(self, v: jagged_array_double_std_allocator_double_t) -> jagged_array_double_std_allocator_double_t: ...
    @overload
    def assign(self, dims: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def assign(self, constclassutility) -> void: ...
    @overload
    def assign(self, dims: pyrosetta.rosetta.utility.vector1_unsigned_long, vals: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def assign(self, __n: int, __u: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def assign(self, v: pyrosetta.rosetta.std.vector_utility_vector1_double_t) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    @overload
    def assign(self, v: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    @overload
    def at(self, i: int) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def at(self, i: int) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def back(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def back(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def equal_size(self, other: jagged_array_double_std_allocator_double_t) -> bool: ...
    @overload
    def equal_size(self, constclassprotocols) -> bool: ...
    @overload
    def front(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def front(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    def get_allocator(self, *args, **kwargs): ...
    @overload
    def get_total(self) -> float: ...
    @overload
    def get_total(self) -> double: ...
    def get_totals_columns(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def has_value(self, t: float) -> bool: ...
    @overload
    def has_value(self, t: pyrosetta.rosetta.utility.vector1_double) -> bool: ...
    @overload
    def has_value(self, constclassutility) -> bool: ...
    @overload
    def index(self, t: float) -> int: ...
    @overload
    def index(self, t: pyrosetta.rosetta.utility.vector1_double) -> int: ...
    @overload
    def index(self, constclassutility) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size_col(self) -> int: ...
    @overload
    def max_size_col(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def push_back(self, __x: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def push_back(self, __x: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def reserve(self, __n: int) -> None: ...
    @overload
    def reserve(self, __n: int) -> None: ...
    @overload
    def resize(self, __sz: int, __x: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def resize(self, __sz: int) -> None: ...
    @overload
    def resize(self, __sz: int, __x: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def resize(self, __sz: int) -> None: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def shrink_to_fit(self) -> None: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size_col(self, col: int) -> int: ...
    @overload
    def size_col(self, unsignedlong) -> unsignedlong: ...
    @overload
    def swap(self) -> None: ...
    @overload
    def swap(self) -> None: ...
    @overload
    def __getitem__(self, i: int) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def __getitem__(self, i: int) -> pyrosetta.rosetta.utility.vector1_double: ...
    def __iter__(self) -> typing.Iterator[pyrosetta.rosetta.utility.vector1_double]: ...

class jagged_array_protocols_mean_field_AAProb_std_allocator_protocols_mean_field_AAProb_t(pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_mean_field_AAProb_t):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, alloc, std) -> None: ...
    @overload
    def __init__(self, arg0: jagged_array_protocols_mean_field_AAProb_std_allocator_protocols_mean_field_AAProb_t) -> None: ...
    @overload
    def __init__(self, v: pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_mean_field_AAProb_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, dims: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def assign(self, v: pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_mean_field_AAProb_t) -> pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_mean_field_AAProb_t: ...
    @overload
    def assign(self, v: jagged_array_protocols_mean_field_AAProb_std_allocator_protocols_mean_field_AAProb_t) -> jagged_array_protocols_mean_field_AAProb_std_allocator_protocols_mean_field_AAProb_t: ...
    @overload
    def assign(self, dims: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def assign(self, constclassutility) -> void: ...
    @overload
    def assign(self, v: pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_mean_field_AAProb_t) -> pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_mean_field_AAProb_t: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def equal_size(self, other: jagged_array_protocols_mean_field_AAProb_std_allocator_protocols_mean_field_AAProb_t) -> bool: ...
    @overload
    def equal_size(self, constclassprotocols) -> bool: ...
    def front(self, *args, **kwargs): ...
    def get_allocator(self, *args, **kwargs): ...
    def get_total(self, *args, **kwargs): ...
    @overload
    def has_value(self, t) -> bool: ...
    @overload
    def has_value(self, constclassprotocols) -> bool: ...
    @overload
    def index(self, t) -> int: ...
    @overload
    def index(self, constclassprotocols) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size_col(self) -> int: ...
    @overload
    def max_size_col(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def reserve(self, __n: int) -> None: ...
    @overload
    def reserve(self, __n: int) -> None: ...
    @overload
    def resize(self, __sz: int) -> None: ...
    @overload
    def resize(self, __sz: int) -> None: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def shrink_to_fit(self) -> None: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size_col(self, col: int) -> int: ...
    @overload
    def size_col(self, unsignedlong) -> unsignedlong: ...
    @overload
    def swap(self) -> None: ...
    @overload
    def swap(self) -> None: ...
    def __getitem__(self, index): ...

class jagged_array_protocols_mean_field_RotProb_std_allocator_protocols_mean_field_RotProb_t(pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_mean_field_RotProb_t):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, alloc, std) -> None: ...
    @overload
    def __init__(self, arg0: jagged_array_protocols_mean_field_RotProb_std_allocator_protocols_mean_field_RotProb_t) -> None: ...
    @overload
    def __init__(self, v: pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_mean_field_RotProb_t) -> None: ...
    @overload
    def __init__(self, num: int) -> None: ...
    @overload
    def __init__(self, dims: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def assign(self, v: pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_mean_field_RotProb_t) -> pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_mean_field_RotProb_t: ...
    @overload
    def assign(self, v: jagged_array_protocols_mean_field_RotProb_std_allocator_protocols_mean_field_RotProb_t) -> jagged_array_protocols_mean_field_RotProb_std_allocator_protocols_mean_field_RotProb_t: ...
    @overload
    def assign(self, dims: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def assign(self, constclassutility) -> void: ...
    @overload
    def assign(self, v: pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_mean_field_RotProb_t) -> pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_mean_field_RotProb_t: ...
    def at(self, *args, **kwargs): ...
    def back(self, *args, **kwargs): ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def capacity(self) -> int: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def empty(self) -> bool: ...
    @overload
    def equal_size(self, other: jagged_array_protocols_mean_field_RotProb_std_allocator_protocols_mean_field_RotProb_t) -> bool: ...
    @overload
    def equal_size(self, constclassprotocols) -> bool: ...
    def front(self, *args, **kwargs): ...
    def get_allocator(self, *args, **kwargs): ...
    def get_total(self, *args, **kwargs): ...
    @overload
    def has_value(self, t) -> bool: ...
    @overload
    def has_value(self, constclassprotocols) -> bool: ...
    @overload
    def index(self, t) -> int: ...
    @overload
    def index(self, constclassprotocols) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size(self) -> int: ...
    @overload
    def max_size_col(self) -> int: ...
    @overload
    def max_size_col(self) -> unsignedlong: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def pop_back(self) -> None: ...
    @overload
    def reserve(self, __n: int) -> None: ...
    @overload
    def reserve(self, __n: int) -> None: ...
    @overload
    def resize(self, __sz: int) -> None: ...
    @overload
    def resize(self, __sz: int) -> None: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def shrink_to_fit(self) -> None: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size_col(self, col: int) -> int: ...
    @overload
    def size_col(self, unsignedlong) -> unsignedlong: ...
    @overload
    def swap(self) -> None: ...
    @overload
    def swap(self) -> None: ...
    def __getitem__(self, index): ...
