import pyrosetta.rosetta.ObjexxFCL
import pyrosetta.rosetta.core.io.silent
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.minimization_packing
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.protocols.wum
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import overload

class Clusterer:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Clusterer) -> None: ...
    def apply(self, structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, ncluster: int, dist_cut: float) -> pyrosetta.rosetta.protocols.wum.SilentStructStore: ...
    def assign(self) -> Clusterer: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...

class MPI_Refine_Emperor(MPI_Refinement):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MPI_Refine_Emperor) -> None: ...
    @overload
    def __init__(self, arg0: MPI_Refine_Emperor) -> None: ...
    def assign(self) -> MPI_Refine_Emperor: ...
    @overload
    def go(self) -> None: ...
    @overload
    def go(self) -> void: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...

class MPI_Refine_Master(MPI_Refinement):
    @overload
    def __init__(self, my_emperor: int, master_rank: int) -> None: ...
    @overload
    def __init__(self, arg0: MPI_Refine_Master) -> None: ...
    @overload
    def __init__(self, arg0: MPI_Refine_Master) -> None: ...
    @overload
    def go(self) -> None: ...
    @overload
    def go(self) -> void: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...

class MPI_Refinement(pyrosetta.rosetta.protocols.wum.MPI_WorkUnitManager):
    @overload
    def __init__(self, machine_letter: str) -> None: ...
    @overload
    def __init__(self, arg0: MPI_Refinement) -> None: ...
    def assign(self) -> MPI_Refinement: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...

class MethodParams:
    cstw: float
    fshave1: float
    fshave2: float
    fshave3: float
    index: int
    irun: int
    istart: int
    movertype: str
    name: str
    nperrun: int
    nrun: int
    relax_type: int
    rerelax_type: int
    roundtype: str
    score_type: int
    @overload
    def __init__(self, arg0: MethodParams) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def assign(self) -> MethodParams: ...

class MultiObjective:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MultiObjective) -> None: ...
    @overload
    def add_objective_function_info(self, ss: pyrosetta.rosetta.core.io.silent.SilentStruct, sstore: pyrosetta.rosetta.protocols.wum.SilentStructStore) -> None: ...
    @overload
    def add_objective_function_info(self, classstd, classprotocols) -> void: ...
    @overload
    def add_objective_function_info(self, sstore: pyrosetta.rosetta.protocols.wum.SilentStructStore) -> None: ...
    @overload
    def add_objective_function_info(self, classprotocols) -> void: ...
    def assign(self) -> MultiObjective: ...
    @overload
    def calculate_pool_diversity(self, structs: pyrosetta.rosetta.protocols.wum.SilentStructStore) -> None: ...
    @overload
    def calculate_pool_diversity(self, classprotocols) -> void: ...
    @overload
    def calculate_pool_diversity(self, structs1: pyrosetta.rosetta.protocols.wum.SilentStructStore, structs2: pyrosetta.rosetta.protocols.wum.SilentStructStore) -> None: ...
    @overload
    def filter_similar(self, structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, measure: str, criteria: float, score_for_priority: str) -> None: ...
    @overload
    def filter_similar(self, structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, measure: str, criteria: float, score_for_priority: str, nmax: int) -> None: ...
    def fobjnames(self, i: int) -> str: ...
    def formatted_objs_names(self) -> str: ...
    def formatted_objs_values(self, ss: pyrosetta.rosetta.core.io.silent.SilentStruct) -> str: ...
    @overload
    def get_fobj(self, ss: pyrosetta.rosetta.core.io.silent.SilentStruct, i: int) -> float: ...
    @overload
    def get_fobj(self, constclasscore, unsignedlong) -> double: ...
    @overload
    def get_fobj(self, ss: pyrosetta.rosetta.core.io.silent.SilentStruct, name: str) -> float: ...
    @overload
    def get_fobj(self, constclasscore, std) -> double: ...
    @overload
    def get_fobj(self, pss: pyrosetta.rosetta.core.io.silent.SilentStruct, i: int) -> float: ...
    @overload
    def get_fobj(self, classstd, unsignedlong) -> double: ...
    def get_scorefxn(self, i: int) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def has_score(self, value: str) -> bool: ...
    @overload
    def has_score(self, std) -> bool: ...
    @overload
    def iha_cut(self) -> float: ...
    @overload
    def iha_cut(self) -> double: ...
    def iha_penalty_mode(self) -> str: ...
    @overload
    def iha_penalty_slope(self) -> float: ...
    @overload
    def iha_penalty_slope(self) -> double: ...
    def init_pose(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    def nobjs(self) -> int: ...
    @overload
    def nobjs(self) -> unsignedlong: ...
    @overload
    def nremain_reset(self) -> int: ...
    @overload
    def nremain_reset(self) -> unsignedlong: ...
    @overload
    def set_iha_cut(self, value: float) -> None: ...
    @overload
    def set_iha_cut(self, double) -> void: ...
    @overload
    def set_iha_penalty_mode(self, value: str) -> None: ...
    @overload
    def set_iha_penalty_mode(self, std) -> void: ...
    @overload
    def set_iha_penalty_slope(self, value: float) -> None: ...
    @overload
    def set_iha_penalty_slope(self, double) -> void: ...
    @overload
    def set_init_pose(self, inpose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_init_pose(self, classcore) -> void: ...
    @overload
    def set_nremain_reset(self, value: int) -> None: ...
    @overload
    def set_nremain_reset(self, unsignedlong) -> void: ...
    def succeed_substitute_info(self, ss_sub: pyrosetta.rosetta.core.io.silent.SilentStruct, ss_ref: pyrosetta.rosetta.core.io.silent.SilentStruct, reset: bool) -> None: ...
    @overload
    def update_library_NSGAII(self, structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, new_structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, nmax: int) -> bool: ...
    @overload
    def update_library_NSGAII(self, structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, new_structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, nmax: int, update_obj_cut: bool) -> bool: ...
    @overload
    def update_library_seeds(self, structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, new_structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, dcut: float, seeds: pyrosetta.rosetta.utility.vector1_unsigned_long, prefix_in: str) -> bool: ...
    @overload
    def update_library_seeds(self, structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, new_structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, dcut: float, seeds: pyrosetta.rosetta.utility.vector1_unsigned_long, prefix_in: str, objname: str) -> bool: ...
    @overload
    def update_library_seeds(self, structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, new_structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, dcut: float, seeds: pyrosetta.rosetta.utility.vector1_unsigned_long, prefix_in: str, objname: str, maxreplace: int) -> bool: ...

class Scheduler:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Scheduler) -> None: ...
    @overload
    def add_rerelaxed(self, value: int) -> None: ...
    @overload
    def add_rerelaxed(self, constunsignedlong) -> void: ...
    @overload
    def add_torerelax(self, value: int) -> None: ...
    @overload
    def add_torerelax(self, constunsignedlong) -> void: ...
    def assign(self) -> Scheduler: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def final_iter(self) -> bool: ...
    @overload
    def final_iter(self) -> bool: ...
    @overload
    def get_params(self) -> MethodParams: ...
    @overload
    def get_params(self, imethod: int) -> MethodParams: ...
    @overload
    def is_excluded(self, picked: pyrosetta.rosetta.utility.vector1_std_string, name2: str) -> bool: ...
    @overload
    def is_excluded(self, classutility, std) -> bool: ...
    @overload
    def iter(self) -> int: ...
    @overload
    def iter(self) -> unsignedlong: ...
    def methodname(self, value: int) -> str: ...
    def methods_picked(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def n_rerelaxed(self) -> int: ...
    @overload
    def n_rerelaxed(self) -> unsignedlong: ...
    @overload
    def n_to_gen(self) -> int: ...
    @overload
    def n_to_gen(self) -> unsignedlong: ...
    @overload
    def n_to_rerelax(self) -> int: ...
    @overload
    def n_to_rerelax(self) -> unsignedlong: ...
    @overload
    def nparams(self) -> int: ...
    @overload
    def nparams(self) -> unsignedlong: ...
    @overload
    def npick_per_iter(self) -> int: ...
    @overload
    def npick_per_iter(self) -> unsignedlong: ...
    def pick_objfunction(self) -> str: ...
    def pick_strategy(self) -> str: ...
    @overload
    def prepare_enrich_stage(self, decoys: pyrosetta.rosetta.protocols.wum.SilentStructStore, scorename: str) -> None: ...
    @overload
    def prepare_enrich_stage(self, constclassprotocols, conststd) -> void: ...
    @overload
    def prepare_search_stage(self, mpi_rank: int) -> None: ...
    @overload
    def prepare_search_stage(self, constunsignedlong) -> void: ...
    @overload
    def proceed(self) -> None: ...
    @overload
    def proceed(self) -> void: ...
    @overload
    def round_expired(self) -> bool: ...
    @overload
    def round_expired(self) -> bool: ...
    def roundtype(self) -> str: ...
    @overload
    def set_random(self, value: bool) -> None: ...
    @overload
    def set_random(self, constbool) -> void: ...

class Serial_Refine:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Serial_Refine) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose, fixres: pyrosetta.rosetta.utility.vector1_unsigned_long) -> float: ...
    @overload
    def apply(self, classcore, classutility) -> double: ...
    def assign(self) -> Serial_Refine: ...
    @overload
    def init(self) -> None: ...
    @overload
    def init(self) -> void: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...

class StructAvrgMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, decoys: pyrosetta.rosetta.protocols.wum.SilentStructStore, minimize: bool) -> None: ...
    @overload
    def __init__(self, arg0: StructAvrgMover) -> None: ...
    @overload
    def __init__(self, arg0: StructAvrgMover) -> None: ...
    @overload
    def apply(self, ref_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> StructAvrgMover: ...
    def get_name(self) -> str: ...
    @overload
    def report_dev(self, ref_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def report_dev(self, constclasscore) -> void: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_mulfactor(self, mulfactor: float) -> None: ...
    @overload
    def set_mulfactor(self, constdouble) -> void: ...

class WorkUnit_CombinePose(WorkUnit_Sampler):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, nstruct: int, cartesian: bool) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_CombinePose) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_CombinePose) -> None: ...
    def assign(self) -> WorkUnit_CombinePose: ...
    def clone(self) -> pyrosetta.rosetta.protocols.wum.WorkUnitBase: ...
    @overload
    def init_from_cmd(self) -> None: ...
    @overload
    def init_from_cmd(self, constunsignedlong) -> void: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def set_maxfrac(self, setting: float) -> None: ...
    @overload
    def set_maxfrac(self, constdouble) -> void: ...
    @overload
    def set_minfrac(self, setting: float) -> None: ...
    @overload
    def set_minfrac(self, constdouble) -> void: ...

class WorkUnit_FragInsert(WorkUnit_Sampler):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def __init__(self, nsteps: int, scoretype: int, res1: int, res2: int, fullatom: bool) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_FragInsert) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_FragInsert) -> None: ...
    def assign(self) -> WorkUnit_FragInsert: ...
    def clone(self) -> pyrosetta.rosetta.protocols.wum.WorkUnitBase: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def set_nsteps(self, setting: int) -> None: ...
    @overload
    def set_nsteps(self, constunsignedlong) -> void: ...
    @overload
    def set_res1(self, setting: int) -> None: ...
    @overload
    def set_res1(self, constunsignedlong) -> void: ...
    @overload
    def set_res2(self, setting: int) -> None: ...
    @overload
    def set_res2(self, constunsignedlong) -> void: ...
    @overload
    def set_scoretype(self, setting: int) -> None: ...
    @overload
    def set_scoretype(self, constunsignedlong) -> void: ...

class WorkUnit_KicCloser(WorkUnit_Sampler):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def __init__(self, nsteps: int, scoretype: int, res1: int, res2: int, kicclose: bool) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_KicCloser) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_KicCloser) -> None: ...
    def assign(self) -> WorkUnit_KicCloser: ...
    def clone(self) -> pyrosetta.rosetta.protocols.wum.WorkUnitBase: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def set_nsteps(self, setting: int) -> None: ...
    @overload
    def set_nsteps(self, constunsignedlong) -> void: ...
    @overload
    def set_res1(self, setting: int) -> None: ...
    @overload
    def set_res1(self, constunsignedlong) -> void: ...
    @overload
    def set_res2(self, setting: int) -> None: ...
    @overload
    def set_res2(self, constunsignedlong) -> void: ...
    @overload
    def set_scoretype(self, setting: int) -> None: ...
    @overload
    def set_scoretype(self, constunsignedlong) -> void: ...

class WorkUnit_LoopHash(WorkUnit_Sampler):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, start_ir: int, end_ir: int, ssid: int, is_global: int) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_LoopHash) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_LoopHash) -> None: ...
    def assign(self) -> WorkUnit_LoopHash: ...
    def clone(self) -> pyrosetta.rosetta.protocols.wum.WorkUnitBase: ...
    @overload
    def init_from_cmd(self) -> None: ...
    @overload
    def init_from_cmd(self, constunsignedlong) -> void: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def set_end(self, end_ir: int) -> None: ...
    @overload
    def set_end(self, unsignedlong) -> void: ...
    @overload
    def set_global(self, is_global: int) -> None: ...
    @overload
    def set_global(self, unsignedlong) -> void: ...
    @overload
    def set_ssid(self, ssid: int) -> None: ...
    @overload
    def set_ssid(self, unsignedlong) -> void: ...
    @overload
    def set_start(self, start_ir: int) -> None: ...
    @overload
    def set_start(self, unsignedlong) -> void: ...

class WorkUnit_MD(WorkUnit_Sampler):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: float) -> None: ...
    @overload
    def __init__(self, relaxtype: int, scoretype: int, nstruct: int, cstweight: float, looponly: bool) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_MD) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_MD) -> None: ...
    def assign(self) -> WorkUnit_MD: ...
    def clone(self) -> pyrosetta.rosetta.protocols.wum.WorkUnitBase: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def set_cstweight(self, setting: float) -> None: ...
    @overload
    def set_cstweight(self, constdouble) -> void: ...
    @overload
    def set_nstruct(self, setting: int) -> None: ...
    @overload
    def set_nstruct(self, constunsignedlong) -> void: ...
    @overload
    def set_relaxtype(self, setting: int) -> None: ...
    @overload
    def set_relaxtype(self, constunsignedlong) -> void: ...
    @overload
    def set_scoretype(self, setting: int) -> None: ...
    @overload
    def set_scoretype(self, constunsignedlong) -> void: ...

class WorkUnit_NormalMode(WorkUnit_Sampler):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, nmodes: int, nmtype: int, relaxtype: int, maxscale: float) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_NormalMode) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_NormalMode) -> None: ...
    def assign(self) -> WorkUnit_NormalMode: ...
    def clone(self) -> pyrosetta.rosetta.protocols.wum.WorkUnitBase: ...
    @overload
    def init_from_cmd(self) -> None: ...
    @overload
    def init_from_cmd(self, constunsignedlong) -> void: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...

class WorkUnit_PartialAbinitio(WorkUnit_Sampler):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, nsteps: int, reconstruct: bool) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_PartialAbinitio) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_PartialAbinitio) -> None: ...
    def assign(self) -> WorkUnit_PartialAbinitio: ...
    def clone(self) -> pyrosetta.rosetta.protocols.wum.WorkUnitBase: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def set_nsteps(self, setting: int) -> None: ...
    @overload
    def set_nsteps(self, constunsignedlong) -> void: ...
    @overload
    def set_reconstruct(self, setting: int) -> None: ...
    @overload
    def set_reconstruct(self, constunsignedlong) -> void: ...
    @overload
    def set_res1(self, setting: int) -> None: ...
    @overload
    def set_res1(self, constunsignedlong) -> void: ...
    @overload
    def set_res2(self, setting: int) -> None: ...
    @overload
    def set_res2(self, constunsignedlong) -> void: ...

class WorkUnit_RamaPerturber(WorkUnit_Sampler):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, nsteps: int, res1: int, res2: int, kT: float) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_RamaPerturber) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_RamaPerturber) -> None: ...
    def assign(self) -> WorkUnit_RamaPerturber: ...
    def clone(self) -> pyrosetta.rosetta.protocols.wum.WorkUnitBase: ...
    @overload
    def init_from_cmd(self) -> None: ...
    @overload
    def init_from_cmd(self, constunsignedlong) -> void: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def set_kT(self, setting: float) -> None: ...
    @overload
    def set_kT(self, constdouble) -> void: ...
    @overload
    def set_nsteps(self, setting: int) -> None: ...
    @overload
    def set_nsteps(self, constunsignedlong) -> void: ...
    @overload
    def set_res1(self, setting: int) -> None: ...
    @overload
    def set_res1(self, constunsignedlong) -> void: ...
    @overload
    def set_res2(self, setting: int) -> None: ...
    @overload
    def set_res2(self, constunsignedlong) -> void: ...

class WorkUnit_Relax(WorkUnit_Sampler):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, relaxtype: int, scoretype: int, nrepeat: int, cstweight: float) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_Relax) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_Relax) -> None: ...
    def assign(self) -> WorkUnit_Relax: ...
    def clone(self) -> pyrosetta.rosetta.protocols.wum.WorkUnitBase: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def set_cstweight(self, setting: float) -> None: ...
    @overload
    def set_cstweight(self, constdouble) -> void: ...
    @overload
    def set_nrepeat(self, setting: int) -> None: ...
    @overload
    def set_nrepeat(self, constunsignedlong) -> void: ...
    @overload
    def set_relaxtype(self, setting: int) -> None: ...
    @overload
    def set_relaxtype(self, constunsignedlong) -> void: ...
    @overload
    def set_scoretype(self, setting: int) -> None: ...
    @overload
    def set_scoretype(self, constunsignedlong) -> void: ...

class WorkUnit_Sampler(pyrosetta.rosetta.protocols.wum.WorkUnit_SilentStructStore):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_Sampler) -> None: ...
    def assign(self) -> WorkUnit_Sampler: ...
    @overload
    def init_from_cmd(self, mpi_rank: int) -> None: ...
    @overload
    def init_from_cmd(self, constunsignedlong) -> void: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...

class WorkUnit_bbGauss(WorkUnit_Sampler):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: float) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: float, arg2: bool) -> None: ...
    @overload
    def __init__(self, nstruct: int, kT: float, centroid: bool, on_defined_segment: bool) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_bbGauss) -> None: ...
    @overload
    def __init__(self, arg0: WorkUnit_bbGauss) -> None: ...
    def assign(self) -> WorkUnit_bbGauss: ...
    def clone(self) -> pyrosetta.rosetta.protocols.wum.WorkUnitBase: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def set_centroid(self, setting: int) -> None: ...
    @overload
    def set_centroid(self, unsignedlong) -> void: ...
    @overload
    def set_kT(self, setting: float) -> None: ...
    @overload
    def set_kT(self, constdouble) -> void: ...
    @overload
    def set_nstruct(self, setting: int) -> None: ...
    @overload
    def set_nstruct(self, unsignedlong) -> void: ...
    @overload
    def set_segdef(self, setting: int) -> None: ...
    @overload
    def set_segdef(self, unsignedlong) -> void: ...

@overload
def CA_Sscore(ss1: pyrosetta.rosetta.core.io.silent.SilentStruct, ss2: pyrosetta.rosetta.core.io.silent.SilentStruct, rmsd: float, loopres: pyrosetta.rosetta.utility.vector1_unsigned_long) -> float: ...
@overload
def CA_Sscore(ss1: pyrosetta.rosetta.core.io.silent.SilentStruct, ss2: pyrosetta.rosetta.core.io.silent.SilentStruct, rmsd: float, loopres: pyrosetta.rosetta.utility.vector1_unsigned_long, superimpose: bool) -> float: ...
@overload
def CA_Sscore(ss1: pyrosetta.rosetta.core.io.silent.SilentStruct, ss2: pyrosetta.rosetta.core.io.silent.SilentStruct, rmsd: float, loopres: pyrosetta.rosetta.utility.vector1_unsigned_long, superimpose: bool, dbase: float) -> float: ...
@overload
def CA_Sscore(ss1: pyrosetta.rosetta.core.io.silent.SilentStruct, ss2: pyrosetta.rosetta.core.io.silent.SilentStruct, rmsd: float) -> float: ...
@overload
def CA_Sscore(ss1: pyrosetta.rosetta.core.io.silent.SilentStruct, ss2: pyrosetta.rosetta.core.io.silent.SilentStruct, rmsd: float, superimpose: bool) -> float: ...
@overload
def CA_Sscore(ss1: pyrosetta.rosetta.core.io.silent.SilentStruct, ss2: pyrosetta.rosetta.core.io.silent.SilentStruct, rmsd: float, superimpose: bool, dbase: float) -> float: ...
@overload
def Zscore_to_library(score: float, mean: float, stdev: float) -> float: ...
@overload
def Zscore_to_library(score: float, mean: float, stdev: float, maxval: float) -> float: ...
@overload
def Zscore_to_library(score: float, mean: float, stdev: float, maxval: float, minval: float) -> float: ...
@overload
def add_init_dev_penalty(ss: pyrosetta.rosetta.core.io.silent.SilentStruct, init_xyz: pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t) -> None: ...
@overload
def add_init_dev_penalty(ss: pyrosetta.rosetta.core.io.silent.SilentStruct, init_xyz: pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t, mode: str) -> None: ...
@overload
def add_init_dev_penalty(ss: pyrosetta.rosetta.core.io.silent.SilentStruct, init_xyz: pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t, mode: str, iha_cut: float) -> None: ...
@overload
def add_init_dev_penalty(ss: pyrosetta.rosetta.core.io.silent.SilentStruct, init_xyz: pyrosetta.rosetta.ObjexxFCL.FArray2D_double_t, mode: str, iha_cut: float, iha_penalty_slope: float) -> None: ...
@overload
def add_init_dev_penalty(ss: pyrosetta.rosetta.core.io.silent.SilentStruct, pose0: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def add_init_dev_penalty(ss: pyrosetta.rosetta.core.io.silent.SilentStruct, pose0: pyrosetta.rosetta.core.pose.Pose, mode: str) -> None: ...
@overload
def add_init_dev_penalty(ss: pyrosetta.rosetta.core.io.silent.SilentStruct, pose0: pyrosetta.rosetta.core.pose.Pose, mode: str, iha_cut: float) -> None: ...
@overload
def add_init_dev_penalty(ss: pyrosetta.rosetta.core.io.silent.SilentStruct, pose0: pyrosetta.rosetta.core.pose.Pose, mode: str, iha_cut: float, iha_penalty_slope: float) -> None: ...
@overload
def add_init_dev_penalty(structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, pose0: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def add_init_dev_penalty(structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, pose0: pyrosetta.rosetta.core.pose.Pose, mode: str) -> None: ...
@overload
def add_init_dev_penalty(structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, pose0: pyrosetta.rosetta.core.pose.Pose, mode: str, iha_cut: float) -> None: ...
@overload
def add_init_dev_penalty(structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, pose0: pyrosetta.rosetta.core.pose.Pose, mode: str, iha_cut: float, iha_penalty_slope: float) -> None: ...
@overload
def add_movemap_from_loopres(mm: pyrosetta.rosetta.core.kinematics.MoveMap, pose: pyrosetta.rosetta.core.pose.Pose, loopres: pyrosetta.rosetta.utility.vector1_unsigned_long, nonideal: bool) -> None: ...
@overload
def add_movemap_from_loopres(classcore, constclasscore, constclassutility, constbool) -> void: ...
@overload
def add_poseinfo_to_ss(ss: pyrosetta.rosetta.core.io.silent.SilentStruct, ref_pose: pyrosetta.rosetta.core.pose.Pose, suffix: str) -> None: ...
@overload
def add_poseinfo_to_ss(classcore, constclasscore, conststd) -> void: ...
@overload
def constrain_residue(pose: pyrosetta.rosetta.core.pose.Pose, resno: int, exclres: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
@overload
def constrain_residue(pose: pyrosetta.rosetta.core.pose.Pose, resno: int, exclres: pyrosetta.rosetta.utility.vector1_unsigned_long, cst_type: str) -> None: ...
@overload
def constrain_residue(pose: pyrosetta.rosetta.core.pose.Pose, resno: int, exclres: pyrosetta.rosetta.utility.vector1_unsigned_long, cst_type: str, stdev: float) -> None: ...
@overload
def constrain_residue(classcore, constunsignedlong, constclassutility, conststd, constdouble) -> void: ...
@overload
def copy_pose_crd(pose_frame: pyrosetta.rosetta.core.pose.Pose, pose_work: pyrosetta.rosetta.core.pose.Pose, loopregions: pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t) -> None: ...
@overload
def copy_pose_crd(constclasscore, classcore, constclassutility) -> void: ...
def distance(ss1: pyrosetta.rosetta.core.io.silent.SilentStruct, ss2: pyrosetta.rosetta.core.io.silent.SilentStruct, similarity_measure: str, superimpose: bool) -> float: ...
def get_loop_info(ss: pyrosetta.rosetta.core.io.silent.SilentStruct, res1: int, res2: int, is_terminus: bool) -> None: ...
@overload
def get_loop_info_full(ss: pyrosetta.rosetta.core.io.silent.SilentStruct, is_terminus: pyrosetta.rosetta.utility.vector1_bool) -> pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t: ...
@overload
def get_loop_info_full(ss: pyrosetta.rosetta.core.io.silent.SilentStruct, is_terminus: pyrosetta.rosetta.utility.vector1_bool, mode: str) -> pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t: ...
@overload
def get_touched_res(pose: pyrosetta.rosetta.core.pose.Pose, loopres: pyrosetta.rosetta.utility.vector1_unsigned_long) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_touched_res(pose: pyrosetta.rosetta.core.pose.Pose, loopres: pyrosetta.rosetta.utility.vector1_unsigned_long, dist_cut: float) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def loopstring_to_loopregions(loopstr: str) -> pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t: ...
@overload
def loopstring_to_loopvector(loopstr: str) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def loopstring_to_loopvector(loopstr: str, ext: int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def mean_and_stdev(values: pyrosetta.rosetta.utility.vector1_double, frac: float, shave_cut: float, mean: float, stdev: float) -> None: ...
@overload
def ramp_minpack_loop(pose: pyrosetta.rosetta.core.pose.Pose, loopres: pyrosetta.rosetta.utility.vector1_unsigned_long, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
@overload
def ramp_minpack_loop(pose: pyrosetta.rosetta.core.pose.Pose, loopres: pyrosetta.rosetta.utility.vector1_unsigned_long, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, nonideal: bool) -> None: ...
@overload
def ramp_minpack_loop(pose: pyrosetta.rosetta.core.pose.Pose, loopres: pyrosetta.rosetta.utility.vector1_unsigned_long, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, nonideal: bool, ramp: bool) -> None: ...
@overload
def ramp_minpack_loop(pose: pyrosetta.rosetta.core.pose.Pose, loopres: pyrosetta.rosetta.utility.vector1_unsigned_long, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, nonideal: bool, ramp: bool, efficient: bool) -> None: ...
@overload
def ramp_minpack_loop(pose: pyrosetta.rosetta.core.pose.Pose, loopres: pyrosetta.rosetta.utility.vector1_unsigned_long, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, nonideal: bool, ramp: bool, efficient: bool, envmin: bool) -> None: ...
@overload
def ramp_minpack_pose(pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
@overload
def ramp_minpack_pose(pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, nonideal: bool) -> None: ...
@overload
def ramp_minpack_pose(pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, nonideal: bool, ramp: bool) -> None: ...
def read_ss2(ssfile: str) -> pyrosetta.rosetta.std.map_unsigned_long_utility_vector1_double_t_std_allocator_std_pair_const_unsigned_long_utility_vector1_double_t: ...
def setup_packer(pose: pyrosetta.rosetta.core.pose.Pose, mm: pyrosetta.rosetta.core.kinematics.MoveMap, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> pyrosetta.rosetta.protocols.minimization_packing.PackRotamersMover: ...
@overload
def superimpose_all(ss_ref: pyrosetta.rosetta.core.io.silent.SilentStruct, structs: pyrosetta.rosetta.protocols.wum.SilentStructStore) -> None: ...
@overload
def superimpose_all(ss_ref: pyrosetta.rosetta.core.io.silent.SilentStruct, structs: pyrosetta.rosetta.protocols.wum.SilentStructStore, columns_copy: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
@overload
def superimpose_all(classstd, classprotocols, constclassutility) -> void: ...
