import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.optimization
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.numeric.expression_parser
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import typing
from typing import ClassVar, overload

ADDED_STRUCTURE_AS_INTENDED: AddStatus
ADDED_STRUCTURE_OPPOSITE_AS_INTENDED: AddStatus
DID_NOT_ADD_STRUCTURE: AddStatus
END_OF_MINIMIZATION: OptEMultifuncMPIMessages
EVAL_DFUNC: OptEMultifuncMPIMessages
EVAL_FUNC: OptEMultifuncMPIMessages
constrained_optimization_weight_func: OptEPositionDataType
dG_binding_correlation: OptEPositionDataType
ddG_bind_correlation: OptEPositionDataType
ddG_mutation_correlation: OptEPositionDataType
ddG_mutation_correlation_with_unfolded_energy: OptEPositionDataType
n_optE_data_types: OptEPositionDataType
prob_native_amino_acid: OptEPositionDataType
prob_native_amino_acid_with_unfolded_energy: OptEPositionDataType
prob_native_ligand_pose: OptEPositionDataType
prob_native_rotamer: OptEPositionDataType
prob_native_structure: OptEPositionDataType
pssm_data: OptEPositionDataType

class AddStatus:
    __members__: ClassVar[dict] = ...  # read-only
    ADDED_STRUCTURE_AS_INTENDED: ClassVar[AddStatus] = ...
    ADDED_STRUCTURE_OPPOSITE_AS_INTENDED: ClassVar[AddStatus] = ...
    DID_NOT_ADD_STRUCTURE: ClassVar[AddStatus] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class ConstraintedOptimizationWeightFunc(OptEPositionData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    @overload
    def __init__(self, arg0: ConstraintedOptimizationWeightFunc) -> None: ...
    @overload
    def __init__(self, arg0: ConstraintedOptimizationWeightFunc) -> None: ...
    def assign(self) -> ConstraintedOptimizationWeightFunc: ...
    def get_score(self, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    @overload
    def initialize_constraints_from_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def initialize_constraints_from_file(self, std) -> void: ...
    @overload
    def memory_use(self) -> int: ...
    @overload
    def memory_use(self) -> unsignedlong: ...
    def print_score(self, ostr: pyrosetta.rosetta.std.ostream, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    def range(self, free_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, lower_bound: pyrosetta.rosetta.core.scoring.EMapVector, upper_bound: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def read_from_binary_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_binary_file(self, std) -> void: ...
    @overload
    def read_from_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_file(self, std) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def type(self) -> OptEPositionDataType: ...
    @overload
    def write_to_binary_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_binary_file(self, std) -> void: ...
    @overload
    def write_to_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_file(self, std) -> void: ...

class DDGBindOptEData(OptEPositionData):
    class DDG_Bind_File_Index:
        __members__: ClassVar[dict] = ...  # read-only
        MUT_COMPLEXES_LIST_FILE: ClassVar[DDGBindOptEData.DDG_Bind_File_Index] = ...
        MUT_UNBOUNDS_LIST_FILE: ClassVar[DDGBindOptEData.DDG_Bind_File_Index] = ...
        WT_COMPLEXES_LIST_FILE: ClassVar[DDGBindOptEData.DDG_Bind_File_Index] = ...
        WT_UNBOUNDS_LIST_FILE: ClassVar[DDGBindOptEData.DDG_Bind_File_Index] = ...
        __entries: ClassVar[dict] = ...
        def __init__(self, value: int) -> None: ...
        def __and__(self, other: object) -> object: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> int: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> object: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: object) -> object: ...
        def __rand__(self, other: object) -> object: ...
        def __ror__(self, other: object) -> object: ...
        def __rxor__(self, other: object) -> object: ...
        def __xor__(self, other: object) -> object: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...
    MUT_COMPLEXES_LIST_FILE: ClassVar[DDGBindOptEData.DDG_Bind_File_Index] = ...
    MUT_UNBOUNDS_LIST_FILE: ClassVar[DDGBindOptEData.DDG_Bind_File_Index] = ...
    WT_COMPLEXES_LIST_FILE: ClassVar[DDGBindOptEData.DDG_Bind_File_Index] = ...
    WT_UNBOUNDS_LIST_FILE: ClassVar[DDGBindOptEData.DDG_Bind_File_Index] = ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DDGBindOptEData) -> None: ...
    @overload
    def __init__(self, arg0: DDGBindOptEData) -> None: ...
    @overload
    def add_mutant_complex(self, mut: SingleStructureData) -> None: ...
    @overload
    def add_mutant_complex(self, classstd) -> void: ...
    @overload
    def add_mutant_unbounds(self, mut: SingleStructureData) -> None: ...
    @overload
    def add_mutant_unbounds(self, classstd) -> void: ...
    def add_mutation(self, mutation: tuple[int, tuple[pyrosetta.rosetta.core.chemical.AA, pyrosetta.rosetta.core.chemical.AA]]) -> None: ...
    @overload
    def add_wt_complex(self, wt: SingleStructureData) -> None: ...
    @overload
    def add_wt_complex(self, classstd) -> void: ...
    @overload
    def add_wt_unbounds(self, wt: SingleStructureData) -> None: ...
    @overload
    def add_wt_unbounds(self, classstd) -> void: ...
    def assign(self) -> DDGBindOptEData: ...
    def get_score(self, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    @overload
    def memory_use(self) -> int: ...
    @overload
    def memory_use(self) -> unsignedlong: ...
    def print_score(self, ostr: pyrosetta.rosetta.std.ostream, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    def process_score(self, ostr: pyrosetta.rosetta.std.ostream, print: bool, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    def range(self, free_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, lower_bound: pyrosetta.rosetta.core.scoring.EMapVector, upper_bound: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def read_from_binary_file(self) -> None: ...
    @overload
    def read_from_binary_file(self, std) -> void: ...
    @overload
    def read_from_file(self) -> None: ...
    @overload
    def read_from_file(self, std) -> void: ...
    @overload
    def set_experimental_ddg_bind(self, exp_ddg_bind: float) -> None: ...
    @overload
    def set_experimental_ddg_bind(self, double) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def type(self) -> OptEPositionDataType: ...
    @overload
    def write_to_binary_file(self) -> None: ...
    @overload
    def write_to_binary_file(self, std) -> void: ...
    @overload
    def write_to_file(self) -> None: ...
    @overload
    def write_to_file(self, std) -> void: ...

class DDGMutationOptEData(OptEPositionData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DDGMutationOptEData) -> None: ...
    @overload
    def __init__(self, arg0: DDGMutationOptEData) -> None: ...
    @overload
    def add_mutant(self, mut: SingleStructureData) -> None: ...
    @overload
    def add_mutant(self, classstd) -> void: ...
    @overload
    def add_wt(self, wt: SingleStructureData) -> None: ...
    @overload
    def add_wt(self, classstd) -> void: ...
    def assign(self) -> DDGMutationOptEData: ...
    def get_score(self, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    @overload
    def memory_use(self) -> int: ...
    @overload
    def memory_use(self) -> unsignedlong: ...
    def print_score(self, ostr: pyrosetta.rosetta.std.ostream, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    def process_score(self, ostr: pyrosetta.rosetta.std.ostream, print: bool, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    def range(self, free_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, lower_bound: pyrosetta.rosetta.core.scoring.EMapVector, upper_bound: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def read_from_binary_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_binary_file(self, std) -> void: ...
    @overload
    def read_from_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_file(self, std) -> void: ...
    @overload
    def set_experimental_ddg(self, ddg: float) -> None: ...
    @overload
    def set_experimental_ddg(self, double) -> void: ...
    @overload
    def set_mut_aa(self, mut_aa: pyrosetta.rosetta.core.chemical.AA) -> None: ...
    @overload
    def set_mut_aa(self, enumcore) -> void: ...
    @overload
    def set_wt_aa(self, wt_aa: pyrosetta.rosetta.core.chemical.AA) -> None: ...
    @overload
    def set_wt_aa(self, enumcore) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def type(self) -> OptEPositionDataType: ...
    @overload
    def write_to_binary_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_binary_file(self, std) -> void: ...
    @overload
    def write_to_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_file(self, std) -> void: ...

class DGBindOptEData(OptEPositionData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DGBindOptEData) -> None: ...
    @overload
    def __init__(self, arg0: DGBindOptEData) -> None: ...
    def assign(self) -> DGBindOptEData: ...
    @overload
    def bound_struct(self, x: SingleStructureData) -> None: ...
    @overload
    def bound_struct(self, classstd) -> void: ...
    @overload
    def deltaG_bind(self, x: float) -> None: ...
    @overload
    def deltaG_bind(self, double) -> void: ...
    def do_score(self, ostr: pyrosetta.rosetta.std.ostream, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, print: bool) -> float: ...
    def get_score(self, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    @overload
    def memory_use(self) -> int: ...
    @overload
    def memory_use(self) -> unsignedlong: ...
    def print_score(self, ostr: pyrosetta.rosetta.std.ostream, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    def range(self, free_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, lower_bound: pyrosetta.rosetta.core.scoring.EMapVector, upper_bound: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def read_from_binary_file(self) -> None: ...
    @overload
    def read_from_binary_file(self, std) -> void: ...
    @overload
    def read_from_file(self) -> None: ...
    @overload
    def read_from_file(self, std) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def type(self) -> OptEPositionDataType: ...
    @overload
    def unbound_struct(self, x: SingleStructureData) -> None: ...
    @overload
    def unbound_struct(self, classstd) -> void: ...
    @overload
    def write_to_binary_file(self) -> None: ...
    @overload
    def write_to_binary_file(self, std) -> void: ...
    @overload
    def write_to_file(self) -> None: ...
    @overload
    def write_to_file(self, std) -> void: ...

class IterativeOptEDriver:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: IterativeOptEDriver) -> None: ...
    def assign(self) -> IterativeOptEDriver: ...
    @overload
    def go(self) -> None: ...
    @overload
    def go(self) -> void: ...
    @overload
    def task_factory(self) -> None: ...
    @overload
    def task_factory(self, classstd) -> void: ...

class NestedEnergyTermDDGMutationOptEData(DDGMutationOptEData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: NestedEnergyTermDDGMutationOptEData) -> None: ...
    @overload
    def __init__(self, arg0: NestedEnergyTermDDGMutationOptEData) -> None: ...
    def assign(self) -> NestedEnergyTermDDGMutationOptEData: ...
    def get_score(self, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    @overload
    def memory_use(self) -> int: ...
    @overload
    def memory_use(self) -> unsignedlong: ...
    def print_score(self, ostr: pyrosetta.rosetta.std.ostream, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    def process_score(self, ostr: pyrosetta.rosetta.std.ostream, print: bool, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    @overload
    def set_mut_unfolded_energies_emap(self, e: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def set_mut_unfolded_energies_emap(self, constclasscore) -> void: ...
    @overload
    def set_wt_unfolded_energies_emap(self, e: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def set_wt_unfolded_energies_emap(self, constclasscore) -> void: ...
    def type(self) -> OptEPositionDataType: ...

class NestedEnergyTermPNatAAOptEPositionData(PNatAAOptEPositionData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: NestedEnergyTermPNatAAOptEPositionData) -> None: ...
    @overload
    def __init__(self, arg0: NestedEnergyTermPNatAAOptEPositionData) -> None: ...
    def assign(self) -> NestedEnergyTermPNatAAOptEPositionData: ...
    def get_score(self, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    @overload
    def memory_use(self) -> int: ...
    @overload
    def memory_use(self) -> unsignedlong: ...
    def print_score(self, ostr: pyrosetta.rosetta.std.ostream, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    def process_score(self, ostr: pyrosetta.rosetta.std.ostream, print: bool, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    @overload
    def read_from_binary_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_binary_file(self, std) -> void: ...
    @overload
    def read_from_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_file(self, std) -> void: ...
    @overload
    def set_unfolded_energy_emap_vector(self, emap_vector: pyrosetta.rosetta.utility.vector1_core_scoring_EMapVector) -> None: ...
    @overload
    def set_unfolded_energy_emap_vector(self, classutility) -> void: ...
    def type(self) -> OptEPositionDataType: ...
    def unfolded_energy_emap_vector(self) -> pyrosetta.rosetta.utility.vector1_core_scoring_EMapVector: ...
    @overload
    def write_to_binary_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_binary_file(self, std) -> void: ...
    @overload
    def write_to_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_file(self, std) -> void: ...

class OptEData:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, free_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    @overload
    def __init__(self, arg0: OptEData) -> None: ...
    @overload
    def add_position_data(self, pos_data_in: OptEPositionData) -> None: ...
    @overload
    def add_position_data(self, classstd) -> void: ...
    def assign(self) -> OptEData: ...
    def energy_terms(self) -> pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType: ...
    def fixed_energy_terms(self) -> pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType: ...
    @overload
    def num_positions(self) -> int: ...
    @overload
    def num_positions(self) -> unsignedlong: ...
    @overload
    def num_rotamers(self) -> int: ...
    @overload
    def num_rotamers(self) -> unsignedlong: ...
    @overload
    def read_from_binary_file(self, filename: str) -> None: ...
    @overload
    def read_from_binary_file(self, std) -> void: ...
    @overload
    def read_from_file(self, filename: str) -> None: ...
    @overload
    def read_from_file(self, std) -> void: ...
    @overload
    def write_to_binary_file(self) -> None: ...
    @overload
    def write_to_binary_file(self, filename: str) -> None: ...
    @overload
    def write_to_binary_file(self, std) -> void: ...
    @overload
    def write_to_file(self) -> None: ...
    @overload
    def write_to_file(self, filename: str) -> None: ...
    @overload
    def write_to_file(self, std) -> void: ...

class OptEMultifunc(pyrosetta.rosetta.core.optimization.Multifunc):
    @overload
    def __init__(self, opte_data_in: OptEData, fixed_terms_in: pyrosetta.rosetta.core.scoring.EMapVector, num_free_in: int, score_list_in: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list_in: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, component_weights: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, opte_data_in: OptEData, fixed_terms_in: pyrosetta.rosetta.core.scoring.EMapVector, num_free_in: int, score_list_in: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list_in: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, reference_energies_in: pyrosetta.rosetta.utility.vector1_double, component_weights: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, arg0: OptEMultifunc) -> None: ...
    @overload
    def __init__(self, arg0: OptEMultifunc) -> None: ...
    @overload
    def declare_minimization_over(self) -> None: ...
    @overload
    def declare_minimization_over(self) -> void: ...
    @overload
    def dfunc(self, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def dfunc(self, constclassutility, classutility) -> void: ...
    @overload
    def fix_reference_energies(self, setting: bool) -> None: ...
    @overload
    def fix_reference_energies(self, bool) -> void: ...
    @overload
    def fix_reference_energies(self) -> bool: ...
    @overload
    def fix_reference_energies(self) -> bool: ...
    def get_dofs_from_energy_map(self, start_vals: pyrosetta.rosetta.core.scoring.EMapVector) -> pyrosetta.rosetta.utility.vector1_double: ...
    def get_energy_map_from_dofs(self, dofs: pyrosetta.rosetta.utility.vector1_double) -> pyrosetta.rosetta.core.scoring.EMapVector: ...
    def get_reference_energies_from_dofs(self, dofs: pyrosetta.rosetta.utility.vector1_double) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def set_starting_reference_energies(self, values: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_starting_reference_energies(self, constclassutility) -> void: ...
    @overload
    def wait_for_remote_vars(self) -> None: ...
    @overload
    def wait_for_remote_vars(self) -> void: ...
    def __call__(self, vars: pyrosetta.rosetta.utility.vector1_double) -> float: ...

class OptEMultifuncMPIMessages:
    __members__: ClassVar[dict] = ...  # read-only
    END_OF_MINIMIZATION: ClassVar[OptEMultifuncMPIMessages] = ...
    EVAL_DFUNC: ClassVar[OptEMultifuncMPIMessages] = ...
    EVAL_FUNC: ClassVar[OptEMultifuncMPIMessages] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OptEPositionData:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: OptEPositionData) -> None: ...
    def assign(self) -> OptEPositionData: ...
    def get_score(self, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    @overload
    def memory_use(self) -> int: ...
    @overload
    def memory_use(self) -> unsignedlong: ...
    def print_score(self, ostr: pyrosetta.rosetta.std.ostream, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    def range(self, free_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, lower_bound: pyrosetta.rosetta.core.scoring.EMapVector, upper_bound: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def read_from_binary_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_binary_file(self, std) -> void: ...
    @overload
    def read_from_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_file(self, std) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def tag(self, tag_in: str) -> None: ...
    @overload
    def tag(self, conststd) -> void: ...
    @overload
    def tag(self) -> str: ...
    def type(self) -> OptEPositionDataType: ...
    @overload
    def write_to_binary_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_binary_file(self, std) -> void: ...
    @overload
    def write_to_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_file(self, std) -> void: ...

class OptEPositionDataFactory:
    def __init__(self) -> None: ...
    @staticmethod
    def create_position_data(type: OptEPositionDataType) -> OptEPositionData: ...
    @overload
    @staticmethod
    def is_optE_type_name(name: str) -> bool: ...
    @overload
    @staticmethod
    def is_optE_type_name(conststd) -> bool: ...
    @staticmethod
    def optE_type_from_name(name: str) -> OptEPositionDataType: ...
    @staticmethod
    def optE_type_name(type: OptEPositionDataType) -> str: ...

class OptEPositionDataType:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    constrained_optimization_weight_func: ClassVar[OptEPositionDataType] = ...
    dG_binding_correlation: ClassVar[OptEPositionDataType] = ...
    ddG_bind_correlation: ClassVar[OptEPositionDataType] = ...
    ddG_mutation_correlation: ClassVar[OptEPositionDataType] = ...
    ddG_mutation_correlation_with_unfolded_energy: ClassVar[OptEPositionDataType] = ...
    n_optE_data_types: ClassVar[OptEPositionDataType] = ...
    prob_native_amino_acid: ClassVar[OptEPositionDataType] = ...
    prob_native_amino_acid_with_unfolded_energy: ClassVar[OptEPositionDataType] = ...
    prob_native_ligand_pose: ClassVar[OptEPositionDataType] = ...
    prob_native_rotamer: ClassVar[OptEPositionDataType] = ...
    prob_native_structure: ClassVar[OptEPositionDataType] = ...
    pssm_data: ClassVar[OptEPositionDataType] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OptEVariableExpression(pyrosetta.rosetta.numeric.expression_parser.VariableExpression):
    @overload
    def __init__(self, name: str) -> None: ...
    @overload
    def __init__(self, name: str, value: float) -> None: ...
    def assign(self) -> OptEVariableExpression: ...
    @overload
    def id(self) -> int: ...
    @overload
    def id(self) -> unsignedlong: ...
    @overload
    def set_id(self, id: int) -> None: ...
    @overload
    def set_id(self, unsignedlong) -> void: ...
    @overload
    def update_value_from_list(self, value_vector: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def update_value_from_list(self, constclassutility) -> void: ...

class PNatAAOptEPositionData(OptEPositionData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PNatAAOptEPositionData) -> None: ...
    @overload
    def __init__(self, arg0: PNatAAOptEPositionData) -> None: ...
    @overload
    def add_rotamer_line_data(self, rot_in: PNatAAOptERotamerData) -> None: ...
    @overload
    def add_rotamer_line_data(self, classstd) -> void: ...
    def assign(self) -> PNatAAOptEPositionData: ...
    def data(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_optimize_weights_PNatAAOptERotamerData_t: ...
    def get_score(self, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    @overload
    def memory_use(self) -> int: ...
    @overload
    def memory_use(self) -> unsignedlong: ...
    def native_aa(self) -> pyrosetta.rosetta.core.chemical.AA: ...
    @overload
    def neighbor_count(self) -> int: ...
    @overload
    def neighbor_count(self) -> unsignedlong: ...
    @overload
    def position(self) -> int: ...
    @overload
    def position(self) -> unsignedlong: ...
    def print_score(self, ostr: pyrosetta.rosetta.std.ostream, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    def range(self, free_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, lower_bound: pyrosetta.rosetta.core.scoring.EMapVector, upper_bound: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def read_from_binary_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_binary_file(self, std) -> void: ...
    @overload
    def read_from_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_file(self, std) -> void: ...
    @overload
    def set_native_aa(self, nat_in: pyrosetta.rosetta.core.chemical.AA) -> None: ...
    @overload
    def set_native_aa(self, enumcore) -> void: ...
    @overload
    def set_neighbor_count(self, nb_in: int) -> None: ...
    @overload
    def set_neighbor_count(self, unsignedlong) -> void: ...
    @overload
    def set_position(self, pos_in: int) -> None: ...
    @overload
    def set_position(self, unsignedlong) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def type(self) -> OptEPositionDataType: ...
    @overload
    def write_to_binary_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_binary_file(self, std) -> void: ...
    @overload
    def write_to_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_file(self, std) -> void: ...

class PNatAAOptERotamerData:
    @overload
    def __init__(self, aa_in: pyrosetta.rosetta.core.chemical.AA, rot_num_in: int, data_vec_in: pyrosetta.rosetta.utility.vector1_double, fixed_data_vec_in: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, arg0: PNatAAOptERotamerData) -> None: ...
    def assign(self) -> PNatAAOptERotamerData: ...
    def data(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    def fixed_data(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def rot_number(self) -> int: ...
    @overload
    def rot_number(self) -> unsignedlong: ...
    def this_aa(self) -> pyrosetta.rosetta.core.chemical.AA: ...
    def __getitem__(self, i: int) -> float: ...
    def __iter__(self) -> typing.Iterator[float]: ...

class PNatLigPoseOptEData(PNatStructureOptEData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PNatLigPoseOptEData) -> None: ...
    @overload
    def __init__(self, arg0: PNatLigPoseOptEData) -> None: ...
    def assign(self) -> PNatLigPoseOptEData: ...
    def do_score(self, ostr: pyrosetta.rosetta.std.ostream, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, print: bool) -> float: ...
    def get_score(self, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    def print_score(self, ostr: pyrosetta.rosetta.std.ostream, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    def type(self) -> OptEPositionDataType: ...

class PNatRotOptEPositionData(OptEPositionData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PNatRotOptEPositionData) -> None: ...
    @overload
    def __init__(self, arg0: PNatRotOptEPositionData) -> None: ...
    def aa(self) -> pyrosetta.rosetta.core.chemical.AA: ...
    @overload
    def add_rotamer_line_data(self, rot_in: PNatRotOptERotamerData) -> None: ...
    @overload
    def add_rotamer_line_data(self, classstd) -> void: ...
    def assign(self) -> PNatRotOptEPositionData: ...
    @overload
    def count_rotamer_as_native(self, rotamer: PNatRotOptERotamerData) -> bool: ...
    @overload
    def count_rotamer_as_native(self, classstd) -> bool: ...
    def data(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_optimize_weights_PNatRotOptERotamerData_t: ...
    def get_score(self, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    @overload
    def memory_use(self) -> int: ...
    @overload
    def memory_use(self) -> unsignedlong: ...
    def phi(self) -> float: ...
    def print_score(self, ostr: pyrosetta.rosetta.std.ostream, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    def process_score(self, ostr: pyrosetta.rosetta.std.ostream, print: bool, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    def psi(self) -> float: ...
    def range(self, free_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, lower_bound: pyrosetta.rosetta.core.scoring.EMapVector, upper_bound: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def read_from_binary_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_binary_file(self, std) -> void: ...
    @overload
    def read_from_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_file(self, std) -> void: ...
    @overload
    def set_native_chi_periodicity(self, native_chi_periodicity: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_native_chi_periodicity(self, constclassutility) -> void: ...
    @overload
    def set_native_rotamer_chi(self, native_chi: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_native_rotamer_chi(self, constclassutility) -> void: ...
    @overload
    def set_native_rotamer_index(self, native_rotamer_index: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_native_rotamer_index(self, constclassutility) -> void: ...
    @overload
    def set_rotamer_well_counts(self, rotamer_well_counts: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_rotamer_well_counts(self, constclassutility) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def type(self) -> OptEPositionDataType: ...
    @overload
    def write_to_binary_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_binary_file(self, std) -> void: ...
    @overload
    def write_to_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_file(self, std) -> void: ...

class PNatRotOptERotamerData:
    @overload
    def __init__(self, rotamer_index: pyrosetta.rosetta.utility.vector1_unsigned_long, chi: pyrosetta.rosetta.utility.vector1_double, free_data: pyrosetta.rosetta.utility.vector1_double, fixed_data: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, arg0: PNatRotOptERotamerData) -> None: ...
    def assign(self) -> PNatRotOptERotamerData: ...
    def chi(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    def fixed_data(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    def free_data(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    def rotamer_index(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def __getitem__(self, i: int) -> float: ...
    def __iter__(self) -> typing.Iterator[float]: ...

class PNatStructureOptEData(OptEPositionData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PNatStructureOptEData) -> None: ...
    @overload
    def __init__(self, arg0: PNatStructureOptEData) -> None: ...
    @overload
    def add_decoy(self, decoy: SingleStructureData) -> None: ...
    @overload
    def add_decoy(self, classstd) -> void: ...
    @overload
    def add_native(self, native: SingleStructureData) -> None: ...
    @overload
    def add_native(self, classstd) -> void: ...
    def assign(self) -> PNatStructureOptEData: ...
    def get_score(self, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    @overload
    def memory_use(self) -> int: ...
    @overload
    def memory_use(self) -> unsignedlong: ...
    @overload
    def n_top_natives_to_score(self, n_top: int) -> None: ...
    @overload
    def n_top_natives_to_score(self, unsignedlong) -> void: ...
    @overload
    def n_top_natives_to_score(self) -> int: ...
    @overload
    def n_top_natives_to_score(self) -> unsignedlong: ...
    @overload
    def nativeness(self, rms: float) -> float: ...
    @overload
    def nativeness(self, double) -> double: ...
    @overload
    @staticmethod
    def nativeness_high() -> float: ...
    @overload
    @staticmethod
    def nativeness_high() -> double: ...
    @overload
    @staticmethod
    def nativeness_low() -> float: ...
    @overload
    @staticmethod
    def nativeness_low() -> double: ...
    def print_score(self, ostr: pyrosetta.rosetta.std.ostream, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    def process_score(self, ostr: pyrosetta.rosetta.std.ostream, print: bool, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    def range(self, free_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, lower_bound: pyrosetta.rosetta.core.scoring.EMapVector, upper_bound: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def read_from_binary_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_binary_file(self, std) -> void: ...
    @overload
    def read_from_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_file(self, std) -> void: ...
    @overload
    def set_initial_decoy_stddev(self, setting: float) -> None: ...
    @overload
    def set_initial_decoy_stddev(self, double) -> void: ...
    @overload
    @staticmethod
    def set_nativeness_high(nativeness_rms_low: float) -> None: ...
    @overload
    @staticmethod
    def set_nativeness_high(double) -> void: ...
    @overload
    @staticmethod
    def set_nativeness_low(nativeness_rms_low: float) -> None: ...
    @overload
    @staticmethod
    def set_nativeness_low(double) -> void: ...
    @overload
    def set_normalize_decoy_stddev(self, setting: bool) -> None: ...
    @overload
    def set_normalize_decoy_stddev(self, bool) -> void: ...
    @overload
    def set_total_residue(self, total_residue: int) -> None: ...
    @overload
    def set_total_residue(self, unsignedlong) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def type(self) -> OptEPositionDataType: ...
    @overload
    def write_to_binary_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_binary_file(self, std) -> void: ...
    @overload
    def write_to_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_file(self, std) -> void: ...

class PSSMOptEPositionData(PNatAAOptEPositionData):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PSSMOptEPositionData) -> None: ...
    @overload
    def __init__(self, arg0: PSSMOptEPositionData) -> None: ...
    def assign(self) -> PSSMOptEPositionData: ...
    def get_score(self, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> float: ...
    @overload
    def memory_use(self) -> int: ...
    @overload
    def memory_use(self) -> unsignedlong: ...
    def print_score(self, ostr: pyrosetta.rosetta.std.ostream, component_weights: pyrosetta.rosetta.utility.vector1_double, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double, num_energy_dofs: int, num_ref_dofs: int, num_total_dofs: int, fixed_terms: pyrosetta.rosetta.core.scoring.EMapVector, score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    @overload
    def read_from_binary_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_binary_file(self, std) -> void: ...
    @overload
    def read_from_file(self, infile: pyrosetta.rosetta.std.ifstream) -> None: ...
    @overload
    def read_from_file(self, std) -> void: ...
    @overload
    def set_pssm_probabilities(self, pssm_probs: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_pssm_probabilities(self, constclassutility) -> void: ...
    def type(self) -> OptEPositionDataType: ...
    @overload
    def write_to_binary_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_binary_file(self, std) -> void: ...
    @overload
    def write_to_file(self, outfile: pyrosetta.rosetta.std.ofstream) -> None: ...
    @overload
    def write_to_file(self, std) -> void: ...

class SingleStructureData:
    @overload
    def __init__(self, free_data: pyrosetta.rosetta.utility.vector1_double, fixed_data: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, arg0: SingleStructureData) -> None: ...
    def assign(self) -> SingleStructureData: ...
    def fixed_data(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    def free_data(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def rms(self) -> float: ...
    @overload
    def rms(self) -> double: ...
    @overload
    def rms(self, rms_in: float) -> None: ...
    @overload
    def rms(self, double) -> void: ...
    @overload
    def tag(self) -> str: ...
    @overload
    def tag(self, setting: str) -> None: ...
    @overload
    def tag(self, conststd) -> void: ...
    def __getitem__(self, i: int) -> float: ...
    def __iter__(self) -> typing.Iterator[float]: ...

class WeightRangeConstraint:
    active_: bool
    max_weight_: float
    min_weight_: float
    spring_constant_: float
    def __init__(self) -> None: ...

class WrappedOptEExpressionCreator(pyrosetta.rosetta.numeric.expression_parser.ExpressionCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, multifunc: pyrosetta.rosetta.std.weak_ptr_protocols_optimize_weights_WrapperOptEMultifunc_t) -> None: ...
    @overload
    def __init__(self, arg0: WrappedOptEExpressionCreator) -> None: ...
    @overload
    def __init__(self, arg0: WrappedOptEExpressionCreator) -> None: ...
    def assign(self) -> WrappedOptEExpressionCreator: ...
    def handle_function_expression(self, function: pyrosetta.rosetta.numeric.expression_parser.FunctionToken, args: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_numeric_expression_parser_Expression_t) -> pyrosetta.rosetta.numeric.expression_parser.Expression: ...
    def handle_variable_expression(self) -> pyrosetta.rosetta.numeric.expression_parser.Expression: ...
    @overload
    def set_wrapping_optE_multifunc(self, multifunc: pyrosetta.rosetta.std.weak_ptr_protocols_optimize_weights_WrapperOptEMultifunc_t) -> None: ...
    @overload
    def set_wrapping_optE_multifunc(self, classstd) -> void: ...

class WrapperOptEMultifunc(pyrosetta.rosetta.core.optimization.Multifunc):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: WrapperOptEMultifunc) -> None: ...
    @overload
    def __init__(self, arg0: WrapperOptEMultifunc) -> None: ...
    def assign(self) -> WrapperOptEMultifunc: ...
    def derived_dofs(self, vars: pyrosetta.rosetta.utility.vector1_double) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def dfunc(self, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def dfunc(self, constclassutility, classutility) -> void: ...
    def get_self_ptr(self) -> WrapperOptEMultifunc: ...
    def get_self_weak_ptr(self) -> pyrosetta.rosetta.std.weak_ptr_protocols_optimize_weights_WrapperOptEMultifunc_t: ...
    def init(self, free_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, free_count: int, fixed_score_list: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType, fixed_scores: pyrosetta.rosetta.core.scoring.EMapVector, optEfunc: OptEMultifunc) -> None: ...
    @overload
    def n_real_dofs(self) -> int: ...
    @overload
    def n_real_dofs(self) -> unsignedlong: ...
    @overload
    def print_dofs(self, vars: pyrosetta.rosetta.utility.vector1_double, ostr: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def print_dofs(self, constclassutility, std) -> void: ...
    def register_variable_expression(self, varname: str) -> pyrosetta.rosetta.numeric.expression_parser.VariableExpression: ...
    @overload
    def set_multifunc(self, multifunc: OptEMultifunc) -> None: ...
    @overload
    def set_multifunc(self, classstd) -> void: ...
    def __call__(self, vars: pyrosetta.rosetta.utility.vector1_double) -> float: ...

@overload
def load_component_weights(component_weights: pyrosetta.rosetta.utility.vector1_double) -> None: ...
@overload
def load_component_weights(classutility) -> void: ...
