import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.utility
from typing import overload

class AlterSpecDisruptionDriver(PointMutScanDriver):
    @overload
    def __init__(self, pdb_file_names: pyrosetta.rosetta.utility.vector1_std_string, double_mutant_scan: bool, list_file: str, output_mutant_structures: bool) -> None: ...
    @overload
    def __init__(self, arg0: AlterSpecDisruptionDriver) -> None: ...
    @overload
    def __init__(self, arg0: AlterSpecDisruptionDriver) -> None: ...
    def assign(self) -> AlterSpecDisruptionDriver: ...
    @overload
    def reject_mutant(self, mutant, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def reject_mutant(self, constclassprotocols, constclasscore) -> bool: ...
    @overload
    def score(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def score(self, classcore) -> double: ...

class Mutant:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Mutant) -> None: ...
    @overload
    def add_mutation(self, md: MutationData) -> None: ...
    @overload
    def add_mutation(self, classprotocols) -> void: ...
    def assign(self) -> Mutant: ...
    @overload
    def n_mutations(self) -> int: ...
    @overload
    def n_mutations(self) -> unsignedlong: ...
    def pop_mutation(self) -> MutationData: ...
    def __eq__(self, m_other: Mutant) -> bool: ...

class MutationData:
    def __init__(self, wt_residue: str, mut_residue: str, pose_resnum: int, pdb_resnum: int, icode: str, chain: str) -> None: ...
    @overload
    def mut_residue(self) -> str: ...
    @overload
    def mut_residue(self) -> char: ...
    def mutation_string(self) -> str: ...
    def mutation_string_PDB_numbering(self) -> str: ...
    @overload
    def pdb_chain(self) -> str: ...
    @overload
    def pdb_chain(self) -> char: ...
    @overload
    def pose_resnum(self) -> int: ...
    @overload
    def pose_resnum(self) -> unsignedlong: ...
    @overload
    def print_mutation_data(self, md: MutationData) -> None: ...
    @overload
    def print_mutation_data(self, classprotocols) -> void: ...
    def __eq__(self, md_other: MutationData) -> bool: ...

class PointMutScanDriver:
    @overload
    def __init__(self, pdb_file_names: pyrosetta.rosetta.utility.vector1_std_string, double_mutant_scan: bool, list_file: str, output_mutant_structures: bool) -> None: ...
    @overload
    def __init__(self, arg0: PointMutScanDriver) -> None: ...
    @overload
    def __init__(self, arg0: PointMutScanDriver) -> None: ...
    def assign(self) -> PointMutScanDriver: ...
    @overload
    def calculate_neighbor_table(self, pose: pyrosetta.rosetta.core.pose.Pose, neighbors: pyrosetta.rosetta.utility.vector1_utility_vector1_bool_t) -> None: ...
    @overload
    def calculate_neighbor_table(self, classcore, classutility) -> void: ...
    @overload
    def fill_mutations_list(self) -> None: ...
    @overload
    def fill_mutations_list(self) -> void: ...
    def get_scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def go(self) -> None: ...
    @overload
    def go(self) -> void: ...
    @overload
    def make_specific_mutant(self, mutant_poses: pyrosetta.rosetta.utility.vector1_core_pose_Pose, native_poses: pyrosetta.rosetta.utility.vector1_core_pose_Pose, m) -> None: ...
    @overload
    def make_specific_mutant(self, mutant_poses: pyrosetta.rosetta.utility.vector1_core_pose_Pose, native_poses: pyrosetta.rosetta.utility.vector1_core_pose_Pose, m, mutation_string: str) -> None: ...
    @overload
    def make_specific_mutant(self, mutant_poses: pyrosetta.rosetta.utility.vector1_core_pose_Pose, native_poses: pyrosetta.rosetta.utility.vector1_core_pose_Pose, m, mutation_string: str, mutation_string_PDB_numbering: str) -> None: ...
    @overload
    def n_mutants(self) -> int: ...
    @overload
    def n_mutants(self) -> unsignedlong: ...
    @overload
    def read_in_structures(self) -> None: ...
    @overload
    def read_in_structures(self) -> void: ...
    @overload
    def reject_mutant(self) -> bool: ...
    @overload
    def reject_mutant(self, constclassprotocols, constclasscore) -> bool: ...
    @overload
    def score(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def score(self, classcore) -> double: ...
    @overload
    def set_ddG_cutoff(self, threshold: float) -> None: ...
    @overload
    def set_ddG_cutoff(self, double) -> void: ...
