import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.protocols.rosetta_scripts
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import overload

class AndSelector(LogicalSelector):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AndSelector) -> None: ...
    @overload
    def __init__(self, arg0: AndSelector) -> None: ...
    def assign(self) -> AndSelector: ...
    def get_name(self) -> str: ...
    @staticmethod
    def name() -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema() -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class AndSelectorCreator(pyrosetta.rosetta.protocols.rosetta_scripts.PoseSelectorCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AndSelectorCreator) -> None: ...
    @overload
    def __init__(self, arg0: AndSelectorCreator) -> None: ...
    def assign(self) -> AndSelectorCreator: ...
    def create_selector(self, *args, **kwargs): ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ClusterPoseSelector(pyrosetta.rosetta.protocols.rosetta_scripts.PoseSelector):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ClusterPoseSelector) -> None: ...
    @overload
    def __init__(self, arg0: ClusterPoseSelector) -> None: ...
    def assign(self) -> ClusterPoseSelector: ...
    def get_flags(self) -> pyrosetta.rosetta.protocols.rosetta_scripts.PoseSelectorFlags: ...
    def get_name(self) -> str: ...
    @staticmethod
    def name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def select_poses(self, poses: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t) -> pyrosetta.rosetta.utility.vector1_bool: ...

class ClusterPoseSelectorCreator(pyrosetta.rosetta.protocols.rosetta_scripts.PoseSelectorCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ClusterPoseSelectorCreator) -> None: ...
    @overload
    def __init__(self, arg0: ClusterPoseSelectorCreator) -> None: ...
    def assign(self) -> ClusterPoseSelectorCreator: ...
    def create_selector(self) -> pyrosetta.rosetta.protocols.rosetta_scripts.PoseSelector: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class Filter(pyrosetta.rosetta.protocols.rosetta_scripts.PoseSelector):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Filter) -> None: ...
    @overload
    def __init__(self, arg0: Filter) -> None: ...
    def assign(self) -> Filter: ...
    def get_flags(self) -> pyrosetta.rosetta.protocols.rosetta_scripts.PoseSelectorFlags: ...
    def get_name(self) -> str: ...
    @staticmethod
    def name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema() -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def select_poses(self, poses: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t) -> pyrosetta.rosetta.utility.vector1_bool: ...

class FilterCreator(pyrosetta.rosetta.protocols.rosetta_scripts.PoseSelectorCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FilterCreator) -> None: ...
    @overload
    def __init__(self, arg0: FilterCreator) -> None: ...
    def assign(self) -> FilterCreator: ...
    def create_selector(self, *args, **kwargs): ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class LogicalSelector(pyrosetta.rosetta.protocols.rosetta_scripts.PoseSelector):
    def __init__(self, *args, **kwargs) -> None: ...
    def assign(self) -> LogicalSelector: ...
    @staticmethod
    def complex_type_generator_for_logical_selector(*args, **kwargs): ...
    def get_flags(self) -> pyrosetta.rosetta.protocols.rosetta_scripts.PoseSelectorFlags: ...
    def get_name(self) -> str: ...
    @staticmethod
    def name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    def select_poses(self, poses: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t) -> pyrosetta.rosetta.utility.vector1_bool: ...

class OrSelector(LogicalSelector):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: OrSelector) -> None: ...
    @overload
    def __init__(self, arg0: OrSelector) -> None: ...
    def assign(self) -> OrSelector: ...
    def get_name(self) -> str: ...
    @staticmethod
    def name() -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema() -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class OrSelectorCreator(pyrosetta.rosetta.protocols.rosetta_scripts.PoseSelectorCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: OrSelectorCreator) -> None: ...
    @overload
    def __init__(self, arg0: OrSelectorCreator) -> None: ...
    def assign(self) -> OrSelectorCreator: ...
    def create_selector(self, *args, **kwargs): ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class TopNByProperty(pyrosetta.rosetta.protocols.rosetta_scripts.PoseSelector):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TopNByProperty) -> None: ...
    @overload
    def __init__(self, arg0: TopNByProperty) -> None: ...
    def assign(self) -> TopNByProperty: ...
    def get_flags(self) -> pyrosetta.rosetta.protocols.rosetta_scripts.PoseSelectorFlags: ...
    def get_name(self) -> str: ...
    @staticmethod
    def name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema() -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def select_poses(self, poses: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t) -> pyrosetta.rosetta.utility.vector1_bool: ...

class TopNByPropertyCreator(pyrosetta.rosetta.protocols.rosetta_scripts.PoseSelectorCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TopNByPropertyCreator) -> None: ...
    @overload
    def __init__(self, arg0: TopNByPropertyCreator) -> None: ...
    def assign(self) -> TopNByPropertyCreator: ...
    def create_selector(self, *args, **kwargs): ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
