import pyrosetta.rosetta.basic.citation_manager
import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.core.simple_metrics
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import overload

class ProteinMPNNMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ProteinMPNNMover) -> None: ...
    @overload
    def __init__(self, arg0: ProteinMPNNMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> ProteinMPNNMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @staticmethod
    def residue_selectors_to_indices(pose: pyrosetta.rosetta.core.pose.Pose, residue_selectors: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_select_residue_selector_ResidueSelector_t) -> pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t: ...
    @overload
    def set_coord_selector_rs(self, coord_selector_rs: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_coord_selector_rs(self, classstd) -> void: ...
    @overload
    def set_design_selector_rs(self, design_selector_rs: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_design_selector_rs(self, classstd) -> void: ...
    @overload
    def set_deterministic_flag(self, deterministic_flag: bool) -> None: ...
    @overload
    def set_deterministic_flag(self, bool) -> void: ...
    @overload
    def set_omit_AAs(self, omit_AAs: pyrosetta.rosetta.utility.vector1_char) -> None: ...
    @overload
    def set_omit_AAs(self, classutility) -> void: ...
    @overload
    def set_temperature(self, temperature: float) -> None: ...
    @overload
    def set_temperature(self, double) -> void: ...
    @overload
    def set_tied_pos_rs(self, tied_pos_rs: pyrosetta.rosetta.utility.vector1_utility_vector1_std_shared_ptr_const_core_select_residue_selector_ResidueSelector_t) -> None: ...
    @overload
    def set_tied_pos_rs(self, classutility) -> void: ...
    @overload
    @staticmethod
    def validate_residue_selectors(selection_positions: pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t, expected_size: int) -> None: ...
    @overload
    @staticmethod
    def validate_residue_selectors(constclassutility, constunsignedlong) -> void: ...

class ProteinMPNNMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ProteinMPNNMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: ProteinMPNNMoverCreator) -> None: ...
    def assign(self) -> ProteinMPNNMoverCreator: ...

class ProteinMPNNProbabilitiesMetric(pyrosetta.rosetta.core.simple_metrics.PerResidueProbabilitiesMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ProteinMPNNProbabilitiesMetric) -> None: ...
    @overload
    def __init__(self, arg0: ProteinMPNNProbabilitiesMetric) -> None: ...
    def assign(self) -> ProteinMPNNProbabilitiesMetric: ...
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    @overload
    def deterministic_flag(self) -> bool: ...
    @overload
    def deterministic_flag(self) -> bool: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self, citations: pyrosetta.rosetta.basic.citation_manager.CitationCollectionList) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def residue_selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_coord_selector_rs(self, coord_selector_rs: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_coord_selector_rs(self, classstd) -> void: ...
    @overload
    def set_deterministic_flag(self, deterministic_flag: bool) -> None: ...
    @overload
    def set_deterministic_flag(self, bool) -> void: ...
    @overload
    def set_residue_selector(self, selector_in: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    @overload
    def set_sequence_mask_selector_rs(self, sequence_mask_selector_rs: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_sequence_mask_selector_rs(self, classstd) -> void: ...
    @overload
    def set_tied_pos_rs(self, tied_pos_rs: pyrosetta.rosetta.utility.vector1_utility_vector1_std_shared_ptr_const_core_select_residue_selector_ResidueSelector_t) -> None: ...
    @overload
    def set_tied_pos_rs(self, classutility) -> void: ...
    def write_pssm(self) -> str: ...

class ProteinMPNNProbabilitiesMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> ProteinMPNNProbabilitiesMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
