import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.filters
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import overload

class FindConsensusSequence(pyrosetta.rosetta.protocols.moves.VectorPoseMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FindConsensusSequence) -> None: ...
    @overload
    def __init__(self, arg0: FindConsensusSequence) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    @overload
    def apply_mpi(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply_mpi(self, classcore) -> void: ...
    def assign(self) -> FindConsensusSequence: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def designable_residues(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def initialize_packer(self) -> None: ...
    @overload
    def initialize_packer(self) -> void: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def parse_resfiles(self) -> None: ...
    @overload
    def parse_resfiles(self) -> void: ...
    @overload
    def pick_consensus_AA(self, res_link_index: int, candidate_AAs: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def pick_consensus_AA(self, unsignedlong, classutility) -> void: ...
    @overload
    def pick_consensus_AA_mpi(self, pose: pyrosetta.rosetta.core.pose.Pose, candidate_AAs: pyrosetta.rosetta.utility.vector1_std_string, pose_position: int) -> None: ...
    @overload
    def pick_consensus_AA_mpi(self, classcore, classutility, unsignedlong) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def resfile_at(self, index: int) -> str: ...
    @overload
    def resfiles(self, resfiles: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def resfiles(self, classutility) -> void: ...
    @overload
    def score_function(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def score_function(self) -> None: ...
    @overload
    def score_function(self, classstd) -> void: ...
    @overload
    def task_factory(self) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    @overload
    def task_factory(self) -> None: ...
    @overload
    def task_factory(self, classstd) -> void: ...
    @overload
    def test_AA(self, pose_copy: pyrosetta.rosetta.core.pose.Pose, trial_AA: str, pose_position: int) -> float: ...
    @overload
    def test_AA(self, classstd, std, unsignedlong) -> double: ...

class FindConsensusSequenceCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FindConsensusSequenceCreator) -> None: ...
    @overload
    def __init__(self, arg0: FindConsensusSequenceCreator) -> None: ...
    def assign(self) -> FindConsensusSequenceCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class FitnessFilter(pyrosetta.rosetta.protocols.filters.VectorPoseFilter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FitnessFilter) -> None: ...
    @overload
    def __init__(self, arg0: FitnessFilter) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def apply(self, constclasscore) -> bool: ...
    @overload
    def apply_mpi(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def apply_mpi(self, constclasscore) -> bool: ...
    @overload
    def calculate_fitness(self) -> float: ...
    @overload
    def calculate_fitness(self, constclasscore) -> double: ...
    @overload
    def calculate_fitness_mpi(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate_fitness_mpi(self, constclasscore) -> double: ...
    def clone(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def report(self) -> None: ...
    @overload
    def report(self, std, constclasscore) -> void: ...
    @overload
    def report_sm(self) -> float: ...
    @overload
    def report_sm(self, constclasscore) -> double: ...
    @overload
    def sfxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def sfxn(self) -> None: ...
    @overload
    def sfxn(self, classstd) -> void: ...
    @overload
    def threshold(self) -> float: ...
    @overload
    def threshold(self) -> double: ...
    @overload
    def threshold(self) -> None: ...
    @overload
    def threshold(self, double) -> void: ...

class FitnessFilterCreator(pyrosetta.rosetta.protocols.filters.FilterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FitnessFilterCreator) -> None: ...
    @overload
    def __init__(self, arg0: FitnessFilterCreator) -> None: ...
    def assign(self) -> FitnessFilterCreator: ...
    def create_filter(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class MSDMover(pyrosetta.rosetta.protocols.moves.VectorPoseMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, mover: pyrosetta.rosetta.protocols.moves.Mover, resfiles: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def __init__(self, arg0: MSDMover) -> None: ...
    @overload
    def __init__(self, arg0: MSDMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def apply_linked_constraints(self, pose: pyrosetta.rosetta.core.pose.Pose, other_pose_sequences: pyrosetta.rosetta.utility.vector1_utility_vector1_std_string_t, my_designable_residues: pyrosetta.rosetta.utility.vector1_unsigned_long) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_scoring_constraints_Constraint_t: ...
    @overload
    def apply_mpi(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply_mpi(self, classcore) -> void: ...
    def assign(self) -> MSDMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def design_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def design_mover(self, design_mover: pyrosetta.rosetta.protocols.moves.Mover) -> None: ...
    @overload
    def design_mover(self, classstd) -> void: ...
    def designable_residues(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def resfiles(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def resfiles(self, resfiles: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def resfiles(self, classutility) -> void: ...
    @overload
    def setup_mover(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def setup_mover(self, classcore) -> void: ...
    @overload
    def weight(self, weight: float) -> None: ...
    @overload
    def weight(self, double) -> void: ...
    @overload
    def weight(self) -> float: ...
    @overload
    def weight(self) -> double: ...

class MSDMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MSDMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: MSDMoverCreator) -> None: ...
    def assign(self) -> MSDMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

@overload
def find_pose_in_vector(pose: pyrosetta.rosetta.core.pose.Pose, poses: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t) -> int: ...
@overload
def find_pose_in_vector(constclasscore, classutility) -> unsignedlong: ...
def get_candidate_AAs(other_pose_sequences: pyrosetta.rosetta.utility.vector1_utility_vector1_std_string_t, position_no: int) -> pyrosetta.rosetta.utility.vector1_std_string: ...
def get_designable_residues(pose: pyrosetta.rosetta.core.pose.Pose, resfile: str) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_designable_sequence(pose: pyrosetta.rosetta.core.pose.Pose, designable_residues: pyrosetta.rosetta.utility.vector1_unsigned_long) -> pyrosetta.rosetta.utility.vector1_std_string: ...
