import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.conformation.symmetry
import pyrosetta.rosetta.core.environment
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.protocols.canonical_sampling
import pyrosetta.rosetta.protocols.environment
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import ClassVar, overload

c2n: Direction
n2c: Direction
partner_downstream: Partner
partner_upstream: Partner
random: Direction

class Direction:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    c2n: ClassVar[Direction] = ...
    n2c: ClassVar[Direction] = ...
    random: ClassVar[Direction] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class MembraneCenterPerturbationMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, trans_mag_in: float) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> MembraneCenterPerturbationMover: ...
    def get_name(self) -> str: ...

class MembraneNormalPerturbationMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rotation_mag_in: float) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> MembraneNormalPerturbationMover: ...
    def get_name(self) -> str: ...

class MovePoseToMembraneCenterMover(pyrosetta.rosetta.protocols.moves.Mover):
    def __init__(self) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> MovePoseToMembraneCenterMover: ...
    def estimate_membrane_center(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def get_name(self) -> str: ...

class Partner:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    partner_downstream: ClassVar[Partner] = ...
    partner_upstream: ClassVar[Partner] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class RigidBodyDeterministicSpinMover(RigidBodySpinMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rb_jump_in: int, spin_axis: pyrosetta.rosetta.numeric.xyzVector_double_t, rotation_center: pyrosetta.rosetta.numeric.xyzVector_double_t, angle_magnitude: float) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDeterministicSpinMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDeterministicSpinMover) -> None: ...
    @overload
    def angle_magnitude(self, angle_magnitude: float) -> None: ...
    @overload
    def angle_magnitude(self, float) -> void: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyDeterministicSpinMover: ...
    def get_name(self) -> str: ...

class RigidBodyDofPerturbMover(RigidBodyMover):
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.std.map_unsigned_long_core_conformation_symmetry_SymDof) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.std.map_unsigned_long_core_conformation_symmetry_SymDof, arg1: float) -> None: ...
    @overload
    def __init__(self, dofs: pyrosetta.rosetta.std.map_unsigned_long_core_conformation_symmetry_SymDof, rot_mag_in: float, trans_mag_in: float) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: pyrosetta.rosetta.core.conformation.symmetry.SymDof) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: pyrosetta.rosetta.core.conformation.symmetry.SymDof, arg2: float) -> None: ...
    @overload
    def __init__(self, rb_jump_in: int, dof: pyrosetta.rosetta.core.conformation.symmetry.SymDof, rot_mag_in: float, trans_mag_in: float) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDofPerturbMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDofPerturbMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyDofPerturbMover: ...
    @overload
    def dof(self, dof: pyrosetta.rosetta.core.conformation.symmetry.SymDof) -> None: ...
    @overload
    def dof(self, classcore) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def rot_magnitude(self, magnitude: float) -> None: ...
    @overload
    def rot_magnitude(self, constdouble) -> void: ...
    @overload
    def trans_magnitude(self, magnitude: float) -> None: ...
    @overload
    def trans_magnitude(self, constdouble) -> void: ...

class RigidBodyDofRandomTransMover(RigidBodyMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, dofs: pyrosetta.rosetta.std.map_unsigned_long_core_conformation_symmetry_SymDof) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDofRandomTransMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDofRandomTransMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyDofRandomTransMover: ...
    def get_name(self) -> str: ...
    @overload
    def step_size(self, step_size_in: float) -> None: ...
    @overload
    def step_size(self, double) -> void: ...
    @overload
    def trans_axis(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def trans_axis(self, trans_axis_in: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def trans_axis(self, classnumeric) -> void: ...

class RigidBodyDofRandomizeMover(RigidBodyMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDofRandomizeMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDofRandomizeMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyDofRandomizeMover: ...
    def get_name(self) -> str: ...

class RigidBodyDofSeqPerturbMover(RigidBodyMover):
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.std.map_unsigned_long_core_conformation_symmetry_SymDof) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.std.map_unsigned_long_core_conformation_symmetry_SymDof, arg1: float) -> None: ...
    @overload
    def __init__(self, dofs: pyrosetta.rosetta.std.map_unsigned_long_core_conformation_symmetry_SymDof, rot_mag_in: float, trans_mag_in: float) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDofSeqPerturbMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDofSeqPerturbMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyDofSeqPerturbMover: ...
    @overload
    def dofs(self, dofs: pyrosetta.rosetta.std.map_unsigned_long_core_conformation_symmetry_SymDof) -> None: ...
    @overload
    def dofs(self, classstd, classcore) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def rot_magnitude(self, magnitude: float) -> None: ...
    @overload
    def rot_magnitude(self, constdouble) -> void: ...
    @overload
    def trans_magnitude(self, magnitude: float) -> None: ...
    @overload
    def trans_magnitude(self, constdouble) -> void: ...

class RigidBodyDofSeqRandomizeMover(RigidBodyMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, dofs: pyrosetta.rosetta.std.map_unsigned_long_core_conformation_symmetry_SymDof) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDofSeqRandomizeMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDofSeqRandomizeMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyDofSeqRandomizeMover: ...
    def get_name(self) -> str: ...

class RigidBodyDofSeqTransMover(RigidBodyMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, dofs: pyrosetta.rosetta.std.map_unsigned_long_core_conformation_symmetry_SymDof) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDofSeqTransMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDofSeqTransMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyDofSeqTransMover: ...
    def get_name(self) -> str: ...
    @overload
    def step_size(self, step_size_in: float) -> None: ...
    @overload
    def step_size(self, double) -> void: ...
    @overload
    def trans_axis(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def trans_axis(self, trans_axis_in: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def trans_axis(self, classnumeric) -> void: ...

class RigidBodyDofTransMover(RigidBodyMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, dof: pyrosetta.rosetta.core.conformation.symmetry.SymDof, rb_jump_in: int, step_size: float) -> None: ...
    @overload
    def __init__(self, dofs: pyrosetta.rosetta.std.map_unsigned_long_core_conformation_symmetry_SymDof) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDofTransMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyDofTransMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyDofTransMover: ...
    def get_name(self) -> str: ...
    @overload
    def last_slide_good(self) -> bool: ...
    @overload
    def last_slide_good(self) -> bool: ...
    @overload
    def step_size(self, step_size_in: float) -> None: ...
    @overload
    def step_size(self, double) -> void: ...
    @overload
    def trans_axis(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def trans_axis(self, trans_axis_in: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def trans_axis(self, classnumeric) -> void: ...

class RigidBodyMotionMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, tree: pyrosetta.rosetta.core.kinematics.FoldTree) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyMotionMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyMotionMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyMotionMover: ...
    @overload
    def chainbreak_bias(self) -> float: ...
    @overload
    def chainbreak_bias(self) -> double: ...
    def fold_tree(self) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    def get_name(self) -> str: ...
    @overload
    def magnitude_rotation(self) -> float: ...
    @overload
    def magnitude_rotation(self) -> double: ...
    @overload
    def magnitude_translation(self) -> float: ...
    @overload
    def magnitude_translation(self) -> double: ...
    @overload
    def set_chainbreak_bias(self, cb_bias: float) -> None: ...
    @overload
    def set_chainbreak_bias(self, double) -> void: ...
    @overload
    def set_fold_tree(self, tree: pyrosetta.rosetta.core.kinematics.FoldTree) -> None: ...
    @overload
    def set_fold_tree(self, constclasscore) -> void: ...
    @overload
    def set_magnitude_rotation(self, mag_rot: float) -> None: ...
    @overload
    def set_magnitude_rotation(self, double) -> void: ...
    @overload
    def set_magnitude_translation(self, mag_trans: float) -> None: ...
    @overload
    def set_magnitude_translation(self, double) -> void: ...

class RigidBodyMover(pyrosetta.rosetta.protocols.canonical_sampling.ThermodynamicMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, rb_jump_in: int, dir_in: Direction) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyMover: ...
    @overload
    def freeze(self) -> None: ...
    @overload
    def freeze(self) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def preserve_detailed_balance(self) -> bool: ...
    @overload
    def preserve_detailed_balance(self) -> bool: ...
    @overload
    def rb_jump(self) -> int: ...
    @overload
    def rb_jump(self) -> int: ...
    @overload
    def rb_jump(self, jump_id: int) -> None: ...
    @overload
    def rb_jump(self, int) -> void: ...
    @overload
    def rot_center(self, rot_center_in: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def rot_center(self, constclassnumeric) -> void: ...
    @overload
    def set_preserve_detailed_balance(self) -> None: ...
    @overload
    def set_preserve_detailed_balance(self, bool) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def torsion_id_ranges(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_core_id_TorsionID_Range: ...
    @overload
    def unfreeze(self) -> None: ...
    @overload
    def unfreeze(self) -> void: ...

class RigidBodyPerturbMover(RigidBodyMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: float, arg2: float) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: float, arg2: float, arg3: Partner) -> None: ...
    @overload
    def __init__(self, rb_jump_in: int, rot_mag_in: float, trans_mag_in: float, partner_in: Partner, interface_in: bool) -> None: ...
    @overload
    def __init__(self, rb_jump_in: int, rot_mag_in: float, trans_mag_in: float, partner_in: Partner, ok_for_centroid_calculation: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: pyrosetta.rosetta.core.kinematics.MoveMap, arg2: float, arg3: float) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: pyrosetta.rosetta.core.kinematics.MoveMap, arg2: float, arg3: float, arg4: Partner) -> None: ...
    @overload
    def __init__(self, pose_in: pyrosetta.rosetta.core.pose.Pose, mm: pyrosetta.rosetta.core.kinematics.MoveMap, rot_mag_in: float, trans_mag_in: float, partner_in: Partner, interface_in: bool) -> None: ...
    @overload
    def __init__(self, arg0: float, arg1: float) -> None: ...
    @overload
    def __init__(self, arg0: float, arg1: float, arg2: Partner) -> None: ...
    @overload
    def __init__(self, rot_mag_in: float, trans_mag_in: float, partner_in: Partner, interface_in: bool) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyPerturbMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyPerturbMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyPerturbMover: ...
    def get_name(self) -> str: ...
    @overload
    def get_rot_mag(self) -> float: ...
    @overload
    def get_rot_mag(self) -> double: ...
    @overload
    def get_trans_mag(self) -> float: ...
    @overload
    def get_trans_mag(self) -> double: ...
    @overload
    def rot_center(self) -> None: ...
    @overload
    def rot_center(self, constclassnumeric) -> void: ...
    @overload
    def rot_magnitude(self, magnitude: float) -> None: ...
    @overload
    def rot_magnitude(self, constdouble) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def trans_magnitude(self, magnitude: float) -> None: ...
    @overload
    def trans_magnitude(self, constdouble) -> void: ...

class RigidBodyPerturbNoCenterMover(RigidBodyMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rb_jump_in: int, rot_mag_in: float, trans_mag_in: float) -> None: ...
    @overload
    def __init__(self, pose_in: pyrosetta.rosetta.core.pose.Pose, mm: pyrosetta.rosetta.core.kinematics.MoveMap, rot_mag_in: float, trans_mag_in: float, dir_in: Direction) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyPerturbNoCenterMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyPerturbNoCenterMover) -> None: ...
    @overload
    def add_jump(self) -> None: ...
    @overload
    def add_jump(self, unsignedlong) -> void: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyPerturbNoCenterMover: ...
    @overload
    def clear_jumps(self) -> None: ...
    @overload
    def clear_jumps(self) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def rot_magnitude(self, magnitude: float) -> None: ...
    @overload
    def rot_magnitude(self, constdouble) -> void: ...
    @overload
    def trans_magnitude(self, magnitude: float) -> None: ...
    @overload
    def trans_magnitude(self, constdouble) -> void: ...

class RigidBodyPerturbNoCenterMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyPerturbNoCenterMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyPerturbNoCenterMoverCreator) -> None: ...
    def assign(self) -> RigidBodyPerturbNoCenterMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class RigidBodyPerturbRandomJumpMover(RigidBodyMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rot_mag_in: float, trans_mag_in: float, num_jump_in: int) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyPerturbRandomJumpMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyPerturbRandomJumpMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyPerturbRandomJumpMover: ...
    def get_name(self) -> str: ...

class RigidBodyRandomizeMover(RigidBodyMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: int, arg2: Partner) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: int, arg2: Partner, arg3: float) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: int, arg2: Partner, arg3: float, arg4: float) -> None: ...
    @overload
    def __init__(self, pose_in: pyrosetta.rosetta.core.pose.Pose, rb_jump_in: int, partner_in: Partner, phi_angle: float, psi_angle: float, update_center_after_move: bool) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyRandomizeMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyRandomizeMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyRandomizeMover: ...
    def get_name(self) -> str: ...
    @overload
    def get_phi(self) -> float: ...
    @overload
    def get_phi(self) -> double: ...
    @overload
    def get_psi(self) -> float: ...
    @overload
    def get_psi(self) -> double: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class RigidBodySpinMover(RigidBodyMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rb_jump_in: int) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodySpinMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodySpinMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodySpinMover: ...
    def get_name(self) -> str: ...
    @overload
    def rot_center(self, rot_center_in: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def rot_center(self, constclassnumeric) -> void: ...
    @overload
    def spin_axis(self, spin_axis_in: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def spin_axis(self, classnumeric) -> void: ...
    def spin_mag(self, spin_mag: float) -> None: ...

class RigidBodyTiltMover(RigidBodyMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rb_jump_in: int, tilt1_mag_in: float, tilt2_mag_in: float, tilt1_center_in: int, tilt2_center_in: int) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyTiltMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyTiltMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyTiltMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def spin_axis(self, spin_axis_in: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def spin_axis(self, constclassnumeric) -> void: ...
    @overload
    def tilt1_center(self, tilt1_center_in: int) -> None: ...
    @overload
    def tilt1_center(self, constunsignedlong) -> void: ...
    @overload
    def tilt1_center(self, tilt1_center_in: pyrosetta.rosetta.core.pose.ResidueIndexDescription) -> None: ...
    @overload
    def tilt1_center(self, classstd) -> void: ...
    @overload
    def tilt1_mag(self, tilt1_mag_in: float) -> None: ...
    @overload
    def tilt1_mag(self, constdouble) -> void: ...
    @overload
    def tilt2_center(self, tilt2_center_in: int) -> None: ...
    @overload
    def tilt2_center(self, constunsignedlong) -> void: ...
    @overload
    def tilt2_center(self, tilt2_center_in: pyrosetta.rosetta.core.pose.ResidueIndexDescription) -> None: ...
    @overload
    def tilt2_center(self, classstd) -> void: ...
    @overload
    def tilt2_mag(self, tilt2_mag_in: float) -> None: ...
    @overload
    def tilt2_mag(self, constdouble) -> void: ...

class RigidBodyTiltMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyTiltMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyTiltMoverCreator) -> None: ...
    def assign(self) -> RigidBodyTiltMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class RigidBodyTransMover(RigidBodyMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, vary_stepsize: bool) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: int) -> None: ...
    @overload
    def __init__(self, pose_in: pyrosetta.rosetta.core.pose.Pose, rb_jump_in: int, vary_stepsize: bool) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.numeric.xyzVector_double_t, arg1: int) -> None: ...
    @overload
    def __init__(self, trans_axis: pyrosetta.rosetta.numeric.xyzVector_double_t, rb_jump_in: int, vary_stepsize: bool) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyTransMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyTransMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidBodyTransMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def step_size(self, step_size_in: float) -> None: ...
    @overload
    def step_size(self, double) -> void: ...
    @overload
    def step_size(self) -> float: ...
    @overload
    def step_size(self) -> double: ...
    @overload
    def trans_axis(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def trans_axis(self, trans_axis_in: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def trans_axis(self, classnumeric) -> void: ...
    @overload
    def vary_stepsize(self, vary: bool) -> None: ...
    @overload
    def vary_stepsize(self, bool) -> void: ...

class RigidBodyTransMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyTransMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyTransMoverCreator) -> None: ...
    def assign(self) -> RigidBodyTransMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class RollMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: float, arg3: float, arg4: pyrosetta.rosetta.numeric.xyzVector_double_t, arg5: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def __init__(self, start_res: int, stop_res: int, min_angle: float, max_angle: float, axis: pyrosetta.rosetta.numeric.xyzVector_double_t, translate: pyrosetta.rosetta.numeric.xyzVector_double_t, legacy_mode: bool) -> None: ...
    @overload
    def __init__(self, arg0: RollMover) -> None: ...
    @overload
    def __init__(self, arg0: RollMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RollMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def set_min_max_angles(self, min_angle: float, max_angle: float) -> None: ...

class RollMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RollMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: RollMoverCreator) -> None: ...
    def assign(self) -> RollMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class RotateJumpAxisMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, rb_jump_num: int) -> None: ...
    @overload
    def __init__(self, rb_jump_num: int, upper: float, lower: float) -> None: ...
    @overload
    def __init__(self, rb_jump_num: int, angle: float) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def get_name(self) -> str: ...

class UniformRigidBodyCM(pyrosetta.rosetta.protocols.environment.ClientMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: pyrosetta.rosetta.core.environment.LocalPosition, arg2: pyrosetta.rosetta.core.environment.LocalPosition) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: pyrosetta.rosetta.core.environment.LocalPosition, arg2: pyrosetta.rosetta.core.environment.LocalPosition, arg3: float) -> None: ...
    @overload
    def __init__(self, name: str, mobile: pyrosetta.rosetta.core.environment.LocalPosition, stationary: pyrosetta.rosetta.core.environment.LocalPosition, rotation_magnitude: float, translation_magnitude: float) -> None: ...
    @overload
    def __init__(self, arg0: UniformRigidBodyCM) -> None: ...
    @overload
    def __init__(self, arg0: UniformRigidBodyCM) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> UniformRigidBodyCM: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def initialize(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def initialize(self, classcore) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def name(self) -> str: ...
    @overload
    def name(self, name: str) -> None: ...
    @overload
    def name(self, conststd) -> void: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def yield_claims(self) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_environment_claims_EnvClaim_t: ...

class UniformRigidBodyCMCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: UniformRigidBodyCMCreator) -> None: ...
    @overload
    def __init__(self, arg0: UniformRigidBodyCMCreator) -> None: ...
    def assign(self) -> UniformRigidBodyCMCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class UniformRigidBodyMover(pyrosetta.rosetta.protocols.canonical_sampling.ThermodynamicMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: float) -> None: ...
    @overload
    def __init__(self, target_jump: int, rotation_mag_: float, translation_mag_: float) -> None: ...
    @overload
    def __init__(self, arg0: UniformRigidBodyMover) -> None: ...
    @overload
    def __init__(self, arg0: UniformRigidBodyMover) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> UniformRigidBodyMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @staticmethod
    def complex_type_gen(*args, **kwargs): ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def jump_number(self) -> None: ...
    @overload
    def jump_number(self, int) -> void: ...
    @overload
    def jump_number(self) -> int: ...
    @overload
    def jump_number(self) -> int: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def preserve_detailed_balance(self) -> bool: ...
    @overload
    def preserve_detailed_balance(self) -> bool: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_preserve_detailed_balance(self) -> None: ...
    @overload
    def set_preserve_detailed_balance(self, bool) -> void: ...
    def torsion_id_ranges(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_core_id_TorsionID_Range: ...

class UniformRigidBodyMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: UniformRigidBodyMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: UniformRigidBodyMoverCreator) -> None: ...
    def assign(self) -> UniformRigidBodyMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class UniformSphereTransMover(RigidBodyMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rb_jump_in: int, step_size_in: float) -> None: ...
    @overload
    def __init__(self, arg0: UniformSphereTransMover) -> None: ...
    @overload
    def __init__(self, arg0: UniformSphereTransMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> UniformSphereTransMover: ...
    def get_name(self) -> str: ...

class WholeBodyRotationMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, axis: pyrosetta.rosetta.numeric.xyzVector_double_t, center: pyrosetta.rosetta.numeric.xyzVector_double_t, alpha: float) -> None: ...
    @overload
    def __init__(self, arg0: WholeBodyRotationMover) -> None: ...
    @overload
    def __init__(self, arg0: WholeBodyRotationMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> WholeBodyRotationMover: ...
    def get_name(self) -> str: ...

class WholeBodyTranslationMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, trans_in: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def __init__(self, arg0: WholeBodyTranslationMover) -> None: ...
    @overload
    def __init__(self, arg0: WholeBodyTranslationMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> WholeBodyTranslationMover: ...
    def get_name(self) -> str: ...

@overload
def gaussian_jump_move(pose: pyrosetta.rosetta.core.pose.Pose, mm: pyrosetta.rosetta.core.kinematics.MoveMap, translation_magnitude: float, rotation_magnitude: float) -> int: ...
@overload
def gaussian_jump_move(pose: pyrosetta.rosetta.core.pose.Pose, mm: pyrosetta.rosetta.core.kinematics.MoveMap, translation_magnitude: float, rotation_magnitude: float, dir: int) -> int: ...
@overload
def gaussian_jump_move(pose: pyrosetta.rosetta.core.pose.Pose, jump_number: int, translation_magnitude: float, rotation_magnitude: float) -> None: ...
@overload
def gaussian_jump_move(pose: pyrosetta.rosetta.core.pose.Pose, jump_number: int, translation_magnitude: float, rotation_magnitude: float, dir: int) -> None: ...
