import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.features
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.sql_database
import pyrosetta.rosetta.utility.tag
from typing import ClassVar, overload

OL_features: OutputLevel
OL_full: OutputLevel
OL_none: OutputLevel

class OutputLevel:
    __members__: ClassVar[dict] = ...  # read-only
    OL_features: ClassVar[OutputLevel] = ...
    OL_full: ClassVar[OutputLevel] = ...
    OL_none: ClassVar[OutputLevel] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class PerNativeRRReporterHuman:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, native_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: PerNativeRRReporterHuman) -> None: ...
    def assign(self) -> PerNativeRRReporterHuman: ...
    @overload
    def initialized(self) -> bool: ...
    @overload
    def initialized(self) -> bool: ...
    def report_rotamer_recovery(self, res: pyrosetta.rosetta.core.conformation.Residue, score: float, recovered: bool) -> None: ...
    @overload
    def set_native(self, native_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_native(self, constclasscore) -> void: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream, column_width: int) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream, column_width: int, precision: int) -> None: ...

class RRComparer:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRComparer) -> None: ...
    def assign(self) -> RRComparer: ...
    def get_name(self) -> str: ...
    def get_parameters(self) -> str: ...
    def measure_rotamer_recovery(self, pose1: pyrosetta.rosetta.core.pose.Pose, pose2: pyrosetta.rosetta.core.pose.Pose, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, score: float, recovered: bool) -> bool: ...
    @overload
    def parse_attributes_from_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_attributes_from_tag(self, classstd) -> void: ...
    @overload
    def set_absolute_threshold(self, absolute_threshold: float) -> None: ...
    @overload
    def set_absolute_threshold(self, constdouble) -> void: ...
    @overload
    def set_recovery_threshold(self, recovery_threshold: float) -> None: ...
    @overload
    def set_recovery_threshold(self, constdouble) -> void: ...

class RRComparerAutomorphicRMSD(RRComparer):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerAutomorphicRMSD) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerAutomorphicRMSD) -> None: ...
    def assign(self) -> RRComparerAutomorphicRMSD: ...
    @overload
    def get_absolute_threshold(self) -> float: ...
    @overload
    def get_absolute_threshold(self) -> double: ...
    @overload
    def get_include_backbone_atoms(self) -> bool: ...
    @overload
    def get_include_backbone_atoms(self) -> bool: ...
    def get_name(self) -> str: ...
    def get_parameters(self) -> str: ...
    @overload
    def get_recovery_threshold(self) -> float: ...
    @overload
    def get_recovery_threshold(self) -> double: ...
    def measure_rotamer_recovery(self, pose1: pyrosetta.rosetta.core.pose.Pose, pose2: pyrosetta.rosetta.core.pose.Pose, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, score: float, recovered: bool) -> bool: ...
    @overload
    def set_absolute_threshold(self, absolute_threshold: float) -> None: ...
    @overload
    def set_absolute_threshold(self, constdouble) -> void: ...
    @overload
    def set_include_backbone_atoms(self, include_backbone_atoms: bool) -> None: ...
    @overload
    def set_include_backbone_atoms(self, constbool) -> void: ...
    @overload
    def set_recovery_threshold(self, recovery_threshold: float) -> None: ...
    @overload
    def set_recovery_threshold(self, constdouble) -> void: ...

class RRComparerAutomorphicRMSDCreator(RRComparerCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerAutomorphicRMSDCreator) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerAutomorphicRMSDCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRComparerAutomorphicRMSDCreator: ...
    def create_comparer(self) -> RRComparer: ...
    def type_name(self) -> str: ...

class RRComparerChiDiff(RRComparer):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerChiDiff) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerChiDiff) -> None: ...
    @overload
    @staticmethod
    def append_attributes(attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    @staticmethod
    def append_attributes(classstd) -> void: ...
    def assign(self) -> RRComparerChiDiff: ...
    def get_name(self) -> str: ...
    def get_parameters(self) -> str: ...
    def measure_rotamer_recovery(self, pose1: pyrosetta.rosetta.core.pose.Pose, pose2: pyrosetta.rosetta.core.pose.Pose, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, score: float, recovered: bool) -> bool: ...
    @overload
    def parse_attributes_from_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_attributes_from_tag(self, classstd) -> void: ...
    @overload
    def set_absolute_threshold(self, setting: float) -> None: ...
    @overload
    def set_absolute_threshold(self, constdouble) -> void: ...
    @overload
    def set_max_chi_considered(self, max_chi: int) -> None: ...
    @overload
    def set_max_chi_considered(self, constunsignedlong) -> void: ...
    @overload
    def set_recovery_threshold(self, setting: float) -> None: ...
    @overload
    def set_recovery_threshold(self, constdouble) -> void: ...

class RRComparerChiDiffCreator(RRComparerCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerChiDiffCreator) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerChiDiffCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRComparerChiDiffCreator: ...
    def create_comparer(self) -> RRComparer: ...
    def type_name(self) -> str: ...

class RRComparerCreator:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRComparerCreator: ...
    def create_comparer(self) -> RRComparer: ...
    def type_name(self) -> str: ...

class RRComparerElecDensDiff(RRComparer):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerElecDensDiff) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerElecDensDiff) -> None: ...
    def assign(self) -> RRComparerElecDensDiff: ...
    @overload
    def get_absolute_threshold(self) -> float: ...
    @overload
    def get_absolute_threshold(self) -> double: ...
    def get_name(self) -> str: ...
    def get_parameters(self) -> str: ...
    @overload
    def get_recovery_threshold(self) -> float: ...
    @overload
    def get_recovery_threshold(self) -> double: ...
    def measure_rotamer_recovery(self, pose1: pyrosetta.rosetta.core.pose.Pose, pose2: pyrosetta.rosetta.core.pose.Pose, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, score: float, recovered: bool) -> bool: ...
    @overload
    def set_absolute_threshold(self, absolute_threshold: float) -> None: ...
    @overload
    def set_absolute_threshold(self, constdouble) -> void: ...
    @overload
    def set_recovery_threshold(self, recovery_threshold: float) -> None: ...
    @overload
    def set_recovery_threshold(self, constdouble) -> void: ...

class RRComparerElecDensDiffCreator(RRComparerCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerElecDensDiffCreator) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerElecDensDiffCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRComparerElecDensDiffCreator: ...
    def create_comparer(self) -> RRComparer: ...
    def type_name(self) -> str: ...

class RRComparerRotBins(RRComparer):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerRotBins) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerRotBins) -> None: ...
    def assign(self) -> RRComparerRotBins: ...
    def get_name(self) -> str: ...
    def get_parameters(self) -> str: ...
    def measure_rotamer_recovery(self, pose1: pyrosetta.rosetta.core.pose.Pose, pose2: pyrosetta.rosetta.core.pose.Pose, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, score: float, recovered: bool) -> bool: ...
    @overload
    def parse_attributes_from_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_attributes_from_tag(self, classstd) -> void: ...
    @overload
    def set_absolute_threshold(self, absolute_threshold: float) -> None: ...
    @overload
    def set_absolute_threshold(self, constdouble) -> void: ...
    @overload
    def set_recovery_threshold(self, recovery_threshold: float) -> None: ...
    @overload
    def set_recovery_threshold(self, constdouble) -> void: ...

class RRComparerRotBinsCreator(RRComparerCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerRotBinsCreator) -> None: ...
    @overload
    def __init__(self, arg0: RRComparerRotBinsCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRComparerRotBinsCreator: ...
    def create_comparer(self) -> RRComparer: ...
    def type_name(self) -> str: ...

class RRProtocol:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocol) -> None: ...
    def assign(self) -> RRProtocol: ...
    def get_name(self) -> str: ...
    def get_parameters(self) -> str: ...
    @overload
    def parse_attributes_from_tag(self, dm: pyrosetta.rosetta.basic.datacache.DataMap, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_attributes_from_tag(self, constclassbasic, classstd) -> void: ...
    def run(self, comparer: RRComparer, reporter, pose: pyrosetta.rosetta.core.pose.Pose, score_function: pyrosetta.rosetta.core.scoring.ScoreFunction, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...

class RRProtocolCreator:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRProtocolCreator: ...
    def create_protocol(self) -> RRProtocol: ...
    def type_name(self) -> str: ...

class RRProtocolMinPack(RRProtocol):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolMinPack) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolMinPack) -> None: ...
    def assign(self) -> RRProtocolMinPack: ...
    def get_name(self) -> str: ...
    def get_parameters(self) -> str: ...
    def run(self, comparer: RRComparer, reporter, pose: pyrosetta.rosetta.core.pose.Pose, score_function: pyrosetta.rosetta.core.scoring.ScoreFunction, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...

class RRProtocolMinPackCreator(RRProtocolCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolMinPackCreator) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolMinPackCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRProtocolMinPackCreator: ...
    def create_protocol(self) -> RRProtocol: ...
    def type_name(self) -> str: ...

class RRProtocolMover(RRProtocol):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, mover: pyrosetta.rosetta.protocols.moves.Mover) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolMover) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolMover) -> None: ...
    def assign(self) -> RRProtocolMover: ...
    def get_name(self) -> str: ...
    def get_parameters(self) -> str: ...
    def run(self, comparer: RRComparer, reporter, pose: pyrosetta.rosetta.core.pose.Pose, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...

class RRProtocolMoverCreator(RRProtocolCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolMoverCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRProtocolMoverCreator: ...
    def create_protocol(self) -> RRProtocol: ...
    def type_name(self) -> str: ...

class RRProtocolPackRotamers(RRProtocol):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolPackRotamers) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolPackRotamers) -> None: ...
    def assign(self) -> RRProtocolPackRotamers: ...
    def get_name(self) -> str: ...
    def get_parameters(self) -> str: ...
    def run(self, comparer: RRComparer, reporter, pose: pyrosetta.rosetta.core.pose.Pose, score_function: pyrosetta.rosetta.core.scoring.ScoreFunction, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...

class RRProtocolPackRotamersCreator(RRProtocolCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolPackRotamersCreator) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolPackRotamersCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRProtocolPackRotamersCreator: ...
    def create_protocol(self) -> RRProtocol: ...
    def type_name(self) -> str: ...

class RRProtocolRTMin(RRProtocol):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolRTMin) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolRTMin) -> None: ...
    def assign(self) -> RRProtocolRTMin: ...
    @overload
    def get_cartesian(self) -> bool: ...
    @overload
    def get_cartesian(self) -> bool: ...
    def get_name(self) -> str: ...
    @overload
    def get_nonideal(self) -> bool: ...
    @overload
    def get_nonideal(self) -> bool: ...
    def get_parameters(self) -> str: ...
    def run(self, comparer: RRComparer, reporter, pose: pyrosetta.rosetta.core.pose.Pose, score_function: pyrosetta.rosetta.core.scoring.ScoreFunction, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def set_cartesian(self, setting: bool) -> None: ...
    @overload
    def set_cartesian(self, bool) -> void: ...
    @overload
    def set_nonideal(self, setting: bool) -> None: ...
    @overload
    def set_nonideal(self, bool) -> void: ...

class RRProtocolRTMinCreator(RRProtocolCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolRTMinCreator) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolRTMinCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRProtocolRTMinCreator: ...
    def create_protocol(self) -> RRProtocol: ...
    def type_name(self) -> str: ...

class RRProtocolReferenceStructure(RRProtocol):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, reference_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolReferenceStructure) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolReferenceStructure) -> None: ...
    @overload
    @staticmethod
    def append_attributes(attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    @staticmethod
    def append_attributes(classstd) -> void: ...
    def assign(self) -> RRProtocolReferenceStructure: ...
    def get_name(self) -> str: ...
    def get_parameters(self) -> str: ...
    @overload
    def parse_attributes_from_tag(self, dm: pyrosetta.rosetta.basic.datacache.DataMap, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_attributes_from_tag(self, constclassbasic, classstd) -> void: ...
    @overload
    def reference_structure(self, reference_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def reference_structure(self, classstd) -> void: ...
    def run(self, comparer: RRComparer, reporter, pose: pyrosetta.rosetta.core.pose.Pose, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...

class RRProtocolReferenceStructureCreator(RRProtocolCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolReferenceStructureCreator) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolReferenceStructureCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRProtocolReferenceStructureCreator: ...
    def create_protocol(self) -> RRProtocol: ...
    def type_name(self) -> str: ...

class RRProtocolRelax(RRProtocol):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolRelax) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolRelax) -> None: ...
    def assign(self) -> RRProtocolRelax: ...
    @overload
    def get_cartesian(self) -> bool: ...
    @overload
    def get_cartesian(self) -> bool: ...
    def get_name(self) -> str: ...
    @overload
    def get_nonideal(self) -> bool: ...
    @overload
    def get_nonideal(self) -> bool: ...
    def get_parameters(self) -> str: ...
    def run(self, comparer: RRComparer, reporter, pose: pyrosetta.rosetta.core.pose.Pose, score_function: pyrosetta.rosetta.core.scoring.ScoreFunction, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
    @overload
    def set_cartesian(self, setting: bool) -> None: ...
    @overload
    def set_cartesian(self, bool) -> void: ...
    @overload
    def set_nonideal(self, setting: bool) -> None: ...
    @overload
    def set_nonideal(self, bool) -> void: ...

class RRProtocolRelaxCreator(RRProtocolCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolRelaxCreator) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolRelaxCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRProtocolRelaxCreator: ...
    def create_protocol(self) -> RRProtocol: ...
    def type_name(self) -> str: ...

class RRProtocolRotamerTrials(RRProtocol):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolRotamerTrials) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolRotamerTrials) -> None: ...
    def assign(self) -> RRProtocolRotamerTrials: ...
    def get_name(self) -> str: ...
    def get_parameters(self) -> str: ...
    def run(self, comparer: RRComparer, reporter, pose: pyrosetta.rosetta.core.pose.Pose, score_function: pyrosetta.rosetta.core.scoring.ScoreFunction, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...

class RRProtocolRotamerTrialsCreator(RRProtocolCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolRotamerTrialsCreator) -> None: ...
    @overload
    def __init__(self, arg0: RRProtocolRotamerTrialsCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRProtocolRotamerTrialsCreator: ...
    def create_protocol(self) -> RRProtocol: ...
    def type_name(self) -> str: ...

class RRReporter:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRReporter) -> None: ...
    def assign(self) -> RRReporter: ...
    @overload
    def recovery_rate(self) -> float: ...
    @overload
    def recovery_rate(self) -> double: ...
    def report_rotamer_recovery(self, pose1: pyrosetta.rosetta.core.pose.Pose, pose2: pyrosetta.rosetta.core.pose.Pose, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, score: float, recovered: bool) -> None: ...
    @overload
    def reset_recovery(self) -> None: ...
    @overload
    def reset_recovery(self) -> void: ...
    def set_comparer_info(self, comparer_name: str, comparer_params: str) -> None: ...
    def set_protocol_info(self, protocol_name: str, protocol_params: str) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self) -> void: ...

class RRReporterCreator:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRReporterCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRReporterCreator: ...
    def create_reporter(self) -> RRReporter: ...
    def type_name(self) -> str: ...

class RRReporterHuman(RRReporter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRReporterHuman) -> None: ...
    @overload
    def __init__(self, arg0: RRReporterHuman) -> None: ...
    def assign(self) -> RRReporterHuman: ...
    @overload
    def recovery_rate(self) -> float: ...
    @overload
    def recovery_rate(self) -> double: ...
    def report_rotamer_recovery(self, pose1: pyrosetta.rosetta.core.pose.Pose, pose2: pyrosetta.rosetta.core.pose.Pose, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, score: float, recovered: bool) -> None: ...
    @overload
    def reset_recovery(self) -> None: ...
    @overload
    def reset_recovery(self) -> void: ...
    def set_comparer_info(self, comparer_name: str, comparer_params: str) -> None: ...
    def set_protocol_info(self, protocol_name: str, protocol_params: str) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self) -> void: ...

class RRReporterHumanCreator(RRReporterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRReporterHumanCreator) -> None: ...
    @overload
    def __init__(self, arg0: RRReporterHumanCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRReporterHumanCreator: ...
    def create_reporter(self) -> RRReporter: ...
    def type_name(self) -> str: ...

class RRReporterSQLite(RRReporter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str) -> None: ...
    @overload
    def __init__(self, database_name: str, database_pq_schema: str, output_level: OutputLevel) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.utility.sql_database.session) -> None: ...
    @overload
    def __init__(self, db_session: pyrosetta.rosetta.utility.sql_database.session, output_level: OutputLevel) -> None: ...
    @overload
    def __init__(self, arg0: RRReporterSQLite) -> None: ...
    @overload
    def __init__(self, arg0: RRReporterSQLite) -> None: ...
    def assign(self) -> RRReporterSQLite: ...
    @overload
    def db_session(self, db_session: pyrosetta.rosetta.utility.sql_database.session) -> None: ...
    @overload
    def db_session(self, classstd) -> void: ...
    @overload
    def db_session(self) -> pyrosetta.rosetta.utility.sql_database.session: ...
    def get_output_level(self) -> OutputLevel: ...
    @overload
    def get_struct_id1(self) -> int: ...
    @overload
    def get_struct_id1(self) -> unsignedlonglong: ...
    @overload
    def recovery_rate(self) -> float: ...
    @overload
    def recovery_rate(self) -> double: ...
    def report_predicted_features(self, struct_id1: int, res1: pyrosetta.rosetta.core.conformation.Residue, predicted_pose: pyrosetta.rosetta.core.pose.Pose, predicted_res: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    def report_rotamer_recovery(self, pose1: pyrosetta.rosetta.core.pose.Pose, pose2: pyrosetta.rosetta.core.pose.Pose, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, score: float, recovered: bool) -> None: ...
    @overload
    def report_rotamer_recovery_features(self, struct_id1: int, res1: pyrosetta.rosetta.core.conformation.Residue, score: float, recovered: bool) -> None: ...
    @overload
    def report_rotamer_recovery_features(self, unsignedlonglong, constclasscore, double, bool) -> void: ...
    def report_rotamer_recovery_full(self, pose1: pyrosetta.rosetta.core.pose.Pose, pose2: pyrosetta.rosetta.core.pose.Pose, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, score: float, recovered: bool) -> None: ...
    @overload
    def reset_recovery(self) -> None: ...
    @overload
    def reset_recovery(self) -> void: ...
    def set_comparer_info(self, comparer_name: str, comparer_params: str) -> None: ...
    @overload
    def set_output_level(self, output_level: OutputLevel) -> None: ...
    @overload
    def set_output_level(self, enumprotocols) -> void: ...
    @overload
    def set_predicted_report_to_db(self, report_to_db: pyrosetta.rosetta.protocols.features.ReportToDB) -> None: ...
    @overload
    def set_predicted_report_to_db(self, classstd) -> void: ...
    def set_protocol_info(self, protocol_name: str, protocol_params: str) -> None: ...
    @overload
    def set_struct_id1(self, struct_id1: int) -> None: ...
    @overload
    def set_struct_id1(self, constunsignedlonglong) -> void: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self) -> void: ...
    @overload
    def write_schema_to_db(self, db_session: pyrosetta.rosetta.utility.sql_database.session) -> None: ...
    @overload
    def write_schema_to_db(self, classstd) -> void: ...

class RRReporterSQLiteCreator(RRReporterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRReporterSQLiteCreator) -> None: ...
    @overload
    def __init__(self, arg0: RRReporterSQLiteCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRReporterSQLiteCreator: ...
    def create_reporter(self) -> RRReporter: ...
    def type_name(self) -> str: ...

class RRReporterSimple(RRReporter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRReporterSimple) -> None: ...
    @overload
    def __init__(self, arg0: RRReporterSimple) -> None: ...
    def assign(self) -> RRReporterSimple: ...
    @overload
    def recovery_rate(self) -> float: ...
    @overload
    def recovery_rate(self) -> double: ...
    def report_rotamer_recovery(self, pose1: pyrosetta.rosetta.core.pose.Pose, pose2: pyrosetta.rosetta.core.pose.Pose, res1: pyrosetta.rosetta.core.conformation.Residue, res2: pyrosetta.rosetta.core.conformation.Residue, score: float, recovered: bool) -> None: ...
    @overload
    def reset_recovery(self) -> None: ...
    @overload
    def reset_recovery(self) -> void: ...
    def set_comparer_info(self) -> None: ...
    def set_protocol_info(self) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self) -> void: ...

class RRReporterSimpleCreator(RRReporterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RRReporterSimpleCreator) -> None: ...
    @overload
    def __init__(self, arg0: RRReporterSimpleCreator) -> None: ...
    @overload
    def append_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_attributes(self, classstd) -> void: ...
    def assign(self) -> RRReporterSimpleCreator: ...
    def create_reporter(self) -> RRReporter: ...
    def type_name(self) -> str: ...

class RotamerRecovery:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, protocol: RRProtocol, comparer: RRComparer, reporter: RRReporter) -> None: ...
    @overload
    def __init__(self, arg0: RotamerRecovery) -> None: ...
    @overload
    def __init__(self, arg0: RotamerRecovery) -> None: ...
    def assign(self) -> RotamerRecovery: ...
    @overload
    def get_ignore_unrecognized_res(self) -> bool: ...
    @overload
    def get_ignore_unrecognized_res(self) -> bool: ...
    @overload
    def init_rotamer_recovery_with_options(self, rotamer_recovery: RotamerRecovery) -> None: ...
    @overload
    def init_rotamer_recovery_with_options(self, classprotocols) -> void: ...
    @overload
    def init_with_options(self) -> None: ...
    @overload
    def init_with_options(self) -> void: ...
    @overload
    def recovery_rate(self) -> float: ...
    @overload
    def recovery_rate(self) -> double: ...
    @overload
    def register_options(self) -> None: ...
    @overload
    def register_options(self) -> void: ...
    @overload
    def reset_recovery(self) -> None: ...
    @overload
    def reset_recovery(self) -> void: ...
    def run(self, pose: pyrosetta.rosetta.core.pose.Pose, score_function: pyrosetta.rosetta.core.scoring.ScoreFunction, packer_task: pyrosetta.rosetta.core.pack.task.PackerTask) -> float: ...
    @overload
    def set_ignore_unrecognized_res(self, ignore_unrecognized_res: bool) -> None: ...
    @overload
    def set_ignore_unrecognized_res(self, constbool) -> void: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self) -> void: ...

class RotamerRecoveryFactory(pyrosetta.rosetta.utility.SingletonBase_protocols_rotamer_recovery_RotamerRecoveryFactory_t):
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def append_comparer_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_comparer_attributes(self, classstd) -> void: ...
    @overload
    def append_protocol_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_protocol_attributes(self, classstd) -> void: ...
    @overload
    def append_reporter_attributes(self, attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
    @overload
    def append_reporter_attributes(self, classstd) -> void: ...
    def get_rotamer_recovery(self, protocol: str, comparer: str, reporter: str) -> RotamerRecovery: ...
    def get_rotamer_recovery_comparer(self, type_name: str) -> RRComparer: ...
    def get_rotamer_recovery_protocol(self, type_name: str) -> RRProtocol: ...
    def get_rotamer_recovery_reporter(self, type_name: str) -> RRReporter: ...

class RotamerRecoveryMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rotamer_recovery: RotamerRecovery, scfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, task_factory: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def __init__(self, arg0: RotamerRecoveryMover) -> None: ...
    @overload
    def __init__(self, arg0: RotamerRecoveryMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RotamerRecoveryMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def register_options(self) -> None: ...
    @overload
    def register_options(self) -> void: ...
    @overload
    def reinitialize_for_each_job(self) -> bool: ...
    @overload
    def reinitialize_for_each_job(self) -> bool: ...
    @overload
    def reinitialize_for_new_input(self) -> bool: ...
    @overload
    def reinitialize_for_new_input(self) -> bool: ...
    @overload
    def score_function(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def score_function(self) -> None: ...
    @overload
    def score_function(self, classstd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self) -> void: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class RotamerRecoveryMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RotamerRecoveryMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: RotamerRecoveryMoverCreator) -> None: ...
    def assign(self) -> RotamerRecoveryMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
