import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.protocols.chemistries
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import overload

class FragmentRotamers(pyrosetta.rosetta.protocols.chemistries.Chemistry):
    def __init__(self) -> None: ...
    @overload
    def apply(self, restype: pyrosetta.rosetta.core.chemical.MutableResidueType) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> FragmentRotamers: ...
    @staticmethod
    def class_name() -> str: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class FragmentRotamersCreator(pyrosetta.rosetta.protocols.chemistries.ChemistryCreator):
    def __init__(self) -> None: ...
    def assign(self) -> FragmentRotamersCreator: ...
    def create_chemistry(self) -> pyrosetta.rosetta.protocols.chemistries.Chemistry: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class RDKitRotamers(pyrosetta.rosetta.protocols.chemistries.Chemistry):
    def __init__(self) -> None: ...
    @overload
    def apply(self, restype: pyrosetta.rosetta.core.chemical.MutableResidueType) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RDKitRotamers: ...
    @staticmethod
    def class_name() -> str: ...
    @overload
    @staticmethod
    def generate_conformers(rsdtype: pyrosetta.rosetta.core.chemical.MutableResidueType, nconf: int) -> pyrosetta.rosetta.utility.vector1_std_map_std_string_numeric_xyzVector_double_t: ...
    @overload
    @staticmethod
    def generate_conformers(rsdtype: pyrosetta.rosetta.core.chemical.MutableResidueType, nconf: int, minimize: bool) -> pyrosetta.rosetta.utility.vector1_std_map_std_string_numeric_xyzVector_double_t: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class RDKitRotamersCreator(pyrosetta.rosetta.protocols.chemistries.ChemistryCreator):
    def __init__(self) -> None: ...
    def assign(self) -> RDKitRotamersCreator: ...
    def create_chemistry(self) -> pyrosetta.rosetta.protocols.chemistries.Chemistry: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
