import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.protocols.evaluation
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from _typeshed import Incomplete
from typing import overload

class ANN:
    ANN_IN_MTX: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    ANN_IN_MTX_LEVEL1: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    ANN_IN_MTX_LEVEL2: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    ANN_OUT_MTX_LEVEL1: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    ANN_OUT_MTX_LEVEL2: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    B2I_1: pyrosetta.rosetta.utility.vector0_float
    B2I_2: pyrosetta.rosetta.utility.vector0_float
    B2I_3: pyrosetta.rosetta.utility.vector0_float
    B2L1_1: pyrosetta.rosetta.utility.vector0_float
    B2L1_2: pyrosetta.rosetta.utility.vector0_float
    B2L1_3: pyrosetta.rosetta.utility.vector0_float
    B2L2_1: pyrosetta.rosetta.utility.vector0_float
    B2L2_2: pyrosetta.rosetta.utility.vector0_float
    B2L2_3: pyrosetta.rosetta.utility.vector0_float
    BI_1: pyrosetta.rosetta.utility.vector0_float
    BI_2: pyrosetta.rosetta.utility.vector0_float
    BI_3: pyrosetta.rosetta.utility.vector0_float
    BL1_1: pyrosetta.rosetta.utility.vector0_float
    BL1_2: pyrosetta.rosetta.utility.vector0_float
    BL1_3: pyrosetta.rosetta.utility.vector0_float
    BL2_1: pyrosetta.rosetta.utility.vector0_float
    BL2_2: pyrosetta.rosetta.utility.vector0_float
    BL2_3: pyrosetta.rosetta.utility.vector0_float
    DB_FNAME_LEVEL1_1: str
    DB_FNAME_LEVEL1_2: str
    DB_FNAME_LEVEL1_3: str
    DB_FNAME_LEVEL2_1: str
    DB_FNAME_LEVEL2_2: str
    DB_FNAME_LEVEL2_3: str
    DB_NAME_PREFIX: str
    DB_PATH: str
    N1_NODE_H: int
    N1_NODE_I: int
    N1_NODE_O: int
    N2_NODE_H: int
    N2_NODE_I: int
    N2_NODE_O: int
    W2I_1: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    W2I_2: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    W2I_3: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    W2L1_1: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    W2L1_2: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    W2L1_3: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    W2L2_1: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    W2L2_2: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    W2L2_3: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    WI_1: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    WI_2: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    WI_3: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    WL1_1: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    WL1_2: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    WL1_3: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    WL2_1: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    WL2_2: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    WL2_3: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
    input_code: int
    slash_char: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, dPATH: str, dNAME_PREFIX: str) -> None: ...
    @overload
    def __init__(self, N1_nodeI: int, N1_nodeH: int, N1_nodeO: int, dPATH: str, dNAME_PREFIX: str) -> None: ...
    @overload
    def __init__(self, N1_nodeI: int, N1_nodeH: int, N1_nodeO: int, N2_nodeI: int, N2_nodeH: int, N2_nodeO: int, dPATH: str, dNAME_PREFIX: str) -> None: ...
    @overload
    def __init__(self, arg0: ANN) -> None: ...
    def applyANNTransformation(self, inp: pyrosetta.rosetta.utility.vector0_float, w: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t, b: pyrosetta.rosetta.utility.vector0_float, out: pyrosetta.rosetta.utility.vector0_float, code: int) -> None: ...
    def applyVecAverage(self, v1: pyrosetta.rosetta.utility.vector0_float, v2: pyrosetta.rosetta.utility.vector0_float, v3: pyrosetta.rosetta.utility.vector0_float, vout: pyrosetta.rosetta.utility.vector0_float) -> None: ...
    @overload
    def applyVecNormalization(self, v: pyrosetta.rosetta.utility.vector0_float) -> None: ...
    @overload
    def applyVecNormalization(self, classutility) -> void: ...
    def assign(self) -> ANN: ...
    @overload
    def calcLevel1(self) -> None: ...
    @overload
    def calcLevel1(self) -> void: ...
    @overload
    def calcLevel2(self) -> None: ...
    @overload
    def calcLevel2(self) -> void: ...
    @overload
    def ftoa(self, n: float, buff: str, s: int) -> str: ...
    @overload
    def ftoa(self, n: float, buff: str, s: int, f: str) -> str: ...
    @overload
    def ftoa(self, n: float, buff: str, s: int, f: str, prec: int) -> str: ...
    @overload
    def getConfidence(self, v: pyrosetta.rosetta.utility.vector0_float) -> float: ...
    @overload
    def getConfidence(self, classutility) -> float: ...
    @overload
    def getNumberMissCS(self, v: pyrosetta.rosetta.utility.vector0_float) -> int: ...
    @overload
    def getNumberMissCS(self, classutility) -> int: ...
    @overload
    def getSlashChar(self) -> None: ...
    @overload
    def getSlashChar(self) -> void: ...
    def init(self, N1_nodeI: int, N1_nodeH: int, N1_nodeO: int, N2_nodeI: int, N2_nodeH: int, N2_nodeO: int, dPATH: str, dNAME_PREFIX: str) -> None: ...
    @overload
    def itoa(self, n: int, buff: str, s: int) -> str: ...
    @overload
    def itoa(self, n: int, buff: str, s: int, base: int) -> str: ...
    def loadWeightBias3(self, fName: str, W1: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t, B1: pyrosetta.rosetta.utility.vector0_float, W2: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t, B2: pyrosetta.rosetta.utility.vector0_float, W3: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t, B3: pyrosetta.rosetta.utility.vector0_float, N_W_row: int, N_W_col: int, N_B: int) -> None: ...
    @overload
    def loadWeights(self) -> None: ...
    @overload
    def loadWeights(self) -> void: ...
    @overload
    def runSpartaANN(self, inMatrix: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t) -> None: ...
    @overload
    def runSpartaANN(self, classstd, classutility) -> void: ...
    @overload
    def set_input_code(self, c: int) -> None: ...
    @overload
    def set_input_code(self, int) -> void: ...

class ChemicalShiftEvaluator(pyrosetta.rosetta.protocols.evaluation.SingleValuePoseEvaluator_double_t):
    @overload
    def __init__(self, tag: str, cst_file: str) -> None: ...
    @overload
    def __init__(self, arg0: ChemicalShiftEvaluator) -> None: ...
    @overload
    def __init__(self, arg0: ChemicalShiftEvaluator) -> None: ...
    @overload
    def applicable(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def applicable(self, constclasscore) -> bool: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def apply(self, classcore) -> double: ...
    def assign(self) -> ChemicalShiftEvaluator: ...

class ChemicalShiftEvaluatorCreator(pyrosetta.rosetta.protocols.evaluation.EvaluatorCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ChemicalShiftEvaluatorCreator) -> None: ...
    @overload
    def __init__(self, arg0: ChemicalShiftEvaluatorCreator) -> None: ...
    @overload
    def add_evaluators(self, eval: pyrosetta.rosetta.protocols.evaluation.MetaPoseEvaluator) -> None: ...
    @overload
    def add_evaluators(self, classprotocols) -> void: ...
    def assign(self) -> ChemicalShiftEvaluatorCreator: ...
    @overload
    def register_options(self) -> None: ...
    @overload
    def register_options(self) -> void: ...
    def type_name(self) -> str: ...

class GDB:
    DATA: pyrosetta.rosetta.utility.vector0_std_string
    EMPTY: Incomplete
    Entries: Incomplete
    FORMAT: Incomplete
    FORMAT_str: str
    GDBfileName: str
    REMARKS: pyrosetta.rosetta.utility.vector0_std_string
    VARS: Incomplete
    VARS_str: str
    VarsNumber: int
    firstResID: int
    residList: Incomplete
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, fileName: str) -> None: ...
    @overload
    def __init__(self, arg0: GDB) -> None: ...
    @overload
    def FORMAT_str_parser(self, str: str) -> None: ...
    @overload
    def FORMAT_str_parser(self, conststd) -> void: ...
    @overload
    def VARS_str_parser(self, str: str) -> None: ...
    @overload
    def VARS_str_parser(self, conststd) -> void: ...
    def addEntry(self, VarName: str, VarVal: str) -> None: ...
    @overload
    def addRemark(self, str: str) -> None: ...
    @overload
    def addRemark(self, conststd) -> void: ...
    def addVAR(self, VAR_Name: str, FORMAT_Name: str) -> None: ...
    def assign(self) -> GDB: ...
    @overload
    def checkFormat(self, f: str) -> bool: ...
    @overload
    def checkFormat(self, conststd) -> bool: ...
    def getData(self, DataName: str) -> str: ...
    @overload
    def getEntryCount(self) -> int: ...
    @overload
    def getEntryCount(self) -> int: ...
    def getResidName(self, rNum: int) -> str: ...
    @overload
    def isVarFloat(self, index: int) -> bool: ...
    @overload
    def isVarFloat(self, int) -> bool: ...
    @overload
    def isVarFloat(self, VarName: str) -> bool: ...
    @overload
    def isVarFloat(self, conststd) -> bool: ...
    @overload
    def isVarInt(self, index: int) -> bool: ...
    @overload
    def isVarInt(self, int) -> bool: ...
    @overload
    def isVarInt(self, VarName: str) -> bool: ...
    @overload
    def isVarInt(self, conststd) -> bool: ...
    @overload
    def isVarString(self, index: int) -> bool: ...
    @overload
    def isVarString(self, int) -> bool: ...
    @overload
    def isVarString(self, VarName: str) -> bool: ...
    @overload
    def isVarString(self, conststd) -> bool: ...
    @overload
    def loadGDB(self, fileName: str) -> None: ...
    @overload
    def loadGDB(self, conststd) -> void: ...
    @overload
    def presetClass(self, ClassName: str) -> None: ...
    @overload
    def presetClass(self, conststd) -> void: ...
    @overload
    def saveGDB(self, fileName: str) -> None: ...
    @overload
    def saveGDB(self, conststd) -> void: ...
    def setData(self, DataName: str, DataVal: str) -> None: ...
    def setEntry(self, index: int, VarName: str, VarVal: str) -> None: ...
    def setVAR(self, index: int, VAR_Name: str, FORMAT_Name: str) -> None: ...
    @overload
    def set_plaintext(self) -> None: ...
    @overload
    def set_plaintext(self) -> void: ...
    @overload
    def showGDB(self, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def showGDB(self, std) -> void: ...

class PDB:
    ATOMS: Incomplete
    AtomSurfaceFullList: Incomplete
    AtomSurfacePartList: Incomplete
    Conformers: Incomplete
    EMPTY: PDB_Entry
    ElectricField: Incomplete
    HBDistList: Incomplete
    HBEnergyList: Incomplete
    HB_DHO_AngleList: Incomplete
    HB_HOA_AngleList: Incomplete
    HN_S2: Incomplete
    NeighborList: Incomplete
    PDBfileName: str
    ResSurfaceFullList: Incomplete
    ResSurfacePartList: Incomplete
    RingNo: int
    SpherePointNo: int
    SurfPrec: int
    VDW_RAD: Incomplete
    acceptorList: pyrosetta.rosetta.std.map_int_int
    donorList: pyrosetta.rosetta.std.map_int_int
    r1: int
    rN: int
    residList: Incomplete
    residListOne: Incomplete
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, fileName: str) -> None: ...
    @overload
    def __init__(self, arg0: PDB) -> None: ...
    def assign(self) -> PDB: ...
    @overload
    def calcPlane(self, ringP: RingData) -> None: ...
    @overload
    def calcPlane(self, structprotocols) -> void: ...
    @overload
    def calcSurface(self, rad_sol: float) -> None: ...
    @overload
    def calcSurface(self, float) -> void: ...
    @overload
    def calc_ElectricField(self) -> None: ...
    @overload
    def calc_ElectricField(self) -> void: ...
    @overload
    def calc_HN_S2(self) -> None: ...
    @overload
    def calc_HN_S2(self) -> void: ...
    @overload
    def collect_HN_S2_and_EF(self) -> None: ...
    @overload
    def collect_HN_S2_and_EF(self) -> void: ...
    @overload
    def findNeighors(self, rad_sol: float) -> None: ...
    @overload
    def findNeighors(self, float) -> void: ...
    def getBondAngle(self, a: PDB_Entry, b: PDB_Entry, c: PDB_Entry) -> float: ...
    def getChi1(self, conformerID: int, resNum: int) -> float: ...
    def getChi2(self, conformerID: int, resNum: int) -> float: ...
    def getDihedralAngle(self, a: PDB_Entry, b: PDB_Entry, c: PDB_Entry, d: PDB_Entry) -> float: ...
    def getDist(self, A: PDB_Entry, B: PDB_Entry) -> float: ...
    @overload
    def getEntry(self, conformerID: int, rNum: int, aName: str) -> PDB_Entry: ...
    @overload
    def getEntry(self, conformerID: int, aNum: int) -> PDB_Entry: ...
    def getField(self, str: str, index: int) -> str: ...
    @overload
    def getHBondDist(self, D: PDB_Entry) -> float: ...
    @overload
    def getHBondDist(self, structprotocols) -> float: ...
    @overload
    def getHBondDist(self, resNum: int, atomName: str) -> float: ...
    @overload
    def getHBondDist(self, int, std) -> float: ...
    def getOmega(self, conformerID: int, resNum: int) -> float: ...
    def getOneAAName(self, a: str) -> str: ...
    def getOrbitalShift(self, conformerID: int, resNum: int, aName: str) -> float: ...
    def getPhi(self, conformerID: int, resNum: int) -> float: ...
    def getPsi(self, conformerID: int, resNum: int) -> float: ...
    def getThreeAAName(self, a: str) -> str: ...
    @overload
    def initHBond(self) -> None: ...
    @overload
    def initHBond(self, DIST: float) -> None: ...
    @overload
    def initHBond(self, DIST: float, ANGLE: float) -> None: ...
    @overload
    def initOrbitalShift(self) -> None: ...
    @overload
    def initOrbitalShift(self) -> void: ...
    def isAcceptor(self, A: PDB_Entry) -> PDB_Entry: ...
    def isDonor(self, D: PDB_Entry) -> PDB_Entry: ...
    def isSSBonded(self, conformerID: int, resNum: int) -> bool: ...
    @overload
    def loadPDB(self, fileName: str) -> None: ...
    @overload
    def loadPDB(self, conststd) -> void: ...
    @overload
    def loadPDB(self, file: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def loadPDB(self, std) -> void: ...
    @overload
    def loadPDB(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def loadPDB(self, constclasscore) -> void: ...
    @overload
    def loadPDB_Entry(self, str: str, entry: PDB_Entry) -> None: ...
    @overload
    def loadPDB_Entry(self, conststd, structprotocols) -> void: ...

class PDB_Entry:
    B_Factor: float
    X: float
    Y: float
    Z: float
    atomName: str
    atomNum: int
    chainName: str
    resName: str
    resNum: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PDB_Entry) -> None: ...
    def assign(self) -> PDB_Entry: ...

class RingData:
    atomNo: int
    rad: float
    resID: int
    resName: str
    ringFact: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RingData) -> None: ...
    def assign(self) -> RingData: ...

class Sparta:
    class SpartaLib:
        AAlist: str
        ADJ_Tab: GDB
        ANN_CS_OUTPUT_FULL: Incomplete
        ANN_IN_MTX: pyrosetta.rosetta.std.map_int_utility_vector0_float_t_std_allocator_std_pair_const_int_utility_vector0_float_t
        BLOSUM_62: Incomplete
        CHI2_ANGLES: Incomplete
        EXCLUDED: str
        FIT_Tab: GDB
        HOMO_Tab: GDB
        NEXT_Tab: GDB
        OMEGA_ANGLES: Incomplete
        PDB_DIR: str
        PRED_DIR: str
        PREV_Tab: GDB
        RC_Tab: GDB
        SHIFT_DIR: str
        SPARTA_ANN: Incomplete
        SPARTA_DIR: str
        SPARTA_ERR_SURF: Incomplete
        SURFACE_EXPOSURE: Incomplete
        TAB_DIR: str
        TRIPLET_Tab: GDB
        WEIGHT_Tab: GDB
        aN: Incomplete
        adjFileName: str
        firstRes: int
        fitFileName: str
        homoFileName: str
        inName: str
        inNames: str
        inPDB: PDB
        inTab: GDB
        lastRes: int
        matchCount: int
        nextFileName: str
        pdbListName: str
        prevFileName: str
        r1: int
        rN: int
        rcFileName: str
        residList: Incomplete
        sequence: str
        slash_char: str
        sourceName: str
        sumName: str
        tVal: float
        tripFileName: str
        weightFileName: str
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: Sparta.SpartaLib) -> None: ...
        def assign(self) -> Sparta.SpartaLib: ...
        @overload
        def deallocate_arrays(self) -> None: ...
        @overload
        def deallocate_arrays(self) -> void: ...
        def getANN_PredError(self, phi: float, psi: float, aa: str, aName: str) -> float: ...
        def getNextRCadj(self, next_rName: str, aName: str) -> float: ...
        def getPrevRCadj(self, prev_rName: str, aName: str) -> float: ...
        def getRC(self, resName: str, aName: str) -> float: ...
        def getRCadj(self, resName: str, aName: str) -> float: ...
        @overload
        def getResInfo(self, create_output: bool) -> None: ...
        @overload
        def getResInfo(self, bool) -> void: ...
        def getWeight(self, Name: str, aName: str) -> float: ...
        def get_ANN_data(self, create_output: bool) -> GDB: ...
        @overload
        def init(self) -> None: ...
        @overload
        def init(self) -> void: ...
        @overload
        def init_PredErrorSurface(self) -> None: ...
        @overload
        def init_PredErrorSurface(self) -> void: ...
        @overload
        def mkdir_pred(self, d: str) -> None: ...
        @overload
        def mkdir_pred(self, conststd) -> void: ...
        @overload
        def setup_defaults(self) -> None: ...
        @overload
        def setup_defaults(self) -> void: ...
        @overload
        def setup_for_scoring(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
        @overload
        def setup_for_scoring(self, constclasscore) -> void: ...
    REF_CS_Tab: GDB
    bCreateOutput_: bool
    refCSFileName: str
    @overload
    def __init__(self, chem_shifts: str) -> None: ...
    @overload
    def __init__(self, arg0: Sparta) -> None: ...
    def assign(self) -> Sparta: ...
    @overload
    def check_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def check_pose(self, constclasscore) -> void: ...
    def lib(self, *args, **kwargs): ...
    @overload
    @staticmethod
    def register_options() -> None: ...
    @overload
    @staticmethod
    def register_options() -> void: ...
    @overload
    def run_A_ANN_Prediction(self) -> float: ...
    @overload
    def run_A_ANN_Prediction(self) -> double: ...
    @overload
    def score_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def score_pose(self, constclasscore) -> double: ...
    def score_pose_per_residue(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_float: ...

def MKDIR(dirName: str) -> int: ...
@overload
def contains(str: str, c: str) -> int: ...
@overload
def contains(str: str, c: str) -> int: ...
@overload
def ftoa(n: float, buff: str, s: int) -> str: ...
@overload
def ftoa(n: float, buff: str, s: int, f: str) -> str: ...
@overload
def ftoa(n: float, buff: str, s: int, f: str, prec: int) -> str: ...
@overload
def getAVG(v1: pyrosetta.rosetta.utility.vector0_float) -> float: ...
@overload
def getAVG(classutility) -> float: ...
def getDiff(ang1: float, ang2: float) -> float: ...
def getRMS(v1: pyrosetta.rosetta.utility.vector0_float, v2: pyrosetta.rosetta.utility.vector0_float) -> float: ...
@overload
def getSTD(v1: pyrosetta.rosetta.utility.vector0_float) -> float: ...
@overload
def getSTD(classutility) -> float: ...
def isDigit(c: str) -> bool: ...
@overload
def isDirExists(Dir: str) -> bool: ...
@overload
def isDirExists(conststd) -> bool: ...
def isSpace(c: str) -> bool: ...
@overload
def itoa(n: int, buff: str, s: int) -> str: ...
@overload
def itoa(n: int, buff: str, s: int, base: int) -> str: ...
@overload
def section(str: str, seq: str, buff: str, n: int, start: int) -> str: ...
@overload
def section(str: str, seq: str, buff: str, n: int, start: int, end: int) -> str: ...
def simplifyWhiteSpace(str: str) -> str: ...
@overload
def split(sep: str, str: str) -> pyrosetta.rosetta.utility.vector0_std_string: ...
@overload
def split(sep: str, str: str) -> pyrosetta.rosetta.utility.vector0_std_string: ...
def split_WhiteSpace(str: str) -> pyrosetta.rosetta.utility.vector0_std_string: ...
