import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.pose.metrics
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility.tag
from typing import overload

class LoadVarSolDistSasaCalculatorMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: float) -> None: ...
    @overload
    def __init__(self, probe_radius: float, wobble: float) -> None: ...
    @overload
    def apply(self, p: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> LoadVarSolDistSasaCalculatorMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class LoadVarSolDistSasaCalculatorMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LoadVarSolDistSasaCalculatorMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: LoadVarSolDistSasaCalculatorMoverCreator) -> None: ...
    def assign(self) -> LoadVarSolDistSasaCalculatorMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd: pyrosetta.rosetta.utility.tag.XMLSchemaDefinition) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class VarSolDRotamerDots:
    @overload
    def __init__(self, rotamer: pyrosetta.rosetta.core.conformation.Residue, vsasa_calc) -> None: ...
    @overload
    def __init__(self, arg0: VarSolDRotamerDots) -> None: ...
    @overload
    def any_exposed_dots(self, atom: int) -> bool: ...
    @overload
    def any_exposed_dots(self, unsignedlong) -> bool: ...
    def assign(self, rhs: VarSolDRotamerDots) -> VarSolDRotamerDots: ...
    @overload
    def copy(self, rhs: VarSolDRotamerDots) -> None: ...
    @overload
    def copy(self, constclassprotocols) -> void: ...
    @overload
    def get_atom_collision_radius(self, atom_index: int) -> float: ...
    @overload
    def get_atom_collision_radius(self, unsignedlong) -> double: ...
    def get_atom_coords_xyz(self, atom_index: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def get_atom_interaction_radius(self, atom_index: int) -> float: ...
    @overload
    def get_atom_interaction_radius(self, unsignedlong) -> double: ...
    def get_dot_covered(self, atom_index: int, shell_index: int, dot_index: int) -> bool: ...
    @overload
    def get_num_atoms(self) -> int: ...
    @overload
    def get_num_atoms(self) -> unsignedlong: ...
    @overload
    def increment_self_overlap(self) -> None: ...
    @overload
    def increment_self_overlap(self) -> void: ...
    @overload
    def intersect_residues(self, other_res: VarSolDRotamerDots) -> None: ...
    @overload
    def intersect_residues(self, classprotocols) -> void: ...
    @overload
    def msas_for_atom(self, atom_index: int) -> float: ...
    @overload
    def msas_for_atom(self, unsignedlong) -> double: ...
    @overload
    def ndots(self) -> int: ...
    @overload
    def ndots(self) -> unsignedlong: ...
    @overload
    def nshells_for_atom(self, atom_index: int) -> int: ...
    @overload
    def nshells_for_atom(self, unsignedlong) -> unsignedlong: ...
    @overload
    def overlaps(self, other: VarSolDRotamerDots) -> bool: ...
    @overload
    def overlaps(self, constclassprotocols) -> bool: ...
    def rotamer(self) -> pyrosetta.rosetta.core.conformation.Residue: ...
    def shell_radius_for_atom(self, atom_index: int, shell_index: int) -> float: ...
    @overload
    def write_dot_kinemage(self, kinfile: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def write_dot_kinemage(self, std) -> void: ...

class VarSolDistSasaCalculator(pyrosetta.rosetta.core.pose.metrics.StructureDependentCalculator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: VarSolDistSasaCalculator) -> None: ...
    @overload
    def __init__(self, arg0: VarSolDistSasaCalculator) -> None: ...
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.id.AtomID_Map_double_t: ...
    def clone(self) -> pyrosetta.rosetta.core.pose.metrics.PoseMetricCalculator: ...
    def get_self_ptr(self) -> VarSolDistSasaCalculator: ...
    def get_self_weak_ptr(self) -> pyrosetta.rosetta.std.weak_ptr_protocols_vardist_solaccess_VarSolDistSasaCalculator_t: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def set_atom_type_radii(self, atype_name: str, coll_radius: float, int_radius: float, nshells: int) -> None: ...
    def set_element_radii(self, atype_name: str, coll_radius: float, int_radius: float, nshells: int) -> None: ...
