import enum
from Bio.Align import Alignment as Alignment, interfaces as interfaces
from Bio.Seq import Seq as Seq
from Bio.SeqRecord import SeqRecord as SeqRecord

class State(enum.Enum):
    MATCH = ...
    QUERY_GAP = ...
    TARGET_GAP = ...
    NONE = ...

class AlignmentIterator(interfaces.AlignmentIterator):
    fmt: str
    def parse_btop(self, btop): ...
    def parse_cigar(self, cigar): ...
