import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.utility.tag
from typing import overload

class DeleteRegionMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, res_start: int, res_end: int) -> None: ...
    @overload
    def __init__(self, arg0: DeleteRegionMover) -> None: ...
    @overload
    def __init__(self, arg0: DeleteRegionMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> DeleteRegionMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def region(self, res_start: str, res_end: str) -> None: ...
    @overload
    def set_add_jump_on_rechain(self, add: bool) -> None: ...
    @overload
    def set_add_jump_on_rechain(self, bool) -> void: ...
    @overload
    def set_add_terminal_types_on_rechain(self, add: bool) -> None: ...
    @overload
    def set_add_terminal_types_on_rechain(self, bool) -> void: ...
    @overload
    def set_rechain(self, rechain: bool) -> None: ...
    @overload
    def set_rechain(self, bool) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...

class DeleteRegionMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DeleteRegionMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: DeleteRegionMoverCreator) -> None: ...
    def assign(self) -> DeleteRegionMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class InsertPoseIntoPoseMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, copy_pdbinfo: bool) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: str, arg2: str) -> None: ...
    @overload
    def __init__(self, src_pose: pyrosetta.rosetta.core.pose.Pose, res_start: str, res_end: str, copy_pdbinfo: bool) -> None: ...
    @overload
    def __init__(self, arg0: InsertPoseIntoPoseMover) -> None: ...
    @overload
    def __init__(self, arg0: InsertPoseIntoPoseMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> InsertPoseIntoPoseMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def end(self, res_end: str) -> None: ...
    @overload
    def end(self, conststd) -> void: ...
    @overload
    def end(self) -> str: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def src_pose(self, src_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def src_pose(self, constclasscore) -> void: ...
    @overload
    def start(self, res_start: str) -> None: ...
    @overload
    def start(self, conststd) -> void: ...
    @overload
    def start(self) -> str: ...

class InsertPoseIntoPoseMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: InsertPoseIntoPoseMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: InsertPoseIntoPoseMoverCreator) -> None: ...
    def assign(self) -> InsertPoseIntoPoseMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class KeepRegionMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, res_start: str, res_end: str) -> None: ...
    @overload
    def __init__(self, arg0: KeepRegionMover) -> None: ...
    @overload
    def __init__(self, arg0: KeepRegionMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> KeepRegionMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def end(self, res_end: str) -> None: ...
    @overload
    def end(self, conststd) -> void: ...
    @overload
    def end(self, res_end: int) -> None: ...
    @overload
    def end(self, unsignedlong) -> void: ...
    @overload
    def end(self) -> str: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def region(self, res_start: str, res_end: str) -> None: ...
    @overload
    def region(self) -> tuple[str, str]: ...
    @overload
    def start(self, res_start: str) -> None: ...
    @overload
    def start(self, conststd) -> void: ...
    @overload
    def start(self, res_start: int) -> None: ...
    @overload
    def start(self, unsignedlong) -> void: ...
    @overload
    def start(self) -> str: ...

class KeepRegionMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: KeepRegionMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: KeepRegionMoverCreator) -> None: ...
    def assign(self) -> KeepRegionMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ReplaceRegionMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, copy_pdbinfo: bool) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: str, arg2: str, arg3: int) -> None: ...
    @overload
    def __init__(self, src_pose: pyrosetta.rosetta.core.pose.Pose, src_pose_start: str, target_pose_start: str, span: int, copy_pdbinfo: bool) -> None: ...
    @overload
    def __init__(self, arg0: ReplaceRegionMover) -> None: ...
    @overload
    def __init__(self, arg0: ReplaceRegionMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> ReplaceRegionMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def src_pose(self, from_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def src_pose(self, constclasscore) -> void: ...
    @overload
    def src_pose_start(self) -> str: ...
    @overload
    def src_pose_start(self, start: str) -> None: ...
    @overload
    def src_pose_start(self, conststd) -> void: ...
    @overload
    def target_pose_start(self) -> str: ...
    @overload
    def target_pose_start(self, start: str) -> None: ...
    @overload
    def target_pose_start(self, conststd) -> void: ...

class ReplaceRegionMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ReplaceRegionMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: ReplaceRegionMoverCreator) -> None: ...
    def assign(self) -> ReplaceRegionMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
