import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.pose.metrics
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.constraint_generator
import pyrosetta.rosetta.protocols.forge.remodel
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from . import filters as filters, potentials as potentials, topology as topology
from typing import overload

class BluePrintBDR(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, filename: str, ss_from_blueprint: bool) -> None: ...
    @overload
    def __init__(self, arg0) -> None: ...
    @overload
    def __init__(self, blueprintOP, ss_from_blueprint: bool) -> None: ...
    @overload
    def __init__(self, arg0: BluePrintBDR) -> None: ...
    @overload
    def __init__(self, arg0: BluePrintBDR) -> None: ...
    @overload
    def add_instruction(self, bi) -> None: ...
    @overload
    def add_instruction(self, classstd) -> void: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def create_directed_dependency(self, u, v) -> None: ...
    @overload
    def dump_pdb_when_fail(self, dump_pdb_when_fail: str) -> None: ...
    @overload
    def dump_pdb_when_fail(self, conststd) -> void: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def instruction_size(self) -> int: ...
    @overload
    def instruction_size(self) -> unsignedlong: ...
    @overload
    def is_initialized(self) -> bool: ...
    @overload
    def is_initialized(self) -> bool: ...
    def loop_mover_str(self, *args, **kwargs): ...
    @overload
    def max_linear_chainbreak(self) -> float: ...
    @overload
    def max_linear_chainbreak(self) -> double: ...
    @overload
    def max_linear_chainbreak(self, threshold: float) -> None: ...
    @overload
    def max_linear_chainbreak(self, constdouble) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def num_fragpick(self) -> int: ...
    @overload
    def num_fragpick(self) -> unsignedlong: ...
    @overload
    def num_fragpick(self, num: int) -> None: ...
    @overload
    def num_fragpick(self, constunsignedlong) -> void: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def scorefunction(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def scorefunction(self, sfx: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def scorefunction(self, constclasscore) -> void: ...
    @overload
    def scorefunction(self, sfx: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def scorefunction(self, classstd) -> void: ...
    @overload
    def set_blueprint(self, filename: str) -> None: ...
    @overload
    def set_blueprint(self, conststd) -> void: ...
    @overload
    def set_blueprint(self, blp) -> None: ...
    @overload
    def set_blueprint(self, constclassstd) -> void: ...
    @overload
    def set_constraint_file(self, constraint_file: str) -> None: ...
    @overload
    def set_constraint_file(self, conststd) -> void: ...
    def set_constraints_NtoC(self, weight: float) -> None: ...
    @overload
    def set_rcgs(self, rcgs: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_forge_remodel_RemodelConstraintGenerator_t) -> None: ...
    @overload
    def set_rcgs(self, constclassutility) -> void: ...
    @overload
    def ss_from_blueprint(self, flag: bool) -> None: ...
    @overload
    def ss_from_blueprint(self, constbool) -> void: ...
    @overload
    def use_abego_bias(self) -> bool: ...
    @overload
    def use_abego_bias(self) -> bool: ...
    @overload
    def use_abego_bias(self, flag: bool) -> None: ...
    @overload
    def use_abego_bias(self, constbool) -> void: ...
    @overload
    def use_fullmer(self) -> bool: ...
    @overload
    def use_fullmer(self) -> bool: ...
    @overload
    def use_fullmer(self, flag: bool) -> None: ...
    @overload
    def use_fullmer(self, constbool) -> void: ...
    @overload
    def use_sequence_bias(self) -> bool: ...
    @overload
    def use_sequence_bias(self) -> bool: ...
    @overload
    def use_sequence_bias(self, flag: bool) -> None: ...
    @overload
    def use_sequence_bias(self, constbool) -> void: ...

class BluePrintBDRCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: BluePrintBDRCreator) -> None: ...
    @overload
    def __init__(self, arg0: BluePrintBDRCreator) -> None: ...
    def assign(self) -> BluePrintBDRCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class CircularPermutation(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CircularPermutation) -> None: ...
    @overload
    def __init__(self, arg0: CircularPermutation) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def new_terminal_pos(self) -> int: ...
    @overload
    def new_terminal_pos(self) -> unsignedlong: ...
    @overload
    def new_terminal_pos(self, s: int) -> None: ...
    @overload
    def new_terminal_pos(self, constunsignedlong) -> void: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def split_chains(self, pose: pyrosetta.rosetta.core.pose.Pose, pos: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def split_chains(self, classcore, constclassutility) -> void: ...
    @overload
    def which_chain(self, s: int, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def which_chain(self, constunsignedlong, constclasscore) -> unsignedlong: ...

class CircularPermutationCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CircularPermutationCreator) -> None: ...
    @overload
    def __init__(self, arg0: CircularPermutationCreator) -> None: ...
    def assign(self) -> CircularPermutationCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class MatchResidues:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MatchResidues) -> None: ...
    def assign(self) -> MatchResidues: ...
    @overload
    def compute(self, pose: pyrosetta.rosetta.core.pose.Pose, best_fit: pyrosetta.rosetta.utility.vector1_unsigned_long) -> float: ...
    @overload
    def compute(self, constclasscore, classutility) -> double: ...
    @overload
    def compute_comb(self, pose: pyrosetta.rosetta.core.pose.Pose, comb: pyrosetta.rosetta.utility.vector1_unsigned_long) -> float: ...
    @overload
    def compute_comb(self, constclasscore, constclassutility) -> double: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_attributes_and_subelements(attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t, ssl) -> None: ...
    @overload
    @staticmethod
    def provide_attributes_and_subelements(classstd, classutility) -> void: ...
    @overload
    def superimpose_comb(self, pose: pyrosetta.rosetta.core.pose.Pose, comb: pyrosetta.rosetta.utility.vector1_unsigned_long) -> float: ...
    @overload
    def superimpose_comb(self, classcore, constclassutility) -> double: ...
    @overload
    def threshold(self) -> float: ...
    @overload
    def threshold(self) -> double: ...
    @overload
    def threshold(self, value: float) -> None: ...
    @overload
    def threshold(self, double) -> void: ...

class MatchResiduesMover(MatchResidues, pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MatchResiduesMover) -> None: ...
    @overload
    def __init__(self, arg0: MatchResiduesMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> MatchResiduesMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class MatchResiduesMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MatchResiduesMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: MatchResiduesMoverCreator) -> None: ...
    def assign(self) -> MatchResiduesMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class NcontactsCalculator(pyrosetta.rosetta.core.pose.metrics.StructureDependentCalculator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, condist: float, isep_sep: int) -> None: ...
    @overload
    def __init__(self, arg0: NcontactsCalculator) -> None: ...
    @overload
    def __init__(self, arg0: NcontactsCalculator) -> None: ...
    def assign(self) -> NcontactsCalculator: ...
    def clone(self) -> pyrosetta.rosetta.core.pose.metrics.PoseMetricCalculator: ...
    @overload
    def contact_distance(self, r: float) -> None: ...
    @overload
    def contact_distance(self, constdouble) -> void: ...
    @overload
    def ignore_loops(self, b: bool) -> None: ...
    @overload
    def ignore_loops(self, constbool) -> void: ...
    @overload
    def ignore_same_sheet(self, b: bool) -> None: ...
    @overload
    def ignore_same_sheet(self, constbool) -> void: ...
    @overload
    def ignore_same_sselement(self, b: bool) -> None: ...
    @overload
    def ignore_same_sselement(self, constbool) -> void: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def use_only_calpha(self, b: bool) -> None: ...
    @overload
    def use_only_calpha(self, constbool) -> void: ...

class ResiduePair:
    orientation: str
    @overload
    def __init__(self, res1: int, res2: int, orient: str) -> None: ...
    @overload
    def __init__(self, arg0: ResiduePair) -> None: ...
    def assign(self) -> ResiduePair: ...

class SheetConstraintGenerator(pyrosetta.rosetta.protocols.constraint_generator.ConstraintGenerator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SheetConstraintGenerator) -> None: ...
    @overload
    def __init__(self, arg0: SheetConstraintGenerator) -> None: ...
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_scoring_constraints_Constraint_t: ...
    def assign(self) -> SheetConstraintGenerator: ...
    @overload
    @staticmethod
    def attributes_for_sheet_constraint_generator() -> None: ...
    @overload
    @staticmethod
    def attributes_for_sheet_constraint_generator(classstd) -> void: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.protocols.constraint_generator.ConstraintGenerator: ...
    @overload
    def initialize_from_blueprint(self, blueprint_file: str) -> None: ...
    @overload
    def initialize_from_blueprint(self, conststd) -> void: ...
    @overload
    def initialize_from_blueprint(self, bp) -> None: ...
    @overload
    def initialize_from_blueprint(self, classstd) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_angle_tolerance(self, angle_tolerance: float) -> None: ...
    @overload
    def set_angle_tolerance(self, constdouble) -> void: ...
    @overload
    def set_bb_dihedral_tolerance(self, dihedral_tolerance: float) -> None: ...
    @overload
    def set_bb_dihedral_tolerance(self, constdouble) -> void: ...
    @overload
    def set_cacb_dihedral_tolerance(self, dihedral_tolerance: float) -> None: ...
    @overload
    def set_cacb_dihedral_tolerance(self, constdouble) -> void: ...
    @overload
    def set_constrain_bb_angle(self, constrain_angle: bool) -> None: ...
    @overload
    def set_constrain_bb_angle(self, constbool) -> void: ...
    @overload
    def set_constrain_bb_cacb_dihedral(self, constrain_dihedral: bool) -> None: ...
    @overload
    def set_constrain_bb_cacb_dihedral(self, constbool) -> void: ...
    @overload
    def set_constrain_bb_dihedral(self, constrain_dihedral: bool) -> None: ...
    @overload
    def set_constrain_bb_dihedral(self, constbool) -> void: ...
    @overload
    def set_constrain_ca_ca_dist(self, constrain_dist_only: bool) -> None: ...
    @overload
    def set_constrain_ca_ca_dist(self, constbool) -> void: ...
    @overload
    def set_distance(self, dist: float) -> None: ...
    @overload
    def set_distance(self, constdouble) -> void: ...
    @overload
    def set_distance_tolerance(self, dist_tol: float) -> None: ...
    @overload
    def set_distance_tolerance(self, constdouble) -> void: ...
    @overload
    def set_flat_bottom_constraints(self, flat_csts: bool) -> None: ...
    @overload
    def set_flat_bottom_constraints(self, constbool) -> void: ...
    @overload
    def set_secstruct(self, ss: str) -> None: ...
    @overload
    def set_secstruct(self, conststd) -> void: ...
    @overload
    def set_strand_pairs(self, spairs: str) -> None: ...
    @overload
    def set_strand_pairs(self, conststd) -> void: ...
    def set_use_dssp(self, *args, **kwargs): ...
    @overload
    def set_weight(self, coef: float) -> None: ...
    @overload
    def set_weight(self, constdouble) -> void: ...

class SheetConstraintGeneratorCreator(pyrosetta.rosetta.protocols.constraint_generator.ConstraintGeneratorCreator):
    def __init__(self) -> None: ...
    def assign(self) -> SheetConstraintGeneratorCreator: ...
    @staticmethod
    def constraint_generator_name() -> str: ...
    def create_constraint_generator(self) -> pyrosetta.rosetta.protocols.constraint_generator.ConstraintGenerator: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SheetRemodelConstraintGenerator(pyrosetta.rosetta.protocols.forge.remodel.RemodelConstraintGenerator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SheetRemodelConstraintGenerator) -> None: ...
    @overload
    def __init__(self, arg0: SheetRemodelConstraintGenerator) -> None: ...
    def assign(self) -> SheetRemodelConstraintGenerator: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class SheetRemodelConstraintGeneratorCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SheetRemodelConstraintGeneratorCreator) -> None: ...
    @overload
    def __init__(self, arg0: SheetRemodelConstraintGeneratorCreator) -> None: ...
    def assign(self) -> SheetRemodelConstraintGeneratorCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
