import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from . import metrics as metrics
from typing import overload

class ClusterMetric:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ClusterMetric) -> None: ...
    def assign(self) -> ClusterMetric: ...
    @overload
    def distance(self, other: ClusterMetric) -> float: ...
    @overload
    def distance(self, constclassprotocols) -> double: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def parse_my_tag(self, pose: pyrosetta.rosetta.core.pose.Pose, tag: pyrosetta.rosetta.utility.tag.Tag, datacache: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, constclasscore, classstd, classbasic) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class ClusterMetricCreator:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ClusterMetricCreator) -> None: ...
    def assign(self) -> ClusterMetricCreator: ...
    def create_metric(self) -> ClusterMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ClusterMetricFactory(pyrosetta.rosetta.utility.SingletonBase_protocols_multistage_rosetta_scripts_cluster_ClusterMetricFactory_t):
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def cluster_metric_xml_schema_group_name() -> str: ...
    def creator_map(self) -> pyrosetta.rosetta.std.map_std_string_std_shared_ptr_protocols_multistage_rosetta_scripts_cluster_ClusterMetricCreator_t_std_allocator_std_pair_const_std_string_std_shared_ptr_protocols_multistage_rosetta_scripts_cluster_ClusterMetricCreator_t: ...
    @overload
    def define_cluster_metric_xml_schema(self, xsd) -> None: ...
    @overload
    def define_cluster_metric_xml_schema(self, classutility) -> void: ...
    @overload
    def factory_register(self, creator: ClusterMetricCreator) -> None: ...
    @overload
    def factory_register(self, classstd) -> void: ...
    @overload
    def has_type(self) -> bool: ...
    @overload
    def has_type(self, conststd) -> bool: ...
    def new_cluster_metric(self, selector_name: str, pose: pyrosetta.rosetta.core.pose.Pose, tag: pyrosetta.rosetta.utility.tag.Tag, datamap: pyrosetta.rosetta.basic.datacache.DataMap) -> ClusterMetric: ...
    @overload
    def provide_xml_schema(self, selector_name: str, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, conststd, classutility) -> void: ...
    @overload
    def set_throw_on_double_registration(self) -> None: ...
    @overload
    def set_throw_on_double_registration(self) -> void: ...

def complex_type_name_for_cluster_metric(cm_type: str) -> str: ...
@overload
def k_medoids_on_the_fly(points: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_protocols_multistage_rosetta_scripts_cluster_ClusterMetric_t, num_medoids: int, medoid_positions: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
@overload
def k_medoids_on_the_fly(constclassutility, constunsignedshort, classutility) -> void: ...
@overload
def k_medoids_on_the_fly(points: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_protocols_multistage_rosetta_scripts_cluster_ClusterMetric_t, num_medoids: int) -> pyrosetta.rosetta.utility.vector1_bool: ...
@overload
def k_medoids_with_edge_precalculation(points: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_protocols_multistage_rosetta_scripts_cluster_ClusterMetric_t, num_medoids: int, medoid_positions: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
@overload
def k_medoids_with_edge_precalculation(constclassutility, constunsignedshort, classutility) -> void: ...
@overload
def k_medoids_with_edge_precalculation(points: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_protocols_multistage_rosetta_scripts_cluster_ClusterMetric_t, num_medoids: int) -> pyrosetta.rosetta.utility.vector1_bool: ...
@overload
def vector_has_n_trues(vec: pyrosetta.rosetta.utility.vector1_bool, n: int) -> bool: ...
@overload
def vector_has_n_trues(constclassutility, int) -> bool: ...
def xsd_type_definition_w_attributes(xsd, cm_type: str, description: str, attributes: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
