import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.environment
import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from . import claims as claims
from typing import overload

class AutoCutData(pyrosetta.rosetta.basic.datacache.WriteableCacheableData):
    @overload
    def __init__(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def __init__(self, hash: int, cuts: pyrosetta.rosetta.std.set_unsigned_long_t) -> None: ...
    @overload
    def __init__(self, arg0: AutoCutData) -> None: ...
    @overload
    def __init__(self, arg0: AutoCutData) -> None: ...
    def assign(self) -> AutoCutData: ...
    def clone(self) -> pyrosetta.rosetta.basic.datacache.CacheableData: ...
    def cuts(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def datatype(self) -> str: ...
    def hash(self) -> int: ...
    @overload
    def write(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def write(self, std) -> void: ...

class AutoCutDataCreator(pyrosetta.rosetta.basic.datacache.WriteableCacheableDataCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AutoCutDataCreator) -> None: ...
    @overload
    def __init__(self, arg0: AutoCutDataCreator) -> None: ...
    def assign(self) -> AutoCutDataCreator: ...
    def create_data(self, _in: pyrosetta.rosetta.std.istream) -> pyrosetta.rosetta.basic.datacache.WriteableCacheableData: ...
    def keyname(self) -> str: ...

class ClientMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ClientMover) -> None: ...
    def assign(self) -> ClientMover: ...
    @overload
    def initialize(self, conf: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def initialize(self, classcore) -> void: ...
    def yield_claims(self) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_environment_claims_EnvClaim_t: ...
    @overload
    def yield_submovers(self) -> None: ...
    @overload
    def yield_submovers(self, classstd) -> void: ...

class CoMTrackerCM(ClientMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, name: str, mobile_selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, stationary_label: str) -> None: ...
    @overload
    def __init__(self, name: str, mobile_selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: CoMTrackerCM) -> None: ...
    @overload
    def __init__(self, arg0: CoMTrackerCM) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> CoMTrackerCM: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def initialize(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def initialize(self, classcore) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def name(self) -> str: ...
    @overload
    def name(self, name: str) -> None: ...
    @overload
    def name(self, conststd) -> void: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def yield_claims(self) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_environment_claims_EnvClaim_t: ...

class CoMTrackerCMCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CoMTrackerCMCreator) -> None: ...
    @overload
    def __init__(self, arg0: CoMTrackerCMCreator) -> None: ...
    def assign(self) -> CoMTrackerCMCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class DofUnlock:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DofUnlock) -> None: ...

class EXCN_Env_Passport(pyrosetta.rosetta.core.environment.EXCN_Env_Exception):
    def __init__(self, file: str, line: int, message: str, mover_name: str, env: pyrosetta.rosetta.std.weak_ptr_const_protocols_environment_Environment_t) -> None: ...
    def assign(self) -> EXCN_Env_Passport: ...

class EXCN_Env_Security_Exception(pyrosetta.rosetta.core.environment.EXCN_Env_Exception):
    @overload
    def __init__(self, file: str, line: int, dof: pyrosetta.rosetta.core.id.DOF_ID, _pass: pyrosetta.rosetta.core.environment.DofPassport, mod_type: str, mover_name: str, env: pyrosetta.rosetta.std.weak_ptr_const_protocols_environment_Environment_t) -> None: ...
    @overload
    def __init__(self, file: str, line: int, message: str, mover_name: str, env: pyrosetta.rosetta.std.weak_ptr_const_protocols_environment_Environment_t) -> None: ...
    @overload
    def __init__(self, arg0: EXCN_Env_Security_Exception) -> None: ...
    @overload
    def __init__(self, arg0: EXCN_Env_Security_Exception) -> None: ...
    def id(self) -> pyrosetta.rosetta.core.id.DOF_ID: ...
    def passport(self) -> pyrosetta.rosetta.core.environment.DofPassport: ...

class EnvClaimBroker:
    class BrokerResult:
        ann: pyrosetta.rosetta.core.environment.SequenceAnnotation
        auto_cuts: pyrosetta.rosetta.std.set_unsigned_long_t
        cached_data: pyrosetta.rosetta.basic.datacache.WriteableCacheableMap
        closer_ft: pyrosetta.rosetta.core.kinematics.FoldTree
        new_vrts: pyrosetta.rosetta.std.map_unsigned_long_std_string
        pose: pyrosetta.rosetta.core.pose.Pose
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: EnvClaimBroker.BrokerResult) -> None: ...
        def assign(self) -> EnvClaimBroker.BrokerResult: ...
    def __init__(self, arg0: EnvClaimBroker) -> None: ...
    def result(self, *args, **kwargs): ...

class EnvMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: EnvMover) -> None: ...
    @overload
    def __init__(self, arg0: EnvMover) -> None: ...
    @overload
    def add_apply_mover(self) -> None: ...
    @overload
    def add_apply_mover(self, classstd) -> void: ...
    @overload
    def add_registered_mover(self) -> None: ...
    @overload
    def add_registered_mover(self, classstd) -> void: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> EnvMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def env(self) -> Environment: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class EnvMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: EnvMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: EnvMoverCreator) -> None: ...
    def assign(self) -> EnvMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class Environment(pyrosetta.rosetta.core.environment.EnvCore):
    @overload
    def __init__(self, name: str) -> None: ...
    @overload
    def __init__(self, arg0: Environment) -> None: ...
    @overload
    def allow_pure_movers(self) -> bool: ...
    @overload
    def allow_pure_movers(self) -> bool: ...
    @overload
    def allow_pure_movers(self) -> None: ...
    @overload
    def allow_pure_movers(self, bool) -> void: ...
    def annotations(self) -> pyrosetta.rosetta.core.environment.SequenceAnnotation: ...
    @overload
    def auto_cut(self) -> bool: ...
    @overload
    def auto_cut(self) -> bool: ...
    @overload
    def auto_cut(self) -> None: ...
    @overload
    def auto_cut(self, bool) -> void: ...
    def broker(self, *args, **kwargs): ...
    def end(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    def get_self_ptr(self) -> Environment: ...
    def get_self_weak_ptr(self) -> pyrosetta.rosetta.std.weak_ptr_protocols_environment_Environment_t: ...
    @overload
    def inherit_cuts(self) -> bool: ...
    @overload
    def inherit_cuts(self) -> bool: ...
    @overload
    def inherit_cuts(self) -> None: ...
    @overload
    def inherit_cuts(self, bool) -> void: ...
    @overload
    def is_registered(self) -> bool: ...
    @overload
    def is_registered(self, classstd) -> bool: ...
    @overload
    def pconf_creation(self, ptr: pyrosetta.rosetta.core.conformation.Conformation) -> None: ...
    @overload
    def pconf_creation(self, classcore) -> void: ...
    @overload
    def pconf_destruction(self, ptr: pyrosetta.rosetta.core.conformation.Conformation) -> None: ...
    @overload
    def pconf_destruction(self, classcore) -> void: ...
    @overload
    def register_mover(self) -> None: ...
    @overload
    def register_mover(self, classstd) -> void: ...
    def start(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    def superenv(self) -> pyrosetta.rosetta.std.weak_ptr_const_protocols_environment_Environment_t: ...

class ProtectedConformation(pyrosetta.rosetta.core.conformation.Conformation):
    @overload
    def __init__(self, arg0: ProtectedConformation) -> None: ...
    @overload
    def __init__(self, arg0: ProtectedConformation) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def annotations(self) -> pyrosetta.rosetta.core.environment.SequenceAnnotation: ...
    @overload
    def append_polymer_residue_after_seqpos(self) -> None: ...
    @overload
    def append_polymer_residue_after_seqpos(self, constclasscore, constunsignedlong, constbool) -> void: ...
    @overload
    def append_residue_by_jump(self) -> None: ...
    @overload
    def append_residue_by_jump(self) -> None: ...
    @overload
    def append_residue_by_jump(self) -> None: ...
    @overload
    def append_residue_by_jump(self, _: bool) -> None: ...
    @overload
    def assign(self, src: pyrosetta.rosetta.core.conformation.Conformation) -> pyrosetta.rosetta.core.conformation.Conformation: ...
    @overload
    def assign(self) -> ProtectedConformation: ...
    def batch_set_xyz(self, id: pyrosetta.rosetta.utility.vector1_core_id_AtomID, position: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t) -> None: ...
    @overload
    def chain_endings(self) -> None: ...
    @overload
    def chain_endings(self, constclassutility) -> void: ...
    @overload
    def chains_from_termini(self) -> None: ...
    @overload
    def chains_from_termini(self) -> void: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    def clone(self) -> pyrosetta.rosetta.core.conformation.Conformation: ...
    def declare_chemical_bond(self) -> None: ...
    @overload
    def delete_chain_ending(self) -> None: ...
    @overload
    def delete_chain_ending(self, constunsignedlong) -> void: ...
    @overload
    def delete_polymer_residue(self) -> None: ...
    @overload
    def delete_polymer_residue(self, constunsignedlong) -> void: ...
    def delete_residue_range_slow(self, range_begin: int, range_end: int) -> None: ...
    @overload
    def delete_residue_slow(self) -> None: ...
    @overload
    def delete_residue_slow(self, constunsignedlong) -> void: ...
    @overload
    def env_destruction(self) -> None: ...
    @overload
    def env_destruction(self) -> void: ...
    def environment(self) -> pyrosetta.rosetta.std.weak_ptr_const_protocols_environment_Environment_t: ...
    @overload
    def fill_missing_atoms(self, missing: pyrosetta.rosetta.core.id.AtomID_Map_bool_t) -> None: ...
    @overload
    def fill_missing_atoms(self, classcore) -> void: ...
    def fix_disulfides(self) -> None: ...
    @overload
    def fold_tree(self) -> None: ...
    @overload
    def fold_tree(self, constclasscore) -> void: ...
    @overload
    def insert_chain_ending(self) -> None: ...
    @overload
    def insert_chain_ending(self, constunsignedlong) -> void: ...
    @overload
    def insert_conformation_by_jump(self) -> None: ...
    @overload
    def insert_conformation_by_jump(self) -> None: ...
    @overload
    def insert_conformation_by_jump(self) -> None: ...
    @overload
    def insert_ideal_geometry_at_polymer_bond(self, seqpos: int) -> None: ...
    @overload
    def insert_ideal_geometry_at_polymer_bond(self, constunsignedlong) -> void: ...
    def insert_ideal_geometry_at_residue_connection(self, pos1: int, connid1: int) -> None: ...
    @overload
    def is_protected(self) -> bool: ...
    @overload
    def is_protected(self) -> bool: ...
    def match_variants(self, seqpos: int, in_rsd: pyrosetta.rosetta.core.conformation.Residue) -> pyrosetta.rosetta.core.conformation.Residue: ...
    @overload
    def prepend_polymer_residue_before_seqpos(self) -> None: ...
    @overload
    def prepend_polymer_residue_before_seqpos(self, constclasscore, constunsignedlong, constbool) -> void: ...
    @overload
    def rebuild_polymer_bond_dependent_atoms(self) -> None: ...
    @overload
    def rebuild_polymer_bond_dependent_atoms(self, constunsignedlong) -> void: ...
    @overload
    def replace_residue(self, seqpos: int, new_rsd: pyrosetta.rosetta.core.conformation.Residue, atom_pairs: pyrosetta.rosetta.utility.vector1_std_pair_std_string_std_string_t) -> None: ...
    @overload
    def replace_residue(self, constunsignedlong, constclasscore, constclassutility, std) -> void: ...
    @overload
    def replace_residue(self, seqpos: int, new_rsd: pyrosetta.rosetta.core.conformation.Residue, orient_backbone: bool) -> None: ...
    @overload
    def replace_residue(self, constunsignedlong, constclasscore, constbool) -> void: ...
    @overload
    def reset_chain_endings(self) -> None: ...
    @overload
    def reset_chain_endings(self) -> void: ...
    @overload
    def reset_move_data(self) -> None: ...
    @overload
    def reset_move_data(self) -> void: ...
    def resolver(self) -> pyrosetta.rosetta.core.environment.SequenceAnnotation: ...
    @overload
    def safely_append_polymer_residue_after_seqpos(self) -> None: ...
    @overload
    def safely_append_polymer_residue_after_seqpos(self, constclasscore, constunsignedlong, constbool) -> void: ...
    @overload
    def safely_prepend_polymer_residue_before_seqpos(self) -> None: ...
    @overload
    def safely_prepend_polymer_residue_before_seqpos(self, constclasscore, constunsignedlong, constbool) -> void: ...
    @overload
    def same_type_as_me(self, other: pyrosetta.rosetta.core.conformation.Conformation, recurse: bool) -> bool: ...
    @overload
    def same_type_as_me(self, constclasscore, constbool) -> bool: ...
    def set_bond_angle(self, atom1: pyrosetta.rosetta.core.id.AtomID, atom2: pyrosetta.rosetta.core.id.AtomID, atom3: pyrosetta.rosetta.core.id.AtomID, setting: float) -> None: ...
    def set_bond_length(self, atom1: pyrosetta.rosetta.core.id.AtomID, atom2: pyrosetta.rosetta.core.id.AtomID, setting: float) -> None: ...
    @overload
    def set_dof(self, id: pyrosetta.rosetta.core.id.DOF_ID, setting: float) -> None: ...
    @overload
    def set_dof(self, constclasscore, constdouble) -> void: ...
    @overload
    def set_jump(self) -> None: ...
    @overload
    def set_jump(self) -> None: ...
    @overload
    def set_jump(self, constint, constclasscore) -> void: ...
    def set_polymeric_connection(self) -> None: ...
    @overload
    def set_secstruct(self, seqpos: int, setting: str) -> None: ...
    @overload
    def set_secstruct(self, constunsignedlong, constchar) -> void: ...
    def set_stub_transform(self, stub_id1: pyrosetta.rosetta.core.id.StubID, stub_id2: pyrosetta.rosetta.core.id.StubID, target_rt: pyrosetta.rosetta.core.kinematics.RT) -> None: ...
    @overload
    def set_torsion(self, id: pyrosetta.rosetta.core.id.TorsionID, setting: float) -> None: ...
    @overload
    def set_torsion(self, constclasscore, constdouble) -> void: ...
    @overload
    def set_torsion_angle(self, atom1: pyrosetta.rosetta.core.id.AtomID, atom2: pyrosetta.rosetta.core.id.AtomID, atom3: pyrosetta.rosetta.core.id.AtomID, atom4: pyrosetta.rosetta.core.id.AtomID, setting: float) -> None: ...
    @overload
    def set_torsion_angle(self, atom1: pyrosetta.rosetta.core.id.AtomID, atom2: pyrosetta.rosetta.core.id.AtomID, atom3: pyrosetta.rosetta.core.id.AtomID, atom4: pyrosetta.rosetta.core.id.AtomID, setting: float, quiet: bool) -> None: ...
    @overload
    def set_xyz(self, id: pyrosetta.rosetta.core.id.AtomID, position: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_xyz(self, constclasscore, constclassnumeric) -> void: ...

class ScriptCM(ClientMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ScriptCM) -> None: ...
    @overload
    def __init__(self, arg0: ScriptCM) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> ScriptCM: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def initialize(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def initialize(self, classcore) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def name(self) -> str: ...
    @overload
    def name(self, name: str) -> None: ...
    @overload
    def name(self, conststd) -> void: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @staticmethod
    def scriptcm_group_name() -> str: ...
    @staticmethod
    def scriptcm_subelement_ct_namer() -> str: ...
    def yield_claims(self) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_environment_claims_EnvClaim_t: ...

class ScriptCMCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ScriptCMCreator) -> None: ...
    @overload
    def __init__(self, arg0: ScriptCMCreator) -> None: ...
    def assign(self) -> ScriptCMCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
