import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.environment
import pyrosetta.rosetta.core.fragment
import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.protocols.environment
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import ClassVar, overload

CAN_CONTROL: ControlStrength
DOES_NOT_CONTROL: ControlStrength
EXCLUSIVE: ControlStrength
MUST_CONTROL: ControlStrength

class ClaimStrength:
    class PrioSubtype:
        __members__: ClassVar[dict] = ...  # read-only
        CAN_CONTROL: ClassVar[ClaimStrength.PrioSubtype] = ...
        DOES_NOT_CONTROL: ClassVar[ClaimStrength.PrioSubtype] = ...
        EXCLUSIVE: ClassVar[ClaimStrength.PrioSubtype] = ...
        MUST_CONTROL: ClassVar[ClaimStrength.PrioSubtype] = ...
        __entries: ClassVar[dict] = ...
        def __init__(self, value: int) -> None: ...
        def __and__(self, other: object) -> object: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> int: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> object: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: object) -> object: ...
        def __rand__(self, other: object) -> object: ...
        def __ror__(self, other: object) -> object: ...
        def __rxor__(self, other: object) -> object: ...
        def __xor__(self, other: object) -> object: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...
    CAN_CONTROL: ClassVar[ClaimStrength.PrioSubtype] = ...
    DOES_NOT_CONTROL: ClassVar[ClaimStrength.PrioSubtype] = ...
    EXCLUSIVE: ClassVar[ClaimStrength.PrioSubtype] = ...
    MUST_CONTROL: ClassVar[ClaimStrength.PrioSubtype] = ...
    @overload
    def __init__(self, type) -> None: ...
    @overload
    def __init__(self, type, subprio: int) -> None: ...
    @overload
    def __init__(self, arg0: ClaimStrength) -> None: ...
    def assign(self) -> ClaimStrength: ...
    @overload
    def subprio(self) -> int: ...
    @overload
    def subprio(self) -> unsignedlong: ...
    def subtype(self) -> ClaimStrength.PrioSubtype: ...
    def __eq__(self) -> bool: ...
    def __ne__(self) -> bool: ...

class ControlStrength:
    __members__: ClassVar[dict] = ...  # read-only
    CAN_CONTROL: ClassVar[ControlStrength] = ...
    DOES_NOT_CONTROL: ClassVar[ControlStrength] = ...
    EXCLUSIVE: ClassVar[ControlStrength] = ...
    MUST_CONTROL: ClassVar[ControlStrength] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class CutBiasClaim(EnvClaim):
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, label: str, ss: pyrosetta.rosetta.core.fragment.SecondaryStructure) -> None: ...
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, label: str, biases: pyrosetta.rosetta.std.map_core_environment_LocalPosition_double) -> None: ...
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, label: str, range: tuple[int, int], bias: float) -> None: ...
    @overload
    def __init__(self, arg0: CutBiasClaim) -> None: ...
    @overload
    def __init__(self, arg0: CutBiasClaim) -> None: ...
    def assign(self) -> CutBiasClaim: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> EnvClaim: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def show(self, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def type(self) -> str: ...

class CutBiasElement:
    bias: float
    p: pyrosetta.rosetta.core.environment.LocalPosition
    def __init__(self) -> None: ...

class CutElement:
    p: pyrosetta.rosetta.core.environment.LocalPosition
    def __init__(self) -> None: ...

class DOFElement:
    c_str: ControlStrength
    i_str: ControlStrength
    id: pyrosetta.rosetta.core.id.DOF_ID
    def __init__(self) -> None: ...

class EnvClaim:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: EnvClaim) -> None: ...
    @overload
    def annotate(self) -> None: ...
    @overload
    def annotate(self, constclasscore, classstd) -> void: ...
    def assign(self) -> EnvClaim: ...
    def clone(self) -> EnvClaim: ...
    @overload
    @staticmethod
    def define_envclaim_schema_group(xsd) -> None: ...
    @overload
    @staticmethod
    def define_envclaim_schema_group(classutility) -> void: ...
    @staticmethod
    def envclaim_ct_namer() -> str: ...
    @staticmethod
    def envclaim_group_name() -> str: ...
    @overload
    @staticmethod
    def is_claim(name: str) -> bool: ...
    @overload
    @staticmethod
    def is_claim(conststd) -> bool: ...
    @staticmethod
    def make_claim(name: str, owner: pyrosetta.rosetta.protocols.environment.ClientMover, tag: pyrosetta.rosetta.utility.tag.Tag, datamap: pyrosetta.rosetta.basic.datacache.DataMap) -> EnvClaim: ...
    def owner(self) -> pyrosetta.rosetta.protocols.environment.ClientMover: ...
    @overload
    def set_owner(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover) -> None: ...
    @overload
    def set_owner(self, classstd) -> void: ...
    @overload
    def show(self, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def type(self) -> str: ...

class EnvLabelSelector(pyrosetta.rosetta.core.select.residue_selector.ResidueSelector):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: EnvLabelSelector) -> None: ...
    @overload
    def __init__(self, arg0: EnvLabelSelector) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, label: str, range: tuple[int, int]) -> None: ...
    @overload
    def add_position(self, p: pyrosetta.rosetta.core.environment.LocalPosition) -> None: ...
    @overload
    def add_position(self, constclasscore) -> void: ...
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def assign(self) -> EnvLabelSelector: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    def get_name(self) -> str: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def local_positions(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_environment_LocalPosition_t: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, datamap: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_local_positions(self) -> None: ...
    @overload
    def set_local_positions(self, constclassutility) -> void: ...

class JumpClaim(EnvClaim):
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.protocols.environment.ClientMover, arg1: str, arg2: pyrosetta.rosetta.core.environment.LocalPosition, arg3: pyrosetta.rosetta.core.environment.LocalPosition) -> None: ...
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, label: str, pos1: pyrosetta.rosetta.core.environment.LocalPosition, pos2: pyrosetta.rosetta.core.environment.LocalPosition, cutp: pyrosetta.rosetta.core.environment.LocalPosition) -> None: ...
    @overload
    def __init__(self, arg0: JumpClaim) -> None: ...
    @overload
    def __init__(self, arg0: JumpClaim) -> None: ...
    def assign(self) -> JumpClaim: ...
    def atoms(self) -> tuple[str, str]: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> EnvClaim: ...
    def create_vrt_if_necessary(self, *args, **kwargs): ...
    @overload
    def cut(self) -> None: ...
    @overload
    def cut(self, constclasscore) -> void: ...
    def label(self) -> str: ...
    @overload
    def physical(self) -> bool: ...
    @overload
    def physical(self) -> bool: ...
    @overload
    def physical(self, setting: bool) -> None: ...
    @overload
    def physical(self, bool) -> void: ...
    def pos1(self) -> pyrosetta.rosetta.core.environment.LocalPosition: ...
    def pos2(self) -> pyrosetta.rosetta.core.environment.LocalPosition: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def set_atoms(self, a1: str, a2: str) -> None: ...
    @overload
    def show(self, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def strength(self, cstr: ControlStrength, istr: ControlStrength) -> None: ...
    @overload
    def stubs_intra_residue(self, setting: bool) -> None: ...
    @overload
    def stubs_intra_residue(self, bool) -> void: ...
    @overload
    def stubs_intra_residue(self) -> bool: ...
    @overload
    def stubs_intra_residue(self) -> bool: ...
    def type(self) -> str: ...

class JumpElement:
    atom1: str
    atom2: str
    force_stub_intra_residue: bool
    has_physical_cut: bool
    label: str
    p1: pyrosetta.rosetta.core.environment.LocalPosition
    p2: pyrosetta.rosetta.core.environment.LocalPosition
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: JumpElement) -> None: ...
    def assign(self) -> JumpElement: ...

class ResidueElement:
    allow_duplicates: bool
    label: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ResidueElement) -> None: ...
    def assign(self) -> ResidueElement: ...

class TorsionClaim(EnvClaim):
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, local_pos: pyrosetta.rosetta.core.environment.LocalPosition) -> None: ...
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, label: str, range: tuple[int, int]) -> None: ...
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, positions: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_environment_LocalPosition_t) -> None: ...
    @overload
    def __init__(self, arg0: TorsionClaim) -> None: ...
    @overload
    def __init__(self, arg0: TorsionClaim) -> None: ...
    def assign(self) -> TorsionClaim: ...
    @overload
    def claim_backbone(self, _in: bool) -> None: ...
    @overload
    def claim_backbone(self, bool) -> void: ...
    @overload
    def claim_backbone(self) -> bool: ...
    @overload
    def claim_backbone(self) -> bool: ...
    @overload
    def claim_sidechain(self, _in: bool) -> None: ...
    @overload
    def claim_sidechain(self, bool) -> void: ...
    @overload
    def claim_sidechain(self) -> bool: ...
    @overload
    def claim_sidechain(self) -> bool: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> EnvClaim: ...
    def ctrl_strength(self) -> ControlStrength: ...
    def init_strength(self) -> ControlStrength: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    def show(self, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def strength(self, control_strength: ControlStrength, initialization_strength: ControlStrength) -> None: ...
    def type(self) -> str: ...

class VirtResClaim(EnvClaim):
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, parent: pyrosetta.rosetta.core.environment.LocalPosition, jump_label: str, vrt_label: str) -> None: ...
    @overload
    def __init__(self, arg0: VirtResClaim) -> None: ...
    @overload
    def __init__(self, arg0: VirtResClaim) -> None: ...
    def assign(self) -> VirtResClaim: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> EnvClaim: ...
    def jump(self) -> JumpClaim: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def show(self, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def strength(self, cstr: ControlStrength, istr: ControlStrength) -> None: ...
    def type(self) -> str: ...
    def vrt_label(self) -> str: ...

class XYZClaim(EnvClaim):
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, local_pos: pyrosetta.rosetta.core.environment.LocalPosition) -> None: ...
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, label: str, range: tuple[int, int]) -> None: ...
    @overload
    def __init__(self, owner: pyrosetta.rosetta.protocols.environment.ClientMover, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: XYZClaim) -> None: ...
    @overload
    def __init__(self, arg0: XYZClaim) -> None: ...
    def assign(self) -> XYZClaim: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> EnvClaim: ...
    def ctrl_strength(self) -> ControlStrength: ...
    def init_strength(self) -> ControlStrength: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def relative(self) -> bool: ...
    @overload
    def relative(self) -> bool: ...
    def selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    def set_relative(self, s: bool) -> None: ...
    @overload
    def set_relative(self, bool) -> void: ...
    @overload
    def show(self, os: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def strength(self, control: ControlStrength, initialization: ControlStrength) -> None: ...
    def type(self) -> str: ...
