import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.fragment
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.protocols.environment
import pyrosetta.rosetta.protocols.jumping
import pyrosetta.rosetta.protocols.loops
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import ClassVar, overload

END: StageID
I: StageID
II: StageID
IIIa: StageID
IIIb: StageID
IVa: StageID
IVb: StageID

class AbscriptLoopCloserCM(pyrosetta.rosetta.protocols.environment.ClientMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, fragset: pyrosetta.rosetta.core.fragment.FragSet, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: AbscriptLoopCloserCM) -> None: ...
    @overload
    def __init__(self, arg0: AbscriptLoopCloserCM) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> AbscriptLoopCloserCM: ...
    @overload
    def broking_finished(self) -> None: ...
    @overload
    def broking_finished(self, conststructprotocols) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    def set_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_selector(self, classstd) -> void: ...
    def yield_claims(self) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_environment_claims_EnvClaim_t: ...

class AbscriptLoopCloserCMCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AbscriptLoopCloserCMCreator) -> None: ...
    @overload
    def __init__(self, arg0: AbscriptLoopCloserCMCreator) -> None: ...
    def assign(self) -> AbscriptLoopCloserCMCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class AbscriptMover(pyrosetta.rosetta.protocols.environment.ClientMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AbscriptMover) -> None: ...
    @overload
    def __init__(self, arg0: AbscriptMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> AbscriptMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def initialize(self) -> None: ...
    @overload
    def initialize(self, classcore) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @staticmethod
    def stage_complex_namer() -> str: ...
    def yield_claims(self) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_environment_claims_EnvClaim_t: ...
    @overload
    def yield_submovers(self) -> None: ...
    @overload
    def yield_submovers(self, classstd) -> void: ...

class AbscriptMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AbscriptMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: AbscriptMoverCreator) -> None: ...
    def assign(self) -> AbscriptMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class AbscriptStageMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, stage: StageID, mc, score: pyrosetta.rosetta.core.scoring.ScoreFunction, cycles: int) -> None: ...
    @overload
    def __init__(self, arg0: AbscriptStageMover) -> None: ...
    @overload
    def __init__(self, arg0: AbscriptStageMover) -> None: ...
    @overload
    def add_preparer(self, mover) -> None: ...
    @overload
    def add_preparer(self, classstd) -> void: ...
    @overload
    def add_submover(self, mover: pyrosetta.rosetta.protocols.environment.ClientMover, weight: float) -> None: ...
    @overload
    def add_submover(self, classstd, double) -> void: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def get_name(self) -> str: ...
    def scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    def seq_sep_intercept(self) -> float: ...
    def set_chainbreak_ramping(self, slope: float, intercept: float) -> None: ...
    @overload
    def set_cycles_adjust(self, _in: float) -> None: ...
    @overload
    def set_cycles_adjust(self, double) -> void: ...
    def set_seq_sep_ramping(self, slope: float, intercept: float) -> None: ...
    def setup_stage(self, pose: pyrosetta.rosetta.core.pose.Pose, progress: float) -> bool: ...
    @overload
    def yield_submovers(self, set: pyrosetta.rosetta.std.set_std_shared_ptr_protocols_environment_ClientMover_t) -> None: ...
    @overload
    def yield_submovers(self, classstd) -> void: ...

class ConstraintPreparer(StagePreparer):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ConstraintPreparer) -> None: ...
    @overload
    def __init__(self, arg0: ConstraintPreparer) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> ConstraintPreparer: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def combine_exclude_file(self, filename: str) -> None: ...
    @overload
    def combine_exclude_file(self, conststd) -> void: ...
    def combine_exclude_res(self) -> pyrosetta.rosetta.utility.vector1_bool: ...
    @overload
    def combine_ratio(self, s: int) -> None: ...
    @overload
    def combine_ratio(self) -> int: ...
    @overload
    def cst_file(self) -> None: ...
    @overload
    def cst_file(self, conststd) -> void: ...
    @overload
    def cst_file(self) -> str: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def prepare(self, pose: pyrosetta.rosetta.core.pose.Pose, progress: float) -> None: ...
    @overload
    def prepare(self, classcore, double) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def random_drop_rate(self) -> float: ...
    @overload
    def random_drop_rate(self) -> double: ...
    @overload
    def random_drop_rate(self, s: float) -> None: ...
    @overload
    def skip_redundant(self) -> bool: ...
    @overload
    def skip_redundant(self) -> bool: ...
    @overload
    def skip_redundant(self, s: bool) -> None: ...
    @overload
    def skip_redundant(self, bool) -> void: ...
    @overload
    def skip_redundant_width(self) -> int: ...
    @overload
    def skip_redundant_width(self) -> unsignedlong: ...
    @overload
    def skip_redundant_width(self, s: int) -> None: ...
    def yield_claims(self) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_environment_claims_EnvClaim_t: ...

class ConstraintPreparerCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ConstraintPreparerCreator) -> None: ...
    @overload
    def __init__(self, arg0: ConstraintPreparerCreator) -> None: ...
    def assign(self) -> ConstraintPreparerCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class FragmentCM(pyrosetta.rosetta.protocols.environment.ClientMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FragmentCM) -> None: ...
    @overload
    def __init__(self, arg0: FragmentCM) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> FragmentCM: ...
    def get_name(self) -> str: ...
    @overload
    def initialize(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def initialize(self, classcore) -> void: ...
    @overload
    def initialize(self) -> bool: ...
    @overload
    def initialize(self) -> bool: ...
    @overload
    def initialize(self, setting: bool) -> None: ...
    @overload
    def initialize(self, bool) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    def set_mover(self, mover) -> None: ...
    @overload
    def set_mover(self, classstd) -> void: ...
    @overload
    def set_selector(self) -> None: ...
    @overload
    def set_selector(self, classstd) -> void: ...
    def yield_claims(self) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_environment_claims_EnvClaim_t: ...
    @overload
    def yield_cut_bias(self) -> bool: ...
    @overload
    def yield_cut_bias(self) -> bool: ...
    @overload
    def yield_cut_bias(self, setting: bool) -> None: ...
    @overload
    def yield_cut_bias(self, bool) -> void: ...

class FragmentCMCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FragmentCMCreator) -> None: ...
    @overload
    def __init__(self, arg0: FragmentCMCreator) -> None: ...
    def assign(self) -> FragmentCMCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class FragmentJumpCM(FragmentCM):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, topol_filename: str, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, moverkey: str) -> None: ...
    @overload
    def __init__(self, arg0: FragmentJumpCM) -> None: ...
    @overload
    def __init__(self, arg0: FragmentJumpCM) -> None: ...
    def assign(self) -> FragmentJumpCM: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    def moverkey(self) -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_moverkey(self, key: str) -> None: ...
    @overload
    def set_moverkey(self, conststd) -> void: ...
    @overload
    def set_topology(self, topology_file: str) -> None: ...
    @overload
    def set_topology(self, conststd) -> void: ...
    @overload
    def set_topology(self, ss_info_file: str, pairing_file: str, n_sheets: int, bRandomSheets: bool) -> None: ...
    def yield_claims(self) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_environment_claims_EnvClaim_t: ...

class FragmentJumpCMCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FragmentJumpCMCreator) -> None: ...
    @overload
    def __init__(self, arg0: FragmentJumpCMCreator) -> None: ...
    def assign(self) -> FragmentJumpCMCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class JumpSampleData(pyrosetta.rosetta.basic.datacache.WriteableCacheableData):
    @overload
    def __init__(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def __init__(self, arg0: JumpSampleData) -> None: ...
    @overload
    def __init__(self, arg0: JumpSampleData) -> None: ...
    def assign(self) -> JumpSampleData: ...
    def clone(self) -> pyrosetta.rosetta.basic.datacache.CacheableData: ...
    def datatype(self) -> str: ...
    def jump_sample(self) -> pyrosetta.rosetta.protocols.jumping.JumpSample: ...
    def moverkey(self) -> str: ...
    @overload
    def write(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def write(self, std) -> void: ...

class JumpSampleDataCreator(pyrosetta.rosetta.basic.datacache.WriteableCacheableDataCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: JumpSampleDataCreator) -> None: ...
    @overload
    def __init__(self, arg0: JumpSampleDataCreator) -> None: ...
    def assign(self) -> JumpSampleDataCreator: ...
    def create_data(self, _in: pyrosetta.rosetta.std.istream) -> pyrosetta.rosetta.basic.datacache.WriteableCacheableData: ...
    def keyname(self) -> str: ...

class RigidChunkCM(pyrosetta.rosetta.protocols.environment.ClientMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, template_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: RigidChunkCM) -> None: ...
    @overload
    def __init__(self, arg0: RigidChunkCM) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidChunkCM: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def initialize(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def initialize(self, classcore) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def select_parts(self, rigid_core: pyrosetta.rosetta.protocols.loops.Loops, random_grow_loops_by: int) -> pyrosetta.rosetta.protocols.loops.Loops: ...
    def sim_origin(self) -> pyrosetta.rosetta.std.map_unsigned_long_unsigned_long: ...
    @overload
    def sim_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def sim_selector(self, classstd) -> void: ...
    @overload
    def sim_selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    def templ(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    def templ_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def templ_selector(self, classstd) -> void: ...
    @overload
    def templ_selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    def templ_target(self) -> pyrosetta.rosetta.std.map_unsigned_long_unsigned_long: ...
    def yield_claims(self) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_environment_claims_EnvClaim_t: ...

class RigidChunkCMCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RigidChunkCMCreator) -> None: ...
    @overload
    def __init__(self, arg0: RigidChunkCMCreator) -> None: ...
    def assign(self) -> RigidChunkCMCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class StageID:
    __members__: ClassVar[dict] = ...  # read-only
    END: ClassVar[StageID] = ...
    I: ClassVar[StageID] = ...
    II: ClassVar[StageID] = ...
    IIIa: ClassVar[StageID] = ...
    IIIb: ClassVar[StageID] = ...
    IVa: ClassVar[StageID] = ...
    IVb: ClassVar[StageID] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class StagePreparer(pyrosetta.rosetta.protocols.environment.ClientMover):
    @overload
    def __init__(self, arg0: StagePreparer) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def assign(self) -> StagePreparer: ...
    @overload
    def prepare(self, pose: pyrosetta.rosetta.core.pose.Pose, progress: float) -> None: ...
    @overload
    def prepare(self, classcore, double) -> void: ...

class StructPerturberCM(pyrosetta.rosetta.protocols.environment.ClientMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, label: str, magnitude: float) -> None: ...
    @overload
    def __init__(self, arg0: StructPerturberCM) -> None: ...
    @overload
    def __init__(self, arg0: StructPerturberCM) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> StructPerturberCM: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def label(self) -> str: ...
    @overload
    def label(self, label: str) -> None: ...
    @overload
    def label(self, conststd) -> void: ...
    @overload
    def magnitude(self) -> float: ...
    @overload
    def magnitude(self, value: float) -> None: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def yield_claims(self) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_environment_claims_EnvClaim_t: ...

class StructPerturberCMCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: StructPerturberCMCreator) -> None: ...
    @overload
    def __init__(self, arg0: StructPerturberCMCreator) -> None: ...
    def assign(self) -> StructPerturberCMCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
