import pyrosetta.rosetta.core.chemical.rna
import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.protocols.recces.sampler
import pyrosetta.rosetta.protocols.toolbox
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import overload

class MC_RNA_KIC_Sampler(pyrosetta.rosetta.protocols.recces.sampler.MC_Sampler):
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.pose.Pose, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, mc_pose: pyrosetta.rosetta.core.pose.Pose, moving_suite: int, chainbreak_suite: int, change_ft: bool) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    @overload
    def check_moved(self) -> bool: ...
    @overload
    def check_moved(self) -> bool: ...
    @overload
    def choose_solution(self) -> None: ...
    @overload
    def choose_solution(self) -> void: ...
    def find(self, torsion_id: pyrosetta.rosetta.core.id.TorsionID) -> pyrosetta.rosetta.protocols.recces.sampler.MC_Sampler: ...
    def get_name(self) -> str: ...
    @overload
    def get_next_solutions(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def get_next_solutions(self, constclasscore) -> void: ...
    @overload
    def init(self) -> None: ...
    @overload
    def init(self) -> void: ...
    @overload
    def next(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def next(self, constclasscore) -> void: ...
    def pre_increment(self) -> None: ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self) -> void: ...
    @overload
    def set_angle_range_from_init_torsions(self, range: float) -> None: ...
    @overload
    def set_angle_range_from_init_torsions(self, constdouble) -> void: ...
    @overload
    def set_gaussian_stdev(self, setting: float) -> None: ...
    @overload
    def set_gaussian_stdev(self, constdouble) -> void: ...
    @overload
    def set_max_tries(self, setting: int) -> None: ...
    @overload
    def set_max_tries(self, constunsignedlong) -> void: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream, indent: int) -> None: ...
    @overload
    def show(self, std, constunsignedlong) -> void: ...
    def type(self) -> pyrosetta.rosetta.protocols.toolbox.SamplerPlusPlusType: ...
    @overload
    def update(self) -> None: ...
    @overload
    def update(self) -> void: ...

class MC_RNA_MultiSuite(pyrosetta.rosetta.protocols.recces.sampler.MC_Comb):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MC_RNA_MultiSuite) -> None: ...
    @overload
    def __init__(self, arg0: MC_RNA_MultiSuite) -> None: ...
    @overload
    def add_rotamer(self, rotamer) -> None: ...
    @overload
    def add_rotamer(self, classstd) -> void: ...
    def assign(self) -> MC_RNA_MultiSuite: ...
    @overload
    def clear_rotamer(self) -> None: ...
    @overload
    def clear_rotamer(self) -> void: ...
    def pre_increment(self) -> None: ...
    @overload
    def set_angle(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_angle(self, constclasscore) -> void: ...
    def set_do_no_op_random(self, setting: bool) -> None: ...
    @overload
    def set_gaussian_stdev(self, setting: float) -> None: ...
    @overload
    def set_gaussian_stdev(self, constdouble) -> void: ...
    @overload
    def set_gaussian_stdev(self, setting: float, rotamer_id: int) -> None: ...
    @overload
    def set_gaussian_stdev(self, constdouble, constunsignedlong) -> void: ...
    @overload
    def set_init_from_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_init_from_pose(self, constclasscore) -> void: ...
    @overload
    def set_pucker_flip_rate(self, setting: float) -> None: ...
    @overload
    def set_pucker_flip_rate(self, constdouble) -> void: ...
    @overload
    def set_pucker_flip_rate(self, setting: float, rotamer_id: int) -> None: ...
    @overload
    def set_pucker_flip_rate(self, constdouble, constunsignedlong) -> void: ...
    def type(self) -> pyrosetta.rosetta.protocols.toolbox.SamplerPlusPlusType: ...

class MC_RNA_OneJump(pyrosetta.rosetta.protocols.recces.sampler.MC_Sampler):
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, jump_num: int) -> None: ...
    @overload
    def __init__(self, arg0: MC_RNA_OneJump) -> None: ...
    @overload
    def __init__(self, arg0: MC_RNA_OneJump) -> None: ...
    def active_jump(self) -> pyrosetta.rosetta.core.kinematics.Jump: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def find(self, torsion_id: pyrosetta.rosetta.core.id.TorsionID) -> pyrosetta.rosetta.protocols.recces.sampler.MC_Sampler: ...
    @overload
    def init(self) -> None: ...
    @overload
    def init(self) -> void: ...
    def pre_increment(self) -> None: ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self) -> void: ...
    @overload
    def set_jump(self, setting: pyrosetta.rosetta.core.kinematics.Jump) -> None: ...
    @overload
    def set_jump(self, constclasscore) -> void: ...
    def set_rmsd_cutoff(self, setting: float) -> None: ...
    def set_rotation_mag(self, setting: float) -> None: ...
    def set_translation_mag(self, setting: float) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream, indent: int) -> None: ...
    @overload
    def show(self, std, constunsignedlong) -> void: ...
    def stored_jump(self) -> pyrosetta.rosetta.core.kinematics.Jump: ...
    def type(self) -> pyrosetta.rosetta.protocols.toolbox.SamplerPlusPlusType: ...
    @overload
    def update(self) -> None: ...
    @overload
    def update(self) -> void: ...

class MC_RNA_Sugar(pyrosetta.rosetta.protocols.recces.sampler.MC_Sampler):
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: float) -> None: ...
    @overload
    def __init__(self, rsd_id: int, flip_rate: float, init_pucker: pyrosetta.rosetta.core.chemical.rna.PuckerState) -> None: ...
    @overload
    def __init__(self, arg0: MC_RNA_Sugar) -> None: ...
    @overload
    def __init__(self, arg0: MC_RNA_Sugar) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> MC_RNA_Sugar: ...
    def find(self, torsion_id: pyrosetta.rosetta.core.id.TorsionID) -> pyrosetta.rosetta.protocols.recces.sampler.MC_Sampler: ...
    def get_name(self) -> str: ...
    @overload
    def init(self) -> None: ...
    @overload
    def init(self) -> void: ...
    def pre_increment(self) -> None: ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self) -> void: ...
    @overload
    def set_flip_rate(self, setting: float) -> None: ...
    @overload
    def set_flip_rate(self, constdouble) -> void: ...
    @overload
    def set_idealize_coord(self, setting: bool) -> None: ...
    @overload
    def set_idealize_coord(self, constbool) -> void: ...
    @overload
    def set_skip_same_pucker(self, setting: bool) -> None: ...
    @overload
    def set_skip_same_pucker(self, constbool) -> void: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream, indent: int) -> None: ...
    @overload
    def show(self, std, constunsignedlong) -> void: ...
    def type(self) -> pyrosetta.rosetta.protocols.toolbox.SamplerPlusPlusType: ...
    @overload
    def update(self) -> None: ...
    @overload
    def update(self) -> void: ...

class MC_RNA_Suite(pyrosetta.rosetta.protocols.recces.sampler.MC_Comb):
    @overload
    def __init__(self, rsd_id: int) -> None: ...
    @overload
    def __init__(self, arg0: MC_RNA_Suite) -> None: ...
    @overload
    def __init__(self, arg0: MC_RNA_Suite) -> None: ...
    @overload
    def clear_rotamer(self) -> None: ...
    @overload
    def clear_rotamer(self) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def init(self) -> None: ...
    @overload
    def init(self) -> void: ...
    @overload
    def set_a_form_range(self, setting: float) -> None: ...
    @overload
    def set_a_form_range(self, constdouble) -> void: ...
    @overload
    def set_angle(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_angle(self, constclasscore) -> void: ...
    @overload
    def set_angle_range_from_init(self, setting: float) -> None: ...
    @overload
    def set_angle_range_from_init(self, constdouble) -> void: ...
    @overload
    def set_gaussian_stdev(self, setting: float) -> None: ...
    @overload
    def set_gaussian_stdev(self, constdouble) -> void: ...
    @overload
    def set_idealize_coord(self, setting: bool) -> None: ...
    @overload
    def set_idealize_coord(self, constbool) -> void: ...
    @overload
    def set_init_from_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_init_from_pose(self, constclasscore) -> void: ...
    @overload
    def set_init_states(self, init_torsions: pyrosetta.rosetta.utility.vector1_double, init_pucker: pyrosetta.rosetta.core.chemical.rna.PuckerState) -> None: ...
    @overload
    def set_init_states(self, constclassutility, constenumcore) -> void: ...
    @overload
    def set_pucker_flip_rate(self, setting: float) -> None: ...
    @overload
    def set_pucker_flip_rate(self, constdouble) -> void: ...
    @overload
    def set_sample_bb(self, setting: bool) -> None: ...
    @overload
    def set_sample_bb(self, constbool) -> void: ...
    @overload
    def set_sample_lower_nucleoside(self, setting: bool) -> None: ...
    @overload
    def set_sample_lower_nucleoside(self, constbool) -> void: ...
    @overload
    def set_sample_near_a_form(self, setting: bool) -> None: ...
    @overload
    def set_sample_near_a_form(self, constbool) -> void: ...
    @overload
    def set_sample_upper_nucleoside(self, setting: bool) -> None: ...
    @overload
    def set_sample_upper_nucleoside(self, constbool) -> void: ...
    @overload
    def set_skip_same_pucker(self, setting: bool) -> None: ...
    @overload
    def set_skip_same_pucker(self, constbool) -> void: ...
    def type(self) -> pyrosetta.rosetta.protocols.toolbox.SamplerPlusPlusType: ...
