import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility.tag
from . import local_backbone_mover as local_backbone_mover
from typing import overload

class RandomizeBBByRamaPrePro(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RandomizeBBByRamaPrePro) -> None: ...
    @overload
    def __init__(self, arg0: RandomizeBBByRamaPrePro) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RandomizeBBByRamaPrePro: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_residue_selector(self, selector_in: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, constclassstd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class RandomizeBBByRamaPreProCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RandomizeBBByRamaPreProCreator) -> None: ...
    @overload
    def __init__(self, arg0: RandomizeBBByRamaPreProCreator) -> None: ...
    def assign(self) -> RandomizeBBByRamaPreProCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
