import pyrosetta.rosetta.basic.citation_manager
import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.scoring.sasa
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.core.simple_metrics
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.excn
import pyrosetta.rosetta.utility.tag
from typing import ClassVar, overload

bogus: summary_type
mean: summary_type
n_res_eq: summary_type
n_res_gt: summary_type
n_res_gt_or_eq: summary_type
n_res_lt: summary_type
n_res_lt_or_eq: summary_type
n_res_ne: summary_type
sum: summary_type
summary_type_total: summary_type

class AverageProbabilitiesMetric(pyrosetta.rosetta.core.simple_metrics.PerResidueProbabilitiesMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, metrics: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_simple_metrics_SimpleMetric_t, weights: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, arg0: AverageProbabilitiesMetric) -> None: ...
    @overload
    def __init__(self, arg0: AverageProbabilitiesMetric) -> None: ...
    def assign(self) -> AverageProbabilitiesMetric: ...
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self, citations: pyrosetta.rosetta.basic.citation_manager.CitationCollectionList) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_fail_on_missing_cache(self, fail: bool) -> None: ...
    @overload
    def set_fail_on_missing_cache(self, bool) -> void: ...
    def set_metric(self, metrics: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_simple_metrics_SimpleMetric_t, weights: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_use_cached_data(self, use_cache: bool) -> None: ...
    @overload
    def set_use_cached_data(self, use_cache: bool, prefix: str) -> None: ...
    @overload
    def set_use_cached_data(self, use_cache: bool, prefix: str, suffix: str) -> None: ...

class AverageProbabilitiesMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> AverageProbabilitiesMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class CalculatorMetric(pyrosetta.rosetta.core.simple_metrics.RealMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, equation: str) -> None: ...
    @overload
    def __init__(self, arg0: CalculatorMetric) -> None: ...
    @overload
    def __init__(self, arg0: CalculatorMetric) -> None: ...
    @overload
    def add_constant(self, name: str, value: float) -> None: ...
    @overload
    def add_constant(self, conststd, double) -> void: ...
    def add_reported_value(self, name: str, report_key: str) -> None: ...
    @overload
    def add_simple_metric(self, name: str, metric: pyrosetta.rosetta.core.simple_metrics.SimpleMetric) -> None: ...
    @overload
    def add_simple_metric(self, conststd, classstd) -> void: ...
    def assign(self) -> CalculatorMetric: ...
    @overload
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate(self, constclasscore) -> double: ...
    @overload
    def check_equation(self) -> bool: ...
    @overload
    def check_equation(self) -> bool: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class CalculatorMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> CalculatorMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class CustomRealValueMetric(pyrosetta.rosetta.core.simple_metrics.RealMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CustomRealValueMetric) -> None: ...
    @overload
    def __init__(self, arg0: CustomRealValueMetric) -> None: ...
    def assign(self) -> CustomRealValueMetric: ...
    @overload
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate(self, constclasscore) -> double: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self, citations: pyrosetta.rosetta.basic.citation_manager.CitationCollectionList) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_value(self, value_in: float) -> None: ...
    @overload
    def set_value(self, constdouble) -> void: ...

class CustomRealValueMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> CustomRealValueMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class CustomStringValueMetric(pyrosetta.rosetta.core.simple_metrics.StringMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CustomStringValueMetric) -> None: ...
    @overload
    def __init__(self, arg0: CustomStringValueMetric) -> None: ...
    def assign(self) -> CustomStringValueMetric: ...
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> str: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self, citations: pyrosetta.rosetta.basic.citation_manager.CitationCollectionList) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_value(self, value_in: str) -> None: ...
    @overload
    def set_value(self, conststd) -> void: ...

class CustomStringValueMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> CustomStringValueMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class DihedralDistanceMetric(pyrosetta.rosetta.core.simple_metrics.RealMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: DihedralDistanceMetric) -> None: ...
    @overload
    def __init__(self, arg0: DihedralDistanceMetric) -> None: ...
    def assign(self) -> DihedralDistanceMetric: ...
    def calculate(self, *args, **kwargs): ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_comparison_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_comparison_pose(self, classstd) -> void: ...
    @overload
    def set_include_protein_omega(self, include_omega: bool) -> None: ...
    @overload
    def set_include_protein_omega(self, bool) -> void: ...
    def set_residue_mapping(self, res_map: pyrosetta.rosetta.std.map_unsigned_long_unsigned_long) -> None: ...
    @overload
    def set_residue_selector(self, residue_selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    @overload
    def set_residue_selector_reference(self, residue_selector_ref: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector_reference(self, classstd) -> void: ...

class DihedralDistanceMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> DihedralDistanceMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class EXCN_CalcFailed(pyrosetta.rosetta.utility.excn.Exception):
    @overload
    def __init__(self, arg0: EXCN_CalcFailed) -> None: ...
    @overload
    def __init__(self, arg0: EXCN_CalcFailed) -> None: ...
    @overload
    def __init__(self, file: str, line: int, msg: str) -> None: ...
    def assign(self) -> EXCN_CalcFailed: ...

class EXCN_InitFailed(pyrosetta.rosetta.utility.excn.Exception):
    @overload
    def __init__(self, arg0: EXCN_InitFailed) -> None: ...
    @overload
    def __init__(self, arg0: EXCN_InitFailed) -> None: ...
    @overload
    def __init__(self, file: str, line: int, msg: str) -> None: ...
    def assign(self) -> EXCN_InitFailed: ...

class InteractionEnergyMetric(pyrosetta.rosetta.core.simple_metrics.RealMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, selector1: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, selector2: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: InteractionEnergyMetric) -> None: ...
    @overload
    def __init__(self, arg0: InteractionEnergyMetric) -> None: ...
    def assign(self) -> InteractionEnergyMetric: ...
    @overload
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate(self, constclasscore) -> double: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_ignore_scoretypes(self, ignore_scoretypes: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    @overload
    def set_ignore_scoretypes(self, constclassutility) -> void: ...
    @overload
    def set_include_only_scoretypes(self, include_only_scoretypes: pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType) -> None: ...
    @overload
    def set_include_only_scoretypes(self, constclassutility) -> void: ...
    @overload
    def set_include_rama_prepro_and_proclose(self, include: bool) -> None: ...
    @overload
    def set_include_rama_prepro_and_proclose(self, bool) -> void: ...
    def set_residue_selectors(self, selector1: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, selector2: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_scorefunction(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefunction(self, classstd) -> void: ...

class InteractionEnergyMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> InteractionEnergyMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class RMSDMetric(pyrosetta.rosetta.core.simple_metrics.RealMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ref_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, ref_pose: pyrosetta.rosetta.core.pose.Pose, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: RMSDMetric) -> None: ...
    @overload
    def __init__(self, arg0: RMSDMetric) -> None: ...
    def assign(self) -> RMSDMetric: ...
    @overload
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate(self, constclasscore) -> double: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_comparison_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_comparison_pose(self, classstd) -> void: ...
    @overload
    def set_corresponding_atoms_robust(self, robust: bool) -> None: ...
    @overload
    def set_corresponding_atoms_robust(self, bool) -> void: ...
    def set_cyclic_residue_mappings(self, rmsd_maps: pyrosetta.rosetta.std.vector_std_map_unsigned_long_unsigned_long_t) -> None: ...
    def set_residue_mapping(self, rmsd_map: pyrosetta.rosetta.std.map_unsigned_long_unsigned_long) -> None: ...
    @overload
    def set_residue_selector(self, residue_selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    @overload
    def set_residue_selector_reference(self, residue_selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector_reference(self, classstd) -> void: ...
    @overload
    def set_residue_selector_super(self, residue_selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector_super(self, classstd) -> void: ...
    @overload
    def set_residue_selector_super_reference(self, residue_selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector_super_reference(self, classstd) -> void: ...
    @overload
    def set_rmsd_type(self, rmsd_type: pyrosetta.rosetta.core.scoring.rmsd_atoms) -> None: ...
    @overload
    def set_rmsd_type(self, enumcore) -> void: ...
    @overload
    def set_run_superimpose(self, super: bool) -> None: ...
    @overload
    def set_run_superimpose(self, bool) -> void: ...

class RMSDMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> RMSDMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ResidueSummaryMetric(pyrosetta.rosetta.core.simple_metrics.RealMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, metric: pyrosetta.rosetta.core.simple_metrics.PerResidueRealMetric) -> None: ...
    @overload
    def __init__(self, arg0: ResidueSummaryMetric) -> None: ...
    @overload
    def __init__(self, arg0: ResidueSummaryMetric) -> None: ...
    def assign(self) -> ResidueSummaryMetric: ...
    @overload
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate(self, constclasscore) -> double: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_action(self, sum_type: summary_type) -> None: ...
    @overload
    def set_action(self, enumcore) -> void: ...
    @overload
    def set_action_value(self, cutoff: float) -> None: ...
    @overload
    def set_action_value(self, double) -> void: ...
    @overload
    def set_epsilon(self, epsilon: float) -> None: ...
    @overload
    def set_epsilon(self, double) -> void: ...
    @overload
    def set_fail_on_missing_cache(self, fail: bool) -> None: ...
    @overload
    def set_fail_on_missing_cache(self, bool) -> void: ...
    @overload
    def set_metric(self, metric: pyrosetta.rosetta.core.simple_metrics.PerResidueRealMetric) -> None: ...
    @overload
    def set_metric(self, classstd) -> void: ...
    @overload
    def set_use_cached_data(self, use_cache: bool) -> None: ...
    @overload
    def set_use_cached_data(self, use_cache: bool, prefix: str) -> None: ...
    @overload
    def set_use_cached_data(self, use_cache: bool, prefix: str, suffix: str) -> None: ...

class ResidueSummaryMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> ResidueSummaryMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SasaMetric(pyrosetta.rosetta.core.simple_metrics.RealMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, mode: pyrosetta.rosetta.core.scoring.sasa.SasaMethodHPMode) -> None: ...
    @overload
    def __init__(self, arg0: SasaMetric) -> None: ...
    @overload
    def __init__(self, arg0: SasaMetric) -> None: ...
    def assign(self) -> SasaMetric: ...
    @overload
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate(self, constclasscore) -> double: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def sasa_metric_mode(self) -> pyrosetta.rosetta.core.scoring.sasa.SasaMethodHPMode: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    @overload
    def set_sasa_metric_mode(self, mode_in: pyrosetta.rosetta.core.scoring.sasa.SasaMethodHPMode) -> None: ...
    @overload
    def set_sasa_metric_mode(self, constenumcore) -> void: ...
    @overload
    def set_sasa_metric_mode(self, mode_in: str) -> None: ...
    @overload
    def set_sasa_metric_mode(self, conststd) -> void: ...

class SasaMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> SasaMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SecondaryStructureMetric(pyrosetta.rosetta.core.simple_metrics.StringMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: SecondaryStructureMetric) -> None: ...
    @overload
    def __init__(self, arg0: SecondaryStructureMetric) -> None: ...
    def assign(self) -> SecondaryStructureMetric: ...
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> str: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    @overload
    def set_use_dssp_reduced(self, reduced: bool) -> None: ...
    @overload
    def set_use_dssp_reduced(self, bool) -> void: ...

class SecondaryStructureMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> SecondaryStructureMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SelectedResidueCountMetric(pyrosetta.rosetta.core.simple_metrics.RealMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SelectedResidueCountMetric) -> None: ...
    @overload
    def __init__(self, arg0: SelectedResidueCountMetric) -> None: ...
    def assign(self) -> SelectedResidueCountMetric: ...
    @overload
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate(self, constclasscore) -> double: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def remove_residue_selector(self) -> None: ...
    @overload
    def remove_residue_selector(self) -> void: ...
    @overload
    def set_residue_selector(self, selector_in: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...

class SelectedResidueCountMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> SelectedResidueCountMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SelectedResiduesMetric(pyrosetta.rosetta.core.simple_metrics.StringMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: SelectedResiduesMetric) -> None: ...
    @overload
    def __init__(self, arg0: SelectedResiduesMetric) -> None: ...
    def assign(self) -> SelectedResiduesMetric: ...
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> str: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_output_in_rosetta_num(self, output_in_rosetta_num: bool) -> None: ...
    @overload
    def set_output_in_rosetta_num(self, bool) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...

class SelectedResiduesMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> SelectedResiduesMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SelectedResiduesPyMOLMetric(pyrosetta.rosetta.core.simple_metrics.StringMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: SelectedResiduesPyMOLMetric) -> None: ...
    @overload
    def __init__(self, arg0: SelectedResiduesPyMOLMetric) -> None: ...
    def assign(self) -> SelectedResiduesPyMOLMetric: ...
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> str: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    @overload
    def set_use_rosetta_numbering(self, setting: bool) -> None: ...
    @overload
    def set_use_rosetta_numbering(self, constbool) -> void: ...
    @overload
    def use_rosetta_numbering(self) -> bool: ...
    @overload
    def use_rosetta_numbering(self) -> bool: ...

class SelectedResiduesPyMOLMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> SelectedResiduesPyMOLMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SequenceMetric(pyrosetta.rosetta.core.simple_metrics.StringMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: SequenceMetric) -> None: ...
    @overload
    def __init__(self, arg0: SequenceMetric) -> None: ...
    @staticmethod
    def allowed_output_modes() -> str: ...
    @staticmethod
    def allowed_output_modes_as_vector() -> pyrosetta.rosetta.utility.vector1_std_string: ...
    def assign(self) -> SequenceMetric: ...
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> str: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def metric(self) -> str: ...
    @staticmethod
    def mode_enum_from_name(mode_string: str) -> SequenceMetricMode: ...
    @staticmethod
    def mode_name_from_enum(mode_enum: SequenceMetricMode) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_output_mode(self, mode_in: SequenceMetricMode) -> None: ...
    @overload
    def set_output_mode(self, constenumcore) -> void: ...
    @overload
    def set_output_mode(self, mode_in: str) -> None: ...
    @overload
    def set_output_mode(self, conststd) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...

class SequenceMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> SequenceMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SequenceMetricMode:
    __members__: ClassVar[dict] = ...  # read-only
    BASE_NAME: ClassVar[SequenceMetricMode] = ...
    END_OF_LIST: ClassVar[SequenceMetricMode] = ...
    FULL_NAME: ClassVar[SequenceMetricMode] = ...
    INVALID_MODE: ClassVar[SequenceMetricMode] = ...
    ONELETTER_CODE: ClassVar[SequenceMetricMode] = ...
    THREELETTER_CODE: ClassVar[SequenceMetricMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class SequenceSimilarityMetric(pyrosetta.rosetta.core.simple_metrics.RealMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: SequenceSimilarityMetric) -> None: ...
    @overload
    def __init__(self, arg0: SequenceSimilarityMetric) -> None: ...
    def assign(self) -> SequenceSimilarityMetric: ...
    @overload
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate(self, constclasscore) -> double: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @staticmethod
    def score(seq1: str, seq2: str, normalize: bool) -> float: ...
    @overload
    def set_apply_selector_to_native(self, setting: bool) -> None: ...
    @overload
    def set_apply_selector_to_native(self, bool) -> void: ...
    @overload
    def set_native_pose(self, setting: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_native_pose(self, classstd) -> void: ...
    @overload
    def set_native_pose(self, setting: pyrosetta.rosetta.core.pose.Pose, apply_selector_to_native: bool) -> None: ...
    @overload
    def set_native_pose(self, classstd, bool) -> void: ...
    @overload
    def set_normalize(self, setting: bool) -> None: ...
    @overload
    def set_normalize(self, bool) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, apply_selector_to_native: bool) -> None: ...
    @overload
    def set_residue_selector(self, classstd, bool) -> void: ...

class SequenceSimilarityMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> SequenceSimilarityMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ShapeSimilarityMetric(pyrosetta.rosetta.core.simple_metrics.RealMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ShapeSimilarityMetric) -> None: ...
    @overload
    def __init__(self, arg0: ShapeSimilarityMetric) -> None: ...
    def assign(self) -> ShapeSimilarityMetric: ...
    @overload
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate(self, constclasscore) -> double: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data_map: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def quick(self, quick: int) -> None: ...
    def verbose(self, verbose: int) -> None: ...
    def write_int_area(self, write_int_area: bool) -> None: ...

class ShapeSimilarityMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> ShapeSimilarityMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class TimingProfileMetric(pyrosetta.rosetta.core.simple_metrics.RealMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TimingProfileMetric) -> None: ...
    @overload
    def __init__(self, arg0: TimingProfileMetric) -> None: ...
    def assign(self) -> TimingProfileMetric: ...
    @overload
    def calc_time(self) -> float: ...
    @overload
    def calc_time(self) -> double: ...
    @overload
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate(self, constclasscore) -> double: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_calc_in_hours(self, calc_in_hours: bool) -> None: ...
    @overload
    def set_calc_in_hours(self, bool) -> void: ...

class TimingProfileMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> TimingProfileMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class TotalEnergyMetric(pyrosetta.rosetta.core.simple_metrics.RealMetric):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: TotalEnergyMetric) -> None: ...
    @overload
    def __init__(self, arg0: TotalEnergyMetric) -> None: ...
    def assign(self) -> TotalEnergyMetric: ...
    @overload
    def calculate(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate(self, constclasscore) -> double: ...
    def clone(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def metric(self) -> str: ...
    def name(self) -> str: ...
    @staticmethod
    def name_static() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_comparison_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_comparison_pose(self, classstd) -> void: ...
    @overload
    def set_residue_selector(self, residue_selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    @overload
    def set_scorefunction(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefunction(self, classstd) -> void: ...
    @overload
    def set_scoretype(self, scoretype: pyrosetta.rosetta.core.scoring.ScoreType) -> None: ...
    @overload
    def set_scoretype(self, enumcore) -> void: ...

class TotalEnergyMetricCreator(pyrosetta.rosetta.core.simple_metrics.SimpleMetricCreator):
    def __init__(self) -> None: ...
    def assign(self) -> TotalEnergyMetricCreator: ...
    def create_simple_metric(self) -> pyrosetta.rosetta.core.simple_metrics.SimpleMetric: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class summary_type:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    bogus: ClassVar[summary_type] = ...
    mean: ClassVar[summary_type] = ...
    n_res_eq: ClassVar[summary_type] = ...
    n_res_gt: ClassVar[summary_type] = ...
    n_res_gt_or_eq: ClassVar[summary_type] = ...
    n_res_lt: ClassVar[summary_type] = ...
    n_res_lt_or_eq: ClassVar[summary_type] = ...
    n_res_ne: ClassVar[summary_type] = ...
    sum: ClassVar[summary_type] = ...
    summary_type_total: ClassVar[summary_type] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

def get_summary_type_strings() -> pyrosetta.rosetta.utility.vector1_std_string: ...
