import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.utility
from . import hashing as hashing
from typing import overload

class BoundingBox_numeric_xyzVector_double_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pp: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def __init__(self, lower: pyrosetta.rosetta.numeric.xyzVector_double_t, upper: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def __init__(self, arg0: BoundingBox_numeric_xyzVector_double_t) -> None: ...
    @overload
    def add(self, pp: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def add(self, constclassnumeric) -> void: ...
    def assign(self, bb: BoundingBox_numeric_xyzVector_double_t) -> BoundingBox_numeric_xyzVector_double_t: ...
    @overload
    def contains(self, x: float, y: float, z: float) -> bool: ...
    @overload
    def contains(self, p: pyrosetta.rosetta.numeric.xyzVector_double_t) -> bool: ...
    @overload
    def contains(self, constclassnumeric) -> bool: ...
    @overload
    def intersects(self, bb: BoundingBox_numeric_xyzVector_double_t) -> bool: ...
    @overload
    def intersects(self, constclassnumeric) -> bool: ...
    def lower(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self, p: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def reset(self, constclassnumeric) -> void: ...
    @overload
    def set_lower(self, p: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_lower(self, constclassnumeric) -> void: ...
    @overload
    def set_upper(self, p: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def set_upper(self, constclassnumeric) -> void: ...
    @overload
    def translate(self, t: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def translate(self, constclassnumeric) -> void: ...
    def upper(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...

@overload
def are_coplanar(ring_point_coords: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t) -> bool: ...
@overload
def are_coplanar(constclassutility) -> bool: ...
def projection_area(xs: pyrosetta.rosetta.utility.vector1_double, ys: pyrosetta.rosetta.utility.vector1_double, elements_rad: pyrosetta.rosetta.utility.vector1_double, probe_radius: float) -> float: ...
@overload
def residual_squared_of_points_to_plane(point_coords: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t, vector_normal_to_plane: pyrosetta.rosetta.numeric.xyzVector_double_t) -> float: ...
@overload
def residual_squared_of_points_to_plane(constclassutility, constclassnumeric) -> double: ...
@overload
def vector_normal_to_ring_plane_of_best_fit(ring_point_coords: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
@overload
def vector_normal_to_ring_plane_of_best_fit(ring_point_coords: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t, co_planar_check: bool) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
