import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.numeric.geometry
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import overload

class Ball:
    atomno_: int
    radius_: int
    resid_: int
    x_: float
    y_: float
    z_: float
    def __init__(self) -> None: ...
    @overload
    def atomno(self) -> int: ...
    @overload
    def atomno(self) -> unsignedlong: ...
    @overload
    def radius(self) -> float: ...
    @overload
    def radius(self) -> float: ...
    @overload
    def radius(self, radius: float) -> None: ...
    @overload
    def radius(self, float) -> void: ...
    @overload
    def resi(self) -> int: ...
    @overload
    def resi(self) -> unsignedlong: ...
    def x(self) -> float: ...
    def xyz(self) -> pyrosetta.rosetta.numeric.xyzVector_float_t: ...
    def xyz_real(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def y(self) -> float: ...
    def z(self) -> float: ...

class Counter:
    count: int
    def __init__(self) -> None: ...
    def visit(self) -> None: ...

class MinimalClashHash:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, grid_resolution: float) -> None: ...
    @overload
    def __init__(self, grid_resolution: float, ball_radius: float) -> None: ...
    @overload
    def __init__(self, grid_resolution: float, ball_radius: float, balls: pyrosetta.rosetta.utility.vector1_numeric_geometry_hashing_Ball) -> None: ...
    @overload
    def __init__(self, arg0: MinimalClashHash) -> None: ...
    def assign(self) -> MinimalClashHash: ...
    @overload
    def clash(self, v: pyrosetta.rosetta.numeric.xyzVector_float_t) -> bool: ...
    @overload
    def clash(self, constclassnumeric) -> bool: ...
    @overload
    def clash_ball(self, b: Ball) -> bool: ...
    @overload
    def clash_ball(self, conststructnumeric) -> bool: ...
    @overload
    def clash_check_balls(self, bs: pyrosetta.rosetta.utility.vector1_numeric_geometry_hashing_Ball) -> int: ...
    @overload
    def clash_check_balls(self, bs: pyrosetta.rosetta.utility.vector1_numeric_geometry_hashing_Ball, clash_limit: int) -> int: ...
    @overload
    def clash_check_balls(self, constclassutility, unsignedlong) -> unsignedlong: ...
    @overload
    def init(self, balls: pyrosetta.rosetta.utility.vector1_numeric_geometry_hashing_Ball) -> None: ...
    @overload
    def init(self, constclassutility) -> void: ...

class SixDCoordinateBinner:
    @overload
    def __init__(self, bounding_box: pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t, euler_offsets: pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_3UL_t, bin_widths: pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t) -> None: ...
    @overload
    def __init__(self, arg0: SixDCoordinateBinner) -> None: ...
    def assign(self) -> SixDCoordinateBinner: ...
    def bin6(self, values: pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t) -> pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_6UL_t: ...
    def bin_center_point(self, bin: pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_6UL_t) -> pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t: ...
    def bin_from_index(self, index: int) -> pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_6UL_t: ...
    @overload
    def bin_index(self, bin: pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_6UL_t) -> int: ...
    @overload
    def bin_index(self, values: pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t) -> int: ...
    def bin_widths(self) -> pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t: ...
    def bounding_box(self) -> pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t: ...
    def bounding_volume_from_index(self, index: int) -> pyrosetta.rosetta.numeric.geometry.BoundingBox_numeric_xyzVector_double_t: ...
    def contains(self, point: pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t) -> bool: ...
    def dimsizes(self) -> pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_6UL_t: ...
    def euler_offsets(self) -> pyrosetta.rosetta.utility.fixedsizearray1_double_3UL_t: ...
    def halfbin6(self, values: pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t) -> pyrosetta.rosetta.utility.fixedsizearray1_unsigned_long_6UL_t: ...
    def halfbin_widths(self) -> pyrosetta.rosetta.utility.fixedsizearray1_double_6UL_t: ...
    @overload
    def tree_init(self, max_radius: int) -> None: ...
    @overload
    def tree_init(self, unsignedlong) -> void: ...

class SixDOffsetTree:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SixDOffsetTree) -> None: ...
    def assign(self) -> SixDOffsetTree: ...
    @overload
    def init(self, max_radius: int) -> None: ...
    @overload
    def init(self, unsignedlong) -> void: ...

class bin_index_hasher:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: bin_index_hasher) -> None: ...
    def assign(self) -> bin_index_hasher: ...
    def __call__(self, bin_index: int) -> int: ...

class xyzStripeHash:
    class const_iterator:
        def __init__(self, p: Ball) -> None: ...
        def arrow(self) -> pyrosetta.rosetta.numeric.xyzVector_float_t: ...
        def dereference(self) -> pyrosetta.rosetta.numeric.xyzVector_float_t: ...
        @overload
        def radius(self) -> float: ...
        @overload
        def radius(self) -> float: ...

    class iter_base_numeric_geometry_hashing_xyzStripeHash_const_iterator_t:
        def __init__(self, p: Ball) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, grid_size: float) -> None: ...
    @overload
    def __init__(self, grid_size: float, balls: pyrosetta.rosetta.utility.vector1_numeric_geometry_hashing_Ball) -> None: ...
    @overload
    def __init__(self, arg0: xyzStripeHash) -> None: ...
    def assign(self) -> xyzStripeHash: ...
    def ball(self, ib: int) -> Ball: ...
    @overload
    def clash(self, v_in: pyrosetta.rosetta.numeric.xyzVector_float_t) -> bool: ...
    @overload
    def clash(self, constclassnumeric) -> bool: ...
    @overload
    def clash_amount(self, v_in: pyrosetta.rosetta.numeric.xyzVector_float_t) -> float: ...
    @overload
    def clash_amount(self, constclassnumeric) -> float: ...
    @overload
    def clash_check_ball(self, b: Ball) -> int: ...
    @overload
    def clash_check_ball(self, conststructnumeric) -> int: ...
    def clash_check_residue_pairs(self, test_balls: pyrosetta.rosetta.utility.vector1_numeric_geometry_hashing_Ball, residue_pairs: pyrosetta.rosetta.std.map_unsigned_long_unsigned_long) -> bool: ...
    @overload
    def clash_not_resid(self, v_in: pyrosetta.rosetta.numeric.xyzVector_float_t, resid: int) -> bool: ...
    @overload
    def clash_not_resid(self, v_in: pyrosetta.rosetta.numeric.xyzVector_float_t, resid: int, resid2: int) -> bool: ...
    @overload
    def clash_raw(self, v: pyrosetta.rosetta.numeric.xyzVector_float_t) -> bool: ...
    @overload
    def clash_raw(self, constclassnumeric) -> bool: ...
    @overload
    def debug_pdb(self) -> str: ...
    @overload
    def debug_pdb(self, x: pyrosetta.rosetta.numeric.xyzTransform_double_t) -> str: ...
    @overload
    def fill_pairs(self, v: pyrosetta.rosetta.numeric.xyzVector_float_t, ir: int, pairs: pyrosetta.rosetta.utility.vector1_std_pair_int_int_t) -> None: ...
    @overload
    def fill_pairs(self, v: pyrosetta.rosetta.numeric.xyzVector_float_t, ir: int, pairs: pyrosetta.rosetta.utility.vector1_std_pair_int_int_t, maxd2: float) -> None: ...
    def grid_atoms(self) -> Ball: ...
    @overload
    def grid_size(self) -> float: ...
    @overload
    def grid_size(self) -> float: ...
    @overload
    def grid_size2(self) -> float: ...
    @overload
    def grid_size2(self) -> float: ...
    @overload
    def init(self, balls: pyrosetta.rosetta.utility.vector1_numeric_geometry_hashing_Ball) -> None: ...
    @overload
    def init(self, constclassutility) -> void: ...
    @overload
    def natom(self) -> int: ...
    @overload
    def natom(self) -> int: ...
    @overload
    def nbcount(self, v_in: pyrosetta.rosetta.numeric.xyzVector_float_t) -> int: ...
    @overload
    def nbcount(self, constclassnumeric) -> int: ...
    @overload
    def nbcount_raw(self, v: pyrosetta.rosetta.numeric.xyzVector_float_t) -> int: ...
    @overload
    def nbcount_raw(self, constclassnumeric) -> int: ...
    def resi(self, ib: int) -> int: ...
    @overload
    def sanity_check(self) -> bool: ...
    @overload
    def sanity_check(self) -> bool: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    def translation(self) -> pyrosetta.rosetta.numeric.xyzVector_float_t: ...
    def translation_real(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def xdim(self) -> int: ...
    @overload
    def xdim(self) -> int: ...
    def xyz(self, ib: int) -> pyrosetta.rosetta.numeric.xyzVector_float_t: ...
    @overload
    def ydim(self) -> int: ...
    @overload
    def ydim(self) -> int: ...
    @overload
    def zdim(self) -> int: ...
    @overload
    def zdim(self) -> int: ...

class xyzStripeHashWithMeta_double_t:
    @overload
    def __init__(self, grid_size: float) -> None: ...
    @overload
    def __init__(self, grid_size: float, atoms: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t, meta: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, arg0: xyzStripeHashWithMeta_double_t) -> None: ...
    @overload
    def grid_size(self) -> float: ...
    @overload
    def grid_size(self) -> float: ...
    def init(self, atoms: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t, meta: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def natom(self) -> int: ...
    @overload
    def natom(self) -> int: ...
    @overload
    def nbcount(self, v_in: pyrosetta.rosetta.numeric.xyzVector_double_t) -> int: ...
    @overload
    def nbcount(self, constclassnumeric) -> int: ...
    @overload
    def sanity_check(self) -> bool: ...
    @overload
    def sanity_check(self) -> bool: ...
    def translation(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def xdim(self) -> int: ...
    @overload
    def xdim(self) -> int: ...
    @overload
    def ydim(self) -> int: ...
    @overload
    def ydim(self) -> int: ...
    @overload
    def zdim(self) -> int: ...
    @overload
    def zdim(self) -> int: ...

class xyzStripeHashWithMeta_float(xyzStripeHashWithMeta_float_t):
    def __init__(self, arg0: xyzStripeHashWithMeta_float) -> None: ...

class xyzStripeHashWithMeta_float_t:
    @overload
    def __init__(self, grid_size: float) -> None: ...
    @overload
    def __init__(self, grid_size: float, atoms: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_float_t, meta: pyrosetta.rosetta.utility.vector1_float) -> None: ...
    @overload
    def __init__(self, arg0: xyzStripeHashWithMeta_float_t) -> None: ...
    @overload
    def grid_size(self) -> float: ...
    @overload
    def grid_size(self) -> float: ...
    def init(self, atoms: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_float_t, meta: pyrosetta.rosetta.utility.vector1_float) -> None: ...
    @overload
    def natom(self) -> int: ...
    @overload
    def natom(self) -> int: ...
    @overload
    def nbcount(self, v_in: pyrosetta.rosetta.numeric.xyzVector_float_t) -> int: ...
    @overload
    def nbcount(self, constclassnumeric) -> int: ...
    @overload
    def sanity_check(self) -> bool: ...
    @overload
    def sanity_check(self) -> bool: ...
    def translation(self) -> pyrosetta.rosetta.numeric.xyzVector_float_t: ...
    @overload
    def xdim(self) -> int: ...
    @overload
    def xdim(self) -> int: ...
    @overload
    def ydim(self) -> int: ...
    @overload
    def ydim(self) -> int: ...
    @overload
    def zdim(self) -> int: ...
    @overload
    def zdim(self) -> int: ...
