import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.protocols.features
import pyrosetta.rosetta.protocols.loops
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.sql_database
import pyrosetta.rosetta.utility.tag
from . import clusters as clusters, constraints as constraints, design as design, grafting as grafting, residue_selector as residue_selector, snugdock as snugdock, task_operations as task_operations
from _typeshed import Incomplete
from typing import ClassVar, overload

AHO_Scheme: AntibodyNumberingSchemeEnum
AntibodyNumberingSchemeEnum_start: AntibodyNumberingSchemeEnum
AntibodyNumberingSchemeEnum_total: AntibodyNumberingSchemeEnum
AntibodyRegionEnum_start: AntibodyRegionEnum
AntibodyRegionEnum_total: AntibodyRegionEnum
Aroop: CDRDefinitionEnum
CDRDefinitionEnum_start: CDRDefinitionEnum
CDRDefinitionEnum_total: CDRDefinitionEnum
CDRLandmarkEnum_total: CDRLandmarkEnum
CDRNameEnum_proto_start: CDRNameEnum
CDRNameEnum_proto_total: CDRNameEnum
CDRNameEnum_start: CDRNameEnum
CDRNameEnum_total: CDRNameEnum
Chothia: CDRDefinitionEnum
Chothia_Scheme: AntibodyNumberingSchemeEnum
Enhanced_Chothia_Scheme: AntibodyNumberingSchemeEnum
Extended: H3BaseTypeEnum
H1: CDRNameEnum
H2: CDRNameEnum
H3: CDRNameEnum
H3BaseTypeEnum_start: H3BaseTypeEnum
H3BaseTypeEnum_total: H3BaseTypeEnum
H4: CDRNameEnum
H_chain_last_loop: CDRNameEnum
IMGT_Scheme: AntibodyNumberingSchemeEnum
Kabat: CDRDefinitionEnum
Kabat_Scheme: AntibodyNumberingSchemeEnum
Kinked: H3BaseTypeEnum
L1: CDRNameEnum
L2: CDRNameEnum
L3: CDRNameEnum
L4: CDRNameEnum
L_chain_last_loop: CDRNameEnum
LightChainTypeEnum_start: LightChainTypeEnum
LightChainTypeEnum_total: LightChainTypeEnum
Martin: CDRDefinitionEnum
NONE: AntibodyNumberingSchemeEnum
Neutral: H3BaseTypeEnum
North: CDRDefinitionEnum
PackingAngleEnum_start: PackingAngleEnum
PackingAngleEnum_total: PackingAngleEnum
Unknown: H3BaseTypeEnum
VH_sheet_1: PackingAngleEnum
VH_sheet_2: PackingAngleEnum
VL_sheet_1: PackingAngleEnum
VL_sheet_2: PackingAngleEnum
antigen_region: AntibodyRegionEnum
camelid_last_loop: CDRNameEnum
cdr_end: CDRLandmarkEnum
cdr_region: AntibodyRegionEnum
cdr_start: CDRLandmarkEnum
framework_region: AntibodyRegionEnum
h1: CDRNameEnum
h2: CDRNameEnum
h3: CDRNameEnum
h4: CDRNameEnum
kappa: LightChainTypeEnum
l1: CDRNameEnum
l2: CDRNameEnum
l3: CDRNameEnum
l4: CDRNameEnum
lambda6: LightChainTypeEnum
num_cdr_loops: CDRNameEnum
proto_h4: CDRNameEnum
proto_l4: CDRNameEnum
start_cdr_loop: CDRNameEnum
unknown: LightChainTypeEnum
unknown_ab_region: AntibodyRegionEnum

class Ab_TemplateInfo:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, load_L1: bool, load_L2: bool, load_L3: bool, load_H1: bool, load_H2: bool, load_H3: bool) -> None: ...
    @overload
    def __init__(self, load_L1: bool, load_L2: bool, load_L3: bool, load_H1: bool, load_H2: bool, load_H3: bool, camelid: bool) -> None: ...
    @overload
    def __init__(self, arg0: Ab_TemplateInfo) -> None: ...
    def assign(self) -> Ab_TemplateInfo: ...
    def get_one_template_pose(self, cdr_name: str) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    def is_camelid(self) -> bool: ...
    @overload
    def is_camelid(self) -> bool: ...
    def load_templates_from_pdbs(self, load_L1: bool, load_L2: bool, load_L3: bool, load_H1: bool, load_H2: bool, load_H3: bool, camelid: bool) -> None: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class AntibodyCDRGrafter(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ab_info) -> None: ...
    @overload
    def __init__(self, arg0, arg1: pyrosetta.rosetta.core.pose.Pose, arg2: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def __init__(self, arg0, arg1: pyrosetta.rosetta.core.pose.Pose, arg2: pyrosetta.rosetta.utility.vector1_bool, arg3: int) -> None: ...
    @overload
    def __init__(self, ab_info, donor_structure: pyrosetta.rosetta.core.pose.Pose, cdrs_to_graft: pyrosetta.rosetta.utility.vector1_bool, nter_overhang: int, cter_overhang: int) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyCDRGrafter) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyCDRGrafter) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def apply_to_cdr(self, pose: pyrosetta.rosetta.core.pose.Pose, cdr_region_with_overhang: pyrosetta.rosetta.core.pose.Pose, cdr: CDRNameEnum, grafter) -> tuple[bool, int]: ...
    def assign(self) -> AntibodyCDRGrafter: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    def get_primary_graft_mover(self, *args, **kwargs): ...
    def get_secondary_graft_mover(self, *args, **kwargs): ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_cdr_only(self, cdr: CDRNameEnum) -> None: ...
    @overload
    def set_cdr_only(self, enumprotocols) -> void: ...
    @overload
    def set_cdrs(self, cdrs: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def set_cdrs(self, constclassutility) -> void: ...
    @overload
    def set_dihedral_constraint_weight(self, dih_cst_wt: float) -> None: ...
    @overload
    def set_dihedral_constraint_weight(self, double) -> void: ...
    @overload
    def set_donor_structure(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_donor_structure(self, constclasscore) -> void: ...
    @overload
    def set_idealize_insert(self, idealize_insert: bool) -> None: ...
    @overload
    def set_idealize_insert(self, bool) -> void: ...
    @overload
    def set_include_cdr4_in_optimization(self, include_cdr4: bool) -> None: ...
    @overload
    def set_include_cdr4_in_optimization(self, bool) -> void: ...
    @overload
    def set_optimize_cdrs(self, optimize_cdrs: bool) -> None: ...
    @overload
    def set_optimize_cdrs(self, bool) -> void: ...
    def set_overhang(self, nter_overhang: int, cter_overhang: int) -> None: ...
    @overload
    def set_scorefxn_low(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn_low(self, classstd) -> void: ...
    @overload
    def set_scorefxn_pack(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn_pack(self, classstd) -> void: ...
    @overload
    def set_stop_after_closure(self, stop_after_closure: bool) -> None: ...
    @overload
    def set_stop_after_closure(self, bool) -> void: ...
    @overload
    def set_use_secondary_graft_mover_if_needed(self, use_secondary_graft_mover: bool) -> None: ...
    @overload
    def set_use_secondary_graft_mover_if_needed(self, bool) -> void: ...

class AntibodyCDRGrafterCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyCDRGrafterCreator) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyCDRGrafterCreator) -> None: ...
    def assign(self) -> AntibodyCDRGrafterCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class AntibodyDatabaseManager:
    @overload
    def __init__(self, ab_info: AntibodyInfo) -> None: ...
    @overload
    def __init__(self, ab_info: AntibodyInfo, force_north_paper_db: bool) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyDatabaseManager) -> None: ...
    def assign(self) -> AntibodyDatabaseManager: ...
    def clone(self) -> AntibodyDatabaseManager: ...
    @overload
    def ignore_light_chain(self, ignore_light_chain: bool) -> None: ...
    @overload
    def ignore_light_chain(self, constbool) -> void: ...
    def load_cdr_design_data(self, options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t, pose: pyrosetta.rosetta.core.pose.Pose, prob_set: pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t, cutoff: int) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def load_cdr_design_data_for_cdrs(self, cdrs: pyrosetta.rosetta.utility.vector1_bool, pose: pyrosetta.rosetta.core.pose.Pose, prob_set: pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t, cutoff: int) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def load_cdr_pose(self, db_pose: CDRDBPose) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    def load_cdr_poses(self, options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_CDRSetOptions_t, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.map_protocols_antibody_CDRNameEnum_utility_vector1_protocols_antibody_CDRDBPose_t_std_allocator_std_pair_const_protocols_antibody_CDRNameEnum_utility_vector1_protocols_antibody_CDRDBPose_t: ...
    @overload
    def load_cdr_poses(self, options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_CDRSetOptions_t, pose: pyrosetta.rosetta.core.pose.Pose, overhang: int) -> pyrosetta.rosetta.std.map_protocols_antibody_CDRNameEnum_utility_vector1_protocols_antibody_CDRDBPose_t_std_allocator_std_pair_const_protocols_antibody_CDRNameEnum_utility_vector1_protocols_antibody_CDRDBPose_t: ...
    @overload
    def load_cdr_sequences(self, cdrs: pyrosetta.rosetta.utility.vector1_bool, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.map_protocols_antibody_CDRNameEnum_utility_vector1_protocols_antibody_CDRDBSequence_t_std_allocator_std_pair_const_protocols_antibody_CDRNameEnum_utility_vector1_protocols_antibody_CDRDBSequence_t: ...
    @overload
    def load_cdr_sequences(self, cdrs: pyrosetta.rosetta.utility.vector1_bool, pose: pyrosetta.rosetta.core.pose.Pose, match_on_length: bool) -> pyrosetta.rosetta.std.map_protocols_antibody_CDRNameEnum_utility_vector1_protocols_antibody_CDRDBSequence_t_std_allocator_std_pair_const_protocols_antibody_CDRNameEnum_utility_vector1_protocols_antibody_CDRDBSequence_t: ...
    @overload
    def set_outlier_use(self, use_outliers: bool) -> None: ...
    @overload
    def set_outlier_use(self, bool) -> void: ...

class AntibodyEnumManager:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyEnumManager) -> None: ...
    @overload
    def all_cdrs(self) -> pyrosetta.rosetta.utility.vector1_protocols_antibody_CDRNameEnum: ...
    @overload
    def all_cdrs(self, include_proto_cdr4: bool) -> pyrosetta.rosetta.utility.vector1_protocols_antibody_CDRNameEnum: ...
    def antibody_region_enum_to_string(self, antibody_region: AntibodyRegionEnum) -> str: ...
    def antibody_region_string_to_enum(self, antibody_region: str) -> AntibodyRegionEnum: ...
    def assign(self) -> AntibodyEnumManager: ...
    def cdr_definition_enum_to_string(self, cdr_definition: CDRDefinitionEnum) -> str: ...
    @overload
    def cdr_definition_is_present(self, cdr_definition: str) -> bool: ...
    @overload
    def cdr_definition_is_present(self, conststd) -> bool: ...
    def cdr_definition_string_to_enum(self, cdr_definition: str) -> CDRDefinitionEnum: ...
    def cdr_landmark_enum_to_string(self, landmark: CDRLandmarkEnum) -> str: ...
    @overload
    def cdr_landmark_is_present(self, landmark: str) -> bool: ...
    @overload
    def cdr_landmark_is_present(self, conststd) -> bool: ...
    def cdr_landmark_string_to_enum(self, landmark: str) -> CDRLandmarkEnum: ...
    def cdr_name_enum_to_string(self, cdr_name: CDRNameEnum) -> str: ...
    @overload
    def cdr_name_is_present(self, cdr_name: str) -> bool: ...
    @overload
    def cdr_name_is_present(self, conststd) -> bool: ...
    def cdr_name_string_to_enum(self, cdr_name: str) -> CDRNameEnum: ...
    def get_recognized_cdr_definitions(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    def get_recognized_numbering_schemes(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    def h3_base_type_enum_to_string(self, base_type: H3BaseTypeEnum) -> str: ...
    def h3_base_type_string_to_enum(self, base_type: str) -> H3BaseTypeEnum: ...
    def light_chain_type_enum_to_string(self, light_chain: LightChainTypeEnum) -> str: ...
    @overload
    def light_chain_type_is_present(self, light_chain: str) -> bool: ...
    @overload
    def light_chain_type_is_present(self, conststd) -> bool: ...
    def light_chain_type_string_to_enum(self, light_chain: str) -> LightChainTypeEnum: ...
    def numbering_scheme_enum_to_string(self, numbering_scheme: AntibodyNumberingSchemeEnum) -> str: ...
    @overload
    def numbering_scheme_is_present(self, numbering_scheme: str) -> bool: ...
    @overload
    def numbering_scheme_is_present(self, conststd) -> bool: ...
    def numbering_scheme_string_to_enum(self, numbering_scheme: str) -> AntibodyNumberingSchemeEnum: ...
    def packing_angle_enum_to_string(self, angle_type: PackingAngleEnum) -> str: ...
    def packing_angle_string_to_enum(self, angle_type: str) -> PackingAngleEnum: ...

class AntibodyFeatures(pyrosetta.rosetta.protocols.features.InterfaceFeatures):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ab_info) -> None: ...
    @overload
    def __init__(self, ab_info, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyFeatures) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyFeatures) -> None: ...
    def assign(self) -> AntibodyFeatures: ...
    @staticmethod
    def class_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def report_ab_H3_kink_metrics_features(self, pose: pyrosetta.rosetta.core.pose.Pose, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> None: ...
    @overload
    def report_ab_H3_kink_metrics_features(self, constclasscore, unsignedlonglong, classstd) -> void: ...
    @overload
    def report_ab_metrics_features(self, pose: pyrosetta.rosetta.core.pose.Pose, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> None: ...
    @overload
    def report_ab_metrics_features(self, constclasscore, unsignedlonglong, classstd) -> void: ...
    @overload
    def report_cdr_metrics_features(self, pose: pyrosetta.rosetta.core.pose.Pose, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, cdr: CDRNameEnum) -> None: ...
    @overload
    def report_cdr_metrics_features(self, constclasscore, unsignedlonglong, classstd, constenumprotocols) -> void: ...
    @overload
    def report_cdr_residue_features(self, pose: pyrosetta.rosetta.core.pose.Pose, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, cdr: CDRNameEnum, relevant_residues: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def report_cdr_residue_features(self, constclasscore, unsignedlonglong, classstd, constenumprotocols, constclassutility) -> void: ...
    def report_cdr_residue_features_row(self, pose: pyrosetta.rosetta.core.pose.Pose, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, cdr: CDRNameEnum, resnum: int, position: int) -> None: ...
    @overload
    def report_features(self, pose: pyrosetta.rosetta.core.pose.Pose, relevant_residues: pyrosetta.rosetta.utility.vector1_bool, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> int: ...
    @overload
    def report_features(self, constclasscore, constclassutility, unsignedlonglong, classstd) -> unsignedlong: ...
    @overload
    def set_ab_info(self, ab_info) -> None: ...
    @overload
    def set_ab_info(self, classstd) -> void: ...
    @overload
    def set_interface_chains(self, intermediate_interfaces: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_interface_chains(self, constclassutility) -> void: ...
    def type_name(self) -> str: ...
    @overload
    def write_ab_H3_kink_metrics_schema_to_db(self, db_session: pyrosetta.rosetta.utility.sql_database.session) -> None: ...
    @overload
    def write_ab_H3_kink_metrics_schema_to_db(self, classstd) -> void: ...
    @overload
    def write_ab_metrics_schema_to_db(self, db_session: pyrosetta.rosetta.utility.sql_database.session) -> None: ...
    @overload
    def write_ab_metrics_schema_to_db(self, classstd) -> void: ...
    @overload
    def write_cdr_metrics_schema_to_db(self, db_session: pyrosetta.rosetta.utility.sql_database.session) -> None: ...
    @overload
    def write_cdr_metrics_schema_to_db(self, classstd) -> void: ...
    @overload
    def write_cdr_residue_schema_to_db(self, db_session: pyrosetta.rosetta.utility.sql_database.session) -> None: ...
    @overload
    def write_cdr_residue_schema_to_db(self, classstd) -> void: ...
    @overload
    def write_schema_to_db(self, db_session: pyrosetta.rosetta.utility.sql_database.session) -> None: ...
    @overload
    def write_schema_to_db(self, classstd) -> void: ...

class AntibodyFeaturesCreator(pyrosetta.rosetta.protocols.features.FeaturesReporterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyFeaturesCreator) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyFeaturesCreator) -> None: ...
    def assign(self) -> AntibodyFeaturesCreator: ...
    def create_features_reporter(self) -> pyrosetta.rosetta.protocols.features.FeaturesReporter: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
    def type_name(self) -> str: ...

class AntibodyInfo:
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, cdr_pdb_numbered: bool) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, numbering_scheme: AntibodyNumberingSchemeEnum, cdr_definition: CDRDefinitionEnum) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, numbering_scheme: AntibodyNumberingSchemeEnum, cdr_definition: CDRDefinitionEnum, cdr_pdb_numbered: bool) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, cdr_definition: CDRDefinitionEnum) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, cdr_definition: CDRDefinitionEnum, cdr_pdb_numbered: bool) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyInfo) -> None: ...
    @overload
    def add_CDR_to_MoveMap(self, pose: pyrosetta.rosetta.core.pose.Pose, movemap: pyrosetta.rosetta.core.kinematics.MoveMap, cdr_name: CDRNameEnum) -> None: ...
    @overload
    def add_CDR_to_MoveMap(self, pose: pyrosetta.rosetta.core.pose.Pose, movemap: pyrosetta.rosetta.core.kinematics.MoveMap, cdr_name: CDRNameEnum, bb_only: bool) -> None: ...
    @overload
    def add_CDR_to_MoveMap(self, pose: pyrosetta.rosetta.core.pose.Pose, movemap: pyrosetta.rosetta.core.kinematics.MoveMap, cdr_name: CDRNameEnum, bb_only: bool, include_nb_sc: bool) -> None: ...
    @overload
    def add_CDR_to_MoveMap(self, pose: pyrosetta.rosetta.core.pose.Pose, movemap: pyrosetta.rosetta.core.kinematics.MoveMap, cdr_name: CDRNameEnum, bb_only: bool, include_nb_sc: bool, nb_dist: float) -> None: ...
    @overload
    def antigen_present(self) -> bool: ...
    @overload
    def antigen_present(self) -> bool: ...
    def assign(self) -> AntibodyInfo: ...
    def clone(self) -> AntibodyInfo: ...
    def get_AllCDRs_in_loopsop(self) -> pyrosetta.rosetta.protocols.loops.Loops: ...
    def get_AntibodyFrameworkInfo(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_antibody_FrameWork_t: ...
    @overload
    def get_CDRNameEnum_of_residue(self, pose: pyrosetta.rosetta.core.pose.Pose, resnum: int) -> CDRNameEnum: ...
    @overload
    def get_CDRNameEnum_of_residue(self, pose: pyrosetta.rosetta.core.pose.Pose, resnum: int, de_as_framework: bool) -> CDRNameEnum: ...
    @overload
    def get_CDR_chain(self, cdr_name: CDRNameEnum) -> str: ...
    @overload
    def get_CDR_chain(self, constenumprotocols) -> char: ...
    def get_CDR_cluster(self, *args, **kwargs): ...
    def get_CDR_cluster_set(self, *args, **kwargs): ...
    @overload
    def get_CDR_end(self, cdr_name: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def get_CDR_end(self, constenumprotocols, constclasscore) -> unsignedlong: ...
    @overload
    def get_CDR_end(self, cdr_name: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose, transform: CDRDefinitionEnum) -> int: ...
    @overload
    def get_CDR_end_PDB_num(self, cdr_name: CDRNameEnum) -> int: ...
    @overload
    def get_CDR_end_PDB_num(self, constenumprotocols) -> unsignedlong: ...
    def get_CDR_in_loopsop(self, cdr_name: CDRNameEnum) -> pyrosetta.rosetta.protocols.loops.Loops: ...
    @overload
    def get_CDR_length(self, cdr_name: CDRNameEnum) -> int: ...
    @overload
    def get_CDR_length(self, constenumprotocols) -> unsignedlong: ...
    @overload
    def get_CDR_length(self, cdr_name: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def get_CDR_length(self, constenumprotocols, constclasscore) -> unsignedlong: ...
    @overload
    def get_CDR_length(self, cdr_name: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose, transform: CDRDefinitionEnum) -> int: ...
    @overload
    def get_CDR_loop(self, cdr_name: CDRNameEnum) -> pyrosetta.rosetta.protocols.loops.Loop: ...
    @overload
    def get_CDR_loop(self, cdr_name: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.protocols.loops.Loop: ...
    @overload
    def get_CDR_loop(self, cdr_name: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose, overhang: int) -> pyrosetta.rosetta.protocols.loops.Loop: ...
    @overload
    def get_CDR_loop(self, cdr_name: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose, transform: CDRDefinitionEnum) -> pyrosetta.rosetta.protocols.loops.Loop: ...
    @overload
    def get_CDR_loop(self, cdr_name: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose, transform: CDRDefinitionEnum, overhang: int) -> pyrosetta.rosetta.protocols.loops.Loop: ...
    @overload
    def get_CDR_loops(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.protocols.loops.Loops: ...
    @overload
    def get_CDR_loops(self, pose: pyrosetta.rosetta.core.pose.Pose, overhang: int) -> pyrosetta.rosetta.protocols.loops.Loops: ...
    @overload
    def get_CDR_loops(self, pose: pyrosetta.rosetta.core.pose.Pose, cdrs: pyrosetta.rosetta.utility.vector1_bool) -> pyrosetta.rosetta.protocols.loops.Loops: ...
    @overload
    def get_CDR_loops(self, pose: pyrosetta.rosetta.core.pose.Pose, cdrs: pyrosetta.rosetta.utility.vector1_bool, overhang: int) -> pyrosetta.rosetta.protocols.loops.Loops: ...
    def get_CDR_name(self, cdr_name: CDRNameEnum) -> str: ...
    def get_CDR_name_enum(self, cdr_name: str) -> CDRNameEnum: ...
    @overload
    def get_CDR_sequence_with_stem(self, cdr_name: CDRNameEnum) -> str: ...
    @overload
    def get_CDR_sequence_with_stem(self, cdr_name: CDRNameEnum, left_stem: int) -> str: ...
    @overload
    def get_CDR_sequence_with_stem(self, cdr_name: CDRNameEnum, left_stem: int, right_stem: int) -> str: ...
    @overload
    def get_CDR_sequence_with_stem(self, cdr_name: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose) -> str: ...
    @overload
    def get_CDR_sequence_with_stem(self, cdr_name: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose, left_stem: int) -> str: ...
    @overload
    def get_CDR_sequence_with_stem(self, cdr_name: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose, left_stem: int, right_stem: int) -> str: ...
    @overload
    def get_CDR_sequence_with_stem(self, cdr_name: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose, left_stem: int, right_stem: int, transform: CDRDefinitionEnum) -> str: ...
    @overload
    def get_CDR_start(self, cdr_name: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def get_CDR_start(self, constenumprotocols, constclasscore) -> unsignedlong: ...
    @overload
    def get_CDR_start(self, cdr_name: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose, transform: CDRDefinitionEnum) -> int: ...
    @overload
    def get_CDR_start_PDB_num(self, cdr_name: CDRNameEnum) -> int: ...
    @overload
    def get_CDR_start_PDB_num(self, constenumprotocols) -> unsignedlong: ...
    def get_FoldTree_AllCDRs(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    def get_FoldTree_AllCDRs_LHDock(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    def get_FoldTree_LA_H(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    def get_FoldTree_LH_A(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    def get_FoldTree_L_HA(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    def get_H3_kink_type(self) -> H3BaseTypeEnum: ...
    def get_H3_kink_type_name(self) -> str: ...
    @overload
    def get_MoveMap_for_AllCDRsSideChains_and_H3backbone(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_MoveMap_for_AllCDRsSideChains_and_H3backbone(self, pose: pyrosetta.rosetta.core.pose.Pose, include_nb_sc: bool) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_MoveMap_for_AllCDRsSideChains_and_H3backbone(self, pose: pyrosetta.rosetta.core.pose.Pose, include_nb_sc: bool, nb_dist: float) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_MoveMap_for_Loops(self, pose: pyrosetta.rosetta.core.pose.Pose, the_loops: pyrosetta.rosetta.protocols.loops.Loops) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_MoveMap_for_Loops(self, pose: pyrosetta.rosetta.core.pose.Pose, the_loops: pyrosetta.rosetta.protocols.loops.Loops, bb_only: bool) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_MoveMap_for_Loops(self, pose: pyrosetta.rosetta.core.pose.Pose, the_loops: pyrosetta.rosetta.protocols.loops.Loops, bb_only: bool, include_nb_sc: bool) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_MoveMap_for_Loops(self, pose: pyrosetta.rosetta.core.pose.Pose, the_loops: pyrosetta.rosetta.protocols.loops.Loops, bb_only: bool, include_nb_sc: bool, nb_dist: float) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_MoveMap_for_LoopsandDock(self, pose: pyrosetta.rosetta.core.pose.Pose, the_loops: pyrosetta.rosetta.protocols.loops.Loops) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_MoveMap_for_LoopsandDock(self, pose: pyrosetta.rosetta.core.pose.Pose, the_loops: pyrosetta.rosetta.protocols.loops.Loops, bb_only: bool) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_MoveMap_for_LoopsandDock(self, pose: pyrosetta.rosetta.core.pose.Pose, the_loops: pyrosetta.rosetta.protocols.loops.Loops, bb_only: bool, include_nb_sc: bool) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_MoveMap_for_LoopsandDock(self, pose: pyrosetta.rosetta.core.pose.Pose, the_loops: pyrosetta.rosetta.protocols.loops.Loops, bb_only: bool, include_nb_sc: bool, nb_dist: float) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    def get_PackingAngleResidues(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def get_TaskFactory_AllCDRs(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    def get_TaskFactory_OneCDR(self, pose: pyrosetta.rosetta.core.pose.Pose, cdr_name: CDRNameEnum) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    @overload
    def get_all_cdrs(self) -> pyrosetta.rosetta.utility.vector1_protocols_antibody_CDRNameEnum: ...
    @overload
    def get_all_cdrs(self, include_proto_cdr4: bool) -> pyrosetta.rosetta.utility.vector1_protocols_antibody_CDRNameEnum: ...
    @overload
    def get_all_cdrs_present(self) -> pyrosetta.rosetta.utility.vector1_protocols_antibody_CDRNameEnum: ...
    @overload
    def get_all_cdrs_present(self, include_proto_cdr4: bool) -> pyrosetta.rosetta.utility.vector1_protocols_antibody_CDRNameEnum: ...
    def get_antibody_chain_ids(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def get_antibody_chain_string(self) -> str: ...
    def get_antibody_chains(self) -> pyrosetta.rosetta.utility.vector1_char: ...
    def get_antibody_enum_manager(self) -> AntibodyEnumManager: ...
    def get_antibody_numbering_info(self) -> AntibodyNumbering: ...
    def get_antibody_sequence(self) -> str: ...
    def get_antigen_chain_ids(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def get_antigen_chain_string(self) -> str: ...
    def get_antigen_chains(self) -> pyrosetta.rosetta.utility.vector1_char: ...
    def get_cdr_cluster_enum_manager(self, *args, **kwargs): ...
    def get_cdr_enum_for_cluster(self, cluster: clusters.CDRClusterEnum) -> CDRNameEnum: ...
    def get_cluster_enum(self, cluster: str) -> clusters.CDRClusterEnum: ...
    @overload
    def get_cluster_length(self, cluster: clusters.CDRClusterEnum) -> int: ...
    @overload
    def get_cluster_length(self, constenumprotocols) -> unsignedlong: ...
    def get_cluster_name(self, cluster: clusters.CDRClusterEnum) -> str: ...
    def get_current_AntibodyNumberingScheme(self) -> str: ...
    def get_current_CDRDefinition(self) -> str: ...
    @overload
    def get_landmark_resnum(self, pose: pyrosetta.rosetta.core.pose.Pose, scheme: AntibodyNumberingSchemeEnum, chain: str, pdb_resnum: int) -> int: ...
    @overload
    def get_landmark_resnum(self, pose: pyrosetta.rosetta.core.pose.Pose, scheme: AntibodyNumberingSchemeEnum, chain: str, pdb_resnum: int, insertion_code: str) -> int: ...
    @overload
    def get_landmark_resnum(self, pose: pyrosetta.rosetta.core.pose.Pose, scheme: AntibodyNumberingSchemeEnum, chain: str, pdb_resnum: int, insertion_code: str, fail_on_missing_resnum: bool) -> int: ...
    def get_light_chain_type(self) -> str: ...
    def get_light_chain_type_enum(self) -> LightChainTypeEnum: ...
    @overload
    def get_region_of_residue(self, pose: pyrosetta.rosetta.core.pose.Pose, resnum: int) -> AntibodyRegionEnum: ...
    @overload
    def get_region_of_residue(self, pose: pyrosetta.rosetta.core.pose.Pose, resnum: int, de_as_framework: bool) -> AntibodyRegionEnum: ...
    @overload
    def get_total_num_CDRs(self) -> int: ...
    @overload
    def get_total_num_CDRs(self, include_proto_cdr4: bool) -> int: ...
    @overload
    def get_total_num_CDRs(self, bool) -> unsignedlong: ...
    @overload
    def has_CDR(self, cdr_name: CDRNameEnum) -> bool: ...
    @overload
    def has_CDR(self, constenumprotocols) -> bool: ...
    @overload
    def has_cluster_for_cdr(self, cdr_name: CDRNameEnum) -> bool: ...
    @overload
    def has_cluster_for_cdr(self, constenumprotocols) -> bool: ...
    @overload
    def is_camelid(self) -> bool: ...
    @overload
    def is_camelid(self) -> bool: ...
    def kink_anion_atoms(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.vector_numeric_xyzVector_double_t: ...
    @overload
    def kink_anion_residue(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def kink_anion_residue(self, constclasscore) -> unsignedlong: ...
    @overload
    def kink_begin(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def kink_begin(self, constclasscore) -> unsignedlong: ...
    def kink_cation_atoms(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.vector_numeric_xyzVector_double_t: ...
    @overload
    def kink_cation_residue(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def kink_cation_residue(self, constclasscore) -> unsignedlong: ...
    @overload
    def kink_end(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def kink_end(self, constclasscore) -> unsignedlong: ...
    @overload
    def kink_trp(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def kink_trp(self, constclasscore) -> unsignedlong: ...
    @overload
    def qq_heavy_residue(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def qq_heavy_residue(self, constclasscore) -> unsignedlong: ...
    @overload
    def qq_light_residue(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def qq_light_residue(self, constclasscore) -> unsignedlong: ...
    @overload
    def set_CDR_cluster(self, cdr: CDRNameEnum, cluster) -> None: ...
    @overload
    def set_CDR_cluster(self, enumprotocols, classstd) -> void: ...
    @overload
    def set_light_chain_type(self, light_chain: LightChainTypeEnum) -> None: ...
    @overload
    def set_light_chain_type(self, enumprotocols) -> void: ...
    @overload
    def setup_CDR_cluster(self, pose: pyrosetta.rosetta.core.pose.Pose, cdr: CDRNameEnum) -> None: ...
    @overload
    def setup_CDR_cluster(self, pose: pyrosetta.rosetta.core.pose.Pose, cdr: CDRNameEnum, attempt_set_from_pose: bool) -> None: ...
    @overload
    def setup_CDR_cluster(self, constclasscore, enumprotocols, bool) -> void: ...
    @overload
    def setup_CDR_clusters(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def setup_CDR_clusters(self, pose: pyrosetta.rosetta.core.pose.Pose, attempt_set_from_pose: bool) -> None: ...
    @overload
    def setup_CDR_clusters(self, constclasscore, bool) -> void: ...
    @overload
    def setup_CDR_clusters(self, pose: pyrosetta.rosetta.core.pose.Pose, cdrs: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def setup_CDR_clusters(self, pose: pyrosetta.rosetta.core.pose.Pose, cdrs: pyrosetta.rosetta.utility.vector1_bool, attempt_set_from_pose: bool) -> None: ...
    @overload
    def setup_CDR_clusters(self, constclasscore, constclassutility, bool) -> void: ...
    def setup_simple_fold_tree(self, jumppoint1: int, cutpoint: int, jumppoint2: int, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class AntibodyModelerProtocol(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyModelerProtocol) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyModelerProtocol) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> AntibodyModelerProtocol: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def display_constraint_residues(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def display_constraint_residues(self, classcore) -> void: ...
    def get_name(self) -> str: ...
    @overload
    @staticmethod
    def register_options() -> None: ...
    @overload
    @staticmethod
    def register_options() -> void: ...
    @overload
    def set_BenchMark(self, setting: bool) -> None: ...
    @overload
    def set_BenchMark(self, bool) -> void: ...
    @overload
    def set_ModelH3(self, setting: bool) -> None: ...
    @overload
    def set_ModelH3(self, bool) -> void: ...
    @overload
    def set_SnugFit(self, setting: bool) -> None: ...
    @overload
    def set_SnugFit(self, bool) -> void: ...
    @overload
    def set_auto_h3_constraint(self, setting: bool) -> None: ...
    @overload
    def set_auto_h3_constraint(self, constbool) -> void: ...
    @overload
    def set_constrain_vlvh_qq(self, setting: bool) -> None: ...
    @overload
    def set_constrain_vlvh_qq(self, constbool) -> void: ...
    @overload
    def set_cst_weight(self, cst_weight: float) -> None: ...
    @overload
    def set_cst_weight(self, constdouble) -> void: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_extend_h3_before_modeling(self, setting: bool) -> None: ...
    @overload
    def set_extend_h3_before_modeling(self, bool) -> void: ...
    @overload
    def set_h3_loop_csts_hr(self, setting: bool) -> None: ...
    @overload
    def set_h3_loop_csts_hr(self, constbool) -> void: ...
    @overload
    def set_h3_loop_csts_lr(self, setting: bool) -> None: ...
    @overload
    def set_h3_loop_csts_lr(self, constbool) -> void: ...
    @overload
    def set_middle_pack_min(self, middle_pack_min: bool) -> None: ...
    @overload
    def set_middle_pack_min(self, bool) -> void: ...
    @overload
    def set_packonly_after_graft(self, setting: bool) -> None: ...
    @overload
    def set_packonly_after_graft(self, bool) -> void: ...
    @overload
    def set_refine_h3(self, setting: bool) -> None: ...
    @overload
    def set_refine_h3(self, bool) -> void: ...
    @overload
    def set_rt_min(self, setting: bool) -> None: ...
    @overload
    def set_rt_min(self, bool) -> void: ...
    @overload
    def set_sc_min(self, setting: bool) -> None: ...
    @overload
    def set_sc_min(self, bool) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def sync_objects_with_flags(self) -> None: ...
    @overload
    def sync_objects_with_flags(self) -> void: ...

class AntibodyNumbering:
    cdr_definition: CDRDefinitionEnum
    cdr_definition_transform: Incomplete
    cdr_numbering: pyrosetta.rosetta.utility.vector1_utility_vector1_std_shared_ptr_protocols_antibody_PDBLandmark_t
    numbering_scheme: AntibodyNumberingSchemeEnum
    numbering_scheme_transform: Incomplete
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyNumbering) -> None: ...
    def assign(self) -> AntibodyNumbering: ...

class AntibodyNumberingConverterMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, _from: AntibodyNumberingSchemeEnum, to: AntibodyNumberingSchemeEnum) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> AntibodyNumberingConverterMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_from_scheme(self, _from: AntibodyNumberingSchemeEnum) -> None: ...
    @overload
    def set_from_scheme(self, constenumprotocols) -> void: ...
    def set_scheme_conversion(self, _from: AntibodyNumberingSchemeEnum, to: AntibodyNumberingSchemeEnum) -> None: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class AntibodyNumberingConverterMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyNumberingConverterMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyNumberingConverterMoverCreator) -> None: ...
    def assign(self) -> AntibodyNumberingConverterMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class AntibodyNumberingParser:
    @overload
    def __init__(self, enum_manager: AntibodyEnumManager) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyNumberingParser) -> None: ...
    def assign(self) -> AntibodyNumberingParser: ...
    def get_antibody_numbering(self, numbering_scheme: AntibodyNumberingSchemeEnum, cdr_definition: CDRDefinitionEnum) -> AntibodyNumbering: ...

class AntibodyNumberingSchemeEnum:
    __members__: ClassVar[dict] = ...  # read-only
    AHO_Scheme: ClassVar[AntibodyNumberingSchemeEnum] = ...
    AntibodyNumberingSchemeEnum_start: ClassVar[AntibodyNumberingSchemeEnum] = ...
    AntibodyNumberingSchemeEnum_total: ClassVar[AntibodyNumberingSchemeEnum] = ...
    Chothia_Scheme: ClassVar[AntibodyNumberingSchemeEnum] = ...
    Enhanced_Chothia_Scheme: ClassVar[AntibodyNumberingSchemeEnum] = ...
    IMGT_Scheme: ClassVar[AntibodyNumberingSchemeEnum] = ...
    Kabat_Scheme: ClassVar[AntibodyNumberingSchemeEnum] = ...
    NONE: ClassVar[AntibodyNumberingSchemeEnum] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class AntibodyRegionEnum:
    __members__: ClassVar[dict] = ...  # read-only
    AntibodyRegionEnum_start: ClassVar[AntibodyRegionEnum] = ...
    AntibodyRegionEnum_total: ClassVar[AntibodyRegionEnum] = ...
    __entries: ClassVar[dict] = ...
    antigen_region: ClassVar[AntibodyRegionEnum] = ...
    cdr_region: ClassVar[AntibodyRegionEnum] = ...
    framework_region: ClassVar[AntibodyRegionEnum] = ...
    unknown_ab_region: ClassVar[AntibodyRegionEnum] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class CDRDBPose:
    cluster: clusters.CDRClusterEnum
    distance: float
    normalized_distance: float
    pdb: str
    pose: pyrosetta.rosetta.core.pose.Pose
    resolution: float
    struct_id: int
    structure_length: int
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, cluster: clusters.CDRClusterEnum, pdb: str, distance: float, normalized_distance: float, resolution: float, structure_length: int) -> None: ...
    @overload
    def __init__(self, struct_id: int, cluster: clusters.CDRClusterEnum, pdb: str, distance: float, normalized_distance: float, resolution: float, structure_length: int) -> None: ...
    @overload
    def __init__(self, arg0: CDRDBPose) -> None: ...
    def assign(self) -> CDRDBPose: ...

class CDRDBSequence:
    cluster: clusters.CDRClusterEnum
    distance: float
    normalized_distance: float
    pdb: str
    resolution: float
    sequence: str
    @overload
    def __init__(self, sequence: str, cluster: clusters.CDRClusterEnum, pdb: str, distance: float, normalized_distance: float, resolution: float) -> None: ...
    @overload
    def __init__(self, arg0: CDRDBSequence) -> None: ...
    def assign(self) -> CDRDBSequence: ...

class CDRDefinitionEnum:
    __members__: ClassVar[dict] = ...  # read-only
    Aroop: ClassVar[CDRDefinitionEnum] = ...
    CDRDefinitionEnum_start: ClassVar[CDRDefinitionEnum] = ...
    CDRDefinitionEnum_total: ClassVar[CDRDefinitionEnum] = ...
    Chothia: ClassVar[CDRDefinitionEnum] = ...
    Kabat: ClassVar[CDRDefinitionEnum] = ...
    Martin: ClassVar[CDRDefinitionEnum] = ...
    North: ClassVar[CDRDefinitionEnum] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class CDRLandmarkEnum:
    __members__: ClassVar[dict] = ...  # read-only
    CDRLandmarkEnum_total: ClassVar[CDRLandmarkEnum] = ...
    __entries: ClassVar[dict] = ...
    cdr_end: ClassVar[CDRLandmarkEnum] = ...
    cdr_start: ClassVar[CDRLandmarkEnum] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class CDRNameEnum:
    __members__: ClassVar[dict] = ...  # read-only
    CDRNameEnum_proto_start: ClassVar[CDRNameEnum] = ...
    CDRNameEnum_proto_total: ClassVar[CDRNameEnum] = ...
    CDRNameEnum_start: ClassVar[CDRNameEnum] = ...
    CDRNameEnum_total: ClassVar[CDRNameEnum] = ...
    H1: ClassVar[CDRNameEnum] = ...
    H2: ClassVar[CDRNameEnum] = ...
    H3: ClassVar[CDRNameEnum] = ...
    H4: ClassVar[CDRNameEnum] = ...
    H_chain_last_loop: ClassVar[CDRNameEnum] = ...
    L1: ClassVar[CDRNameEnum] = ...
    L2: ClassVar[CDRNameEnum] = ...
    L3: ClassVar[CDRNameEnum] = ...
    L4: ClassVar[CDRNameEnum] = ...
    L_chain_last_loop: ClassVar[CDRNameEnum] = ...
    __entries: ClassVar[dict] = ...
    camelid_last_loop: ClassVar[CDRNameEnum] = ...
    h1: ClassVar[CDRNameEnum] = ...
    h2: ClassVar[CDRNameEnum] = ...
    h3: ClassVar[CDRNameEnum] = ...
    h4: ClassVar[CDRNameEnum] = ...
    l1: ClassVar[CDRNameEnum] = ...
    l2: ClassVar[CDRNameEnum] = ...
    l3: ClassVar[CDRNameEnum] = ...
    l4: ClassVar[CDRNameEnum] = ...
    num_cdr_loops: ClassVar[CDRNameEnum] = ...
    proto_h4: ClassVar[CDRNameEnum] = ...
    proto_l4: ClassVar[CDRNameEnum] = ...
    start_cdr_loop: ClassVar[CDRNameEnum] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class CDRSetOptions:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, load: bool) -> None: ...
    @overload
    def __init__(self, cdr: CDRNameEnum) -> None: ...
    @overload
    def __init__(self, cdr: CDRNameEnum, load: bool) -> None: ...
    @overload
    def __init__(self, arg0: CDRSetOptions) -> None: ...
    def assign(self) -> CDRSetOptions: ...
    def cdr(self) -> CDRNameEnum: ...
    def clone(self) -> CDRSetOptions: ...
    @overload
    def cluster_sampling_cutoff(self, cutoff: int) -> None: ...
    @overload
    def cluster_sampling_cutoff(self, unsignedlong) -> void: ...
    @overload
    def cluster_sampling_cutoff(self) -> int: ...
    @overload
    def cluster_sampling_cutoff(self) -> unsignedlong: ...
    @overload
    def exclude_clusters(self, exclude: pyrosetta.rosetta.utility.vector1_protocols_antibody_clusters_CDRClusterEnum) -> None: ...
    @overload
    def exclude_clusters(self, classutility) -> void: ...
    @overload
    def exclude_clusters(self) -> pyrosetta.rosetta.utility.vector1_protocols_antibody_clusters_CDRClusterEnum: ...
    @overload
    def exclude_clusters_add(self, exclude: clusters.CDRClusterEnum) -> None: ...
    @overload
    def exclude_clusters_add(self, enumprotocols) -> void: ...
    @overload
    def exclude_clusters_clear(self) -> None: ...
    @overload
    def exclude_clusters_clear(self) -> void: ...
    @overload
    def exclude_germlines(self, exclude: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def exclude_germlines(self, classutility) -> void: ...
    @overload
    def exclude_germlines(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def exclude_germlines_add(self, exclude: str) -> None: ...
    @overload
    def exclude_germlines_add(self, std) -> void: ...
    @overload
    def exclude_germlines_clear(self) -> None: ...
    @overload
    def exclude_germlines_clear(self) -> void: ...
    @overload
    def exclude_pdbs(self, exclude_pdbids: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def exclude_pdbs(self, classutility) -> void: ...
    @overload
    def exclude_pdbs(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def exclude_pdbs_add(self, pdbid: str) -> None: ...
    @overload
    def exclude_pdbs_add(self, std) -> void: ...
    @overload
    def exclude_pdbs_clear(self) -> None: ...
    @overload
    def exclude_pdbs_clear(self) -> void: ...
    @overload
    def exclude_species(self, exclude: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def exclude_species(self, classutility) -> void: ...
    @overload
    def exclude_species(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def exclude_species_add(self, exclude: str) -> None: ...
    @overload
    def exclude_species_add(self, std) -> void: ...
    @overload
    def exclude_species_clear(self) -> None: ...
    @overload
    def exclude_species_clear(self) -> void: ...
    @overload
    def include_only_center_clusters(self, centers_only: bool) -> None: ...
    @overload
    def include_only_center_clusters(self, bool) -> void: ...
    @overload
    def include_only_center_clusters(self) -> bool: ...
    @overload
    def include_only_center_clusters(self) -> bool: ...
    @overload
    def include_only_clusters(self, include_only: pyrosetta.rosetta.utility.vector1_protocols_antibody_clusters_CDRClusterEnum) -> None: ...
    @overload
    def include_only_clusters(self, classutility) -> void: ...
    @overload
    def include_only_clusters(self) -> pyrosetta.rosetta.utility.vector1_protocols_antibody_clusters_CDRClusterEnum: ...
    @overload
    def include_only_clusters_add(self, include_only: clusters.CDRClusterEnum) -> None: ...
    @overload
    def include_only_clusters_add(self, enumprotocols) -> void: ...
    @overload
    def include_only_clusters_clear(self) -> None: ...
    @overload
    def include_only_clusters_clear(self) -> void: ...
    def include_only_current_cluster(self, *args, **kwargs): ...
    @overload
    def include_only_germlines(self, include_only: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def include_only_germlines(self, classutility) -> void: ...
    @overload
    def include_only_germlines(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def include_only_germlines_add(self, include_only: str) -> None: ...
    @overload
    def include_only_germlines_add(self, std) -> void: ...
    @overload
    def include_only_germlines_clear(self) -> None: ...
    @overload
    def include_only_germlines_clear(self) -> void: ...
    @overload
    def include_only_pdbs(self, include_pdbids: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def include_only_pdbs(self, classutility) -> void: ...
    @overload
    def include_only_pdbs(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def include_only_pdbs_add(self, pdbid: str) -> None: ...
    @overload
    def include_only_pdbs_add(self, std) -> void: ...
    @overload
    def include_only_pdbs_clear(self) -> None: ...
    @overload
    def include_only_pdbs_clear(self) -> void: ...
    @overload
    def include_only_species(self, include_only: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def include_only_species(self, classutility) -> void: ...
    @overload
    def include_only_species(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def include_only_species_add(self, include_only: str) -> None: ...
    @overload
    def include_only_species_add(self, std) -> void: ...
    @overload
    def include_only_species_clear(self) -> None: ...
    @overload
    def include_only_species_clear(self) -> void: ...
    @overload
    def length_type(self, type: int, setting: bool) -> None: ...
    @overload
    def length_type(self, constunsignedlong, constbool) -> void: ...
    @overload
    def length_type(self) -> pyrosetta.rosetta.utility.vector1_bool: ...
    @overload
    def load(self, load: bool) -> None: ...
    @overload
    def load(self, bool) -> void: ...
    @overload
    def load(self) -> bool: ...
    @overload
    def load(self) -> bool: ...
    @overload
    def max_length(self, length: int) -> None: ...
    @overload
    def max_length(self, unsignedlong) -> void: ...
    @overload
    def max_length(self) -> int: ...
    @overload
    def max_length(self) -> unsignedlong: ...
    @overload
    def min_length(self, length: int) -> None: ...
    @overload
    def min_length(self, unsignedlong) -> void: ...
    @overload
    def min_length(self) -> int: ...
    @overload
    def min_length(self) -> unsignedlong: ...
    @overload
    def set_cdr(self, cdr: CDRNameEnum) -> None: ...
    @overload
    def set_cdr(self, enumprotocols) -> void: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...

class CDRSetOptionsParser:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CDRSetOptionsParser) -> None: ...
    def assign(self) -> CDRSetOptionsParser: ...
    def clone(self) -> CDRSetOptionsParser: ...
    @overload
    def parse_default_and_user_options(self, cdr: CDRNameEnum, filename: str) -> CDRSetOptions: ...
    @overload
    def parse_default_and_user_options(self, filename: str) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_CDRSetOptions_t: ...
    @overload
    def parse_options(self, cdr: CDRNameEnum, filename: str) -> CDRSetOptions: ...
    @overload
    def parse_options(self, filename: str) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_CDRSetOptions_t: ...

class CDRsMinPackMin(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, antibody_info: AntibodyInfo) -> None: ...
    @overload
    def __init__(self, antibody_info: AntibodyInfo, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, tf: pyrosetta.rosetta.core.pack.task.TaskFactory, movemap: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def __init__(self, arg0: CDRsMinPackMin) -> None: ...
    @overload
    def __init__(self, arg0: CDRsMinPackMin) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> CDRsMinPackMin: ...
    def get_name(self) -> str: ...
    @overload
    def set_alter_foldtree(self, setting: bool) -> None: ...
    @overload
    def set_alter_foldtree(self, bool) -> void: ...
    @overload
    def set_move_map(self, movemap: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def set_move_map(self, classstd) -> void: ...
    @overload
    def set_rt_min(self, rtmin: bool) -> None: ...
    @overload
    def set_rt_min(self, bool) -> void: ...
    @overload
    def set_sc_min(self, scmin: bool) -> None: ...
    @overload
    def set_sc_min(self, bool) -> void: ...
    @overload
    def set_task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...
    @overload
    def set_turnoff_minimization(self, setting: bool) -> None: ...
    @overload
    def set_turnoff_minimization(self, bool) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class CloseOneCDRLoop(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, query_start: int, query_end: int) -> None: ...
    @overload
    def __init__(self, arg0: CloseOneCDRLoop) -> None: ...
    @overload
    def __init__(self, arg0: CloseOneCDRLoop) -> None: ...
    @overload
    def apply(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> CloseOneCDRLoop: ...
    @overload
    def enable_benchmark_mode(self, setting: bool) -> None: ...
    @overload
    def enable_benchmark_mode(self, bool) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...

class FrameWork:
    chain_name: str
    start: int
    stop: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FrameWork) -> None: ...
    def assign(self) -> FrameWork: ...

class GraftCDRLoopsProtocol(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GraftCDRLoopsProtocol) -> None: ...
    @overload
    def __init__(self, arg0: GraftCDRLoopsProtocol) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> GraftCDRLoopsProtocol: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def display_constraint_residues(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def display_constraint_residues(self, classcore) -> void: ...
    def get_name(self) -> str: ...
    @overload
    @staticmethod
    def register_options() -> None: ...
    @overload
    @staticmethod
    def register_options() -> void: ...
    @overload
    def set_benchmark(self, benchmark: bool) -> None: ...
    @overload
    def set_benchmark(self, bool) -> void: ...
    @overload
    def set_camelid(self, camelid: bool) -> None: ...
    @overload
    def set_camelid(self, bool) -> void: ...
    @overload
    def set_camelid_constraints(self, camelid_constraints: bool) -> None: ...
    @overload
    def set_camelid_constraints(self, bool) -> void: ...
    @overload
    def set_cst_weight(self, cst_weight: float) -> None: ...
    @overload
    def set_cst_weight(self, double) -> void: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_graft_h1(self, graft_h1: bool) -> None: ...
    @overload
    def set_graft_h1(self, bool) -> void: ...
    @overload
    def set_graft_h2(self, graft_h2: bool) -> None: ...
    @overload
    def set_graft_h2(self, bool) -> void: ...
    @overload
    def set_graft_h3(self, graft_h3: bool) -> None: ...
    @overload
    def set_graft_h3(self, bool) -> void: ...
    @overload
    def set_graft_l1(self, graft_l1: bool) -> None: ...
    @overload
    def set_graft_l1(self, bool) -> void: ...
    @overload
    def set_graft_l2(self, graft_l2: bool) -> None: ...
    @overload
    def set_graft_l2(self, bool) -> void: ...
    @overload
    def set_graft_l3(self, graft_l3: bool) -> None: ...
    @overload
    def set_graft_l3(self, bool) -> void: ...
    @overload
    def set_h3_stem_graft(self, h3_stem_graft: bool) -> None: ...
    @overload
    def set_h3_stem_graft(self, bool) -> void: ...
    @overload
    def set_packonly_after_graft(self, setting: bool) -> None: ...
    @overload
    def set_packonly_after_graft(self, bool) -> void: ...
    @overload
    def set_rt_min(self, rtmin: bool) -> None: ...
    @overload
    def set_rt_min(self, bool) -> void: ...
    @overload
    def set_sc_min(self, scmin: bool) -> None: ...
    @overload
    def set_sc_min(self, bool) -> void: ...
    @overload
    def set_stem_optimize(self, setting: bool) -> None: ...
    @overload
    def set_stem_optimize(self, bool) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class GraftOneCDRLoop(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, cdr_name: CDRNameEnum, antibody_info: AntibodyInfo, ab_t_info: Ab_TemplateInfo) -> None: ...
    @overload
    def __init__(self, arg0: GraftOneCDRLoop) -> None: ...
    @overload
    def __init__(self, arg0: GraftOneCDRLoop) -> None: ...
    @overload
    def apply(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self, rhs: GraftOneCDRLoop) -> GraftOneCDRLoop: ...
    @overload
    def enable_benchmark_mode(self, setting: bool) -> None: ...
    @overload
    def enable_benchmark_mode(self, bool) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def set_flank_size(self, setting: int) -> None: ...
    @overload
    def set_flank_size(self, unsignedlong) -> void: ...
    def set_no_stem_copy(self, setting: bool) -> None: ...
    @overload
    def set_scorefxn(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn(self, classstd) -> void: ...

class GraftedStemOptimizer(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, cdr_name: CDRNameEnum, antibody_info: AntibodyInfo) -> None: ...
    @overload
    def __init__(self, arg0: GraftedStemOptimizer) -> None: ...
    @overload
    def __init__(self, arg0: GraftedStemOptimizer) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self, rhs: GraftedStemOptimizer) -> GraftedStemOptimizer: ...
    def enable_benchmark_mode(self, setting: bool) -> None: ...
    def get_Cstem_foldtree(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    def get_N_C_stems_foldtree(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    def get_Nstem_foldtree(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    def get_name(self) -> str: ...
    @overload
    def get_stem_movemap(self, pose: pyrosetta.rosetta.core.pose.Pose, type: str) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_stem_movemap(self, pose: pyrosetta.rosetta.core.pose.Pose, type: str, include_nb_sc: bool) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_stem_taskfactory(self, pose: pyrosetta.rosetta.core.pose.Pose, type: str) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    @overload
    def get_stem_taskfactory(self, pose: pyrosetta.rosetta.core.pose.Pose, type: str, include_nb_sc: bool) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    def set_deep_optimization(self, setting: bool) -> None: ...
    @overload
    def set_scorefxn(self, setting: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn(self, classstd) -> void: ...
    def set_stem_size(self, setting: int) -> None: ...

class H3BaseTypeEnum:
    __members__: ClassVar[dict] = ...  # read-only
    Extended: ClassVar[H3BaseTypeEnum] = ...
    H3BaseTypeEnum_start: ClassVar[H3BaseTypeEnum] = ...
    H3BaseTypeEnum_total: ClassVar[H3BaseTypeEnum] = ...
    Kinked: ClassVar[H3BaseTypeEnum] = ...
    Neutral: ClassVar[H3BaseTypeEnum] = ...
    Unknown: ClassVar[H3BaseTypeEnum] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class H3CterInsert(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, antibody_info: AntibodyInfo) -> None: ...
    @overload
    def __init__(self, arg0: H3CterInsert) -> None: ...
    @overload
    def __init__(self, arg0: H3CterInsert) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> H3CterInsert: ...
    def get_name(self) -> str: ...
    @overload
    def read_H3_cter_fragment(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def read_H3_cter_fragment(self, constclasscore) -> void: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...

class H3PerturbCCD(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, antibody_in: AntibodyInfo) -> None: ...
    @overload
    def __init__(self, antibody_in: AntibodyInfo, highres_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: H3PerturbCCD) -> None: ...
    @overload
    def __init__(self, arg0: H3PerturbCCD) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> H3PerturbCCD: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def pass_the_loop(self, input_loop: pyrosetta.rosetta.protocols.loops.Loop) -> None: ...
    @overload
    def pass_the_loop(self, classprotocols) -> void: ...
    @overload
    def read_and_store_fragments(self) -> None: ...
    @overload
    def read_and_store_fragments(self) -> void: ...
    @overload
    def set_lowres_score_func(self, lowres_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_lowres_score_func(self, classstd) -> void: ...
    @overload
    def turn_off_H3_filter(self) -> None: ...
    @overload
    def turn_off_H3_filter(self) -> void: ...

class H3RefineCCD(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, antibody_info: AntibodyInfo, loop_name: CDRNameEnum) -> None: ...
    @overload
    def __init__(self, antibody_info: AntibodyInfo, loop_name: CDRNameEnum, highres_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, antibody_info: AntibodyInfo) -> None: ...
    @overload
    def __init__(self, arg0: H3RefineCCD) -> None: ...
    @overload
    def __init__(self, arg0: H3RefineCCD) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> H3RefineCCD: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def pass_start_pose(self, start_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def pass_start_pose(self, classcore) -> void: ...
    @overload
    def set_highres_score_func(self, highres_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_highres_score_func(self, classstd) -> void: ...
    @overload
    def set_task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...
    @overload
    def turn_off_flank_relax(self) -> None: ...
    @overload
    def turn_off_flank_relax(self) -> void: ...
    @overload
    def turn_off_h3_filter(self) -> None: ...
    @overload
    def turn_off_h3_filter(self) -> void: ...
    @overload
    def turn_on_benchmark(self) -> None: ...
    @overload
    def turn_on_benchmark(self) -> void: ...

class LHRepulsiveRamp(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, movable_jumps: pyrosetta.rosetta.utility.vector1_int, dock_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, pack_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: LHRepulsiveRamp) -> None: ...
    @overload
    def __init__(self, arg0: LHRepulsiveRamp) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> LHRepulsiveRamp: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_dock_jump(self, jump: pyrosetta.rosetta.utility.vector1_int) -> None: ...
    @overload
    def set_dock_jump(self, classutility) -> void: ...
    @overload
    def set_dock_score_func(self, dock_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_dock_score_func(self, classstd) -> void: ...
    @overload
    def set_move_map(self, movemap: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def set_move_map(self, classstd) -> void: ...
    @overload
    def set_pack_score_func(self, pack_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_pack_score_func(self, classstd) -> void: ...
    @overload
    def set_rot_mag(self, rot_mag: float) -> float: ...
    @overload
    def set_rot_mag(self, double) -> double: ...
    @overload
    def set_rt_min(self, rt_min: bool) -> None: ...
    @overload
    def set_rt_min(self, bool) -> void: ...
    @overload
    def set_sc_min(self, sc_min: bool) -> None: ...
    @overload
    def set_sc_min(self, bool) -> void: ...
    @overload
    def set_task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...
    @overload
    def set_trans_mag(self, trans_mag: float) -> float: ...
    @overload
    def set_trans_mag(self, double) -> double: ...

class LHRepulsiveRampLegacy(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, loops_in: pyrosetta.rosetta.protocols.loops.Loops) -> None: ...
    @overload
    def __init__(self, antibody_in: AntibodyInfo) -> None: ...
    @overload
    def __init__(self, antibody_in: AntibodyInfo, camelid: bool) -> None: ...
    @overload
    def __init__(self, loops_in: pyrosetta.rosetta.protocols.loops.Loops, dock_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, pack_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, antibody_in: AntibodyInfo, dock_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, pack_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: LHRepulsiveRampLegacy) -> None: ...
    @overload
    def __init__(self, arg0: LHRepulsiveRampLegacy) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> LHRepulsiveRampLegacy: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_dock_score_func(self, dock_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_dock_score_func(self, classstd) -> void: ...
    @overload
    def set_pack_score_func(self, pack_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_pack_score_func(self, classstd) -> void: ...
    @overload
    def set_rot_mag(self, rot_mag: float) -> float: ...
    @overload
    def set_rot_mag(self, double) -> double: ...
    @overload
    def set_task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...
    @overload
    def set_trans_mag(self, trans_mag: float) -> float: ...
    @overload
    def set_trans_mag(self, double) -> double: ...

class LHSnugFitLegacy(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, loops_in: pyrosetta.rosetta.protocols.loops.Loops) -> None: ...
    @overload
    def __init__(self, antibody_in: AntibodyInfo) -> None: ...
    @overload
    def __init__(self, antibody_in: AntibodyInfo, camelid: bool) -> None: ...
    @overload
    def __init__(self, arg0: LHSnugFitLegacy) -> None: ...
    @overload
    def __init__(self, arg0: LHSnugFitLegacy) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> LHSnugFitLegacy: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...

class LightChainTypeEnum:
    __members__: ClassVar[dict] = ...  # read-only
    LightChainTypeEnum_start: ClassVar[LightChainTypeEnum] = ...
    LightChainTypeEnum_total: ClassVar[LightChainTypeEnum] = ...
    __entries: ClassVar[dict] = ...
    kappa: ClassVar[LightChainTypeEnum] = ...
    lambda6: ClassVar[LightChainTypeEnum] = ...
    unknown: ClassVar[LightChainTypeEnum] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class PDBLandmark:
    @overload
    def __init__(self, chain: str, resnum: int, insertion_code: str) -> None: ...
    @overload
    def __init__(self, chain: str, resnum: int, insertion_code: str, scheme: AntibodyNumberingSchemeEnum) -> None: ...
    @overload
    def __init__(self, arg0: PDBLandmark) -> None: ...
    def assign(self) -> PDBLandmark: ...
    @overload
    def chain(self) -> str: ...
    @overload
    def chain(self) -> char: ...
    def get_string(self) -> str: ...
    @overload
    def insertion_code(self) -> str: ...
    @overload
    def insertion_code(self) -> char: ...
    def numbering_scheme(self) -> AntibodyNumberingSchemeEnum: ...
    @overload
    def resnum(self) -> int: ...
    @overload
    def resnum(self) -> unsignedlong: ...
    def __eq__(self, compare: PDBLandmark) -> bool: ...
    def __ne__(self, compare: PDBLandmark) -> bool: ...

class PackingAngleEnum:
    __members__: ClassVar[dict] = ...  # read-only
    PackingAngleEnum_start: ClassVar[PackingAngleEnum] = ...
    PackingAngleEnum_total: ClassVar[PackingAngleEnum] = ...
    VH_sheet_1: ClassVar[PackingAngleEnum] = ...
    VH_sheet_2: ClassVar[PackingAngleEnum] = ...
    VL_sheet_1: ClassVar[PackingAngleEnum] = ...
    VL_sheet_2: ClassVar[PackingAngleEnum] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class ParatopeMetric_double_t:
    cdr: pyrosetta.rosetta.utility.vector1_double
    paratope: float
    paratope_heavy: float
    paratope_light: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ParatopeMetric_double_t) -> None: ...
    def assign(self) -> ParatopeMetric_double_t: ...

class ParatopeMetric_long_t:
    cdr: pyrosetta.rosetta.utility.vector1_long
    paratope: int
    paratope_heavy: int
    paratope_light: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ParatopeMetric_long_t) -> None: ...
    def assign(self) -> ParatopeMetric_long_t: ...

class RefineBetaBarrel(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, antibody_info: AntibodyInfo) -> None: ...
    @overload
    def __init__(self, antibody_info: AntibodyInfo, dock_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, pack_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: RefineBetaBarrel) -> None: ...
    @overload
    def __init__(self, arg0: RefineBetaBarrel) -> None: ...
    @overload
    def apply(self, pose_in: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RefineBetaBarrel: ...
    def get_name(self) -> str: ...
    @overload
    def set_dock_score_func(self, dock_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_dock_score_func(self, classstd) -> void: ...
    @overload
    def set_pack_score_func(self, pack_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_pack_score_func(self, classstd) -> void: ...
    @overload
    def set_rt_min(self, rt_min: bool) -> None: ...
    @overload
    def set_rt_min(self, bool) -> void: ...
    @overload
    def set_sc_min(self, sc_min: bool) -> None: ...
    @overload
    def set_sc_min(self, bool) -> void: ...
    @overload
    def set_task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...
    @overload
    def turn_off_repulsive_ramp(self) -> None: ...
    @overload
    def turn_off_repulsive_ramp(self) -> void: ...

@overload
def CDR_H3_cter_filter(pose_in: pyrosetta.rosetta.core.pose.Pose, ab_info: AntibodyInfo) -> bool: ...
@overload
def CDR_H3_cter_filter(constclasscore, classstd) -> bool: ...
@overload
def CDR_H3_filter_legacy_code_with_old_rule(pose_in: pyrosetta.rosetta.core.pose.Pose, input_loop: pyrosetta.rosetta.protocols.loops.Loop, is_camelid: bool) -> bool: ...
@overload
def CDR_H3_filter_legacy_code_with_old_rule(constclasscore, classprotocols, bool) -> bool: ...
@overload
def align_to_native(pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, ab_info: AntibodyInfo, native_ab_info: AntibodyInfo) -> None: ...
@overload
def align_to_native(pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, ab_info: AntibodyInfo, native_ab_info: AntibodyInfo, request_chain: str) -> None: ...
@overload
def attributes_for_get_cdr_bool_from_tag(attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t, tagname: str) -> None: ...
@overload
def attributes_for_get_cdr_bool_from_tag(attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t, tagname: str, Description: str) -> None: ...
@overload
def cdr_CN_anchor_distance(pose: pyrosetta.rosetta.core.pose.Pose, ab_info, cdr: CDRNameEnum) -> float: ...
@overload
def cdr_CN_anchor_distance(constclasscore, classstd, constenumprotocols) -> double: ...
@overload
def cdr_backbone_rmsds(p1: pyrosetta.rosetta.core.pose.Pose, p2: pyrosetta.rosetta.core.pose.Pose, a1, a2) -> pyrosetta.rosetta.utility.vector1_double: ...
@overload
def cdr_backbone_rmsds(p1: pyrosetta.rosetta.core.pose.Pose, p2: pyrosetta.rosetta.core.pose.Pose, a1, a2, aln_thresh: int) -> pyrosetta.rosetta.utility.vector1_double: ...
def cdr_energy(pose: pyrosetta.rosetta.core.pose.Pose, ab_info, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, cdr: CDRNameEnum) -> float: ...
@overload
def check_fix_aho_cdr_numbering(ab_info: AntibodyInfo, cdr: CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def check_fix_aho_cdr_numbering(classstd, enumprotocols, classcore) -> void: ...
@overload
def check_fix_aho_cdr_numbering(ab_info: AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def check_fix_aho_cdr_numbering(classstd, classcore) -> void: ...
@overload
def cutpoint_separation(pose_in: pyrosetta.rosetta.core.pose.Pose, cutpoint: int) -> float: ...
@overload
def cutpoint_separation(classcore, unsignedlong) -> double: ...
@overload
def cutpoints_separation(pose: pyrosetta.rosetta.core.pose.Pose, antibody_info: AntibodyInfo) -> bool: ...
@overload
def cutpoints_separation(classcore, classstd) -> bool: ...
def deep_copy(*args, **kwargs): ...
@overload
def get_cdr_bool_from_tag(tag: pyrosetta.rosetta.utility.tag.Tag, name: str) -> pyrosetta.rosetta.utility.vector1_bool: ...
@overload
def get_cdr_bool_from_tag(tag: pyrosetta.rosetta.utility.tag.Tag, name: str, include_cdr4: bool) -> pyrosetta.rosetta.utility.vector1_bool: ...
@overload
def get_cdr_loops(ab_info: AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, cdrs: pyrosetta.rosetta.utility.vector1_bool) -> pyrosetta.rosetta.protocols.loops.Loops: ...
@overload
def get_cdr_loops(ab_info: AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, cdrs: pyrosetta.rosetta.utility.vector1_bool, stem_size: int) -> pyrosetta.rosetta.protocols.loops.Loops: ...
def get_conserved_residue_list(chain: str) -> pyrosetta.rosetta.utility.vector1_double: ...
def get_matching_landmark(numbering: AntibodyNumbering, landmark: PDBLandmark, from_scheme: AntibodyNumberingSchemeEnum, to_scheme: AntibodyNumberingSchemeEnum) -> PDBLandmark: ...
def global_loop_rmsd(pose_in: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, current_loop: pyrosetta.rosetta.protocols.loops.Loops) -> float: ...
@overload
def is_H3_rama_kinked(rama: str) -> bool: ...
@overload
def is_H3_rama_kinked(conststd) -> bool: ...
@overload
def kink_RD_Hbond(pose: pyrosetta.rosetta.core.pose.Pose, abinfo) -> float: ...
@overload
def kink_RD_Hbond(constclasscore, constclassprotocols) -> double: ...
@overload
def kink_Trp_Hbond(pose: pyrosetta.rosetta.core.pose.Pose, abinfo) -> float: ...
@overload
def kink_Trp_Hbond(constclasscore, constclassprotocols) -> double: ...
@overload
def kink_bb_Hbond(pose: pyrosetta.rosetta.core.pose.Pose, abinfo) -> float: ...
@overload
def kink_bb_Hbond(constclasscore, constclassprotocols) -> double: ...
@overload
def kink_constrain_antibody_H3(pose: pyrosetta.rosetta.core.pose.Pose, kink_begin: int) -> None: ...
@overload
def kink_constrain_antibody_H3(classcore, unsignedlong) -> void: ...
@overload
def kink_constrain_antibody_H3(pose: pyrosetta.rosetta.core.pose.Pose, antibody_info: AntibodyInfo) -> None: ...
@overload
def kink_constrain_antibody_H3(classcore, constclassstd) -> void: ...
@overload
def kink_dihedral(pose: pyrosetta.rosetta.core.pose.Pose, abinfo) -> tuple[float, float]: ...
@overload
def kink_dihedral(pose: pyrosetta.rosetta.core.pose.Pose, abinfo, debug: bool) -> tuple[float, float]: ...
@overload
def paratope_charge(pose: pyrosetta.rosetta.core.pose.Pose, abinfo) -> ParatopeMetric_long_t: ...
@overload
def paratope_charge(pose: pyrosetta.rosetta.core.pose.Pose, abinfo, include_de_loop: bool) -> ParatopeMetric_long_t: ...
@overload
def paratope_sasa(pose: pyrosetta.rosetta.core.pose.Pose, ab_info) -> tuple[ParatopeMetric_double_t, ParatopeMetric_double_t]: ...
@overload
def paratope_sasa(pose: pyrosetta.rosetta.core.pose.Pose, ab_info, include_de_loop: bool) -> tuple[ParatopeMetric_double_t, ParatopeMetric_double_t]: ...
@overload
def pose_charge(pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
@overload
def pose_charge(constclasscore) -> long: ...
def qq_constrain_antibody(pose: pyrosetta.rosetta.core.pose.Pose, VH_qq_resi: int, VL_qq_resi: int) -> None: ...
@overload
def select_epitope_residues(ab_info: AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_bool: ...
@overload
def select_epitope_residues(ab_info: AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, interface_distance: int) -> pyrosetta.rosetta.utility.vector1_bool: ...
def setup_A_LH_foldtree(ab_info: AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose) -> str: ...
def setup_LH_A_foldtree(ab_info: AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose) -> str: ...
def setup_packer_task(pose_in: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
def simple_fold_tree(pose_in: pyrosetta.rosetta.core.pose.Pose, jumppoint1: int, cutpoint: int, jumppoint2: int) -> None: ...
@overload
def simple_one_loop_fold_tree(pose: pyrosetta.rosetta.core.pose.Pose, loop: pyrosetta.rosetta.protocols.loops.Loop) -> None: ...
@overload
def simple_one_loop_fold_tree(classcore, constclassprotocols) -> void: ...
def vl_vh_orientation_coords(pose_in: pyrosetta.rosetta.core.pose.Pose, ab_info) -> pyrosetta.rosetta.utility.vector1_double: ...
