import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pack.task.operation
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.protocols.antibody
import pyrosetta.rosetta.protocols.antibody.clusters
import pyrosetta.rosetta.protocols.loops
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import ClassVar, overload

DesignProtocolEnum_total: AntibodyDesignProtocolEnum
MinTypeEnum_total: MinTypeEnum
SeqDesignStrategyEnum_total: SeqDesignStrategyEnum
backrub_protocol: MinTypeEnum
centroid_relax: MinTypeEnum
deterministic_graft: AntibodyDesignProtocolEnum
dualspace: MinTypeEnum
even_cluster_monte_carlo: AntibodyDesignProtocolEnum
even_length_cluster_monte_carlo: AntibodyDesignProtocolEnum
generalized_monte_carlo: AntibodyDesignProtocolEnum
minimize: MinTypeEnum
minimize_cartesian: MinTypeEnum
no_min: MinTypeEnum
relax: MinTypeEnum
repack: MinTypeEnum
seq_design_basic: SeqDesignStrategyEnum
seq_design_conservative: SeqDesignStrategyEnum
seq_design_none: SeqDesignStrategyEnum
seq_design_profile_sets: SeqDesignStrategyEnum
seq_design_profile_sets_combined: SeqDesignStrategyEnum
seq_design_profiles: SeqDesignStrategyEnum

class AntibodyDesignEnumManager:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyDesignEnumManager) -> None: ...
    def assign(self) -> AntibodyDesignEnumManager: ...
    def design_protocol_enum_to_string(self, design_protocol: AntibodyDesignProtocolEnum) -> str: ...
    @overload
    def design_protocol_is_present(self, design_protocol: str) -> bool: ...
    @overload
    def design_protocol_is_present(self, conststd) -> bool: ...
    def design_protocol_string_to_enum(self, design_protocol: str) -> AntibodyDesignProtocolEnum: ...
    def get_recognized_design_protocols(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    def min_type_enum_to_string(self, min_type: MinTypeEnum) -> str: ...
    @overload
    def min_type_is_present(self, min_type: str) -> bool: ...
    @overload
    def min_type_is_present(self, conststd) -> bool: ...
    def min_type_string_to_enum(self, min_type: str) -> MinTypeEnum: ...
    def seq_design_strategy_enum_to_string(self, seq_design_strategy: SeqDesignStrategyEnum) -> str: ...
    @overload
    def seq_design_strategy_is_present(self, seq_design_strategy: str) -> bool: ...
    @overload
    def seq_design_strategy_is_present(self, conststd) -> bool: ...
    def seq_design_strategy_string_to_enum(self, seq_design_strategy: str) -> SeqDesignStrategyEnum: ...

class AntibodyDesignMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyDesignMover) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyDesignMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> AntibodyDesignMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_additional_output(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    def get_name(self) -> str: ...
    def get_top_designs(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_cdr_set_options(self, cdr_set_options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_CDRSetOptions_t) -> None: ...
    @overload
    def set_cdr_set_options(self, classutility) -> void: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...
    @overload
    def set_design_protocol(self, design_protocol: AntibodyDesignProtocolEnum) -> None: ...
    @overload
    def set_design_protocol(self, enumprotocols) -> void: ...
    @overload
    def set_dock_first_cycles(self, dock_first_cycles: int) -> None: ...
    @overload
    def set_dock_first_cycles(self, unsignedlong) -> void: ...
    @overload
    def set_dock_post_graft(self, dock_post_graft: bool) -> None: ...
    @overload
    def set_dock_post_graft(self, bool) -> void: ...
    @overload
    def set_dock_rounds(self, dock_rounds: int) -> None: ...
    @overload
    def set_dock_rounds(self, unsignedlong) -> void: ...
    @overload
    def set_dock_second_cycles(self, dock_second_cycles: int) -> None: ...
    @overload
    def set_dock_second_cycles(self, unsignedlong) -> void: ...
    @overload
    def set_epitope_residues(self, epitope_residues: pyrosetta.rosetta.utility.vector1_protocols_antibody_design_PDBNumbering) -> None: ...
    @overload
    def set_epitope_residues(self, classutility) -> void: ...
    @overload
    def set_graft_design_cdrs(self, graft_design_cdrs: pyrosetta.rosetta.utility.vector1_protocols_antibody_CDRNameEnum) -> None: ...
    @overload
    def set_graft_design_cdrs(self, classutility) -> void: ...
    @overload
    def set_graft_design_options(self, graft_design_options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRGraftDesignOptions_t) -> None: ...
    @overload
    def set_graft_design_options(self, classutility) -> void: ...
    @overload
    def set_inner_cycles(self, inner_cycles: int) -> None: ...
    @overload
    def set_inner_cycles(self, unsignedlong) -> void: ...
    @overload
    def set_instruction_file(self, instruction_file: str) -> None: ...
    @overload
    def set_instruction_file(self, std) -> void: ...
    @overload
    def set_interface_dis(self, interface_dis: float) -> None: ...
    @overload
    def set_interface_dis(self, double) -> void: ...
    @overload
    def set_keep_top_designs(self, top_designs: int) -> None: ...
    @overload
    def set_keep_top_designs(self, unsignedlong) -> void: ...
    @overload
    def set_light_chain(self, light_chain: str) -> None: ...
    @overload
    def set_light_chain(self, conststd) -> void: ...
    @overload
    def set_neighbor_dis(self, neighbor_dis: float) -> None: ...
    @overload
    def set_neighbor_dis(self, double) -> void: ...
    @overload
    def set_outer_cycles(self, outer_cycles: int) -> None: ...
    @overload
    def set_outer_cycles(self, unsignedlong) -> void: ...
    @overload
    def set_paratope_cdrs(self, cdrs: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def set_paratope_cdrs(self, constclassutility) -> void: ...
    def set_primary_cdrs(self, primary_cdrs: pyrosetta.rosetta.utility.vector1_protocols_antibody_CDRNameEnum) -> None: ...
    @overload
    def set_random_start(self, random_start: bool) -> None: ...
    @overload
    def set_random_start(self, constbool) -> void: ...
    @overload
    def set_relax_cycles(self, relax_cycles: int) -> None: ...
    @overload
    def set_relax_cycles(self, unsignedlong) -> void: ...
    @overload
    def set_scorefunction(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefunction(self, classstd) -> void: ...
    @overload
    def set_scorefunction_min(self, min_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefunction_min(self, classstd) -> void: ...
    @overload
    def set_seq_design_cdrs(self, seq_design_cdrs: pyrosetta.rosetta.utility.vector1_protocols_antibody_CDRNameEnum) -> None: ...
    @overload
    def set_seq_design_cdrs(self, classutility) -> void: ...
    @overload
    def set_seq_design_options(self, seq_design_options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t) -> None: ...
    @overload
    def set_seq_design_options(self, classutility) -> void: ...
    @overload
    def set_use_epitope_constraints(self, use_epitope_csts: bool) -> None: ...
    @overload
    def set_use_epitope_constraints(self, bool) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class AntibodyDesignMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyDesignMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyDesignMoverCreator) -> None: ...
    def assign(self) -> AntibodyDesignMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class AntibodyDesignProtocolEnum:
    __members__: ClassVar[dict] = ...  # read-only
    DesignProtocolEnum_total: ClassVar[AntibodyDesignProtocolEnum] = ...
    __entries: ClassVar[dict] = ...
    deterministic_graft: ClassVar[AntibodyDesignProtocolEnum] = ...
    even_cluster_monte_carlo: ClassVar[AntibodyDesignProtocolEnum] = ...
    even_length_cluster_monte_carlo: ClassVar[AntibodyDesignProtocolEnum] = ...
    generalized_monte_carlo: ClassVar[AntibodyDesignProtocolEnum] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class AntibodySeqDesignTFCreator:
    @overload
    def __init__(self, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo) -> None: ...
    @overload
    def __init__(self, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, force_north_paper_db: bool) -> None: ...
    @overload
    def __init__(self, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, design_options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t) -> None: ...
    @overload
    def __init__(self, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, design_options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t, force_north_paper_db: bool) -> None: ...
    @overload
    def __init__(self, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, design_options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t, force_north_paper_db: bool, stem_size: int) -> None: ...
    @overload
    def __init__(self, arg0: AntibodySeqDesignTFCreator) -> None: ...
    def assign(self) -> AntibodySeqDesignTFCreator: ...
    def clone(self) -> AntibodySeqDesignTFCreator: ...
    @overload
    def design_antigen(self, antigen_design: bool) -> None: ...
    @overload
    def design_antigen(self, bool) -> void: ...
    @overload
    def design_framework(self, framework_design: bool) -> None: ...
    @overload
    def design_framework(self, bool) -> void: ...
    @overload
    def design_proline(self, setting: bool) -> None: ...
    @overload
    def design_proline(self, constbool) -> void: ...
    @overload
    def disable_design_for_non_designing_cdrs(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def disable_design_for_non_designing_cdrs(self, classstd, constclasscore) -> void: ...
    @overload
    def disable_disallowed_aa(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def disable_disallowed_aa(self, classstd, constclasscore) -> void: ...
    @overload
    def disable_proline_design(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def disable_proline_design(self, classstd, constclasscore) -> void: ...
    def generate_task_op_all_cdr_design(self, *args, **kwargs): ...
    def generate_task_op_cdr_design(self, *args, **kwargs): ...
    def generate_task_op_cdr_profiles(self, *args, **kwargs): ...
    @overload
    def generate_tf_seq_design(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    @overload
    def generate_tf_seq_design(self, pose: pyrosetta.rosetta.core.pose.Pose, disable_non_designing_cdrs: bool) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    def generate_tf_seq_design_graft_design(self, pose: pyrosetta.rosetta.core.pose.Pose, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, neighbor_cdr_min: pyrosetta.rosetta.utility.vector1_bool) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    @overload
    def get_cdr_design_options(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t: ...
    @overload
    def get_cdr_design_options(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum) -> CDRSeqDesignOptions: ...
    @overload
    def neighbor_detection_dis(self, neighbor_distance: float) -> None: ...
    @overload
    def neighbor_detection_dis(self, constdouble) -> void: ...
    @overload
    def set_cdr_design_options(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, design_options: CDRSeqDesignOptions) -> None: ...
    @overload
    def set_cdr_design_options(self, enumprotocols, classstd) -> void: ...
    @overload
    def set_cdr_design_options(self, design_options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t) -> None: ...
    @overload
    def set_cdr_design_options(self, constclassutility) -> void: ...
    @overload
    def set_design_H3_stem(self, design_H3_stem: bool) -> None: ...
    @overload
    def set_design_H3_stem(self, bool) -> void: ...
    @overload
    def set_design_framework_conservative(self, design_framework_conservative: bool) -> None: ...
    @overload
    def set_design_framework_conservative(self, bool) -> void: ...
    @overload
    def set_design_framework_conserved_res(self, design_framework_conserved_res: bool) -> None: ...
    @overload
    def set_design_framework_conserved_res(self, bool) -> void: ...
    @overload
    def set_no_probability(self, no_probability: bool) -> None: ...
    @overload
    def set_no_probability(self, bool) -> void: ...
    @overload
    def set_probability_data_cutoff(self, cutoff: int) -> None: ...
    @overload
    def set_probability_data_cutoff(self, constunsignedlong) -> void: ...
    @overload
    def set_zero_prob_weight_at(self, weight: float) -> None: ...
    @overload
    def set_zero_prob_weight_at(self, constdouble) -> void: ...

class CDRGraftDesignOptions:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum) -> None: ...
    @overload
    def __init__(self, arg0: CDRGraftDesignOptions) -> None: ...
    def assign(self) -> CDRGraftDesignOptions: ...
    def clone(self) -> CDRGraftDesignOptions: ...
    @overload
    def design(self, design: bool) -> None: ...
    @overload
    def design(self, bool) -> void: ...
    @overload
    def design(self) -> bool: ...
    @overload
    def design(self) -> bool: ...
    @overload
    def min_neighbor_sc(self, min_neighbor_sc: bool) -> None: ...
    @overload
    def min_neighbor_sc(self, bool) -> void: ...
    @overload
    def min_neighbor_sc(self) -> bool: ...
    @overload
    def min_neighbor_sc(self) -> bool: ...
    @overload
    def min_rb(self, min_rb: bool) -> None: ...
    @overload
    def min_rb(self, bool) -> void: ...
    @overload
    def min_rb(self) -> bool: ...
    @overload
    def min_rb(self) -> bool: ...
    def min_sc(self, min_sc: bool) -> None: ...
    @overload
    def mintype(self, mintype: MinTypeEnum) -> None: ...
    @overload
    def mintype(self, enumprotocols) -> void: ...
    @overload
    def mintype(self) -> MinTypeEnum: ...
    @overload
    def neighbor_min(self, neighbor_min: pyrosetta.rosetta.utility.vector1_protocols_antibody_CDRNameEnum) -> None: ...
    @overload
    def neighbor_min(self, classutility) -> void: ...
    @overload
    def neighbor_min(self) -> pyrosetta.rosetta.utility.vector1_protocols_antibody_CDRNameEnum: ...
    @overload
    def neighbor_min_add(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum) -> None: ...
    @overload
    def neighbor_min_add(self, enumprotocols) -> void: ...
    @overload
    def neighbor_min_clear(self) -> None: ...
    @overload
    def neighbor_min_clear(self) -> void: ...
    @overload
    def set_cdr(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum) -> None: ...
    @overload
    def set_cdr(self, enumprotocols) -> void: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...
    @overload
    def weight(self, weight: float) -> None: ...
    @overload
    def weight(self, double) -> void: ...
    @overload
    def weight(self) -> float: ...
    @overload
    def weight(self) -> double: ...

class CDRGraftDesignOptionsParser:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CDRGraftDesignOptionsParser) -> None: ...
    def assign(self) -> CDRGraftDesignOptionsParser: ...
    def clone(self) -> CDRGraftDesignOptionsParser: ...
    @overload
    def parse_default_and_user_options(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, filename: str) -> CDRGraftDesignOptions: ...
    @overload
    def parse_default_and_user_options(self, filename: str) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRGraftDesignOptions_t: ...
    @overload
    def parse_options(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, filename: str) -> CDRGraftDesignOptions: ...
    @overload
    def parse_options(self, filename: str) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRGraftDesignOptions_t: ...

class CDRSeqDesignOptions:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum) -> None: ...
    @overload
    def __init__(self, arg0: CDRSeqDesignOptions) -> None: ...
    def assign(self) -> CDRSeqDesignOptions: ...
    def cdr(self) -> pyrosetta.rosetta.protocols.antibody.CDRNameEnum: ...
    def clone(self) -> CDRSeqDesignOptions: ...
    @overload
    def design(self, design: bool) -> None: ...
    @overload
    def design(self, bool) -> void: ...
    @overload
    def design(self) -> bool: ...
    @overload
    def design(self) -> bool: ...
    @overload
    def design_strategy(self, strategy: SeqDesignStrategyEnum) -> None: ...
    @overload
    def design_strategy(self, enumprotocols) -> void: ...
    @overload
    def design_strategy(self) -> SeqDesignStrategyEnum: ...
    @overload
    def disallow_aa(self, disallowed: pyrosetta.rosetta.utility.vector1_core_chemical_AA) -> None: ...
    @overload
    def disallow_aa(self, constclassutility) -> void: ...
    @overload
    def disallow_aa(self) -> pyrosetta.rosetta.utility.vector1_core_chemical_AA: ...
    @overload
    def fallback(self) -> bool: ...
    @overload
    def fallback(self) -> bool: ...
    @overload
    def fallback_strategy(self, strategy: SeqDesignStrategyEnum) -> None: ...
    @overload
    def fallback_strategy(self, enumprotocols) -> void: ...
    @overload
    def fallback_strategy(self) -> SeqDesignStrategyEnum: ...
    @overload
    def set_cdr(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum) -> None: ...
    @overload
    def set_cdr(self, enumprotocols) -> void: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...

class CDRSeqDesignOptionsParser:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CDRSeqDesignOptionsParser) -> None: ...
    def assign(self) -> CDRSeqDesignOptionsParser: ...
    def clone(self) -> CDRSeqDesignOptionsParser: ...
    @overload
    def parse_default_and_user_options(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, filename: str) -> CDRSeqDesignOptions: ...
    @overload
    def parse_default_and_user_options(self, filename: str) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t: ...
    @overload
    def parse_options(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, filename: str) -> CDRSeqDesignOptions: ...
    @overload
    def parse_options(self, filename: str) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t: ...

class GeneralAntibodyModeler:
    @overload
    def __init__(self, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo) -> None: ...
    @overload
    def __init__(self, arg0: GeneralAntibodyModeler) -> None: ...
    @overload
    def ab_dock_chains(self, ab_dock_chains: str) -> None: ...
    @overload
    def ab_dock_chains(self, std) -> void: ...
    @overload
    def apply_A_LH_foldtree(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply_A_LH_foldtree(self, classcore) -> void: ...
    def assign(self) -> GeneralAntibodyModeler: ...
    @overload
    def backrub_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def backrub_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose, min_sc: bool) -> None: ...
    @overload
    def backrub_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose, min_sc: bool, include_neighbor_sc: bool) -> None: ...
    @overload
    def cdr_overhang(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, overhang: int) -> None: ...
    @overload
    def cdr_overhang(self, constenumprotocols, constunsignedlong) -> void: ...
    def clone(self) -> GeneralAntibodyModeler: ...
    @overload
    def dock_high_res(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def dock_high_res(self, pose: pyrosetta.rosetta.core.pose.Pose, first_cycle: int) -> None: ...
    @overload
    def dock_high_res(self, pose: pyrosetta.rosetta.core.pose.Pose, first_cycle: int, second_cycle: int) -> None: ...
    @overload
    def dock_low_res(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def dock_low_res(self, pose: pyrosetta.rosetta.core.pose.Pose, pack_interface: bool) -> None: ...
    @overload
    def dock_low_res(self, classcore, bool) -> void: ...
    @overload
    def extend_CDR(self, pose: pyrosetta.rosetta.core.pose.Pose, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum) -> None: ...
    @overload
    def extend_CDR(self, classcore, enumprotocols) -> void: ...
    def get_cdr_loop_with_overhang(self, pose: pyrosetta.rosetta.core.pose.Pose, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum) -> pyrosetta.rosetta.protocols.loops.Loop: ...
    def get_cdr_loops(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.protocols.loops.Loops: ...
    def get_cdr_loops_with_overhang(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.protocols.loops.Loops: ...
    @overload
    def get_cdrs_movemap_with_overhang(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_cdrs_movemap_with_overhang(self, pose: pyrosetta.rosetta.core.pose.Pose, min_bb: bool) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_cdrs_movemap_with_overhang(self, pose: pyrosetta.rosetta.core.pose.Pose, min_bb: bool, min_sc: bool) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_cdrs_movemap_with_overhang(self, pose: pyrosetta.rosetta.core.pose.Pose, min_bb: bool, min_sc: bool, include_neighbor_sc: bool) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def get_cdrs_movemap_with_overhang(self, pose: pyrosetta.rosetta.core.pose.Pose, min_bb: bool, min_sc: bool, include_neighbor_sc: bool, include_neighbor_bb: bool) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    def get_dock_chains(self) -> str: ...
    def get_movemap_from_task(self, pose: pyrosetta.rosetta.core.pose.Pose, task: pyrosetta.rosetta.core.pack.task.PackerTask) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @overload
    def interface_detection_dis(self, interface_distance: float) -> None: ...
    @overload
    def interface_detection_dis(self, double) -> void: ...
    @overload
    def interface_detection_dis(self) -> float: ...
    @overload
    def interface_detection_dis(self) -> double: ...
    @overload
    def minimize_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def minimize_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose, min_sc: bool) -> None: ...
    @overload
    def minimize_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose, min_sc: bool, include_neighbor_sc: bool) -> None: ...
    @overload
    def minimize_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose, min_sc: bool, include_neighbor_sc: bool, min_interface: bool) -> None: ...
    @overload
    def minimize_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose, min_sc: bool, include_neighbor_sc: bool, min_interface: bool, cartmin: bool) -> None: ...
    @overload
    def minimize_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose, min_sc: bool, include_neighbor_sc: bool, min_interface: bool, cartmin: bool, use_talaris_cartmin: bool) -> None: ...
    @overload
    def minimize_interface(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def minimize_interface(self, pose: pyrosetta.rosetta.core.pose.Pose, min_interface_sc: bool) -> None: ...
    @overload
    def minimize_interface(self, classcore, bool) -> void: ...
    @overload
    def neighbor_detection_dis(self, neighbor_distance: float) -> None: ...
    @overload
    def neighbor_detection_dis(self, double) -> void: ...
    @overload
    def neighbor_detection_dis(self) -> float: ...
    @overload
    def neighbor_detection_dis(self) -> double: ...
    @overload
    def relax_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def relax_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose, include_neighbor_sc: bool) -> None: ...
    @overload
    def relax_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose, include_neighbor_sc: bool, starting_coordinate_constraints: bool) -> None: ...
    @overload
    def relax_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose, include_neighbor_sc: bool, starting_coordinate_constraints: bool, min_interface: bool) -> None: ...
    @overload
    def relax_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose, include_neighbor_sc: bool, starting_coordinate_constraints: bool, min_interface: bool, dualspace: bool) -> None: ...
    @overload
    def relax_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose, include_neighbor_sc: bool, starting_coordinate_constraints: bool, min_interface: bool, dualspace: bool, repeats: int) -> None: ...
    @overload
    def relax_interface(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def relax_interface(self, pose: pyrosetta.rosetta.core.pose.Pose, min_interface_sc: bool) -> None: ...
    @overload
    def relax_interface(self, classcore, bool) -> void: ...
    @overload
    def repack_antibody_interface(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def repack_antibody_interface(self, classcore) -> void: ...
    @overload
    def repack_antigen_ab_interface(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def repack_antigen_ab_interface(self, classcore) -> void: ...
    @overload
    def repack_antigen_interface(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def repack_antigen_interface(self, classcore) -> void: ...
    @overload
    def repack_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def repack_cdrs(self, pose: pyrosetta.rosetta.core.pose.Pose, include_neighbor_sc: bool) -> None: ...
    @overload
    def repack_cdrs(self, classcore, bool) -> void: ...
    @overload
    def reset_task_factory(self) -> None: ...
    @overload
    def reset_task_factory(self) -> void: ...
    @overload
    def set_cdr(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, setting: bool) -> None: ...
    @overload
    def set_cdr(self, constenumprotocols, bool) -> void: ...
    @overload
    def set_cdr_only(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, setting: bool) -> None: ...
    @overload
    def set_cdr_only(self, constenumprotocols, bool) -> void: ...
    def set_cdr_range(self, cdr_start: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, cdr_end: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, setting: bool) -> None: ...
    @overload
    def set_cdrs(self, cdrs: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def set_cdrs(self, classutility) -> void: ...
    @overload
    def set_dock_high_res_scorefunction(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_dock_high_res_scorefunction(self, classstd) -> void: ...
    @overload
    def set_dock_low_res_scorefunction(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_dock_low_res_scorefunction(self, classstd) -> void: ...
    @overload
    def set_overhang(self, overhang: int) -> None: ...
    @overload
    def set_overhang(self, constunsignedlong) -> void: ...
    @overload
    def set_scorefunction(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefunction(self, classstd) -> void: ...
    @overload
    def set_scorefunction_min(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefunction_min(self, classstd) -> void: ...
    @overload
    def set_task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...

class MinTypeEnum:
    __members__: ClassVar[dict] = ...  # read-only
    MinTypeEnum_total: ClassVar[MinTypeEnum] = ...
    __entries: ClassVar[dict] = ...
    backrub_protocol: ClassVar[MinTypeEnum] = ...
    centroid_relax: ClassVar[MinTypeEnum] = ...
    dualspace: ClassVar[MinTypeEnum] = ...
    minimize: ClassVar[MinTypeEnum] = ...
    minimize_cartesian: ClassVar[MinTypeEnum] = ...
    no_min: ClassVar[MinTypeEnum] = ...
    relax: ClassVar[MinTypeEnum] = ...
    repack: ClassVar[MinTypeEnum] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class MutantPosition:
    mutants_allowed_: pyrosetta.rosetta.utility.vector1_bool
    numbering_scheme_: pyrosetta.rosetta.protocols.antibody.AntibodyNumberingSchemeEnum
    pdb_position_: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MutantPosition) -> None: ...
    def assign(self) -> MutantPosition: ...

class MutateFrameworkForCluster(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo) -> None: ...
    @overload
    def __init__(self, arg0: MutateFrameworkForCluster) -> None: ...
    @overload
    def __init__(self, arg0: MutateFrameworkForCluster) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> MutateFrameworkForCluster: ...
    def framework_dependant_clusters(self) -> pyrosetta.rosetta.utility.vector1_protocols_antibody_clusters_CDRClusterEnum: ...
    def framework_dependant_mutations(self, pose: pyrosetta.rosetta.core.pose.Pose, cluster: pyrosetta.rosetta.protocols.antibody.clusters.CDRClusterEnum, resnum: int) -> pyrosetta.rosetta.utility.vector1_bool: ...
    @overload
    def framework_dependant_positions(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_bool: ...
    @overload
    def framework_dependant_positions(self, pose: pyrosetta.rosetta.core.pose.Pose, cluster: pyrosetta.rosetta.protocols.antibody.clusters.CDRClusterEnum) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_data(self) -> pyrosetta.rosetta.std.map_protocols_antibody_clusters_CDRClusterEnum_utility_vector1_protocols_antibody_design_MutantPosition_t_std_allocator_std_pair_const_protocols_antibody_clusters_CDRClusterEnum_utility_vector1_protocols_antibody_design_MutantPosition_t: ...
    def get_name(self) -> str: ...
    @overload
    def has_framework_dependant_cluster(self, pose: pyrosetta.rosetta.core.pose.Pose, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum) -> bool: ...
    @overload
    def has_framework_dependant_cluster(self, constclasscore, constenumprotocols) -> bool: ...
    @overload
    def has_framework_dependant_clusters(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def has_framework_dependant_clusters(self, constclasscore) -> bool: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    def set_cdr_only(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum) -> None: ...
    @overload
    def set_cdr_only(self, constenumprotocols) -> void: ...
    @overload
    def set_cdrs(self, cdrs: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def set_cdrs(self, constclassutility) -> void: ...
    @overload
    def set_custom_data(self, mutant_info: pyrosetta.rosetta.std.map_protocols_antibody_clusters_CDRClusterEnum_utility_vector1_protocols_antibody_design_MutantPosition_t_std_allocator_std_pair_const_protocols_antibody_clusters_CDRClusterEnum_utility_vector1_protocols_antibody_design_MutantPosition_t) -> None: ...
    @overload
    def set_custom_data(self, constclassstd, classutility) -> void: ...
    @overload
    def set_pack_shell(self, pack_shell: float) -> None: ...
    @overload
    def set_pack_shell(self, constdouble) -> void: ...
    @overload
    def set_scorefxn(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn(self, classstd) -> void: ...

class MutateFrameworkForClusterCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MutateFrameworkForClusterCreator) -> None: ...
    def assign(self) -> MutateFrameworkForClusterCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...

class NativeAntibodySeq(pyrosetta.rosetta.basic.datacache.CacheableData):
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: NativeAntibodySeq) -> None: ...
    @overload
    def __init__(self, arg0: NativeAntibodySeq) -> None: ...
    def assign(self) -> NativeAntibodySeq: ...
    def clone(self) -> pyrosetta.rosetta.basic.datacache.CacheableData: ...
    def get_cdr_sequence(self) -> pyrosetta.rosetta.std.map_protocols_antibody_CDRNameEnum_utility_vector1_core_chemical_AA_t_std_allocator_std_pair_const_protocols_antibody_CDRNameEnum_utility_vector1_core_chemical_AA_t: ...
    def get_full_sequence(self) -> pyrosetta.rosetta.std.map_std_string_core_chemical_AA: ...
    def get_native_sequence_matching_current_length(self, pose: pyrosetta.rosetta.core.pose.Pose, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo) -> str: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_from_cdr(self, pose: pyrosetta.rosetta.core.pose.Pose, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum) -> None: ...
    @overload
    def set_from_cdr(self, constclasscore, constclassprotocols, enumprotocols) -> void: ...
    @overload
    def set_sequence(self, pose: pyrosetta.rosetta.core.pose.Pose, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo) -> None: ...
    @overload
    def set_sequence(self, constclasscore, constclassprotocols) -> void: ...
    @overload
    def set_to_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_to_pose(self, classcore) -> void: ...

class PDBNumbering:
    chain: str
    icode: str
    resnum: int
    def __init__(self) -> None: ...

class ResnumFromStringsWithRangesSelector(pyrosetta.rosetta.core.select.residue_selector.ResidueSelector):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pdb_residues: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def __init__(self, arg0: ResnumFromStringsWithRangesSelector) -> None: ...
    @overload
    def __init__(self, arg0: ResnumFromStringsWithRangesSelector) -> None: ...
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def assign(self) -> ResnumFromStringsWithRangesSelector: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    def get_name(self) -> str: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, datamap: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class SeqDesignStrategyEnum:
    __members__: ClassVar[dict] = ...  # read-only
    SeqDesignStrategyEnum_total: ClassVar[SeqDesignStrategyEnum] = ...
    __entries: ClassVar[dict] = ...
    seq_design_basic: ClassVar[SeqDesignStrategyEnum] = ...
    seq_design_conservative: ClassVar[SeqDesignStrategyEnum] = ...
    seq_design_none: ClassVar[SeqDesignStrategyEnum] = ...
    seq_design_profile_sets: ClassVar[SeqDesignStrategyEnum] = ...
    seq_design_profile_sets_combined: ClassVar[SeqDesignStrategyEnum] = ...
    seq_design_profiles: ClassVar[SeqDesignStrategyEnum] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

@overload
def add_loops_from_bool_vector(loops: pyrosetta.rosetta.protocols.loops.Loops, residues: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
@overload
def add_loops_from_bool_vector(loops: pyrosetta.rosetta.protocols.loops.Loops, residues: pyrosetta.rosetta.utility.vector1_bool, add_cutpoints: bool) -> None: ...
@overload
def add_loops_from_bool_vector(classprotocols, classutility, bool) -> void: ...
@overload
def attributes_for_get_ab_design_global_scorefxn(attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
@overload
def attributes_for_get_ab_design_global_scorefxn(classstd) -> void: ...
@overload
def attributes_for_get_ab_design_min_scorefxn(attlist: pyrosetta.rosetta.std.list_utility_tag_XMLSchemaAttribute_t) -> None: ...
@overload
def attributes_for_get_ab_design_min_scorefxn(classstd) -> void: ...
@overload
def check_cb(pose: pyrosetta.rosetta.core.pose.Pose, residues: pyrosetta.rosetta.utility.vector1_bool) -> tuple[bool, int]: ...
@overload
def check_cb(pose: pyrosetta.rosetta.core.pose.Pose, loops: pyrosetta.rosetta.protocols.loops.Loops) -> tuple[bool, int]: ...
def deep_copy(*args, **kwargs): ...
def design_protocol_to_enum(design_type: str) -> AntibodyDesignProtocolEnum: ...
def design_protocol_to_string(design_type: AntibodyDesignProtocolEnum) -> str: ...
def disable_conserved_framework_positions(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.pack.task.operation.RestrictResidueToRepacking: ...
def disable_design_antigen(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.pack.task.operation.RestrictResidueToRepacking: ...
def disable_design_cdr(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.pack.task.operation.RestrictResidueToRepacking: ...
def disable_design_cdrs(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.pack.task.operation.RestrictResidueToRepacking: ...
@overload
def disable_design_framework(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.pack.task.operation.RestrictResidueToRepacking: ...
@overload
def disable_design_framework(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, cdr4_as_framework: bool) -> pyrosetta.rosetta.core.pack.task.operation.RestrictResidueToRepacking: ...
@overload
def disable_design_region(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, region: pyrosetta.rosetta.protocols.antibody.AntibodyRegionEnum) -> pyrosetta.rosetta.core.pack.task.operation.RestrictResidueToRepacking: ...
@overload
def disable_design_region(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, region: pyrosetta.rosetta.protocols.antibody.AntibodyRegionEnum, cdr4_as_framework: bool) -> pyrosetta.rosetta.core.pack.task.operation.RestrictResidueToRepacking: ...
@overload
def disable_h3_stem_positions(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.pack.task.operation.RestrictResidueToRepacking: ...
@overload
def disable_h3_stem_positions(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, nter_stem: int) -> pyrosetta.rosetta.core.pack.task.operation.RestrictResidueToRepacking: ...
@overload
def disable_h3_stem_positions(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, nter_stem: int, cter_stem: int) -> pyrosetta.rosetta.core.pack.task.operation.RestrictResidueToRepacking: ...
def get_ab_design_dock_high_scorefxn() -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
def get_ab_design_dock_low_scorefxn() -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
@overload
def get_ab_design_global_scorefxn() -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
@overload
def get_ab_design_global_scorefxn(tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
@overload
def get_ab_design_min_scorefxn() -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
@overload
def get_ab_design_min_scorefxn(tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
def get_all_graft_permutations(permutations: pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t, totals: pyrosetta.rosetta.utility.vector1_unsigned_long, n: int) -> pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t: ...
@overload
def get_cdr_set_options() -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_CDRSetOptions_t: ...
@overload
def get_cdr_set_options(instruction_file: str) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_CDRSetOptions_t: ...
@overload
def get_cluster_profile_probability_data(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, cdrs: pyrosetta.rosetta.utility.vector1_bool, no_data_cdrs: pyrosetta.rosetta.utility.vector1_bool) -> pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t: ...
@overload
def get_cluster_profile_probability_data(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, cdrs: pyrosetta.rosetta.utility.vector1_bool, no_data_cdrs: pyrosetta.rosetta.utility.vector1_bool, prob_cutoff: int) -> pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t: ...
@overload
def get_cluster_profile_probability_data(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, cdrs: pyrosetta.rosetta.utility.vector1_bool, no_data_cdrs: pyrosetta.rosetta.utility.vector1_bool, prob_cutoff: int, use_outliers: bool) -> pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t: ...
@overload
def get_cluster_profile_probability_data(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, cdrs: pyrosetta.rosetta.utility.vector1_bool, no_data_cdrs: pyrosetta.rosetta.utility.vector1_bool, prob_cutoff: int, use_outliers: bool, force_north_db: bool) -> pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t: ...
@overload
def get_cluster_profile_probability_data(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, cdrs: pyrosetta.rosetta.utility.vector1_bool, no_data_cdrs: pyrosetta.rosetta.utility.vector1_bool, prob_cutoff: int, use_outliers: bool, force_north_db: bool, ignore_light_chain_: bool) -> pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t: ...
@overload
def get_cluster_profile_probability_data(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, seq_design_options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t, no_data_cdrs: pyrosetta.rosetta.utility.vector1_bool) -> pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t: ...
@overload
def get_cluster_profile_probability_data(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, seq_design_options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t, no_data_cdrs: pyrosetta.rosetta.utility.vector1_bool, prob_cutoff: int) -> pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t: ...
@overload
def get_cluster_profile_probability_data(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, seq_design_options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t, no_data_cdrs: pyrosetta.rosetta.utility.vector1_bool, prob_cutoff: int, use_outliers: bool) -> pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t: ...
@overload
def get_cluster_profile_probability_data(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, seq_design_options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t, no_data_cdrs: pyrosetta.rosetta.utility.vector1_bool, prob_cutoff: int, use_outliers: bool, force_north_db: bool) -> pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t: ...
@overload
def get_cluster_profile_probability_data(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, seq_design_options: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t, no_data_cdrs: pyrosetta.rosetta.utility.vector1_bool, prob_cutoff: int, use_outliers: bool, force_north_db: bool, ignore_light_chain_: bool) -> pyrosetta.rosetta.std.map_unsigned_long_std_map_core_chemical_AA_double_t_std_allocator_std_pair_const_unsigned_long_std_map_core_chemical_AA_double_t: ...
def get_dock_chains_from_ab_dock_chains(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, ab_dock_chains: str) -> str: ...
@overload
def get_graft_design_options() -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRGraftDesignOptions_t: ...
@overload
def get_graft_design_options(instruction_file: str) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRGraftDesignOptions_t: ...
def get_native_sequence(pose: pyrosetta.rosetta.core.pose.Pose, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo) -> str: ...
def get_pdb_numbering_from_single_string(pdb_residue: str) -> PDBNumbering: ...
def get_pdb_numbering_from_strings(pdb_residues: pyrosetta.rosetta.utility.vector1_std_string) -> pyrosetta.rosetta.utility.vector1_protocols_antibody_design_PDBNumbering: ...
def get_resnum_from_pdb_numbering(pose: pyrosetta.rosetta.core.pose.Pose, pdb_residues: pyrosetta.rosetta.utility.vector1_protocols_antibody_design_PDBNumbering) -> pyrosetta.rosetta.utility.vector1_bool: ...
@overload
def get_resnum_from_single_string(pose: pyrosetta.rosetta.core.pose.Pose, pdb_residue: str) -> int: ...
@overload
def get_resnum_from_single_string(constclasscore, conststd) -> unsignedlong: ...
@overload
def get_resnum_from_single_string_w_landmark(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, pose: pyrosetta.rosetta.core.pose.Pose, pdb_residue: str, scheme: pyrosetta.rosetta.protocols.antibody.AntibodyNumberingSchemeEnum) -> int: ...
@overload
def get_resnum_from_single_string_w_landmark(classstd, constclasscore, conststd, constenumprotocols) -> unsignedlong: ...
def get_resnum_from_strings(pose: pyrosetta.rosetta.core.pose.Pose, pdb_residues: pyrosetta.rosetta.utility.vector1_std_string) -> pyrosetta.rosetta.utility.vector1_bool: ...
def get_resnums_from_strings_with_ranges(pose: pyrosetta.rosetta.core.pose.Pose, pdb_residues: pyrosetta.rosetta.utility.vector1_std_string) -> pyrosetta.rosetta.utility.vector1_bool: ...
@overload
def get_seq_design_options() -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t: ...
@overload
def get_seq_design_options(instruction_file: str) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_antibody_design_CDRSeqDesignOptions_t: ...
@overload
def has_native_sequence(pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
@overload
def has_native_sequence(constclasscore) -> bool: ...
@overload
def insert_cdr_into_antibody(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose, cdr_piece: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def insert_cdr_into_antibody(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose, cdr_piece: pyrosetta.rosetta.core.pose.Pose, overhang: int) -> None: ...
def seq_design_strategy_to_enum(strategy: str) -> SeqDesignStrategyEnum: ...
def seq_design_strategy_to_string(strategy: SeqDesignStrategyEnum) -> str: ...
@overload
def set_native_cdr_sequence(ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def set_native_cdr_sequence(classstd, enumprotocols, classcore) -> void: ...
