import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.protocols.antibody
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import overload

class AntibodyRegionSelector(pyrosetta.rosetta.core.select.residue_selector.ResidueSelector):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo) -> None: ...
    @overload
    def __init__(self, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, region: pyrosetta.rosetta.protocols.antibody.AntibodyRegionEnum) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyRegionSelector) -> None: ...
    @overload
    def __init__(self, arg0: AntibodyRegionSelector) -> None: ...
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def assign(self) -> AntibodyRegionSelector: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    def get_name(self) -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, datamap: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_ab_info(self, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo) -> None: ...
    @overload
    def set_ab_info(self, classstd) -> void: ...
    @overload
    def set_region(self, region: pyrosetta.rosetta.protocols.antibody.AntibodyRegionEnum) -> None: ...
    @overload
    def set_region(self, enumprotocols) -> void: ...

class AntibodyRegionSelectorCreator(pyrosetta.rosetta.core.select.residue_selector.ResidueSelectorCreator):
    def __init__(self) -> None: ...
    def assign(self) -> AntibodyRegionSelectorCreator: ...
    def create_residue_selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class CDRResidueSelector(pyrosetta.rosetta.core.select.residue_selector.ResidueSelector):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo) -> None: ...
    @overload
    def __init__(self, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, cdrs: pyrosetta.rosetta.utility.vector1_protocols_antibody_CDRNameEnum) -> None: ...
    @overload
    def __init__(self, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo, cdrs: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def __init__(self, arg0: CDRResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: CDRResidueSelector) -> None: ...
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def assign(self) -> CDRResidueSelector: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    def get_name(self) -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, datamap: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_ab_info(self, ab_info: pyrosetta.rosetta.protocols.antibody.AntibodyInfo) -> None: ...
    @overload
    def set_ab_info(self, classstd) -> void: ...
    @overload
    def set_cdr(self, cdr: pyrosetta.rosetta.protocols.antibody.CDRNameEnum) -> None: ...
    @overload
    def set_cdr(self, enumprotocols) -> void: ...
    @overload
    def set_cdrs(self, cdrs: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def set_cdrs(self, classutility) -> void: ...
    @overload
    def set_cdrs(self, cdrs: pyrosetta.rosetta.utility.vector1_protocols_antibody_CDRNameEnum) -> None: ...
    @overload
    def set_cdrs(self, classutility) -> void: ...

class CDRResidueSelectorCreator(pyrosetta.rosetta.core.select.residue_selector.ResidueSelectorCreator):
    def __init__(self) -> None: ...
    def assign(self) -> CDRResidueSelectorCreator: ...
    def create_residue_selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
