import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pack.rotamer_set
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.scoring.annealing
import pyrosetta.rosetta.core.scoring.lkball
import pyrosetta.rosetta.core.scoring.methods
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.utility
from typing import overload

class LK_DomeHelper:
    @overload
    def __init__(self, lk_dome: pyrosetta.rosetta.core.scoring.lkball.LK_DomeEnergy, lk_dome_weight: float, lk_dome_iso_weight: float, lk_dome_bridge_weight: float, lk_dome_bridge_uncpl_weight: float, lk_ball_bridge2_weight: float, lk_ball_bridge_uncpl2_weight: float) -> None: ...
    @overload
    def __init__(self, arg0: LK_DomeHelper) -> None: ...
    def assign(self) -> LK_DomeHelper: ...
    def calculate_energy(self, resvect: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t, current_rotamer_ids: pyrosetta.rosetta.utility.vector1_unsigned_long, substitution_position: int) -> float: ...
    @overload
    def commit_considered_substitution(self) -> None: ...
    @overload
    def commit_considered_substitution(self) -> void: ...
    @overload
    def current_score(self) -> float: ...
    @overload
    def current_score(self) -> double: ...
    def init_with_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, rotamer_sets: pyrosetta.rosetta.core.pack.rotamer_set.RotamerSets) -> pyrosetta.rosetta.core.pack.rotamer_set.RotamerSets: ...

class LK_DomePackEnergy(pyrosetta.rosetta.core.scoring.methods.WholeStructureEnergy, pyrosetta.rosetta.core.scoring.annealing.ResidueArrayAnnealableEnergy):
    @overload
    def __init__(self, options: pyrosetta.rosetta.core.scoring.methods.EnergyMethodOptions) -> None: ...
    @overload
    def __init__(self, arg0: LK_DomePackEnergy) -> None: ...
    @overload
    def __init__(self, arg0: LK_DomePackEnergy) -> None: ...
    def assign(self) -> LK_DomePackEnergy: ...
    @overload
    def calculate_energy(self, resvect: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t, current_rotamer_ids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> float: ...
    @overload
    def calculate_energy(self, resvect: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t, current_rotamer_ids: pyrosetta.rosetta.utility.vector1_unsigned_long, substitution_position: int) -> float: ...
    @overload
    def clean_up_residuearrayannealableenergy_after_packing(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def clean_up_residuearrayannealableenergy_after_packing(self, classcore) -> void: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    @overload
    def commit_considered_substitution(self) -> None: ...
    @overload
    def commit_considered_substitution(self) -> void: ...
    @overload
    def finalize_after_minimizing(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def finalize_after_minimizing(self, classcore) -> void: ...
    def finalize_total_energy(self, pose: pyrosetta.rosetta.core.pose.Pose, totals: pyrosetta.rosetta.core.scoring.EMapVector) -> None: ...
    @overload
    def indicate_required_context_graphs(self, context_graphs_required: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
    @overload
    def indicate_required_context_graphs(self, classutility) -> void: ...
    def set_up_residuearrayannealableenergy_for_packing(self, pose: pyrosetta.rosetta.core.pose.Pose, rotamersets: pyrosetta.rosetta.core.pack.rotamer_set.RotamerSets, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    def setup_for_minimizing(self, pose: pyrosetta.rosetta.core.pose.Pose, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, minmap: pyrosetta.rosetta.core.kinematics.MinimizerMapBase) -> None: ...
    @overload
    def version(self) -> int: ...
    @overload
    def version(self) -> unsignedlong: ...

class LK_DomePackEnergyCreator(pyrosetta.rosetta.core.scoring.methods.EnergyMethodCreator):
    def __init__(self) -> None: ...
    def assign(self) -> LK_DomePackEnergyCreator: ...
    def create_energy_method(self, options: pyrosetta.rosetta.core.scoring.methods.EnergyMethodOptions) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    def score_types_for_method(self) -> pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType: ...

class MyWaterHolder:
    base_xyz: pyrosetta.rosetta.numeric.xyzVector_double_t
    iatom: int
    is_bb: bool
    sol_value: float
    water_xyz: pyrosetta.rosetta.numeric.xyzVector_double_t
    @overload
    def __init__(self, bb: bool, sol: float, wat: pyrosetta.rosetta.numeric.xyzVector_double_t, base: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def __init__(self, bb: bool, sol: float, wat: pyrosetta.rosetta.numeric.xyzVector_double_t, base: pyrosetta.rosetta.numeric.xyzVector_double_t, iat: int) -> None: ...
    @overload
    def __init__(self, arg0: MyWaterHolder) -> None: ...
    def assign(self) -> MyWaterHolder: ...
    def __eq__(self, o: MyWaterHolder) -> bool: ...

def bit_set(bit: int, smallest_byte: int) -> None: ...
def bit_test(bit: int, smallest_byte: int) -> bool: ...
def popcount_until_bit(bit: int, smallest_byte: int) -> int: ...
