from collections import MutableMapping
from pyrosetta.bindings.scores.base import PoseCacheAccessorBase as PoseCacheAccessorBase
from pyrosetta.rosetta.core.simple_metrics import clear_sm_data as clear_sm_data, get_sm_data as get_sm_data

class SimpleMetricDataAccessorBase(PoseCacheAccessorBase, MutableMapping):
    def __init__(self, pose) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def format_composite_string(self, raw_data): ...
    def format_composite_real(self, raw_data): ...
    def format_per_residue_string(self, raw_data): ...
    def format_per_residue_real(self, raw_data): ...
    def format_per_residue_probabilities(self, raw_data): ...
    def clear(self) -> None: ...

class SimpleMetricStringDataAccessor(SimpleMetricDataAccessorBase):
    def __init__(self, pose) -> None: ...
    @property
    def all(self): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def clear(self) -> None: ...

class SimpleMetricRealDataAccessor(SimpleMetricDataAccessorBase):
    def __init__(self, pose) -> None: ...
    @property
    def all(self): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def clear(self) -> None: ...

class SimpleMetricCompositeStringDataAccessor(SimpleMetricDataAccessorBase):
    def __init__(self, pose) -> None: ...
    @property
    def all(self): ...
    def __setitem__(self, key, value) -> None: ...

class SimpleMetricCompositeRealDataAccessor(SimpleMetricDataAccessorBase):
    def __init__(self, pose) -> None: ...
    @property
    def all(self): ...
    def __setitem__(self, key, value) -> None: ...

class SimpleMetricPerResidueStringDataAccessor(SimpleMetricDataAccessorBase):
    def __init__(self, pose) -> None: ...
    @property
    def all(self): ...
    def __setitem__(self, key, value) -> None: ...

class SimpleMetricPerResidueRealDataAccessor(SimpleMetricDataAccessorBase):
    def __init__(self, pose) -> None: ...
    @property
    def all(self): ...
    def __setitem__(self, key, value) -> None: ...

class SimpleMetricPerResidueProbabilitiesDataAccessor(SimpleMetricDataAccessorBase):
    def __init__(self, pose) -> None: ...
    @property
    def all(self): ...
    def __setitem__(self, key, value) -> None: ...

class SimpleMetricDataAccessor(SimpleMetricDataAccessorBase):
    def __init__(self, pose) -> None: ...
    @property
    def all(self): ...
    @property
    def string(self): ...
    @property
    def real(self): ...
    @property
    def composite_string(self): ...
    @property
    def composite_real(self): ...
    @property
    def per_residue_string(self): ...
    @property
    def per_residue_real(self): ...
    @property
    def per_residue_probabilities(self): ...
    def clear(self) -> None: ...
