import pyrosetta.rosetta.ObjexxFCL
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.utility
from typing import overload

class AnnealerFactory:
    def __init__(self) -> None: ...
    @staticmethod
    def create_annealer(*args, **kwargs): ...

class AnnealerObserver:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AnnealerObserver) -> None: ...
    def assign(self) -> AnnealerObserver: ...
    def observe_mc(self, resid: int, mres: int, existing_rotamer: pyrosetta.rosetta.core.conformation.Residue, candidate_rotamer: pyrosetta.rosetta.core.conformation.Residue, temperature: float, passed: bool) -> None: ...
    @overload
    def setup_for_mc(self, rotamer_sets) -> None: ...
    @overload
    def setup_for_mc(self, constclassstd) -> void: ...

class DebuggingAnnealer(RotamerAssigningAnnealer):
    @overload
    def __init__(self, rot_to_pack: pyrosetta.rosetta.utility.vector0_int, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, p_rotamer_set, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    @overload
    def __init__(self, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, p_rotamer_set, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    @overload
    def annealer_file(self, fname: str) -> None: ...
    @overload
    def annealer_file(self, conststd) -> void: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...

class FASTERAnnealer(RotamerAssigningAnnealer):
    def __init__(self, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, rotamer_sets, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def set_ciBR_only(self, setting: bool) -> None: ...
    @overload
    def set_ciBR_only(self, bool) -> void: ...
    @overload
    def set_num_sa_trajectories(self, setting: int) -> None: ...
    @overload
    def set_num_sa_trajectories(self, int) -> void: ...
    @overload
    def set_sa_length_scale(self, setting: float) -> None: ...
    @overload
    def set_sa_length_scale(self, double) -> void: ...

class FixbbCoupledRotamerSimAnnealer(RotamerAssigningAnnealer):
    @overload
    def __init__(self, rot_to_pack: pyrosetta.rosetta.utility.vector0_int, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, rotamer_sets, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t, rotamer_couplings) -> None: ...
    @overload
    def __init__(self, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, rotamer_sets, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t, rotamer_couplings) -> None: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...

class FixbbLinkingRotamerSimAnnealer(RotamerAssigningAnnealer):
    @overload
    def __init__(self, rot_to_pack: pyrosetta.rosetta.utility.vector0_int, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, rotamer_sets, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t, rotamer_links) -> None: ...
    @overload
    def __init__(self, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, rotamer_sets, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t, rotamer_links) -> None: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...

class FixbbPwatSimAnnealer(RotamerAssigningAnnealer):
    def __init__(self, rot_to_pack: pyrosetta.rosetta.utility.vector0_int, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, rotamer_sets, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    def get_dwell_times(self) -> pyrosetta.rosetta.utility.vector1_core_pack_annealer_PointDwell: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def set_min_dwell(self, mindwell: float) -> None: ...
    @overload
    def set_min_dwell(self, double) -> void: ...

class FixbbSimAnnealer(RotamerAssigningAnnealer):
    @overload
    def __init__(self, rot_to_pack: pyrosetta.rosetta.utility.vector0_int, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, rotamer_sets, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    @overload
    def __init__(self, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, rotamer_sets, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    @overload
    def record_annealer_trajectory(self, setting: bool) -> None: ...
    @overload
    def record_annealer_trajectory(self, bool) -> void: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def trajectory_file_name(self, setting: str) -> None: ...
    @overload
    def trajectory_file_name(self, conststd) -> void: ...

class MultiCoolAnnealer(RotamerAssigningAnnealer):
    @overload
    def __init__(self, task, rot_to_pack: pyrosetta.rosetta.utility.vector0_int, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, rotamer_sets, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    @overload
    def __init__(self, task, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, rotamer_sets, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...

class PointDwell:
    dwell: float
    xyz: pyrosetta.rosetta.numeric.xyzVector_double_t
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PointDwell) -> None: ...
    def assign(self) -> PointDwell: ...

class RotSub:
    accept: int
    moltenresid: int
    rotamerid: int
    def __init__(self) -> None: ...

class RotamerAssigningAnnealer(SimAnnealerBase):
    @overload
    def __init__(self, num_of_rot_to_pack: int, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, p_rotamer_set, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    @overload
    def __init__(self, rot_to_pack: pyrosetta.rosetta.utility.vector0_int, num_of_rot_to_pack: int, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, p_rotamer_set, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    @overload
    def pick_a_rotamer(self, cycle: int) -> int: ...
    @overload
    def pick_a_rotamer(self, int) -> int: ...
    @overload
    def pick_a_rotamer_for_node(self, node: int) -> int: ...
    @overload
    def pick_a_rotamer_for_node(self, int) -> int: ...
    @overload
    def set_assign_state_to_all_nodes_immediately(self, setting: bool) -> None: ...
    @overload
    def set_assign_state_to_all_nodes_immediately(self, bool) -> void: ...

class SeqSymmAnnealerSetup:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SeqSymmAnnealerSetup) -> None: ...
    @property
    def common_res_types(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_std_unordered_set_std_string_t: ...
    @property
    def corresponding_mress_for_mres(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t: ...

class SequenceSymmetricAnnealer(RotamerAssigningAnnealer):
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, rot_to_pack: pyrosetta.rosetta.utility.vector0_int, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, rotamer_sets, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t, rs_prefix: str) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, rotamer_sets, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t, rs_prefix: str) -> None: ...
    def create_corresponding_mress_for_mres(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_unsigned_long_t: ...
    @overload
    def record_annealer_trajectory(self, setting: bool) -> None: ...
    @overload
    def record_annealer_trajectory(self, bool) -> void: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def trajectory_file_name(self, setting: str) -> None: ...
    @overload
    def trajectory_file_name(self, conststd) -> void: ...

class SimAnnealerBase:
    def __init__(self, num_rots_to_pack: int, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    def get_annealer_observer(self) -> AnnealerObserver: ...
    @overload
    def get_calc_rot_freq(self) -> bool: ...
    @overload
    def get_calc_rot_freq(self) -> bool: ...
    @overload
    def get_inneriterations(self) -> int: ...
    @overload
    def get_inneriterations(self) -> int: ...
    @overload
    def get_outeriterations(self) -> int: ...
    @overload
    def get_outeriterations(self) -> int: ...
    @overload
    def get_start_with_current(self) -> bool: ...
    @overload
    def get_start_with_current(self) -> bool: ...
    @overload
    def get_temperature(self) -> float: ...
    @overload
    def get_temperature(self) -> float: ...
    @overload
    def pass_metropolis(self, delta_energy: float) -> bool: ...
    @overload
    def pass_metropolis(self, float) -> bool: ...
    @overload
    def pass_metropolis(self, previous_energy: float, delta_energy: float) -> bool: ...
    @overload
    def quench(self) -> bool: ...
    @overload
    def quench(self) -> bool: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def scale_inneriterations(self, si: float) -> None: ...
    @overload
    def scale_inneriterations(self, constfloat) -> void: ...
    @overload
    def scale_outeriterations(self, so: float) -> None: ...
    @overload
    def scale_outeriterations(self, constfloat) -> void: ...
    @overload
    def set_annealer_observer(self, obs: AnnealerObserver) -> None: ...
    @overload
    def set_annealer_observer(self, classstd) -> void: ...
    def set_disallow_quench(self, setting: bool) -> None: ...
    @overload
    def set_hightemp(self) -> None: ...
    @overload
    def set_hightemp(self, float) -> void: ...
    @overload
    def set_lowtemp(self) -> None: ...
    @overload
    def set_lowtemp(self, float) -> void: ...
    @overload
    def set_not_to_quench(self) -> None: ...
    @overload
    def set_not_to_quench(self) -> void: ...
    @overload
    def set_temperature(self, new_temperature: float) -> None: ...
    @overload
    def set_temperature(self, float) -> void: ...
    @overload
    def set_to_quench(self) -> None: ...
    @overload
    def set_to_quench(self) -> void: ...
    @overload
    def setup_iterations(self) -> None: ...
    @overload
    def setup_iterations(self) -> void: ...
    @overload
    def setup_iterations(self, num_of_state_changes: int) -> None: ...
    @overload
    def setup_temperature(self, nn: int) -> None: ...
    @overload
    def setup_temperature(self, loopenergy: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t, nn: int) -> None: ...
    @overload
    def setup_temperature(self, constclassObjexxFCL, int) -> void: ...

class SmartFixbbSimAnnealer(RotamerAssigningAnnealer):
    @overload
    def __init__(self, rot_to_pack: pyrosetta.rosetta.utility.vector0_int, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, rotamer_sets, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    @overload
    def __init__(self, bestrotamer_at_seqpos: pyrosetta.rosetta.ObjexxFCL.FArray1D_int_t, bestenergy: float, start_with_current: bool, ig, rotamer_sets, current_rot_index: pyrosetta.rosetta.ObjexxFCL.FArray1_int_t, calc_rot_freq: bool, rot_freq: pyrosetta.rosetta.ObjexxFCL.FArray1D_float_t) -> None: ...
    @overload
    def initialize_from_task(self, task) -> None: ...
    @overload
    def initialize_from_task(self, constclasscore) -> void: ...
    @overload
    def perform_validation_test(self) -> None: ...
    @overload
    def perform_validation_test(self) -> void: ...
    @overload
    def record_annealer_trajectory(self, setting: bool) -> None: ...
    @overload
    def record_annealer_trajectory(self, bool) -> void: ...
    @overload
    def run(self) -> None: ...
    @overload
    def run(self) -> void: ...
    @overload
    def trajectory_file_name(self, setting: str) -> None: ...
    @overload
    def trajectory_file_name(self, conststd) -> void: ...
