import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.scoring.methods
import pyrosetta.rosetta.utility
from typing import overload

class DFIRE_Energy(pyrosetta.rosetta.core.scoring.methods.ContextIndependentLRTwoBodyEnergy):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DFIRE_Energy) -> None: ...
    @overload
    def __init__(self, arg0: DFIRE_Energy) -> None: ...
    def assign(self) -> DFIRE_Energy: ...
    def clone(self) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    @overload
    def defines_intrares_energy(self) -> bool: ...
    @overload
    def defines_intrares_energy(self, constclasscore) -> bool: ...
    def defines_residue_pair_energy(self, pose, res1: int, res2: int) -> bool: ...
    def eval_intrares_energy(self, rsd: pyrosetta.rosetta.core.conformation.Residue, pose, sfxn, emap) -> None: ...
    @overload
    def indicate_required_context_graphs(self) -> None: ...
    @overload
    def indicate_required_context_graphs(self, classutility) -> void: ...
    def long_range_type(self) -> pyrosetta.rosetta.core.scoring.methods.LongRangeEnergyType: ...
    def residue_energy(self, rsd: pyrosetta.rosetta.core.conformation.Residue, pose, emap) -> None: ...
    def residue_pair_energy(self, rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, pose, sfxn, emap) -> None: ...
    @overload
    def setup_for_scoring(self, pose) -> None: ...
    @overload
    def setup_for_scoring(self, classcore, constclasscore) -> void: ...

class DFIRE_EnergyCreator(pyrosetta.rosetta.core.scoring.methods.EnergyMethodCreator):
    def __init__(self) -> None: ...
    def assign(self) -> DFIRE_EnergyCreator: ...
    def create_energy_method(self) -> pyrosetta.rosetta.core.scoring.methods.EnergyMethod: ...
    def score_types_for_method(self) -> pyrosetta.rosetta.utility.vector1_core_scoring_ScoreType: ...
