import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pack.task.operation
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.protocols.filters
import pyrosetta.rosetta.protocols.loops
import pyrosetta.rosetta.protocols.minimization_packing
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.protocols.rigid
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from . import membrane as membrane, stateless as stateless
from typing import Any, ClassVar, overload

class ConformerSwitchMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0) -> None: ...
    @overload
    def __init__(self, ensemble, random_conformer: bool) -> None: ...
    @overload
    def __init__(self, arg0: ConformerSwitchMover) -> None: ...
    @overload
    def __init__(self, arg0: ConformerSwitchMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> ConformerSwitchMover: ...
    def get_ensemble(self, *args, **kwargs): ...
    def get_name(self) -> str: ...
    @overload
    def get_temperature(self) -> float: ...
    @overload
    def get_temperature(self) -> double: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_random_confomer(self, rand: bool) -> None: ...
    @overload
    def set_random_confomer(self, bool) -> void: ...
    @overload
    def set_specific_conformer(self, conformer_num_in: int) -> None: ...
    @overload
    def set_specific_conformer(self, unsignedlong) -> void: ...
    @overload
    def set_temperature(self, temp_in: float) -> None: ...
    @overload
    def set_temperature(self, double) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def switch_conformer(self, pose: pyrosetta.rosetta.core.pose.Pose, conf_num: int) -> None: ...
    @overload
    def switch_conformer(self, classcore, unsignedlong) -> void: ...
    @overload
    def use_random_conformer(self) -> bool: ...
    @overload
    def use_random_conformer(self) -> bool: ...

class ConformerSwitchMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ConformerSwitchMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: ConformerSwitchMoverCreator) -> None: ...
    def assign(self) -> ConformerSwitchMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class DHR_Type:
    __members__: ClassVar[dict] = ...  # read-only
    DockMCMProtocol: ClassVar[DHR_Type] = ...
    DockMinMover: ClassVar[DHR_Type] = ...
    DockingHighResLegacy: ClassVar[DHR_Type] = ...
    DockingPrepackProtocol: ClassVar[DHR_Type] = ...
    SnugDock: ClassVar[DHR_Type] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class DockMCMCycle(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rb_jump: int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, rb_jump: int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, scorefxn_pack: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, movable_jumps: pyrosetta.rosetta.utility.vector1_int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, scorefxn_pack: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: DockMCMCycle) -> None: ...
    @overload
    def __init__(self, arg0: DockMCMCycle) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> DockMCMCycle: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_mc(self) -> pyrosetta.rosetta.protocols.moves.MonteCarlo: ...
    def get_name(self) -> str: ...
    @overload
    def init_mc(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def init_mc(self, classcore) -> void: ...
    def movable_jumps(self) -> pyrosetta.rosetta.utility.vector1_int: ...
    @overload
    def reset_cycle_index(self) -> None: ...
    @overload
    def reset_cycle_index(self) -> void: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_min_type(self, min_type: str) -> None: ...
    @overload
    def set_min_type(self, std) -> void: ...
    @overload
    def set_move_map(self, movemap: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def set_move_map(self, classstd) -> void: ...
    @overload
    def set_rot_magnitude(self, value: float) -> None: ...
    @overload
    def set_rot_magnitude(self, double) -> void: ...
    @overload
    def set_rtmin(self, setting: bool) -> None: ...
    @overload
    def set_rtmin(self, bool) -> void: ...
    @overload
    def set_scmin(self, setting: bool) -> None: ...
    @overload
    def set_scmin(self, bool) -> void: ...
    @overload
    def set_task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class DockMCMProtocol(DockingHighRes):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rb_jump: int) -> None: ...
    @overload
    def __init__(self, rb_jump: int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, scorefxn_pack: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, movable_jumps: pyrosetta.rosetta.utility.vector1_int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, movable_jumps: pyrosetta.rosetta.utility.vector1_int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, scorefxn_pack: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: DockMCMProtocol) -> None: ...
    @overload
    def __init__(self, arg0: DockMCMProtocol) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> DockMCMProtocol: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def init(self) -> None: ...
    @overload
    def init(self) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def scorefxn_docking(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    def scorefxn_packing(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def set_filter(self, filter: DockingHighResFilter) -> None: ...
    @overload
    def set_filter(self, classstd) -> void: ...
    def set_first_cycle(self, num: int) -> None: ...
    @overload
    def set_move_map(self, movemap: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def set_move_map(self, classstd) -> void: ...
    def set_second_cycle(self, num: int) -> None: ...

class DockMCMProtocolCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DockMCMProtocolCreator) -> None: ...
    @overload
    def __init__(self, arg0: DockMCMProtocolCreator) -> None: ...
    def assign(self) -> DockMCMProtocolCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class DockMinMover(DockingHighRes):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, movable_jumps: pyrosetta.rosetta.utility.vector1_int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, movable_jumps: pyrosetta.rosetta.utility.vector1_int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, mc: pyrosetta.rosetta.protocols.moves.MonteCarlo) -> None: ...
    @overload
    def __init__(self, movable_jumps: pyrosetta.rosetta.utility.vector1_int, movemap: pyrosetta.rosetta.core.kinematics.MoveMap, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, min_type: str, min_tolerance: float, nb_list: bool, mc: pyrosetta.rosetta.protocols.moves.MonteCarlo) -> None: ...
    @overload
    def __init__(self, arg0: DockMinMover) -> None: ...
    @overload
    def __init__(self, arg0: DockMinMover) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> DockMinMover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_min_tolerance(self, min_tolerance: float) -> None: ...
    @overload
    def set_min_tolerance(self, double) -> void: ...
    @overload
    def set_min_type(self, min_type: str) -> None: ...
    @overload
    def set_min_type(self, std) -> void: ...

class DockMinMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DockMinMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: DockMinMoverCreator) -> None: ...
    def assign(self) -> DockMinMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class DockSetupMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DockSetupMover) -> None: ...
    @overload
    def __init__(self, arg0: DockSetupMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self, rhs: DockSetupMover) -> DockSetupMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    def partners(self) -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...
    @overload
    def set_partners(self, setting: str) -> None: ...
    @overload
    def set_partners(self, conststd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class DockSetupMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DockSetupMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: DockSetupMoverCreator) -> None: ...
    def assign(self) -> DockSetupMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class DockTaskFactory:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DockTaskFactory) -> None: ...
    @overload
    def add_additional_task_operaration(self, task_operation: pyrosetta.rosetta.core.pack.task.operation.TaskOperation) -> None: ...
    @overload
    def add_additional_task_operaration(self, classstd) -> void: ...
    def assign(self) -> DockTaskFactory: ...
    @overload
    def create_and_attach_task_factory(self, docker: DockingHighRes, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def create_and_attach_task_factory(self, classprotocols, constclasscore) -> void: ...
    def get_additional_task_operarations(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_operation_TaskOperation_t: ...
    @overload
    def get_norepack1(self) -> bool: ...
    @overload
    def get_norepack1(self) -> bool: ...
    @overload
    def get_norepack2(self) -> bool: ...
    @overload
    def get_norepack2(self) -> bool: ...
    @overload
    def init_from_options(self) -> None: ...
    @overload
    def init_from_options(self) -> void: ...
    @overload
    def register_options(self) -> None: ...
    @overload
    def register_options(self) -> void: ...
    @overload
    def set_additional_task_operarations(self, additional_task_operations: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_operation_TaskOperation_t) -> None: ...
    @overload
    def set_additional_task_operarations(self, classutility) -> void: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_design_chains(self, design_chains: pyrosetta.rosetta.utility.vector1_char) -> None: ...
    @overload
    def set_design_chains(self, classutility) -> void: ...
    @overload
    def set_interface_definition_task_operation(self, interface_definition) -> None: ...
    @overload
    def set_interface_definition_task_operation(self, classstd) -> void: ...
    @overload
    def set_norepack1(self, norepack1: bool) -> None: ...
    @overload
    def set_norepack1(self, bool) -> void: ...
    @overload
    def set_norepack2(self, norepack2: bool) -> None: ...
    @overload
    def set_norepack2(self, bool) -> void: ...
    @overload
    def set_prepack_only(self, prepack_only: bool) -> None: ...
    @overload
    def set_prepack_only(self, bool) -> void: ...

class DockingEnsemble:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, start_res: int, end_res: int, jump_id: int, ensemble_file_path: str, partner: str, scorefxn_low: pyrosetta.rosetta.core.scoring.ScoreFunction, scorefxn_high: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: DockingEnsemble) -> None: ...
    def assign(self) -> DockingEnsemble: ...
    @overload
    def calculate_highres_ref_energy(self, conf_num: int) -> None: ...
    @overload
    def calculate_highres_ref_energy(self, unsignedlong) -> void: ...
    @overload
    def calculate_highres_ref_energy(self, pose: pyrosetta.rosetta.core.pose.Pose, partner_num: str) -> None: ...
    @overload
    def calculate_highres_ref_energy(self, classcore, std) -> void: ...
    @overload
    def calculate_lowres_ref_energy(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def calculate_lowres_ref_energy(self, classcore) -> void: ...
    @overload
    def conf_size(self) -> int: ...
    @overload
    def conf_size(self) -> unsignedlong: ...
    @overload
    def end_res(self) -> int: ...
    @overload
    def end_res(self) -> unsignedlong: ...
    def get_conformer(self, conf_num: int) -> pyrosetta.rosetta.core.pose.Pose: ...
    def get_conformer_cen(self, conf_num: int) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    def get_current_confnum(self) -> int: ...
    @overload
    def get_current_confnum(self) -> unsignedlong: ...
    @overload
    def highres_reference_energy(self, conf_num: int) -> float: ...
    @overload
    def highres_reference_energy(self, unsignedlong) -> double: ...
    @overload
    def highres_reference_energy(self) -> float: ...
    @overload
    def highres_reference_energy(self) -> double: ...
    @overload
    def jump_id(self) -> int: ...
    @overload
    def jump_id(self) -> unsignedlong: ...
    @overload
    def lowres_reference_energy(self, conf_num: int) -> float: ...
    @overload
    def lowres_reference_energy(self, unsignedlong) -> double: ...
    @overload
    def lowres_reference_energy(self) -> float: ...
    @overload
    def lowres_reference_energy(self) -> double: ...
    def partner(self) -> str: ...
    @overload
    def recover_and_pack_conformer_sidechains(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def recover_and_pack_conformer_sidechains(self, classcore) -> void: ...
    def scorefxn_low(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def set_current_confnum(self, conf_num: int) -> None: ...
    @overload
    def set_current_confnum(self, unsignedlong) -> void: ...
    @overload
    def set_packer(self, packer) -> None: ...
    @overload
    def set_packer(self, classstd) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def start_res(self) -> int: ...
    @overload
    def start_res(self) -> unsignedlong: ...
    @overload
    def update_pdblist_file(self, partner_num: str) -> None: ...
    @overload
    def update_pdblist_file(self, std) -> void: ...

class DockingEnsemblePrepackProtocol(DockingHighRes):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DockingEnsemblePrepackProtocol) -> None: ...
    @overload
    def __init__(self, arg0: DockingEnsemblePrepackProtocol) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> DockingEnsemblePrepackProtocol: ...
    @overload
    def check_ensemble_member_compatibility(self) -> None: ...
    @overload
    def check_ensemble_member_compatibility(self) -> void: ...
    def get_name(self) -> str: ...
    def get_pose_chains(self) -> pyrosetta.rosetta.utility.vector1_char: ...
    @overload
    def move_away(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def move_away(self, classcore) -> void: ...
    @overload
    def move_back(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def move_back(self, classcore) -> void: ...
    @overload
    def set_ensemble1(self, ensemble1: str) -> None: ...
    @overload
    def set_ensemble1(self, conststd) -> void: ...
    @overload
    def set_ensemble2(self, ensemble2: str) -> None: ...
    @overload
    def set_ensemble2(self, conststd) -> void: ...
    @overload
    def set_spanfile1(self, spanfile1: str) -> None: ...
    @overload
    def set_spanfile1(self, conststd) -> void: ...
    @overload
    def set_spanfile2(self, spanfile2: str) -> None: ...
    @overload
    def set_spanfile2(self, conststd) -> void: ...
    @overload
    def setup_defaults(self) -> None: ...
    @overload
    def setup_defaults(self) -> void: ...
    @overload
    def setup_pack_operation_movers(self) -> None: ...
    @overload
    def setup_pack_operation_movers(self) -> void: ...

class DockingHighRes(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rb_jump: int) -> None: ...
    @overload
    def __init__(self, rb_jump: int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, rb_jump: int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, scorefxn_pack: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, movable_jumps: pyrosetta.rosetta.utility.vector1_int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, scorefxn_pack: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: DockingHighRes) -> None: ...
    @overload
    def add_additional_task_operaration(self, task_operation: pyrosetta.rosetta.core.pack.task.operation.TaskOperation) -> None: ...
    @overload
    def add_additional_task_operaration(self, classstd) -> void: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> DockingHighRes: ...
    def get_additional_task_operarations(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_operation_TaskOperation_t: ...
    def get_name(self) -> str: ...
    def get_partners(self) -> str: ...
    @overload
    def ignore_default_task(self) -> bool: ...
    @overload
    def ignore_default_task(self) -> bool: ...
    def movable_jumps(self) -> pyrosetta.rosetta.utility.vector1_int: ...
    def partners(self) -> str: ...
    @overload
    def rt_min(self) -> bool: ...
    @overload
    def rt_min(self) -> bool: ...
    @overload
    def sc_min(self) -> bool: ...
    @overload
    def sc_min(self) -> bool: ...
    def scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    def scorefxn_pack(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def set_additional_task_operarations(self, additional_task_operations: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_operation_TaskOperation_t) -> None: ...
    @overload
    def set_additional_task_operarations(self, classutility) -> void: ...
    @overload
    def set_ignore_default_task(self, ignore_default_task: bool) -> None: ...
    @overload
    def set_ignore_default_task(self, bool) -> void: ...
    @overload
    def set_interface_definition_task_operation(self, interface_definition) -> None: ...
    @overload
    def set_interface_definition_task_operation(self, classstd) -> void: ...
    @overload
    def set_movable_jumps(self, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> None: ...
    @overload
    def set_movable_jumps(self, classutility) -> void: ...
    @overload
    def set_partners(self, partners: str) -> None: ...
    @overload
    def set_partners(self, std) -> void: ...
    @overload
    def set_rt_min(self, rt_min: bool) -> None: ...
    @overload
    def set_rt_min(self, bool) -> void: ...
    @overload
    def set_sc_min(self, sc_min: bool) -> None: ...
    @overload
    def set_sc_min(self, bool) -> void: ...
    @overload
    def set_scorefxn(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn(self, classstd) -> void: ...
    @overload
    def set_scorefxn_pack(self, scorefxn_pack: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn_pack(self, classstd) -> void: ...
    @overload
    def set_task_factory(self, tf: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...
    def task_factory(self) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...

class DockingHighResFactory(pyrosetta.rosetta.utility.SingletonBase_protocols_docking_DockingHighResFactory_t):
    def __init__(self, *args, **kwargs) -> None: ...
    def create_docking_high_res_mover(self, type_name: DHR_Type) -> DockingHighRes: ...

class DockingHighResFilter(pyrosetta.rosetta.protocols.filters.Filter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DockingHighResFilter) -> None: ...
    @overload
    def __init__(self, arg0: DockingHighResFilter) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def apply(self, constclasscore) -> bool: ...
    def clone(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    @overload
    def set_moveable_jumps(self, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> None: ...
    @overload
    def set_moveable_jumps(self, constclassutility) -> void: ...
    @overload
    def set_score_cutoff(self, new_cutoff: float) -> None: ...
    @overload
    def set_score_cutoff(self, double) -> void: ...
    @overload
    def set_score_margin(self, new_score_margin: float) -> None: ...
    @overload
    def set_score_margin(self, double) -> void: ...
    @overload
    def set_scorefunction(self, scorefunction: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefunction(self, constclassstd) -> void: ...

class DockingHighResLegacy(DockingHighRes):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rb_jump: int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, rb_jump: int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, scorefxn_pack: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, movable_jumps: pyrosetta.rosetta.utility.vector1_int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, scorefxn_pack: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: DockingHighResLegacy) -> None: ...
    @overload
    def __init__(self, arg0: DockingHighResLegacy) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> DockingHighResLegacy: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def define_loops(self, pose: pyrosetta.rosetta.core.pose.Pose, loop_set: pyrosetta.rosetta.protocols.loops.Loops, interface_dist: float) -> None: ...
    @overload
    def design(self, des: bool) -> None: ...
    @overload
    def design(self, constbool) -> void: ...
    @overload
    def design(self) -> bool: ...
    @overload
    def design(self) -> bool: ...
    def get_mc(self) -> pyrosetta.rosetta.protocols.moves.MonteCarlo: ...
    def get_name(self) -> str: ...
    @overload
    def get_rot_magnitude(self) -> float: ...
    @overload
    def get_rot_magnitude(self) -> double: ...
    @overload
    def get_trans_magnitude(self) -> float: ...
    @overload
    def get_trans_magnitude(self) -> double: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def rt_min(self) -> bool: ...
    @overload
    def rt_min(self) -> bool: ...
    @overload
    def sc_min(self) -> bool: ...
    @overload
    def sc_min(self) -> bool: ...
    @overload
    def set_default(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_default(self, classcore) -> void: ...
    @overload
    def set_dock_mcm_protocol(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_dock_mcm_protocol(self, classcore) -> void: ...
    @overload
    def set_dock_min_protocol(self) -> None: ...
    @overload
    def set_dock_min_protocol(self) -> void: ...
    @overload
    def set_dock_ppk_protocol(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_dock_ppk_protocol(self, classcore) -> void: ...
    @overload
    def set_min_type(self, min_type_in: str) -> None: ...
    @overload
    def set_min_type(self, std) -> void: ...
    @overload
    def set_move_map(self, movemap_in: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def set_move_map(self, classstd) -> void: ...
    @overload
    def set_protocol(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_protocol(self, classcore) -> void: ...
    @overload
    def set_repack(self, repack_switch: bool) -> None: ...
    @overload
    def set_repack(self, bool) -> void: ...
    @overload
    def set_rot_magnitude(self, rot_magnitude: float) -> None: ...
    @overload
    def set_rot_magnitude(self, double) -> void: ...
    @overload
    def set_rt_min(self, rt_min: bool) -> None: ...
    @overload
    def set_rt_min(self, bool) -> void: ...
    @overload
    def set_sc_min(self, sc_min: bool) -> None: ...
    @overload
    def set_sc_min(self, bool) -> void: ...
    @overload
    def set_task_factory(self, task: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...
    @overload
    def set_trans_magnitude(self, trans_magnitude: float) -> None: ...
    @overload
    def set_trans_magnitude(self, double) -> void: ...

class DockingHighResLegacyCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DockingHighResLegacyCreator) -> None: ...
    @overload
    def __init__(self, arg0: DockingHighResLegacyCreator) -> None: ...
    def assign(self) -> DockingHighResLegacyCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class DockingInitialPerturbation(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, rb_jump: int, slide: bool) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.utility.vector1_int) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.utility.vector1_int, arg1: bool) -> None: ...
    @overload
    def __init__(self, movable_jumps: pyrosetta.rosetta.utility.vector1_int, slide: bool, autofoldtree: bool) -> None: ...
    @overload
    def __init__(self, arg0: DockingInitialPerturbation) -> None: ...
    @overload
    def __init__(self, arg0: DockingInitialPerturbation) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    @overload
    def apply_body(self, pose: pyrosetta.rosetta.core.pose.Pose, jump_number: int) -> None: ...
    @overload
    def apply_body(self, classcore, unsignedlong) -> void: ...
    def assign(self) -> DockingInitialPerturbation: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def init(self) -> None: ...
    @overload
    def init(self) -> void: ...
    @overload
    def init_from_options(self) -> None: ...
    @overload
    def init_from_options(self) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def or_randomize2(self, randomize2: bool) -> None: ...
    @overload
    def or_randomize2(self, bool) -> void: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    @staticmethod
    def register_options() -> None: ...
    @overload
    @staticmethod
    def register_options() -> void: ...
    @overload
    def set_center(self, center: bool) -> None: ...
    @overload
    def set_center(self, bool) -> void: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_dock_pert(self, dock_pert: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_dock_pert(self, constclassutility) -> void: ...
    @overload
    def set_randomize1(self, randomize1: bool) -> None: ...
    @overload
    def set_randomize1(self, bool) -> void: ...
    @overload
    def set_randomize2(self, randomize2: bool) -> None: ...
    @overload
    def set_randomize2(self, bool) -> void: ...
    @overload
    def set_spin(self, spin: bool) -> None: ...
    @overload
    def set_spin(self, bool) -> void: ...
    @overload
    def set_tilt(self, tilt: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_tilt(self, constclassutility) -> void: ...
    @overload
    def set_tilt1_center(self, tilt_center: str) -> None: ...
    @overload
    def set_tilt1_center(self, conststd) -> void: ...
    @overload
    def set_tilt2_center(self, tilt_center: str) -> None: ...
    @overload
    def set_tilt2_center(self, conststd) -> void: ...
    @overload
    def set_uniform_trans(self, uniform_trans: float) -> None: ...
    @overload
    def set_uniform_trans(self, double) -> void: ...
    @overload
    def set_use_ellipsoidal_randomization(self, use_ellipsoidal_randomization: bool) -> None: ...
    @overload
    def set_use_ellipsoidal_randomization(self, bool) -> void: ...

class DockingInitialPerturbationCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DockingInitialPerturbationCreator) -> None: ...
    @overload
    def __init__(self, arg0: DockingInitialPerturbationCreator) -> None: ...
    def assign(self) -> DockingInitialPerturbationCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class DockingLowRes(pyrosetta.rosetta.protocols.moves.Mover):
    first_apply_with_current_setup_: bool
    flags_and_objects_are_in_sync_: bool
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, rb_jump: int) -> None: ...
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> None: ...
    @overload
    def __init__(self, arg0: DockingLowRes) -> None: ...
    @overload
    def __init__(self, arg0: DockingLowRes) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> DockingLowRes: ...
    @overload
    def calc_accept_rate(self) -> None: ...
    @overload
    def calc_accept_rate(self) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def get_accept_rate(self) -> float: ...
    @overload
    def get_accept_rate(self) -> double: ...
    @overload
    def get_current_conformer_ensemble1(self) -> int: ...
    @overload
    def get_current_conformer_ensemble1(self) -> unsignedlong: ...
    @overload
    def get_current_conformer_ensemble2(self) -> int: ...
    @overload
    def get_current_conformer_ensemble2(self) -> unsignedlong: ...
    @overload
    def get_inner_cycles(self) -> int: ...
    @overload
    def get_inner_cycles(self) -> unsignedlong: ...
    def get_mc(self) -> pyrosetta.rosetta.protocols.moves.MonteCarlo: ...
    def get_movable_jumps(self) -> pyrosetta.rosetta.utility.vector1_int: ...
    def get_name(self) -> str: ...
    @overload
    def get_outer_cycles(self) -> int: ...
    @overload
    def get_outer_cycles(self) -> unsignedlong: ...
    def get_pymol_mover(self, *args, **kwargs): ...
    def get_rb_mover(self) -> pyrosetta.rosetta.protocols.rigid.RigidBodyPerturbNoCenterMover: ...
    def get_rb_seq(self) -> pyrosetta.rosetta.protocols.moves.SequenceMover: ...
    def get_rb_trial(self, *args, **kwargs): ...
    @overload
    def get_rot_magnitude(self) -> float: ...
    @overload
    def get_rot_magnitude(self) -> double: ...
    def get_scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def get_temperature(self) -> float: ...
    @overload
    def get_temperature(self) -> double: ...
    @overload
    def get_trans_magnitude(self) -> float: ...
    @overload
    def get_trans_magnitude(self) -> double: ...
    @overload
    def get_view_in_pymol(self) -> bool: ...
    @overload
    def get_view_in_pymol(self) -> bool: ...
    @overload
    def lowres_inner_cycle(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def lowres_inner_cycle(self, classcore) -> void: ...
    @overload
    def pymol_color_change(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def pymol_color_change(self, classcore) -> void: ...
    @overload
    def reset_rb_trial_counters(self) -> None: ...
    @overload
    def reset_rb_trial_counters(self) -> void: ...
    @overload
    def rigid_body_trial(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def rigid_body_trial(self, classcore) -> void: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_inner_cycles(self, inner_cycles: int) -> None: ...
    @overload
    def set_inner_cycles(self, unsignedlong) -> void: ...
    @overload
    def set_outer_cycles(self, outer_cycles: int) -> None: ...
    @overload
    def set_outer_cycles(self, unsignedlong) -> void: ...
    @overload
    def set_rb_trial(self, rb_trial_in) -> None: ...
    @overload
    def set_rb_trial(self, classstd) -> void: ...
    @overload
    def set_rot_magnitude(self, rot_magnitude: float) -> None: ...
    @overload
    def set_rot_magnitude(self, double) -> void: ...
    @overload
    def set_scorefxn(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_scorefxn(self, classstd) -> void: ...
    @overload
    def set_trans_magnitude(self, trans_magnitude: float) -> None: ...
    @overload
    def set_trans_magnitude(self, double) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def sync_magnitudes_with_flags(self) -> None: ...
    @overload
    def sync_magnitudes_with_flags(self) -> void: ...
    @overload
    def sync_objects_with_flags(self) -> None: ...
    @overload
    def sync_objects_with_flags(self) -> void: ...

class DockingLowResEnsemble(DockingLowRes):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> None: ...
    @overload
    def __init__(self, arg0: DockingLowResEnsemble) -> None: ...
    @overload
    def __init__(self, arg0: DockingLowResEnsemble) -> None: ...
    @overload
    def adaptive_inner_cycle(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def adaptive_inner_cycle(self, classcore) -> void: ...
    def assign(self) -> DockingLowResEnsemble: ...
    @overload
    def calc_ensemble_accept_rate_(self) -> None: ...
    @overload
    def calc_ensemble_accept_rate_(self) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def ensemble_defaults(self) -> None: ...
    @overload
    def ensemble_defaults(self) -> void: ...
    @overload
    def get_current_conformer_ensemble1(self) -> int: ...
    @overload
    def get_current_conformer_ensemble1(self) -> unsignedlong: ...
    @overload
    def get_current_conformer_ensemble2(self) -> int: ...
    @overload
    def get_current_conformer_ensemble2(self) -> unsignedlong: ...
    @overload
    def initialize_movers(self) -> None: ...
    @overload
    def initialize_movers(self) -> void: ...
    @overload
    def lowres_inner_cycle(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def lowres_inner_cycle(self, classcore) -> void: ...
    @overload
    def reset_ensemble_trial_counters(self) -> None: ...
    @overload
    def reset_ensemble_trial_counters(self) -> void: ...
    @overload
    def set_ensemble1(self, ensemble1: DockingEnsemble) -> None: ...
    @overload
    def set_ensemble1(self, classstd) -> void: ...
    @overload
    def set_ensemble2(self, ensemble2: DockingEnsemble) -> None: ...
    @overload
    def set_ensemble2(self, classstd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def try_all_conformers(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def try_all_conformers(self, classcore) -> void: ...

class DockingLowResFilter(pyrosetta.rosetta.protocols.filters.Filter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DockingLowResFilter) -> None: ...
    @overload
    def __init__(self, arg0: DockingLowResFilter) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def apply(self, constclasscore) -> bool: ...
    def clone(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    @overload
    def report(self, out: pyrosetta.rosetta.std.ostream, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def report(self, std, constclasscore) -> void: ...
    @overload
    def set_use_constraints(self, flag: bool) -> None: ...
    @overload
    def set_use_constraints(self, flag: bool, cutoff: float) -> None: ...
    @overload
    def set_use_constraints(self, bool, double) -> void: ...

class DockingPrepackProtocol(DockingHighRes):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DockingPrepackProtocol) -> None: ...
    @overload
    def __init__(self, arg0: DockingPrepackProtocol) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> DockingPrepackProtocol: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def score_and_output(self, filename: str) -> None: ...
    @overload
    def score_and_output(self, std, classcore) -> void: ...
    @overload
    def set_dock_ppk(self, dock_ppk: bool) -> None: ...
    @overload
    def set_dock_ppk(self, bool) -> void: ...
    @overload
    def setup_defaults(self) -> None: ...
    @overload
    def setup_defaults(self) -> void: ...
    @overload
    def setup_pack_operation_movers(self) -> None: ...
    @overload
    def setup_pack_operation_movers(self) -> void: ...

class DockingPrepackProtocolCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DockingPrepackProtocolCreator) -> None: ...
    @overload
    def __init__(self, arg0: DockingPrepackProtocolCreator) -> None: ...
    def assign(self) -> DockingPrepackProtocolCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class DockingProtocol(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: bool) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: bool, arg2: bool) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: bool, arg2: bool, arg3: bool) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: bool, arg2: bool, arg3: bool, arg4: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, rb_jump_in: int, low_res_protocol_only: bool, docking_local_refine: bool, autofoldtree: bool, docking_score_low: pyrosetta.rosetta.core.scoring.ScoreFunction, docking_score_high: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.utility.vector1_int) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.utility.vector1_int, arg1: bool) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.utility.vector1_int, arg1: bool, arg2: bool) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.utility.vector1_int, arg1: bool, arg2: bool, arg3: bool) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.utility.vector1_int, arg1: bool, arg2: bool, arg3: bool, arg4: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, movable_jumps: pyrosetta.rosetta.utility.vector1_int, low_res_protocol_only: bool, docking_local_refine: bool, autofoldtree: bool, docking_score_low: pyrosetta.rosetta.core.scoring.ScoreFunction, docking_score_high: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: DockingProtocol) -> None: ...
    @overload
    def __init__(self, arg0: DockingProtocol) -> None: ...
    @overload
    def add_additional_low_resolution_step(self, additional_low_resolution_mover: pyrosetta.rosetta.protocols.moves.Mover) -> None: ...
    @overload
    def add_additional_low_resolution_step(self, classstd) -> void: ...
    @overload
    def add_additional_task_operaration(self, task_operation: pyrosetta.rosetta.core.pack.task.operation.TaskOperation) -> None: ...
    @overload
    def add_additional_task_operaration(self, classstd) -> void: ...
    @overload
    def add_jump(self, jump_number: int) -> None: ...
    @overload
    def add_jump(self, constunsignedlong) -> void: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self, rhs: DockingProtocol) -> DockingProtocol: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def docking_highres_mover(self) -> DockingHighRes: ...
    def docking_lowres_mover(self) -> DockingLowRes: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_additional_task_operarations(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_operation_TaskOperation_t: ...
    def get_highres_scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    def get_name(self) -> str: ...
    def movable_jumps(self) -> pyrosetta.rosetta.utility.vector1_int: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    def partners(self) -> str: ...
    def perturber(self) -> DockingInitialPerturbation: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    @staticmethod
    def register_options() -> None: ...
    @overload
    @staticmethod
    def register_options() -> void: ...
    @overload
    def reinitialize_for_new_input(self) -> bool: ...
    @overload
    def reinitialize_for_new_input(self) -> bool: ...
    @overload
    def set_additional_task_operarations(self, additional_task_operations: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pack_task_operation_TaskOperation_t) -> None: ...
    @overload
    def set_additional_task_operarations(self, classutility) -> void: ...
    @overload
    def set_autofoldtree(self, autofoldtree: bool) -> None: ...
    @overload
    def set_autofoldtree(self, constbool) -> void: ...
    @overload
    def set_cst_weight(self, cst_weight: float) -> None: ...
    @overload
    def set_cst_weight(self, constdouble) -> void: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_design(self, design: bool) -> None: ...
    @overload
    def set_design(self, constbool) -> void: ...
    @overload
    def set_dock_min(self, dock_min: bool) -> None: ...
    @overload
    def set_dock_min(self, constbool) -> void: ...
    @overload
    def set_docking_highres_mover(self, docking_highres_mover: DockingHighRes) -> None: ...
    @overload
    def set_docking_highres_mover(self, classstd) -> void: ...
    @overload
    def set_docking_local_refine(self, docking_local_refine: bool) -> None: ...
    @overload
    def set_docking_local_refine(self, constbool) -> void: ...
    @overload
    def set_ensemble1(self, ensemble1: str) -> None: ...
    @overload
    def set_ensemble1(self, conststd) -> void: ...
    @overload
    def set_ensemble2(self, ensemble2: str) -> None: ...
    @overload
    def set_ensemble2(self, conststd) -> void: ...
    @overload
    def set_highres_scorefxn(self, docking_scorefxn_high: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_highres_scorefxn(self, classstd) -> void: ...
    @overload
    def set_highres_scorefxn(self, docking_scorefxn_high: pyrosetta.rosetta.core.scoring.ScoreFunction, docking_scorefxn_pack: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_highres_scorefxn(self, docking_scorefxn_high: pyrosetta.rosetta.core.scoring.ScoreFunction, docking_scorefxn_pack: pyrosetta.rosetta.core.scoring.ScoreFunction, docking_scorefxn_output: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_ignore_default_docking_task(self, ignore_default_docking_task: bool) -> None: ...
    @overload
    def set_ignore_default_docking_task(self, constbool) -> void: ...
    @overload
    def set_inner_cycles(self, inner_cycles: int) -> None: ...
    @overload
    def set_inner_cycles(self, unsignedlong) -> void: ...
    @overload
    def set_interface_definition_task_operation(self, interface_definition) -> None: ...
    @overload
    def set_interface_definition_task_operation(self, classstd) -> void: ...
    @overload
    def set_low_res_protocol_only(self, low_res_protocol_only: bool) -> None: ...
    @overload
    def set_low_res_protocol_only(self, constbool) -> void: ...
    @overload
    def set_lowres_scorefxn(self, docking_scorefxn_low: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_lowres_scorefxn(self, classstd) -> void: ...
    @overload
    def set_movable_jumps(self, jump_numbers: pyrosetta.rosetta.utility.vector1_int) -> None: ...
    @overload
    def set_movable_jumps(self, constclassutility) -> void: ...
    @overload
    def set_no_filters(self, no_filters: bool) -> None: ...
    @overload
    def set_no_filters(self, bool) -> void: ...
    @overload
    def set_outer_cycles(self, outer_cycles: int) -> None: ...
    @overload
    def set_outer_cycles(self, unsignedlong) -> void: ...
    @overload
    def set_partners(self, partners: str) -> None: ...
    @overload
    def set_partners(self, conststd) -> void: ...
    @overload
    def set_recover_sidechains_filename(self, file: str) -> None: ...
    @overload
    def set_recover_sidechains_filename(self, conststd) -> void: ...
    @overload
    def set_reporting(self, report: bool) -> None: ...
    @overload
    def set_reporting(self, bool) -> void: ...
    @overload
    def set_rt_min(self, rt_min: bool) -> None: ...
    @overload
    def set_rt_min(self, bool) -> void: ...
    @overload
    def set_sc_min(self, sc_min: bool) -> None: ...
    @overload
    def set_sc_min(self, bool) -> void: ...
    @overload
    def set_task_factory(self, task_factory: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def set_task_factory(self, classstd) -> void: ...
    @overload
    def set_use_constraints(self, use_csts: bool) -> None: ...
    @overload
    def set_use_constraints(self, constbool) -> void: ...
    @overload
    def set_use_legacy_protocol(self, use_legacy_protocol: bool) -> None: ...
    @overload
    def set_use_legacy_protocol(self, constbool) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def sync_objects_with_flags(self) -> None: ...
    @overload
    def sync_objects_with_flags(self) -> void: ...
    def task_factory(self) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    def to_all_atom(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def to_centroid(self, *args, **kwargs): ...

class DockingProtocolCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DockingProtocolCreator) -> None: ...
    @overload
    def __init__(self, arg0: DockingProtocolCreator) -> None: ...
    def assign(self) -> DockingProtocolCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class DockingSlideIntoContact(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rb_jump: int) -> None: ...
    @overload
    def __init__(self, rb_jump: int, slide_axis: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def __init__(self, rb_jump: int, slide_axis: pyrosetta.rosetta.numeric.xyzVector_double_t, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, scoretype_for_contact: pyrosetta.rosetta.core.scoring.ScoreType) -> None: ...
    @overload
    def __init__(self, rb_jump: int, slide_axis: pyrosetta.rosetta.numeric.xyzVector_double_t, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, scoretype_for_contact: pyrosetta.rosetta.core.scoring.ScoreType, threshold: float) -> None: ...
    @overload
    def __init__(self, arg0: DockingSlideIntoContact) -> None: ...
    @overload
    def __init__(self, arg0: DockingSlideIntoContact) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> DockingSlideIntoContact: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def get_jump_num(self) -> int: ...
    @overload
    def get_jump_num(self) -> unsignedlong: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_use_delta(self, setting: bool) -> None: ...
    @overload
    def set_use_delta(self, bool) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class DockingSlideIntoContactCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DockingSlideIntoContactCreator) -> None: ...
    @overload
    def __init__(self, arg0: DockingSlideIntoContactCreator) -> None: ...
    def assign(self) -> DockingSlideIntoContactCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class EllipsoidalRandomizationMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rb_jump: int, ellipsoid_is_first_partner: bool, autofoldtree: bool) -> None: ...
    @overload
    def __init__(self, arg0: EllipsoidalRandomizationMover) -> None: ...
    @overload
    def __init__(self, arg0: EllipsoidalRandomizationMover) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> EllipsoidalRandomizationMover: ...
    def calculate_axes(self) -> pyrosetta.rosetta.numeric.xyzMatrix_double_t: ...
    def calculate_geometry(self) -> tuple[pyrosetta.rosetta.numeric.xyzMatrix_double_t, pyrosetta.rosetta.numeric.xyzVector_double_t]: ...
    def calculate_plane_axes(self) -> pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def get_a_axis(self) -> float: ...
    @overload
    def get_a_axis(self) -> double: ...
    @overload
    def get_b_axis(self) -> float: ...
    @overload
    def get_b_axis(self) -> double: ...
    @overload
    def get_c_axis(self) -> float: ...
    @overload
    def get_c_axis(self) -> double: ...
    def get_interface_residues(self, pose_in: pyrosetta.rosetta.core.pose.Pose, interface_distence_cutoff: float, autofoldtree: bool) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def get_name(self) -> str: ...
    def get_nbr_atom_centroid(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def get_nbr_atom_non_ellipsoid_centroid(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def get_normal_to_plane(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def get_partner_residue_start_stop(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def get_random_point_on_ellipsoid(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def get_rotation_matrix(self) -> pyrosetta.rosetta.numeric.xyzMatrix_double_t: ...
    def get_slide_axis(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def get_spin_center(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def init_from_options(self) -> None: ...
    @overload
    def init_from_options(self) -> void: ...
    def inward_normal_to_plane(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def normal_to_ellipsoid(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    def point_on_ellipsoid(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def recalculate_z_coordinate(self) -> float: ...
    @overload
    def recalculate_z_coordinate(self, classnumeric) -> double: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_foldtree(self) -> None: ...
    @overload
    def set_foldtree(self, classcore) -> void: ...
    @overload
    def set_partners(self) -> None: ...
    @overload
    def set_partners(self, conststd) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    def single_beta_sample(self) -> float: ...

class EnsureExclusivelySharedJumpMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: EnsureExclusivelySharedJumpMover) -> None: ...
    @overload
    def __init__(self, arg0: EnsureExclusivelySharedJumpMover) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def apply(self) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self, rhs: EnsureExclusivelySharedJumpMover) -> EnsureExclusivelySharedJumpMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    def selector(self, getter) -> Any: ...
    @overload
    def set_selector(self, setting: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_selector(self, classstd) -> void: ...

class EnsureExclusivelySharedJumpMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: EnsureExclusivelySharedJumpMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: EnsureExclusivelySharedJumpMoverCreator) -> None: ...
    def assign(self) -> EnsureExclusivelySharedJumpMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class FaDockingSlideIntoContact(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rb_jump: int) -> None: ...
    @overload
    def __init__(self, rb_jumps: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, rb_jump: int, slide_axis: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def __init__(self, arg0: FaDockingSlideIntoContact) -> None: ...
    @overload
    def __init__(self, arg0: FaDockingSlideIntoContact) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> FaDockingSlideIntoContact: ...
    @overload
    def get_jump_num(self) -> int: ...
    @overload
    def get_jump_num(self) -> unsignedlong: ...
    def get_name(self) -> str: ...
    @overload
    def get_tolerance(self) -> float: ...
    @overload
    def get_tolerance(self) -> double: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...

class InterfaceSidechainMinMover(SidechainMinMover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, rb_jump: int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, interface_dist: float) -> None: ...
    @overload
    def __init__(self, arg0: InterfaceSidechainMinMover) -> None: ...
    @overload
    def __init__(self, arg0: InterfaceSidechainMinMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> InterfaceSidechainMinMover: ...
    def get_name(self) -> str: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_interface_dist(self, interface_dist: float) -> None: ...
    @overload
    def set_interface_dist(self, double) -> void: ...

class RigidBodyInfo:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RigidBodyInfo) -> None: ...
    @overload
    def add_jump(self) -> None: ...
    @overload
    def add_jump(self, unsignedlong) -> void: ...
    def assign(self) -> RigidBodyInfo: ...
    def movable_jumps(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...

class SidechainMinMover(DockingHighRes):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, movemap: pyrosetta.rosetta.core.kinematics.MoveMap) -> None: ...
    @overload
    def __init__(self, rb_jump: int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: SidechainMinMover) -> None: ...
    @overload
    def __init__(self, arg0: SidechainMinMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> SidechainMinMover: ...
    def get_name(self) -> str: ...
    @overload
    def set_default(self) -> None: ...
    @overload
    def set_default(self) -> void: ...
    @overload
    def set_minmover(self, minmover: pyrosetta.rosetta.protocols.minimization_packing.MinMover) -> None: ...
    @overload
    def set_minmover(self, classstd) -> void: ...
    @overload
    def update_movemap(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def update_movemap(self, classcore) -> void: ...

class SlideIntoContact(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, jump: int) -> None: ...
    @overload
    def __init__(self, arg0: SlideIntoContact) -> None: ...
    @overload
    def __init__(self, arg0: SlideIntoContact) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> SlideIntoContact: ...
    @overload
    def get_jump_num(self) -> int: ...
    @overload
    def get_jump_num(self) -> unsignedlong: ...
    def get_name(self) -> str: ...
    def get_sfxn_name(self) -> str: ...
    @overload
    def get_stepsize(self) -> float: ...
    @overload
    def get_stepsize(self) -> double: ...
    @overload
    def move_apart_first(self, yesno: bool) -> None: ...
    @overload
    def move_apart_first(self, bool) -> void: ...
    def scorefunction(self, sfxn_name: str, scoretype_for_sliding: str) -> None: ...
    @overload
    def set_starting_rep(self, starting_rep: float) -> None: ...
    @overload
    def set_starting_rep(self, double) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, output: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def slide_axis(self, slide_axis: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def slide_axis(self, constclassnumeric) -> void: ...
    @overload
    def stepsize(self, stepsize: float) -> None: ...
    @overload
    def stepsize(self, double) -> void: ...
    @overload
    def vary_stepsize(self, yesno: bool) -> None: ...
    @overload
    def vary_stepsize(self, bool) -> void: ...

class TemperedDocking(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TemperedDocking) -> None: ...
    @overload
    def __init__(self, arg0: TemperedDocking) -> None: ...
    @overload
    def add_jump(self, jump_number: int) -> None: ...
    @overload
    def add_jump(self, constlong) -> void: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self, rhs: TemperedDocking) -> TemperedDocking: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    def movable_jumps(self) -> pyrosetta.rosetta.utility.vector1_int: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    def partners(self) -> str: ...
    @overload
    @staticmethod
    def register_options() -> None: ...
    @overload
    @staticmethod
    def register_options() -> void: ...
    @overload
    def set_autofoldtree(self, setting: bool) -> None: ...
    @overload
    def set_autofoldtree(self, bool) -> void: ...
    @overload
    def set_defaults(self) -> None: ...
    @overload
    def set_defaults(self) -> void: ...
    @overload
    def set_highres_scorefxn(self, docking_scorefxn_high: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_highres_scorefxn(self, classstd) -> void: ...
    @overload
    def set_highres_scorefxn(self, docking_scorefxn_high: pyrosetta.rosetta.core.scoring.ScoreFunction, docking_scorefxn_pack: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_highres_scorefxn(self, docking_scorefxn_high: pyrosetta.rosetta.core.scoring.ScoreFunction, docking_scorefxn_pack: pyrosetta.rosetta.core.scoring.ScoreFunction, docking_scorefxn_output: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_lowres_scorefxn(self, docking_scorefxn_low: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def set_lowres_scorefxn(self, classstd) -> void: ...
    @overload
    def set_movable_jumps(self, setting: pyrosetta.rosetta.utility.vector1_int) -> None: ...
    @overload
    def set_movable_jumps(self, constclassutility) -> void: ...
    @overload
    def set_partners(self, setting: str) -> None: ...
    @overload
    def set_partners(self, conststd) -> void: ...
    @overload
    def set_sc_min(self, sc_min: bool) -> None: ...
    @overload
    def set_sc_min(self, bool) -> void: ...
    @overload
    def set_use_constraints(self, setting: bool) -> None: ...
    @overload
    def set_use_constraints(self, bool) -> void: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def show(self, std) -> void: ...
    @overload
    def sync_objects_with_flags(self) -> None: ...
    @overload
    def sync_objects_with_flags(self) -> void: ...
    def to_centroid(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...

class TemperedDockingCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TemperedDockingCreator) -> None: ...
    def assign(self) -> TemperedDockingCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...

def calc_CAPRI_rank(pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, dock_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> int: ...
def calc_CA_Irmsd(pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, dock_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> float: ...
@overload
def calc_Fnat(pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, dock_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> float: ...
@overload
def calc_Fnat(pose: pyrosetta.rosetta.core.pose.Pose, list_file: str, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> float: ...
@overload
def calc_Fnat(constclasscore, conststd, constclassutility) -> double: ...
@overload
def calc_Fnonnat(pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, dock_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> float: ...
@overload
def calc_Fnonnat(pose: pyrosetta.rosetta.core.pose.Pose, list_file: str, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> float: ...
@overload
def calc_Fnonnat(constclasscore, conststd, constclassutility) -> double: ...
def calc_Irmsd(pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, dock_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> float: ...
def calc_Irmsd_legacy(pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, dock_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> float: ...
def calc_Lrmsd(pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> float: ...
def calc_P1rmsd(pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> float: ...
def calc_P2rmsd(pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> float: ...
@overload
def calc_interaction_energy(pose: pyrosetta.rosetta.core.pose.Pose, dock_scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> float: ...
@overload
def calc_interaction_energy(constclasscore, constclassstd, constclassutility) -> double: ...
@overload
def calc_intf_score(pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, jump: int) -> float: ...
@overload
def calc_intf_score(constclasscore, constclassstd, constint) -> double: ...
def calc_res_contact(rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, dist_cutoff: float) -> bool: ...
def comma_separated_partner_chains(chains: str) -> str: ...
@overload
def move_apart(pose: pyrosetta.rosetta.core.pose.Pose, jump: int, axis: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
@overload
def move_apart(classcore, int, constclassnumeric) -> void: ...
@overload
def move_together(pose: pyrosetta.rosetta.core.pose.Pose, jump: int, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
@overload
def move_together(classcore, int, classstd) -> void: ...
@overload
def setup_foldtree(pose: pyrosetta.rosetta.core.pose.Pose, partner_chainID: str, movable_jumps: pyrosetta.rosetta.utility.vector1_int) -> None: ...
@overload
def setup_foldtree(pose: pyrosetta.rosetta.core.pose.Pose, partner_chainID: str, movable_jumps: pyrosetta.rosetta.utility.vector1_int, rand_jump_res_partner2: bool) -> None: ...
@overload
def setup_foldtree(classcore, conststd, classutility, bool) -> void: ...
@overload
def setup_foldtree(pose: pyrosetta.rosetta.core.pose.Pose, partner1: pyrosetta.rosetta.utility.vector1_bool, movable_jumps: pyrosetta.rosetta.utility.vector1_int, ft: pyrosetta.rosetta.core.kinematics.FoldTree) -> None: ...
@overload
def setup_foldtree(pose: pyrosetta.rosetta.core.pose.Pose, partner1: pyrosetta.rosetta.utility.vector1_bool, movable_jumps: pyrosetta.rosetta.utility.vector1_int, ft: pyrosetta.rosetta.core.kinematics.FoldTree, rand_jump_res_partner2: bool) -> None: ...
@overload
def setup_foldtree(constclasscore, constclassutility, classutility, classcore, bool) -> void: ...
