import pyrosetta.rosetta.numeric

def ALPHA(r0: float, omega0: float, P_omega0: float) -> float: ...
def COSFXN(t: float, omega: float, delta_omega: float) -> float: ...
def PP(r0: float, omega0: float, z1: float, failed: bool) -> float: ...
def P_omega0(r0: float, omega0: float, z1: float, epsilon_equals_one: bool, dr0_dt: float, failed: bool) -> float: ...
def SINFXN(t: float, omega: float, delta_omega: float) -> float: ...
def XYZ_BUNDLE(t: float, r0: float, omega0: float, delta_omega0: float, r1: float, omega1: float, z1: float, delta_omega1: float, delta_z1: float, epsilon: float, failed: bool) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
def X_BUNDLE(t: float, r0: float, omega0: float, delta_omega0: float, r1: float, omega1: float, z1: float, delta_omega1: float, delta_z1: float, epsilon: float, dr0prime_dt: float, failed: bool) -> float: ...
def Y_BUNDLE(t: float, r0: float, omega0: float, delta_omega0: float, r1: float, omega1: float, z1: float, delta_omega1: float, delta_z1: float, epsilon: float, dr0prime_dt: float, failed: bool) -> float: ...
def Z_BUNDLE(t: float, r0: float, omega0: float, delta_omega0: float, r1: float, omega1: float, z1: float, delta_omega1: float, delta_z1: float, epsilon: float, dr0prime_dt: float, failed: bool) -> float: ...
def dx_ddelta_omega1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def dx_ddelta_z1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def dx_ddz1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def dx_domega1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def dx_dr1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def dy_ddelta_omega1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def dy_ddelta_z1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def dy_ddz1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def dy_domega1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def dy_dr1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def dz_ddelta_omega1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def dz_ddelta_z1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def dz_ddz1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def dz_domega1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def dz_dr1(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def gradnorm(r0: float, omega0: float, Pomega0: float, s0: float, c0: float) -> float: ...
def x(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def xyz(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
def y(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
def z(r1: float, omega1: float, t: float, dz1: float, delta_omega1: float, delta_z1: float) -> float: ...
