import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.utility
from typing import overload

class EllipseParameters:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, h: float, k: float, a: float, b: float, rotation: pyrosetta.rosetta.numeric.MathMatrix_double_t) -> None: ...
    @overload
    def __init__(self, arg0: EllipseParameters) -> None: ...
    def add_buffer(self, major_buffer: float, minor_buffer: float) -> None: ...
    def assign(self) -> EllipseParameters: ...
    @overload
    def center_h(self) -> float: ...
    @overload
    def center_h(self) -> double: ...
    @overload
    def center_k(self) -> float: ...
    @overload
    def center_k(self) -> double: ...
    def clone(self) -> EllipseParameters: ...
    @overload
    def major_radius(self) -> float: ...
    @overload
    def major_radius(self) -> double: ...
    @overload
    def minor_radius(self) -> float: ...
    @overload
    def minor_radius(self) -> double: ...
    def rotation(self) -> pyrosetta.rosetta.numeric.MathMatrix_double_t: ...

def epslon(x: float) -> float: ...
@overload
def minimum_bounding_ellipse(points: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t, tolerance: float) -> EllipseParameters: ...
@overload
def minimum_bounding_ellipse(points: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t, tolerance: float, max_iterations: int) -> EllipseParameters: ...
def non_square_transpose(matrix_in: pyrosetta.rosetta.numeric.MathMatrix_double_t) -> pyrosetta.rosetta.numeric.MathMatrix_double_t: ...
def point_in_ellipse(p: pyrosetta.rosetta.numeric.xyzVector_double_t, h: float, k: float, a: float, b: float, rotation: pyrosetta.rosetta.numeric.MathMatrix_double_t) -> bool: ...
def sum_of_square_differences(old_u: pyrosetta.rosetta.numeric.MathMatrix_double_t, new_u: pyrosetta.rosetta.numeric.MathMatrix_double_t) -> float: ...
def svdcmp(a: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t, m: int, n: int, w: pyrosetta.rosetta.utility.vector1_double, v: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t) -> None: ...
