import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from typing import Any, overload

class RandomGenerator:
    def __init__(self, *args, **kwargs) -> None: ...
    def assign(self) -> RandomGenerator: ...
    @overload
    def gaussian(self) -> float: ...
    @overload
    def gaussian(self) -> double: ...
    @overload
    def get_seed(self) -> int: ...
    @overload
    def get_seed(self) -> int: ...
    @overload
    def initialized(self) -> bool: ...
    @overload
    def initialized(self, byacalltoset_seed) -> Any: ...
    @overload
    def initialized(self) -> bool: ...
    @overload
    def max(self) -> float: ...
    @overload
    def max(self) -> double: ...
    @overload
    def min(self) -> float: ...
    @overload
    def min(self) -> double: ...
    def random_range(self, low: int, high: int) -> int: ...
    def random_range2(self, low: int, high: int) -> int: ...
    @overload
    def restoreState(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def restoreState(self, std) -> void: ...
    @overload
    def saveState(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def saveState(self, std) -> void: ...
    @overload
    def set_seed(self, generator_type: str, seed: int) -> None: ...
    @overload
    def set_seed(self, conststd, int) -> void: ...
    @overload
    def set_seed(self, seed: int) -> None: ...
    @overload
    def set_seed(self, int) -> void: ...
    @overload
    def uniform(self) -> float: ...
    @overload
    def uniform(self) -> double: ...
    def __call__(self) -> float: ...

class WeightedSampler:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, num_weights: int) -> None: ...
    @overload
    def __init__(self, weights: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, arg0: WeightedSampler) -> None: ...
    @overload
    def add_weight(self, weight: float) -> None: ...
    @overload
    def add_weight(self, double) -> void: ...
    def assign(self) -> WeightedSampler: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    @overload
    def random_sample(self) -> int: ...
    @overload
    def random_sample(self) -> unsignedlong: ...
    @overload
    def random_sample(self) -> int: ...
    @overload
    def random_sample(self, classnumeric) -> unsignedlong: ...
    @overload
    def random_sample(self, randnum: float) -> int: ...
    @overload
    def random_sample(self, double) -> unsignedlong: ...
    @overload
    def resize(self, num_weights: int) -> None: ...
    @overload
    def resize(self, num_weights: int, default_weight: float) -> None: ...
    @overload
    def resize(self, unsignedlong, double) -> void: ...
    @overload
    def set_weight(self, weight_num: int, weight: float) -> None: ...
    @overload
    def set_weight(self, unsignedlong, double) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def update_cumulative_distribution(self) -> bool: ...
    @overload
    def update_cumulative_distribution(self) -> bool: ...
    @overload
    def weights(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    @overload
    def weights(self, weights: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def weights(self, constclassutility) -> void: ...

class mt19937_RG(uniform_RG):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: mt19937_RG) -> None: ...
    @overload
    def __init__(self, arg0: mt19937_RG) -> None: ...
    def assign(self) -> mt19937_RG: ...
    @overload
    def getRandom(self) -> float: ...
    @overload
    def getRandom(self) -> double: ...
    @overload
    def getSeed(self) -> int: ...
    @overload
    def getSeed(self) -> int: ...
    @overload
    def restoreState(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def restoreState(self, std) -> void: ...
    @overload
    def saveState(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def saveState(self, std) -> void: ...
    @overload
    def setSeed(self, iseed: int) -> None: ...
    @overload
    def setSeed(self, constint) -> void: ...
    @overload
    def setSeed(self) -> None: ...
    @overload
    def setSeed(self, conststd) -> void: ...

class standard_RG(uniform_RG):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: standard_RG) -> None: ...
    @overload
    def __init__(self, arg0: standard_RG) -> None: ...
    def assign(self) -> standard_RG: ...
    @overload
    def getRandom(self) -> float: ...
    @overload
    def getRandom(self) -> double: ...
    @overload
    def getSeed(self) -> int: ...
    @overload
    def getSeed(self) -> int: ...
    @overload
    def restoreState(self) -> None: ...
    @overload
    def restoreState(self, std) -> void: ...
    @overload
    def saveState(self) -> None: ...
    @overload
    def saveState(self, std) -> void: ...
    @overload
    def setSeed(self, seed: int) -> None: ...
    @overload
    def setSeed(self, constint) -> void: ...
    @overload
    def setSeed(self) -> None: ...
    @overload
    def setSeed(self, conststd) -> void: ...

class uniform_RG:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: uniform_RG) -> None: ...
    def assign(self) -> uniform_RG: ...
    @overload
    def getRandom(self) -> float: ...
    @overload
    def getRandom(self) -> double: ...
    @overload
    def getSeed(self) -> int: ...
    @overload
    def getSeed(self) -> int: ...
    @overload
    def restoreState(self, _in: pyrosetta.rosetta.std.istream) -> None: ...
    @overload
    def restoreState(self, std) -> void: ...
    @overload
    def saveState(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def saveState(self, std) -> void: ...
    @overload
    def setSeed(self, seed: int) -> None: ...
    @overload
    def setSeed(self, constint) -> void: ...
    @overload
    def setSeed(self, seed: str) -> None: ...
    @overload
    def setSeed(self, conststd) -> void: ...

@overload
def gaussian() -> float: ...
@overload
def gaussian() -> double: ...
def gaussian_random_xform(angsd: float, movsd: float) -> pyrosetta.rosetta.numeric.xyzTransform_double_t: ...
@overload
def ini_func1(x: int) -> int: ...
@overload
def ini_func1(unsignedint) -> unsignedint: ...
@overload
def ini_func2(x: int) -> int: ...
@overload
def ini_func2(unsignedint) -> unsignedint: ...
def random_normal() -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
def random_range(low: int, high: int) -> int: ...
def random_rotation() -> pyrosetta.rosetta.numeric.xyzMatrix_double_t: ...
def random_unit_quaternion() -> pyrosetta.rosetta.numeric.Quaternion_double_t: ...
def random_vector() -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
def random_vector_spherical() -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
def random_vector_unit_cube() -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
def random_xform() -> pyrosetta.rosetta.numeric.xyzTransform_double_t: ...
def reservoir_sample_accept_prob(n_wanted: int, n_seen: int) -> float: ...
def rg(*args, **kwargs): ...
@overload
def sformat_idxof(i: int) -> int: ...
@overload
def sformat_idxof(int) -> int: ...
@overload
def uniform() -> float: ...
@overload
def uniform() -> double: ...
@overload
def uniform_vector_sphere() -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
@overload
def uniform_vector_sphere(radius: float) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
