import pyrosetta.rosetta.utility
from typing import overload

@overload
def Dawson(x: float) -> float: ...
@overload
def Dawson(double) -> double: ...
def corrcoef(vec1: pyrosetta.rosetta.utility.vector1_double, vec2: pyrosetta.rosetta.utility.vector1_double) -> float: ...
def corrcoef_with_provided_mean_and_std_dev(vec1: pyrosetta.rosetta.utility.vector1_double, m1: float, sd1: float, vec2: pyrosetta.rosetta.utility.vector1_double, m2: float, sd2: float) -> float: ...
def cov(vec1: pyrosetta.rosetta.utility.vector1_double, vec2: pyrosetta.rosetta.utility.vector1_double) -> float: ...
def cov_with_provided_mean(vec1: pyrosetta.rosetta.utility.vector1_double, m1: float, vec2: pyrosetta.rosetta.utility.vector1_double, m2: float) -> float: ...
@overload
def errf(x: float) -> float: ...
@overload
def errf(double) -> double: ...
@overload
def errfc(x: float) -> float: ...
@overload
def errfc(double) -> double: ...
@overload
def errfcx(x: float) -> float: ...
@overload
def errfcx(double) -> double: ...
@overload
def errfi(x: float) -> float: ...
@overload
def errfi(double) -> double: ...
def kl_divergence(prior: pyrosetta.rosetta.utility.vector1_double, posterior: pyrosetta.rosetta.utility.vector1_double) -> float: ...
def spearman_r(vec1: pyrosetta.rosetta.utility.vector1_double, vec2: pyrosetta.rosetta.utility.vector1_double) -> float: ...
def w(*args, **kwargs): ...
@overload
def w_im(x: float) -> float: ...
@overload
def w_im(double) -> double: ...
