import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.fragment
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.select.movemap
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import overload

class AlignByResidueSelectorMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AlignByResidueSelectorMover) -> None: ...
    @overload
    def __init__(self, arg0: AlignByResidueSelectorMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> AlignByResidueSelectorMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def query_selector(self, select: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def query_selector(self, constclassstd) -> void: ...
    @overload
    def query_selector(self, select: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def query_selector(self, constclasscore) -> void: ...
    @overload
    def reference_pose(self, ref: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def reference_pose(self, constclassstd) -> void: ...
    @overload
    def reference_pose(self, ref: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def reference_pose(self, constclasscore) -> void: ...
    @overload
    def reference_selector(self, select: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def reference_selector(self, constclassstd) -> void: ...
    @overload
    def reference_selector(self, select: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def reference_selector(self, constclasscore) -> void: ...

class AlignByResidueSelectorMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AlignByResidueSelectorMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: AlignByResidueSelectorMoverCreator) -> None: ...
    def assign(self) -> AlignByResidueSelectorMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class DisplayPoseLabelsMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DisplayPoseLabelsMover) -> None: ...
    @overload
    def __init__(self, arg0: DisplayPoseLabelsMover) -> None: ...
    @overload
    def add_labels_as_remark(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def add_labels_as_remark(self, classcore) -> void: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> DisplayPoseLabelsMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def movemap_factory(self) -> pyrosetta.rosetta.core.select.movemap.MoveMapFactory: ...
    @overload
    def movemap_factory(self, pick: pyrosetta.rosetta.core.select.movemap.MoveMapFactory) -> None: ...
    @overload
    def movemap_factory(self, classstd) -> void: ...
    def movemap_from_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def tasks(self) -> pyrosetta.rosetta.core.pack.task.TaskFactory: ...
    @overload
    def tasks(self, pick: pyrosetta.rosetta.core.pack.task.TaskFactory) -> None: ...
    @overload
    def tasks(self, classstd) -> void: ...
    @overload
    def title_width(self) -> int: ...
    @overload
    def title_width(self) -> unsignedlong: ...
    @overload
    def title_width(self, pick: int) -> None: ...
    @overload
    def title_width(self, unsignedlong) -> void: ...
    @overload
    def use_dssp(self) -> bool: ...
    @overload
    def use_dssp(self) -> bool: ...
    @overload
    def use_dssp(self, pick: bool) -> None: ...
    @overload
    def use_dssp(self, bool) -> void: ...
    @overload
    def write(self) -> bool: ...
    @overload
    def write(self) -> bool: ...
    @overload
    def write(self, pick: bool) -> None: ...
    @overload
    def write(self, bool) -> void: ...

class DisplayPoseLabelsMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DisplayPoseLabelsMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: DisplayPoseLabelsMoverCreator) -> None: ...
    def assign(self) -> DisplayPoseLabelsMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class LabelPoseFromResidueSelectorMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector, string: str) -> None: ...
    @overload
    def __init__(self, arg0: LabelPoseFromResidueSelectorMover) -> None: ...
    @overload
    def __init__(self, arg0: LabelPoseFromResidueSelectorMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> LabelPoseFromResidueSelectorMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def from_remark(self, pick: bool) -> None: ...
    def get_name(self) -> str: ...
    @overload
    def label(self, label: str) -> None: ...
    @overload
    def label(self, conststd) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def residue_selector(self, constclassstd) -> void: ...
    @overload
    def residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def residue_selector(self, constclasscore) -> void: ...
    @overload
    def unlabel(self, label: str) -> None: ...
    @overload
    def unlabel(self, conststd) -> void: ...

class LabelPoseFromResidueSelectorMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LabelPoseFromResidueSelectorMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: LabelPoseFromResidueSelectorMoverCreator) -> None: ...
    def assign(self) -> LabelPoseFromResidueSelectorMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class MoveMapFactoryToNamedMoveMapMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MoveMapFactoryToNamedMoveMapMover) -> None: ...
    @overload
    def __init__(self, arg0: MoveMapFactoryToNamedMoveMapMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> MoveMapFactoryToNamedMoveMapMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class MoveMapFactoryToNamedMoveMapMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MoveMapFactoryToNamedMoveMapMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: MoveMapFactoryToNamedMoveMapMoverCreator) -> None: ...
    def assign(self) -> MoveMapFactoryToNamedMoveMapMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class NubInitioLoopClosureMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: NubInitioLoopClosureMover) -> None: ...
    @overload
    def __init__(self, arg0: NubInitioLoopClosureMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> NubInitioLoopClosureMover: ...
    @overload
    def break_side(self) -> int: ...
    @overload
    def break_side(self) -> unsignedlong: ...
    @overload
    def break_side(self, value: float) -> None: ...
    @overload
    def break_side(self, double) -> void: ...
    @overload
    def break_side_ramp(self) -> bool: ...
    @overload
    def break_side_ramp(self) -> bool: ...
    @overload
    def break_side_ramp(self, pick: bool) -> None: ...
    @overload
    def break_side_ramp(self, bool) -> void: ...
    @overload
    def centroid(self) -> bool: ...
    @overload
    def centroid(self) -> bool: ...
    @overload
    def centroid(self, pick: bool) -> None: ...
    @overload
    def centroid(self, bool) -> void: ...
    @overload
    def centroid_scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def centroid_scorefxn(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def centroid_scorefxn(self, constclassstd) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def design(self) -> bool: ...
    @overload
    def design(self) -> bool: ...
    @overload
    def design(self, pick: bool) -> None: ...
    @overload
    def design(self, bool) -> void: ...
    @overload
    def fragments(self) -> pyrosetta.rosetta.core.fragment.FragSet: ...
    @overload
    def fragments(self, frags: pyrosetta.rosetta.core.fragment.FragSet) -> None: ...
    @overload
    def fragments(self, classstd) -> void: ...
    @overload
    def fragments_id(self) -> str: ...
    @overload
    def fragments_id(self, name: str) -> None: ...
    @overload
    def fragments_id(self, conststd) -> void: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def fullatom_scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def fullatom_scorefxn(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def fullatom_scorefxn(self, constclassstd) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def label(self) -> bool: ...
    @overload
    def label(self) -> bool: ...
    @overload
    def label(self, pick: bool) -> None: ...
    @overload
    def label(self, bool) -> void: ...
    @overload
    def max_trials(self, choice: int) -> None: ...
    @overload
    def max_trials(self, unsignedlong) -> void: ...
    @overload
    def max_trials(self) -> int: ...
    @overload
    def max_trials(self) -> unsignedlong: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def trust(self) -> bool: ...
    @overload
    def trust(self) -> bool: ...
    @overload
    def trust(self, pick: bool) -> None: ...
    @overload
    def trust(self, bool) -> void: ...

class NubInitioLoopClosureMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: NubInitioLoopClosureMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: NubInitioLoopClosureMoverCreator) -> None: ...
    def assign(self) -> NubInitioLoopClosureMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ReleaseConstraintFromResidueMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: ReleaseConstraintFromResidueMover) -> None: ...
    @overload
    def __init__(self, arg0: ReleaseConstraintFromResidueMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> ReleaseConstraintFromResidueMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, constclassstd) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, constclasscore) -> void: ...

class ReleaseConstraintFromResidueMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ReleaseConstraintFromResidueMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: ReleaseConstraintFromResidueMoverCreator) -> None: ...
    def assign(self) -> ReleaseConstraintFromResidueMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ResidueLabelsToPymolSelectionMover(pyrosetta.rosetta.protocols.moves.Mover):
    def __init__(self) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> ResidueLabelsToPymolSelectionMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def pdb_count(self, action: bool) -> None: ...
    @overload
    def pdb_count(self, bool) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class ResidueLabelsToPymolSelectionMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ResidueLabelsToPymolSelectionMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: ResidueLabelsToPymolSelectionMoverCreator) -> None: ...
    def assign(self) -> ResidueLabelsToPymolSelectionMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SavePDBInfoMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SavePDBInfoMover) -> None: ...
    @overload
    def __init__(self, arg0: SavePDBInfoMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> SavePDBInfoMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class SavePDBInfoMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SavePDBInfoMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: SavePDBInfoMoverCreator) -> None: ...
    def assign(self) -> SavePDBInfoMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SplitAndMixPoseMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SplitAndMixPoseMover) -> None: ...
    @overload
    def __init__(self, arg0: SplitAndMixPoseMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def apply_without_merge(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_pose_Pose_t: ...
    def assign(self) -> SplitAndMixPoseMover: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def count_segments(self) -> int: ...
    @overload
    def count_segments(self) -> unsignedlong: ...
    @overload
    def count_segments(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def count_segments(self, constclasscore) -> unsignedlong: ...
    @overload
    @staticmethod
    def default_exclude_consecutive() -> bool: ...
    @overload
    @staticmethod
    def default_exclude_consecutive() -> bool: ...
    @overload
    @staticmethod
    def default_max_distance() -> float: ...
    @overload
    @staticmethod
    def default_max_distance() -> double: ...
    @overload
    @staticmethod
    def default_merge_chains() -> bool: ...
    @overload
    @staticmethod
    def default_merge_chains() -> bool: ...
    @overload
    @staticmethod
    def default_try_all_pairs() -> bool: ...
    @overload
    @staticmethod
    def default_try_all_pairs() -> bool: ...
    @overload
    def exclude_consecutive(self) -> bool: ...
    @overload
    def exclude_consecutive(self) -> bool: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def get_global_i(self) -> int: ...
    @overload
    def get_global_i(self) -> unsignedlong: ...
    def get_name(self) -> str: ...
    @overload
    def max_distance(self) -> float: ...
    @overload
    def max_distance(self) -> double: ...
    @overload
    def merge_chains(self) -> bool: ...
    @overload
    def merge_chains(self) -> bool: ...
    @staticmethod
    def mover_name() -> str: ...
    def order(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def ranges(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueRanges: ...
    @overload
    def reset_order(self) -> None: ...
    @overload
    def reset_order(self) -> void: ...
    def residue_selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    def set_exclude_consecutive(self, exclude_consecutive: bool) -> None: ...
    @overload
    def set_exclude_consecutive(self, bool) -> void: ...
    @overload
    def set_max_distance(self, max_distance: float) -> None: ...
    @overload
    def set_max_distance(self, double) -> void: ...
    @overload
    def set_merge_chains(self, merge: bool) -> None: ...
    @overload
    def set_merge_chains(self, bool) -> void: ...
    @overload
    def set_order(self, order: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_order(self, classutility) -> void: ...
    @overload
    def set_order(self, order: str) -> None: ...
    @overload
    def set_order(self, std) -> void: ...
    @overload
    def set_order(self, max: int) -> None: ...
    @overload
    def set_order(self, unsignedlong) -> void: ...
    @overload
    def set_ranges(self, ranges: pyrosetta.rosetta.core.select.residue_selector.ResidueRanges) -> None: ...
    @overload
    def set_ranges(self, constclassstd) -> void: ...
    @overload
    def set_residue_selector(self, selector: pyrosetta.rosetta.core.select.residue_selector.ResidueSelector) -> None: ...
    @overload
    def set_residue_selector(self, classstd) -> void: ...
    @overload
    def set_try_all_pairs(self, try_all_pairs: bool) -> None: ...
    @overload
    def set_try_all_pairs(self, bool) -> void: ...
    @overload
    def try_all_pairs(self) -> bool: ...
    @overload
    def try_all_pairs(self) -> bool: ...

class SplitAndMixPoseMoverCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SplitAndMixPoseMoverCreator) -> None: ...
    @overload
    def __init__(self, arg0: SplitAndMixPoseMoverCreator) -> None: ...
    def assign(self) -> SplitAndMixPoseMoverCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
