import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.select.residue_selector
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import overload

class ConstraintResidueSelector(pyrosetta.rosetta.core.select.residue_selector.ResidueSelector):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ConstraintResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: ConstraintResidueSelector) -> None: ...
    @overload
    def angle(self) -> bool: ...
    @overload
    def angle(self) -> bool: ...
    @overload
    def angle(self, pick: bool) -> None: ...
    @overload
    def angle(self, bool) -> void: ...
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def assign(self) -> ConstraintResidueSelector: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    @overload
    @staticmethod
    def default_angle() -> bool: ...
    @overload
    @staticmethod
    def default_angle() -> bool: ...
    @overload
    @staticmethod
    def default_dihedral() -> bool: ...
    @overload
    @staticmethod
    def default_dihedral() -> bool: ...
    @overload
    @staticmethod
    def default_distance() -> bool: ...
    @overload
    @staticmethod
    def default_distance() -> bool: ...
    @overload
    def dihedral(self) -> bool: ...
    @overload
    def dihedral(self) -> bool: ...
    @overload
    def dihedral(self, pick: bool) -> None: ...
    @overload
    def dihedral(self, bool) -> void: ...
    @overload
    def distance(self) -> bool: ...
    @overload
    def distance(self) -> bool: ...
    @overload
    def distance(self, pick: bool) -> None: ...
    @overload
    def distance(self, bool) -> void: ...
    def get_name(self) -> str: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, datamap: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class ConstraintResidueSelectorCreator(pyrosetta.rosetta.core.select.residue_selector.ResidueSelectorCreator):
    def __init__(self) -> None: ...
    def assign(self) -> ConstraintResidueSelectorCreator: ...
    def create_residue_selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class CutpointResidueSelector(pyrosetta.rosetta.core.select.residue_selector.ResidueSelector):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, use_foldtree: bool) -> None: ...
    @overload
    def __init__(self, arg0: CutpointResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: CutpointResidueSelector) -> None: ...
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def assign(self) -> CutpointResidueSelector: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    def get_name(self) -> str: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, datamap: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def use_foldtree(self, pick: bool) -> None: ...
    @overload
    def use_foldtree(self, bool) -> void: ...
    @overload
    def use_foldtree(self) -> bool: ...
    @overload
    def use_foldtree(self) -> bool: ...

class CutpointResidueSelectorCreator(pyrosetta.rosetta.core.select.residue_selector.ResidueSelectorCreator):
    def __init__(self) -> None: ...
    def assign(self) -> CutpointResidueSelectorCreator: ...
    def create_residue_selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ProteinResidueSelector(pyrosetta.rosetta.core.select.residue_selector.ResidueSelector):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ProteinResidueSelector) -> None: ...
    @overload
    def __init__(self, arg0: ProteinResidueSelector) -> None: ...
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_bool: ...
    def assign(self) -> ProteinResidueSelector: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    def get_name(self) -> str: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, datamap: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class ProteinResidueSelectorCreator(pyrosetta.rosetta.core.select.residue_selector.ResidueSelectorCreator):
    def __init__(self) -> None: ...
    def assign(self) -> ProteinResidueSelectorCreator: ...
    def create_residue_selector(self) -> pyrosetta.rosetta.core.select.residue_selector.ResidueSelector: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
