import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.protocols.features
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.sql_database
import pyrosetta.rosetta.utility.tag
from typing import overload

class SandwichFeatures(pyrosetta.rosetta.protocols.features.FeaturesReporter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SandwichFeatures) -> None: ...
    @overload
    def __init__(self, arg0: SandwichFeatures) -> None: ...
    def assign(self) -> SandwichFeatures: ...
    @staticmethod
    def class_name() -> str: ...
    def features_reporter_dependencies(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def report_features(self, pose: pyrosetta.rosetta.core.pose.Pose, relevant_residues: pyrosetta.rosetta.utility.vector1_bool, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> int: ...
    @overload
    def report_features(self, constclasscore, constclassutility, unsignedlonglong, classstd) -> unsignedlong: ...
    def type_name(self) -> str: ...
    @overload
    def write_schema_to_db(self, db_session: pyrosetta.rosetta.utility.sql_database.session) -> None: ...
    @overload
    def write_schema_to_db(self, classstd) -> void: ...

class SandwichFeaturesCreator(pyrosetta.rosetta.protocols.features.FeaturesReporterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SandwichFeaturesCreator) -> None: ...
    @overload
    def __init__(self, arg0: SandwichFeaturesCreator) -> None: ...
    def assign(self) -> SandwichFeaturesCreator: ...
    def create_features_reporter(self) -> pyrosetta.rosetta.protocols.features.FeaturesReporter: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
    def type_name(self) -> str: ...

class SandwichFragment:
    @overload
    def __init__(self, chain_B_resNum: int) -> None: ...
    @overload
    def __init__(self, start: int, end: int) -> None: ...
    @overload
    def __init__(self, sheet_id: int, start: int, end: int) -> None: ...
    @overload
    def __init__(self, sheet_id: int, strand_id: int, start: int, end: int) -> None: ...
    @overload
    def __init__(self, sw_can_by_sh_id: int, sheet_id: int, strand_id: int, start: int, end: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SandwichFragment) -> None: ...
    def assign(self) -> SandwichFragment: ...
    @overload
    def get_end(self) -> int: ...
    @overload
    def get_end(self) -> unsignedlong: ...
    @overload
    def get_resNum(self) -> int: ...
    @overload
    def get_resNum(self) -> unsignedlong: ...
    @overload
    def get_sheet_id(self) -> int: ...
    @overload
    def get_sheet_id(self) -> unsignedlong: ...
    @overload
    def get_size(self) -> int: ...
    @overload
    def get_size(self) -> unsignedlong: ...
    @overload
    def get_start(self) -> int: ...
    @overload
    def get_start(self) -> unsignedlong: ...
    @overload
    def get_strand_id(self) -> int: ...
    @overload
    def get_strand_id(self) -> unsignedlong: ...
    @overload
    def get_sw_can_by_sh_id(self) -> int: ...
    @overload
    def get_sw_can_by_sh_id(self) -> unsignedlong: ...

class StrandBundleFeatures(pyrosetta.rosetta.protocols.features.FeaturesReporter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: StrandBundleFeatures) -> None: ...
    @overload
    def __init__(self, arg0: StrandBundleFeatures) -> None: ...
    def assign(self) -> StrandBundleFeatures: ...
    def check_strand_too_closeness(self, pose: pyrosetta.rosetta.core.pose.Pose, strand_i, strand_j) -> bool: ...
    def check_sw_by_dis(self, pose: pyrosetta.rosetta.core.pose.Pose, strand_i, strand_j, antiparalell: bool) -> float: ...
    @staticmethod
    def class_name() -> str: ...
    def features_reporter_dependencies(self) -> pyrosetta.rosetta.utility.vector1_std_string: ...
    def final_check_sw_by_dis(self, pose: pyrosetta.rosetta.core.pose.Pose, temp_strand_ii_i, temp_strand_ii_j, temp_strand_jj_i, temp_strand_jj_j, antiparalell: bool) -> bool: ...
    def find_antiparallel(self, pose: pyrosetta.rosetta.core.pose.Pose, strand_i, strand_j) -> bool: ...
    def find_parallel(self, pose: pyrosetta.rosetta.core.pose.Pose, strand_i, strand_j) -> bool: ...
    def get_avg_dis_CA_CA(self, pose: pyrosetta.rosetta.core.pose.Pose, i_resnum: int, i_resnum_1: int, i_resnum_2: int, i_resnum_3: int, j_resnum: int, j_resnum_1: int, j_resnum_2: int, j_resnum_3: int) -> float: ...
    @overload
    def get_nearest_res_from_strand(self, pose: pyrosetta.rosetta.core.pose.Pose, strand_to_be_searched, rounded_resnum: int) -> int: ...
    @overload
    def get_nearest_res_from_strand(self, constclasscore, classprotocols, unsignedlong) -> unsignedlong: ...
    def get_shortest_among_4(self, val_shortest_dis_sidechain_1: float, val_shortest_dis_sidechain_2: float, val_shortest_dis_sidechain_3: float, val_shortest_dis_sidechain_4: float) -> float: ...
    @overload
    def init_from_options(self) -> None: ...
    @overload
    def init_from_options(self) -> void: ...
    def judge_facing(self, pose: pyrosetta.rosetta.core.pose.Pose, strand_ii_i, strand_ii_j, strand_jj_i, strand_jj_j) -> bool: ...
    def judge_sw_dis_too_close(self, pose: pyrosetta.rosetta.core.pose.Pose, temp_strand_ii_i, temp_strand_ii_j, temp_strand_jj_i, temp_strand_jj_j) -> bool: ...
    def judge_sw_inter_dis(self, pose: pyrosetta.rosetta.core.pose.Pose, temp_strand_ii_i, temp_strand_ii_j, temp_strand_jj_i, temp_strand_jj_j) -> float: ...
    def judge_sw_torsion(self, pose: pyrosetta.rosetta.core.pose.Pose, temp_strand_ii_i, temp_strand_ii_j, temp_strand_jj_i, temp_strand_jj_j) -> bool: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def report_features(self, pose: pyrosetta.rosetta.core.pose.Pose, relevant_residues: pyrosetta.rosetta.utility.vector1_bool, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> int: ...
    @overload
    def report_features(self, constclasscore, constclassutility, unsignedlonglong, classstd) -> unsignedlong: ...
    @overload
    def round(self, x: float) -> int: ...
    @overload
    def round(self, double) -> unsignedlong: ...
    def sheet_dis_by_terminals(self, pose: pyrosetta.rosetta.core.pose.Pose, strand_i, strand_j) -> float: ...
    def sheet_torsion(self, pose: pyrosetta.rosetta.core.pose.Pose, strand_i, strand_j) -> float: ...
    def shortest_dis_sidechain(self, pose: pyrosetta.rosetta.core.pose.Pose, strand_i, strand_j) -> float: ...
    def type_name(self) -> str: ...
    @overload
    def write_schema_to_db(self, db_session: pyrosetta.rosetta.utility.sql_database.session) -> None: ...
    @overload
    def write_schema_to_db(self, classstd) -> void: ...

class StrandBundleFeaturesCreator(pyrosetta.rosetta.protocols.features.FeaturesReporterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: StrandBundleFeaturesCreator) -> None: ...
    @overload
    def __init__(self, arg0: StrandBundleFeaturesCreator) -> None: ...
    def assign(self) -> StrandBundleFeaturesCreator: ...
    def create_features_reporter(self) -> pyrosetta.rosetta.protocols.features.FeaturesReporter: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
    def type_name(self) -> str: ...

class StrandFragment:
    @overload
    def __init__(self, start: int, end: int) -> None: ...
    @overload
    def __init__(self, beta_selected_segments_id: int, start: int, end: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: StrandFragment) -> None: ...
    def assign(self) -> StrandFragment: ...
    @overload
    def get_end(self) -> int: ...
    @overload
    def get_end(self) -> unsignedlong: ...
    @overload
    def get_i(self) -> int: ...
    @overload
    def get_i(self) -> unsignedlong: ...
    @overload
    def get_id(self) -> int: ...
    @overload
    def get_id(self) -> unsignedlong: ...
    @overload
    def get_j(self) -> int: ...
    @overload
    def get_j(self) -> unsignedlong: ...
    def get_pdb_source(self) -> str: ...
    @overload
    def get_size(self) -> int: ...
    @overload
    def get_size(self) -> unsignedlong: ...
    @overload
    def get_start(self) -> int: ...
    @overload
    def get_start(self) -> unsignedlong: ...
    @overload
    def set_pdb_source(self, pdb_source_: str) -> None: ...
    @overload
    def set_pdb_source(self, std) -> void: ...

def WriteToDB_AA_to_terminal_loops(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, dssp_pose: pyrosetta.rosetta.core.pose.Pose, sandwich_PK_id_counter: int, sw_can_by_sh_id: int, tag: str, starting_loop: bool, residue_begin: int, residue_end: int) -> None: ...
@overload
def WriteToDB_avg_b_factor_CB_at_each_component(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, sw_can_by_sh_id: int) -> int: ...
@overload
def WriteToDB_avg_b_factor_CB_at_each_component(unsignedlonglong, classstd, constclasscore, unsignedlong) -> unsignedlong: ...
@overload
def WriteToDB_dihedral_angle_between_core_strands_across_facing_sheets(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, sw_can_by_sh_id: int) -> int: ...
@overload
def WriteToDB_dihedral_angle_between_core_strands_across_facing_sheets(unsignedlonglong, classstd, constclasscore, unsignedlong) -> unsignedlong: ...
@overload
def WriteToDB_dssp_ratio_in_sw(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, dssp_pose: pyrosetta.rosetta.core.pose.Pose, sw_can_by_sh_id: int) -> int: ...
@overload
def WriteToDB_dssp_ratio_in_sw(unsignedlonglong, classstd, classcore, unsignedlong) -> unsignedlong: ...
def WriteToDB_ending_loop(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, dssp_pose: pyrosetta.rosetta.core.pose.Pose, sandwich_PK_id_counter: int, sw_can_by_sh_id: int, tag: str, max_starting_loop_size_: int) -> int: ...
@overload
def WriteToDB_hydrophobic_ratio_net_charge(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> int: ...
@overload
def WriteToDB_hydrophobic_ratio_net_charge(unsignedlonglong, classstd, unsignedlong) -> unsignedlong: ...
@overload
def WriteToDB_long_strand_id_in_each_sw(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> int: ...
@overload
def WriteToDB_long_strand_id_in_each_sw(unsignedlonglong, classstd, unsignedlong) -> unsignedlong: ...
def WriteToDB_min_avg_dis_between_sheets_by_cen_res(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int, dssp_pose: pyrosetta.rosetta.core.pose.Pose, all_distinct_sheet_ids: pyrosetta.rosetta.utility.vector1_unsigned_long, min_num_strands_in_sheet_: int) -> int: ...
@overload
def WriteToDB_min_dis_between_sheets_by_all_res(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int, dssp_pose: pyrosetta.rosetta.core.pose.Pose, all_distinct_sheet_ids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> int: ...
@overload
def WriteToDB_min_dis_between_sheets_by_all_res(unsignedlonglong, classstd, unsignedlong, classcore, constclassutility) -> unsignedlong: ...
@overload
def WriteToDB_number_of_core_heading_FWY_in_sw(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> None: ...
@overload
def WriteToDB_number_of_core_heading_FWY_in_sw(unsignedlonglong, classstd, unsignedlong) -> void: ...
@overload
def WriteToDB_number_of_core_heading_LWY_in_core_strands_in_sw(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> int: ...
@overload
def WriteToDB_number_of_core_heading_LWY_in_core_strands_in_sw(unsignedlonglong, classstd, unsignedlong) -> unsignedlong: ...
@overload
def WriteToDB_number_of_core_heading_W_in_sw(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> None: ...
@overload
def WriteToDB_number_of_core_heading_W_in_sw(unsignedlonglong, classstd, unsignedlong) -> void: ...
def WriteToDB_number_of_core_heading_aro_AAs_in_a_pair_of_edge_strands(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int, current_bs_id: int, closest_bs_id: int) -> int: ...
def WriteToDB_number_of_core_heading_charged_AAs_in_a_pair_of_edge_strands(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int, current_bs_id: int, closest_bs_id: int) -> int: ...
@overload
def WriteToDB_number_of_edge_strands_in_each_sw(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> int: ...
@overload
def WriteToDB_number_of_edge_strands_in_each_sw(unsignedlonglong, classstd, unsignedlong) -> unsignedlong: ...
def WriteToDB_number_of_sheets_that_surround_this_sheet(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sheet_id: int, num_of_sheets_that_surround_this_sheet: int) -> int: ...
@overload
def WriteToDB_number_strands_in_each_sw(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> int: ...
@overload
def WriteToDB_number_strands_in_each_sw(unsignedlonglong, classstd, unsignedlong) -> unsignedlong: ...
def WriteToDB_prolines_that_seem_to_prevent_aggregation(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int, wt_for_pro_in_starting_loop_: float, wt_for_pro_in_1st_inter_sheet_loop_: float, wt_for_pro_in_3rd_inter_sheet_loop_: float) -> int: ...
@overload
def WriteToDB_ratio_of_core_heading_FWY_in_sw(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
@overload
def WriteToDB_ratio_of_core_heading_FWY_in_sw(unsignedlonglong, classstd, unsignedlong, constclasscore) -> unsignedlong: ...
def WriteToDB_rkde(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, rkde_PK_id_counter: int, tag: str, residue_number: int, residue_type: str) -> int: ...
def WriteToDB_rkde_in_strands(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, rkde_in_strands_PK_id_counter: int, tag: str, sw_can_by_sh_id: int, residue_number: int, residue_type: str, heading_direction: str) -> int: ...
def WriteToDB_sandwich(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, sandwich_PK_id_counter: int, tag: str, sw_can_by_sh_id: int, sheet_id: int, sheet_antiparellel: str, sandwich_bs_id: int, strand_is_at_edge: str, component_size: int, residue_begin: int, residue_end: int) -> int: ...
def WriteToDB_sandwich_by_AA_w_direction(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, pose_w_center_000: pyrosetta.rosetta.core.pose.Pose, sw_can_by_sh_id: int, sheet_id: int, residue_begin: int, residue_end: int) -> int: ...
def WriteToDB_sheet(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sheet_PK_id_counter: int, sheet_id: int, segment_id: int) -> int: ...
@overload
def WriteToDB_sheet_antiparallel(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sheet_id: int, antiparallel: str) -> int: ...
@overload
def WriteToDB_sheet_antiparallel(unsignedlonglong, classstd, unsignedlong, conststd) -> unsignedlong: ...
def WriteToDB_sheet_connectivity(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, sandwich_PK_id_counter: int, tag: str, sw_can_by_sh_id: int, loop_kind: str, intra_sheet_con_id: int, inter_sheet_con_id: int, LR: str, cano_LR: str, PA_by_preceding_E: str, PA_by_following_E: str, cano_PA: str, heading_direction: str, heading_parallel: str, cano_parallel_EE: str, loop_size: int, start_res: int, end_res: int) -> int: ...
def WriteToDB_sheet_id(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, new_sheet_id: int, old_sheet_id: int) -> int: ...
def WriteToDB_shortest_dis_between_facing_aro_in_sw(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int, pose: pyrosetta.rosetta.core.pose.Pose, all_distinct_sheet_ids: pyrosetta.rosetta.utility.vector1_unsigned_long, min_num_strands_in_sheet_: int) -> float: ...
def WriteToDB_starting_loop(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, dssp_pose: pyrosetta.rosetta.core.pose.Pose, sandwich_PK_id_counter: int, sw_can_by_sh_id: int, tag: str, max_starting_loop_size_: int) -> int: ...
def WriteToDB_sw_can_by_sh(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_PK_id_counter: int, tag: str, sw_can_by_sh_id_counter: int, sheet_id: int, num_strands_from_sheet: int) -> int: ...
@overload
def WriteToDB_sw_res_size(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> int: ...
@overload
def WriteToDB_sw_res_size(unsignedlonglong, classstd, unsignedlong) -> unsignedlong: ...
@overload
def WriteToDB_topology_candidate(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> int: ...
@overload
def WriteToDB_topology_candidate(unsignedlonglong, classstd, unsignedlong) -> unsignedlong: ...
def WriteToDB_turn_AA(pose: pyrosetta.rosetta.core.pose.Pose, sw_can_by_sh_id: int, i: int, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, turn_type: str) -> None: ...
def WriteToDB_turn_type(pose: pyrosetta.rosetta.core.pose.Pose, sw_can_by_sh_id: int, start_res: int, end_res: int, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, allowed_deviation_for_turn_type_id_: float) -> str: ...
@overload
def WriteToDB_whether_sw_is_not_connected_with_continuous_atoms(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int, sw_is_not_connected_with_continuous_atoms: str) -> int: ...
@overload
def WriteToDB_whether_sw_is_not_connected_with_continuous_atoms(unsignedlonglong, classstd, unsignedlong, conststd) -> unsignedlong: ...
@overload
def absolute_vec(vector: pyrosetta.rosetta.numeric.xyzVector_double_t) -> float: ...
@overload
def absolute_vec(classnumeric) -> double: ...
def cal_dis_angle_to_find_sheet(pose: pyrosetta.rosetta.core.pose.Pose, res_i_0: int, res_i_1: int, res_i_2: int, res_j_0: int, res_j_1: int, res_j_2: int) -> pyrosetta.rosetta.std.vector_double: ...
def cal_min_avg_dis_between_sheets_by_cen_res(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, dssp_pose: pyrosetta.rosetta.core.pose.Pose, all_distinct_sheet_ids: pyrosetta.rosetta.utility.vector1_unsigned_long, min_num_strands_in_sheet_: int) -> tuple[float, float]: ...
def cal_min_avg_dis_between_two_sheets_by_cen_res(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, dssp_pose: pyrosetta.rosetta.core.pose.Pose, sheet_id_1: int, sheet_id_2: int) -> tuple[float, float]: ...
@overload
def cal_min_dis_between_sheets_by_all_res(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, dssp_pose: pyrosetta.rosetta.core.pose.Pose, all_distinct_sheet_ids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> float: ...
@overload
def cal_min_dis_between_sheets_by_all_res(unsignedlonglong, classstd, classcore, classutility) -> float: ...
def cal_min_dis_between_two_sheets_by_all_res(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, dssp_pose: pyrosetta.rosetta.core.pose.Pose, sheet_id_1: int, sheet_id_2: int) -> float: ...
def cal_num_of_sheets_that_surround_this_sheet(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, dssp_pose: pyrosetta.rosetta.core.pose.Pose, all_distinct_sheet_ids: pyrosetta.rosetta.utility.vector1_unsigned_long, sheet_id: int, min_num_strands_in_sheet_: int, inter_sheet_distance_to_see_whether_a_sheet_is_surrounded_by_other_sheets_: float) -> int: ...
@overload
def cal_shortest_dis_between_facing_aro_in_sw(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, all_distinct_sheet_ids: pyrosetta.rosetta.utility.vector1_unsigned_long, min_num_strands_in_sheet_: int) -> float: ...
@overload
def cal_shortest_dis_between_facing_aro_in_sw(unsignedlonglong, classstd, constclasscore, classutility, unsignedlong) -> float: ...
def calculate_dihedral_w_4_resnums(pose: pyrosetta.rosetta.core.pose.Pose, res1_sheet_i: int, res2_sheet_i: int, res1_sheet_j: int, res2_sheet_j: int) -> float: ...
def change_sheet_id_if_possible(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, min_CA_CA_dis_: float, max_CA_CA_dis_: float, min_C_O_N_angle_: float) -> bool: ...
def check_LR(dssp_pose: pyrosetta.rosetta.core.pose.Pose, preceding_E: int, following_E: int) -> str: ...
def check_PA(dssp_pose: pyrosetta.rosetta.core.pose.Pose, residue_begin: int, residue_end: int) -> tuple[str, str]: ...
def check_canonicalness_of_LR(loop_size: int, intra_sheet: bool, LR: str) -> str: ...
def check_canonicalness_of_PA(loop_size: int, intra_sheet: bool, PA_by_preceding_E: str, PA_by_following_E: str, check_canonicalness_cutoff_: float) -> str: ...
def check_canonicalness_of_parallel_EE(loop_size: int, intra_sheet: bool, parallel_EE: str) -> str: ...
def check_heading_direction(dssp_pose: pyrosetta.rosetta.core.pose.Pose, preceding_E: int, following_E: int, check_heading_direction_by_: str) -> str: ...
@overload
def check_helix_existence(pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
@overload
def check_helix_existence(constclasscore) -> bool: ...
def check_strand_too_closeness(pose: pyrosetta.rosetta.core.pose.Pose, strand_i: SandwichFragment, strand_j: SandwichFragment, min_inter_sheet_dis_CA_CA_: float) -> bool: ...
def check_sw_by_dis(pose: pyrosetta.rosetta.core.pose.Pose, strand_i: SandwichFragment, strand_j: SandwichFragment, antiparalell: bool, min_sheet_dis_: float, max_sheet_dis_: float) -> float: ...
def check_whether_hairpin_connects_short_strand(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, start_res: int, next_start_res: int) -> bool: ...
def check_whether_same_direction_strands_connect_two_sheets_or_a_loop(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, start_res: int, next_start_res: int) -> bool: ...
def check_whether_sheets_are_connected_with_near_bb_atoms(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, dssp_pose: pyrosetta.rosetta.core.pose.Pose, sw_can_by_sh_id: int, min_N_O_dis_between_two_sheets_: float, min_N_H_O_angle_between_two_sheets_: float) -> bool: ...
@overload
def check_whether_strand_i_is_in_sheet(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, segment_id: int) -> bool: ...
@overload
def check_whether_strand_i_is_in_sheet(unsignedlonglong, classstd, unsignedlong) -> bool: ...
@overload
def check_whether_sw_by_sh_id_still_alive(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> bool: ...
@overload
def check_whether_sw_by_sh_id_still_alive(unsignedlonglong, classstd, unsignedlong) -> bool: ...
def check_whether_sw_is_not_connected_with_continuous_atoms(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, dssp_pose: pyrosetta.rosetta.core.pose.Pose, sw_can_by_sh_id: int) -> str: ...
@overload
def check_whether_this_pdb_should_be_excluded(tag: str) -> bool: ...
@overload
def check_whether_this_pdb_should_be_excluded(conststd) -> bool: ...
@overload
def check_whether_this_sheet_is_too_short(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sheet_i: int) -> bool: ...
@overload
def check_whether_this_sheet_is_too_short(unsignedlonglong, classstd, unsignedlong) -> bool: ...
def count_AA_w_direction(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, pose_w_center_000: pyrosetta.rosetta.core.pose.Pose, sw_can_by_sh_id: int, sheet_id: int, residue_begin: int, residue_end: int) -> pyrosetta.rosetta.std.vector_unsigned_long: ...
def count_AA_wo_direction(pose: pyrosetta.rosetta.core.pose.Pose, residue_begin: int, residue_end: int) -> pyrosetta.rosetta.std.vector_unsigned_long: ...
@overload
def delete_this_struct_id(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> int: ...
@overload
def delete_this_struct_id(unsignedlonglong, classstd) -> unsignedlong: ...
@overload
def delete_this_sw_can_by_sh_id_from_sw_by_comp(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> int: ...
@overload
def delete_this_sw_can_by_sh_id_from_sw_by_comp(unsignedlonglong, classstd, unsignedlong) -> unsignedlong: ...
def determine_core_heading_surface_heading_by_distance(pose_w_center_000: pyrosetta.rosetta.core.pose.Pose, residue_num: int) -> str: ...
def determine_heading_direction_by_vector(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, sw_can_by_sh_id: int, sheet_id: int, residue_begin: int, residue_end: int, ii: int) -> str: ...
def find_sheet(pose: pyrosetta.rosetta.core.pose.Pose, strand_i: SandwichFragment, strand_j: SandwichFragment, antiparalell: bool, min_CA_CA_dis_: float, max_CA_CA_dis_: float, min_C_O_N_angle_: float, care_smaller_sheet: bool) -> int: ...
def get_all_residues_in_this_sheet(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sheet_id: int) -> pyrosetta.rosetta.std.vector_unsigned_long: ...
def get_aro_residues_in_this_sheet(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, sheet_id: int) -> pyrosetta.rosetta.std.vector_unsigned_long: ...
def get_avg_dis_CA_CA(pose: pyrosetta.rosetta.core.pose.Pose, i_resnum: int, i_resnum_1: int, i_resnum_2: int, i_resnum_3: int, j_resnum: int, j_resnum_1: int, j_resnum_2: int, j_resnum_3: int, min_sheet_dis_: float, max_sheet_dis_: float) -> float: ...
def get_avg_dis_strands(pose: pyrosetta.rosetta.core.pose.Pose, strand_i: SandwichFragment, strand_j: SandwichFragment) -> float: ...
def get_central_residues_in_each_of_two_edge_strands(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, sheet_i: int, min_CA_CA_dis_: float, max_CA_CA_dis_: float) -> tuple[int, int]: ...
def get_central_residues_in_other_sheet(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int, sheet_id: int) -> pyrosetta.rosetta.std.vector_unsigned_long: ...
def get_central_residues_in_this_sheet(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sheet_id: int) -> pyrosetta.rosetta.std.vector_unsigned_long: ...
def get_chain_B_resNum(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_closest_distance_between_strands(pose: pyrosetta.rosetta.core.pose.Pose, strand_i: SandwichFragment, strand_j: SandwichFragment) -> float: ...
def get_current_bs_id_and_closest_edge_bs_id_in_different_sheet(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, sw_can_by_sh_id: int, sheet_id: int, residue_begin: int, residue_end: int) -> tuple[int, int]: ...
def get_distinct_sheet_id_from_sheet_table(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_distinct_sw_id_from_sandwich_table(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_max_sheet_id(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> int: ...
@overload
def get_max_sheet_id(unsignedlonglong, classstd) -> unsignedlong: ...
def get_next_starting_res_for_connecting_strands(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int, former_ending_res: int) -> tuple[int, int]: ...
@overload
def get_num_of_distinct_sheet_id(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> int: ...
@overload
def get_num_of_distinct_sheet_id(unsignedlonglong, classstd) -> unsignedlong: ...
@overload
def get_num_of_sheets_that_surround_this_sheet(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sheet_id: int) -> int: ...
@overload
def get_num_of_sheets_that_surround_this_sheet(unsignedlonglong, classstd, unsignedlong) -> unsignedlong: ...
@overload
def get_num_strands_in_this_sheet(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sheet_id: int) -> int: ...
@overload
def get_num_strands_in_this_sheet(unsignedlonglong, classstd, unsignedlong) -> unsignedlong: ...
@overload
def get_segment_id(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, all_strands_index: int) -> int: ...
@overload
def get_segment_id(unsignedlonglong, classstd, unsignedlong) -> unsignedlong: ...
def get_sheet_antiparallel_info(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sheet_id: int) -> str: ...
@overload
def get_size_sandwich_PK_id(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> int: ...
@overload
def get_size_sandwich_PK_id(unsignedlonglong, classstd, unsignedlong) -> unsignedlong: ...
def get_starting_res_for_connecting_strands(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int, former_res_end: int) -> tuple[int, int]: ...
def get_tag(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> str: ...
def get_vec_AA_kind(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_vec_distinct_sheet_id(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_vec_of_sw_can_by_sh_id(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_vector_of_loop_AA_distribution(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, loop_kind: str) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_vector_of_strand_AA_distribution(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, heading_direction: str, strand_location: str) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def identify_sheet_id_by_residue_end(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, residue_end: int) -> int: ...
@overload
def identify_sheet_id_by_residue_end(unsignedlonglong, classstd, unsignedlong) -> unsignedlong: ...
def is_this_strand_at_edge(pose: pyrosetta.rosetta.core.pose.Pose, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sheet_id: int, residue_begin: int, residue_end: int, min_CA_CA_dis_: float, max_CA_CA_dis_: float) -> str: ...
def is_this_strand_at_edge_by_looking_db(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, residue_begin: int) -> str: ...
def judge_facing(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, sheet_i: int, sheet_j: int, min_CA_CA_dis_: float, max_CA_CA_dis_: float, min_sheet_angle_by_four_term_cen_res_: float, max_sheet_angle_by_four_term_cen_res_: float, min_sheet_torsion_cen_res_: float, max_sheet_torsion_cen_res_: float, max_sheet_angle_with_cen_res_in_smaller_sheet_and_two_terminal_res_in_larger_sheet_: float) -> int: ...
@overload
def process_decoy(dssp_pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def process_decoy(classcore, constclasscore) -> void: ...
def report_heading_directions_of_all_AA_in_a_strand(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, sw_can_by_sh_id: int, sheet_id: int, residue_begin: int, residue_end: int) -> str: ...
def retrieve_residue_num_of_rkde(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int, dssp_code: str, heading_direction: str) -> pyrosetta.rosetta.utility.vector1_int: ...
@overload
def round_to_Real(x: float) -> float: ...
@overload
def round_to_Real(double) -> double: ...
@overload
def round_to_Size(x: float) -> int: ...
@overload
def round_to_Size(double) -> unsignedlong: ...
@overload
def round_to_float(x: float) -> float: ...
@overload
def round_to_float(float) -> float: ...
def see_edge_or_core_or_loop_or_short_edge(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, residue_num: int) -> str: ...
def see_whether_sheet_is_antiparallel(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, i_sheet: int, min_CA_CA_dis_: float, max_CA_CA_dis_: float, min_C_O_N_angle_: float) -> str: ...
def see_whether_sheets_can_be_combined(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, i_sheet: int, j_sheet: int, min_CA_CA_dis_: float, max_CA_CA_dis_: float, min_C_O_N_angle_: float) -> bool: ...
@overload
def see_whether_this_sw_has_SS_bond(struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> bool: ...
@overload
def see_whether_this_sw_has_SS_bond(unsignedlonglong, classstd) -> bool: ...
@overload
def write_AA_distribution_with_direction_to_a_file(tag: str, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> int: ...
@overload
def write_AA_distribution_with_direction_to_a_file(std, unsignedlonglong, classstd) -> unsignedlong: ...
@overload
def write_AA_distribution_without_direction_to_a_file(tag: str, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session) -> int: ...
@overload
def write_AA_distribution_without_direction_to_a_file(std, unsignedlonglong, classstd) -> unsignedlong: ...
def write_AA_kind_to_a_file(tag: str, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int, sw_res_size: int) -> int: ...
@overload
def write_chain_B_resNum_to_a_file(tag: str, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, sw_can_by_sh_id: int) -> int: ...
@overload
def write_chain_B_resNum_to_a_file(std, unsignedlonglong, classstd, unsignedlong) -> unsignedlong: ...
def write_number_of_electrostatic_interactions_of_residues_to_files(tag: str, struct_id: int, db_session: pyrosetta.rosetta.utility.sql_database.session, pose: pyrosetta.rosetta.core.pose.Pose, dssp_code: str, heading_direction: str, distance_cutoff_for_electrostatic_interactions_: float, CB_b_factor_cutoff_for_electrostatic_interactions_: float, min_primary_seq_distance_diff_for_electrostatic_interactions_: int) -> int: ...
@overload
def write_p_aa_pp_of_AAs_to_a_file(tag: str, dssp_pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
@overload
def write_p_aa_pp_of_AAs_to_a_file(std, classcore) -> unsignedlong: ...
@overload
def write_rama_of_AAs_to_a_file(tag: str, dssp_pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
@overload
def write_rama_of_AAs_to_a_file(std, classcore) -> unsignedlong: ...
