from Bio import MissingPythonDependencyError as MissingPythonDependencyError
from _typeshed import Incomplete

def to_networkx(tree): ...
def to_igraph(tree, vertex_attributes: Incomplete | None = None, edge_attributes=('color', 'width')): ...
def draw_ascii(tree, file: Incomplete | None = None, column_width: int = 80): ...
def draw(tree, label_func=..., do_show: bool = True, show_confidence: bool = True, axes: Incomplete | None = None, branch_labels: Incomplete | None = None, label_colors: Incomplete | None = None, *args, **kwargs): ...
