import pyrosetta.rosetta.RDKit
import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.std
from typing import overload

class RDMolToRestype:
    @overload
    def __init__(self, rdmol: pyrosetta.rosetta.RDKit.ROMol) -> None: ...
    @overload
    def __init__(self, arg0: RDMolToRestype) -> None: ...
    @overload
    def generate_restype(self) -> pyrosetta.rosetta.core.chemical.MutableResidueType: ...
    @overload
    def generate_restype(self, mapping: pyrosetta.rosetta.core.chemical.AtomRefMapping_void__star__unsigned_long_t) -> pyrosetta.rosetta.core.chemical.MutableResidueType: ...
    @overload
    def generate_restype(self, orig_restype: pyrosetta.rosetta.core.chemical.MutableResidueType, mapping: pyrosetta.rosetta.core.chemical.AtomRefMapping_void__star__unsigned_long_t) -> pyrosetta.rosetta.core.chemical.MutableResidueType: ...
    def index_to_vd(self) -> pyrosetta.rosetta.core.chemical.AtomRefMapping_unsigned_long_void__star__t: ...
    @overload
    def set_nbr(self, nbr: int) -> None: ...
    @overload
    def set_nbr(self, unsignedlong) -> void: ...

class RestypeToRDMol:
    @overload
    def __init__(self, res: pyrosetta.rosetta.core.chemical.MutableResidueType) -> None: ...
    @overload
    def __init__(self, res: pyrosetta.rosetta.core.chemical.MutableResidueType, neutralize: bool) -> None: ...
    @overload
    def __init__(self, res: pyrosetta.rosetta.core.chemical.MutableResidueType, neutralize: bool, keep_hydro: bool) -> None: ...
    @overload
    def __init__(self, res: pyrosetta.rosetta.core.chemical.MutableResidueType, neutralize: bool, keep_hydro: bool, sanitize: bool) -> None: ...
    @overload
    def __init__(self, res: pyrosetta.rosetta.core.chemical.MutableResidueType, neutralize: bool, keep_hydro: bool, sanitize: bool, noImplicitHs: bool) -> None: ...
    @overload
    def __init__(self, res: pyrosetta.rosetta.core.chemical.MutableResidueType, neutralize: bool, keep_hydro: bool, sanitize: bool, noImplicitHs: bool, skipHs: bool) -> None: ...
    @overload
    def __init__(self, res: pyrosetta.rosetta.core.chemical.MutableResidueType, options: RestypeToRDMolOptions) -> None: ...
    @overload
    def __init__(self, arg0: RestypeToRDMol) -> None: ...
    def get_atomIndexMap_Rd2Res(self) -> pyrosetta.rosetta.std.map_unsigned_long_unsigned_long: ...
    def index_to_vd(self) -> pyrosetta.rosetta.core.chemical.AtomRefMapping_unsigned_long_void__star__t: ...
    def vd_to_index(self) -> pyrosetta.rosetta.core.chemical.AtomRefMapping_void__star__unsigned_long_t: ...

class RestypeToRDMolOptions:
    aro2double: bool
    keep_hydro: bool
    neutralize: bool
    noImplicitHs: bool
    sanitize: bool
    skipHs: bool
    @overload
    def __init__(self, arg0: RestypeToRDMolOptions) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def assign(self) -> RestypeToRDMolOptions: ...

def convert_from_rdkit_bondtype(bondtype) -> pyrosetta.rosetta.core.chemical.BondName: ...
def convert_to_rdkit_bondtype(*args, **kwargs): ...
def get_forcefield(*args, **kwargs): ...
def get_metric_names() -> pyrosetta.rosetta.std.map_std_string_std_string: ...
def get_name(mol: pyrosetta.rosetta.RDKit.ROMol) -> str: ...
@overload
def has_explicit_Hs(mol: pyrosetta.rosetta.RDKit.ROMol) -> bool: ...
@overload
def has_explicit_Hs(constclassRDKit) -> bool: ...
@overload
def has_implicit_Hs(mol: pyrosetta.rosetta.RDKit.ROMol) -> bool: ...
@overload
def has_implicit_Hs(constclassRDKit) -> bool: ...
@overload
def has_physical_Hs(mol: pyrosetta.rosetta.RDKit.ROMol) -> bool: ...
@overload
def has_physical_Hs(constclassRDKit) -> bool: ...
@overload
def initialize_rdkit_random(seed: int) -> None: ...
@overload
def initialize_rdkit_random(int) -> void: ...
@overload
def initialize_rdkit_tracers() -> None: ...
@overload
def initialize_rdkit_tracers() -> void: ...
@overload
def label_with_index(rdmol: pyrosetta.rosetta.RDKit.ROMol) -> None: ...
@overload
def label_with_index(rdmol: pyrosetta.rosetta.RDKit.ROMol, index_prop: str) -> None: ...
@overload
def label_with_index(classRDKit, conststd) -> void: ...
@overload
def neutralize_rdmol(rdmol: pyrosetta.rosetta.RDKit.RWMol) -> None: ...
@overload
def neutralize_rdmol(rdmol: pyrosetta.rosetta.RDKit.RWMol, addHs: bool) -> None: ...
@overload
def neutralize_rdmol(classRDKit, bool) -> void: ...
@overload
def rdkit_metric(mol: pyrosetta.rosetta.RDKit.ROMol, metric: str) -> float: ...
@overload
def rdkit_metric(constclassRDKit, conststd) -> double: ...
@overload
def remove_excess_protons(rdmol: pyrosetta.rosetta.RDKit.RWMol) -> None: ...
@overload
def remove_excess_protons(classRDKit) -> void: ...
@overload
def reprotonate_rdmol(rdmol: pyrosetta.rosetta.RDKit.RWMol) -> None: ...
@overload
def reprotonate_rdmol(classRDKit) -> void: ...
@overload
def softSanitize(mol: pyrosetta.rosetta.RDKit.RWMol) -> None: ...
@overload
def softSanitize(classRDKit) -> void: ...
