import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.cereal
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.protocols.filters
import pyrosetta.rosetta.protocols.jd3
import pyrosetta.rosetta.protocols.jd3.job_summaries
import pyrosetta.rosetta.protocols.jd3.standard
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from . import cluster as cluster
from typing import overload

class JobResultID_hash:
    def __init__(self) -> None: ...
    def __call__(self, id: tuple[int, int]) -> int: ...

class MRSJob(pyrosetta.rosetta.protocols.jd3.Job):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, max_num_results: int) -> None: ...
    @overload
    def __init__(self, arg0: MRSJob) -> None: ...
    @overload
    def __init__(self, arg0: MRSJob) -> None: ...
    def assign(self) -> MRSJob: ...
    @overload
    def max_num_results(self) -> int: ...
    @overload
    def max_num_results(self) -> unsignedlong: ...
    @overload
    def metric_for_evaluation(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def metric_for_evaluation(self, classstd) -> double: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, mover_tags_by_name: pyrosetta.rosetta.std.map_std_string_std_shared_ptr_const_utility_tag_Tag_t_std_allocator_std_pair_const_std_string_std_shared_ptr_const_utility_tag_Tag_t, filter_tags_by_name: pyrosetta.rosetta.std.map_std_string_std_shared_ptr_const_utility_tag_Tag_t_std_allocator_std_pair_const_std_string_std_shared_ptr_const_utility_tag_Tag_t) -> None: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, cache: ParsedTagCache) -> None: ...
    def pose(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    def protocols(self) -> pyrosetta.rosetta.std.list_protocols_multistage_rosetta_scripts_mover_or_filter_t: ...
    def run(self) -> pyrosetta.rosetta.protocols.jd3.CompletedJobOutput: ...
    @overload
    def set_cluster_metric_tag(self, tag_for_cluster_metric: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def set_cluster_metric_tag(self, classstd) -> void: ...
    @overload
    def set_max_num_results(self, setting: int) -> None: ...
    @overload
    def set_max_num_results(self, unsignedlong) -> void: ...
    @overload
    def set_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_pose(self, classstd) -> void: ...

class MRSJobQueen(pyrosetta.rosetta.protocols.jd3.standard.StandardJobQueen):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MRSJobQueen) -> None: ...
    @overload
    def __init__(self, arg0: MRSJobQueen) -> None: ...
    def assign(self) -> MRSJobQueen: ...
    @overload
    def completed_job_summary(self, job_id: pyrosetta.rosetta.utility.StrongT_unsigned_long_protocols_jd3_GlobalJobID_t, result_index: pyrosetta.rosetta.utility.StrongT_unsigned_long_protocols_jd3_ResultIndex_t, summary: pyrosetta.rosetta.protocols.jd3.JobSummary) -> None: ...
    @overload
    def completed_job_summary(self, job: pyrosetta.rosetta.protocols.jd3.LarvalJob, result_index: pyrosetta.rosetta.utility.StrongT_unsigned_long_protocols_jd3_ResultIndex_t, summary: pyrosetta.rosetta.protocols.jd3.JobSummary) -> None: ...
    def create_initial_job_dag(self) -> pyrosetta.rosetta.protocols.jd3.JobDigraph: ...
    def determine_job_list(self, job_dag_node_index: pyrosetta.rosetta.utility.StrongT_unsigned_long_protocols_jd3_JobDAGNodeID_t, max_njobs: int) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_jd3_LarvalJob_t: ...
    @overload
    def determine_validity_of_stage_tags(self) -> None: ...
    @overload
    def determine_validity_of_stage_tags(self) -> void: ...
    def job_results_that_should_be_discarded(self) -> pyrosetta.rosetta.std.list_std_pair_unsigned_long_unsigned_long_t: ...
    def jobs_that_should_be_output(self) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_jd3_output_OutputSpecification_t: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def note_job_completed(self, job_id: pyrosetta.rosetta.utility.StrongT_unsigned_long_protocols_jd3_GlobalJobID_t, status: pyrosetta.rosetta.protocols.jd3.JobStatus, nresults: int, are_you_a_unit_test: bool) -> None: ...
    @overload
    def note_job_completed(self, structutility, structprotocols, enumprotocols, unsignedlong, bool) -> void: ...
    @overload
    def note_job_completed(self) -> None: ...
    @overload
    def note_job_completed(self, job: pyrosetta.rosetta.protocols.jd3.LarvalJob, status: pyrosetta.rosetta.protocols.jd3.JobStatus, nresults: int) -> None: ...
    @overload
    def note_job_completed(self, classstd, enumprotocols, unsignedlong) -> void: ...
    @overload
    def num_input_structs(self) -> int: ...
    @overload
    def num_input_structs(self) -> unsignedlong: ...
    @overload
    def num_results_to_keep_for_stage(self, stage: int) -> int: ...
    @overload
    def num_results_to_keep_for_stage(self, unsignedlong) -> unsignedlong: ...
    @overload
    def num_stages(self) -> int: ...
    @overload
    def num_stages(self) -> unsignedlong: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    def stage_for_global_job_id(self, global_job_id: pyrosetta.rosetta.utility.StrongT_unsigned_long_protocols_jd3_GlobalJobID_t) -> pyrosetta.rosetta.utility.StrongT_unsigned_long_protocols_jd3_JobDAGNodeID_t: ...
    def tag_manager(self) -> TagManager: ...

class MRSJobQueenChecker(MRSJobQueen):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MRSJobQueenChecker) -> None: ...
    @overload
    def __init__(self, arg0: MRSJobQueenChecker) -> None: ...
    def assign(self) -> MRSJobQueenChecker: ...
    def create_initial_job_dag(self) -> pyrosetta.rosetta.protocols.jd3.JobDigraph: ...
    def determine_job_list(self, job_dag_node_index: pyrosetta.rosetta.utility.StrongT_unsigned_long_protocols_jd3_JobDAGNodeID_t, max_njobs: int) -> pyrosetta.rosetta.std.list_std_shared_ptr_protocols_jd3_LarvalJob_t: ...
    @overload
    def estimate_number_of_bytes_needed_for_archiving(self) -> int: ...
    @overload
    def estimate_number_of_bytes_needed_for_archiving(self) -> unsignedlong: ...
    @staticmethod
    def fa_and_cen_sizes_for_archives(pose: pyrosetta.rosetta.core.pose.Pose) -> tuple[int, int]: ...

class MRSJobSummary(pyrosetta.rosetta.protocols.jd3.job_summaries.EnergyJobSummary):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, energy: float) -> None: ...
    @overload
    def __init__(self, energy: float, cluster_metric) -> None: ...
    @overload
    def __init__(self, arg0: MRSJobSummary) -> None: ...
    def assign(self) -> MRSJobSummary: ...
    def cluster_metric(self, *args, **kwargs): ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_cluster_metric(self, setting) -> None: ...
    @overload
    def set_cluster_metric(self, classstd) -> void: ...

class NoFailDataMap(pyrosetta.rosetta.basic.datacache.DataMap):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: NoFailDataMap) -> None: ...
    @overload
    def __init__(self, arg0: NoFailDataMap) -> None: ...
    def assign(self) -> NoFailDataMap: ...

class ParsedTagCache:
    data_map: NoFailDataMap
    filter_tags: pyrosetta.rosetta.std.map_std_string_std_shared_ptr_const_utility_tag_Tag_t_std_allocator_std_pair_const_std_string_std_shared_ptr_const_utility_tag_Tag_t
    input_pose_id: pyrosetta.rosetta.utility.StrongT_unsigned_long_protocols_jd3_PrelimJobNodeID_t
    mover_tags: pyrosetta.rosetta.std.map_std_string_std_shared_ptr_const_utility_tag_Tag_t_std_allocator_std_pair_const_std_string_std_shared_ptr_const_utility_tag_Tag_t
    @overload
    def __init__(self, input_pose_id_in: pyrosetta.rosetta.utility.StrongT_unsigned_long_protocols_jd3_PrelimJobNodeID_t, data_map_in: NoFailDataMap, mover_tags_in: pyrosetta.rosetta.std.map_std_string_std_shared_ptr_const_utility_tag_Tag_t_std_allocator_std_pair_const_std_string_std_shared_ptr_const_utility_tag_Tag_t, filter_tags_in: pyrosetta.rosetta.std.map_std_string_std_shared_ptr_const_utility_tag_Tag_t_std_allocator_std_pair_const_std_string_std_shared_ptr_const_utility_tag_Tag_t) -> None: ...
    @overload
    def __init__(self, arg0: ParsedTagCache) -> None: ...
    def assign(self) -> ParsedTagCache: ...

class PoseForPoseID:
    pose: pyrosetta.rosetta.core.pose.Pose
    pose_id: int
    @overload
    def __init__(self, pose_id_arg: int, pose_arg: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def __init__(self, arg0: PoseForPoseID) -> None: ...
    def assign(self) -> PoseForPoseID: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...

class SortByLowEnergy:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SortByLowEnergy) -> None: ...
    def assign(self) -> SortByLowEnergy: ...
    def __call__(self, left: tuple[int, pyrosetta.rosetta.protocols.jd3.job_summaries.StandardPoseJobSummary], right: tuple[int, pyrosetta.rosetta.protocols.jd3.job_summaries.StandardPoseJobSummary]) -> bool: ...

class TagManager:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, num_input_pose_ids: int) -> None: ...
    @overload
    def __init__(self, arg0: TagManager) -> None: ...
    def assign(self) -> TagManager: ...
    def generate_data_for_input_pose_id(self, input_pose_id: pyrosetta.rosetta.utility.StrongT_unsigned_long_protocols_jd3_PrelimJobNodeID_t, nstruct_ind: pyrosetta.rosetta.utility.StrongT_unsigned_long_protocols_jd3_NStructIndex_t) -> ParsedTagCache: ...
    @overload
    def load(self, arc: pyrosetta.rosetta.cereal.BinaryInputArchive) -> None: ...
    @overload
    def load(self, classcereal) -> void: ...
    @overload
    def register_data_tags_for_input_pose_id(self, input_pose_id: pyrosetta.rosetta.utility.StrongT_unsigned_long_protocols_jd3_PrelimJobNodeID_t, tags_in_order: pyrosetta.rosetta.std.list_std_shared_ptr_const_utility_tag_Tag_t) -> None: ...
    @overload
    def register_data_tags_for_input_pose_id(self, structutility, structprotocols, constclassstd) -> void: ...
    @overload
    def save(self, arc: pyrosetta.rosetta.cereal.BinaryOutputArchive) -> None: ...
    @overload
    def save(self, classcereal) -> void: ...
    @overload
    def set_common_data_tags(self, tags_in_order: pyrosetta.rosetta.std.list_std_shared_ptr_const_utility_tag_Tag_t) -> None: ...
    @overload
    def set_common_data_tags(self, constclassstd) -> void: ...
    @overload
    def set_num_input_pose_ids(self, num_input_pose_ids: int) -> None: ...
    @overload
    def set_num_input_pose_ids(self, unsignedlong) -> void: ...
    def tag_list_for_input_pose_id(self) -> pyrosetta.rosetta.std.vector_std_shared_ptr_std_list_std_shared_ptr_const_utility_tag_Tag_t: ...

class mover_or_filter:
    filter: pyrosetta.rosetta.protocols.filters.Filter
    is_mover: bool
    mover: pyrosetta.rosetta.protocols.moves.Mover
    @overload
    def __init__(self, in_mover: pyrosetta.rosetta.protocols.moves.Mover) -> None: ...
    @overload
    def __init__(self, in_filter: pyrosetta.rosetta.protocols.filters.Filter) -> None: ...
    @overload
    def __init__(self, arg0: mover_or_filter) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def assign(self, src: mover_or_filter) -> mover_or_filter: ...
    def deep_clone(self) -> mover_or_filter: ...
