import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.grid
import pyrosetta.rosetta.core.import_pose.atom_tree_diffs
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.scoring.constraints
import pyrosetta.rosetta.core.scoring.func
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.protocols.filters
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.protocols.parser
import pyrosetta.rosetta.protocols.rigid
import pyrosetta.rosetta.protocols.toolbox.match_enzdes_util
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.io
import pyrosetta.rosetta.utility.tag
from . import ga_ligand_dock as ga_ligand_dock, ligand_options as ligand_options, rdf as rdf
from typing import ClassVar, overload

Gaussian: Distribution
Uniform: Distribution

class AddHydrogen(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, residue: int, connection_id: int) -> None: ...
    @overload
    def __init__(self, arg0: AddHydrogen) -> None: ...
    @overload
    def __init__(self, arg0: AddHydrogen) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> AddHydrogen: ...
    def get_name(self) -> str: ...

class AddHydrogens(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AddHydrogens) -> None: ...
    @overload
    def __init__(self, arg0: AddHydrogens) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> AddHydrogens: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class AddHydrogensCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AddHydrogensCreator) -> None: ...
    @overload
    def __init__(self, arg0: AddHydrogensCreator) -> None: ...
    def assign(self) -> AddHydrogensCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class AtomCountFilter(pyrosetta.rosetta.protocols.filters.Filter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, chain: str, heavy_atom_limit: int) -> None: ...
    @overload
    def __init__(self, arg0: AtomCountFilter) -> None: ...
    @overload
    def __init__(self, arg0: AtomCountFilter) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def apply(self, constclasscore) -> bool: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def name(self) -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class AtomCountFilterCreator(pyrosetta.rosetta.protocols.filters.FilterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: AtomCountFilterCreator) -> None: ...
    @overload
    def __init__(self, arg0: AtomCountFilterCreator) -> None: ...
    def assign(self) -> AtomCountFilterCreator: ...
    def create_filter(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ChainExistsFilter(pyrosetta.rosetta.protocols.filters.Filter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, chain: str) -> None: ...
    @overload
    def __init__(self, arg0: ChainExistsFilter) -> None: ...
    @overload
    def __init__(self, arg0: ChainExistsFilter) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def apply(self, constclasscore) -> bool: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def name(self) -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class ChainExistsFilterCreator(pyrosetta.rosetta.protocols.filters.FilterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ChainExistsFilterCreator) -> None: ...
    @overload
    def __init__(self, arg0: ChainExistsFilterCreator) -> None: ...
    def assign(self) -> ChainExistsFilterCreator: ...
    def create_filter(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class CompleteConnectionsFilter(pyrosetta.rosetta.protocols.filters.Filter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, chain: str) -> None: ...
    @overload
    def __init__(self, arg0: CompleteConnectionsFilter) -> None: ...
    @overload
    def __init__(self, arg0: CompleteConnectionsFilter) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def apply(self, constclasscore) -> bool: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def name(self) -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class CompleteConnectionsFilterCreator(pyrosetta.rosetta.protocols.filters.FilterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CompleteConnectionsFilterCreator) -> None: ...
    @overload
    def __init__(self, arg0: CompleteConnectionsFilterCreator) -> None: ...
    def assign(self) -> CompleteConnectionsFilterCreator: ...
    def create_filter(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class CompoundTranslate(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CompoundTranslate) -> None: ...
    @overload
    def __init__(self, arg0: CompoundTranslate) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> CompoundTranslate: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, datamap: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class CompoundTranslateCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CompoundTranslateCreator) -> None: ...
    @overload
    def __init__(self, arg0: CompoundTranslateCreator) -> None: ...
    def assign(self) -> CompoundTranslateCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ComputeLigandRDF(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ComputeLigandRDF) -> None: ...
    @overload
    def __init__(self, arg0: ComputeLigandRDF) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> ComputeLigandRDF: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data_map: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class ComputeLigandRDFCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ComputeLigandRDFCreator) -> None: ...
    @overload
    def __init__(self, arg0: ComputeLigandRDFCreator) -> None: ...
    def assign(self) -> ComputeLigandRDFCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class Distribution:
    __members__: ClassVar[dict] = ...  # read-only
    Gaussian: ClassVar[Distribution] = ...
    Uniform: ClassVar[Distribution] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class DistributionMap(pyrosetta.rosetta.utility.SingletonBase_protocols_ligand_docking_DistributionMap_t):
    def __init__(self, *args, **kwargs) -> None: ...
    def __getitem__(self, distribution: str) -> Distribution: ...

class FinalMinimizer(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: pyrosetta.rosetta.core.scoring.ScoreFunction, arg1) -> None: ...
    @overload
    def __init__(self, score_fxn: pyrosetta.rosetta.core.scoring.ScoreFunction, movemap_builder, remove_constraints: bool) -> None: ...
    @overload
    def __init__(self, arg0: FinalMinimizer) -> None: ...
    @overload
    def __init__(self, arg0: FinalMinimizer) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> FinalMinimizer: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class FinalMinimizerCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: FinalMinimizerCreator) -> None: ...
    @overload
    def __init__(self, arg0: FinalMinimizerCreator) -> None: ...
    def assign(self) -> FinalMinimizerCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class GrowLigand(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, chain: str) -> None: ...
    @overload
    def __init__(self, arg0: GrowLigand) -> None: ...
    @overload
    def __init__(self, arg0: GrowLigand) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> GrowLigand: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class GrowLigandCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GrowLigandCreator) -> None: ...
    @overload
    def __init__(self, arg0: GrowLigandCreator) -> None: ...
    def assign(self) -> GrowLigandCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class HBondAcceptorFilter(pyrosetta.rosetta.protocols.filters.Filter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, chain: str, hbond_donor_limit: int) -> None: ...
    @overload
    def __init__(self, arg0: HBondAcceptorFilter) -> None: ...
    @overload
    def __init__(self, arg0: HBondAcceptorFilter) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def apply(self, constclasscore) -> bool: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def name(self) -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class HBondAcceptorFilterCreator(pyrosetta.rosetta.protocols.filters.FilterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: HBondAcceptorFilterCreator) -> None: ...
    @overload
    def __init__(self, arg0: HBondAcceptorFilterCreator) -> None: ...
    def assign(self) -> HBondAcceptorFilterCreator: ...
    def create_filter(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class HBondDonorFilter(pyrosetta.rosetta.protocols.filters.Filter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, chain: str, hbond_donor_limit: int) -> None: ...
    @overload
    def __init__(self, arg0: HBondDonorFilter) -> None: ...
    @overload
    def __init__(self, arg0: HBondDonorFilter) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def apply(self, constclasscore) -> bool: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def name(self) -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class HBondDonorFilterCreator(pyrosetta.rosetta.protocols.filters.FilterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: HBondDonorFilterCreator) -> None: ...
    @overload
    def __init__(self, arg0: HBondDonorFilterCreator) -> None: ...
    def assign(self) -> HBondDonorFilterCreator: ...
    def create_filter(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class HeavyAtomFilter(pyrosetta.rosetta.protocols.filters.Filter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, chain: str, heavy_atom_limit: int) -> None: ...
    @overload
    def __init__(self, arg0: HeavyAtomFilter) -> None: ...
    @overload
    def __init__(self, arg0: HeavyAtomFilter) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def apply(self, constclasscore) -> bool: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def name(self) -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def report_sm(self) -> float: ...
    @overload
    def report_sm(self, constclasscore) -> double: ...

class HeavyAtomFilterCreator(pyrosetta.rosetta.protocols.filters.FilterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: HeavyAtomFilterCreator) -> None: ...
    @overload
    def __init__(self, arg0: HeavyAtomFilterCreator) -> None: ...
    def assign(self) -> HeavyAtomFilterCreator: ...
    def create_filter(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class HighResDocker(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: HighResDocker) -> None: ...
    @overload
    def __init__(self, arg0: HighResDocker) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: pyrosetta.rosetta.core.scoring.ScoreFunction, arg3) -> None: ...
    @overload
    def __init__(self, num_cycles: int, repack_every_Nth: int, score_fxn: pyrosetta.rosetta.core.scoring.ScoreFunction, movemap_builder, resfile: str) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    @overload
    def apply(self, poses: pyrosetta.rosetta.utility.vector1_core_pose_Pose, current_scores: pyrosetta.rosetta.utility.vector1_double, qsar_chars: pyrosetta.rosetta.utility.vector1_char, cycle: int) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose, current_score: float, qsar_char: str, cycle: int) -> None: ...
    def assign(self) -> HighResDocker: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_all_residues(self, input: bool) -> None: ...
    @overload
    def set_all_residues(self, bool) -> void: ...
    @overload
    def set_allow_repacking(self, input: bool) -> None: ...
    @overload
    def set_allow_repacking(self, bool) -> void: ...

class HighResDockerCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: HighResDockerCreator) -> None: ...
    @overload
    def __init__(self, arg0: HighResDockerCreator) -> None: ...
    def assign(self) -> HighResDockerCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class HighResEnsemble(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: HighResEnsemble) -> None: ...
    @overload
    def __init__(self, arg0: HighResEnsemble) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> HighResEnsemble: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def reinitialize_for_each_job(self) -> bool: ...
    @overload
    def reinitialize_for_each_job(self) -> bool: ...

class HighResEnsembleCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: HighResEnsembleCreator) -> None: ...
    @overload
    def __init__(self, arg0: HighResEnsembleCreator) -> None: ...
    def assign(self) -> HighResEnsembleCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class InterfaceBuilder:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: InterfaceBuilder) -> None: ...
    def assign(self) -> InterfaceBuilder: ...
    def build(self, *args, **kwargs): ...
    @staticmethod
    def element_name() -> str: ...
    def get_ligand_areas(self) -> pyrosetta.rosetta.std.map_char_std_shared_ptr_protocols_ligand_docking_LigandArea_t_std_allocator_std_pair_const_char_std_shared_ptr_protocols_ligand_docking_LigandArea_t: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, datamap: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class InterfaceBuilderLoader(pyrosetta.rosetta.protocols.parser.DataLoader):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: InterfaceBuilderLoader) -> None: ...
    @overload
    def __init__(self, arg0: InterfaceBuilderLoader) -> None: ...
    def assign(self) -> InterfaceBuilderLoader: ...
    @staticmethod
    def interface_builder_ct_namer(element_name: str) -> str: ...
    @overload
    def load_data(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def load_data(self, classstd, classbasic) -> void: ...
    @staticmethod
    def loader_name() -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class InterfaceBuilderLoaderCreator(pyrosetta.rosetta.protocols.parser.DataLoaderCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: InterfaceBuilderLoaderCreator) -> None: ...
    @overload
    def __init__(self, arg0: InterfaceBuilderLoaderCreator) -> None: ...
    def assign(self) -> InterfaceBuilderLoaderCreator: ...
    def create_loader(self) -> pyrosetta.rosetta.protocols.parser.DataLoader: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
    def schema_ct_naming_function(self, *args, **kwargs): ...

class InterfaceScoreCalculator(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: InterfaceScoreCalculator) -> None: ...
    @overload
    def __init__(self, arg0: InterfaceScoreCalculator) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> InterfaceScoreCalculator: ...
    @overload
    def chains(self, chains: pyrosetta.rosetta.std.vector_std_string) -> None: ...
    @overload
    def chains(self, constclassstd) -> void: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def grid_set_prototype(self, grid_prototype) -> None: ...
    @overload
    def grid_set_prototype(self, classstd) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def native_ensemble_best(self, setting: bool) -> None: ...
    @overload
    def native_ensemble_best(self, bool) -> void: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def score_fxn(self, score_fxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def score_fxn(self, constclassstd) -> void: ...
    @overload
    def set_native(self, setting: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_native(self, classstd) -> void: ...

class InterfaceScoreCalculatorCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: InterfaceScoreCalculatorCreator) -> None: ...
    @overload
    def __init__(self, arg0: InterfaceScoreCalculatorCreator) -> None: ...
    def assign(self) -> InterfaceScoreCalculatorCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class LigandArea:
    Calpha_restraints_: float
    add_nbr_radius_: bool
    all_atom_mode_: bool
    chain_: str
    cutoff_: float
    high_res_angstroms_: float
    high_res_degrees_: float
    minimize_ligand_: float
    tether_ligand_: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LigandArea) -> None: ...
    def assign(self) -> LigandArea: ...
    @staticmethod
    def element_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class LigandAreaLoader(pyrosetta.rosetta.protocols.parser.DataLoader):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LigandAreaLoader) -> None: ...
    @overload
    def __init__(self, arg0: LigandAreaLoader) -> None: ...
    def assign(self) -> LigandAreaLoader: ...
    @staticmethod
    def ligand_area_ct_namer(element_name: str) -> str: ...
    @overload
    def load_data(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def load_data(self, classstd, classbasic) -> void: ...
    @staticmethod
    def loader_name() -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class LigandAreaLoaderCreator(pyrosetta.rosetta.protocols.parser.DataLoaderCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LigandAreaLoaderCreator) -> None: ...
    @overload
    def __init__(self, arg0: LigandAreaLoaderCreator) -> None: ...
    def assign(self) -> LigandAreaLoaderCreator: ...
    def create_loader(self) -> pyrosetta.rosetta.protocols.parser.DataLoader: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
    def schema_ct_naming_function(self, *args, **kwargs): ...

class LigandBaseProtocol(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LigandBaseProtocol) -> None: ...
    @overload
    def __init__(self, arg0: LigandBaseProtocol) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> LigandBaseProtocol: ...
    @overload
    @staticmethod
    def get_ligand_id(pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    @staticmethod
    def get_ligand_id(constclasscore) -> unsignedlong: ...
    @overload
    @staticmethod
    def get_ligand_id(pose: pyrosetta.rosetta.core.pose.Pose, jump_id: int) -> int: ...
    @overload
    @staticmethod
    def get_ligand_id(constclasscore, unsignedlong) -> unsignedlong: ...
    @overload
    @staticmethod
    def get_ligand_jump_id(pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    @staticmethod
    def get_ligand_jump_id(constclasscore) -> unsignedlong: ...
    def get_name(self) -> str: ...
    @overload
    def get_non_bb_clashing_rotamers(self, pose: pyrosetta.rosetta.core.pose.Pose, seqpos: int, scofx: pyrosetta.rosetta.core.scoring.ScoreFunction, accepted_rotamers: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t) -> None: ...
    @overload
    def get_non_bb_clashing_rotamers(self, constclasscore, unsignedlong, classstd, classutility) -> void: ...
    def get_scorefxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    def reorder_foldtree_around_mobile_regions(self, pose: pyrosetta.rosetta.core.pose.Pose, jump_id: int, mobile_bb: pyrosetta.rosetta.utility.vector1_bool, lig_id: int) -> None: ...
    @overload
    def restrain_protein_Calphas(self, pose: pyrosetta.rosetta.core.pose.Pose, is_restrained: pyrosetta.rosetta.utility.vector1_bool, restr_func: pyrosetta.rosetta.core.scoring.func.Func) -> None: ...
    @overload
    def restrain_protein_Calphas(self, classcore, constclassutility, classstd) -> void: ...
    def shared_from_this(self) -> LigandBaseProtocol: ...

class LigandDesign(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LigandDesign) -> None: ...
    @overload
    def __init__(self, arg0: LigandDesign) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> LigandDesign: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class LigandDesignCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: LigandDesignCreator) -> None: ...
    @overload
    def __init__(self, arg0: LigandDesignCreator) -> None: ...
    def assign(self) -> LigandDesignCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class LigandDockProtocol(LigandBaseProtocol):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: bool, arg2: bool, arg3: bool, arg4: bool, arg5: float, arg6: float) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: bool, arg2: bool, arg3: bool, arg4: bool, arg5: float, arg6: float, arg7: float) -> None: ...
    @overload
    def __init__(self, protocol: str, minimize_ligand: bool, minimize_backbone: bool, tether_ligand: bool, mutate_same_name3: bool, ligand_chi_stddev_deg: float, protein_CA_stddev_Ang: float, ligand_tether_stddev_Ang_: float, ligand_shear_moves: int) -> None: ...
    def add_start_from(self, x: float, y: float, z: float) -> None: ...
    @overload
    def append_ligand_docking_scores(self, before: pyrosetta.rosetta.core.pose.Pose, after: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, scores: pyrosetta.rosetta.std.map_std_string_double) -> None: ...
    @overload
    def append_ligand_docking_scores(self, before: pyrosetta.rosetta.core.pose.Pose, after: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, scores: pyrosetta.rosetta.std.map_std_string_double, constraint_io: pyrosetta.rosetta.protocols.toolbox.match_enzdes_util.EnzConstraintIO) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> LigandDockProtocol: ...
    def get_name(self) -> str: ...
    def shared_from_this(self) -> LigandDockProtocol: ...

class Ligand_info:
    atr: int
    jump: pyrosetta.rosetta.core.kinematics.Jump
    rep: int
    residues: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t
    tag_along_residues: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, residues: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t, atr: int, rep: int) -> None: ...
    @overload
    def __init__(self, residues: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t, scores: tuple[int, int], jump: pyrosetta.rosetta.core.kinematics.Jump) -> None: ...
    @overload
    def __init__(self, arg0: Ligand_info) -> None: ...
    def assign(self) -> Ligand_info: ...
    def get_residues(self) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t: ...

class MinimizeBackbone(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, interface_builder: InterfaceBuilder) -> None: ...
    @overload
    def __init__(self, arg0: MinimizeBackbone) -> None: ...
    @overload
    def __init__(self, arg0: MinimizeBackbone) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> MinimizeBackbone: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def remove_constraints(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def remove_constraints(self, classcore) -> void: ...
    @overload
    def remove_cutpoints(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def remove_cutpoints(self, classcore) -> void: ...

class MinimizeBackboneCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MinimizeBackboneCreator) -> None: ...
    @overload
    def __init__(self, arg0: MinimizeBackboneCreator) -> None: ...
    def assign(self) -> MinimizeBackboneCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class MinimizeLigand(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, chain: str, degrees: float) -> None: ...
    @overload
    def __init__(self, arg0: MinimizeLigand) -> None: ...
    @overload
    def __init__(self, arg0: MinimizeLigand) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> MinimizeLigand: ...
    def get_name(self) -> str: ...
    @overload
    def remove_constraints(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def remove_constraints(self, classcore) -> void: ...
    def __eq__(self, chain: str) -> bool: ...

class MolarMassFilter(pyrosetta.rosetta.protocols.filters.Filter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, chain: str, mass_limit: int) -> None: ...
    @overload
    def __init__(self, arg0: MolarMassFilter) -> None: ...
    @overload
    def __init__(self, arg0: MolarMassFilter) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def apply(self, constclasscore) -> bool: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def name(self) -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class MolarMassFilterCreator(pyrosetta.rosetta.protocols.filters.FilterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MolarMassFilterCreator) -> None: ...
    @overload
    def __init__(self, arg0: MolarMassFilterCreator) -> None: ...
    def assign(self) -> MolarMassFilterCreator: ...
    def create_filter(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class MolecularMassFilter(pyrosetta.rosetta.protocols.filters.Filter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, chain: str, mass_limit: int) -> None: ...
    @overload
    def __init__(self, arg0: MolecularMassFilter) -> None: ...
    @overload
    def __init__(self, arg0: MolecularMassFilter) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> bool: ...
    @overload
    def apply(self, constclasscore) -> bool: ...
    @staticmethod
    def class_name() -> str: ...
    def clone(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def name(self) -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class MolecularMassFilterCreator(pyrosetta.rosetta.protocols.filters.FilterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MolecularMassFilterCreator) -> None: ...
    @overload
    def __init__(self, arg0: MolecularMassFilterCreator) -> None: ...
    def assign(self) -> MolecularMassFilterCreator: ...
    def create_filter(self) -> pyrosetta.rosetta.protocols.filters.Filter: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class MoveMapBuilder:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MoveMapBuilder) -> None: ...
    @overload
    def __init__(self, sc: InterfaceBuilder, bb: InterfaceBuilder, minimize_water: bool) -> None: ...
    def assign(self) -> MoveMapBuilder: ...
    def build(self) -> pyrosetta.rosetta.core.kinematics.MoveMap: ...
    @staticmethod
    def element_name() -> str: ...
    def get_bb_interface_builder(self) -> InterfaceBuilder: ...
    def get_sc_interface_builder(self) -> InterfaceBuilder: ...
    @overload
    def minimize_backbone(self) -> bool: ...
    @overload
    def minimize_backbone(self) -> bool: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, datamap: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class MoveMapBuilderLoader(pyrosetta.rosetta.protocols.parser.DataLoader):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MoveMapBuilderLoader) -> None: ...
    @overload
    def __init__(self, arg0: MoveMapBuilderLoader) -> None: ...
    def assign(self) -> MoveMapBuilderLoader: ...
    @overload
    def load_data(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def load_data(self, classstd, classbasic) -> void: ...
    @staticmethod
    def loader_name() -> str: ...
    @staticmethod
    def movemap_builder_ct_namer(element_name: str) -> str: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class MoveMapBuilderLoaderCreator(pyrosetta.rosetta.protocols.parser.DataLoaderCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MoveMapBuilderLoaderCreator) -> None: ...
    @overload
    def __init__(self, arg0: MoveMapBuilderLoaderCreator) -> None: ...
    def assign(self) -> MoveMapBuilderLoaderCreator: ...
    def create_loader(self) -> pyrosetta.rosetta.protocols.parser.DataLoader: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...
    def schema_ct_naming_function(self, *args, **kwargs): ...

class ProtLigEnsemble(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ProtLigEnsemble) -> None: ...
    @overload
    def __init__(self, arg0: ProtLigEnsemble) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> ProtLigEnsemble: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def reinitialize_for_each_job(self) -> bool: ...
    @overload
    def reinitialize_for_each_job(self) -> bool: ...

class ProtLigEnsembleCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ProtLigEnsembleCreator) -> None: ...
    @overload
    def __init__(self, arg0: ProtLigEnsembleCreator) -> None: ...
    def assign(self) -> ProtLigEnsembleCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ProtLigPair_info:
    bind_data: float
    has_bind: bool
    lig_chain: str
    mut_resid: int
    mut_target: str
    wild_type: bool
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ProtLigPair_info) -> None: ...
    def assign(self) -> ProtLigPair_info: ...
    def print_mut_string(self) -> str: ...
    def print_string(self) -> str: ...

class RandomConformerMover(pyrosetta.rosetta.protocols.moves.Mover):
    def __init__(self, resid: int) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RandomConformerMover: ...
    def get_name(self) -> str: ...

class RandomConformers(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RandomConformers) -> None: ...
    @overload
    def __init__(self, arg0: RandomConformers) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RandomConformers: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class RandomConformersCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RandomConformersCreator) -> None: ...
    @overload
    def __init__(self, arg0: RandomConformersCreator) -> None: ...
    def assign(self) -> RandomConformersCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class ResidueTorsionRestraints:
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, resid: int, stddev_degrees: float) -> None: ...
    @overload
    def __init__(self, arg0: ResidueTorsionRestraints) -> None: ...
    def assign(self) -> ResidueTorsionRestraints: ...
    @overload
    def disable(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def disable(self, classcore) -> void: ...
    @overload
    def enable(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def enable(self, classcore) -> void: ...
    def __eq__(self, other: ResidueTorsionRestraints) -> bool: ...

class RigidSearchMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, jump_id: int, num_trials: int, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: RigidSearchMover) -> None: ...
    @overload
    def __init__(self, arg0: RigidSearchMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> RigidSearchMover: ...
    def get_name(self) -> str: ...
    @overload
    def recover_low(self) -> bool: ...
    @overload
    def recover_low(self) -> bool: ...
    @overload
    def recover_low(self, b: bool) -> None: ...
    @overload
    def recover_low(self, bool) -> void: ...
    def rotate_around_atom(self, rsd: int, atom: int) -> None: ...
    @overload
    def rotate_around_downstream_centroid(self) -> None: ...
    @overload
    def rotate_around_downstream_centroid(self) -> void: ...
    @overload
    def rotation(self) -> float: ...
    @overload
    def rotation(self) -> double: ...
    @overload
    def rotation(self, degrees: float) -> None: ...
    @overload
    def rotation(self, double) -> void: ...
    @overload
    def translation(self) -> float: ...
    @overload
    def translation(self) -> double: ...
    @overload
    def translation(self, angstroms: float) -> None: ...
    @overload
    def translation(self, double) -> void: ...

class Rotate(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rotate_info: Rotate_info) -> None: ...
    @overload
    def __init__(self, arg0: Rotate) -> None: ...
    @overload
    def __init__(self, arg0: Rotate) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> Rotate: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def set_chain(self, chain: str) -> None: ...
    @overload
    def set_chain(self, conststd) -> void: ...
    @overload
    def set_chain_id(self, chain_id: int) -> None: ...
    @overload
    def set_chain_id(self, unsignedlong) -> void: ...

class RotateCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RotateCreator) -> None: ...
    @overload
    def __init__(self, arg0: RotateCreator) -> None: ...
    def assign(self) -> RotateCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class Rotate_info:
    cycles: int
    degrees: float
    distribution: Distribution
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Rotate_info) -> None: ...
    def assign(self) -> Rotate_info: ...
    @overload
    def chain_id(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def chain_id(self, constclasscore) -> unsignedlong: ...
    @overload
    def chain_letter(self, pose: pyrosetta.rosetta.core.pose.Pose) -> str: ...
    @overload
    def chain_letter(self, constclasscore) -> char: ...
    @overload
    def jump_id(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def jump_id(self, constclasscore) -> unsignedlong: ...
    @overload
    def set_chain_id(self, id: int) -> None: ...
    @overload
    def set_chain_id(self, unsignedlong) -> void: ...
    @overload
    def set_chain_letter(self, str: str) -> None: ...
    @overload
    def set_chain_letter(self, conststd) -> void: ...
    @overload
    def set_tag_along_chains(self, setting: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def set_tag_along_chains(self, constclassutility) -> void: ...
    def tag_along_chain_ids(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def tag_along_jumps(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def tag_along_residues(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...

class Rotates(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Rotates) -> None: ...
    @overload
    def __init__(self, arg0: Rotates) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> Rotates: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class RotatesCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RotatesCreator) -> None: ...
    @overload
    def __init__(self, arg0: RotatesCreator) -> None: ...
    def assign(self) -> RotatesCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class SlideTogether(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, chain: str) -> None: ...
    @overload
    def __init__(self, arg0: SlideTogether) -> None: ...
    @overload
    def __init__(self, arg0: SlideTogether) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> SlideTogether: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class SlideTogetherCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: SlideTogetherCreator) -> None: ...
    @overload
    def __init__(self, arg0: SlideTogetherCreator) -> None: ...
    def assign(self) -> SlideTogetherCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class StartFrom(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: StartFrom) -> None: ...
    @overload
    def __init__(self, arg0: StartFrom) -> None: ...
    @overload
    def add_coords(self, coords: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def add_coords(self, coords: pyrosetta.rosetta.numeric.xyzVector_double_t, pdb_tag: str) -> None: ...
    @overload
    def add_coords(self, constclassnumeric, conststd) -> void: ...
    @overload
    def add_coords_hash(self, coords: pyrosetta.rosetta.numeric.xyzVector_double_t, hash_value: str) -> None: ...
    @overload
    def add_coords_hash(self, constclassnumeric, conststd) -> void: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> StartFrom: ...
    @overload
    def chain(self, chains: pyrosetta.rosetta.utility.vector1_std_string) -> None: ...
    @overload
    def chain(self, constclassutility) -> void: ...
    @overload
    def chain(self, chain: str) -> None: ...
    @overload
    def chain(self, conststd) -> void: ...
    @overload
    def chain(self) -> str: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def parse_pdb_file(self, filename: str) -> None: ...
    @overload
    def parse_pdb_file(self, filename: str, atom_name: str) -> None: ...
    @overload
    def parse_pdb_file(self, filename: str, atom_name: str, tag: str) -> None: ...
    @overload
    def parse_startfrom_file(self, filename: str) -> None: ...
    @overload
    def parse_startfrom_file(self, conststd) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def use_nbr(self, setting: bool) -> None: ...
    @overload
    def use_nbr(self, bool) -> void: ...
    @overload
    def use_nbr(self) -> bool: ...
    @overload
    def use_nbr(self) -> bool: ...

class StartFromCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: StartFromCreator) -> None: ...
    @overload
    def __init__(self, arg0: StartFromCreator) -> None: ...
    def assign(self) -> StartFromCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class TetherLigand(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, chain: str, angstroms: float) -> None: ...
    @overload
    def __init__(self, arg0: TetherLigand) -> None: ...
    @overload
    def __init__(self, arg0: TetherLigand) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> TetherLigand: ...
    def get_ligand_tether(self) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
    def get_name(self) -> str: ...
    @overload
    def release(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def release(self, classcore) -> void: ...

class Transform(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, grid_prototype, chain: str, box_size: float, move_distance: float, angle: float, cycles: int, temp: float) -> None: ...
    @overload
    def __init__(self, arg0: Transform) -> None: ...
    @overload
    def __init__(self, arg0: Transform) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> Transform: ...
    @overload
    def change_conformer(self, residue: pyrosetta.rosetta.core.conformation.UltraLightResidue) -> None: ...
    @overload
    def change_conformer(self, classcore) -> void: ...
    @overload
    def check_conformers(self, starting_residue: pyrosetta.rosetta.core.conformation.UltraLightResidue) -> bool: ...
    @overload
    def check_conformers(self, classcore) -> bool: ...
    @overload
    def check_grid(self, ligand_residue: pyrosetta.rosetta.core.conformation.UltraLightResidue) -> bool: ...
    @overload
    def check_grid(self, ligand_residue: pyrosetta.rosetta.core.conformation.UltraLightResidue, distance: float) -> bool: ...
    @overload
    def check_grid(self, classcore, double) -> bool: ...
    def check_rmsd(self, start: pyrosetta.rosetta.core.conformation.UltraLightResidue, current: pyrosetta.rosetta.core.conformation.UltraLightResidue) -> bool: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def convert_to_full_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, residue: pyrosetta.rosetta.core.conformation.UltraLightResidue, chain_id: int) -> float: ...
    @overload
    def dump_conformer(self, residue: pyrosetta.rosetta.core.conformation.UltraLightResidue, output: pyrosetta.rosetta.utility.io.ozstream) -> None: ...
    @overload
    def dump_conformer(self, classcore, classutility) -> void: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def make_multi_pose_grids(self, center: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def make_multi_pose_grids(self, classnumeric) -> void: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data_map: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    def randomize_ligand(self, residue: pyrosetta.rosetta.core.conformation.UltraLightResidue, distance: float, angle: float) -> None: ...
    @overload
    def recommended_box_size(self) -> float: ...
    @overload
    def recommended_box_size(self, success_rate: float) -> float: ...
    @overload
    def recommended_box_size(self, double) -> double: ...
    @overload
    def recommended_grid_size(self) -> float: ...
    @overload
    def recommended_grid_size(self, success_rate: float) -> float: ...
    @overload
    def recommended_grid_size(self, double) -> double: ...
    def score_constraints(self, pose: pyrosetta.rosetta.core.pose.Pose, residue: pyrosetta.rosetta.core.conformation.UltraLightResidue, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> float: ...
    @overload
    def score_ligand(self, ligand_residue: pyrosetta.rosetta.core.conformation.UltraLightResidue) -> float: ...
    @overload
    def score_ligand(self, classcore) -> double: ...
    @overload
    def setup_conformers(self, pose: pyrosetta.rosetta.core.pose.Pose, begin: int) -> None: ...
    @overload
    def setup_conformers(self, classcore, unsignedlong) -> void: ...
    @overload
    def transform_ligand(self, residue: pyrosetta.rosetta.core.conformation.UltraLightResidue) -> None: ...
    @overload
    def transform_ligand(self, classcore) -> void: ...

class TransformCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TransformCreator) -> None: ...
    @overload
    def __init__(self, arg0: TransformCreator) -> None: ...
    def assign(self) -> TransformCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class TransformEnsemble(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, grid_set_prototype, chains: pyrosetta.rosetta.utility.vector1_std_string, box_size: float, move_distance: float, angle: float, cycles: int, temp: float) -> None: ...
    @overload
    def __init__(self, arg0: TransformEnsemble) -> None: ...
    @overload
    def __init__(self, arg0: TransformEnsemble) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> TransformEnsemble: ...
    @overload
    def change_conformer(self, ligand_residue: pyrosetta.rosetta.core.conformation.UltraLightResidue, reference_residue: pyrosetta.rosetta.core.conformation.UltraLightResidue, resid: int) -> None: ...
    @overload
    def change_conformer(self, classcore, constclasscore, unsignedlong) -> void: ...
    @overload
    def change_conformers(self, ligand_residues: pyrosetta.rosetta.utility.vector1_core_conformation_UltraLightResidue, reference_residues: pyrosetta.rosetta.utility.vector1_core_conformation_UltraLightResidue) -> None: ...
    @overload
    def change_conformers(self, classutility, constclassutility) -> void: ...
    @overload
    def check_grid(self, ligand_residues: pyrosetta.rosetta.utility.vector1_core_conformation_UltraLightResidue) -> bool: ...
    @overload
    def check_grid(self, ligand_residues: pyrosetta.rosetta.utility.vector1_core_conformation_UltraLightResidue, distance: float) -> bool: ...
    @overload
    def check_grid(self, classutility, double) -> bool: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def convert_to_full_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, best_pose_count: int) -> float: ...
    @overload
    def dump_conformer(self, residue: pyrosetta.rosetta.core.conformation.UltraLightResidue, output: pyrosetta.rosetta.utility.io.ozstream) -> None: ...
    @overload
    def dump_conformer(self, constclasscore, classutility) -> void: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @overload
    def make_multi_pose_grids(self, center: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def make_multi_pose_grids(self, classnumeric) -> void: ...
    def monte_carlo(self, current: float, last: float) -> bool: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data_map: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    def print_xyz(self, vector: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def print_xyz(self, classnumeric) -> void: ...
    @overload
    def provide_citation_info(self) -> None: ...
    @overload
    def provide_citation_info(self, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def score_ligands(self, ligand_residues: pyrosetta.rosetta.utility.vector1_core_conformation_UltraLightResidue) -> float: ...
    @overload
    def score_ligands(self, classutility) -> double: ...
    def transform_ligand(self, ligand_residues: pyrosetta.rosetta.utility.vector1_core_conformation_UltraLightResidue, reference_residues: pyrosetta.rosetta.utility.vector1_core_conformation_UltraLightResidue) -> None: ...
    def translate_ligand(self, ligand_residues: pyrosetta.rosetta.utility.vector1_core_conformation_UltraLightResidue, reference_residues: pyrosetta.rosetta.utility.vector1_core_conformation_UltraLightResidue, distance: float) -> None: ...
    def weighted_center(self, residues: pyrosetta.rosetta.utility.vector1_core_conformation_UltraLightResidue) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...

class TransformEnsembleCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TransformEnsembleCreator) -> None: ...
    @overload
    def __init__(self, arg0: TransformEnsembleCreator) -> None: ...
    def assign(self) -> TransformEnsembleCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class TransformEnsemble_info:
    angle: float
    box_size: float
    chains: pyrosetta.rosetta.utility.vector1_std_string
    cycles: int
    move_distance: float
    repeats: int
    temperature: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TransformEnsemble_info) -> None: ...
    def assign(self) -> TransformEnsemble_info: ...
    def chain_ids(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def jump_ids(self, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...

class Transform_info:
    angle: float
    box_size: float
    chain: str
    cycles: int
    move_distance: float
    repeats: int
    rmsd: float
    temperature: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Transform_info) -> None: ...
    def assign(self) -> Transform_info: ...

class Translate(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, translate_info: Translate_info) -> None: ...
    @overload
    def __init__(self, arg0: Translate) -> None: ...
    @overload
    def __init__(self, arg0: Translate) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> Translate: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    @overload
    def get_chain_id(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def get_chain_id(self, constclasscore) -> unsignedlong: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data_map: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class TranslateCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TranslateCreator) -> None: ...
    @overload
    def __init__(self, arg0: TranslateCreator) -> None: ...
    def assign(self) -> TranslateCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class Translate_info:
    angstroms: float
    cycles: int
    distribution: Distribution
    force: bool
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Translate_info) -> None: ...
    def assign(self) -> Translate_info: ...
    @overload
    def chain_id(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def chain_id(self, constclasscore) -> unsignedlong: ...
    @overload
    def chain_letter(self, pose: pyrosetta.rosetta.core.pose.Pose) -> str: ...
    @overload
    def chain_letter(self, constclasscore) -> char: ...
    @overload
    def jump_id(self, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
    @overload
    def jump_id(self, constclasscore) -> unsignedlong: ...
    @overload
    def set_chain_id(self, id: int) -> None: ...
    @overload
    def set_chain_id(self, unsignedlong) -> void: ...
    @overload
    def set_chain_letter(self, str: str) -> None: ...
    @overload
    def set_chain_letter(self, conststd) -> void: ...

class UnconstrainedTorsionsMover(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self, child_mover: pyrosetta.rosetta.protocols.moves.Mover, restraints: pyrosetta.rosetta.utility.vector1_std_shared_ptr_protocols_ligand_docking_ResidueTorsionRestraints_t) -> None: ...
    @overload
    def __init__(self, arg0: UnconstrainedTorsionsMover) -> None: ...
    @overload
    def __init__(self, arg0: UnconstrainedTorsionsMover) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> UnconstrainedTorsionsMover: ...
    def get_name(self) -> str: ...

class WriteLigandMolFile(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: WriteLigandMolFile) -> None: ...
    @overload
    def __init__(self, arg0: WriteLigandMolFile) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> WriteLigandMolFile: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...

class WriteLigandMolFileCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: WriteLigandMolFileCreator) -> None: ...
    @overload
    def __init__(self, arg0: WriteLigandMolFileCreator) -> None: ...
    def assign(self) -> WriteLigandMolFileCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

@overload
def add_string_real_pair(pose: pyrosetta.rosetta.core.pose.Pose, string: str, real: float) -> None: ...
@overload
def add_string_real_pair(classcore, conststd, double) -> void: ...
@overload
def apply_rotate(mover: pyrosetta.rosetta.protocols.rigid.RigidBodyMover, pose: pyrosetta.rosetta.core.pose.Pose, center: pyrosetta.rosetta.numeric.xyzVector_double_t, jump_id: int, tag_along_chains: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
@overload
def apply_rotate(classstd, classcore, constclassnumeric, unsignedlong, classutility) -> void: ...
@overload
def check_score(ligand: Ligand_info, heavy_atom_number: int) -> bool: ...
@overload
def check_score(conststructprotocols, constunsignedlong) -> bool: ...
@overload
def constrain_ligand_torsions(pose: pyrosetta.rosetta.core.pose.Pose, stddev_degrees: float) -> None: ...
@overload
def constrain_ligand_torsions(pose: pyrosetta.rosetta.core.pose.Pose, stddev_degrees: float, constrain_all_torsions_equally: bool) -> None: ...
@overload
def constrain_ligand_torsions(classcore, double, bool) -> void: ...
@overload
def find_attach_pt(jump_id: int, interface, pose: pyrosetta.rosetta.core.pose.Pose) -> int: ...
@overload
def find_attach_pt(constunsignedlong, constclassprotocols, constclasscore) -> unsignedlong: ...
def find_peptide_attach_pt(start: int, stop: int, jump_to_attach: pyrosetta.rosetta.std.map_unsigned_long_unsigned_long) -> int: ...
def find_unconnected_residues(pose: pyrosetta.rosetta.core.pose.Pose, start: int, end: int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def frac_atoms_within(rsd1: pyrosetta.rosetta.core.conformation.Residue, rsd2: pyrosetta.rosetta.core.conformation.Residue, cutoffs: pyrosetta.rosetta.utility.vector1_double, fractions_out: pyrosetta.rosetta.utility.vector1_double) -> None: ...
@overload
def generate_unique_name() -> str: ...
@overload
def generate_unique_name(input_name: str) -> str: ...
@overload
def get_automorphic_RMSDs(test_pose: pyrosetta.rosetta.core.pose.Pose, ref_pose: pyrosetta.rosetta.core.pose.Pose, test_residue_id: int, ref_residue_ids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_automorphic_RMSDs(test_pose: pyrosetta.rosetta.core.pose.Pose, ref_pose: pyrosetta.rosetta.core.pose.Pose, test_residue_id: int, ref_residue_ids: pyrosetta.rosetta.utility.vector1_unsigned_long, prefix: str) -> pyrosetta.rosetta.std.map_std_string_double: ...
def get_distribution(distribution_str: str) -> Distribution: ...
def get_incomplete_connections(residue: pyrosetta.rosetta.core.conformation.Residue) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_interface_deltas(chain: str, after: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_interface_deltas(chain: str, after: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, prefix: str) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_interface_deltas(chain: str, after: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, prefix: str, normalization_function) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_interface_deltas(chain: str, after: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, prefix: str, normalization_function, score_in_mem: bool) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_ligand_RMSDs(chain: str, test_pose: pyrosetta.rosetta.core.pose.Pose, ref_pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_ligand_RMSDs(chain: str, test_pose: pyrosetta.rosetta.core.pose.Pose, ref_pose: pyrosetta.rosetta.core.pose.Pose, prefix: str) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_ligand_RMSDs(chain: str, test_pose: pyrosetta.rosetta.core.pose.Pose, ref_pose: pyrosetta.rosetta.core.pose.Pose, prefix: str, use_ensemble_best: bool) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_ligand_grid_scores(grid_set_prototype, jump_id: int, test_pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_ligand_grid_scores(grid_set_prototype, jump_id: int, test_pose: pyrosetta.rosetta.core.pose.Pose, prefix: str) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_ligand_grid_scores(grid_set_prototype, jump_id: int, test_pose: pyrosetta.rosetta.core.pose.Pose, prefix: str, normalization_function) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_ligand_grid_scores(grid_set_prototype, chain: str, test_pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_ligand_grid_scores(grid_set_prototype, chain: str, test_pose: pyrosetta.rosetta.core.pose.Pose, prefix: str) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_ligand_grid_scores(grid_set_prototype, chain: str, test_pose: pyrosetta.rosetta.core.pose.Pose, prefix: str, normalization_function) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_ligand_grid_scores(grid_set_prototype, residues: pyrosetta.rosetta.utility.vector1_unsigned_long, chain_label: str, test_pose: pyrosetta.rosetta.core.pose.Pose, prefix: str, normalization_function) -> pyrosetta.rosetta.std.map_std_string_double: ...
def get_ligand_seqpos(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_ligand_torsion_constraints(pose: pyrosetta.rosetta.core.pose.Pose, rsd_no: int, stddev_degrees: float, csts_out: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_scoring_constraints_Constraint_t, constrain_all_torsions_equally: bool) -> None: ...
@overload
def get_ligand_torsion_constraints(classcore, unsignedlong, double, classutility, constbool) -> void: ...
@overload
def get_ligand_travel(chain: str, test_pose: pyrosetta.rosetta.core.pose.Pose, ref_pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_ligand_travel(chain: str, test_pose: pyrosetta.rosetta.core.pose.Pose, ref_pose: pyrosetta.rosetta.core.pose.Pose, prefix: str) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_ligand_travel(chain: str, test_pose: pyrosetta.rosetta.core.pose.Pose, ref_pose: pyrosetta.rosetta.core.pose.Pose, prefix: str, use_ensemble_best: bool) -> pyrosetta.rosetta.std.map_std_string_double: ...
def get_ligand_travel_ensemble_best(test_pose: pyrosetta.rosetta.core.pose.Pose, ref_pose: pyrosetta.rosetta.core.pose.Pose, test_residue_id: int, ref_residue_ids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> float: ...
@overload
def get_multi_residue_ligand_RMSDs(test_pose: pyrosetta.rosetta.core.pose.Pose, ref_pose: pyrosetta.rosetta.core.pose.Pose, test_residue_ids: pyrosetta.rosetta.utility.vector1_unsigned_long, ref_residue_ids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_multi_residue_ligand_RMSDs(test_pose: pyrosetta.rosetta.core.pose.Pose, ref_pose: pyrosetta.rosetta.core.pose.Pose, test_residue_ids: pyrosetta.rosetta.utility.vector1_unsigned_long, ref_residue_ids: pyrosetta.rosetta.utility.vector1_unsigned_long, chain: str) -> pyrosetta.rosetta.std.map_std_string_double: ...
@overload
def get_multi_residue_ligand_RMSDs(test_pose: pyrosetta.rosetta.core.pose.Pose, ref_pose: pyrosetta.rosetta.core.pose.Pose, test_residue_ids: pyrosetta.rosetta.utility.vector1_unsigned_long, ref_residue_ids: pyrosetta.rosetta.utility.vector1_unsigned_long, chain: str, prefix: str) -> pyrosetta.rosetta.std.map_std_string_double: ...
def get_radius_of_gyration(chain: str, test_pose: pyrosetta.rosetta.core.pose.Pose, prefix: str) -> pyrosetta.rosetta.std.map_std_string_double: ...
def get_rb_atr_and_rep_scores(grid: pyrosetta.rosetta.core.grid.CartGrid_int_t, pose: pyrosetta.rosetta.core.pose.Pose, begin: int, end: int) -> tuple[int, int]: ...
@overload
def grid_rotamer_trials(grid: pyrosetta.rosetta.core.grid.CartGrid_int_t, pose: pyrosetta.rosetta.core.pose.Pose, rsd_no: int, packertask: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
@overload
def grid_rotamer_trials(grid: pyrosetta.rosetta.core.grid.CartGrid_int_t, pose: pyrosetta.rosetta.core.pose.Pose, rsd_no: int, packertask: pyrosetta.rosetta.core.pack.task.PackerTask, min_score: int) -> None: ...
def grid_rotamer_trials_atr_rep(grid: pyrosetta.rosetta.core.grid.CartGrid_int_t, pose: pyrosetta.rosetta.core.pose.Pose, rsd_no: int, packertask: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
@overload
def grid_score(grid: pyrosetta.rosetta.core.grid.CartGrid_int_t, rsd: pyrosetta.rosetta.core.conformation.Residue) -> int: ...
@overload
def grid_score(grid: pyrosetta.rosetta.core.grid.CartGrid_int_t, rsd: pyrosetta.rosetta.core.conformation.Residue, max_score: int) -> int: ...
@overload
def grid_score_atr_rep(grid: pyrosetta.rosetta.core.grid.CartGrid_int_t, rsd: pyrosetta.rosetta.core.conformation.Residue, atr_out: int, rep_out: int) -> None: ...
@overload
def grid_score_atr_rep(grid: pyrosetta.rosetta.core.grid.CartGrid_int_t, rsd: pyrosetta.rosetta.core.conformation.Residue, atr_out: int, rep_out: int, max_rep: int) -> None: ...
def grow(start: int, end: int) -> bool: ...
@overload
def has_incomplete_connections(pose: pyrosetta.rosetta.core.pose.Pose, start: int, end: int) -> bool: ...
@overload
def has_incomplete_connections(classcore, unsignedlong, constunsignedlong) -> bool: ...
@overload
def info_to_rank(vector: pyrosetta.rosetta.utility.vector1_protocols_ligand_docking_ProtLigPair_info) -> None: ...
@overload
def info_to_rank(classutility) -> void: ...
def make_atr_rep_grid(pose: pyrosetta.rosetta.core.pose.Pose, center: pyrosetta.rosetta.numeric.xyzVector_double_t) -> pyrosetta.rosetta.core.grid.CartGrid_int_t: ...
def make_atr_rep_grid_without_ligand(pose: pyrosetta.rosetta.core.pose.Pose, center: pyrosetta.rosetta.numeric.xyzVector_double_t, ligand_chain_id_to_exclude: int) -> pyrosetta.rosetta.core.grid.CartGrid_int_t: ...
def make_atr_rep_grid_without_ligands(pose: pyrosetta.rosetta.core.pose.Pose, center: pyrosetta.rosetta.numeric.xyzVector_double_t, ligand_chain_ids_to_exclude: pyrosetta.rosetta.utility.vector1_unsigned_long) -> pyrosetta.rosetta.core.grid.CartGrid_int_t: ...
@overload
def move_ligand_neighbor_to_desired_position(chains: pyrosetta.rosetta.utility.vector1_std_string, desired_position: pyrosetta.rosetta.numeric.xyzVector_double_t, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def move_ligand_neighbor_to_desired_position(constclassutility, constclassnumeric, classcore) -> void: ...
@overload
def move_ligand_neighbor_to_desired_position(chain: str, desired_position: pyrosetta.rosetta.numeric.xyzVector_double_t, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def move_ligand_neighbor_to_desired_position(conststd, constclassnumeric, classcore) -> void: ...
@overload
def move_ligand_to_desired_centroid(chain: str, desired_centroid: pyrosetta.rosetta.numeric.xyzVector_double_t, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def move_ligand_to_desired_centroid(conststd, constclassnumeric, classcore) -> void: ...
@overload
def move_ligand_to_desired_centroid(chains: pyrosetta.rosetta.utility.vector1_std_string, desired_centroid: pyrosetta.rosetta.numeric.xyzVector_double_t, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def move_ligand_to_desired_centroid(constclassutility, constclassnumeric, classcore) -> void: ...
@overload
def move_ligand_to_desired_centroid(jump_id: int, desired_centroid: pyrosetta.rosetta.numeric.xyzVector_double_t, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def move_ligand_to_desired_centroid(constunsignedlong, constclassnumeric, classcore) -> void: ...
@overload
def output_interface_deltas(score_map: pyrosetta.rosetta.std.map_std_string_double, chain: str, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, together_energies: pyrosetta.rosetta.core.scoring.EMapVector, separated_energies: pyrosetta.rosetta.core.scoring.EMapVector, residues: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t) -> None: ...
@overload
def output_interface_deltas(score_map: pyrosetta.rosetta.std.map_std_string_double, chain: str, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, together_energies: pyrosetta.rosetta.core.scoring.EMapVector, separated_energies: pyrosetta.rosetta.core.scoring.EMapVector, residues: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t, prefix: str) -> None: ...
@overload
def output_interface_deltas(score_map: pyrosetta.rosetta.std.map_std_string_double, chain: str, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, together_energies: pyrosetta.rosetta.core.scoring.EMapVector, separated_energies: pyrosetta.rosetta.core.scoring.EMapVector, residues: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t, prefix: str, normalization_function) -> None: ...
@overload
def passes_filters(pose: pyrosetta.rosetta.core.pose.Pose, start: int, end: int) -> bool: ...
@overload
def passes_filters(constclasscore, unsignedlong, constunsignedlong) -> bool: ...
def process_line(line: str) -> ProtLigPair_info: ...
@overload
def random_connection(residue: pyrosetta.rosetta.core.conformation.Residue) -> int: ...
@overload
def random_connection(classstd) -> unsignedlong: ...
def rb_grid_rotamer_trials_atr_rep(grid: pyrosetta.rosetta.core.grid.CartGrid_int_t, pose: pyrosetta.rosetta.core.pose.Pose, begin: int, end: int, packertask: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
@overload
def rb_grid_score_atr_rep(grid: pyrosetta.rosetta.core.grid.CartGrid_int_t, pose: pyrosetta.rosetta.core.pose.Pose, begin: int, end: int, atr_out: int, rep_out: int) -> None: ...
@overload
def rb_grid_score_atr_rep(grid: pyrosetta.rosetta.core.grid.CartGrid_int_t, pose: pyrosetta.rosetta.core.pose.Pose, begin: int, end: int, atr_out: int, rep_out: int, max_rep: int) -> None: ...
@overload
def reorder_with_first_non_mobile_as_root(f: pyrosetta.rosetta.core.kinematics.FoldTree, interface, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def reorder_with_first_non_mobile_as_root(classstd, constclassprotocols, classcore) -> void: ...
def restrain_ligand_nbr_atom(lig_id: int, stddev_Angstroms: float, pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
@overload
def restrict_to_protein_residues(interface, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
@overload
def restrict_to_protein_residues(classprotocols, constclasscore) -> void: ...
@overload
def rotamers_for_trials(pose: pyrosetta.rosetta.core.pose.Pose, rsd_no: int, conformers_out: pyrosetta.rosetta.utility.vector1_std_shared_ptr_core_conformation_Residue_t, packertask: pyrosetta.rosetta.core.pack.task.PackerTask) -> None: ...
@overload
def rotamers_for_trials(classcore, unsignedlong, classutility, constclasscore) -> void: ...
@overload
def select_best_poses(atdiff: pyrosetta.rosetta.core.import_pose.atom_tree_diffs.AtomTreeDiff, tags_out: pyrosetta.rosetta.std.set_std_string_t) -> None: ...
@overload
def select_best_poses(constclasscore, classstd) -> void: ...
@overload
def select_best_poses(atdiff: pyrosetta.rosetta.core.import_pose.atom_tree_diffs.AtomTreeDiff, scores_out: pyrosetta.rosetta.utility.vector1_std_pair_std_string_std_map_std_string_double_t) -> None: ...
@overload
def select_best_poses(atdiff: pyrosetta.rosetta.core.import_pose.atom_tree_diffs.AtomTreeDiff, scores_out: pyrosetta.rosetta.utility.vector1_std_pair_std_string_std_map_std_string_double_t, to_keep: float) -> None: ...
@overload
def select_best_poses(scores_in: pyrosetta.rosetta.utility.vector1_std_pair_std_string_std_map_std_string_double_t, scores_out: pyrosetta.rosetta.utility.vector1_std_pair_std_string_std_map_std_string_double_t) -> None: ...
@overload
def select_best_poses(scores_in: pyrosetta.rosetta.utility.vector1_std_pair_std_string_std_map_std_string_double_t, scores_out: pyrosetta.rosetta.utility.vector1_std_pair_std_string_std_map_std_string_double_t, to_keep: float) -> None: ...
def sort_by_binding(left_lig: ProtLigPair_info, right_lig: ProtLigPair_info) -> bool: ...
def sort_by_second(left_lig: tuple[int, float], right_lig: tuple[int, float]) -> bool: ...
def spearman(vector_exp: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_double_t, vector_rosetta: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_double_t) -> float: ...
def torsion_constraints_from_chi_rotamers(rsd_no: int, chino: int, rsdtype: pyrosetta.rosetta.core.chemical.ResidueType) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
def torsion_constraints_from_rotamers(rsd_no: int, chino: int, rsds: pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_conformation_Residue_t, stddev_degrees: float) -> pyrosetta.rosetta.core.scoring.constraints.Constraint: ...
def vector_to_rank(vector: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_double_t) -> None: ...
