import pyrosetta.rosetta.basic.datacache
import pyrosetta.rosetta.core.chemical
import pyrosetta.rosetta.core.chemical.rdkit
import pyrosetta.rosetta.core.conformation
import pyrosetta.rosetta.core.id
import pyrosetta.rosetta.core.io.silent
import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.optimization
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.core.scoring.constraints
import pyrosetta.rosetta.core.scoring.hbonds
import pyrosetta.rosetta.core.scoring.lkball
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.protocols.moves
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
import pyrosetta.rosetta.utility.tag
from typing import ClassVar, overload

OPTH_FLEXIBLE_SIDECHAINS: OptHMode
OPTH_FULL: OptHMode
OPTH_NONE: OptHMode
OPTH_NO_FLIP_HNQ: OptHMode
OPTH_REDEFINE_SIDECHAINS: OptHMode

class AtomProperties:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, donor: bool, acceptor: bool, H: bool, polarH: bool, halogen: bool, generic: bool, ambiguity: float, score: float, tag: str) -> None: ...
    @overload
    def __init__(self, arg0: AtomProperties) -> None: ...
    @overload
    def acceptor(self) -> bool: ...
    @overload
    def acceptor(self) -> bool: ...
    @overload
    def ambiguity(self) -> float: ...
    @overload
    def ambiguity(self) -> double: ...
    def assign(self) -> AtomProperties: ...
    @overload
    def donor(self) -> bool: ...
    @overload
    def donor(self) -> bool: ...
    @overload
    def generic(self) -> bool: ...
    @overload
    def generic(self) -> bool: ...
    @overload
    def match(self, other: AtomProperties, polar_scale: float, halogen_specific: bool) -> float: ...
    @overload
    def match(self, constclassprotocols, double, bool) -> double: ...
    @overload
    def polarH(self) -> bool: ...
    @overload
    def polarH(self) -> bool: ...
    @overload
    def score(self) -> float: ...
    @overload
    def score(self) -> double: ...
    @overload
    def score(self, value: float) -> None: ...
    @overload
    def score(self, double) -> void: ...
    def show(self) -> str: ...
    def tag(self) -> str: ...
    @overload
    def used_for_phore(self) -> bool: ...
    @overload
    def used_for_phore(self) -> bool: ...

class ChiInfo:
    E: float
    ligchis: pyrosetta.rosetta.utility.vector1_double
    recchis: pyrosetta.rosetta.std.map_unsigned_long_utility_vector1_double_t_std_allocator_std_pair_const_unsigned_long_utility_vector1_double_t
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ChiInfo) -> None: ...
    def assign(self) -> ChiInfo: ...

class ConstraintInfo:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, use_pharmacophore: bool) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, use_pharmacophore: bool, report_phore_info: bool) -> None: ...
    @overload
    def __init__(self, density_points: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, gridscore: GridScorer) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, gridscore: GridScorer, simple: bool) -> None: ...
    @overload
    def __init__(self, arg0: ConstraintInfo) -> None: ...
    def align_to_current_phore_match(self, pose: pyrosetta.rosetta.core.pose.Pose, recinfo: ConstraintInfo, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, marked_pairs: pyrosetta.rosetta.utility.vector1_std_pair_unsigned_long_unsigned_long_t, SrcPriorIDs: pyrosetta.rosetta.utility.vector1_unsigned_long, TgtPriorIDs: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    def assign(self) -> ConstraintInfo: ...
    def atomid(self, i: int) -> pyrosetta.rosetta.core.id.AtomID: ...
    def coord(self, i: int) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def init_from_ligand(self, pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def init_from_ligand(self, constclasscore, constclassutility) -> void: ...
    @overload
    def init_from_ligand_pharmacophore(self, pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, report_phore_info: bool) -> None: ...
    @overload
    def init_from_ligand_pharmacophore(self, constclasscore, constclassutility, bool) -> void: ...
    @overload
    def init_from_map(self, density_points: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t) -> None: ...
    @overload
    def init_from_map(self, classutility) -> void: ...
    @overload
    def init_from_receptor(self, pose: pyrosetta.rosetta.core.pose.Pose, gridscore: GridScorer, simple: bool) -> None: ...
    @overload
    def init_from_receptor(self, constclasscore, classstd, constbool) -> void: ...
    @overload
    def limit(self) -> float: ...
    @overload
    def limit(self) -> double: ...
    @overload
    def map_phores(self, receptor_phores: pyrosetta.rosetta.utility.vector1_protocols_ligand_docking_ga_ligand_dock_Pharmacophore, update: bool) -> None: ...
    @overload
    def map_phores(self, receptor_phores: pyrosetta.rosetta.utility.vector1_protocols_ligand_docking_ga_ligand_dock_Pharmacophore, update: bool, nmax: int) -> None: ...
    @overload
    def map_phores(self, constclassutility, constbool, constunsignedlong) -> void: ...
    @overload
    def n_phore_match(self) -> int: ...
    @overload
    def n_phore_match(self) -> unsignedlong: ...
    @overload
    def natoms(self) -> int: ...
    @overload
    def natoms(self) -> unsignedlong: ...
    @overload
    def pharmacophores_defined(self) -> bool: ...
    @overload
    def pharmacophores_defined(self) -> bool: ...
    def phores(self) -> pyrosetta.rosetta.utility.vector1_protocols_ligand_docking_ga_ligand_dock_Pharmacophore: ...
    @overload
    def polar_scale(self) -> float: ...
    @overload
    def polar_scale(self) -> double: ...
    def properties(self, i: int) -> AtomProperties: ...
    @overload
    def select_phore_match(self, run_index: int) -> None: ...
    @overload
    def select_phore_match(self, constunsignedlong) -> void: ...
    @overload
    def weight(self) -> float: ...
    @overload
    def weight(self) -> double: ...

class EntropyEstimator:
    @overload
    def __init__(self, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction, pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, method: str) -> None: ...
    @overload
    def __init__(self, arg0: EntropyEstimator) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def apply(self, constclasscore) -> double: ...
    def assign(self) -> EntropyEstimator: ...
    @overload
    def set_niter(self, setting: int) -> None: ...
    @overload
    def set_niter(self, unsignedlong) -> void: ...

class GADockStageParams:
    elec_scale: float
    maxiter: float
    packcycles: float
    pmut: float
    pool: int
    ramp_schedule: pyrosetta.rosetta.utility.vector1_double
    repeats: int
    rmsthreshold: float
    smoothing: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, repeats_in: int, pool_in: int, rmsthreshold_in: float, pmut_in: float, maxiter_in: float, packcycles_in: float, smoothing_in: float, ramp_schedule_in: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, arg0: GADockStageParams) -> None: ...
    def assign(self) -> GADockStageParams: ...

class GALigandDock(pyrosetta.rosetta.protocols.moves.Mover):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GALigandDock) -> None: ...
    @overload
    def __init__(self, arg0: GALigandDock) -> None: ...
    @overload
    def apply(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def apply(self, classcore) -> void: ...
    def assign(self) -> GALigandDock: ...
    def clone(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def fresh_instance(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def get_additional_output(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    def get_name(self) -> str: ...
    @staticmethod
    def mover_name() -> str: ...
    @overload
    def parse_my_tag(self, tag: pyrosetta.rosetta.utility.tag.Tag, data: pyrosetta.rosetta.basic.datacache.DataMap) -> None: ...
    @overload
    def parse_my_tag(self, classstd, classbasic) -> void: ...
    @overload
    @staticmethod
    def provide_xml_schema(xsd) -> None: ...
    @overload
    @staticmethod
    def provide_xml_schema(classutility) -> void: ...
    @overload
    def setup_params_for_runmode(self, runmode: str) -> None: ...
    @overload
    def setup_params_for_runmode(self, std) -> void: ...

class GALigandDockCreator(pyrosetta.rosetta.protocols.moves.MoverCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GALigandDockCreator) -> None: ...
    @overload
    def __init__(self, arg0: GALigandDockCreator) -> None: ...
    def assign(self) -> GALigandDockCreator: ...
    def create_mover(self) -> pyrosetta.rosetta.protocols.moves.Mover: ...
    def keyname(self) -> str: ...
    @overload
    def provide_xml_schema(self, xsd) -> None: ...
    @overload
    def provide_xml_schema(self, classutility) -> void: ...

class GAOptimizer:
    @overload
    def __init__(self, grid: GridScorer) -> None: ...
    @overload
    def __init__(self, arg0: GAOptimizer) -> None: ...
    def assign(self) -> GAOptimizer: ...
    @overload
    def set_align_reference_atom_ids(self, newval: pyrosetta.rosetta.utility.vector1_core_id_AtomID) -> None: ...
    @overload
    def set_align_reference_atom_ids(self, classutility) -> void: ...
    @overload
    def set_altcrossover(self, newval: bool) -> None: ...
    @overload
    def set_altcrossover(self, bool) -> void: ...
    @overload
    def set_favor_native(self, newval: float) -> None: ...
    @overload
    def set_favor_native(self, double) -> void: ...
    @overload
    def set_max_rot_cumulative_prob(self, newval: float) -> None: ...
    @overload
    def set_max_rot_cumulative_prob(self, double) -> void: ...
    @overload
    def set_native(self, native: LigandConformer) -> None: ...
    @overload
    def set_native(self, constclassprotocols) -> void: ...
    @overload
    def set_protocol(self, protocol_in: pyrosetta.rosetta.utility.vector1_protocols_ligand_docking_ga_ligand_dock_GADockStageParams) -> None: ...
    @overload
    def set_protocol(self, constclassutility) -> void: ...
    @overload
    def set_rot_energy_cutoff(self, newval: float) -> None: ...
    @overload
    def set_rot_energy_cutoff(self, double) -> void: ...
    @overload
    def set_single_mutation(self, newval: bool) -> None: ...
    @overload
    def set_single_mutation(self, bool) -> void: ...

class GridHash3D_protocols_ligand_docking_ga_ligand_dock_hbAcc_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GridHash3D_protocols_ligand_docking_ga_ligand_dock_hbAcc_t) -> None: ...
    @overload
    def add_point(self, info: hbAcc) -> None: ...
    @overload
    def add_point(self, structprotocols) -> void: ...
    def assign(self) -> GridHash3D_protocols_ligand_docking_ga_ligand_dock_hbAcc_t: ...
    @overload
    def npoints(self) -> int: ...
    @overload
    def npoints(self) -> int: ...
    @overload
    def set_resolution(self, reso: float) -> None: ...
    @overload
    def set_resolution(self, double) -> void: ...

class GridHash3D_protocols_ligand_docking_ga_ligand_dock_hbDon_t:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: GridHash3D_protocols_ligand_docking_ga_ligand_dock_hbDon_t) -> None: ...
    @overload
    def add_point(self, info: hbDon) -> None: ...
    @overload
    def add_point(self, structprotocols) -> void: ...
    def assign(self) -> GridHash3D_protocols_ligand_docking_ga_ligand_dock_hbDon_t: ...
    @overload
    def npoints(self) -> int: ...
    @overload
    def npoints(self) -> int: ...
    @overload
    def set_resolution(self, reso: float) -> None: ...
    @overload
    def set_resolution(self, double) -> void: ...

class GridScorer:
    @overload
    def __init__(self, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: GridScorer) -> None: ...
    def calculate_density_penalty(self, nres: int, lig: pyrosetta.rosetta.core.conformation.Residue, pose: pyrosetta.rosetta.core.pose.Pose, unpenalized_density: float) -> float: ...
    def calculate_grid(self, pose: pyrosetta.rosetta.core.pose.Pose, lig_resnos: pyrosetta.rosetta.utility.vector1_unsigned_long, movingSCs: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    def calculate_ligand_density_correlation(self, resid: int, rsd: pyrosetta.rosetta.core.conformation.Residue, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate_pocket_density_correlation(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate_pocket_density_correlation(self, constclasscore) -> double: ...
    @overload
    def calculate_pose_density_correlation(self, pose: pyrosetta.rosetta.core.pose.Pose) -> float: ...
    @overload
    def calculate_pose_density_correlation(self, constclasscore) -> double: ...
    def debug_deriv(self, pose: pyrosetta.rosetta.core.pose.Pose, lig: LigandConformer, min_map: pyrosetta.rosetta.core.optimization.MinimizerMap) -> None: ...
    @overload
    def density_score(self, lig: LigandConformer) -> float: ...
    @overload
    def density_score(self, constclassprotocols) -> double: ...
    def derivatives(self, pose: pyrosetta.rosetta.core.pose.Pose, lig: LigandConformer, min_map: pyrosetta.rosetta.core.optimization.MinimizerMap) -> None: ...
    def dof_derivative(self, pose: pyrosetta.rosetta.core.pose.Pose, min_map: pyrosetta.rosetta.core.optimization.MinimizerMap, dof_id: pyrosetta.rosetta.core.id.DOF_ID, torsion_id: pyrosetta.rosetta.core.id.TorsionID) -> float: ...
    @overload
    def get_1b_energy(self, res_i: pyrosetta.rosetta.core.conformation.Residue, lkbrinfo: pyrosetta.rosetta.core.scoring.lkball.LKB_ResidueInfo, include_bb: bool) -> ReweightableRepEnergy: ...
    @overload
    def get_1b_energy(self, res_i: pyrosetta.rosetta.core.conformation.Residue, lkbrinfo: pyrosetta.rosetta.core.scoring.lkball.LKB_ResidueInfo, include_bb: bool, soft: bool) -> ReweightableRepEnergy: ...
    @overload
    def get_1b_energy(self, res_i: pyrosetta.rosetta.core.conformation.Residue, lkbrinfo: pyrosetta.rosetta.core.scoring.lkball.LKB_ResidueInfo, include_bb: bool, soft: bool, has_density_map: bool) -> ReweightableRepEnergy: ...
    @overload
    def get_2b_energy(self, pose: pyrosetta.rosetta.core.pose.Pose, res_i: pyrosetta.rosetta.core.conformation.Residue, lkbrinfo_i: pyrosetta.rosetta.core.scoring.lkball.LKB_ResidueInfo, incl_bb_i: bool, res_j: pyrosetta.rosetta.core.conformation.Residue, lkbrinfo_j: pyrosetta.rosetta.core.scoring.lkball.LKB_ResidueInfo, incl_bb_j: bool) -> ReweightableRepEnergy: ...
    @overload
    def get_2b_energy(self, pose: pyrosetta.rosetta.core.pose.Pose, res_i: pyrosetta.rosetta.core.conformation.Residue, lkbrinfo_i: pyrosetta.rosetta.core.scoring.lkball.LKB_ResidueInfo, incl_bb_i: bool, res_j: pyrosetta.rosetta.core.conformation.Residue, lkbrinfo_j: pyrosetta.rosetta.core.scoring.lkball.LKB_ResidueInfo, incl_bb_j: bool, soft: bool) -> ReweightableRepEnergy: ...
    @overload
    def get_debug(self) -> bool: ...
    @overload
    def get_debug(self) -> bool: ...
    @overload
    def get_elec_scale(self) -> float: ...
    @overload
    def get_elec_scale(self) -> double: ...
    @overload
    def get_exact(self) -> bool: ...
    @overload
    def get_exact(self) -> bool: ...
    @overload
    def get_grid_all_atomtypes(self) -> None: ...
    @overload
    def get_grid_all_atomtypes(self) -> void: ...
    def get_ligand_com(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def get_maxRad(self) -> float: ...
    @overload
    def get_maxRad(self) -> double: ...
    @overload
    def get_maxiterminimize(self) -> bool: ...
    @overload
    def get_maxiterminimize(self) -> bool: ...
    @overload
    def get_packer_cycles(self) -> int: ...
    @overload
    def get_packer_cycles(self) -> unsignedlong: ...
    @overload
    def get_padding(self) -> float: ...
    @overload
    def get_padding(self) -> double: ...
    def get_sfxn(self) -> pyrosetta.rosetta.core.scoring.ScoreFunction: ...
    @overload
    def get_smoothing(self) -> float: ...
    @overload
    def get_smoothing(self) -> double: ...
    @overload
    def get_voxel_spacing(self) -> float: ...
    @overload
    def get_voxel_spacing(self) -> double: ...
    @overload
    def get_w_rep(self) -> float: ...
    @overload
    def get_w_rep(self) -> double: ...
    @overload
    def has_atom_type(self, atype: int) -> bool: ...
    @overload
    def has_atom_type(self, int) -> bool: ...
    @overload
    def is_point_in_grid(self, x: pyrosetta.rosetta.numeric.xyzVector_double_t) -> bool: ...
    @overload
    def is_point_in_grid(self, classnumeric) -> bool: ...
    @overload
    def is_residue_in_grid(self, res: pyrosetta.rosetta.core.conformation.Residue, angle_buffer: float, padding_buffer: float) -> bool: ...
    @overload
    def is_residue_in_grid(self, res: pyrosetta.rosetta.core.conformation.Residue, padding_buffer: float, eigval: pyrosetta.rosetta.numeric.xyzVector_double_t, eigvec: pyrosetta.rosetta.numeric.xyzMatrix_double_t) -> bool: ...
    @overload
    def minimizer_loop(self, lig: LigandConformer, minopt: pyrosetta.rosetta.core.optimization.MinimizerOptions) -> float: ...
    @overload
    def minimizer_loop(self, classprotocols, constclasscore) -> double: ...
    def optimize(self, lig: LigandConformer, ramp_schedule: pyrosetta.rosetta.utility.vector1_double, placeable_rotdb: pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_ligand_docking_ga_ligand_dock_PlaceableRotamer_t, rot_energies: RotamerPairEnergies) -> float: ...
    def packer_loop(self, lig: LigandConformer, placeable_rotdb: pyrosetta.rosetta.utility.vector1_utility_vector1_protocols_ligand_docking_ga_ligand_dock_PlaceableRotamer_t, rotamer_energies: RotamerPairEnergies) -> float: ...
    @overload
    def point_clash_energy(self, X: pyrosetta.rosetta.numeric.xyzVector_double_t) -> float: ...
    @overload
    def point_clash_energy(self, X: pyrosetta.rosetta.numeric.xyzVector_double_t, atype_in: str) -> float: ...
    @overload
    def point_clash_energy(self, X: pyrosetta.rosetta.numeric.xyzVector_double_t, atype_in: str, soft: bool) -> float: ...
    @overload
    def point_clash_energy(self, classnumeric, std, bool) -> double: ...
    @overload
    def point_energy(self, X: pyrosetta.rosetta.numeric.xyzVector_double_t) -> float: ...
    @overload
    def point_energy(self, X: pyrosetta.rosetta.numeric.xyzVector_double_t, atype_in: str) -> float: ...
    @overload
    def point_energy(self, X: pyrosetta.rosetta.numeric.xyzVector_double_t, atype_in: str, weightelec_in: float) -> float: ...
    @overload
    def point_energy(self, classnumeric, std, double) -> double: ...
    @overload
    def prepare_grid(self, pose: pyrosetta.rosetta.core.pose.Pose, lig_resnos: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def prepare_grid(self, constclasscore, constclassutility) -> void: ...
    @overload
    def score(self, lig: LigandConformer) -> float: ...
    @overload
    def score(self, lig: LigandConformer, soft: bool) -> float: ...
    @overload
    def score(self, constclassprotocols, bool) -> double: ...
    @overload
    def score(self, pose: pyrosetta.rosetta.core.pose.Pose, lig: LigandConformer) -> float: ...
    @overload
    def score(self, pose: pyrosetta.rosetta.core.pose.Pose, lig: LigandConformer, soft: bool) -> float: ...
    @overload
    def score(self, classcore, constclassprotocols, bool) -> double: ...
    @overload
    def score_init(self, lig: LigandConformer) -> float: ...
    @overload
    def score_init(self, lig: LigandConformer, soft: bool) -> float: ...
    @overload
    def score_init(self, lig: LigandConformer, soft: bool, init_dens_weight: float) -> float: ...
    @overload
    def score_init(self, constclassprotocols, bool, double) -> double: ...
    @overload
    def score_init(self, pose: pyrosetta.rosetta.core.pose.Pose, lig: LigandConformer, soft: bool) -> float: ...
    @overload
    def score_init(self, pose: pyrosetta.rosetta.core.pose.Pose, lig: LigandConformer, soft: bool, init_dens_weight: float) -> float: ...
    @overload
    def score_init(self, classcore, constclassprotocols, bool, double) -> double: ...
    @overload
    def set_bbox_padding(self, bbox_padding_in: float) -> None: ...
    @overload
    def set_bbox_padding(self, double) -> void: ...
    @overload
    def set_debug(self, debugin: bool) -> None: ...
    @overload
    def set_debug(self, bool) -> void: ...
    @overload
    def set_elec_scale(self, setting: float) -> bool: ...
    @overload
    def set_elec_scale(self, double) -> bool: ...
    @overload
    def set_exact(self, exactin: bool) -> None: ...
    @overload
    def set_exact(self, bool) -> void: ...
    @overload
    def set_force_exact_min(self, setting: bool) -> None: ...
    @overload
    def set_force_exact_min(self, bool) -> void: ...
    @overload
    def set_grid_dim_with_maxRad(self, inval: float) -> None: ...
    @overload
    def set_grid_dim_with_maxRad(self, double) -> void: ...
    @overload
    def set_hash_gridding(self, hash_gridding_in: float) -> None: ...
    @overload
    def set_hash_gridding(self, double) -> void: ...
    @overload
    def set_hash_subgridding(self, hash_subgridding_in: int) -> None: ...
    @overload
    def set_hash_subgridding(self, unsignedlong) -> void: ...
    @overload
    def set_maxiter_minimize(self, setting: int) -> None: ...
    @overload
    def set_maxiter_minimize(self, unsignedlong) -> void: ...
    @overload
    def set_out_of_bound_e(self, setting: float) -> None: ...
    @overload
    def set_out_of_bound_e(self, double) -> void: ...
    @overload
    def set_packer_cycles(self, setting: int) -> None: ...
    @overload
    def set_packer_cycles(self, unsignedlong) -> void: ...
    @overload
    def set_smoothing(self, setting: float) -> bool: ...
    @overload
    def set_smoothing(self, double) -> bool: ...
    @overload
    def set_voxel_spacing(self, voxel_spacing_in: float) -> None: ...
    @overload
    def set_voxel_spacing(self, double) -> void: ...
    @overload
    def set_w_rep(self, setting: float) -> None: ...
    @overload
    def set_w_rep(self, double) -> void: ...

class GriddedAtomTreeMultifunc(pyrosetta.rosetta.core.optimization.Multifunc):
    @overload
    def __init__(self, arg0: LigandConformer, arg1: pyrosetta.rosetta.core.pose.Pose, arg2: GridScorer, arg3: pyrosetta.rosetta.core.optimization.MinimizerMap) -> None: ...
    @overload
    def __init__(self, conf_in: LigandConformer, pose_in: pyrosetta.rosetta.core.pose.Pose, scorefxn_in: GridScorer, min_map_in: pyrosetta.rosetta.core.optimization.MinimizerMap, debug: bool) -> None: ...
    @overload
    def __init__(self, arg0: GriddedAtomTreeMultifunc) -> None: ...
    @overload
    def __init__(self, arg0: GriddedAtomTreeMultifunc) -> None: ...
    @overload
    def dfunc(self, vars: pyrosetta.rosetta.utility.vector1_double, dE_dvars: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def dfunc(self, constclassutility, classutility) -> void: ...
    def dump(self, vars: pyrosetta.rosetta.utility.vector1_double, vars2: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    def __call__(self, vars: pyrosetta.rosetta.utility.vector1_double) -> float: ...

class LigandAligner:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, use_pharmacophore: bool, movable_scs: pyrosetta.rosetta.utility.vector1_unsigned_long, faster: bool) -> None: ...
    @overload
    def __init__(self, arg0: LigandAligner) -> None: ...
    def advanced_select_points(self, pose: pyrosetta.rosetta.core.pose.Pose, ligid: int, radius: float, skeleton_threshold_const: float, neighborhood_size: int, pool_size: int) -> None: ...
    @overload
    def apply(self, lig: LigandConformer) -> None: ...
    @overload
    def apply(self, classprotocols) -> void: ...
    def assign(self) -> LigandAligner: ...
    @overload
    def estimate_nstruct_sample(self, pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, ntotal: int) -> int: ...
    @overload
    def estimate_nstruct_sample(self, constclasscore, constclassutility, constunsignedlong) -> unsignedlong: ...
    def points_to_search(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_numeric_xyzVector_double_t: ...
    @overload
    def prealigned_input(self, setting: bool) -> None: ...
    @overload
    def prealigned_input(self, bool) -> void: ...
    @overload
    def prealigned_input(self) -> bool: ...
    @overload
    def prealigned_input(self) -> bool: ...
    @overload
    def refine_input(self, setting: bool) -> None: ...
    @overload
    def refine_input(self, bool) -> void: ...
    @overload
    def sample_ring_conformers(self) -> bool: ...
    @overload
    def sample_ring_conformers(self) -> bool: ...
    @overload
    def select_points(self, pose: pyrosetta.rosetta.core.pose.Pose, ligid: int, radius: float) -> None: ...
    @overload
    def select_points(self, pose: pyrosetta.rosetta.core.pose.Pose, ligid: int, radius: float, skeleton_threshold_const: float) -> None: ...
    @overload
    def select_points(self, pose: pyrosetta.rosetta.core.pose.Pose, ligid: int, radius: float, skeleton_threshold_const: float, neighborhood_size: int) -> None: ...
    @overload
    def set_chi_step(self, chi_step_in: int) -> None: ...
    @overload
    def set_chi_step(self, unsignedlong) -> void: ...
    @overload
    def set_pharmacophore_reference(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def set_pharmacophore_reference(self, constclasscore) -> void: ...
    @overload
    def set_rot_step(self, rot_step_in: int) -> None: ...
    @overload
    def set_rot_step(self, unsignedlong) -> void: ...
    @overload
    def set_sample_ring_conformers(self, setting: bool) -> None: ...
    @overload
    def set_sample_ring_conformers(self, constbool) -> void: ...
    @overload
    def set_sf(self, sf_in: GridScorer) -> None: ...
    @overload
    def set_sf(self, classstd) -> void: ...
    @overload
    def set_target(self, tgt_in: ConstraintInfo) -> None: ...
    @overload
    def set_target(self, constclassprotocols) -> void: ...
    @overload
    def set_trans_step(self, trans_step_in: int) -> None: ...
    @overload
    def set_trans_step(self, unsignedlong) -> void: ...
    @overload
    def set_use_pharmacophore(self, setting: bool) -> None: ...
    @overload
    def set_use_pharmacophore(self, bool) -> void: ...
    @overload
    def use_pharmacophore(self) -> bool: ...
    @overload
    def use_pharmacophore(self) -> bool: ...

class LigandConformer:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, movingscs: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, movingscs: pyrosetta.rosetta.utility.vector1_unsigned_long, freeze_ligand_backbone: bool) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, movingscs: pyrosetta.rosetta.utility.vector1_unsigned_long, freeze_ligand_backbone: bool, freeze_ligand: bool) -> None: ...
    @overload
    def __init__(self, arg0: LigandConformer) -> None: ...
    def assign(self) -> LigandConformer: ...
    @overload
    def assign_ligand_trans(self, transv: pyrosetta.rosetta.numeric.xyzVector_double_t) -> None: ...
    @overload
    def assign_ligand_trans(self, classnumeric) -> void: ...
    @overload
    def defined(self) -> bool: ...
    @overload
    def defined(self) -> bool: ...
    @overload
    def density_score(self, scorein: float) -> None: ...
    @overload
    def density_score(self, double) -> void: ...
    @overload
    def density_score(self) -> float: ...
    @overload
    def density_score(self) -> double: ...
    @overload
    def dump_pose(self, pdbname: str) -> None: ...
    @overload
    def dump_pose(self, std) -> void: ...
    def generation_tag(self) -> str: ...
    @overload
    def get_jumpid(self) -> int: ...
    @overload
    def get_jumpid(self) -> unsignedlong: ...
    @overload
    def get_ligandchi(self, ichi: int) -> float: ...
    @overload
    def get_ligandchi(self, unsignedlong) -> double: ...
    def get_ligandchis(self) -> pyrosetta.rosetta.utility.vector1_double: ...
    def get_ligchi_type(self, ndx: int) -> TorsionType: ...
    def get_ligchi_types(self) -> pyrosetta.rosetta.utility.vector1_protocols_ligand_docking_ga_ligand_dock_TorsionType: ...
    def get_protein_chis(self, ires: int) -> pyrosetta.rosetta.utility.vector1_double: ...
    def get_protein_restype(self, ires: int) -> pyrosetta.rosetta.core.chemical.ResidueType: ...
    def get_ref_pose(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    def get_reference_ft(self) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
    @overload
    def has_density_map(self) -> bool: ...
    @overload
    def has_density_map(self) -> bool: ...
    @overload
    def init_params(self) -> None: ...
    @overload
    def init_params(self) -> void: ...
    def initialize(self, pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, movingscs: pyrosetta.rosetta.utility.vector1_unsigned_long, freeze_ligand_backbone: bool, freeze_ligand: bool) -> None: ...
    @overload
    def is_ligand_bb_frozen(self) -> bool: ...
    @overload
    def is_ligand_bb_frozen(self) -> bool: ...
    @overload
    def is_ligand_frozen(self) -> bool: ...
    @overload
    def is_ligand_frozen(self) -> bool: ...
    @overload
    def is_ligand_terminal(self) -> bool: ...
    @overload
    def is_ligand_terminal(self) -> bool: ...
    def ligand_ids(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def ligand_residue(self, ires: int) -> pyrosetta.rosetta.core.conformation.Residue: ...
    @overload
    def ligand_rg(self) -> float: ...
    @overload
    def ligand_rg(self) -> double: ...
    @overload
    def ligand_typename(self) -> str: ...
    @overload
    def ligand_typename(self, i: int) -> str: ...
    def ligand_xyz(self) -> pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t: ...
    def moving_scs(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def n_ligandchis(self) -> int: ...
    @overload
    def n_ligandchis(self) -> unsignedlong: ...
    @overload
    def neg_Tds(self) -> float: ...
    @overload
    def neg_Tds(self) -> double: ...
    def protein_residue(self, ires: int) -> pyrosetta.rosetta.core.conformation.Residue: ...
    def quat(self) -> pyrosetta.rosetta.numeric.Quaternion_double_t: ...
    @overload
    def randomize(self, transmax: float) -> None: ...
    @overload
    def randomize(self, double) -> void: ...
    def receptor(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    def rms(self, rmsin: float) -> None: ...
    @overload
    def rms(self, double) -> void: ...
    @overload
    def rms(self) -> float: ...
    @overload
    def rms(self) -> double: ...
    @overload
    def sample_conformation(self, transmax: float, sampler) -> None: ...
    @overload
    def sample_conformation(self, double, constclassstd) -> void: ...
    @overload
    def sample_ring_conformers(self) -> bool: ...
    @overload
    def sample_ring_conformers(self) -> bool: ...
    @overload
    def score(self, scorein: float) -> None: ...
    @overload
    def score(self, double) -> void: ...
    @overload
    def score(self) -> float: ...
    @overload
    def score(self) -> double: ...
    @overload
    def set_chiwidth(self, setting: float) -> None: ...
    @overload
    def set_chiwidth(self, double) -> void: ...
    @overload
    def set_generation_tag(self, tag: str) -> None: ...
    @overload
    def set_generation_tag(self, std) -> void: ...
    @overload
    def set_has_density_map(self, setting: bool) -> None: ...
    @overload
    def set_has_density_map(self, bool) -> void: ...
    @overload
    def set_ligandchi(self, ichi: int, value: float) -> None: ...
    @overload
    def set_ligandchi(self, unsignedlong, double) -> void: ...
    @overload
    def set_moving_scs(self, setting: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_moving_scs(self, classutility) -> void: ...
    @overload
    def set_negTds(self, inval: float) -> None: ...
    @overload
    def set_negTds(self, double) -> void: ...
    @overload
    def set_protein_chis(self, ires: int, newchis: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def set_protein_chis(self, unsignedlong, constclassutility) -> void: ...
    @overload
    def set_protein_restype(self, ires: int, restype: pyrosetta.rosetta.core.chemical.ResidueType) -> None: ...
    @overload
    def set_protein_restype(self, unsignedlong, classstd) -> void: ...
    @overload
    def set_rotwidth(self, setting: float) -> None: ...
    @overload
    def set_rotwidth(self, double) -> void: ...
    @overload
    def set_rtmutrate(self, setting: float) -> None: ...
    @overload
    def set_rtmutrate(self, double) -> void: ...
    @overload
    def set_sample_ring_conformers(self, setting: bool) -> None: ...
    @overload
    def set_sample_ring_conformers(self, bool) -> void: ...
    @overload
    def set_torsmutrate(self, setting: float) -> None: ...
    @overload
    def set_torsmutrate(self, double) -> void: ...
    @overload
    def set_transwidth(self, setting: float) -> None: ...
    @overload
    def set_transwidth(self, double) -> void: ...
    @overload
    def superimpose_to_ref_pose(self, ids: pyrosetta.rosetta.utility.vector1_core_id_AtomID) -> None: ...
    @overload
    def superimpose_to_ref_pose(self, constclassutility) -> void: ...
    @overload
    def to_minipose(self, pose: pyrosetta.rosetta.core.pose.Pose, minilig: LigandConformer) -> None: ...
    @overload
    def to_minipose(self, classstd, classprotocols) -> void: ...
    @overload
    def to_pose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def to_pose(self, classstd) -> void: ...
    def to_string(self) -> str: ...
    def trans(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def update_conf(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def update_conf(self, classstd) -> void: ...
    @overload
    def update_conf_from_minipose(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def update_conf_from_minipose(self, classstd) -> void: ...
    @overload
    def update_ligand_conf(self, pose: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    @overload
    def update_ligand_conf(self, classstd) -> void: ...
    @overload
    def update_ligchi_types(self, ligres: pyrosetta.rosetta.core.conformation.Residue) -> None: ...
    @overload
    def update_ligchi_types(self, constclasscore) -> void: ...

class MCSAligner:
    @overload
    def __init__(self, reference_pose: pyrosetta.rosetta.core.pose.Pose, reference_ligres_idx: int, options: MCSAlignerOptions) -> None: ...
    @overload
    def __init__(self, arg0: MCSAligner) -> None: ...
    def align_pose(self, template_pose: pyrosetta.rosetta.core.pose.Pose, ligand_pose: pyrosetta.rosetta.core.pose.Pose, pair_indices_map: pyrosetta.rosetta.std.map_unsigned_long_unsigned_long, template_idx: int, ligand_idx: int) -> None: ...
    @overload
    def apply(self, lig: LigandConformer) -> None: ...
    @overload
    def apply(self, classprotocols) -> void: ...
    @overload
    def set_options(self, options: MCSAlignerOptions) -> None: ...
    @overload
    def set_options(self, conststructprotocols) -> void: ...
    def set_torsion_and_align(self, template_pose: pyrosetta.rosetta.core.pose.Pose, ligand_pose: pyrosetta.rosetta.core.pose.Pose, pair_indices_map: pyrosetta.rosetta.std.map_unsigned_long_unsigned_long, template_idx: int, ligand_idx: int) -> None: ...
    def torsion_in_align(self) -> pyrosetta.rosetta.utility.vector1_bool: ...

class MCSAlignerOptions:
    perturb_rb: bool
    perturb_rb_rotation: float
    perturb_rb_translation: float
    perturb_torsion: bool
    perturb_torsion_rotation: float
    restype_to_rdmol_options: pyrosetta.rosetta.core.chemical.rdkit.RestypeToRDMolOptions
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: MCSAlignerOptions) -> None: ...
    def assign(self) -> MCSAlignerOptions: ...

class OptHMode:
    __members__: ClassVar[dict] = ...  # read-only
    OPTH_FLEXIBLE_SIDECHAINS: ClassVar[OptHMode] = ...
    OPTH_FULL: ClassVar[OptHMode] = ...
    OPTH_NONE: ClassVar[OptHMode] = ...
    OPTH_NO_FLIP_HNQ: ClassVar[OptHMode] = ...
    OPTH_REDEFINE_SIDECHAINS: ClassVar[OptHMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OutputStructureStore:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: OutputStructureStore) -> None: ...
    def assign(self) -> OutputStructureStore: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    def dH_pop(self, pose: pyrosetta.rosetta.core.pose.Pose, E: float, rms: float, complexscore: float, ligandscore: float, recscore: float, ranking_prerelax: int, ligandname: str) -> None: ...
    @overload
    def has_data(self) -> bool: ...
    @overload
    def has_data(self) -> bool: ...
    @overload
    def pop(self, pose: pyrosetta.rosetta.core.pose.Pose, E: float, rms: float, complexscore: float, ligandscore: float, recscore: float, ranking_prerelax: int, ligandname: str) -> None: ...
    @overload
    def pop(self) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    def pop(self, metric: str) -> pyrosetta.rosetta.core.pose.Pose: ...
    @overload
    def push(self, pose: pyrosetta.rosetta.core.pose.Pose, E: float) -> None: ...
    @overload
    def push(self, pose: pyrosetta.rosetta.core.pose.Pose, E: float, rms: float) -> None: ...
    @overload
    def push(self, pose: pyrosetta.rosetta.core.pose.Pose, E: float, rms: float, complexscore: float) -> None: ...
    @overload
    def push(self, pose: pyrosetta.rosetta.core.pose.Pose, E: float, rms: float, complexscore: float, ligandscore: float) -> None: ...
    @overload
    def push(self, pose: pyrosetta.rosetta.core.pose.Pose, E: float, rms: float, complexscore: float, ligandscore: float, recscore: float) -> None: ...
    @overload
    def push(self, pose: pyrosetta.rosetta.core.pose.Pose, E: float, rms: float, complexscore: float, ligandscore: float, recscore: float, ranking_prerelax: int) -> None: ...
    @overload
    def push(self, pose: pyrosetta.rosetta.core.pose.Pose, E: float, rms: float, complexscore: float, ligandscore: float, recscore: float, ranking_prerelax: int, ligandname: str) -> None: ...
    @overload
    def resize(self, n: int) -> None: ...
    @overload
    def resize(self, unsignedlong) -> void: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...

class Pharmacophore:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, atmno: pyrosetta.rosetta.utility.vector1_unsigned_long, p: pyrosetta.rosetta.utility.vector1_protocols_ligand_docking_ga_ligand_dock_AtomProperties, Dmtrx: pyrosetta.rosetta.utility.vector1_utility_vector1_double_t, coords: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t) -> None: ...
    @overload
    def __init__(self, arg0: Pharmacophore) -> None: ...
    def assign(self) -> Pharmacophore: ...
    @overload
    def atm(self, i: int) -> int: ...
    @overload
    def atm(self, unsignedlong) -> unsignedlong: ...
    def atms(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    def com(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...
    @overload
    def dist(self) -> pyrosetta.rosetta.utility.vector1_utility_vector1_double_t: ...
    @overload
    def dist(self, i: int, j: int) -> float: ...
    @overload
    def find_type_matches(self, other: Pharmacophore) -> float: ...
    @overload
    def find_type_matches(self, other: Pharmacophore, just_count: bool) -> float: ...
    @overload
    def find_type_matches(self, constclassprotocols, constbool) -> double: ...
    @overload
    def has(self, i: int) -> bool: ...
    @overload
    def has(self, unsignedlong) -> bool: ...
    def index(self) -> str: ...
    @overload
    def is_acceptor(self, i: int) -> bool: ...
    @overload
    def is_acceptor(self, unsignedlong) -> bool: ...
    @overload
    def is_close(self, Dcol: pyrosetta.rosetta.utility.vector1_double, dcut: float) -> bool: ...
    @overload
    def is_close(self, constclassutility, double) -> bool: ...
    @overload
    def is_donor(self, i: int) -> bool: ...
    @overload
    def is_donor(self, unsignedlong) -> bool: ...
    @overload
    def is_polarH(self, i: int) -> bool: ...
    @overload
    def is_polarH(self, unsignedlong) -> bool: ...
    def map_index(self) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
    @overload
    def match(self, other: Pharmacophore, map_index: pyrosetta.rosetta.utility.vector1_unsigned_long, unmatch_score: float) -> float: ...
    @overload
    def match(self, constclassprotocols, constclassutility, constdouble) -> double: ...
    def props(self) -> pyrosetta.rosetta.utility.vector1_protocols_ligand_docking_ga_ligand_dock_AtomProperties: ...
    @overload
    def set_map_index(self, map_index: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
    @overload
    def set_map_index(self, classutility) -> void: ...
    def show(self) -> str: ...
    @overload
    def size(self) -> int: ...
    @overload
    def size(self) -> unsignedlong: ...
    @overload
    def update_com(self, coords: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t) -> None: ...
    @overload
    def update_com(self, constclassutility) -> void: ...

class PlaceableRotamer:
    chis: pyrosetta.rosetta.utility.vector1_double
    lkbrinfo: pyrosetta.rosetta.core.scoring.lkball.LKB_ResidueInfo
    prob: float
    prob_accum: float
    resid: int
    restype: pyrosetta.rosetta.core.chemical.ResidueType
    rotno: int
    score: ReweightableRepEnergy
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PlaceableRotamer) -> None: ...
    def assign(self) -> PlaceableRotamer: ...

class PointScoreComparator:
    def __init__(self) -> None: ...
    def __call__(self, Pair1: tuple[pyrosetta.rosetta.numeric.xyzVector_double_t, float], Pair2: tuple[pyrosetta.rosetta.numeric.xyzVector_double_t, float]) -> bool: ...

class ReweightableRepEnergy:
    bonus_wtd_: float
    cst_wtd_: float
    elec_dens_wtd_: float
    fa_atr_wtd_: float
    fa_elec_wtd_: float
    fa_rep_: float
    fa_sol_wtd_: float
    hbond_wtd_: float
    lk_ball_wtd_: float
    oneb_wtd_: float
    penalty_wtd_: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ReweightableRepEnergy) -> None: ...
    def assign(self) -> ReweightableRepEnergy: ...
    @overload
    def reset(self) -> None: ...
    @overload
    def reset(self) -> void: ...
    @overload
    def score(self, farep_scale: float) -> float: ...
    @overload
    def score(self, double) -> float: ...

class RotamerPairEnergies:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: RotamerPairEnergies) -> None: ...
    @overload
    def add_residue(self, nrots_i: int) -> None: ...
    @overload
    def add_residue(self, unsignedlong) -> void: ...
    def assign(self) -> RotamerPairEnergies: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self) -> void: ...
    def energy1b(self, ires: int, irot: int) -> ReweightableRepEnergy: ...
    def energy2b(self, ires: int, irot: int, jres: int, jrot: int) -> ReweightableRepEnergy: ...
    def energyBG(self, ires: int, irot: int) -> ReweightableRepEnergy: ...
    @overload
    def finalize(self) -> None: ...
    @overload
    def finalize(self) -> void: ...

class StructInfo:
    E: float
    complexscore: float
    cst: pyrosetta.rosetta.core.scoring.constraints.ConstraintSet
    dH: float
    ligandname: str
    ligandscore: float
    ranking_prerelax: int
    recscore: float
    rms: float
    str: pyrosetta.rosetta.core.io.silent.SilentStruct
    @overload
    def __init__(self, arg0: StructInfo) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def assign(self) -> StructInfo: ...

class StructInfoComp:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: StructInfoComp) -> None: ...
    def assign(self) -> StructInfoComp: ...
    def __call__(self, a: StructInfo, b: StructInfo) -> bool: ...

class StructInfoCompdH:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: StructInfoCompdH) -> None: ...
    def assign(self) -> StructInfoCompdH: ...
    def __call__(self, a: StructInfo, b: StructInfo) -> bool: ...

class TorsionDistrParams:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ttype_in: str, mult_in: int) -> None: ...
    @overload
    def __init__(self, arg0: TorsionDistrParams) -> None: ...
    def add_mode(self, A: float, mu: float, sigma: float) -> None: ...
    def assign(self) -> TorsionDistrParams: ...
    def get_mode_i(self, i: int, A_out: float, mu_out: float, sigma_out: float) -> None: ...
    @overload
    def multiplicity(self) -> int: ...
    @overload
    def multiplicity(self) -> unsignedlong: ...
    @overload
    def n_mode(self) -> int: ...
    @overload
    def n_mode(self) -> unsignedlong: ...
    @overload
    def normalize(self) -> None: ...
    @overload
    def normalize(self) -> void: ...
    def sample_mode(self, A_out: float, mu_out: float, sigma_out: float) -> None: ...
    @overload
    def set_multiplicity(self, mult_in: float) -> None: ...
    @overload
    def set_multiplicity(self, double) -> void: ...
    @overload
    def set_torsion_type(self, ttype_in: str) -> None: ...
    @overload
    def set_torsion_type(self, conststd) -> void: ...
    def torsion_type(self) -> str: ...

class TorsionSampler:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TorsionSampler) -> None: ...
    def assign(self) -> TorsionSampler: ...
    def lookup_tors_distr_params(self, bn: pyrosetta.rosetta.core.chemical.BondName, br: pyrosetta.rosetta.core.chemical.BondRingness, type1: int, type2: int, type3: int, type4: int) -> TorsionDistrParams: ...
    def sample(self, bn: pyrosetta.rosetta.core.chemical.BondName, br: pyrosetta.rosetta.core.chemical.BondRingness, type1: int, type2: int, type3: int, type4: int) -> float: ...

class TorsionType:
    at1: int
    at2: int
    at3: int
    at4: int
    bn: pyrosetta.rosetta.core.chemical.BondName
    br: pyrosetta.rosetta.core.chemical.BondRingness
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TorsionType) -> None: ...
    def assign(self) -> TorsionType: ...

class atmInfo:
    atom: pyrosetta.rosetta.core.conformation.Atom
    atomWaters: pyrosetta.rosetta.utility.vector1_numeric_xyzVector_double_t
    atomicCharge: float
    nAtomWaters: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: atmInfo) -> None: ...
    def assign(self) -> atmInfo: ...
    def nbr_atom(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...

class hbAcc:
    A: pyrosetta.rosetta.numeric.xyzVector_double_t
    B: pyrosetta.rosetta.numeric.xyzVector_double_t
    B_0: pyrosetta.rosetta.numeric.xyzVector_double_t
    acctype: pyrosetta.rosetta.core.scoring.hbonds.HBAccChemType
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: hbAcc) -> None: ...
    def assign(self) -> hbAcc: ...
    def nbr_atom(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...

class hbDon:
    D: pyrosetta.rosetta.numeric.xyzVector_double_t
    H: pyrosetta.rosetta.numeric.xyzVector_double_t
    dontype: pyrosetta.rosetta.core.scoring.hbonds.HBDonChemType
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: hbDon) -> None: ...
    def assign(self) -> hbDon: ...
    def nbr_atom(self) -> pyrosetta.rosetta.numeric.xyzVector_double_t: ...

def compute_nhbonds(pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, resids: pyrosetta.rosetta.utility.vector1_unsigned_long, nhbonds_total: int, nhbonds_max1: int, include_bb: bool, hb_metric: str) -> None: ...
@overload
def constraint_relax(pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, movable_scs: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
@overload
def constraint_relax(pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, movable_scs: pyrosetta.rosetta.utility.vector1_unsigned_long, maxiter: float) -> None: ...
def count_neighbors(pose: pyrosetta.rosetta.core.pose.Pose, atomname: str, dcut: float) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def count_neighbors_on_coord(pose: pyrosetta.rosetta.core.pose.Pose, xyz1: pyrosetta.rosetta.numeric.xyzVector_double_t, atomname: str, dcut: float) -> int: ...
@overload
def count_neighbors_on_coord(constclasscore, constclassnumeric, conststd, constdouble) -> unsignedlong: ...
def crossover(l1: LigandConformer, l2: LigandConformer) -> LigandConformer: ...
def crossover_ft(l1: LigandConformer, l2: LigandConformer) -> LigandConformer: ...
def distance_fast(gene1: LigandConformer, gene2: LigandConformer) -> float: ...
def distance_internal(gene1: LigandConformer, gene2: LigandConformer) -> tuple[float, float]: ...
def distance_slow(gene1: LigandConformer, gene2: LigandConformer) -> float: ...
@overload
def get_atomic_contacting_sidechains(pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
@overload
def get_atomic_contacting_sidechains(pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, atomic_distance_cut: float) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def get_hbond_score_weighted(sf: pyrosetta.rosetta.core.scoring.ScoreFunction, database: pyrosetta.rosetta.core.scoring.hbonds.HBondDatabase, hbopt: pyrosetta.rosetta.core.scoring.hbonds.HBondOptions, hbt: pyrosetta.rosetta.core.scoring.hbonds.HBEvalTuple, D: pyrosetta.rosetta.numeric.xyzVector_double_t, H: pyrosetta.rosetta.numeric.xyzVector_double_t, A: pyrosetta.rosetta.numeric.xyzVector_double_t, B: pyrosetta.rosetta.numeric.xyzVector_double_t, B_0: pyrosetta.rosetta.numeric.xyzVector_double_t) -> float: ...
@overload
def get_ligand_jumpid(pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> int: ...
@overload
def get_ligand_jumpid(constclasscore, constclassutility) -> unsignedlong: ...
@overload
def get_ligand_resids(pose: pyrosetta.rosetta.core.pose.Pose, lig_resids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
@overload
def get_ligand_resids(constclasscore, classutility) -> void: ...
def is_hb_satisfied(sf: pyrosetta.rosetta.core.scoring.ScoreFunction, hb_database: pyrosetta.rosetta.core.scoring.hbonds.HBondDatabase, hbopt: pyrosetta.rosetta.core.scoring.hbonds.HBondOptions, acc: hbAcc, don: hbDon, maxHbdis2: float, hb_energy_cutoff: float, metric: str) -> bool: ...
def make_ligand_only_pose(pose_new: pyrosetta.rosetta.core.pose.Pose, pose: pyrosetta.rosetta.core.pose.Pose, lig_resnos: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
def mutate(l: LigandConformer) -> LigandConformer: ...
def mutate_ft(l: LigandConformer, single_mutation: bool) -> LigandConformer: ...
@overload
def perturb_ligand_rb(pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
@overload
def perturb_ligand_rb(pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, trans_step: float) -> None: ...
@overload
def perturb_ligand_rb(pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, trans_step: float, rot_step: float) -> None: ...
@overload
def perturb_ligand_torsions(pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, freeze_chi: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
@overload
def perturb_ligand_torsions(pose: pyrosetta.rosetta.core.pose.Pose, ligids: pyrosetta.rosetta.utility.vector1_unsigned_long, freeze_chi: pyrosetta.rosetta.utility.vector1_unsigned_long, chi_step: float) -> None: ...
