import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
from typing import overload

def indel_motif(aln_seq: str, motif_radius: int, aln_resi: int, pose_ss_aln: str) -> tuple[str, str]: ...
def indel_motif_seq_id(motif1: str, motif2: str) -> float: ...
def short_ss_loop_filter(ss: str, min_loop_length: int) -> str: ...
@overload
def thread_sequence_on_pose(pose: pyrosetta.rosetta.core.pose.Pose, thread_seq: str, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
@overload
def thread_sequence_on_pose(classcore, conststd, classstd) -> void: ...
