import types
from _typeshed import Incomplete
from collections import Mapping, MutableMapping

def open_compressed(filename): ...

class SilentFilePoseAccessor(Mapping):
    sdata: Incomplete
    def __init__(self, sdata) -> None: ...
    def keys(self): ...
    def __getitem__(self, tag_name): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...

class SilentFileEnergyAccessor(Mapping):
    sdata: Incomplete
    def __init__(self, sdata) -> None: ...
    def keys(self): ...
    def __getitem__(self, tag_name): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...

class SilentFileMap(MutableMapping):
    filename: Incomplete
    file_writable: bool
    sdata: Incomplete
    def __init__(self, filename=None, data=None) -> None: ...
    @property
    def tags(self): ...
    @property
    def poses(self): ...
    @property
    def energies(self): ...
    def write_file(self, filename=None, force: bool = False) -> None: ...
    def __getitem__(self, tag_name): ...
    def __setitem__(self, tag_name, structure) -> None: ...
    def __delitem__(self, tag_name) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None) -> None: ...
