import pyrosetta.rosetta.core.kinematics
import pyrosetta.rosetta.core.pack.task
import pyrosetta.rosetta.core.pose
import pyrosetta.rosetta.core.scoring
import pyrosetta.rosetta.numeric
import pyrosetta.rosetta.protocols.jd2
import pyrosetta.rosetta.std
import pyrosetta.rosetta.utility
from . import filters as filters, movers as movers
from typing import overload

class FavorNativeResidue:
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, native_residue_bonus: float) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, native_residue_bonus: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, arg0: FavorNativeResidue) -> None: ...
    def assign(self) -> FavorNativeResidue: ...

class FavorNonNativeResidue:
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, native_residue_bonus: float) -> None: ...
    @overload
    def __init__(self, pose: pyrosetta.rosetta.core.pose.Pose, native_residue_bonus: pyrosetta.rosetta.utility.vector1_double) -> None: ...
    @overload
    def __init__(self, arg0: FavorNonNativeResidue) -> None: ...
    def assign(self) -> FavorNonNativeResidue: ...

class ParserJobInputter(pyrosetta.rosetta.protocols.jd2.PDBJobInputter):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ParserJobInputter) -> None: ...
    @overload
    def __init__(self, arg0: ParserJobInputter) -> None: ...
    def assign(self) -> ParserJobInputter: ...
    @overload
    def pose_from_job(self, pose: pyrosetta.rosetta.core.pose.Pose, job: pyrosetta.rosetta.protocols.jd2.Job) -> None: ...
    @overload
    def pose_from_job(self, classcore, classstd) -> void: ...

class ParserJobInputterCreator(pyrosetta.rosetta.protocols.jd2.JobInputterCreator):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ParserJobInputterCreator) -> None: ...
    @overload
    def __init__(self, arg0: ParserJobInputterCreator) -> None: ...
    def assign(self) -> ParserJobInputterCreator: ...
    def create_JobInputter(self) -> pyrosetta.rosetta.protocols.jd2.JobInputter: ...
    def keyname(self) -> str: ...

class PatchdockReader:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PatchdockReader) -> None: ...
    def assign(self) -> PatchdockReader: ...
    @overload
    def clear_internals(self) -> None: ...
    @overload
    def clear_internals(self) -> void: ...
    @overload
    def from_entry(self, f: int) -> None: ...
    @overload
    def from_entry(self, constunsignedlong) -> void: ...
    @overload
    def from_entry(self) -> int: ...
    @overload
    def from_entry(self) -> unsignedlong: ...
    @overload
    def number_of_patchdock_entries(self) -> int: ...
    @overload
    def number_of_patchdock_entries(self) -> unsignedlong: ...
    @overload
    def patchdock_entry_num(self) -> int: ...
    @overload
    def patchdock_entry_num(self) -> unsignedlong: ...
    @overload
    def patchdock_entry_num(self, s: int) -> None: ...
    @overload
    def patchdock_entry_num(self, constunsignedlong) -> void: ...
    @overload
    def patchdock_fname(self) -> str: ...
    @overload
    def patchdock_fname(self, s: str) -> None: ...
    @overload
    def patchdock_fname(self, conststd) -> void: ...
    @overload
    def random_entry(self) -> bool: ...
    @overload
    def random_entry(self) -> bool: ...
    @overload
    def random_entry(self, b: bool) -> None: ...
    @overload
    def random_entry(self, constbool) -> void: ...
    def read_patchdock(self, input_tag: str, native_tag: str) -> None: ...
    def read_patchdock_entry(self) -> Transformation: ...
    @overload
    def read_poses(self, input_pose: pyrosetta.rosetta.core.pose.Pose, input_tag: str) -> None: ...
    @overload
    def read_poses(self, classcore, std) -> void: ...
    @overload
    def read_poses(self, input_pose: pyrosetta.rosetta.core.pose.Pose, native_pose: pyrosetta.rosetta.core.pose.Pose, input_tag: str, native_tag: str) -> None: ...
    @overload
    def to_entry(self, t: int) -> None: ...
    @overload
    def to_entry(self, constunsignedlong) -> void: ...
    @overload
    def to_entry(self) -> int: ...
    @overload
    def to_entry(self) -> unsignedlong: ...
    @overload
    def transform_pose(self, pose: pyrosetta.rosetta.core.pose.Pose, chain: int, t: Transformation) -> None: ...
    @overload
    def transform_pose(self, classcore, constunsignedlong, conststructprotocols) -> void: ...

class ReportPSSMDifferences:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ReportPSSMDifferences) -> None: ...
    def assign(self) -> ReportPSSMDifferences: ...
    def calculate(self, pose1: pyrosetta.rosetta.core.pose.Pose, pose2: pyrosetta.rosetta.core.pose.Pose, task: pyrosetta.rosetta.core.pack.task.PackerTask) -> float: ...
    @overload
    def load_pssm_data(self, native_filename: str) -> bool: ...
    @overload
    def load_pssm_data(self, conststd) -> bool: ...
    def pssm_(self) -> pyrosetta.rosetta.utility.vector1_std_pair_core_chemical_AA_utility_vector1_double_t: ...
    def res_name1(self) -> pyrosetta.rosetta.std.map_unsigned_long_std_string: ...

class ReportSequenceDifferences:
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> None: ...
    @overload
    def __init__(self, arg0: ReportSequenceDifferences) -> None: ...
    def assign(self) -> ReportSequenceDifferences: ...
    def calculate(self, pose1: pyrosetta.rosetta.core.pose.Pose, pose2: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    def get_res_energy(self, num: int) -> pyrosetta.rosetta.std.map_unsigned_long_double: ...
    @overload
    def report(self, out: pyrosetta.rosetta.std.ostream) -> None: ...
    @overload
    def report(self, std) -> void: ...
    def res_name1(self) -> pyrosetta.rosetta.std.map_unsigned_long_std_string: ...
    def res_name2(self) -> pyrosetta.rosetta.std.map_unsigned_long_std_string: ...

class Revert:
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, ddg_tolerance: float) -> None: ...
    @overload
    def __init__(self, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, ddg_tolerance: float, ddg_cycles: int) -> None: ...
    @overload
    def __init__(self, arg0: Revert) -> None: ...
    def apply(self, pose_wt: pyrosetta.rosetta.core.pose.Pose, pose_des: pyrosetta.rosetta.core.pose.Pose) -> None: ...
    def assign(self) -> Revert: ...

class Transformation:
    alpha: float
    beta: float
    gamma: float
    translation: pyrosetta.rosetta.numeric.xyzVector_double_t
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Transformation) -> None: ...
    def assign(self) -> Transformation: ...

@overload
def MinimizeInterface(pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, min_bb: pyrosetta.rosetta.utility.vector1_bool, min_sc: pyrosetta.rosetta.utility.vector1_bool, min_rb: pyrosetta.rosetta.utility.vector1_bool, optimize_foldtree: bool, target_residues: pyrosetta.rosetta.utility.vector1_unsigned_long) -> None: ...
@overload
def MinimizeInterface(pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, min_bb: pyrosetta.rosetta.utility.vector1_bool, min_sc: pyrosetta.rosetta.utility.vector1_bool, min_rb: pyrosetta.rosetta.utility.vector1_bool, optimize_foldtree: bool, target_residues: pyrosetta.rosetta.utility.vector1_unsigned_long, simultaneous_minimization: bool) -> None: ...
@overload
def SymMinimizeInterface(pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, min_bb: pyrosetta.rosetta.utility.vector1_bool, min_sc: pyrosetta.rosetta.utility.vector1_bool, min_rb: pyrosetta.rosetta.utility.vector1_bool) -> None: ...
@overload
def SymMinimizeInterface(pose: pyrosetta.rosetta.core.pose.Pose, scorefxn: pyrosetta.rosetta.core.scoring.ScoreFunction, min_bb: pyrosetta.rosetta.utility.vector1_bool, min_sc: pyrosetta.rosetta.utility.vector1_bool, min_rb: pyrosetta.rosetta.utility.vector1_bool, simultaneous_minimization: bool) -> None: ...
def best_bbcst_residues(pose: pyrosetta.rosetta.core.pose.Pose, chain: int, n_return: int) -> pyrosetta.rosetta.utility.vector1_unsigned_long: ...
def best_cutpoint(pose: pyrosetta.rosetta.core.pose.Pose, prev_u: int, prev_d: int, u: int, d: int) -> int: ...
def find_lowest_constraint_energy_residue(pose: pyrosetta.rosetta.core.pose.Pose, chain: int, resi: int, lowest_energy: float) -> None: ...
@overload
def find_nearest_residue(pose: pyrosetta.rosetta.core.pose.Pose, target_chain: int, res: int) -> int: ...
@overload
def find_nearest_residue(pose: pyrosetta.rosetta.core.pose.Pose, target_chain: int, res: int, atom: str) -> int: ...
def get_bbcsts(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_scoring_constraints_Constraint_t: ...
@overload
def hbonded(pose: pyrosetta.rosetta.core.pose.Pose, target_residue: int, binders: pyrosetta.rosetta.std.set_unsigned_long_t, bb: bool, sc: bool, energy_thres: float) -> pyrosetta.rosetta.std.list_unsigned_long_t: ...
@overload
def hbonded(pose: pyrosetta.rosetta.core.pose.Pose, target_residue: int, binders: pyrosetta.rosetta.std.set_unsigned_long_t, bb: bool, sc: bool, energy_thres: float, bb_bb: bool) -> pyrosetta.rosetta.std.list_unsigned_long_t: ...
@overload
def hbonded(pose: pyrosetta.rosetta.core.pose.Pose, target_residue: int, binders: pyrosetta.rosetta.std.set_unsigned_long_t, bb: bool, sc: bool, energy_thres: float, bb_bb: bool, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> pyrosetta.rosetta.std.list_unsigned_long_t: ...
@overload
def hbonded_atom(pose: pyrosetta.rosetta.core.pose.Pose, target_residue: int, target_atom: str, binders: pyrosetta.rosetta.std.set_unsigned_long_t, bb: bool, sc: bool, energy_thres: float) -> pyrosetta.rosetta.std.list_unsigned_long_t: ...
@overload
def hbonded_atom(pose: pyrosetta.rosetta.core.pose.Pose, target_residue: int, target_atom: str, binders: pyrosetta.rosetta.std.set_unsigned_long_t, bb: bool, sc: bool, energy_thres: float, bb_bb: bool) -> pyrosetta.rosetta.std.list_unsigned_long_t: ...
@overload
def hbonded_atom(pose: pyrosetta.rosetta.core.pose.Pose, target_residue: int, target_atom: str, binders: pyrosetta.rosetta.std.set_unsigned_long_t, bb: bool, sc: bool, energy_thres: float, bb_bb: bool, sfxn: pyrosetta.rosetta.core.scoring.ScoreFunction) -> pyrosetta.rosetta.std.list_unsigned_long_t: ...
def make_hotspot_foldtree(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
def optimal_connection_point(residue_type: str) -> str: ...
def remove_coordinate_constraints_from_pose(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.utility.vector1_std_shared_ptr_const_core_scoring_constraints_Constraint_t: ...
def star_fold_tree(pose: pyrosetta.rosetta.core.pose.Pose) -> pyrosetta.rosetta.core.kinematics.FoldTree: ...
@overload
def sum_total_residue_energy(pose: pyrosetta.rosetta.core.pose.Pose, resid: int) -> float: ...
@overload
def sum_total_residue_energy(constclasscore, constunsignedlong) -> double: ...
